"""
PIE Data Models — Auditable, traceable, deduplicable insights.
"""

import hashlib

from django.conf import settings
from django.db import models


class Insight(models.Model):
    """
    A single factual insight generated by a rule.

    Every insight stores WHY it was generated (rule + evidence + data window)
    and can be deduplicated via dedupe_key.
    """

    SEVERITY_CHOICES = [
        ("info", "Info"),
        ("positive", "Positive"),
        ("warning", "Warning"),
        ("critical", "Critical"),
    ]

    STATUS_CHOICES = [
        ("new", "New"),
        ("read", "Read"),
        ("dismissed", "Dismissed"),
    ]

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="pie_insights",
    )
    module = models.CharField(
        max_length=100,
        help_text="e.g., 'health', 'goals', 'scripture', 'journal'",
    )
    insight_type = models.CharField(
        max_length=120,
        help_text="e.g., 'weight_trend_up', 'goal_deadline_risk'",
    )
    severity = models.CharField(
        max_length=20,
        choices=SEVERITY_CHOICES,
        default="info",
    )
    title = models.CharField(max_length=180)
    message = models.TextField()

    confidence_score = models.FloatField(
        default=0.0,
        help_text="0.0 to 1.0 — only notify if >= rule threshold",
    )
    explain_why = models.TextField(
        help_text="Human explanation of why this was generated",
    )
    evidence = models.JSONField(
        default=dict,
        help_text="Structured provenance: dates, values, record ids, rule_name",
    )

    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default="new",
    )

    # Dedupe: same insight_type over same window should not duplicate
    dedupe_key = models.CharField(max_length=255, db_index=True)

    # Notification tracking
    notified_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When user was notified (None = not notified)",
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        app_label = "core"
        db_table = "core_ai_insight"
        indexes = [
            models.Index(
                fields=["user", "module", "insight_type"],
                name="idx_insight_user_mod_type",
            ),
            models.Index(
                fields=["user", "status", "-created_at"],
                name="idx_insight_user_status",
            ),
            models.Index(fields=["dedupe_key"], name="idx_insight_dedupe"),
        ]
        ordering = ["-created_at"]

    def __str__(self):
        return f"[{self.severity}] {self.title}"


def build_dedupe_key(user_id, insight_type, window_start, window_end,
                      key_record_ids=None):
    """
    Build a unique dedupe key for an insight.

    Incorporates user, type, window, and key records so the same
    situation doesn't generate duplicate insights.
    """
    parts = [
        str(user_id),
        insight_type,
        str(window_start),
        str(window_end),
    ]
    if key_record_ids:
        parts.append(",".join(str(rid) for rid in sorted(key_record_ids)))

    raw = "|".join(parts)
    return hashlib.sha256(raw.encode()).hexdigest()[:64]
