"""
PIE Insight Read Services — Engine-first reads for UI consumption.

Provides helpers for the dashboard and module home pages to read
stored intelligence without calling OpenAI. All reads are bounded
to a 48-hour freshness window to avoid showing stale insights.

Used by:
    - Dashboard: get_stored_daily_insight()
    - Module home pages: get_module_insight()
"""

import logging
from datetime import timedelta

from django.utils import timezone

logger = logging.getLogger(__name__)

# Only show insights generated in the last 48 hours
INSIGHT_FRESHNESS_HOURS = 48

# Prevent layout issues from very long insight text
MAX_INSIGHT_LENGTH = 500


def get_module_insight(user, module_name):
    """
    Read the latest PIE insight for a specific module.

    Returns the insight message text (str) or None if no fresh insight exists.
    Used by module home pages (health, journal, faith, life, purpose).
    """
    try:
        from apps.core.ai_insights.models import Insight

        from apps.core.ai_config import get_threshold

        freshness = get_threshold("insight_freshness_hours", INSIGHT_FRESHNESS_HOURS)
        cutoff = timezone.now() - timedelta(hours=freshness)

        insight = Insight.objects.filter(
            user=user,
            module=module_name,
            status='new',
            created_at__gte=cutoff,
        ).order_by('-created_at').first()

        if insight:
            return insight.message[:MAX_INSIGHT_LENGTH]
    except Exception:
        logger.debug("get_module_insight failed for module=%s", module_name)

    return None


def get_stored_daily_insight(user):
    """
    Read the best available stored insight for the dashboard tile.

    Priority order (all DB reads, no OpenAI):
        1. Cached AIInsight with valid_until in the future
        2. PIE Insight with module='dashboard' or 'global' (48h window)
        3. PIE Insight from any module (48h window)
        4. Active GuidanceItem (not dismissed, not snoozed)
        5. None — tile hides gracefully

    Returns insight text (str) or None.
    """
    now = timezone.now()
    from apps.core.ai_config import get_threshold

    freshness = get_threshold("insight_freshness_hours", INSIGHT_FRESHNESS_HOURS)
    cutoff = now - timedelta(hours=freshness)

    # 1. Cached AIInsight (previously generated by DashboardAI, may still be valid)
    try:
        from apps.ai.models import AIInsight

        cached = AIInsight.objects.filter(
            user=user,
            insight_type='daily',
            valid_until__gt=now,
        ).order_by('-created_at').first()

        if cached and cached.content:
            return cached.content[:MAX_INSIGHT_LENGTH]
    except Exception:
        logger.debug("AIInsight cache check failed")

    # 2. PIE Insight — prefer dashboard/global module first
    try:
        from apps.core.ai_insights.models import Insight

        insight = Insight.objects.filter(
            user=user,
            module__in=['dashboard', 'global'],
            status='new',
            created_at__gte=cutoff,
        ).order_by('-created_at').first()

        if not insight:
            # Fall back to any module
            insight = Insight.objects.filter(
                user=user,
                status='new',
                created_at__gte=cutoff,
            ).order_by('-created_at').first()

        if insight:
            return insight.message[:MAX_INSIGHT_LENGTH]
    except Exception:
        logger.debug("PIE insight read failed")

    # 3. Active GuidanceItem from PGE
    try:
        from apps.core.ai_guidance.models import GuidanceItem

        guidance = GuidanceItem.objects.filter(
            user=user,
            is_active=True,
            dismissed_at__isnull=True,
        ).order_by('priority', '-created_at').first()

        if guidance and guidance.message:
            return guidance.message[:MAX_INSIGHT_LENGTH]
    except Exception:
        logger.debug("GuidanceItem read failed")

    # 4. Nothing available — tile will hide
    return None
