# Generated by Django 5.2.9 on 2025-12-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyEncouragement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "scripture_reference",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Philippians 4:6-7'",
                        max_length=100,
                    ),
                ),
                ("scripture_text", models.TextField(blank=True)),
                (
                    "translation",
                    models.CharField(
                        default="ESV",
                        help_text="Bible translation (ESV, NIV, BSB)",
                        max_length=10,
                    ),
                ),
                (
                    "is_faith_specific",
                    models.BooleanField(
                        default=False,
                        help_text="Only show when Faith module is enabled",
                    ),
                ),
                (
                    "themes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Themes like 'peace', 'trust', 'gratitude', 'strength'",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        blank=True,
                        help_text="0=Monday, 6=Sunday. Null = any day",
                        null=True,
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        blank=True,
                        help_text="1=January, 12=December. Null = any month",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "daily encouragement",
                "verbose_name_plural": "daily encouragements",
            },
        ),
    ]
