# Generated by Django 5.2.9 on 2025-12-25 16:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FastingWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fasting_type",
                    models.CharField(
                        choices=[
                            ("16:8", "16:8 (16 hours fast)"),
                            ("18:6", "18:6 (18 hours fast)"),
                            ("20:4", "20:4 (20 hours fast)"),
                            ("OMAD", "OMAD (One Meal A Day)"),
                            ("24h", "24 Hour Fast"),
                            ("36h", "36 Hour Fast"),
                            ("custom", "Custom"),
                        ],
                        default="16:8",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "target_hours",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Target fasting duration in hours",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "fasting window",
                "verbose_name_plural": "fasting windows",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="GlucoseEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=1, help_text="Glucose reading", max_digits=5
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("mg/dL", "mg/dL"), ("mmol/L", "mmol/L")],
                        default="mg/dL",
                        max_length=10,
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("fasting", "Fasting"),
                            ("before_meal", "Before Meal"),
                            ("after_meal", "After Meal (2 hours)"),
                            ("bedtime", "Bedtime"),
                            ("random", "Random"),
                        ],
                        default="fasting",
                        max_length=20,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "glucose entry",
                "verbose_name_plural": "glucose entries",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="HeartRateEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("bpm", models.PositiveIntegerField(help_text="Beats per minute")),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("resting", "Resting"),
                            ("morning", "Morning (upon waking)"),
                            ("active", "Active / Exercise"),
                            ("post_exercise", "Post-Exercise"),
                            ("stressed", "Stressed"),
                            ("relaxed", "Relaxed"),
                            ("other", "Other"),
                        ],
                        default="resting",
                        max_length=20,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "heart rate entry",
                "verbose_name_plural": "heart rate entries",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="WeightEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=1, help_text="Weight value", max_digits=5
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("lb", "Pounds"), ("kg", "Kilograms")],
                        default="lb",
                        max_length=2,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "weight entry",
                "verbose_name_plural": "weight entries",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
