# Generated by Django 5.2.9 on 2025-12-27 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("resistance", "Resistance Training"),
                            ("cardio", "Cardio"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "muscle_group",
                    models.CharField(
                        blank=True,
                        help_text="Primary muscle group (for resistance exercises)",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "exercise",
                "verbose_name_plural": "exercises",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workout_instances",
                        to="health.exercise",
                    ),
                ),
            ],
            options={
                "verbose_name": "workout exercise",
                "verbose_name_plural": "workout exercises",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ExerciseSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set_number", models.PositiveIntegerField()),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Weight in pounds",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("reps", models.PositiveIntegerField(blank=True, null=True)),
                ("is_warmup", models.BooleanField(default=False)),
                (
                    "is_pr",
                    models.BooleanField(
                        default=False, help_text="Personal record for this exercise"
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=100)),
                (
                    "workout_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="health.workoutexercise",
                    ),
                ),
            ],
            options={
                "verbose_name": "exercise set",
                "verbose_name_plural": "exercise sets",
                "ordering": ["set_number"],
            },
        ),
        migrations.CreateModel(
            name="CardioDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Duration in minutes", null=True
                    ),
                ),
                (
                    "distance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Distance in miles",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "intensity",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("calories_burned", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "avg_heart_rate",
                    models.PositiveIntegerField(
                        blank=True, help_text="Average heart rate in BPM", null=True
                    ),
                ),
                (
                    "workout_exercise",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cardio_details",
                        to="health.workoutexercise",
                    ),
                ),
            ],
            options={
                "verbose_name": "cardio details",
                "verbose_name_plural": "cardio details",
            },
        ),
        migrations.CreateModel(
            name="WorkoutSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField()),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional name like 'Push Day' or 'Morning Run'",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total workout duration in minutes",
                        null=True,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "workout session",
                "verbose_name_plural": "workout sessions",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="workoutexercise",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workout_exercises",
                to="health.workoutsession",
            ),
        ),
        migrations.CreateModel(
            name="PersonalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=1, help_text="Weight in pounds", max_digits=6
                    ),
                ),
                ("reps", models.PositiveIntegerField()),
                ("achieved_date", models.DateField()),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_records",
                        to="health.exercise",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workout_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="personal_records",
                        to="health.workoutsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "personal record",
                "verbose_name_plural": "personal records",
                "ordering": ["-achieved_date"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Template name like 'Push Day' or 'Leg Day'",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "workout template",
                "verbose_name_plural": "workout templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TemplateExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "default_sets",
                    models.PositiveIntegerField(
                        default=3, help_text="Default number of sets for this exercise"
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_instances",
                        to="health.exercise",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_exercises",
                        to="health.workouttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "template exercise",
                "verbose_name_plural": "template exercises",
                "ordering": ["order"],
            },
        ),
    ]
