# Generated by Django 5.2.9 on 2025-12-28 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0002_add_fitness_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Medicine name (brand or generic)", max_length=200
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        blank=True,
                        help_text="What this medicine is for (e.g., 'blood pressure', 'allergies')",
                        max_length=500,
                    ),
                ),
                (
                    "dose",
                    models.CharField(
                        help_text="Dose amount (e.g., '500mg', '1 tablet', '2 puffs')",
                        max_length=100,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("twice_daily", "Twice Daily"),
                            ("three_daily", "Three Times Daily"),
                            ("four_daily", "Four Times Daily"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Every Two Weeks"),
                            ("monthly", "Monthly"),
                            ("as_needed", "As Needed (PRN)"),
                            ("custom", "Custom Schedule"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                (
                    "is_prn",
                    models.BooleanField(
                        default=False,
                        help_text="Take as-needed (PRN) rather than on a schedule",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="When you started taking this medicine"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Expected end date (optional)", null=True
                    ),
                ),
                (
                    "medicine_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                        ],
                        default="active",
                        help_text="Current status of this medicine regimen",
                        max_length=20,
                    ),
                ),
                (
                    "paused_at",
                    models.DateTimeField(
                        blank=True, help_text="When this medicine was paused", null=True
                    ),
                ),
                (
                    "paused_reason",
                    models.CharField(
                        blank=True,
                        help_text="Reason for pausing this medicine",
                        max_length=500,
                    ),
                ),
                (
                    "current_supply",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Current number of doses remaining",
                        null=True,
                    ),
                ),
                (
                    "refill_threshold",
                    models.PositiveIntegerField(
                        default=7, help_text="Alert when supply drops to this many days"
                    ),
                ),
                (
                    "prescribing_doctor",
                    models.CharField(
                        blank=True,
                        help_text="Doctor who prescribed this medicine",
                        max_length=200,
                    ),
                ),
                (
                    "pharmacy",
                    models.CharField(
                        blank=True,
                        help_text="Pharmacy where you fill this prescription",
                        max_length=200,
                    ),
                ),
                (
                    "rx_number",
                    models.CharField(
                        blank=True, help_text="Prescription/Rx number", max_length=50
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Special instructions (e.g., 'take with food', 'avoid grapefruit')",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Personal notes about this medicine"
                    ),
                ),
                (
                    "grace_period_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Minutes after scheduled time before marking as overdue",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "medicine",
                "verbose_name_plural": "medicines",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MedicineSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheduled_time",
                    models.TimeField(help_text="Time of day to take this dose"),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Optional label like 'morning', 'bedtime', 'with dinner'",
                        max_length=50,
                    ),
                ),
                (
                    "days_of_week",
                    models.CharField(
                        default="0,1,2,3,4,5,6",
                        help_text="Days to take this dose (0=Mon, 6=Sun)",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this schedule currently active?"
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="health.medicine",
                    ),
                ),
            ],
            options={
                "verbose_name": "medicine schedule",
                "verbose_name_plural": "medicine schedules",
                "ordering": ["scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="MedicineLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "scheduled_date",
                    models.DateField(help_text="Date this dose was scheduled for"),
                ),
                (
                    "scheduled_time",
                    models.TimeField(
                        blank=True,
                        help_text="Time this dose was scheduled for",
                        null=True,
                    ),
                ),
                (
                    "taken_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the medicine was actually taken",
                        null=True,
                    ),
                ),
                (
                    "log_status",
                    models.CharField(
                        choices=[
                            ("taken", "Taken"),
                            ("missed", "Missed"),
                            ("skipped", "Skipped"),
                            ("late", "Taken Late"),
                        ],
                        default="taken",
                        max_length=10,
                    ),
                ),
                (
                    "is_prn_dose",
                    models.BooleanField(
                        default=False, help_text="Was this an as-needed (PRN) dose?"
                    ),
                ),
                (
                    "prn_reason",
                    models.CharField(
                        blank=True,
                        help_text="Reason for taking PRN dose (e.g., 'headache', 'anxiety')",
                        max_length=500,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about this dose (side effects, observations, etc.)",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="health.medicine",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which scheduled dose this log is for",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="health.medicineschedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "medicine log",
                "verbose_name_plural": "medicine logs",
                "ordering": ["-scheduled_date", "-scheduled_time"],
            },
        ),
    ]
