# Generated by Django 5.2.9 on 2025-12-28 14:42

from django.db import migrations


def fix_empty_days(apps, schema_editor):
    """
    Fix any MedicineSchedule records with empty days_of_week.
    Set them to all days (0,1,2,3,4,5,6).
    """
    MedicineSchedule = apps.get_model("health", "MedicineSchedule")
    updated = MedicineSchedule.objects.filter(days_of_week="").update(
        days_of_week="0,1,2,3,4,5,6"
    )
    if updated:
        print(f"Fixed {updated} schedules with empty days_of_week")


def reverse_fix(apps, schema_editor):
    # No reverse needed - we don't want to re-break the data
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0003_add_medicine_models"),
    ]

    operations = [
        migrations.RunPython(fix_empty_days, reverse_fix),
    ]
