# Generated by Django 5.2.9 on 2025-12-28 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0003_add_medicine_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("serving_size", models.DecimalField(decimal_places=2, max_digits=8)),
                ("serving_unit", models.CharField(max_length=50)),
                ("calories", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "protein_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "carbohydrates_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "fiber_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "sugar_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "fat_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "saturated_fat_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "sodium_mg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("is_recipe", models.BooleanField(default=False)),
                (
                    "recipe_ingredients",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {food_id, quantity, unit} for recipe ingredients",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "custom food",
                "verbose_name_plural": "custom foods",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("brand", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("barcode", models.CharField(blank=True, db_index=True, max_length=50)),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("usda", "USDA Database"),
                            ("barcode", "Barcode Scan"),
                            ("ai", "AI Recognition"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        blank=True,
                        help_text="USDA ID, API reference, etc.",
                        max_length=200,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("serving_size", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "serving_unit",
                    models.CharField(
                        help_text="e.g., grams, oz, cups, pieces", max_length=50
                    ),
                ),
                (
                    "servings_per_container",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("calories", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "protein_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "carbohydrates_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "fiber_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "sugar_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "fat_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "saturated_fat_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "unsaturated_fat_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "trans_fat_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "sodium_mg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "cholesterol_mg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "potassium_mg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "calcium_mg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "iron_mg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "vitamin_a_iu",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "vitamin_c_mg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "vitamin_d_iu",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "vitamin_b12_mcg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("is_vegan", models.BooleanField(default=False)),
                ("is_vegetarian", models.BooleanField(default=False)),
                ("is_keto_friendly", models.BooleanField(default=False)),
                ("is_gluten_free", models.BooleanField(default=False)),
                ("is_dairy_free", models.BooleanField(default=False)),
                ("is_nut_free", models.BooleanField(default=False)),
                ("is_low_sodium", models.BooleanField(default=False)),
                ("is_low_carb", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "food item",
                "verbose_name_plural": "food items",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["barcode"], name="health_food_barcode_cee3d3_idx"
                    ),
                    models.Index(fields=["name"], name="health_food_name_032bcb_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="NutritionGoals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "daily_calorie_target",
                    models.PositiveIntegerField(
                        blank=True, help_text="Daily calorie goal", null=True
                    ),
                ),
                (
                    "daily_protein_target_g",
                    models.PositiveIntegerField(
                        blank=True, help_text="Daily protein goal in grams", null=True
                    ),
                ),
                (
                    "daily_carb_target_g",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Daily carbohydrate goal in grams",
                        null=True,
                    ),
                ),
                (
                    "daily_fat_target_g",
                    models.PositiveIntegerField(
                        blank=True, help_text="Daily fat goal in grams", null=True
                    ),
                ),
                (
                    "daily_fiber_target_g",
                    models.PositiveIntegerField(
                        blank=True, help_text="Daily fiber goal in grams", null=True
                    ),
                ),
                (
                    "daily_sodium_limit_mg",
                    models.PositiveIntegerField(
                        blank=True, help_text="Maximum daily sodium in mg", null=True
                    ),
                ),
                (
                    "daily_sugar_limit_g",
                    models.PositiveIntegerField(
                        blank=True, help_text="Maximum daily sugar in grams", null=True
                    ),
                ),
                (
                    "dietary_preferences",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="e.g., ['vegan', 'gluten_free']",
                    ),
                ),
                (
                    "allergies",
                    models.JSONField(
                        blank=True, default=list, help_text="e.g., ['nuts', 'dairy']"
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(help_text="When these goals became active"),
                ),
                (
                    "effective_until",
                    models.DateField(
                        blank=True,
                        help_text="When these goals end (null = still active)",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "nutrition goals",
                "verbose_name_plural": "nutrition goals",
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="DailyNutritionSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("summary_date", models.DateField()),
                (
                    "total_calories",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_protein_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_carbohydrates_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_fiber_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_sugar_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_fat_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_saturated_fat_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_sodium_mg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("breakfast_count", models.PositiveSmallIntegerField(default=0)),
                ("lunch_count", models.PositiveSmallIntegerField(default=0)),
                ("dinner_count", models.PositiveSmallIntegerField(default=0)),
                ("snack_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "protein_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "carb_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "fat_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("calculation_version", models.PositiveSmallIntegerField(default=1)),
                ("last_recalculated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "daily nutrition summary",
                "verbose_name_plural": "daily nutrition summaries",
                "ordering": ["-summary_date"],
                "unique_together": {("user", "summary_date")},
            },
        ),
        migrations.CreateModel(
            name="FoodEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("food_name", models.CharField(max_length=300)),
                ("food_brand", models.CharField(blank=True, max_length=200)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="Number of servings",
                        max_digits=8,
                    ),
                ),
                ("serving_size", models.DecimalField(decimal_places=2, max_digits=8)),
                ("serving_unit", models.CharField(max_length=50)),
                (
                    "total_calories",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_protein_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_carbohydrates_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_fiber_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_sugar_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_fat_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_saturated_fat_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_sodium_mg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_cholesterol_mg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_potassium_mg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("logged_date", models.DateField()),
                ("logged_time", models.TimeField(blank=True, null=True)),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snack", "Snack"),
                        ],
                        default="snack",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("home", "Home"),
                            ("restaurant", "Restaurant"),
                            ("work", "Work"),
                            ("travel", "Travel"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "eating_pace",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rushed", "Rushed"),
                            ("normal", "Normal"),
                            ("slow", "Slow/Mindful"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "hunger_level_before",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Hunger level before eating (1-5)",
                        null=True,
                    ),
                ),
                (
                    "fullness_level_after",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Fullness level after eating (1-5)",
                        null=True,
                    ),
                ),
                (
                    "mood_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags like 'stressed', 'happy', 'tired'",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "entry_source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("barcode", "Barcode Scan"),
                            ("camera", "Camera Recognition"),
                            ("voice", "Voice Input"),
                            ("quick_add", "Quick Add"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "ai_confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="AI confidence score for camera/voice entries",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "custom_food",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entries",
                        to="health.customfood",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "food_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entries",
                        to="health.fooditem",
                    ),
                ),
            ],
            options={
                "verbose_name": "food entry",
                "verbose_name_plural": "food entries",
                "ordering": ["-logged_date", "-logged_time", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "logged_date"],
                        name="health_food_user_id_cba0a2_idx",
                    ),
                    models.Index(
                        fields=["logged_date", "meal_type"],
                        name="health_food_logged__7a01ae_idx",
                    ),
                ],
            },
        ),
    ]
