# Generated by Django 5.2.9 on 2025-12-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0004_food_tracking"),
        ("health", "0005_add_created_via_field"),
    ]

    operations = []
