# Generated by Django 5.2.9 on 2025-12-28 16:40
# Add created_via field to food tracking models

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0006_merge_0004_food_tracking_0005_add_created_via_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="customfood",
            name="created_via",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Entry"),
                    ("ai_camera", "AI Camera Scan"),
                    ("import", "Data Import"),
                    ("api", "API"),
                ],
                default="manual",
                help_text="How this entry was created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="foodentry",
            name="created_via",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Entry"),
                    ("ai_camera", "AI Camera Scan"),
                    ("import", "Data Import"),
                    ("api", "API"),
                ],
                default="manual",
                help_text="How this entry was created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dailynutritionsummary",
            name="created_via",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Entry"),
                    ("ai_camera", "AI Camera Scan"),
                    ("import", "Data Import"),
                    ("api", "API"),
                ],
                default="manual",
                help_text="How this entry was created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="nutritiongoals",
            name="created_via",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Entry"),
                    ("ai_camera", "AI Camera Scan"),
                    ("import", "Data Import"),
                    ("api", "API"),
                ],
                default="manual",
                help_text="How this entry was created",
                max_length=20,
            ),
        ),
    ]
