# Generated by Django 5.2.9 on 2025-12-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0007_add_created_via_to_food_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodentry",
            name="total_calories",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
