# Generated by Django 5.2.9 on 2025-12-29 20:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0008_make_total_calories_default_zero"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="refill_requested",
            field=models.BooleanField(
                default=False,
                help_text="Has a refill been requested for this medicine?",
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="refill_requested_at",
            field=models.DateTimeField(
                blank=True, help_text="When the refill was requested", null=True
            ),
        ),
        migrations.CreateModel(
            name="BloodOxygenEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_via",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("ai_camera", "AI Camera Scan"),
                            ("import", "Data Import"),
                            ("api", "API"),
                        ],
                        default="manual",
                        help_text="How this entry was created",
                        max_length=20,
                    ),
                ),
                (
                    "spo2",
                    models.PositiveIntegerField(
                        help_text="Blood oxygen saturation percentage (SpO2)"
                    ),
                ),
                (
                    "pulse",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Pulse rate (if measured with SpO2)",
                        null=True,
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("resting", "Resting"),
                            ("morning", "Morning (upon waking)"),
                            ("active", "Active / Exercise"),
                            ("post_exercise", "Post-Exercise"),
                            ("sleeping", "During Sleep"),
                            ("illness", "While Ill"),
                            ("other", "Other"),
                        ],
                        default="resting",
                        max_length=20,
                    ),
                ),
                (
                    "measurement_method",
                    models.CharField(
                        choices=[
                            ("finger", "Finger Pulse Oximeter"),
                            ("wrist", "Wrist Device"),
                            ("ear", "Ear Clip"),
                            ("other", "Other"),
                        ],
                        default="finger",
                        max_length=20,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "blood oxygen entry",
                "verbose_name_plural": "blood oxygen entries",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="BloodPressureEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_via",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("ai_camera", "AI Camera Scan"),
                            ("import", "Data Import"),
                            ("api", "API"),
                        ],
                        default="manual",
                        help_text="How this entry was created",
                        max_length=20,
                    ),
                ),
                (
                    "systolic",
                    models.PositiveIntegerField(
                        help_text="Systolic pressure (top number) in mmHg"
                    ),
                ),
                (
                    "diastolic",
                    models.PositiveIntegerField(
                        help_text="Diastolic pressure (bottom number) in mmHg"
                    ),
                ),
                (
                    "pulse",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Pulse rate (if measured with BP)",
                        null=True,
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("resting", "Resting"),
                            ("morning", "Morning (upon waking)"),
                            ("evening", "Evening"),
                            ("post_exercise", "Post-Exercise"),
                            ("stressed", "Stressed"),
                            ("relaxed", "Relaxed"),
                            ("other", "Other"),
                        ],
                        default="resting",
                        max_length=20,
                    ),
                ),
                (
                    "arm",
                    models.CharField(
                        choices=[("left", "Left Arm"), ("right", "Right Arm")],
                        default="left",
                        max_length=10,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("sitting", "Sitting"),
                            ("standing", "Standing"),
                            ("lying", "Lying Down"),
                        ],
                        default="sitting",
                        max_length=10,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "blood pressure entry",
                "verbose_name_plural": "blood pressure entries",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
