# Generated by Django 5.2.9 on 2025-12-30 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0009_add_blood_pressure_oxygen_and_refill_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_via",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("ai_camera", "AI Camera Scan"),
                            ("import", "Data Import"),
                            ("api", "API"),
                        ],
                        default="manual",
                        help_text="How this entry was created",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Provider or practice name", max_length=200
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        choices=[
                            ("primary_care", "Primary Care / Family Medicine"),
                            ("internal_medicine", "Internal Medicine"),
                            ("pediatrics", "Pediatrics"),
                            ("obgyn", "OB/GYN"),
                            ("cardiology", "Cardiology"),
                            ("dermatology", "Dermatology"),
                            ("endocrinology", "Endocrinology"),
                            ("gastroenterology", "Gastroenterology"),
                            ("neurology", "Neurology"),
                            ("oncology", "Oncology"),
                            ("ophthalmology", "Ophthalmology"),
                            ("orthopedics", "Orthopedics"),
                            ("psychiatry", "Psychiatry"),
                            ("pulmonology", "Pulmonology"),
                            ("rheumatology", "Rheumatology"),
                            ("urology", "Urology"),
                            ("dentist", "Dentist"),
                            ("optometrist", "Optometrist"),
                            ("chiropractor", "Chiropractor"),
                            ("physical_therapy", "Physical Therapy"),
                            ("mental_health", "Mental Health / Therapist"),
                            ("pharmacy", "Pharmacy"),
                            ("urgent_care", "Urgent Care"),
                            ("hospital", "Hospital"),
                            ("lab", "Laboratory"),
                            ("imaging", "Imaging / Radiology"),
                            ("other", "Other"),
                        ],
                        default="primary_care",
                        max_length=50,
                    ),
                ),
                (
                    "credentials",
                    models.CharField(
                        blank=True,
                        help_text="e.g., MD, DO, DDS, PhD, PA-C, NP",
                        max_length=100,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Primary phone number", max_length=20
                    ),
                ),
                (
                    "phone_alt",
                    models.CharField(
                        blank=True,
                        help_text="Alternate phone (scheduling, etc.)",
                        max_length=20,
                    ),
                ),
                ("fax", models.CharField(blank=True, max_length=20)),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Office email address", max_length=254
                    ),
                ),
                ("website", models.URLField(blank=True, help_text="Practice website")),
                ("address_line1", models.CharField(blank=True, max_length=200)),
                ("address_line2", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "country",
                    models.CharField(blank=True, default="USA", max_length=100),
                ),
                (
                    "portal_url",
                    models.URLField(blank=True, help_text="Link to patient portal"),
                ),
                (
                    "portal_username",
                    models.CharField(
                        blank=True,
                        help_text="Username for patient portal (stored locally only)",
                        max_length=100,
                    ),
                ),
                (
                    "npi_number",
                    models.CharField(
                        blank=True,
                        help_text="National Provider Identifier (10 digits)",
                        max_length=20,
                    ),
                ),
                (
                    "accepts_insurance",
                    models.BooleanField(
                        default=True, help_text="Does this provider accept insurance?"
                    ),
                ),
                (
                    "insurance_notes",
                    models.TextField(
                        blank=True, help_text="Notes about accepted insurance plans"
                    ),
                ),
                (
                    "office_hours",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Office hours by day: {'monday': '8am-5pm', ...}",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Is this your primary care provider?"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Personal notes about this provider"
                    ),
                ),
                (
                    "ai_lookup_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Was AI used to populate provider info?",
                    ),
                ),
                (
                    "ai_lookup_at",
                    models.DateTimeField(
                        blank=True, help_text="When AI lookup was performed", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "medical provider",
                "verbose_name_plural": "medical providers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProviderStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_via",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("ai_camera", "AI Camera Scan"),
                            ("import", "Data Import"),
                            ("api", "API"),
                        ],
                        default="manual",
                        help_text="How this entry was created",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Staff member's name", max_length=200),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("physician_assistant", "Physician Assistant (PA)"),
                            ("nurse_practitioner", "Nurse Practitioner (NP)"),
                            ("registered_nurse", "Registered Nurse (RN)"),
                            ("licensed_nurse", "Licensed Practical Nurse (LPN)"),
                            ("medical_assistant", "Medical Assistant (MA)"),
                            ("front_desk", "Front Desk / Receptionist"),
                            ("billing", "Billing Specialist"),
                            ("scheduler", "Scheduler / Coordinator"),
                            ("lab_tech", "Lab Technician"),
                            ("xray_tech", "X-Ray Technician"),
                            ("pharmacist", "Pharmacist"),
                            ("pharmacy_tech", "Pharmacy Technician"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Job title or role description",
                        max_length=100,
                    ),
                ),
                (
                    "phone_extension",
                    models.CharField(
                        blank=True,
                        help_text="Phone extension if applicable",
                        max_length=20,
                    ),
                ),
                (
                    "direct_phone",
                    models.CharField(
                        blank=True,
                        help_text="Direct phone number if different from office",
                        max_length=20,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Direct email if available",
                        max_length=254,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about this staff member"
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="health.medicalprovider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "provider staff",
                "verbose_name_plural": "provider staff",
                "ordering": ["provider", "name"],
            },
        ),
    ]
