# Generated by Django 5.2.9 on 2026-01-01 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0011_fix_medicine_log_status_timezone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DexcomCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField(blank=True)),
                ("token_expiry", models.DateTimeField(blank=True, null=True)),
                ("dexcom_user_id", models.CharField(blank=True, max_length=255)),
                (
                    "sync_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable automatic glucose sync"
                    ),
                ),
                (
                    "days_to_sync",
                    models.PositiveIntegerField(
                        default=7, help_text="Days of glucose history to sync"
                    ),
                ),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("last_sync_status", models.CharField(blank=True, max_length=50)),
                ("last_sync_message", models.TextField(blank=True)),
                ("last_sync_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dexcom Credential",
                "verbose_name_plural": "Dexcom Credentials",
            },
        ),
        migrations.AddField(
            model_name="glucoseentry",
            name="dexcom_record_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Dexcom recordId for sync tracking",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="glucoseentry",
            name="display_device",
            field=models.CharField(
                blank=True,
                help_text="Device type (receiver, iOS, android)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="glucoseentry",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Entry"),
                    ("dexcom", "Dexcom CGM"),
                    ("imported", "Imported"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="glucoseentry",
            name="trend",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "N/A"),
                    ("doubleUp", "Rising Rapidly"),
                    ("singleUp", "Rising"),
                    ("fortyFiveUp", "Rising Slowly"),
                    ("flat", "Stable"),
                    ("fortyFiveDown", "Falling Slowly"),
                    ("singleDown", "Falling"),
                    ("doubleDown", "Falling Rapidly"),
                    ("none", "None"),
                    ("notComputable", "Not Computable"),
                    ("rateOutOfRange", "Rate Out of Range"),
                ],
                help_text="Glucose trend direction from CGM",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="glucoseentry",
            name="trend_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Rate of change in mg/dL/min",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="glucoseentry",
            name="context",
            field=models.CharField(
                choices=[
                    ("fasting", "Fasting"),
                    ("before_meal", "Before Meal"),
                    ("after_meal", "After Meal (2 hours)"),
                    ("bedtime", "Bedtime"),
                    ("random", "Random"),
                    ("cgm", "CGM Reading"),
                ],
                default="fasting",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="glucoseentry",
            index=models.Index(
                fields=["user", "dexcom_record_id"],
                name="health_gluc_user_id_744eff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="glucoseentry",
            index=models.Index(
                fields=["user", "source", "recorded_at"],
                name="health_gluc_user_id_0ea5c4_idx",
            ),
        ),
        migrations.AddField(
            model_name="dexcomcredential",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dexcom_credential",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
