# Generated by Django 5.2.10 on 2026-01-10 11:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0015_sync_latest_workout_to_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StepsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('count', models.PositiveIntegerField(help_text='Number of steps')),
                ('logged_date', models.DateField(help_text='Date the steps were logged for')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this entry was recorded')),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('apple_health', 'Apple Health'), ('google_fit', 'Google Fit'), ('fitbit', 'Fitbit'), ('garmin', 'Garmin'), ('samsung_health', 'Samsung Health'), ('other', 'Other App/Device')], default='manual', max_length=20)),
                ('sync_id', models.CharField(blank=True, db_index=True, help_text='External ID from synced source to prevent duplicates', max_length=100)),
                ('goal', models.PositiveIntegerField(blank=True, help_text='Daily step goal (optional)', null=True)),
                ('distance_miles', models.DecimalField(blank=True, decimal_places=2, help_text='Distance in miles (if available)', max_digits=6, null=True)),
                ('calories_burned', models.PositiveIntegerField(blank=True, help_text='Estimated calories burned (if available)', null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'steps entry',
                'verbose_name_plural': 'steps entries',
                'ordering': ['-logged_date', '-recorded_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'logged_date', 'source'), name='unique_steps_per_day_per_source')],
            },
        ),
    ]
