# Generated by Django 5.2.10 on 2026-01-10 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0016_add_steps_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="category",
            field=models.CharField(
                choices=[
                    ("resistance", "Resistance Training"),
                    ("cardio", "Cardio"),
                    ("class", "Fitness Class"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ClassDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Class duration in minutes", null=True
                    ),
                ),
                (
                    "intensity",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "workout_exercise",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_details",
                        to="health.workoutexercise",
                    ),
                ),
            ],
            options={
                "verbose_name": "class details",
                "verbose_name_plural": "class details",
            },
        ),
    ]
