# Generated by Django 4.2.27 on 2026-01-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0019_alter_fastingwindow_fasting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='fatsecret_id',
            field=models.CharField(blank=True, db_index=True, help_text='FatSecret API food ID for re-verification', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, help_text='When external API data was last verified/refreshed', null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='data_source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('usda', 'USDA Database'), ('barcode', 'Barcode Scan'), ('ai', 'AI Recognition'), ('fatsecret', 'FatSecret API')], default='manual', max_length=20),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['fatsecret_id'], name='health_food_fatsecr_c08e67_idx'),
        ),
    ]
