# Generated by Django 4.2.27 on 2026-01-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0020_add_fatsecret_fields_to_fooditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dexcomcredential',
            name='access_token',
            field=models.TextField(help_text='Encrypted access token'),
        ),
        migrations.AlterField(
            model_name='dexcomcredential',
            name='refresh_token',
            field=models.TextField(blank=True, help_text='Encrypted refresh token'),
        ),
    ]
