# Generated by Django 4.2.27 on 2026-01-15 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0021_alter_dexcomcredential_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cycle_tracking_enabled', models.BooleanField(default=False, help_text='Enable menstrual cycle tracking features')),
                ('average_cycle_length', models.PositiveSmallIntegerField(default=28, help_text='Average length of menstrual cycle in days (typically 21-35)')),
                ('average_period_length', models.PositiveSmallIntegerField(default=5, help_text='Average length of period in days (typically 3-7)')),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Send notifications for period predictions and reminders')),
                ('fertile_window_tracking_enabled', models.BooleanField(default=False, help_text='Track and display fertile window predictions')),
                ('last_period_start_date', models.DateField(blank=True, help_text='Start date of most recent period (used for predictions)', null=True)),
                ('user', models.OneToOneField(help_text='User these cycle settings belong to', on_delete=django.db.models.deletion.CASCADE, related_name='cycle_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cycle settings',
                'verbose_name_plural': 'cycle settings',
            },
        ),
    ]
