# Generated by Django 4.2.27 on 2026-01-15 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0022_add_cyclesettings_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('log_date', models.DateField(default=django.utils.timezone.now, help_text='Date of this cycle log entry')),
                ('flow_level', models.CharField(choices=[('none', 'None'), ('spotting', 'Spotting'), ('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], default='none', help_text='Menstrual flow intensity for this day', max_length=10)),
                ('symptoms', models.JSONField(blank=True, default=list, help_text='List of symptom keys from CYCLE_SYMPTOM_CHOICES')),
                ('mood', models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('irritable', 'Irritable'), ('anxious', 'Anxious'), ('calm', 'Calm'), ('energetic', 'Energetic'), ('tired', 'Tired'), ('emotional', 'Emotional')], help_text='Primary emotional state for this day', max_length=20)),
                ('energy_level', models.PositiveSmallIntegerField(blank=True, help_text='Energy level from 1 (very low) to 5 (very high)', null=True)),
                ('cervical_mucus', models.CharField(blank=True, choices=[('dry', 'Dry'), ('sticky', 'Sticky'), ('creamy', 'Creamy'), ('watery', 'Watery'), ('egg_white', 'Egg White (Fertile)')], help_text='Cervical mucus type (optional, for fertility tracking)', max_length=20)),
                ('basal_temp', models.DecimalField(blank=True, decimal_places=2, help_text='Basal body temperature in Fahrenheit (e.g., 97.80)', max_digits=4, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or observations for this day')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cycle daily log',
                'verbose_name_plural': 'cycle daily logs',
                'ordering': ['-log_date'],
                'indexes': [models.Index(fields=['user', 'log_date'], name='health_cycl_user_id_24de87_idx'), models.Index(fields=['user', 'flow_level'], name='health_cycl_user_id_784454_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='cycledailylog',
            constraint=models.UniqueConstraint(fields=('user', 'log_date'), name='unique_cycle_log_per_user_per_day'),
        ),
    ]
