# Generated by Django 4.2.27 on 2026-01-15 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0023_add_cycledailylog_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('cycle_number', models.PositiveIntegerField(help_text='Cycle number for this user (auto-incremented)')),
                ('start_date', models.DateField(help_text='First day of period (cycle start date)')),
                ('end_date', models.DateField(blank=True, help_text='Day before next period starts (set when next cycle begins)', null=True)),
                ('period_end_date', models.DateField(blank=True, help_text='Last day of period bleeding', null=True)),
                ('is_predicted', models.BooleanField(default=False, help_text='True if this cycle was AI-predicted rather than user-confirmed')),
                ('notes', models.TextField(blank=True, help_text='Notes about this cycle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cycle',
                'verbose_name_plural': 'cycles',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['user', 'start_date'], name='health_cycl_user_id_5dd5ae_idx'), models.Index(fields=['user', 'cycle_number'], name='health_cycl_user_id_4c9551_idx')],
            },
        ),
    ]
