# Generated by Django 4.2.27 on 2026-01-15 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0024_add_cycle_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyclePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('predicted_period_start', models.DateField(help_text='Predicted first day of period')),
                ('predicted_period_end', models.DateField(help_text='Predicted last day of period')),
                ('predicted_fertile_window_start', models.DateField(blank=True, help_text='Predicted start of fertile window (ovulation window)', null=True)),
                ('predicted_fertile_window_end', models.DateField(blank=True, help_text='Predicted end of fertile window', null=True)),
                ('prediction_confidence', models.DecimalField(decimal_places=2, help_text='Algorithm confidence score (0.00 to 1.00)', max_digits=3)),
                ('prediction_algorithm_version', models.CharField(help_text="Version of the prediction algorithm used (e.g., 'v1.0', 'v2.1-ml')", max_length=50)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this prediction was generated')),
                ('actual_period_start', models.DateField(blank=True, help_text='Actual period start date (filled when verified for accuracy tracking)', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cycle prediction',
                'verbose_name_plural': 'cycle predictions',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['user', 'predicted_period_start'], name='health_cycl_user_id_25763e_idx'), models.Index(fields=['user', '-generated_at'], name='health_cycl_user_id_105a94_idx')],
            },
        ),
    ]
