# Generated by Django 4.2.27 on 2026-01-17 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0025_add_cycleprediction_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('amount', models.DecimalField(decimal_places=1, help_text='Amount of water consumed', max_digits=6)),
                ('unit', models.CharField(choices=[('oz', 'Ounces (oz)'), ('ml', 'Milliliters (ml)'), ('cups', 'Cups'), ('liters', 'Liters')], default='oz', max_length=10)),
                ('container', models.CharField(blank=True, choices=[('glass', 'Glass'), ('bottle', 'Water Bottle'), ('cup', 'Cup/Mug'), ('large_bottle', 'Large Bottle (32oz+)'), ('other', 'Other')], default='glass', max_length=20)),
                ('logged_date', models.DateField(help_text='Date the water was logged for')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this entry was recorded')),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'water entry',
                'verbose_name_plural': 'water entries',
                'ordering': ['-logged_date', '-recorded_at'],
            },
        ),
    ]
