# Generated by Django 4.2.27 on 2026-01-20 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0026_water_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('sleep_date', models.DateField(help_text='Date of sleep (the night of - e.g., sleep on Jan 5 night is Jan 5)')),
                ('bedtime', models.DateTimeField(help_text='When you went to bed / sleep session started')),
                ('wake_time', models.DateTimeField(help_text='When you woke up / sleep session ended')),
                ('total_duration_minutes', models.PositiveIntegerField(help_text='Total time in bed (bedtime to wake_time) in minutes')),
                ('asleep_duration_minutes', models.PositiveIntegerField(blank=True, help_text='Actual time asleep in minutes (excludes awake periods)', null=True)),
                ('stage_awake_minutes', models.PositiveIntegerField(blank=True, help_text='Time spent awake during sleep session', null=True)),
                ('stage_rem_minutes', models.PositiveIntegerField(blank=True, help_text='Time in REM sleep (dreams, memory consolidation)', null=True)),
                ('stage_light_minutes', models.PositiveIntegerField(blank=True, help_text='Time in light/core sleep', null=True)),
                ('stage_deep_minutes', models.PositiveIntegerField(blank=True, help_text='Time in deep/slow-wave sleep (physical restoration)', null=True)),
                ('quality_rating', models.CharField(blank=True, choices=[('excellent', 'Excellent - Woke refreshed'), ('good', 'Good - Felt rested'), ('fair', 'Fair - Okay'), ('poor', 'Poor - Tired'), ('terrible', 'Terrible - Exhausted')], help_text='Subjective quality rating (manual entry or morning check-in)', max_length=20)),
                ('quality_score', models.PositiveIntegerField(blank=True, help_text='Calculated quality score 0-100 (from stages, efficiency, etc.)', null=True)),
                ('sleep_efficiency', models.DecimalField(blank=True, decimal_places=2, help_text='Sleep efficiency percentage (time asleep / time in bed * 100)', max_digits=5, null=True)),
                ('interruption_count', models.PositiveIntegerField(default=0, help_text='Number of times woken during the night')),
                ('total_awake_minutes', models.PositiveIntegerField(blank=True, help_text='Total time spent awake after initially falling asleep', null=True)),
                ('heart_rate_avg', models.PositiveIntegerField(blank=True, help_text='Average heart rate during sleep (BPM)', null=True)),
                ('heart_rate_min', models.PositiveIntegerField(blank=True, help_text='Minimum heart rate during sleep (BPM)', null=True)),
                ('heart_rate_max', models.PositiveIntegerField(blank=True, help_text='Maximum heart rate during sleep (BPM)', null=True)),
                ('respiratory_rate', models.DecimalField(blank=True, decimal_places=1, help_text='Average breaths per minute during sleep', max_digits=4, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('apple_health', 'Apple Health'), ('google_fit', 'Google Fit'), ('fitbit', 'Fitbit'), ('garmin', 'Garmin'), ('oura', 'Oura Ring'), ('samsung_health', 'Samsung Health'), ('whoop', 'WHOOP'), ('other', 'Other App/Device')], default='manual', max_length=20)),
                ('sync_id', models.CharField(blank=True, db_index=True, help_text='External ID from synced source to prevent duplicates', max_length=255)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this entry was recorded/synced')),
                ('notes', models.TextField(blank=True, help_text="Notes about sleep (e.g., 'took melatonin', 'stressed about work')")),
                ('factors', models.JSONField(blank=True, default=list, help_text='Factors affecting sleep: caffeine, alcohol, exercise, stress, etc.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sleep entry',
                'verbose_name_plural': 'sleep entries',
                'ordering': ['-sleep_date', '-bedtime'],
                'indexes': [models.Index(fields=['user', 'sleep_date'], name='health_slee_user_id_f4fe13_idx'), models.Index(fields=['source', 'sync_id'], name='health_slee_source_b7be86_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='sleepentry',
            constraint=models.UniqueConstraint(condition=models.Q(('sync_id__gt', '')), fields=('user', 'sleep_date', 'source', 'sync_id'), name='unique_sleep_per_night_per_source'),
        ),
    ]
