# Generated by Django 4.2.27 on 2026-01-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0027_sleepentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glucoseentry',
            name='sync_id',
            field=models.CharField(blank=True, db_index=True, help_text='External ID from synced source (HealthKit UUID) to prevent duplicates', max_length=100),
        ),
        migrations.AlterField(
            model_name='glucoseentry',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('dexcom', 'Dexcom CGM'), ('apple_health', 'Apple Health'), ('imported', 'Imported')], default='manual', max_length=20),
        ),
    ]
