# Generated by Django 4.2.27 on 2026-01-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0028_add_glucose_apple_health_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodoxygenentry',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('apple_health', 'Apple Health'), ('imported', 'Imported')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='bloodoxygenentry',
            name='sync_id',
            field=models.CharField(blank=True, db_index=True, help_text='External ID from synced source to prevent duplicates', max_length=100),
        ),
        migrations.AddField(
            model_name='waterentry',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('apple_health', 'Apple Health'), ('imported', 'Imported')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='waterentry',
            name='sync_id',
            field=models.CharField(blank=True, db_index=True, help_text='External ID from synced source to prevent duplicates', max_length=100),
        ),
    ]
