# Generated by Django 4.2.27 on 2026-01-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0029_add_sync_fields_water_oxygen'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepsentry',
            name='flights_climbed',
            field=models.PositiveIntegerField(blank=True, help_text='Flights of stairs climbed (if available)', null=True),
        ),
        migrations.AddField(
            model_name='stepsentry',
            name='resting_calories',
            field=models.PositiveIntegerField(blank=True, help_text='Resting/basal calories burned (if available)', null=True),
        ),
        migrations.AlterField(
            model_name='stepsentry',
            name='calories_burned',
            field=models.PositiveIntegerField(blank=True, help_text='Active calories burned (if available)', null=True),
        ),
    ]
