# Generated by Django 4.2.27 on 2026-01-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0030_add_resting_calories_flights_to_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepsentry',
            name='exercise_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Minutes of exercise (if available)', null=True),
        ),
        migrations.AddField(
            model_name='stepsentry',
            name='stand_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Hours with standing activity (if available)', null=True),
        ),
    ]
