# Generated by Django 4.2.27 on 2026-01-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0031_add_exercise_stand_to_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightentry',
            name='body_fat_percentage',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Body fat percentage from Apple Health or smart scale', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='weightentry',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('apple_health', 'Apple Health')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='weightentry',
            name='sync_id',
            field=models.CharField(blank=True, help_text='Unique ID for deduplication during sync', max_length=100),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='avg_heart_rate',
            field=models.PositiveIntegerField(blank=True, help_text='Average heart rate during workout', null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='calories_burned',
            field=models.PositiveIntegerField(blank=True, help_text='Total calories burned during workout', null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='distance_miles',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance for cardio workouts (in miles)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('apple_health', 'Apple Health')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='sync_id',
            field=models.CharField(blank=True, help_text='Unique ID for deduplication during sync', max_length=100),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='workout_type',
            field=models.CharField(blank=True, help_text='Workout type from HealthKit (e.g., Running, Cycling, Strength Training)', max_length=50),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', 'date'], name='health_work_user_id_ba14bb_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['source', 'sync_id'], name='health_work_source_f1a072_idx'),
        ),
        migrations.AddConstraint(
            model_name='workoutsession',
            constraint=models.UniqueConstraint(condition=models.Q(('sync_id__gt', '')), fields=('user', 'sync_id'), name='unique_workout_sync_id'),
        ),
    ]
