# Generated by Django 4.2.27 on 2026-01-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0032_add_bodyfat_workout_sync_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightentry',
            name='lean_body_mass',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Lean body mass in pounds from Apple Health or smart scale', max_digits=5, null=True),
        ),
    ]
