# Generated by Django 4.2.27 on 2026-01-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0033_add_lean_body_mass_to_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleepentry',
            name='hrv_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Heart Rate Variability SDNN in milliseconds', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='sleepentry',
            name='vo2_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='VO2 Max in mL/kg/min (cardio fitness level)', max_digits=5, null=True),
        ),
    ]
