# Generated by Django 4.2.27 on 2026-01-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0034_add_hrv_and_vo2max_to_sleepentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleepentry',
            name='caffeine_mg',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Daily caffeine intake in milligrams', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='sleepentry',
            name='mindful_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Daily mindful minutes (meditation, breathing exercises)', null=True),
        ),
    ]
