# Generated by Django 4.2.27 on 2026-01-24 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0035_add_caffeine_and_mindful_minutes_to_sleepentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodpressureentry',
            name='source',
            field=models.CharField(default='manual', help_text='Data source (manual, apple_health, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='bloodpressureentry',
            name='sync_id',
            field=models.CharField(blank=True, help_text='Unique sync ID to prevent duplicates', max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='BodyTemperatureEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('temperature', models.DecimalField(decimal_places=1, help_text='Temperature value', max_digits=4)),
                ('unit', models.CharField(choices=[('fahrenheit', 'Fahrenheit'), ('celsius', 'Celsius')], default='fahrenheit', max_length=10)),
                ('context', models.CharField(choices=[('oral', 'Oral'), ('ear', 'Ear (Tympanic)'), ('forehead', 'Forehead'), ('armpit', 'Armpit (Axillary)'), ('rectal', 'Rectal'), ('other', 'Other')], default='oral', max_length=20)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(default='manual', help_text='Data source (manual, apple_health, etc.)', max_length=50)),
                ('sync_id', models.CharField(blank=True, help_text='Unique sync ID to prevent duplicates', max_length=100, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'body temperature entry',
                'verbose_name_plural': 'body temperature entries',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
