# Generated by Django 4.2.27 on 2026-01-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0036_add_blood_pressure_source_and_body_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodytemperatureentry',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10),
        ),
    ]
