# Generated by Django 4.2.27 on 2026-01-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0037_bodytemperatureentry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineschedule',
            name='time_of_day',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('mid_morning', 'Mid-Morning'), ('lunch', 'Lunch'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('nightly', 'Nightly')], help_text='Time period for grouping doses (Morning, Lunch, Evening, etc.)', max_length=20),
        ),
    ]
