# Generated by Django 4.2.27 on 2026-02-14 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0039_populate_time_of_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_inches', models.DecimalField(blank=True, decimal_places=1, help_text='Height in inches (used for projections and modeling)', max_digits=5, null=True)),
                ('activity_level', models.CharField(blank=True, choices=[('sedentary', 'Sedentary'), ('lightly_active', 'Lightly Active'), ('moderately_active', 'Moderately Active'), ('very_active', 'Very Active'), ('highly_active', 'Highly Active')], default='', help_text='General activity level (used for caloric modeling)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'health profile',
                'verbose_name_plural': 'health profiles',
            },
        ),
        migrations.CreateModel(
            name='InsightResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('insight_type', models.CharField(choices=[('trend', 'Trend'), ('consistency', 'Consistency'), ('gap', 'Gap'), ('correlation', 'Correlation')], db_index=True, max_length=20)),
                ('text', models.TextField(help_text='The insight text shown to the user')),
                ('related_domains', models.JSONField(default=list, help_text='Domains this insight spans, e.g. ["weight", "body_composition"]')),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='0.00-1.00 confidence based on data density', max_digits=3)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured data about the insight')),
                ('is_dismissed', models.BooleanField(default=False, help_text='User has dismissed this insight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'insight result',
                'verbose_name_plural': 'insight results',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['user', 'insight_type', '-generated_at'], name='health_insi_user_id_d7c077_idx')],
            },
        ),
        migrations.CreateModel(
            name='BodyCompositionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('metric_name', models.CharField(db_index=True, help_text='Type of measurement (e.g. body_fat_pct, lean_mass, waist)', max_length=50)),
                ('value', models.DecimalField(decimal_places=2, help_text='Measurement value', max_digits=10)),
                ('unit', models.CharField(blank=True, default='', help_text='Unit of measurement (%, lb, in, cm, etc.)', max_length=10)),
                ('measurement_date', models.DateField(help_text='Date the measurement was taken')),
                ('source', models.CharField(blank=True, choices=[('manual', 'Manual Entry'), ('smart_scale', 'Smart Scale'), ('dexa_scan', 'DEXA Scan'), ('bod_pod', 'Bod Pod'), ('inbody', 'InBody Scanner'), ('gym_scan', 'Gym Body Scan'), ('apple_health', 'Apple Health'), ('other', 'Other')], default='manual', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'body composition entry',
                'verbose_name_plural': 'body composition entries',
                'ordering': ['-measurement_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'metric_name', '-measurement_date'], name='health_body_user_id_2199a7_idx')],
            },
        ),
    ]
