# Generated by Django 4.2.27 on 2026-02-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0040_body_composition_health_profile_insights'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='weight_goal',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Target weight goal', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='weight_goal_target_date',
            field=models.DateField(blank=True, help_text='Target date to achieve weight goal', null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='weight_goal_unit',
            field=models.CharField(choices=[('lb', 'Pounds'), ('kg', 'Kilograms')], default='lb', help_text='Unit for weight goal', max_length=2),
        ),
    ]
