# Generated by Django 4.2.27 on 2026-02-14 19:07

from django.db import migrations


def copy_weight_goals_forward(apps, schema_editor):
    """Copy weight goal data from UserPreferences to HealthProfile."""
    UserPreferences = apps.get_model("users", "UserPreferences")
    HealthProfile = apps.get_model("health", "HealthProfile")

    prefs_with_goals = UserPreferences.objects.filter(
        weight_goal__isnull=False
    ).select_related("user")

    for prefs in prefs_with_goals:
        profile, _ = HealthProfile.objects.get_or_create(user=prefs.user)
        profile.weight_goal = prefs.weight_goal
        profile.weight_goal_unit = prefs.weight_goal_unit
        profile.weight_goal_target_date = prefs.weight_goal_target_date
        profile.save()


def copy_weight_goals_backward(apps, schema_editor):
    """Copy weight goal data back from HealthProfile to UserPreferences."""
    HealthProfile = apps.get_model("health", "HealthProfile")
    UserPreferences = apps.get_model("users", "UserPreferences")

    profiles_with_goals = HealthProfile.objects.filter(
        weight_goal__isnull=False
    ).select_related("user")

    for profile in profiles_with_goals:
        try:
            prefs = UserPreferences.objects.get(user=profile.user)
            prefs.weight_goal = profile.weight_goal
            prefs.weight_goal_unit = profile.weight_goal_unit
            prefs.weight_goal_target_date = profile.weight_goal_target_date
            prefs.save()
        except UserPreferences.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0041_add_weight_goal_to_health_profile"),
        ("users", "0019_add_weight_nutrition_goals"),
    ]

    operations = [
        migrations.RunPython(
            copy_weight_goals_forward,
            copy_weight_goals_backward,
        ),
    ]
