# Generated by Django 4.2.27 on 2026-02-17 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purpose', '0006_alter_habitgoal_measurement_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0042_migrate_weight_goal_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransformationProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('name', models.CharField(help_text="Protocol name (e.g., '12-Week Cut', 'Summer Bulk')", max_length=200)),
                ('protocol_type', models.CharField(choices=[('cut', 'Cut'), ('bulk', 'Bulk'), ('recomp', 'Recomposition'), ('maintenance', 'Maintenance'), ('custom', 'Custom')], default='custom', help_text='Type of transformation protocol', max_length=20)),
                ('start_date', models.DateField(help_text='When the protocol starts')),
                ('target_end_date', models.DateField(blank=True, help_text='Target completion date', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this protocol is currently active')),
                ('goal_weight', models.DecimalField(blank=True, decimal_places=2, help_text="Target weight (in user's preferred unit)", max_digits=6, null=True)),
                ('goal_weight_unit', models.CharField(choices=[('lb', 'Pounds'), ('kg', 'Kilograms')], default='lb', max_length=5)),
                ('goal_body_fat', models.DecimalField(blank=True, decimal_places=2, help_text='Target body fat percentage', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, help_text='Protocol notes')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the protocol was completed', null=True)),
                ('life_goal', models.ForeignKey(blank=True, help_text='Linked life goal for goal engine tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transformation_protocols', to='purpose.lifegoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'transformation protocol',
                'verbose_name_plural': 'transformation protocols',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='health_tran_user_id_e22c3a_idx'), models.Index(fields=['user', '-start_date'], name='health_tran_user_id_2c339f_idx')],
            },
        ),
    ]
