# Generated by Django 4.2.27 on 2026-02-18 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0043_transformationprotocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('name', models.CharField(help_text="Plan name (e.g., '2-Group Strength Split')", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is currently active')),
                ('days_per_week', models.PositiveIntegerField(default=6, help_text='Target training days per week')),
                ('goal', models.CharField(blank=True, help_text="Primary goal (e.g., 'fat loss', 'muscle gain')", max_length=100)),
                ('transformation_protocol', models.ForeignKey(blank=True, help_text='Linked transformation protocol', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_plans', to='health.transformationprotocol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'workout plan',
                'verbose_name_plural': 'workout plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='0=Monday through 6=Sunday')),
                ('preferred_time', models.TimeField(blank=True, help_text='Preferred workout time (e.g., 17:00)', null=True)),
                ('is_rest_day', models.BooleanField(default=False, help_text='Mark as rest day (template ignored if True)')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='health.workoutplan')),
                ('template', models.ForeignKey(help_text='Workout template for this day', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='health.workouttemplate')),
            ],
            options={
                'verbose_name': 'workout schedule entry',
                'verbose_name_plural': 'workout schedule entries',
                'ordering': ['day_of_week'],
                'unique_together': {('plan', 'day_of_week')},
            },
        ),
        migrations.AddIndex(
            model_name='workoutplan',
            index=models.Index(fields=['user', 'is_active'], name='health_work_user_id_438c28_idx'),
        ),
    ]
