# Generated by Django 4.2.27 on 2026-02-18 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0044_workout_plan_and_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('default_meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='snack', max_length=20)),
                ('is_favorite', models.BooleanField(default=False)),
                ('use_count', models.PositiveIntegerField(default=0, help_text='How many times this template has been applied')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'meal template',
                'verbose_name_plural': 'meal templates',
                'ordering': ['-is_favorite', '-use_count', 'name'],
            },
        ),
        migrations.AddField(
            model_name='foodentry',
            name='confidence_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Confidence in nutrient accuracy (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='copied_from_entry',
            field=models.ForeignKey(blank=True, help_text='Entry this was copied from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='health.foodentry'),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='data_source_used',
            field=models.CharField(blank=True, choices=[('local', 'Local Database'), ('fatsecret', 'FatSecret API'), ('openfoodfacts', 'Open Food Facts'), ('ai_guess', 'AI Estimate'), ('user_override', 'User Override'), ('quick_add', 'Quick Add'), ('manual', 'Manual Entry')], default='manual', help_text='Which data source provided the nutrient values for this entry', max_length=30),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='food_item_version',
            field=models.PositiveIntegerField(blank=True, help_text='FoodItem.version at the time this entry was logged', null=True),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Mark as favorite for quick access'),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='snapshot_nutrients',
            field=models.JSONField(blank=True, default=dict, help_text='Per-serving nutrient values at time of logging. Format: {calories: 10, protein_g: 0, carbohydrates_g: 4, ...}'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='external_ids',
            field=models.JSONField(blank=True, default=dict, help_text='{"fatsecret_id": "...", "off_barcode": "...", "usda_fdb_id": "..."}'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='verified_by_user',
            field=models.ForeignKey(blank=True, help_text='User who last verified/corrected this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_food_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Incremented when nutrient values change'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='data_source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('usda', 'USDA Database'), ('barcode', 'Barcode Scan'), ('ai', 'AI Recognition'), ('fatsecret', 'FatSecret API'), ('openfoodfacts', 'Open Food Facts'), ('user_created', 'User Created')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='NutritionLabelEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='nutrition_labels/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_evidence', to='health.fooditem')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_label_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'nutrition label evidence',
                'verbose_name_plural': 'nutrition label evidence',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MealTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=300)),
                ('food_brand', models.CharField(blank=True, max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('serving_size', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('serving_unit', models.CharField(default='serving', max_length=50)),
                ('snapshot_nutrients', models.JSONField(blank=True, default=dict, help_text='Per-serving nutrient values when this item was added to the template')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('custom_food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_items', to='health.customfood')),
                ('food_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_items', to='health.fooditem')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='health.mealtemplate')),
            ],
            options={
                'verbose_name': 'meal template item',
                'verbose_name_plural': 'meal template items',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='foodentry',
            name='applied_template',
            field=models.ForeignKey(blank=True, help_text='Meal template that was applied to create this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_entries', to='health.mealtemplate'),
        ),
        migrations.CreateModel(
            name='NutritionEntryAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_type', models.CharField(choices=[('quantity_change', 'Quantity Changed'), ('override_nutrients', 'Nutrients Overridden'), ('source_change', 'Source Changed'), ('copy_action', 'Copied from Another Entry'), ('template_apply', 'Template Applied'), ('edit', 'General Edit'), ('create', 'Entry Created')], max_length=30)),
                ('before_data', models.JSONField(blank=True, default=dict, help_text='State before the change')),
                ('after_data', models.JSONField(blank=True, default=dict, help_text='State after the change')),
                ('notes', models.TextField(blank=True, help_text='Optional description of the change')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='health.foodentry')),
            ],
            options={
                'verbose_name': 'nutrition entry audit',
                'verbose_name_plural': 'nutrition entry audits',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['entry', '-changed_at'], name='health_nutr_entry_i_c7615c_idx')],
            },
        ),
        migrations.CreateModel(
            name='FoodItemOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('overridden_nutrients', models.JSONField(help_text='Per-serving nutrient values corrected by the user. Format: {calories: 10, protein_g: 0, carbohydrates_g: 4, ...}')),
                ('override_reason', models.TextField(blank=True, help_text="Why the user corrected these values (e.g., 'Label says 10 cal not 3')")),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_overrides', to='health.fooditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'food item override',
                'verbose_name_plural': 'food item overrides',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'food_item')},
            },
        ),
    ]
