# Generated by Django 4.2.27 on 2026-02-18 01:12
# Data migration: backfill snapshot_nutrients and data_source_used for existing FoodEntry records.

from decimal import Decimal
from django.db import migrations


def backfill_snapshots(apps, schema_editor):
    """
    Backfill snapshot_nutrients from existing total_* fields / quantity.

    For every FoodEntry that has no snapshot_nutrients yet:
    1. Compute per-serving values = total_* / quantity
    2. Store as snapshot_nutrients JSON
    3. Map entry_source to data_source_used
    4. Map ai_confidence_score to confidence_score (scale to 0-100)
    """
    FoodEntry = apps.get_model('health', 'FoodEntry')

    # Source mapping: entry_source -> data_source_used
    source_map = {
        'manual': 'manual',
        'barcode': 'local',
        'camera': 'fatsecret',
        'voice': 'manual',
        'quick_add': 'quick_add',
    }

    # Process in batches to avoid memory issues
    batch_size = 500
    entries = FoodEntry.objects.filter(snapshot_nutrients={}).only(
        'id', 'quantity', 'entry_source', 'ai_confidence_score',
        'total_calories', 'total_protein_g', 'total_carbohydrates_g',
        'total_fiber_g', 'total_sugar_g', 'total_fat_g',
        'total_saturated_fat_g', 'total_sodium_mg',
        'total_cholesterol_mg', 'total_potassium_mg',
    )

    updates = []
    for entry in entries.iterator(chunk_size=batch_size):
        qty = entry.quantity or Decimal('1')
        if qty == 0:
            qty = Decimal('1')

        # Build per-serving snapshot from stored totals
        snapshot = {}
        for field in ['calories', 'protein_g', 'carbohydrates_g', 'fiber_g',
                       'sugar_g', 'fat_g', 'saturated_fat_g']:
            total_val = getattr(entry, f'total_{field}', None)
            if total_val is not None:
                snapshot[field] = float((Decimal(str(total_val)) / qty).quantize(Decimal('0.01')))
            else:
                snapshot[field] = 0.0

        # Optional micros
        for field in ['sodium_mg', 'cholesterol_mg', 'potassium_mg']:
            total_val = getattr(entry, f'total_{field}', None)
            if total_val is not None:
                snapshot[field] = float((Decimal(str(total_val)) / qty).quantize(Decimal('0.01')))

        entry.snapshot_nutrients = snapshot

        # Map data source
        entry.data_source_used = source_map.get(entry.entry_source, 'manual')

        # Map confidence score (ai_confidence_score is 0-1.0, scale to 0-100)
        if entry.ai_confidence_score is not None:
            entry.confidence_score = float(entry.ai_confidence_score * 100)
        elif entry.entry_source == 'manual':
            entry.confidence_score = 100.0
        elif entry.entry_source in ('barcode', 'camera'):
            entry.confidence_score = 95.0

        updates.append(entry)

        if len(updates) >= batch_size:
            FoodEntry.objects.bulk_update(
                updates,
                ['snapshot_nutrients', 'data_source_used', 'confidence_score'],
                batch_size=batch_size,
            )
            updates = []

    # Final batch
    if updates:
        FoodEntry.objects.bulk_update(
            updates,
            ['snapshot_nutrients', 'data_source_used', 'confidence_score'],
            batch_size=batch_size,
        )


def reverse_backfill(apps, schema_editor):
    """Reverse: clear snapshot_nutrients (totals remain intact)."""
    FoodEntry = apps.get_model('health', 'FoodEntry')
    FoodEntry.objects.exclude(snapshot_nutrients={}).update(
        snapshot_nutrients={},
        data_source_used='',
        confidence_score=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0045_nutrition_upgrade_phase1'),
    ]

    operations = [
        migrations.RunPython(backfill_snapshots, reverse_backfill),
    ]
