# Generated by Django 4.2.27 on 2026-02-21 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0046_nutrition_backfill_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartRateEventEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('event_type', models.CharField(choices=[('high_hr', 'High Heart Rate'), ('low_hr', 'Low Heart Rate'), ('irregular_rhythm', 'Irregular Rhythm (AFib)')], help_text='Type of heart rate event', max_length=20)),
                ('heart_rate', models.PositiveIntegerField(blank=True, help_text='Heart rate at time of event (BPM)', null=True)),
                ('threshold', models.PositiveIntegerField(blank=True, help_text='Threshold that was crossed (BPM, for high/low HR events)', null=True)),
                ('recorded_at', models.DateTimeField(help_text='When the event was detected')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Duration of the event in seconds (if applicable)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional context about the event')),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('apple_health', 'Apple Health'), ('imported', 'Imported')], default='apple_health', max_length=20)),
                ('sync_id', models.CharField(blank=True, db_index=True, help_text='External ID from synced source to prevent duplicates', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'heart rate event',
                'verbose_name_plural': 'heart rate events',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='DietaryNutrientEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('metric_date', models.DateField(help_text='Date these dietary metrics were recorded')),
                ('calories', models.PositiveIntegerField(blank=True, help_text='Total dietary energy in kilocalories', null=True)),
                ('protein_g', models.DecimalField(blank=True, decimal_places=2, help_text='Total protein in grams', max_digits=7, null=True)),
                ('carbohydrates_g', models.DecimalField(blank=True, decimal_places=2, help_text='Total carbohydrates in grams', max_digits=7, null=True)),
                ('fat_g', models.DecimalField(blank=True, decimal_places=2, help_text='Total fat in grams', max_digits=7, null=True)),
                ('fiber_g', models.DecimalField(blank=True, decimal_places=2, help_text='Total dietary fiber in grams', max_digits=7, null=True)),
                ('sugar_g', models.DecimalField(blank=True, decimal_places=2, help_text='Total sugar in grams', max_digits=7, null=True)),
                ('sodium_mg', models.DecimalField(blank=True, decimal_places=2, help_text='Sodium in milligrams', max_digits=7, null=True)),
                ('cholesterol_mg', models.DecimalField(blank=True, decimal_places=2, help_text='Dietary cholesterol in milligrams', max_digits=7, null=True)),
                ('saturated_fat_g', models.DecimalField(blank=True, decimal_places=2, help_text='Saturated fat in grams', max_digits=7, null=True)),
                ('potassium_mg', models.DecimalField(blank=True, decimal_places=2, help_text='Potassium in milligrams', max_digits=7, null=True)),
                ('calcium_mg', models.DecimalField(blank=True, decimal_places=2, help_text='Calcium in milligrams', max_digits=7, null=True)),
                ('iron_mg', models.DecimalField(blank=True, decimal_places=2, help_text='Iron in milligrams', max_digits=7, null=True)),
                ('vitamin_d_mcg', models.DecimalField(blank=True, decimal_places=2, help_text='Vitamin D in micrograms', max_digits=7, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('apple_health', 'Apple Health'), ('imported', 'Imported')], default='apple_health', max_length=20)),
                ('sync_id', models.CharField(blank=True, db_index=True, help_text='External ID from synced source to prevent duplicates', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dietary nutrient entry',
                'verbose_name_plural': 'dietary nutrient entries',
                'ordering': ['-metric_date'],
            },
        ),
        migrations.CreateModel(
            name='AudioExposureEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('metric_date', models.DateField(help_text='Date these audio metrics were recorded')),
                ('headphone_level_db', models.DecimalField(blank=True, decimal_places=2, help_text='Average headphone audio level in decibels (dB)', max_digits=5, null=True)),
                ('headphone_duration_minutes', models.PositiveIntegerField(blank=True, help_text='Total headphone listening time in minutes', null=True)),
                ('environmental_level_db', models.DecimalField(blank=True, decimal_places=2, help_text='Average environmental sound level in decibels (dB)', max_digits=5, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('apple_health', 'Apple Health'), ('imported', 'Imported')], default='apple_health', max_length=20)),
                ('sync_id', models.CharField(blank=True, db_index=True, help_text='External ID from synced source to prevent duplicates', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audio exposure entry',
                'verbose_name_plural': 'audio exposure entries',
                'ordering': ['-metric_date'],
            },
        ),
        migrations.CreateModel(
            name='MobilityEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('metric_date', models.DateField(help_text='Date these mobility metrics were recorded')),
                ('walking_asymmetry', models.DecimalField(blank=True, decimal_places=2, help_text='Walking asymmetry percentage (left/right imbalance, 0-50%)', max_digits=5, null=True)),
                ('walking_steadiness', models.CharField(blank=True, choices=[('ok', 'OK'), ('low', 'Low'), ('very_low', 'Very Low')], help_text='Apple Watch walking steadiness classification', max_length=10)),
                ('walking_steadiness_score', models.DecimalField(blank=True, decimal_places=2, help_text='Walking steadiness numeric score (0-100, if available)', max_digits=5, null=True)),
                ('walking_speed', models.DecimalField(blank=True, decimal_places=2, help_text='Average walking speed in mph', max_digits=5, null=True)),
                ('step_length', models.DecimalField(blank=True, decimal_places=2, help_text='Average step length in inches', max_digits=5, null=True)),
                ('double_support_time', models.DecimalField(blank=True, decimal_places=2, help_text='Double support time as percentage of walking cycle', max_digits=5, null=True)),
                ('stair_ascent_speed', models.DecimalField(blank=True, decimal_places=2, help_text='Stair ascent speed (flights per minute)', max_digits=5, null=True)),
                ('stair_descent_speed', models.DecimalField(blank=True, decimal_places=2, help_text='Stair descent speed (flights per minute)', max_digits=5, null=True)),
                ('six_min_walk_distance', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated six-minute walk distance in meters', max_digits=7, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('apple_health', 'Apple Health'), ('imported', 'Imported')], default='apple_health', max_length=20)),
                ('sync_id', models.CharField(blank=True, db_index=True, help_text='External ID from synced source to prevent duplicates', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mobility entry',
                'verbose_name_plural': 'mobility entries',
                'ordering': ['-metric_date'],
                'indexes': [models.Index(fields=['user', 'metric_date'], name='health_mobi_user_id_e15851_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='mobilityentry',
            constraint=models.UniqueConstraint(fields=('user', 'metric_date', 'source'), name='unique_mobility_per_day_per_source'),
        ),
        migrations.AddIndex(
            model_name='heartrateevententry',
            index=models.Index(fields=['user', 'event_type'], name='health_hear_user_id_096a34_idx'),
        ),
        migrations.AddIndex(
            model_name='heartrateevententry',
            index=models.Index(fields=['user', 'recorded_at'], name='health_hear_user_id_ae6f2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='dietarynutriententry',
            constraint=models.UniqueConstraint(fields=('user', 'metric_date', 'source'), name='unique_dietary_nutrients_per_day_per_source'),
        ),
        migrations.AddConstraint(
            model_name='audioexposureentry',
            constraint=models.UniqueConstraint(fields=('user', 'metric_date', 'source'), name='unique_audio_per_day_per_source'),
        ),
    ]
