# Generated by Django 4.2.27 on 2026-03-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0048_remove_dummy_sleep_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='days_per_week',
            field=models.PositiveIntegerField(default=4, help_text='Target training days per week'),
        ),
    ]
