# Generated by Django 4.2.27 on 2026-03-04 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0049_alter_workoutplan_days_per_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHealthSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('summary_date', models.DateField(db_index=True, help_text='Date this summary covers')),
                ('baseline_ready', models.BooleanField(default=False, help_text='True if user has >=14 days of core health signals')),
                ('health_score', models.PositiveSmallIntegerField(blank=True, help_text='Composite health score 0-100 (null if baseline not ready)', null=True)),
                ('health_score_drivers', models.JSONField(blank=True, default=dict, help_text='Explainable breakdown: strongest_positive, primary_risk, etc.')),
                ('recovery_score', models.PositiveSmallIntegerField(blank=True, help_text='Recovery readiness score 0-100', null=True)),
                ('recovery_drivers', models.JSONField(blank=True, default=dict, help_text='Recovery score driver breakdown')),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Total sleep duration in hours', max_digits=4, null=True)),
                ('sleep_quality_score', models.PositiveSmallIntegerField(blank=True, help_text='Sleep quality 0-100 derived from stages + efficiency', null=True)),
                ('sleep_debt_minutes', models.IntegerField(blank=True, help_text='Minutes of sleep debt (target - actual, positive = deficit)', null=True)),
                ('deep_sleep_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('rem_sleep_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('sleep_efficiency_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('resting_hr', models.PositiveSmallIntegerField(blank=True, help_text='Resting heart rate (bpm)', null=True)),
                ('hrv', models.DecimalField(blank=True, decimal_places=2, help_text='Heart rate variability (ms)', max_digits=6, null=True)),
                ('blood_pressure_systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('spo2_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('steps', models.PositiveIntegerField(blank=True, null=True)),
                ('active_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('calories_burned', models.PositiveIntegerField(blank=True, help_text='Active calories burned', null=True)),
                ('stand_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('flights_climbed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('workout_count', models.PositiveSmallIntegerField(default=0)),
                ('workout_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('training_load', models.DecimalField(blank=True, decimal_places=2, help_text='Volume-based training load score for the day', max_digits=8, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Latest weight reading in lbs', max_digits=6, null=True)),
                ('body_fat_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('skeletal_muscle_mass', models.DecimalField(blank=True, decimal_places=2, help_text='Skeletal muscle mass in lbs (when available)', max_digits=6, null=True)),
                ('lean_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('glucose_avg', models.DecimalField(blank=True, decimal_places=2, help_text='Average glucose mg/dL for the day', max_digits=6, null=True)),
                ('glucose_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('glucose_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('glucose_variability', models.DecimalField(blank=True, decimal_places=2, help_text='Glucose coefficient of variation (%)', max_digits=6, null=True)),
                ('time_in_range_pct', models.DecimalField(blank=True, decimal_places=2, help_text='% of readings in 70-180 mg/dL range', max_digits=5, null=True)),
                ('calories_consumed', models.PositiveIntegerField(blank=True, null=True)),
                ('protein_g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('carbs_g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fat_g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fiber_g', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('water_oz', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('nutrition_logged', models.BooleanField(default=False, help_text='True if at least one food entry was logged')),
                ('meals_logged', models.PositiveSmallIntegerField(default=0)),
                ('medication_adherence_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Medication adherence rate 0-100 for the day', max_digits=5, null=True)),
                ('doses_taken', models.PositiveSmallIntegerField(default=0)),
                ('doses_expected', models.PositiveSmallIntegerField(default=0)),
                ('fasting_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Total fasting hours during this day', max_digits=5, null=True)),
                ('caffeine_mg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('mindful_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('data_completeness_pct', models.DecimalField(blank=True, decimal_places=2, help_text='% of trackable domains with data today', max_digits=5, null=True)),
                ('signals_present', models.JSONField(blank=True, default=list, help_text='List of domain names that have data for this day')),
                ('last_computed', models.DateTimeField(auto_now=True, help_text='When this summary was last recomputed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'daily health summary',
                'verbose_name_plural': 'daily health summaries',
                'ordering': ['-summary_date'],
                'indexes': [models.Index(fields=['user', '-summary_date'], name='health_dail_user_id_a38820_idx'), models.Index(fields=['user', 'summary_date'], name='health_dail_user_id_5ea1e9_idx'), models.Index(fields=['user', 'baseline_ready', '-summary_date'], name='health_dail_user_id_b235ae_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyhealthsummary',
            constraint=models.UniqueConstraint(fields=('user', 'summary_date'), name='unique_health_summary_per_day'),
        ),
    ]
