# Generated by Django 4.2.27 on 2026-03-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0050_add_daily_health_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='protein_consumed_g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total protein consumed today (mirrors protein_g for clarity)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='protein_per_lb',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Grams of protein per pound of body weight', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='protein_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='protein_consumed / protein_target (1.0 = 100% of target)', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='protein_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Protein adequacy score 0-100', null=True),
        ),
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='protein_target_g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily protein target in grams (0.7g/lb body weight)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='protein_per_lb_target',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Custom protein multiplier (g per lb body weight). Default: 0.7', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='protein_target_g_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom daily protein target (g). Overrides auto-calculated 0.7g/lb.', max_digits=6, null=True),
        ),
    ]
