# Generated by Django 4.2.27 on 2026-03-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0051_add_protein_intelligence_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='protein_method',
            field=models.CharField(blank=True, default='', help_text="Target method: 'lean_body_mass', 'body_weight', or 'override'", max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyhealthsummary',
            name='protein_target_g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily protein target (LBM×1.0/1.1 or fallback 0.7g/lb)', max_digits=6, null=True),
        ),
    ]
