# Generated by Django 4.2.27 on 2026-03-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0052_add_protein_method_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='body_comp_drivers',
            field=models.JSONField(blank=True, default=dict, help_text='Explainable drivers for body comp intelligence'),
        ),
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='fat_loss_quality_label',
            field=models.CharField(blank=True, default='', help_text='EXCELLENT/GOOD/MIXED/MUSCLE_LOSS_RISK/INSUFFICIENT_DATA', max_length=20),
        ),
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='fat_loss_ratio_14d',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='abs(fat_mass_delta) / abs(weight_delta) over 14d window', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='fat_loss_speed_label',
            field=models.CharField(blank=True, default='', help_text='SAFE/FAST/TOO_FAST/SLOW/GAINING', max_length=10),
        ),
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='fat_loss_speed_pct_per_week',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pct of body weight lost per week over 14d window', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='fat_mass',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Computed: weight * (body_fat_pct / 100) in lbs', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='muscle_loss_risk_level',
            field=models.CharField(blank=True, default='', help_text='LOW/MED/HIGH', max_length=10),
        ),
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='muscle_loss_risk_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Composite 0-100 risk score for muscle loss', null=True),
        ),
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='plateau_status',
            field=models.CharField(blank=True, default='', help_text='TRUE_PLATEAU/RECOMP/WATER/INSUFFICIENT_DATA', max_length=20),
        ),
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='recomposition_flag_14d',
            field=models.BooleanField(blank=True, help_text='True if fat down + muscle up + weight flat over 14d', null=True),
        ),
    ]
