# Generated by Django 4.2.27 on 2026-03-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0053_body_composition_intelligence'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='fat_loss_phase',
            field=models.CharField(blank=True, default='', help_text='RAPID_INITIAL_LOSS / STABLE_FAT_LOSS / RECOMPOSITION / PLATEAU / REBOUND_RISK', max_length=25),
        ),
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='muscle_preservation_status',
            field=models.CharField(blank=True, default='', help_text='HIGH_QUALITY / MODERATE_QUALITY / MUSCLE_RISK / INSUFFICIENT_DATA', max_length=20),
        ),
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='phase_confidence',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Confidence 0-100 in phase classification', null=True),
        ),
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='phase_start_date',
            field=models.DateField(blank=True, help_text='Estimated date current phase began', null=True),
        ),
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='plateau_prediction_window_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Estimated days until plateau onset', null=True),
        ),
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='plateau_risk_label',
            field=models.CharField(blank=True, default='', help_text='LOW / RISING / HIGH', max_length=10),
        ),
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='plateau_risk_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Predictive plateau risk 0-100', null=True),
        ),
    ]
