# Generated by Django 4.2.27 on 2026-03-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0054_health_intelligence_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalrecord',
            name='pr_type',
            field=models.CharField(choices=[('weight', 'Max Weight'), ('reps', 'Rep PR'), ('e1rm', 'Estimated 1RM')], default='weight', help_text='Type of PR: max weight, rep PR at same weight, or estimated 1RM', max_length=10),
        ),
        migrations.AddField(
            model_name='personalrecord',
            name='previous_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Previous best value that was surpassed (weight in lbs, reps, or e1RM)', max_digits=8, null=True),
        ),
    ]
