# Generated by Django 4.2.27 on 2026-03-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0055_add_pr_type_and_previous_value'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='personalrecord',
            index=models.Index(fields=['user', 'exercise'], name='pr_user_exercise_idx'),
        ),
        migrations.AddIndex(
            model_name='personalrecord',
            index=models.Index(fields=['user', 'achieved_date'], name='pr_user_date_idx'),
        ),
    ]
