# Generated by Django 4.2.27 on 2026-03-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0056_add_pr_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='movement_type',
            field=models.CharField(choices=[('weighted', 'Weighted'), ('bodyweight', 'Bodyweight'), ('time', 'Time-Based')], default='weighted', help_text='Controls input fields: weighted (weight+reps), bodyweight (reps, optional weight), time (duration)', max_length=20),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='bodyweight_used',
            field=models.DecimalField(blank=True, decimal_places=1, help_text="User's bodyweight at time of exercise (for volume calculation)", max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds for time-based exercises', null=True),
        ),
        migrations.AddField(
            model_name='personalrecord',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds for time-based PRs', null=True),
        ),
        migrations.AddField(
            model_name='templateexerciseset',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Default duration in seconds for time-based exercises', null=True),
        ),
        migrations.AlterField(
            model_name='personalrecord',
            name='pr_type',
            field=models.CharField(choices=[('weight', 'Max Weight'), ('reps', 'Rep PR'), ('e1rm', 'Estimated 1RM'), ('time', 'Longest Hold')], default='weight', help_text='Type of PR: max weight, rep PR at same weight, or estimated 1RM', max_length=10),
        ),
        migrations.AlterField(
            model_name='personalrecord',
            name='reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalrecord',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Weight in pounds', max_digits=6, null=True),
        ),
    ]
