# Generated by Django 4.2.27 on 2026-03-10 11:22
# Data migration: classify existing exercises by movement_type

from django.db import migrations


# Exercises that use bodyweight (reps-based, no external weight required)
BODYWEIGHT_EXERCISES = [
    "Push-ups",
    "Pull-ups",
    "Chin-ups",
    "Chest Dips",
    "Tricep Dips",
    "Dips",
    "Lunges",
    "Walking Lunges",
    "Bulgarian Split Squat",
    "Crunches",
    "Russian Twist",
    "Leg Raise",
    "Hanging Leg Raise",
    "Mountain Climbers",
    "Dead Bug",
    "Bird Dog",
    "KB Lunges",
    "Burpees",
    "Jumping Jacks",
    "Box Jumps",
]

# Exercises that are time-based (hold for duration)
TIME_EXERCISES = [
    "Plank",
]


def classify_exercises(apps, schema_editor):
    Exercise = apps.get_model("health", "Exercise")

    # Set bodyweight exercises
    Exercise.objects.filter(
        name__in=BODYWEIGHT_EXERCISES,
        category="resistance",
    ).update(movement_type="bodyweight")

    # Set time-based exercises
    Exercise.objects.filter(
        name__in=TIME_EXERCISES,
        category="resistance",
    ).update(movement_type="time")

    # All others already default to "weighted" from the field default


def reverse_classification(apps, schema_editor):
    Exercise = apps.get_model("health", "Exercise")
    Exercise.objects.filter(
        movement_type__in=["bodyweight", "time"],
    ).update(movement_type="weighted")


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0057_add_movement_type_and_time_fields"),
    ]

    operations = [
        migrations.RunPython(classify_exercises, reverse_classification),
    ]
