# Generated by Django 4.2.27 on 2026-03-18 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0062_add_warmup_hip_hinges_band_pull_aparts'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutschedule',
            name='grace_period_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Minutes after preferred_time before marking late'),
        ),
        migrations.CreateModel(
            name='WorkoutScheduleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('scheduled_date', models.DateField(help_text='The date this schedule entry was for')),
                ('log_status', models.CharField(choices=[('completed', 'Completed'), ('completed_late', 'Completed Late'), ('skipped', 'Skipped')], max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the workout was completed', null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='health.workoutschedule')),
                ('session', models.ForeignKey(blank=True, help_text='The actual workout session (null for skipped)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_logs', to='health.workoutsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'workout schedule log',
                'verbose_name_plural': 'workout schedule logs',
                'ordering': ['-scheduled_date'],
                'unique_together': {('schedule', 'scheduled_date')},
            },
        ),
    ]
