# Generated by Django 4.2.27 on 2026-03-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0063_behavior_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinelog',
            name='is_user_corrected',
            field=models.BooleanField(default=False, help_text='True when user has manually edited a past log'),
        ),
        migrations.AddField(
            model_name='workoutschedulelog',
            name='is_user_corrected',
            field=models.BooleanField(default=False, help_text='True when user has manually edited a past log'),
        ),
    ]
