# Generated by Django 4.2.27 on 2026-03-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0065_audit_workout_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='instructions',
            field=models.TextField(blank=True, help_text='Step-by-step exercise instructions and form cues'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_source',
            field=models.CharField(blank=True, choices=[('athleanx', 'AthleanX'), ('nippard', 'Jeff Nippard'), ('ethier', 'Jeremy Ethier'), ('custom', 'Custom')], help_text='Source channel of the assigned video', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Direct YouTube video URL for exercise demonstration'),
        ),
    ]
