# Generated by Django 4.2.27 on 2026-03-21 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0066_exercise_guidance_fields'),
        ('health', '0066_routine_maintenance_bridge_choices'),
    ]

    operations = [
    ]
