# Generated by Django 4.2.27 on 2026-03-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0067_merge_20260321_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='load_multiplier',
            field=models.FloatField(blank=True, help_text='Future: optional scaling factor for load (e.g., 0.4 for partial bodyweight). Not used in calculations yet.', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='load_type',
            field=models.CharField(choices=[('external', 'External Weight'), ('bodyweight', 'Bodyweight'), ('assisted', 'Assisted'), ('band', 'Band Resistance'), ('movement', 'Movement / Skill')], default='external', help_text='Controls volume calculation: external/bodyweight produce volume, others do not', max_length=20),
        ),
    ]
