# Generated by Django 4.2.27 on 2026-03-23 20:05
# Data migration: classify existing exercises by load_type

from django.db import migrations


# Exercises that are band-based (no meaningful volume)
BAND_EXERCISE_KEYWORDS = [
    "Band",
]

# Exercises that are movement/skill drills (no meaningful volume)
MOVEMENT_EXERCISES = [
    "Baseball Bat Swing",
    "Hip Hinge",
    "Mountain Climbers",
    "Dead Bug",
    "Bird Dog",
    "Jumping Jacks",
    "Box Jumps",
    "Burpees",
]


def classify_load_types(apps, schema_editor):
    Exercise = apps.get_model("health", "Exercise")

    # 1. movement_type="bodyweight" → load_type="bodyweight" (default for true bodyweight)
    Exercise.objects.filter(
        movement_type="bodyweight",
    ).update(load_type="bodyweight")

    # 2. movement_type="time" → load_type="movement" (time exercises have no volume)
    Exercise.objects.filter(
        movement_type="time",
    ).update(load_type="movement")

    # 3. movement_type="weighted" stays load_type="external" (the default, no-op)

    # 4. Override: band exercises → load_type="band"
    for keyword in BAND_EXERCISE_KEYWORDS:
        Exercise.objects.filter(
            name__icontains=keyword,
        ).update(load_type="band")

    # 5. Override: movement/skill drills → load_type="movement"
    Exercise.objects.filter(
        name__in=MOVEMENT_EXERCISES,
    ).update(load_type="movement")


def reverse_classification(apps, schema_editor):
    Exercise = apps.get_model("health", "Exercise")
    # Reset all to default
    Exercise.objects.all().update(load_type="external")


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0068_add_load_type_fields"),
    ]

    operations = [
        migrations.RunPython(classify_load_types, reverse_classification),
    ]
