# Generated by Django 4.2.27 on 2026-03-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0069_classify_exercise_load_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartrateentry',
            name='source',
            field=models.CharField(default='manual', help_text='Data source (manual, apple_health, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='heartrateentry',
            name='sync_id',
            field=models.CharField(blank=True, help_text='Unique sync ID to prevent duplicates', max_length=100, null=True, unique=True),
        ),
    ]
