# Generated by Django 4.2.27 on 2026-03-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0070_add_source_sync_id_to_heartrateentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterentry',
            options={'ordering': ['-logged_date', '-recorded_at'], 'verbose_name': 'hydration entry', 'verbose_name_plural': 'hydration entries'},
        ),
        migrations.AddField(
            model_name='waterentry',
            name='drink_type',
            field=models.CharField(choices=[('water', 'Water'), ('coffee', 'Coffee'), ('tea', 'Tea'), ('electrolyte', 'Electrolyte Drink'), ('creatine', 'Creatine Drink'), ('juice', 'Juice'), ('milk', 'Milk'), ('other', 'Other')], default='water', help_text='Type of beverage consumed', max_length=20),
        ),
        migrations.AlterField(
            model_name='waterentry',
            name='amount',
            field=models.DecimalField(decimal_places=1, help_text='Amount consumed', max_digits=6),
        ),
        migrations.AlterField(
            model_name='waterentry',
            name='logged_date',
            field=models.DateField(help_text='Date the fluid was logged for'),
        ),
    ]
