# Generated by Django 4.2.27 on 2026-04-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0071_add_drink_type_to_water_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='intensity',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], help_text='User-provided intensity level for activity workouts', max_length=20),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='session_mode',
            field=models.CharField(choices=[('structured', 'Structured'), ('activity', 'Activity')], default='structured', help_text='structured = exercises with sets/reps, activity = duration-driven', max_length=20),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='workout_type',
            field=models.CharField(blank=True, help_text='Activity type (e.g., Pickleball, Running, Strength Training)', max_length=50),
        ),
    ]
