# Generated by Django 4.2.27 on 2026-04-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0071_add_drink_type_to_water_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='intensity',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], default='', help_text='User-reported or derived intensity level', max_length=20),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='session_mode',
            field=models.CharField(choices=[('structured', 'Structured'), ('activity', 'Activity')], default='structured', help_text='Whether this is a structured workout (sets/reps) or duration-based activity', max_length=20),
        ),
    ]
