# Generated by Django 4.2.27 on 2026-04-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0073_backfill_activity_workout_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='session_mode',
            field=models.CharField(choices=[('structured', 'Structured'), ('activity', 'Activity')], default='structured', help_text='Whether this is a structured workout (sets/reps) or duration-based activity', max_length=20),
        ),
    ]
