# Generated by Django 4.2.27 on 2026-04-04 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0072_add_session_mode_and_intensity_to_workout'),
        ('health', '0073_backfill_activity_workout_mode'),
    ]

    operations = [
    ]
