# Generated by Django 4.2.27 on 2026-04-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0079_alter_workoutsession_intensity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='intake_type',
            field=models.CharField(choices=[('medication', 'Medication'), ('supplement', 'Supplement')], default='medication', help_text='Whether this is a medication or supplement', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('optimization', 'Optimization')], default='critical', help_text='Critical (health consequence if missed) vs optimization (goal support)', max_length=20),
        ),
        migrations.AddField(
            model_name='medicinelog',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('cos', 'CoS'), ('routine', 'Routine')], default='manual', help_text='How this log was created (manual, CoS, routine bridge)', max_length=20),
        ),
    ]
