# Generated by Django 4.2.27 on 2026-04-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0081_seed_creatine_supplement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterentry',
            name='drink_type',
            field=models.CharField(choices=[('water', 'Water'), ('coffee', 'Coffee'), ('tea', 'Tea'), ('electrolyte', 'Electrolyte Drink'), ('juice', 'Juice'), ('milk', 'Milk'), ('other', 'Other')], default='water', help_text='Type of beverage consumed', max_length=20),
        ),
    ]
