# Generated by Django 4.2.27 on 2026-04-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0084_backfill_intake_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='intake_status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', help_text='Current status of this intake regimen', max_length=20),
        ),
        migrations.AlterField(
            model_name='intake',
            name='paused_at',
            field=models.DateTimeField(blank=True, help_text='When this intake was paused', null=True),
        ),
        migrations.AlterField(
            model_name='intake',
            name='paused_reason',
            field=models.CharField(blank=True, help_text='Reason for pausing this intake', max_length=500),
        ),
    ]
