# Generated by Django 4.2.27 on 2026-05-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0086_backfill_structured_workout_routine_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakelog',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual (legacy)'), ('cos', 'CoS (legacy)'), ('routine', 'Routine (legacy)'), ('ui_per_item', 'UI — Per-Item Check'), ('ui_block_toggle', 'UI — Block Toggle'), ('ui_skip', 'UI — Skip'), ('llm_action', 'LLM Action Handler'), ('quick_reply', 'Quick Reply'), ('sms_reply', 'SMS Reply'), ('correction', 'User Correction')], default='manual', help_text='How this log was created (manual, CoS, routine bridge)', max_length=20),
        ),
    ]
