# Generated by Django 4.2.27 on 2026-05-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0087_alter_intakelog_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='intake',
            name='intake_subtype',
            field=models.CharField(blank=True, choices=[('insulin_basal', 'Insulin — Basal'), ('insulin_bolus', 'Insulin — Bolus')], help_text='Optional refinement under intake_type. Currently used to mark insulin variants (basal vs bolus) for metabolic intelligence. Null for all other intakes (default).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='intakelog',
            name='dose_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Per-event dose amount. Required for insulin logs where dose varies per administration; null for all other intake logs.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='intakelog',
            name='dose_event_type',
            field=models.CharField(blank=True, choices=[('basal', 'Basal'), ('meal_bolus', 'Meal Bolus'), ('correction', 'Correction')], help_text='Type of dose event (basal, meal_bolus, correction). Used by insulin intelligence; null for all other intake logs.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='intakelog',
            name='dose_unit',
            field=models.CharField(blank=True, choices=[('units', 'Units (U)'), ('ml', 'Milliliters (ml)'), ('mg', 'Milligrams (mg)')], help_text='Unit for dose_amount (units, ml, mg). Null when dose_amount is null.', max_length=20, null=True),
        ),
    ]
