# Generated by Django 4.2.27 on 2026-05-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0088_insulin_dose_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='glucose_readings_count',
            field=models.PositiveSmallIntegerField(default=0, help_text="Number of glucose readings the day's aggregates were computed from."),
        ),
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='insulin_basal_units',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Basal insulin units logged for the day.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='insulin_bolus_units',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bolus + correction insulin units logged for the day.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='insulin_total_units',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total insulin units logged for the day (basal + bolus + correction).', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='meal_response_distribution',
            field=models.JSONField(blank=True, default=dict, help_text="Distribution of classified meal glucose responses for the day (e.g., {'minimal_spike': 2, 'large_spike': 1}). Populated by the MealGlucoseResponse classifier (C8); empty dict until then."),
        ),
        migrations.AddField(
            model_name='dailyhealthsummary',
            name='overnight_avg_glucose',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Avg glucose mg/dL during overnight window (midnight–6am local).', max_digits=6, null=True),
        ),
    ]
