# Generated by Django 4.2.27 on 2026-05-25 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0089_daily_summary_metabolic_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealGlucoseResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('meal_consumed_at', models.DateTimeField(db_index=True, help_text='When the meal was consumed (FoodEntry logged_date + logged_time).')),
                ('classification', models.CharField(choices=[('minimal_spike', 'Minimal spike (<30 mg/dL rise)'), ('moderate_spike', 'Moderate spike (30-59 mg/dL rise)'), ('large_spike', 'Large spike (60-99 mg/dL rise)'), ('extreme_spike', 'Extreme spike (≥100 mg/dL rise)'), ('prolonged_spike', 'Prolonged spike (failed to return to baseline)')], help_text='Deterministic spike classification.', max_length=20)),
                ('baseline_glucose', models.DecimalField(decimal_places=2, help_text='Glucose reading in the -10m..+5m window around the meal (mg/dL).', max_digits=6)),
                ('peak_glucose', models.DecimalField(decimal_places=2, help_text='Maximum glucose reading in the +0..+120m window (mg/dL).', max_digits=6)),
                ('glucose_at_120m', models.DecimalField(decimal_places=2, help_text='Glucose reading nearest to +120m post-meal (mg/dL).', max_digits=6)),
                ('delta_peak', models.DecimalField(decimal_places=2, help_text='peak_glucose - baseline_glucose (mg/dL).', max_digits=6)),
                ('delta_2h', models.DecimalField(decimal_places=2, help_text='glucose_at_120m - baseline_glucose (mg/dL).', max_digits=6)),
                ('time_to_peak_min', models.PositiveSmallIntegerField(help_text='Minutes from meal_consumed_at to peak_glucose timestamp.')),
                ('computed_at', models.DateTimeField(auto_now_add=True, help_text='When the classifier produced this row.')),
                ('food_entry', models.OneToOneField(help_text='Source FoodEntry. One response per FoodEntry.', on_delete=django.db.models.deletion.CASCADE, related_name='glucose_response', to='health.foodentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'meal glucose response',
                'verbose_name_plural': 'meal glucose responses',
                'ordering': ['-meal_consumed_at'],
                'indexes': [models.Index(fields=['user', '-meal_consumed_at'], name='health_meal_user_id_86659b_idx'), models.Index(fields=['user', 'classification'], name='health_meal_user_id_0780c0_idx')],
            },
        ),
    ]
