# Generated by Django 4.2.27 on 2026-06-27 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0090_meal_glucose_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('event_type', models.CharField(choices=[('started', 'Started'), ('tracking_began', 'Tracking began'), ('paused', 'Paused'), ('resumed', 'Resumed'), ('discontinued', 'Discontinued'), ('dose_changed', 'Dose changed'), ('frequency_changed', 'Frequency changed'), ('provider_changed', 'Provider changed'), ('pharmacy_changed', 'Pharmacy changed'), ('refill', 'Refill')], max_length=24)),
                ('effective_date', models.DateField(help_text='The date the change took effect (user-local).')),
                ('previous_value', models.JSONField(blank=True, help_text='Snapshot of the changed attribute(s) BEFORE the change.', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='Snapshot of the changed attribute(s) AFTER the change.', null=True)),
                ('reason', models.CharField(choices=[('provider_directed', 'Provider directed'), ('side_effect', 'Side effect'), ('cost', 'Cost'), ('effectiveness', 'Effectiveness'), ('user_choice', 'Personal choice'), ('backfill', 'Tracking backfill'), ('unknown', 'Unknown')], default='unknown', max_length=24)),
                ('reason_detail', models.CharField(blank=True, default='', max_length=500)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('scan', 'Scan'), ('pharmacy_doc', 'Pharmacy document'), ('cos_confirmed', 'Chief of Staff (confirmed)'), ('lifecycle', 'Lifecycle'), ('backfill', 'Backfill')], default='lifecycle', max_length=20)),
                ('intake', models.ForeignKey(help_text='The medication/supplement this change belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='health.intake')),
                ('provider', models.ForeignKey(blank=True, help_text='Prescriber associated with this change, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_events', to='health.medicalprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'medication event',
                'verbose_name_plural': 'medication events',
                'ordering': ['-effective_date', '-created_at'],
                'indexes': [models.Index(fields=['intake', '-effective_date'], name='health_medi_intake__651e7d_idx')],
            },
        ),
    ]
