# Generated by Django 4.2.27 on 2026-06-27 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0092_backfill_tracking_began_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('rx_account', models.CharField(blank=True, default='', help_text="The user's account/membership number at this pharmacy.", max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pharmacy',
                'verbose_name_plural': 'pharmacies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='intake',
            name='monitoring_requirements',
            field=models.TextField(blank=True, default='', help_text="What to monitor for this medication (e.g., 'A1c every 3 months')."),
        ),
        migrations.AddField(
            model_name='intake',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Structured prescriber (reuses MedicalProvider). Free-text prescribing_doctor remains as a fallback.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intakes', to='health.medicalprovider'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('rx_number', models.CharField(blank=True, default='', max_length=60)),
                ('written_date', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('refills_authorized', models.PositiveIntegerField(blank=True, null=True)),
                ('refills_remaining', models.PositiveIntegerField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('sig_text', models.TextField(blank=True, default='', help_text='The SIG / directions exactly as written on the prescription.')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='health.intake')),
                ('pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='health.pharmacy')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='health.medicalprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'prescription',
                'verbose_name_plural': 'prescriptions',
                'ordering': ['-written_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='intake',
            name='pharmacy_ref',
            field=models.ForeignKey(blank=True, help_text='Structured pharmacy. Free-text `pharmacy` remains as a fallback.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intakes', to='health.pharmacy'),
        ),
    ]
