# Generated by Django 4.2.27 on 2026-06-27 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0093_pharmacy_intake_monitoring_requirements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationScanDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual entry'), ('bottle_image', 'Bottle image'), ('pharmacy_label', 'Pharmacy label'), ('pharmacy_pdf', 'Pharmacy PDF'), ('med_list', 'Medication list'), ('provider_export', 'Provider export'), ('fhir', 'FHIR'), ('pharmacy_api', 'Pharmacy API')], max_length=24)),
                ('intake_type', models.CharField(choices=[('medication', 'Medication'), ('supplement', 'Supplement')], default='medication', help_text="Declared/extracted type (defaults to the stricter 'medication').", max_length=20)),
                ('extracted_values', models.JSONField(blank=True, default=dict, help_text='Per-field acquired values (name, dose, frequency, sig, provider, pharmacy, quantity, expiration, refills, purpose, strength, ndc).')),
                ('field_confidences', models.JSONField(blank=True, default=dict, help_text='Per-field confidence 0.0–1.0 (parallel to extracted_values).')),
                ('overall_confidence', models.FloatField(blank=True, help_text='Composed overall confidence 0.0–1.0 for the whole record.', null=True)),
                ('evidence', models.JSONField(blank=True, default=list, help_text='Standardized evidence envelope: list of {source_type, source_id, captured_at, confidence, summary}. Evidence supports truth; it is not truth.')),
                ('review_status', models.CharField(choices=[('pending_review', 'Pending review'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending_review', max_length=20)),
                ('confirmation_action', models.CharField(blank=True, choices=[('create', 'Create new'), ('update', 'Update existing'), ('discontinue', 'Discontinue existing'), ('replace', 'Replace existing'), ('ignore', 'Ignore')], default='', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_intake', models.ForeignKey(blank=True, help_text='The canonical Intake this draft confirmed into (create/update).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquisition_drafts', to='health.intake')),
                ('duplicate_of', models.ForeignKey(blank=True, help_text='An existing Intake this draft was detected as a possible duplicate of.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='possible_duplicate_drafts', to='health.intake')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'medication scan draft',
                'verbose_name_plural': 'medication scan drafts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'review_status'], name='health_medi_user_id_a2e3bc_idx')],
            },
        ),
    ]
