# Generated by Django 4.2.27 on 2026-06-27 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0094_medicationscandraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('icd_code', models.CharField(blank=True, default='', max_length=20)),
                ('condition_status', models.CharField(choices=[('active_condition', 'Active'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved')], default='active_condition', max_length=20)),
                ('diagnosed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditions', to='health.medicalprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'medical condition',
                'verbose_name_plural': 'medical conditions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('health_focus', models.CharField(blank=True, default='', help_text='Free-text focus when no structured condition is linked.', max_length=200)),
                ('goal_narrative', models.TextField(blank=True, default='')),
                ('plan_status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=20)),
                ('started_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_plans', to='health.medicalcondition')),
                ('intakes', models.ManyToManyField(blank=True, related_name='treatment_plans', to='health.intake')),
                ('primary_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_plans', to='health.medicalprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'treatment plan',
                'verbose_name_plural': 'treatment plans',
                'ordering': ['-started_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('metric_key', models.CharField(blank=True, choices=[('a1c', 'A1C'), ('fasting_glucose', 'Fasting glucose'), ('glucose_avg', 'Average glucose'), ('glucose_variability', 'Glucose variability'), ('weight', 'Weight'), ('blood_pressure', 'Blood pressure')], default='', help_text='The canonical domain metric this goal watches (optional).', max_length=30)),
                ('direction', models.CharField(choices=[('lower', 'Lower'), ('higher', 'Higher'), ('maintain', 'Maintain')], default='maintain', max_length=10)),
                ('target_value', models.CharField(blank=True, default='', max_length=60)),
                ('notes', models.TextField(blank=True, default='')),
                ('treatment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='health.treatmentplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'treatment goal',
                'verbose_name_plural': 'treatment goals',
                'ordering': ['name'],
            },
        ),
    ]
