# Generated by Django 4.2.27 on 2026-06-27 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0095_medicalcondition_treatmentplan_treatmentgoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationCaptureSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('profile', models.CharField(blank=True, default='', max_length=30)),
                ('intake_type', models.CharField(default='medication', max_length=20)),
                ('images', models.JSONField(blank=True, default=list)),
                ('images_total', models.PositiveIntegerField(default=0)),
                ('images_analyzed', models.PositiveIntegerField(default=0)),
                ('processing_status', models.CharField(choices=[('created', 'Created'), ('analyzing', 'Analyzing'), ('ready', 'Ready'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('current_step', models.CharField(default='Queued', max_length=120)),
                ('merged_extracted', models.JSONField(blank=True, default=dict)),
                ('overall_confidence', models.FloatField(blank=True, null=True)),
                ('quality', models.CharField(blank=True, default='', max_length=40)),
                ('error_message', models.TextField(blank=True, default='')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capture_session', to='health.medicationscandraft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'medication capture session',
                'ordering': ['-created_at'],
            },
        ),
    ]
