# Generated by Django 4.2.27 on 2026-07-12 13:30

import apps.core.current_context
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0098_fix_future_dated_weight_recorded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMeasurementSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('checked_in_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this check-in was taken (gives the time-of-day resolution a date alone lacks, and lets historical imports set an explicit timestamp).')),
                ('title', models.CharField(blank=True, default='', help_text="Optional label, e.g. 'Quarterly check-in' or 'Start of cut'.", max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, choices=[('manual', 'Manual Entry'), ('apple_health', 'Apple Health'), ('renpho', 'RENPHO'), ('inbody', 'InBody'), ('smart_scale', 'Smart Scale'), ('dexa_scan', 'DEXA Scan'), ('other', 'Other')], default='manual', max_length=20)),
                ('sync_id', models.CharField(blank=True, help_text='Unique ID for idempotent import/sync deduplication.', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'body measurement session',
                'verbose_name_plural': 'body measurement sessions',
                'ordering': ['-checked_in_at'],
            },
            bases=(apps.core.current_context.NarratableMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='bodycompositionentry',
            name='source',
            field=models.CharField(blank=True, choices=[('manual', 'Manual Entry'), ('smart_scale', 'Smart Scale'), ('renpho', 'RENPHO'), ('dexa_scan', 'DEXA Scan'), ('bod_pod', 'Bod Pod'), ('inbody', 'InBody Scanner'), ('gym_scan', 'Gym Body Scan'), ('apple_health', 'Apple Health'), ('other', 'Other')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='bodycompositionentry',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Optional check-in this measurement was recorded in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='health.bodymeasurementsession'),
        ),
        migrations.AddField(
            model_name='weightentry',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Optional check-in this weigh-in was recorded in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weight_entries', to='health.bodymeasurementsession'),
        ),
        migrations.CreateModel(
            name='BodyProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('pose', models.CharField(choices=[('front_relaxed', 'Front Relaxed'), ('left_relaxed', 'Left Side Relaxed'), ('right_relaxed', 'Right Side Relaxed'), ('back_relaxed', 'Back Relaxed'), ('front_double_biceps', 'Front Double Biceps')], max_length=30)),
                ('image', models.ImageField(upload_to='health/body_progress/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('session', models.ForeignKey(help_text='The check-in this photo belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='health.bodymeasurementsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'body progress photo',
                'verbose_name_plural': 'body progress photos',
                'ordering': ['session', 'pose'],
                'indexes': [models.Index(fields=['user', 'pose', '-created_at'], name='health_body_user_id_a34623_idx')],
            },
            bases=(apps.core.current_context.NarratableMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='bodymeasurementsession',
            index=models.Index(fields=['user', '-checked_in_at'], name='health_body_user_id_36a5b6_idx'),
        ),
        migrations.AddConstraint(
            model_name='bodymeasurementsession',
            constraint=models.UniqueConstraint(condition=models.Q(('sync_id__gt', '')), fields=('user', 'sync_id'), name='unique_body_session_sync_id'),
        ),
    ]
