# Generated by Django 4.2.27 on 2026-07-15 02:20

import apps.core.current_context
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0102_refresh_sae_after_weight_repair'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthKitDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('metric_key', models.CharField(db_index=True, help_text="Canonical registry key, e.g. 'cycling_distance', 'move_minutes'", max_length=50)),
                ('value', models.DecimalField(decimal_places=3, help_text='The metric value, expressed in `unit`', max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('metric_date', models.DateField(help_text='Local day this daily aggregate is for')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Real sample instant (preserved from HealthKit when available)')),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('apple_health', 'Apple Health'), ('imported', 'Imported')], default='apple_health', max_length=20)),
                ('sync_id', models.CharField(blank=True, db_index=True, help_text='External ID from the synced source to prevent duplicates', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HealthKit daily metric',
                'verbose_name_plural': 'HealthKit daily metrics',
                'ordering': ['-metric_date'],
                'indexes': [models.Index(fields=['user', 'metric_key', '-metric_date'], name='health_heal_user_id_56aa6b_idx')],
            },
            bases=(apps.core.current_context.NarratableMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='healthkitdailymetric',
            constraint=models.UniqueConstraint(fields=('user', 'metric_key', 'metric_date', 'source'), name='unique_hk_daily_metric_per_day_per_source'),
        ),
    ]
