# Generated by Django 4.2.27 on 2026-07-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0103_healthkitdailymetric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='net_content',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Net package contents in net_content_unit (from OFF product_quantity)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='net_content_unit',
            field=models.CharField(blank=True, help_text="Base unit for net_content: 'g' or 'ml'", max_length=10),
        ),
    ]
