# Generated by Django 4.2.27 on 2026-08-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0106_fix_nutrition_double_scaling'),
    ]

    operations = [
        migrations.AddField(
            model_name='intake',
            name='reference_identity_confidence',
            field=models.CharField(blank=True, default='', help_text="exact | ambiguous | unsupported | no_label | '' (not yet attempted)", max_length=20),
        ),
        migrations.AddField(
            model_name='intake',
            name='reference_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='reference_rxcui',
            field=models.CharField(blank=True, default='', help_text='RxNorm concept this medication resolved to (identity authority)', max_length=32),
        ),
        migrations.AddField(
            model_name='intake',
            name='reference_spl_setid',
            field=models.CharField(blank=True, db_index=True, default='', help_text='DailyMed SPL setid of the authoritative label, once resolved', max_length=64),
        ),
    ]
