# Generated by Django 4.2.27 on 2026-09-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0108_remove_erroneous_534_weight_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodentry',
            name='data_source_used',
            field=models.CharField(blank=True, choices=[('local', 'Local Database'), ('fatsecret', 'FatSecret API'), ('openfoodfacts', 'Open Food Facts'), ('unknown', 'Nutrition Unknown'), ('ai_guess', 'AI Estimate'), ('user_override', 'User Override'), ('quick_add', 'Quick Add'), ('manual', 'Manual Entry')], default='manual', help_text='Which data source provided the nutrient values for this entry', max_length=30),
        ),
    ]
