# Generated by Django 5.2.9 on 2025-12-26 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        help_text="e.g., Electronics, Furniture, Appliances, Jewelry",
                        max_length=100,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Living Room, Garage, Master Bedroom",
                        max_length=100,
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Current estimated value",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("model_number", models.CharField(blank=True, max_length=100)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("warranty_expiration", models.DateField(blank=True, null=True)),
                ("warranty_info", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Item",
                "verbose_name_plural": "Inventory Items",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="InventoryPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="life/inventory/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("is_primary", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="life.inventoryitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("repair", "Repair"),
                            ("maintenance", "Maintenance"),
                            ("upgrade", "Upgrade"),
                            ("service", "Service Visit"),
                            ("replacement", "Replacement"),
                            ("inspection", "Inspection"),
                            ("other", "Other"),
                        ],
                        default="maintenance",
                        max_length=20,
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        help_text="e.g., HVAC, Plumbing, Roof, Kitchen", max_length=100
                    ),
                ),
                ("date", models.DateField()),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, help_text="Who did the work?", max_length=200
                    ),
                ),
                ("provider_contact", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True,
                        help_text="When should this be done again?",
                        null=True,
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_logs",
                        to="life.inventoryitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance Log",
                "verbose_name_plural": "Maintenance Logs",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "species",
                    models.CharField(
                        choices=[
                            ("dog", "Dog"),
                            ("cat", "Cat"),
                            ("bird", "Bird"),
                            ("fish", "Fish"),
                            ("rabbit", "Rabbit"),
                            ("hamster", "Hamster"),
                            ("reptile", "Reptile"),
                            ("other", "Other"),
                        ],
                        default="dog",
                        max_length=20,
                    ),
                ),
                ("breed", models.CharField(blank=True, max_length=100)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("adoption_date", models.DateField(blank=True, null=True)),
                ("color", models.CharField(blank=True, max_length=100)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Weight in pounds",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("microchip_id", models.CharField(blank=True, max_length=100)),
                ("veterinarian", models.CharField(blank=True, max_length=200)),
                ("vet_phone", models.CharField(blank=True, max_length=20)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Uncheck if pet has passed away"
                    ),
                ),
                ("passed_date", models.DateField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="life/pets/"),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pet",
                "verbose_name_plural": "Pets",
                "ordering": ["-is_active", "name"],
            },
        ),
        migrations.CreateModel(
            name="PetRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("vet_visit", "Vet Visit"),
                            ("vaccination", "Vaccination"),
                            ("medication", "Medication"),
                            ("grooming", "Grooming"),
                            ("weight", "Weight Check"),
                            ("other", "Other"),
                        ],
                        default="vet_visit",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "next_due_date",
                    models.DateField(
                        blank=True, help_text="When is this needed again?", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="life.pet",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="What is this project about?"
                    ),
                ),
                (
                    "purpose",
                    models.TextField(
                        blank=True, help_text="Why does this project matter to you?"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("now", "Now"),
                            ("soon", "Soon"),
                            ("someday", "Someday"),
                        ],
                        default="someday",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                (
                    "target_date",
                    models.DateField(
                        blank=True,
                        help_text="When would you like to complete this?",
                        null=True,
                    ),
                ),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Home, Travel, Learning, Family",
                        max_length=50,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="Tags for organization"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="life/projects/"
                    ),
                ),
                (
                    "reflection",
                    models.TextField(
                        blank=True, help_text="What did you learn? How did it go?"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LifeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("personal", "Personal"),
                            ("family", "Family"),
                            ("household", "Household"),
                            ("faith", "Faith"),
                            ("health", "Health"),
                            ("work", "Work"),
                            ("social", "Social"),
                            ("travel", "Travel"),
                            ("other", "Other"),
                        ],
                        default="personal",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("is_all_day", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=300)),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurrence_pattern",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'daily', 'weekly', 'monthly', 'yearly'",
                        max_length=50,
                    ),
                ),
                ("recurrence_end_date", models.DateField(blank=True, null=True)),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="ID from external calendar (Google, Outlook)",
                        max_length=255,
                    ),
                ),
                (
                    "external_source",
                    models.CharField(
                        blank=True, help_text="Source calendar provider", max_length=50
                    ),
                ),
                (
                    "reminder_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minutes before event to send reminder",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="life.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Life Event",
                "verbose_name_plural": "Life Events",
                "ordering": ["start_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description or story behind this recipe",
                    ),
                ),
                ("ingredients", models.TextField(help_text="One ingredient per line")),
                ("instructions", models.TextField()),
                (
                    "prep_time_minutes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Preparation time in minutes", null=True
                    ),
                ),
                (
                    "cook_time_minutes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Cooking time in minutes", null=True
                    ),
                ),
                ("servings", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "difficulty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Breakfast, Dinner, Dessert, Holiday",
                        max_length=50,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags like 'vegetarian', 'quick', 'family-favorite'",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Where did this recipe come from?",
                        max_length=200,
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="life/recipes/"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Your variations, tips, or memories"
                    ),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe",
                "verbose_name_plural": "Recipes",
                "ordering": ["-is_favorite", "title"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=300)),
                ("notes", models.TextField(blank=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("now", "Now"),
                            ("soon", "Soon"),
                            ("someday", "Someday"),
                        ],
                        default="someday",
                        max_length=20,
                    ),
                ),
                (
                    "effort",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("quick", "Quick (< 15 min)"),
                            ("small", "Small (< 1 hour)"),
                            ("medium", "Medium (1-3 hours)"),
                            ("large", "Large (half day+)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurrence_pattern",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'daily', 'weekly', 'monthly', 'yearly'",
                        max_length=50,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="life.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["is_completed", "priority", "-created_at"],
            },
        ),
    ]
