# Generated by Django 5.2.9 on 2025-12-26 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("insurance", "Insurance"),
                            ("legal", "Legal Documents"),
                            ("financial", "Financial"),
                            ("medical", "Medical Records"),
                            ("home", "Home & Property"),
                            ("vehicle", "Vehicle"),
                            ("education", "Education"),
                            ("identity", "Identity Documents"),
                            ("warranty", "Warranties & Manuals"),
                            ("tax", "Tax Documents"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload document (PDF, image, or other file)",
                        upload_to="life/documents/%Y/%m/",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, help_text="Auto-detected file type", max_length=50
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "document_date",
                    models.DateField(
                        blank=True,
                        help_text="Date on the document (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True,
                        help_text="When does this document expire?",
                        null=True,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Archived documents are hidden from default view",
                    ),
                ),
                (
                    "related_inventory_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to inventory item (e.g., warranty for appliance)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="life.inventoryitem",
                    ),
                ),
                (
                    "related_pet",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to pet (e.g., vaccination records)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="life.pet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-created_at"],
            },
        ),
    ]
