# Generated by Django 5.2.9 on 2025-12-26 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life", "0002_document"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleCalendarCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField(blank=True)),
                (
                    "token_uri",
                    models.CharField(
                        default="https://oauth2.googleapis.com/token", max_length=500
                    ),
                ),
                ("client_id", models.CharField(max_length=500)),
                ("client_secret", models.CharField(max_length=500)),
                ("token_expiry", models.DateTimeField(blank=True, null=True)),
                (
                    "scopes",
                    models.TextField(blank=True, help_text="JSON list of OAuth scopes"),
                ),
                (
                    "selected_calendar_id",
                    models.CharField(
                        default="primary",
                        help_text="Google Calendar ID to sync with",
                        max_length=500,
                    ),
                ),
                (
                    "selected_calendar_name",
                    models.CharField(
                        blank=True,
                        help_text="Display name of selected calendar",
                        max_length=200,
                    ),
                ),
                (
                    "sync_direction",
                    models.CharField(
                        choices=[
                            ("import", "Import Only (Google → App)"),
                            ("export", "Export Only (App → Google)"),
                            ("both", "Two-Way Sync"),
                        ],
                        default="import",
                        max_length=20,
                    ),
                ),
                (
                    "days_past",
                    models.PositiveIntegerField(
                        default=0, help_text="Days in the past to sync"
                    ),
                ),
                (
                    "days_future",
                    models.PositiveIntegerField(
                        default=30, help_text="Days in the future to sync"
                    ),
                ),
                (
                    "sync_event_types",
                    models.TextField(
                        default='["personal", "family", "work", "health", "social", "travel"]',
                        help_text="JSON list of event types to sync",
                    ),
                ),
                (
                    "auto_sync_enabled",
                    models.BooleanField(
                        default=False, help_text="Automatically sync on page load"
                    ),
                ),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("last_sync_status", models.CharField(blank=True, max_length=50)),
                ("last_sync_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_calendar_credential",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Calendar Credential",
                "verbose_name_plural": "Google Calendar Credentials",
            },
        ),
    ]
