# Generated by Django 5.2.9 on 2025-12-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life", "0003_googlecalendarcredential"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="created_via",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Entry"),
                    ("ai_camera", "AI Camera Scan"),
                    ("import", "Data Import"),
                    ("api", "API"),
                ],
                default="manual",
                help_text="How this entry was created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="created_via",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Entry"),
                    ("ai_camera", "AI Camera Scan"),
                    ("import", "Data Import"),
                    ("api", "API"),
                ],
                default="manual",
                help_text="How this entry was created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lifeevent",
            name="created_via",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Entry"),
                    ("ai_camera", "AI Camera Scan"),
                    ("import", "Data Import"),
                    ("api", "API"),
                ],
                default="manual",
                help_text="How this entry was created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="created_via",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Entry"),
                    ("ai_camera", "AI Camera Scan"),
                    ("import", "Data Import"),
                    ("api", "API"),
                ],
                default="manual",
                help_text="How this entry was created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="created_via",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Entry"),
                    ("ai_camera", "AI Camera Scan"),
                    ("import", "Data Import"),
                    ("api", "API"),
                ],
                default="manual",
                help_text="How this entry was created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="created_via",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Entry"),
                    ("ai_camera", "AI Camera Scan"),
                    ("import", "Data Import"),
                    ("api", "API"),
                ],
                default="manual",
                help_text="How this entry was created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="created_via",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Entry"),
                    ("ai_camera", "AI Camera Scan"),
                    ("import", "Data Import"),
                    ("api", "API"),
                ],
                default="manual",
                help_text="How this entry was created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="created_via",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Entry"),
                    ("ai_camera", "AI Camera Scan"),
                    ("import", "Data Import"),
                    ("api", "API"),
                ],
                default="manual",
                help_text="How this entry was created",
                max_length=20,
            ),
        ),
    ]
