# Generated by Django on 2025-12-28
# Data migration to recalculate task priorities based on due date

from django.db import migrations
from django.utils import timezone


def recalculate_task_priorities(apps, schema_editor):
    """
    Recalculate priority for all tasks based on their due date.

    Priority rules:
    - Now: Due today or overdue
    - Soon: Due within 7 days
    - Someday: No due date or due date > 7 days away
    """
    Task = apps.get_model('life', 'Task')
    today = timezone.now().date()

    updated_count = 0

    for task in Task.objects.all():
        if not task.due_date:
            new_priority = 'someday'
        else:
            days_until_due = (task.due_date - today).days
            if days_until_due <= 0:
                new_priority = 'now'
            elif days_until_due <= 7:
                new_priority = 'soon'
            else:
                new_priority = 'someday'

        if task.priority != new_priority:
            task.priority = new_priority
            task.save(update_fields=['priority'])
            updated_count += 1

    if updated_count > 0:
        print(f"  Updated priority for {updated_count} task(s)")


def reverse_migration(apps, schema_editor):
    """No reverse action needed - priorities can be recalculated again."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0004_add_created_via_field'),
    ]

    operations = [
        migrations.RunPython(recalculate_task_priorities, reverse_migration),
    ]
