# Generated by Django 5.2.9 on 2025-12-31 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("life", "0005_recalculate_task_priorities"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SignificantEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_via",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("ai_camera", "AI Camera Scan"),
                            ("import", "Data Import"),
                            ("api", "API"),
                        ],
                        default="manual",
                        help_text="How this entry was created",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., Mom's Birthday, Wedding Anniversary",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional notes about this event"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("birthday", "Birthday"),
                            ("anniversary", "Anniversary"),
                            ("memorial", "Memorial / In Memory"),
                            ("milestone", "Milestone"),
                            ("holiday", "Personal Holiday"),
                            ("other", "Other"),
                        ],
                        default="birthday",
                        max_length=20,
                    ),
                ),
                (
                    "event_date",
                    models.DateField(
                        help_text="The date of the event (year used for calculating years/age)"
                    ),
                ),
                (
                    "original_year",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Year the event started (for calculating anniversaries, ages)",
                        null=True,
                    ),
                ),
                (
                    "person_name",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Mom, John & Jane, Grandpa",
                        max_length=200,
                    ),
                ),
                (
                    "sms_reminder_enabled",
                    models.BooleanField(
                        default=False, help_text="Send SMS reminders for this event"
                    ),
                ),
                (
                    "reminder_days",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Days before event to send reminders (e.g., [7, 3, 1, 0])",
                    ),
                ),
                (
                    "custom_message",
                    models.TextField(
                        blank=True,
                        help_text="Custom message to include in reminders (e.g., Gift ideas: Books, flowers)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Significant Event",
                "verbose_name_plural": "Significant Events",
                "ordering": ["event_date"],
            },
        ),
    ]
