# Generated by Django 4.2.27 on 2026-01-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0007_task_start_date_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecalendarcredential',
            name='access_token',
            field=models.TextField(help_text='Encrypted access token'),
        ),
        migrations.AlterField(
            model_name='googlecalendarcredential',
            name='client_secret',
            field=models.CharField(help_text='Encrypted client secret', max_length=500),
        ),
        migrations.AlterField(
            model_name='googlecalendarcredential',
            name='refresh_token',
            field=models.TextField(blank=True, help_text='Encrypted refresh token'),
        ),
    ]
