# Generated by Django 4.2.27 on 2026-01-16 19:17

import apps.life.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0008_alter_googlecalendarcredential_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='Upload document (PDF, image, or other file)', storage=apps.life.models.get_document_storage, upload_to='life/documents/%Y/%m/'),
        ),
    ]
