# Generated by Django 4.2.27 on 2026-01-17 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('life', '0009_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='email_source_date',
            field=models.DateTimeField(blank=True, help_text='Original email date', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='email_source_id',
            field=models.CharField(blank=True, db_index=True, help_text='Gmail message ID if created from email', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='email_source_sender',
            field=models.CharField(blank=True, help_text='Original email sender', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='email_source_subject',
            field=models.CharField(blank=True, help_text='Original email subject', max_length=500),
        ),
        migrations.CreateModel(
            name='GmailCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(help_text='Encrypted access token')),
                ('refresh_token', models.TextField(blank=True, help_text='Encrypted refresh token')),
                ('token_uri', models.CharField(default='https://oauth2.googleapis.com/token', max_length=500)),
                ('client_id', models.CharField(max_length=500)),
                ('client_secret', models.CharField(help_text='Encrypted', max_length=500)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.TextField(blank=True, help_text='JSON list of OAuth scopes')),
                ('scan_enabled', models.BooleanField(default=True, help_text='Enable automatic inbox scanning')),
                ('max_emails_per_scan', models.PositiveIntegerField(default=20, help_text='Maximum emails to process per scan')),
                ('days_to_look_back', models.PositiveIntegerField(default=3, help_text='Only scan emails from the last N days')),
                ('last_scan', models.DateTimeField(blank=True, null=True)),
                ('last_scan_status', models.CharField(blank=True, max_length=50)),
                ('last_scan_message', models.TextField(blank=True)),
                ('last_scan_tasks_created', models.PositiveIntegerField(default=0)),
                ('last_scan_errors', models.TextField(blank=True, help_text='JSON list of errors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_credential', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gmail Credential',
                'verbose_name_plural': 'Gmail Credentials',
            },
        ),
        migrations.CreateModel(
            name='ProcessedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(db_index=True, max_length=255)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('action_items_found', models.PositiveIntegerField(default=0)),
                ('tasks_created', models.PositiveIntegerField(default=0)),
                ('skipped_reason', models.CharField(blank=True, help_text="e.g., 'no_action_items', 'ai_error'", max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processed Email',
                'verbose_name_plural': 'Processed Emails',
                'ordering': ['-processed_at'],
                'unique_together': {('user', 'gmail_message_id')},
            },
        ),
    ]
