# Generated by Django 4.2.27 on 2026-02-17 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('life', '0010_gmail_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('name', models.CharField(help_text="List name (e.g., 'Week 3 Meal Prep', 'Protein Sources')", max_length=200)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether all items have been purchased')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the list was completed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Shopping list notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'shopping list',
                'verbose_name_plural': 'shopping lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('name', models.CharField(help_text='Item name', max_length=200)),
                ('quantity', models.CharField(blank=True, help_text="Quantity (e.g., '2 lbs', '1 dozen', '3')", max_length=50)),
                ('category', models.CharField(choices=[('produce', 'Produce'), ('protein', 'Protein'), ('dairy', 'Dairy'), ('grains', 'Grains'), ('frozen', 'Frozen'), ('pantry', 'Pantry'), ('beverages', 'Beverages'), ('supplements', 'Supplements'), ('household', 'Household'), ('other', 'Other')], default='other', max_length=20)),
                ('is_purchased', models.BooleanField(default=False)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='life.shoppinglist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'shopping item',
                'verbose_name_plural': 'shopping items',
                'ordering': ['is_purchased', 'category', 'name'],
            },
        ),
    ]
