# Generated by Django 4.2.27 on 2026-02-18 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_relationships', '0001_initial'),
        ('life', '0011_shoppinglist_shoppingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='significantevent',
            name='person',
            field=models.ForeignKey(blank=True, help_text='Optional link to tracked Person record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='significant_events', to='ai_relationships.person'),
        ),
    ]
