# Generated by Django 4.2.27 on 2026-02-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0012_significantevent_person_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress_percentage',
            field=models.PositiveSmallIntegerField(default=0, help_text="0-100 progress percentage. >0 counts as 'worked on' for conflict detection."),
        ),
        migrations.AddField(
            model_name='task',
            name='progress_state',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible progress state (e.g. steps completed, notes on progress)'),
        ),
    ]
