# Generated by Django 4.2.27 on 2026-02-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0013_cos_phase1_task_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated duration in minutes for calendar block sizing', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_routine',
            field=models.BooleanField(default=False, help_text='Whether this is a daily routine task (Quiet Time, Workout, etc.)'),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Scheduled time of day for routine tasks (e.g., 06:00)', null=True),
        ),
    ]
