# Generated by Django 4.2.27 on 2026-02-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0014_add_routine_task_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='scheduled_end_time',
            field=models.TimeField(blank=True, help_text='Scheduled end time for routine tasks (e.g., 06:30)', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated duration in minutes (computed from times or set manually)', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Scheduled start time for routine tasks (e.g., 06:00)', null=True),
        ),
    ]
