# Generated by Django 4.2.27 on 2026-03-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0015_add_scheduled_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='module',
            field=models.CharField(blank=True, choices=[('faith', 'Faith'), ('health', 'Health'), ('journal', 'Journal'), ('purpose', 'Purpose'), ('life', 'Life')], help_text='Link task to a module for cross-module engagement tracking', max_length=20),
        ),
    ]
