# Generated by Django 4.2.27 on 2026-03-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0016_task_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_completed', 'priority', 'scheduled_time', '-created_at'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
