# Generated by Django 4.2.27 on 2026-03-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0018_recipebulkimportsession_recipebulkimportphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipebulkimportphoto',
            name='photo_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('extracted', 'Extracted'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='recipebulkimportsession',
            name='import_status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploading', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipebulkimportphoto',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='recipebulkimportsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10),
        ),
    ]
