# Generated by Django 4.2.27 on 2026-03-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0019_recipebulkimportphoto_photo_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipebulkimportphoto',
            name='image_url',
            field=models.URLField(blank=True, help_text='Cloudinary CDN URL captured at upload time for worker access', max_length=500),
        ),
    ]
