# Generated by Django 4.2.27 on 2026-03-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0021_task_completion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='commitment_level',
            field=models.CharField(choices=[('optional', 'Optional'), ('important', 'Important'), ('non_negotiable', 'Non-Negotiable')], default='important', help_text='Non-negotiable tasks trigger coaching if skipped repeatedly', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='last_skipped_at',
            field=models.DateTimeField(blank=True, help_text='When the task was last skipped (for recency guard)', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='skip_streak',
            field=models.PositiveSmallIntegerField(default=0, help_text='Consecutive skip count for tracking patterns'),
        ),
    ]
