# Generated by Django 4.2.27 on 2026-03-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0023_purge_approve_payroll'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completion_status', 'priority', 'due_date', 'scheduled_time', '-created_at'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
