# Generated by Django 4.2.27 on 2026-03-14 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purpose', '0008_habitgoal_commitment_level_habitgoallink'),
        ('life', '0024_alter_task_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGoalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_links', to='purpose.lifegoal')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_links', to='life.task')),
            ],
            options={
                'verbose_name': 'Task-Goal Link',
                'verbose_name_plural': 'Task-Goal Links',
                'unique_together': {('task', 'goal')},
            },
        ),
    ]
