# Generated by Django 4.2.27 on 2026-03-17 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0025_taskgoallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(help_text='Signal taxonomy type (e.g., health_activity, cognitive_fitness)', max_length=30)),
                ('domain', models.CharField(help_text='LifeDomain slug (e.g., health, brain_training)', max_length=20)),
                ('confidence', models.FloatField(help_text='Extraction confidence 0.0-1.0')),
                ('extracted_text', models.TextField(help_text='The text or category that indicates this signal')),
                ('direction', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], default='positive', help_text='Signal direction', max_length=10)),
                ('extractor_type', models.CharField(help_text='Which extractor produced this (category_rule, keyword_rule, llm)', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_signals', to='life.document')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', 'signal_type'], name='life_docume_documen_4380e9_idx')],
            },
        ),
    ]
