# Generated by Django 4.2.27 on 2026-03-18 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('life', '0026_phase55_extraction_signals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('time_of_day', models.CharField(choices=[('morning', 'Morning'), ('mid_morning', 'Mid-Morning'), ('lunch', 'Lunch'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('nightly', 'Nightly')], help_text='Default grouping for this routine', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoutineSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of this routine item (e.g., 'Prayer time', 'Shower')", max_length=200)),
                ('scheduled_time', models.TimeField(help_text='When this item should be done')),
                ('grace_period_minutes', models.PositiveIntegerField(default=30, help_text='Minutes after scheduled_time before marking late')),
                ('days_of_week', models.CharField(default='0,1,2,3,4,5,6', help_text='Comma-separated day numbers (0=Mon, 6=Sun)', max_length=20)),
                ('specific_date', models.DateField(blank=True, help_text='If set, this item only applies to this specific date', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='life.routine')),
            ],
            options={
                'ordering': ['sort_order', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='RoutineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('scheduled_date', models.DateField(help_text='The date this routine item was scheduled for')),
                ('log_status', models.CharField(choices=[('completed', 'Completed'), ('completed_late', 'Completed Late'), ('skipped', 'Skipped')], max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the item was completed (null for skipped)', null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='life.routineschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'routine log',
                'verbose_name_plural': 'routine logs',
                'ordering': ['-scheduled_date'],
                'unique_together': {('schedule', 'scheduled_date')},
            },
        ),
    ]
