# Generated by Django 4.2.27 on 2026-03-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0026_phase55_extraction_signals'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of file content for dedup/change detection', max_length=64),
        ),
        migrations.AddField(
            model_name='document',
            name='extracted_at',
            field=models.DateTimeField(blank=True, help_text='When content extraction completed', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='extraction_quality',
            field=models.FloatField(blank=True, help_text='Extraction quality estimate 0.0-1.0', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('not_applicable', 'Not Applicable')], default='pending', help_text='Content extraction pipeline status', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='raw_text',
            field=models.TextField(blank=True, default='', help_text='Extracted text content from file (PDF text or OCR)'),
        ),
    ]
