# Generated by Django 4.2.27 on 2026-03-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0027_phase6a_knowledge_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedemail',
            name='classification',
            field=models.CharField(blank=True, choices=[('keep', 'Keep — extract facts'), ('skip', 'Skip — no useful facts'), ('uncertain', 'Uncertain — LLM classified')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='processedemail',
            name='classification_confidence',
            field=models.FloatField(default=0.0, help_text='Classification confidence score'),
        ),
        migrations.AddField(
            model_name='processedemail',
            name='classification_reason',
            field=models.CharField(blank=True, default='', help_text='Rule or LLM reason for classification', max_length=200),
        ),
        migrations.AddField(
            model_name='processedemail',
            name='facts_created_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of ExtractedFact records created'),
        ),
        migrations.AddField(
            model_name='processedemail',
            name='facts_extracted',
            field=models.BooleanField(default=False, help_text='Whether fact extraction has been run'),
        ),
        migrations.AddField(
            model_name='processedemail',
            name='received_date',
            field=models.DateTimeField(blank=True, help_text='When the email was received', null=True),
        ),
        migrations.AddField(
            model_name='processedemail',
            name='sender',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='processedemail',
            name='snippet',
            field=models.CharField(blank=True, default='', help_text='First ~500 chars for review context', max_length=500),
        ),
        migrations.AddField(
            model_name='processedemail',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
