# Generated by Django 4.2.27 on 2026-03-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0027_behavior_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinelog',
            name='is_user_corrected',
            field=models.BooleanField(default=False, help_text='True when user has manually edited a past log'),
        ),
    ]
