# Generated by Django 4.2.27 on 2026-03-17 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('life', '0028_phase6b_email_intelligence'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.CharField(choices=[('upload', 'User Upload'), ('email', 'Email Attachment'), ('scan', 'Receipt Scan')], default='upload', help_text='How this document was created', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='source_id',
            field=models.CharField(blank=True, default='', help_text='Source record ID (e.g., Gmail message ID)', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='subcategory',
            field=models.CharField(blank=True, default='', help_text="Sub-category (e.g., 'receipt', 'statement', 'bill')", max_length=50),
        ),
        migrations.CreateModel(
            name='EmailClassificationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(help_text='Email sender address (normalized to lowercase)', max_length=255)),
                ('original_classification', models.CharField(blank=True, default='', help_text='What the system originally classified this as', max_length=20)),
                ('corrected_classification', models.CharField(choices=[('keep', 'Always Keep'), ('skip', 'Always Skip')], help_text='What the user wants emails from this sender classified as', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_classification_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Classification Feedback',
                'verbose_name_plural': 'Email Classification Feedback',
                'indexes': [models.Index(fields=['user', 'corrected_classification'], name='idx_email_feedback_user_class')],
                'unique_together': {('user', 'sender')},
            },
        ),
    ]
