# Generated by Django 4.2.27 on 2026-03-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0029_phase6b_completion'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'email')), fields=('user', 'source', 'source_id'), name='unique_email_source_document'),
        ),
    ]
