# Generated by Django 4.2.27 on 2026-03-18 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0027_behavior_system'),
        ('life', '0030_document_unique_email_source_document'),
    ]

    operations = [
    ]
