# Generated by Django 4.2.27 on 2026-03-18 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0028_user_corrected_field'),
        ('life', '0030_document_unique_email_source_document'),
    ]

    operations = [
    ]
