# Generated by Django 4.2.27 on 2026-03-18 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0031_merge_20260318_0251'),
        ('life', '0031_merge_20260318_0254'),
    ]

    operations = [
    ]
