# Generated by Django 4.2.27 on 2026-03-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0032_merge_20260318_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_foundational',
            field=models.BooleanField(default=False, help_text='Fallback foundational flag for standalone tasks. Dashboard prefers linked goal/habit foundational status.'),
        ),
    ]
