# Generated by Django 4.2.27 on 2026-03-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0034_fix_routine_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineschedule',
            name='importance',
            field=models.CharField(choices=[('foundational', 'Foundational'), ('important', 'Important'), ('flexible', 'Flexible')], default='flexible', help_text='Priority tier: foundational > important > flexible', max_length=20),
        ),
    ]
