# Generated by Django 4.2.27 on 2026-03-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0035_routineschedule_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='grace_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text='Minutes of grace after scheduled_time before marking overdue (0 = immediate)'),
        ),
    ]
