# Generated by Django 4.2.27 on 2026-03-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0036_task_grace_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='commitment_level',
            field=models.CharField(choices=[('foundational', 'Foundational'), ('important', 'Important'), ('flexible', 'Flexible')], default='important', help_text='Non-negotiable tasks trigger coaching if skipped repeatedly', max_length=20),
        ),
    ]
