# Generated by Django 4.2.27 on 2026-03-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0038_convert_commitment_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinelog',
            name='rescheduled_time',
            field=models.TimeField(blank=True, help_text='Override time for same-day reschedule (log-level only, never modifies template)', null=True),
        ),
        migrations.AlterField(
            model_name='routinelog',
            name='log_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('completed_late', 'Completed Late'), ('skipped', 'Skipped'), ('rescheduled', 'Rescheduled')], max_length=20),
        ),
    ]
