# Generated by Django 4.2.27 on 2026-03-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0039_routine_log_reschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinelog',
            name='reschedule_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of times this item was rescheduled today (awareness only, no penalty)'),
        ),
    ]
