# Generated by Django 4.2.27 on 2026-03-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0040_routine_log_reschedule_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='matched_schedule_id',
            field=models.IntegerField(blank=True, help_text='RoutineSchedule ID this log was linked to (soft ref)', null=True),
        ),
        migrations.AddField(
            model_name='routineschedule',
            name='creates_maintenance_log',
            field=models.BooleanField(default=False, help_text='Prompt to create a maintenance log when this item is completed'),
        ),
        migrations.AddField(
            model_name='routineschedule',
            name='default_maintenance_title',
            field=models.CharField(blank=True, help_text='Default title for maintenance entry. Falls back to item name.', max_length=200),
        ),
        migrations.AddField(
            model_name='routineschedule',
            name='follow_up_days',
            field=models.PositiveIntegerField(blank=True, help_text='Days until follow-up. Suggests follow_up_date on maintenance form.', null=True),
        ),
        migrations.AddField(
            model_name='routineschedule',
            name='maintenance_area',
            field=models.CharField(blank=True, help_text='Default area (e.g., HVAC, Jeep, Yard)', max_length=100),
        ),
        migrations.AddField(
            model_name='routineschedule',
            name='maintenance_type',
            field=models.CharField(blank=True, choices=[('repair', 'Repair'), ('maintenance', 'Maintenance'), ('upgrade', 'Upgrade'), ('service', 'Service Visit'), ('replacement', 'Replacement'), ('inspection', 'Inspection'), ('other', 'Other')], default='maintenance', help_text='Default log type for the maintenance entry', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='lifeevent',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipebulkimportphoto',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipebulkimportsession',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='routine',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='routinelog',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='significantevent',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
    ]
