# Generated by Django 4.2.27 on 2026-03-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0041_routine_maintenance_bridge'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinelog',
            name='maintenance_logged',
            field=models.BooleanField(default=False, help_text='True when maintenance was logged from this completion'),
        ),
        migrations.AddField(
            model_name='routineschedule',
            name='last_maintenance_date',
            field=models.DateField(blank=True, help_text='Date of last maintenance log created from this routine item.', null=True),
        ),
    ]
