# Generated by Django 4.2.27 on 2026-03-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0042_routine_maintenance_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinelog',
            name='completed_as_scheduled',
            field=models.BooleanField(default=False, help_text='User asserts completion happened at the scheduled time, even if logged later. Treated as on-time for scoring/streaks.'),
        ),
    ]
