# Generated by Django 4.2.27 on 2026-03-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0044_backfill_completed_as_scheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineschedule',
            name='obligation_type',
            field=models.CharField(blank=True, choices=[('', 'General (no bridge)'), ('workout', 'Workout'), ('journal', 'Journal'), ('faith_prayer', 'Faith — Prayer'), ('faith_bible', 'Faith — Bible Reading')], default='', help_text="If set, tells the compliance engine this routine item represents an obligation in another domain (e.g., a 'Workout' routine item bridges to the workout domain). This replaces name-based matching.", max_length=20),
        ),
    ]
