# Generated by Django 4.2.27 on 2026-03-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0044_backfill_completed_as_scheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinelog',
            name='completion_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('workout', 'Workout'), ('medicine', 'Medicine'), ('bible', 'Bible Reading'), ('auto', 'Auto')], default='manual', help_text='How this log was created: manual toggle, workout session, etc.', max_length=20),
        ),
        migrations.AddField(
            model_name='routinelog',
            name='source_object_id',
            field=models.PositiveIntegerField(blank=True, help_text="PK of the source object that triggered this completion. Combined with completion_source, provides full traceability (e.g., completion_source='workout' + source_object_id=42 → WorkoutSession pk=42).", null=True),
        ),
        migrations.AddField(
            model_name='routineschedule',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('workout', 'Workout'), ('journal', 'Journal'), ('bible', 'Bible Reading'), ('faith', 'Faith')], help_text='When routine_type=activity, which data source drives completion', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='routineschedule',
            name='routine_type',
            field=models.CharField(choices=[('binary', 'Binary'), ('activity', 'Activity')], default='binary', help_text='Binary = manual toggle, Activity = derives completion from real data', max_length=20),
        ),
    ]
