# Generated by Django 4.2.27 on 2026-03-23 02:01

from django.db import migrations


def backfill_workout_types(apps, schema_editor):
    """
    Backfill RoutineSchedule items with 'workout' in their name to
    routine_type='activity', activity_type='workout'.

    This is part of the workout-first architecture (Phase 2): existing
    workout-related routine items are migrated from binary (manual toggle)
    to activity (data-driven completion).
    """
    RoutineSchedule = apps.get_model('life', 'RoutineSchedule')
    updated = RoutineSchedule.objects.filter(
        name__icontains='workout',
    ).update(routine_type='activity', activity_type='workout')
    if updated:
        print(f"  Backfilled {updated} RoutineSchedule(s) to activity/workout")


def reverse_backfill(apps, schema_editor):
    """Reverse: reset all activity/workout schedules back to binary."""
    RoutineSchedule = apps.get_model('life', 'RoutineSchedule')
    RoutineSchedule.objects.filter(
        routine_type='activity', activity_type='workout',
    ).update(routine_type='binary', activity_type=None)


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0045_workout_routine_integration'),
    ]

    operations = [
        migrations.RunPython(backfill_workout_types, reverse_backfill),
    ]
