# Generated by Django 4.2.27 on 2026-03-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0046_backfill_obligation_type'),
        ('life', '0046_backfill_workout_routine_types'),
    ]

    operations = [
    ]
