# Generated by Django 4.2.27 on 2026-03-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0047_merge_20260323_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinelog',
            name='performed_at',
            field=models.DateTimeField(blank=True, help_text='When the activity actually happened (vs completed_at = click time)', null=True),
        ),
        migrations.AddField(
            model_name='routinelog',
            name='timing',
            field=models.CharField(blank=True, choices=[('on_time', 'On Time'), ('late', 'Late'), ('early', 'Early')], default='', help_text='Timing classification based on grace window (on_time, late, early)', max_length=10),
        ),
        migrations.AlterField(
            model_name='routinelog',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the user clicked complete (click timestamp)', null=True),
        ),
        migrations.AlterField(
            model_name='routinelog',
            name='completion_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('workout', 'Workout'), ('medicine', 'Medicine'), ('bible', 'Bible Reading'), ('auto', 'Auto'), ('scheduled_override', 'Scheduled Override')], default='manual', help_text='How this log was created: manual toggle, workout session, etc.', max_length=25),
        ),
    ]
