# Generated by Django 4.2.27 on 2026-03-23 14:26

from django.db import migrations, models


def populate_performed_at(apps, schema_editor):
    """Backfill performed_at and timing for existing completed RoutineLog records.

    Uses completed_at as best available data for performed_at.
    Sets timing='late' as safe default (we can't retroactively infer truth).
    """
    RoutineLog = apps.get_model('life', 'RoutineLog')
    RoutineLog.objects.filter(
        log_status__in=('completed', 'completed_late'),
        performed_at__isnull=True,
    ).update(
        performed_at=models.F('completed_at'),
        timing='late',
    )


def reverse_populate(apps, schema_editor):
    """Reverse: clear performed_at and timing."""
    RoutineLog = apps.get_model('life', 'RoutineLog')
    RoutineLog.objects.update(performed_at=None, timing='')


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0048_add_routine_execution_truth'),
    ]

    operations = [
        migrations.RunPython(populate_performed_at, reverse_populate),
    ]
