# Generated by Django 4.2.27 on 2026-03-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0049_populate_routine_execution_truth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routinelog',
            name='completion_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('workout', 'Workout'), ('medicine', 'Medicine'), ('bible', 'Bible Reading'), ('faith', 'Faith'), ('journal', 'Journal Entry'), ('auto', 'Auto'), ('scheduled_override', 'Scheduled Override')], default='manual', help_text='How this log was created: manual toggle, workout session, etc.', max_length=25),
        ),
    ]
