# Generated by Django 4.2.27 on 2026-04-02 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0050_alter_routinelog_completion_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinelog',
            name='routine_at_time',
            field=models.ForeignKey(blank=True, help_text='Routine this schedule belonged to when this log was created. IMMUTABLE after creation — set once at write time, never updated. Null for logs created before move-tracking was added; consumers fall back to schedule.routine for null values.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='life.routine'),
        ),
    ]
