# Generated by Django 4.2.27 on 2026-04-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0051_add_routine_at_time_to_routinelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='depends_on_key',
            field=models.CharField(blank=True, db_index=True, help_text="Canonical key of prerequisite item. Format: 'task:{pk}', 'routine:{schedule_id}', or 'domain:{name}'. When set and hide_until_ready is True, this task is hidden from today's actionable list until the prerequisite is complete.", max_length=64),
        ),
        migrations.AddField(
            model_name='task',
            name='hide_until_ready',
            field=models.BooleanField(default=True, help_text='When True and depends_on_key is set, this task is excluded from Today Engine / execution contract / CoS until the prereq completes.'),
        ),
    ]
