# Generated by Django 4.2.27 on 2026-04-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0052_task_depends_on_key_task_hide_until_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='depends_on_key',
            field=models.CharField(blank=True, db_index=True, help_text="Canonical key of prerequisite item. Accepted formats: 'task:{pk}' | 'routine:{schedule_id}' | 'domain:{name}'. All parsing is centralized in apps/core/execution/dependency_gating.py — do not interpret this field elsewhere. Invalid / unresolvable keys fail open (task is shown, not blocked).", max_length=64),
        ),
    ]
