# Generated by Django 4.2.27 on 2026-07-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0053_alter_task_depends_on_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineschedule',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('workout', 'Workout'), ('journal', 'Journal'), ('bible', 'Bible Reading'), ('faith', 'Faith'), ('prayer', 'Prayer'), ('nutrition_anchor', 'Nutrition / Food Log'), ('weigh_in', 'Weigh-In'), ('measurement', 'Body Measurement')], help_text='When routine_type=activity, which data source drives completion', max_length=20, null=True),
        ),
    ]
