# Generated by Django 4.2.27 on 2026-07-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0056_collapse_dual_defined_routines'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_plain',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='purpose_plain',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='reflection_plain',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
