# Generated by Django 4.2.27 on 2026-09-13 23:43

import apps.life.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0060_cleanup_cos_writepath_test_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='original_filename',
            field=models.CharField(blank=True, default='', help_text='The filename the user uploaded, as they know it. The storage key is internal.', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='upload_token',
            field=models.CharField(blank=True, help_text='Idempotency token from the upload form (unique per user).', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='Upload document (PDF, image, or other file)', max_length=500, storage=apps.life.models.get_document_storage, upload_to=apps.life.models.document_upload_path),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('upload_token__isnull', False)), fields=('user', 'upload_token'), name='unique_document_upload_token'),
        ),
    ]
