# Generated by Django 4.2.27 on 2026-03-01 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0100_personaloperatingblueprint_eae_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Optional title. If blank, derived from body preview.', max_length=200)),
                ('body', models.TextField(help_text='Note content.')),
                ('color', models.CharField(choices=[('default', 'Default'), ('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('pink', 'Pink')], default='default', help_text='Visual color code for the note card.', max_length=10)),
                ('is_pinned', models.BooleanField(db_index=True, default=False, help_text='Pinned notes appear first in the list.')),
                ('word_count', models.PositiveIntegerField(default=0, editable=False)),
                ('tags', models.ManyToManyField(blank=True, related_name='notes', to='core.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='ID of the attached entity.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(help_text='Type of the attached entity.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='notes.note')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='noteattach_entity'), models.Index(fields=['note', 'content_type'], name='noteattach_note_ct')],
                'unique_together': {('note', 'content_type', 'object_id')},
            },
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'status', '-is_pinned', '-updated_at'], name='notes_user_status_pin_updated'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'color'], name='notes_user_color'),
        ),
    ]
