# Generated by Django 4.2.27 on 2026-03-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_populate_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='attachments_text',
            field=models.TextField(blank=True, default='', editable=False, help_text='Denormalized attachment display strings for full-text search indexing.'),
        ),
        migrations.AddField(
            model_name='note',
            name='tags_text',
            field=models.TextField(blank=True, default='', editable=False, help_text='Denormalized tag names for full-text search indexing.'),
        ),
    ]
