# Generated by Django 4.2.27 on 2026-03-01 16:31

from django.contrib.postgres.search import SearchVector
from django.db import migrations

BATCH_SIZE = 500


def backfill_tags_and_attachments_text(apps, schema_editor):
    """
    Backfill tags_text and attachments_text for all existing notes,
    then recompute search_vector to include the new fields.
    """
    # SearchVector requires PostgreSQL — skip on SQLite (CI test database)
    if schema_editor.connection.vendor != "postgresql":
        return

    Note = apps.get_model("notes", "Note")
    NoteAttachment = apps.get_model("notes", "NoteAttachment")
    ContentType = apps.get_model("contenttypes", "ContentType")

    all_notes = Note.objects.all().order_by("pk")
    total = all_notes.count()
    if total == 0:
        return

    # Pre-fetch all note-tag relationships
    NoteTagThrough = Note.tags.through
    tag_map = {}  # note_id -> list of tag names
    Tag = apps.get_model("core", "Tag")
    for through in NoteTagThrough.objects.select_related().all():
        tag_map.setdefault(through.note_id, [])
    # Get tag names via a join
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT nt.note_id, t.name
            FROM notes_note_tags nt
            JOIN core_tag t ON t.id = nt.tag_id
            ORDER BY nt.note_id
            """
        )
        for note_id, tag_name in cursor.fetchall():
            tag_map.setdefault(note_id, []).append(tag_name)

    # Pre-fetch all attachments with their content types
    att_map = {}  # note_id -> list of display strings
    for att in NoteAttachment.objects.select_related("content_type").all():
        ct = att.content_type
        model_class = ct.model_class()
        if model_class is None:
            continue
        try:
            entity = model_class.objects.get(pk=att.object_id)
            verbose = model_class._meta.verbose_name.title()
            display = (
                getattr(entity, "display_title", None)
                or getattr(entity, "title", None)
                or getattr(entity, "name", None)
                or str(entity)
            )
            att_map.setdefault(att.note_id, []).append(f"{verbose}: {display}")
        except model_class.DoesNotExist:
            pass

    # Batch update tags_text and attachments_text
    updated = 0
    for note in all_notes.iterator(chunk_size=BATCH_SIZE):
        tags_text = " ".join(tag_map.get(note.pk, []))
        attachments_text = " ".join(att_map.get(note.pk, []))
        if tags_text != note.tags_text or attachments_text != note.attachments_text:
            Note.objects.filter(pk=note.pk).update(
                tags_text=tags_text,
                attachments_text=attachments_text,
            )
            updated += 1

    # Recompute search_vector for ALL notes to include new fields
    for start in range(0, total, BATCH_SIZE):
        batch_ids = list(
            all_notes.values_list("pk", flat=True)[start : start + BATCH_SIZE]
        )
        Note.objects.filter(pk__in=batch_ids).update(
            search_vector=(
                SearchVector("title", weight="A")
                + SearchVector("body", weight="B")
                + SearchVector("tags_text", weight="C")
                + SearchVector("attachments_text", weight="C")
            )
        )


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_add_tags_text_attachments_text"),
    ]

    operations = [
        migrations.RunPython(
            backfill_tags_and_attachments_text,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
