# Generated by Django 4.2.27 on 2026-03-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_backfill_tags_text_attachments_text_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Semantic embedding vector for CoS similarity search.', null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the embedding was last generated.', null=True),
        ),
    ]
