# Generated by Django 4.2.27 on 2026-07-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_routine_maintenance_bridge_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='body_plain',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(help_text='Note content (sanitized rich-text HTML).'),
        ),
    ]
