# Generated by Django 4.2.27 on 2026-07-16 10:03

import apps.core.current_context
import apps.people.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('display_name', models.CharField(db_index=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('notes_plain', models.TextField(blank=True, default='', editable=False)),
                ('is_deceased', models.BooleanField(db_index=True, default=False)),
                ('is_self', models.BooleanField(db_index=True, default=False, help_text='This Person IS the user (the self-anchor). At most one per user.')),
                ('origin', models.CharField(choices=[('manual', 'Created manually'), ('contact_import', 'Imported from contacts'), ('gedcom', 'Imported from GEDCOM'), ('extraction', 'Recognized from text'), ('mention', 'Created from a mention'), ('promotion', 'Promoted from Legacy'), ('api', 'Created via API')], db_index=True, default='manual', help_text='How this identity first entered WLJ.', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
            },
            bases=(apps.core.current_context.NarratableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PersonSourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_domain', models.CharField(choices=[('relationships', 'relationships.Person'), ('legacy', 'legacy.Person'), ('ai_relationships', 'ai_relationships.Person')], db_index=True, max_length=20)),
                ('source_pk', models.PositiveIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='people.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=apps.people.models.person_photo_upload_to)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='people.person')),
            ],
            options={
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_via', models.CharField(choices=[('manual', 'Manually created'), ('contact_import', 'Imported as a contact'), ('mention', 'Resolved mention'), ('reference', 'Referenced by the user'), ('interaction', 'Interacted with'), ('feature', 'Added by a WLJ feature'), ('promotion', 'Promoted from Legacy')], max_length=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='people.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('created_manual', 'Created manually'), ('imported_contacts', 'Imported from contacts'), ('imported_gedcom', 'Imported from GEDCOM'), ('promoted_to_people', 'Promoted into People'), ('first_mention', 'First resolved mention'), ('phrase_confirmed', 'Recognition phrase confirmed'), ('phrase_removed', 'Recognition phrase removed'), ('duplicate_detected', 'Duplicate detected'), ('merge_completed', 'Merge completed'), ('relationship_added', 'Relationship added'), ('relationship_removed', 'Relationship removed'), ('archived', 'Archived'), ('restored', 'Restored'), ('source_added', 'Source or provenance added')], db_index=True, max_length=24)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('actor', models.CharField(default='system', help_text='system | user | import — who caused the event.', max_length=20)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='people.person')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='RecognitionPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phrase', models.CharField(help_text='As entered by the user.', max_length=120)),
                ('normalized', models.CharField(db_index=True, editable=False, max_length=120)),
                ('source', models.CharField(choices=[('custom', 'User-defined'), ('learned', 'User-confirmed (learned)')], max_length=10)),
                ('learned_from', models.CharField(blank=True, help_text="e.g. 'journal:1234' — the entry where the user confirmed this.", max_length=120)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_phrases', to='people.person')),
            ],
            options={
                'indexes': [models.Index(fields=['normalized'], name='people_reco_normali_f32047_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='recognitionphrase',
            constraint=models.UniqueConstraint(fields=('person', 'normalized'), name='unique_phrase_per_person'),
        ),
        migrations.AddIndex(
            model_name='personsourcelink',
            index=models.Index(fields=['source_domain', 'source_pk'], name='people_pers_source__6ccb78_idx'),
        ),
        migrations.AddConstraint(
            model_name='personsourcelink',
            constraint=models.UniqueConstraint(fields=('source_domain', 'source_pk'), name='unique_source_row_binding'),
        ),
        migrations.AddIndex(
            model_name='personevent',
            index=models.Index(fields=['person', 'at'], name='people_pers_person__e8bb79_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['user', 'status'], name='people_pers_user_id_9c1297_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['user', 'is_self'], name='people_pers_user_id_8f797e_idx'),
        ),
    ]
