# Generated by Django 4.2.27 on 2026-07-18 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('people', '0003_backfill_legacy_genealogy'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('source_type', models.CharField(choices=[('explicit_at_mention', 'Explicit @mention'), ('exact_name', 'Recognized by name'), ('relationship_role', 'Recognized by role'), ('confirmed_alias', 'Recognized by phrase'), ('reviewed_resolution', 'Confirmed in review')], default='explicit_at_mention', max_length=24)),
                ('surface_text', models.CharField(blank=True, max_length=120)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_mentions', to='people.person')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='people_pers_content_9078a7_idx'), models.Index(fields=['person'], name='people_pers_person__b9dad8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='personmention',
            constraint=models.UniqueConstraint(fields=('person', 'content_type', 'object_id'), name='unique_person_mention_per_object'),
        ),
    ]
