# Generated by Django 5.2.9 on 2026-01-01 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClaudeTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_number",
                    models.PositiveIntegerField(
                        help_text="Auto-assigned task number (TASK-XXX)", unique=True
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title for the task", max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In Progress"),
                            ("complete", "Complete"),
                            ("blocked", "Blocked"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "HIGH - Bugs, broken features, blocking issues"),
                            (
                                "medium",
                                "MEDIUM - New features, user-requested enhancements",
                            ),
                            ("low", "LOW - Ideas, nice-to-haves, future improvements"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("action_required", "ACTION REQUIRED - User action needed"),
                            ("review", "Review - Task complete, please review"),
                            ("bug", "Bug - Fix broken functionality"),
                            ("feature", "Feature - New functionality"),
                            ("enhancement", "Enhancement - Improve existing feature"),
                            ("idea", "Idea - Future consideration"),
                            ("refactor", "Refactor - Code restructuring"),
                            ("maintenance", "Maintenance - System upkeep"),
                            ("cleanup", "Cleanup - Remove unused code/files"),
                            ("security", "Security - Security improvements"),
                            ("performance", "Performance - Speed/efficiency"),
                            ("documentation", "Documentation - Docs updates"),
                        ],
                        default="feature",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of what needs to be done"
                    ),
                ),
                (
                    "acceptance_criteria",
                    models.TextField(
                        blank=True,
                        help_text="List of criteria to verify task completion (one per line)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional context, links, or implementation hints",
                    ),
                ),
                (
                    "phases",
                    models.TextField(
                        blank=True,
                        help_text="For multi-phase tasks, list phases (one per line). Leave blank for single-phase tasks.",
                    ),
                ),
                (
                    "current_phase",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current phase number (0 = not started, 1 = phase 1, etc.)",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("user", "User - Added by Danny"),
                            ("claude", "Claude - Discovered during session"),
                        ],
                        default="user",
                        help_text="Who identified this task",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session_label",
                    models.CharField(
                        blank=True,
                        help_text="Claude session that worked on this task",
                        max_length=100,
                    ),
                ),
                (
                    "completion_notes",
                    models.TextField(
                        blank=True, help_text="Notes added when task was completed"
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent task this was created from (for follow-ups)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="followup_tasks",
                        to="admin_console.claudetask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Claude Task",
                "verbose_name_plural": "Claude Tasks",
                "ordering": [
                    models.Case(
                        models.When(status="in_progress", then=0),
                        models.When(status="new", then=1),
                        models.When(status="blocked", then=2),
                        default=3,
                        output_field=models.IntegerField(),
                    ),
                    models.Case(
                        models.When(priority="high", then=0),
                        models.When(priority="medium", then=1),
                        models.When(priority="low", then=2),
                        output_field=models.IntegerField(),
                    ),
                    "created_at",
                ],
            },
        ),
    ]
