# Generated by Django 5.2.9 on 2026-01-01 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_console", "0003_delete_claudetask"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminProjectPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phase_number", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("objective", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("complete", "Complete"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project Phase",
                "verbose_name_plural": "Project Phases",
                "ordering": ["phase_number"],
            },
        ),
        migrations.CreateModel(
            name="AdminTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("feature", "Feature"),
                            ("bug", "Bug"),
                            ("infra", "Infrastructure"),
                            ("content", "Content"),
                            ("business", "Business"),
                        ],
                        max_length=20,
                    ),
                ),
                ("priority", models.IntegerField(default=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("backlog", "Backlog"),
                            ("ready", "Ready"),
                            ("in_progress", "In Progress"),
                            ("blocked", "Blocked"),
                            ("done", "Done"),
                        ],
                        default="backlog",
                        max_length=20,
                    ),
                ),
                (
                    "effort",
                    models.CharField(
                        choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        choices=[("human", "Human"), ("claude", "Claude")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="admin_console.adminprojectphase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Task",
                "verbose_name_plural": "Admin Tasks",
                "ordering": ["priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdminActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.TextField()),
                (
                    "created_by",
                    models.CharField(
                        choices=[("human", "Human"), ("claude", "Claude")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="admin_console.admintask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
