# Generated by Django 5.2.9 on 2026-01-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_console", "0004_admin_project_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="admintask",
            name="blocked_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
