# Generated by Django 5.2.9 on 2026-01-01 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_console", "0005_add_blocked_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="admintask",
            name="blocking_task",
            field=models.ForeignKey(
                blank=True,
                help_text="The blocker task that is preventing this task from proceeding",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blocks",
                to="admin_console.admintask",
            ),
        ),
    ]
