# Generated by Django 5.2.9 on 2026-01-02 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_console", "0007_add_admin_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminTaskCategoryConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order in dropdowns"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="If False, cannot be assigned to new tasks",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Task Category Config",
                "verbose_name_plural": "Task Category Configs",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AdminTaskEffortConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='Display label, e.g., "Small"', max_length=50
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text='Short code, e.g., "S"', max_length=10, unique=True
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order in dropdowns"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="If False, cannot be assigned to new tasks",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Task Effort Config",
                "verbose_name_plural": "Task Effort Configs",
                "ordering": ["order", "value"],
            },
        ),
        migrations.CreateModel(
            name="AdminTaskPriorityConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='Display label, e.g., "Highest"', max_length=50
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        help_text="Numeric value, e.g., 1 for highest", unique=True
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order in dropdowns"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="If False, cannot be assigned to new tasks",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Task Priority Config",
                "verbose_name_plural": "Task Priority Configs",
                "ordering": ["order", "value"],
            },
        ),
        migrations.CreateModel(
            name="AdminTaskStatusConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                (
                    "execution_allowed",
                    models.BooleanField(
                        default=False,
                        help_text="If True, tasks in this status can be executed/worked on",
                    ),
                ),
                (
                    "terminal",
                    models.BooleanField(
                        default=False,
                        help_text="If True, this is a terminal status (no further transitions allowed)",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order in dropdowns"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="If False, cannot be assigned to new tasks",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Task Status Config",
                "verbose_name_plural": "Task Status Configs",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AlterField(
            model_name="admintask",
            name="effort",
            field=models.CharField(
                choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")], max_length=10
            ),
        ),
        migrations.AddField(
            model_name="admintask",
            name="category_config",
            field=models.ForeignKey(
                blank=True,
                help_text="Configured category for this task",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="admin_console.admintaskcategoryconfig",
            ),
        ),
        migrations.AddField(
            model_name="admintask",
            name="effort_config",
            field=models.ForeignKey(
                blank=True,
                help_text="Configured effort level for this task",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="admin_console.admintaskeffortconfig",
            ),
        ),
        migrations.AddField(
            model_name="admintask",
            name="priority_config",
            field=models.ForeignKey(
                blank=True,
                help_text="Configured priority for this task",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="admin_console.admintaskpriorityconfig",
            ),
        ),
        migrations.AddField(
            model_name="admintask",
            name="status_config",
            field=models.ForeignKey(
                blank=True,
                help_text="Configured status for this task",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="admin_console.admintaskstatusconfig",
            ),
        ),
    ]
