# ==============================================================================
# File: apps/admin_console/migrations/0011_alter_admintask_description.py
# Project: Whole Life Journey - Django 5.x Personal Wellness/Journaling App
# Description: Schema migration to change description field to JSONField
# Owner: Danny Jenkins (dannyjenkins71@gmail.com)
# Created: 2026-01-01
# Last Updated: 2026-01-01
# ==============================================================================
# Generated by Django 5.2.9 on 2026-01-02 03:13

import apps.admin_console.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_console", "0010_convert_description_to_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admintask",
            name="description",
            field=models.JSONField(
                default=dict,
                help_text="Executable task description in JSON format. Required fields: objective (string), inputs (array of strings), actions (array with at least one step), output (string).",
                validators=[
                    apps.admin_console.models.validate_executable_task_description
                ],
            ),
        ),
    ]
