# Generated by Django 5.2.9 on 2026-01-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_console", "0011_alter_admintask_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="admintask",
            name="attachment",
            field=models.ImageField(
                blank=True,
                help_text="Optional screenshot or image attachment for task context",
                null=True,
                upload_to="admin_tasks/attachments/",
            ),
        ),
    ]
