# Generated by Django 5.2.9 on 2026-01-04 16:30
# Adds 'Future' and 'Never' status values to AdminTaskStatusConfig

from django.db import migrations


def add_new_statuses(apps, schema_editor):
    """Add Future and Never status values."""
    AdminTaskStatusConfig = apps.get_model('admin_console', 'AdminTaskStatusConfig')

    new_statuses = [
        {
            'name': 'future',
            'display_name': 'Future',
            'execution_allowed': False,
            'terminal': False,
            'order': 6,
            'active': True,
        },
        {
            'name': 'never',
            'display_name': 'Never',
            'execution_allowed': False,
            'terminal': True,  # Terminal - task is effectively closed
            'order': 7,
            'active': True,
        },
    ]

    for data in new_statuses:
        AdminTaskStatusConfig.objects.get_or_create(name=data['name'], defaults=data)


def remove_new_statuses(apps, schema_editor):
    """Remove Future and Never status values."""
    AdminTaskStatusConfig = apps.get_model('admin_console', 'AdminTaskStatusConfig')
    AdminTaskStatusConfig.objects.filter(name__in=['future', 'never']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("admin_console", "0013_add_dataloadconfig"),
    ]

    operations = [
        migrations.RunPython(add_new_statuses, remove_new_statuses),
    ]
