# Generated by Django 4.2.27 on 2026-01-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0018_reset_teaching_destinations_loader'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintask',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the task was marked as done', null=True),
        ),
        migrations.AddField(
            model_name='admintask',
            name='resolution_notes',
            field=models.TextField(blank=True, default='', help_text='Documentation of what was done to complete this task: root cause, fix applied, files changed, etc.'),
        ),
    ]
