# Generated by Django 4.2.27 on 2026-01-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0019_add_resolution_notes_and_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactivitylog',
            name='created_by',
            field=models.CharField(choices=[('human', 'Human'), ('claude', 'Claude'), ('404_reporter', '404 Reporter'), ('system', 'System')], max_length=15),
        ),
        migrations.AlterField(
            model_name='admintask',
            name='created_by',
            field=models.CharField(choices=[('human', 'Human'), ('claude', 'Claude'), ('404_reporter', '404 Reporter'), ('system', 'System')], max_length=15),
        ),
    ]
