# Generated by Django 4.2.27 on 2026-01-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0020_extend_created_by_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('medicine', 'Medicine Reminder'), ('medicine_refill', 'Medicine Refill'), ('task', 'Task Due'), ('event', 'Calendar Event'), ('prayer', 'Prayer Reminder'), ('reading_plan', 'Reading Plan'), ('fasting', 'Fasting Reminder'), ('significant_event', 'Significant Event'), ('milestone', 'Goal Milestone'), ('finance', 'Finance Alert'), ('journal', 'Journal Prompt'), ('system', 'System'), ('digest', 'Daily Digest')], help_text='Notification category this template applies to', max_length=20, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable name for admin interface', max_length=100)),
                ('subject_template', models.CharField(help_text='Email subject line. Supports Django template syntax: {{ notification.title }}', max_length=200)),
                ('body_template', models.TextField(help_text='Email body in HTML format. Supports Django template syntax.\nAvailable variables: user, notification, notifications (for digest), site_name, current_year, preferences_url')),
                ('is_active', models.BooleanField(default=True, help_text="If disabled, emails for this category won't be sent")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Notification Template',
                'verbose_name_plural': 'Email Notification Templates',
                'ordering': ['category'],
            },
        ),
    ]
