# Generated by Django 4.2.27 on 2026-01-25 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_console', '0022_reset_help_topics_loader'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title for the announcement', max_length=200)),
                ('message', models.TextField(help_text='Full message content (supports basic HTML: <b>, <i>, <a>, <br>, <ul>, <li>)')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error/Urgent'), ('success', 'Success')], default='info', help_text='Determines the color/styling of the announcement', max_length=20)),
                ('starts_at', models.DateTimeField(help_text='When to start showing this announcement')),
                ('ends_at', models.DateTimeField(blank=True, help_text='When to stop showing (leave blank for indefinite)', null=True)),
                ('is_published', models.BooleanField(default=False, help_text='Only published announcements are shown to users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Announcement',
                'verbose_name_plural': 'System Announcements',
                'ordering': ['-starts_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemAnnouncementDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to='admin_console.systemannouncement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement Dismissal',
                'verbose_name_plural': 'Announcement Dismissals',
                'unique_together': {('user', 'announcement')},
            },
        ),
    ]
