# Generated by Django 4.2.27 on 2026-02-01 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_console', '0025_reset_teaching_destinations_for_brain_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of this test cycle (e.g., 'v1.0 Production Release')", max_length=200)),
                ('version', models.CharField(blank=True, help_text="Version being tested (e.g., '1.0.0')", max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description or notes about this test cycle')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When testing started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When all tests were completed', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test Cycle',
                'verbose_name_plural': 'Test Cycles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Phase name (e.g., 'User Authentication')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of what this phase tests')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the cycle')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='admin_console.testcycle')),
            ],
            options={
                'verbose_name': 'Test Phase',
                'verbose_name_plural': 'Test Phases',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Test name/action (e.g., 'Create new journal entry with image')", max_length=300)),
                ('description', models.TextField(blank=True, help_text='Detailed description or steps to perform')),
                ('expected_result', models.TextField(blank=True, help_text='What should happen when test passes')),
                ('url', models.CharField(blank=True, help_text="URL path to test (e.g., '/journal/new/')", max_length=500)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('passed', 'Passed'), ('failed', 'Failed'), ('blocked', 'Blocked')], default='not_started', max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('actual_result', models.TextField(blank=True, help_text='What actually happened during testing')),
                ('notes', models.TextField(blank=True, help_text='Additional notes, bug references, etc.')),
                ('tested_at', models.DateTimeField(blank=True, help_text='When the test was last executed', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the phase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='admin_console.testcycle')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='admin_console.testphase')),
                ('tester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tested_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test Item',
                'verbose_name_plural': 'Test Items',
                'ordering': ['order', 'name'],
            },
        ),
    ]
