# Generated by Django 4.2.27 on 2026-02-16 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0026_add_test_plan_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminGuideSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.SlugField(help_text='Unique identifier for this section', max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('icon', models.CharField(default='📄', help_text='Emoji icon for sidebar display', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Brief description shown below the section title')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Guide Section',
                'verbose_name_plural': 'Admin Guide Sections',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AdminGuideArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('content', models.TextField(help_text='Article content in Markdown format')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_editable', models.BooleanField(default=False, help_text='If True, admin can edit via web interface')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='admin_console.adminguidesection')),
            ],
            options={
                'verbose_name': 'Admin Guide Article',
                'verbose_name_plural': 'Admin Guide Articles',
                'ordering': ['order', 'title'],
                'unique_together': {('section', 'slug')},
            },
        ),
    ]
