# Generated by Django 4.2.27 on 2026-02-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0027_adminguidesection_adminguidearticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcycle',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
