# Generated by Django 4.2.27 on 2026-02-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0028_add_paused_cancelled_to_testcycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='UITestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('passed', 'All Passed'), ('failed', 'Some Failed'), ('error', 'Error')], default='running', max_length=10)),
                ('modules', models.JSONField(default=list, help_text="List of module names tested (e.g. ['journal', 'smoke'])")),
                ('total_cases', models.PositiveIntegerField(default=0)),
                ('passed', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('pass_rate', models.DecimalField(decimal_places=2, default=0, help_text='Pass rate as percentage', max_digits=5)),
                ('duration_seconds', models.FloatField(default=0, help_text='Total run time in seconds')),
                ('run_id', models.CharField(blank=True, help_text='WLJ UI framework RUN_ID', max_length=50)),
                ('output', models.TextField(blank=True, help_text='Combined stdout/stderr from run')),
            ],
            options={
                'verbose_name': 'UI Test Run',
                'verbose_name_plural': 'UI Test Runs',
                'ordering': ['-run_at'],
            },
        ),
    ]
