# Generated by Django 4.2.27 on 2026-02-26 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0029_add_uitestrun_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='uitestrun',
            name='parent_run',
            field=models.ForeignKey(blank=True, help_text='Parent full-suite run (null for standalone or parent runs)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_runs', to='admin_console.uitestrun'),
        ),
    ]
