# Generated by Django 4.2.27 on 2026-03-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0031_uitestrun_case_results_uitestrun_environment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminguidesection',
            name='guide_type',
            field=models.CharField(choices=[('admin', 'Admin Guide'), ('data_dictionary', 'Data Dictionary'), ('user', 'User Guide')], db_index=True, default='admin', help_text='Which guide this section belongs to', max_length=20),
        ),
        migrations.AlterField(
            model_name='adminguidesection',
            name='section_key',
            field=models.SlugField(help_text='Unique identifier for this section within its guide', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='adminguidesection',
            unique_together={('guide_type', 'section_key')},
        ),
    ]
