# Generated by Django 4.2.27 on 2026-06-27 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_console', '0036_reset_fixtures_for_march_docs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptanceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suite_name', models.CharField(default='full', max_length=32)),
                ('environment', models.CharField(blank=True, max_length=40)),
                ('git_commit', models.CharField(blank=True, max_length=40)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('pass_count', models.PositiveIntegerField(default=0)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('score_percent', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('chatgpt_review_prompt', models.TextField(blank=True)),
                ('claude_fix_prompt', models.TextField(blank=True)),
                ('raw_report_json', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beth_acceptance_runs_created', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beth_acceptance_runs_targeted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcceptanceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=64)),
                ('suite', models.CharField(blank=True, max_length=32)),
                ('question_text', models.TextField(blank=True)),
                ('expected_intent', models.CharField(blank=True, max_length=64)),
                ('expected_lane', models.CharField(blank=True, max_length=64)),
                ('actual_intent', models.CharField(blank=True, max_length=64)),
                ('actual_lane', models.CharField(blank=True, max_length=64)),
                ('response_text', models.TextField(blank=True)),
                ('response_time_ms', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('failed_rules', models.JSONField(blank=True, default=list)),
                ('required_concepts', models.JSONField(blank=True, default=list)),
                ('forbidden_concepts', models.JSONField(blank=True, default=list)),
                ('openai_called', models.BooleanField(default=False)),
                ('fallback_used', models.BooleanField(blank=True, null=True)),
                ('raw_result_json', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='admin_console.acceptancerun')),
            ],
            options={
                'ordering': ['run', 'sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='acceptancerun',
            index=models.Index(fields=['-created_at'], name='admin_conso_created_d48242_idx'),
        ),
        migrations.AddIndex(
            model_name='acceptancerun',
            index=models.Index(fields=['status'], name='admin_conso_status_3fd64a_idx'),
        ),
    ]
