# Generated by Django 4.2.27 on 2026-06-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0037_acceptancerun_acceptanceresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptanceresult',
            name='is_critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acceptanceresult',
            name='is_slow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acceptancerun',
            name='avg_response_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acceptancerun',
            name='category_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='acceptancerun',
            name='critical_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acceptancerun',
            name='depth',
            field=models.CharField(default='full', max_length=16),
        ),
        migrations.AddField(
            model_name='acceptancerun',
            name='grade',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='acceptancerun',
            name='warning_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
