# Generated by Django 4.2.27 on 2026-06-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0038_acceptanceresult_is_critical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptancerun',
            name='analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='acceptancerun',
            name='trustworthy',
            field=models.BooleanField(default=True),
        ),
    ]
