# Generated by Django 4.2.27 on 2026-07-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0039_acceptancerun_analysis_acceptancerun_trustworthy'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptanceresult',
            name='canonical_provider',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='acceptanceresult',
            name='first_failing_layer',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='acceptanceresult',
            name='retrieval_evidence',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='acceptanceresult',
            name='retrieved_records',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='acceptanceresult',
            name='runtime_used',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='acceptanceresult',
            name='selected_tool',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='acceptanceresult',
            name='tool_arguments',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
