# Generated by Django 4.2.27 on 2026-07-18 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_console', '0040_acceptanceresult_canonical_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptanceresult',
            name='check_pass_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acceptanceresult',
            name='check_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acceptanceresult',
            name='checks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='acceptanceresult',
            name='expected_truth',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='acceptanceresult',
            name='extracted_truth',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='acceptanceresult',
            name='is_na',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acceptanceresult',
            name='object_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='acceptanceresult',
            name='override_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='acceptancerun',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acceptancerun',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acceptancerun',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_runs_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acceptancerun',
            name='checks_passed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acceptancerun',
            name='checks_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acceptancerun',
            name='db_version',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='acceptancerun',
            name='na_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='acceptancerun',
            name='provider_version',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='acceptancerun',
            name='scope_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='acceptancerun',
            name='scope_kind',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='acceptancerun',
            name='suite_version',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='acceptancerun',
            name='validation_type',
            field=models.CharField(default='behavior', max_length=24),
        ),
        migrations.AddIndex(
            model_name='acceptancerun',
            index=models.Index(fields=['validation_type', '-created_at'], name='admin_conso_validat_4be31f_idx'),
        ),
    ]
