# Generated by Django 4.2.27 on 2026-07-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0041_acceptanceresult_check_pass_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptancerun',
            name='prompt_mode',
            field=models.CharField(blank=True, default='resolved', max_length=16),
        ),
    ]
