# Generated by Django 4.2.27 on 2026-01-23 01:15

import apps.security.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('action', models.CharField(choices=[('view_dashboard', 'View Dashboard'), ('view_run', 'View Run Details'), ('view_finding', 'View Finding'), ('export', 'Export Data'), ('run_assessment', 'Run Assessment')], max_length=30)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('resource_id', models.CharField(blank=True, max_length=50)),
                ('success', models.BooleanField(default=True)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecurityFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finding_id', models.CharField(db_index=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], max_length=10)),
                ('likelihood', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('impact', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('cvss_vector', models.CharField(blank=True, max_length=100)),
                ('cvss_score', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('_description', apps.security.models.EncryptedTextField()),
                ('_risk_reasoning', apps.security.models.EncryptedTextField(blank=True, default='')),
                ('_evidence', apps.security.models.EncryptedJSONField(blank=True, null=True)),
                ('_affected_components', apps.security.models.EncryptedJSONField(blank=True, null=True)),
                ('_recommendations', apps.security.models.EncryptedJSONField(blank=True, null=True)),
                ('_validation_steps', apps.security.models.EncryptedTextField(blank=True, default='')),
                ('is_quick_win', models.BooleanField(default=False)),
                ('remediation_effort', models.CharField(default='medium', max_length=20)),
            ],
            options={
                'ordering': ['-cvss_score', 'finding_id'],
            },
        ),
        migrations.CreateModel(
            name='SecurityRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('run_type', models.CharField(default='full', max_length=50)),
                ('triggered_by', models.CharField(default='manual', max_length=100)),
                ('total_tests', models.IntegerField(default=0)),
                ('passed_tests', models.IntegerField(default=0)),
                ('failed_tests', models.IntegerField(default=0)),
                ('total_findings', models.IntegerField(default=0)),
                ('critical_findings', models.IntegerField(default=0)),
                ('high_findings', models.IntegerField(default=0)),
                ('medium_findings', models.IntegerField(default=0)),
                ('low_findings', models.IntegerField(default=0)),
                ('_executive_summary', apps.security.models.EncryptedTextField(blank=True, default='')),
                ('_attack_paths', apps.security.models.EncryptedJSONField(blank=True, null=True)),
                ('_failure_modes', apps.security.models.EncryptedJSONField(blank=True, null=True)),
                ('_ciso_sleep_test', apps.security.models.EncryptedTextField(blank=True, default='')),
                ('_remediation_prompt', apps.security.models.EncryptedTextField(blank=True, default='')),
                ('run_hash', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['-run_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecurityTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_id', models.CharField(db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('secrets', 'Secrets & Credentials'), ('auth', 'Authentication & Sessions'), ('authz', 'Authorization'), ('input', 'Input Validation'), ('data', 'Data Protection'), ('logging', 'Logging & Auditing'), ('web', 'Web Security'), ('deps', 'Dependencies'), ('deploy', 'Deployment'), ('abuse', 'Abuse Resistance'), ('infra', 'Infrastructure'), ('compliance', 'Compliance')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('criteria', models.TextField()),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('unknown', 'Unknown'), ('skipped', 'Skipped')], max_length=10)),
                ('result_details', models.TextField(blank=True)),
                ('_evidence', apps.security.models.EncryptedJSONField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_ms', models.IntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='security.securityrun')),
            ],
            options={
                'ordering': ['test_id'],
            },
        ),
        migrations.CreateModel(
            name='SecurityScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_timestamp', models.DateTimeField(db_index=True)),
                ('cvss_avg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('cvss_critical_count', models.IntegerField(default=0)),
                ('cvss_high_count', models.IntegerField(default=0)),
                ('cvss_medium_count', models.IntegerField(default=0)),
                ('cvss_low_count', models.IntegerField(default=0)),
                ('cvss_none_count', models.IntegerField(default=0)),
                ('securityscorecard_grade', models.CharField(choices=[('A', 'A - Excellent'), ('B', 'B - Good'), ('C', 'C - Fair'), ('D', 'D - Poor'), ('F', 'F - Critical')], default='C', max_length=1)),
                ('bitsight_score', models.IntegerField(default=500)),
                ('risk_score_0_100', models.IntegerField(default=50)),
                ('maturity_level', models.IntegerField(choices=[(0, 'Ad Hoc'), (1, 'Basic'), (2, 'Managed'), (3, 'Mature')], default=1)),
                ('_scoring_methodology', apps.security.models.EncryptedJSONField(blank=True, null=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='security.securityrun')),
            ],
            options={
                'ordering': ['-run_timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='securityrun',
            index=models.Index(fields=['-run_timestamp'], name='security_se_run_tim_c30c43_idx'),
        ),
        migrations.AddIndex(
            model_name='securityrun',
            index=models.Index(fields=['status'], name='security_se_status_f8fcea_idx'),
        ),
        migrations.AddField(
            model_name='securityfinding',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='security.securityrun'),
        ),
        migrations.AddField(
            model_name='securityfinding',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='security.securitytest'),
        ),
        migrations.AddField(
            model_name='securityauditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='securitytest',
            index=models.Index(fields=['run', 'test_id'], name='security_se_run_id_ca4478_idx'),
        ),
        migrations.AddIndex(
            model_name='securitytest',
            index=models.Index(fields=['category'], name='security_se_categor_eea855_idx'),
        ),
        migrations.AddIndex(
            model_name='securitytest',
            index=models.Index(fields=['result'], name='security_se_result_e2d5da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='securitytest',
            unique_together={('run', 'test_id')},
        ),
        migrations.AddIndex(
            model_name='securityscore',
            index=models.Index(fields=['-run_timestamp'], name='security_se_run_tim_6f78c3_idx'),
        ),
        migrations.AddIndex(
            model_name='securityscore',
            index=models.Index(fields=['securityscorecard_grade'], name='security_se_securit_2d05ca_idx'),
        ),
        migrations.AddIndex(
            model_name='securityfinding',
            index=models.Index(fields=['run', 'severity'], name='security_se_run_id_d4911a_idx'),
        ),
        migrations.AddIndex(
            model_name='securityfinding',
            index=models.Index(fields=['cvss_score'], name='security_se_cvss_sc_9afe44_idx'),
        ),
        migrations.AddIndex(
            model_name='securityfinding',
            index=models.Index(fields=['finding_id'], name='security_se_finding_0b38a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='securityfinding',
            unique_together={('run', 'finding_id')},
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['-timestamp'], name='security_se_timesta_8b2c21_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['user', '-timestamp'], name='security_se_user_id_84c0e4_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['action'], name='security_se_action_526294_idx'),
        ),
    ]
