# Generated by Django 4.2.27 on 2026-01-23 02:11

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcknowledgedFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finding_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('superseded', 'Superseded')], default='active', max_length=20)),
                ('justification', models.TextField(help_text='Why is this risk being accepted?')),
                ('mitigating_controls', models.TextField(blank=True, help_text='What compensating controls reduce this risk?')),
                ('accepted_risk_level', models.CharField(choices=[('low', 'Low - Minimal business impact'), ('medium', 'Medium - Moderate impact, compensating controls in place'), ('high', 'High - Significant impact but accepted for business reasons')], default='medium', max_length=20)),
                ('acknowledged_by', models.CharField(max_length=100)),
                ('acknowledged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When should this acknowledgment be reviewed? Leave blank for indefinite.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Additional context or future remediation plans')),
            ],
            options={
                'verbose_name': 'Acknowledged Finding',
                'verbose_name_plural': 'Acknowledged Findings',
                'ordering': ['finding_id'],
            },
        ),
    ]
