# Generated by Django 4.2.27 on 2026-01-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_add_acknowledged_finding'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityfinding',
            name='acknowledgment_justification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='securityfinding',
            name='finding_key',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='securityfinding',
            name='is_acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
