# Generated by Django 4.2.27 on 2026-01-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_add_finding_status_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityrun',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='User notes about this assessment run'),
        ),
        migrations.AddField(
            model_name='securityrun',
            name='notes_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityrun',
            name='notes_updated_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
