# Generated by Django 4.2.27 on 2026-01-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_add_notes_to_security_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityauditlog',
            name='action',
            field=models.CharField(choices=[('view_dashboard', 'View Dashboard'), ('view_run', 'View Run Details'), ('view_finding', 'View Finding'), ('export', 'Export Data'), ('run_assessment', 'Run Assessment'), ('modify', 'Modify Data'), ('delete', 'Delete Data')], max_length=30),
        ),
    ]
