# Generated by Django 4.2.27 on 2026-01-12 15:19

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='The promo code that was used', max_length=50)),
                ('stripe_coupon_id', models.CharField(blank=True, help_text='Stripe Coupon ID', max_length=255)),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed discount amount (if applicable)', max_digits=10, null=True)),
                ('discount_percent', models.PositiveIntegerField(blank=True, help_text='Percentage discount (if applicable)', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promo Code Usage',
                'verbose_name_plural': 'Promo Code Usages',
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='FeatureSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suggestion_text', models.TextField(help_text="The user's feature suggestion")),
                ('submitted_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Under Review'), ('planned', 'Planned'), ('implemented', 'Implemented'), ('declined', 'Declined')], default='submitted', max_length=20)),
                ('implemented_date', models.DateField(blank=True, help_text='Date the feature was implemented', null=True)),
                ('reward_given', models.BooleanField(default=False, help_text='$5 credit given for implemented suggestion')),
                ('reward_amount', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Reward amount (default $5)', max_digits=10)),
                ('public_credit_consent', models.BooleanField(default=False, help_text='User consents to public credit for the suggestion')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes about this suggestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Suggestion',
                'verbose_name_plural': 'Feature Suggestions',
                'ordering': ['-submitted_date'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for credits earned, negative for credits used', max_digits=10)),
                ('transaction_type', models.CharField(choices=[('referral_bonus', 'Referral Bonus'), ('suggestion_reward', 'Suggestion Reward'), ('manual', 'Manual Adjustment'), ('applied_to_invoice', 'Applied to Invoice'), ('promo_code', 'Promo Code'), ('refund', 'Refund')], max_length=30)),
                ('description', models.TextField(help_text='Description of the transaction')),
                ('related_invoice', models.CharField(blank=True, help_text='Stripe invoice ID if applied to payment', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Transaction',
                'verbose_name_plural': 'Credit Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pricing_tier', models.CharField(choices=[('free', 'Free'), ('student', 'Student ($3.99/mo)'), ('adult', 'Adult ($7.99/mo)'), ('founding', 'Founding Member (Lifetime)')], default='free', help_text="User's current pricing tier", max_length=20)),
                ('tier_locked_until', models.DateField(blank=True, help_text='Tier cannot change until this date (for gift year, etc.)', null=True)),
                ('graduation_date', models.DateField(blank=True, help_text='Date when student tier graduates to adult tier', null=True)),
                ('stripe_customer_id', models.CharField(blank=True, help_text='Stripe Customer ID (cus_xxx)', max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='Active Stripe Subscription ID (sub_xxx)', max_length=255)),
                ('subscription_status', models.CharField(choices=[('none', 'No Subscription'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('lifetime', 'Lifetime (Founding Member)')], default='none', help_text='Current subscription status', max_length=20)),
                ('billing_cycle', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('lifetime', 'Lifetime')], help_text='Current billing cycle', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, help_text='Start of current billing period', null=True)),
                ('current_period_end', models.DateTimeField(blank=True, help_text='End of current billing period (next billing date)', null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False, help_text='Subscription will cancel at end of current period')),
                ('referral_code', models.CharField(blank=True, help_text="User's unique referral code", max_length=20, unique=True)),
                ('account_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Available account credit balance', max_digits=10)),
                ('payout_method', models.CharField(blank=True, choices=[('paypal', 'PayPal'), ('venmo', 'Venmo'), ('zelle', 'Zelle'), ('bank', 'Bank Transfer')], help_text='Preferred payout method (Founding Members only)', max_length=20)),
                ('payout_email', models.EmailField(blank=True, help_text='Email for PayPal/Venmo payouts', max_length=254)),
                ('payout_phone', models.CharField(blank=True, help_text='Phone for Zelle payouts', max_length=20)),
                ('payout_bank_info', models.TextField(blank=True, help_text='Bank details for direct deposit (encrypted in production)')),
                ('referred_by', models.ForeignKey(blank=True, help_text='User who referred this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing Profile',
                'verbose_name_plural': 'Billing Profiles',
            },
        ),
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signup_date', models.DateField(help_text='Date the referred user signed up')),
                ('first_payment_date', models.DateField(blank=True, help_text="Date of referred user's first payment", null=True)),
                ('referrer_reward_given', models.BooleanField(default=False, help_text='$5 credit given to referrer')),
                ('referred_reward_given', models.BooleanField(default=False, help_text='$5 credit given to referred user')),
                ('referred_user', models.ForeignKey(help_text='User who was referred', on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards_received', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(help_text='User who made the referral', on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Reward',
                'verbose_name_plural': 'Referral Rewards',
                'unique_together': {('referrer', 'referred_user')},
            },
        ),
        migrations.CreateModel(
            name='ReferralQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signup_date', models.DateField(help_text='When the referred user signed up')),
                ('qualified_date', models.DateField(help_text='Date when 90 days is reached (signup_date + 90)')),
                ('bonus_eligible', models.BooleanField(default=False, help_text='True if user stayed subscribed for 90 days')),
                ('bonus_paid', models.BooleanField(default=False, help_text='True if Founding Member bonus was paid')),
                ('quarter_applied', models.CharField(blank=True, help_text='Quarter when bonus was applied (e.g., 2026-Q1)', max_length=10)),
                ('referred_user', models.ForeignKey(help_text='The referred user being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='qualification_records', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(help_text='The Founding Member who made the referral', on_delete=django.db.models.deletion.CASCADE, related_name='referral_qualifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Qualification',
                'verbose_name_plural': 'Referral Qualifications',
                'unique_together': {('referrer', 'referred_user')},
            },
        ),
        migrations.CreateModel(
            name='PaymentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('checkout_started', 'Checkout Started'), ('checkout_completed', 'Checkout Completed'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('subscription_created', 'Subscription Created'), ('subscription_updated', 'Subscription Updated'), ('subscription_canceled', 'Subscription Canceled'), ('refund_issued', 'Refund Issued'), ('credit_added', 'Credit Added'), ('credit_used', 'Credit Used'), ('webhook_received', 'Webhook Received')], max_length=30)),
                ('stripe_event_id', models.CharField(blank=True, help_text='Stripe Event ID (evt_xxx)', max_length=255)),
                ('stripe_object_id', models.CharField(blank=True, help_text='Related Stripe object ID', max_length=255)),
                ('success', models.BooleanField(default=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details (sensitive data redacted)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Audit Log',
                'verbose_name_plural': 'Payment Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action'], name='billing_pay_user_id_1f4bfb_idx'), models.Index(fields=['stripe_event_id'], name='billing_pay_stripe__fc0e41_idx'), models.Index(fields=['created_at', 'action'], name='billing_pay_created_a7ab22_idx')],
            },
        ),
        migrations.CreateModel(
            name='FoundingMemberPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quarter', models.CharField(help_text='Quarter (e.g., 2026-Q1)', max_length=10)),
                ('qualifying_referrals', models.PositiveIntegerField(default=0, help_text='Number of referrals that qualified this quarter')),
                ('payout_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total payout amount ($5 per qualified referral)', max_digits=10)),
                ('payout_method', models.CharField(blank=True, choices=[('paypal', 'PayPal'), ('venmo', 'Venmo'), ('zelle', 'Zelle'), ('bank', 'Bank Transfer')], help_text='Method used for this payout', max_length=20)),
                ('payout_reference', models.CharField(blank=True, help_text='Transaction ID or confirmation number', max_length=255)),
                ('paid_date', models.DateField(blank=True, help_text='Date the payout was sent', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this payout')),
                ('founding_member', models.ForeignKey(help_text='The Founding Member receiving the payout', on_delete=django.db.models.deletion.CASCADE, related_name='founding_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Founding Member Payout',
                'verbose_name_plural': 'Founding Member Payouts',
                'ordering': ['-quarter', 'founding_member__email'],
                'unique_together': {('founding_member', 'quarter')},
            },
        ),
    ]
