# Generated by Django 4.2.27 on 2026-01-12 16:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Beacon Innovation LLC', help_text='Business entity name', max_length=100)),
                ('product_name', models.CharField(default='Whole Life Journey', help_text='Product name', max_length=100)),
                ('student_max_age', models.PositiveIntegerField(default=22, help_text='Maximum age for student pricing (age X and under)')),
                ('student_monthly_price', models.DecimalField(decimal_places=2, default=Decimal('4.99'), help_text='Student monthly subscription price', max_digits=10)),
                ('student_annual_price', models.DecimalField(decimal_places=2, default=Decimal('49.00'), help_text='Student annual subscription price', max_digits=10)),
                ('adult_monthly_price', models.DecimalField(decimal_places=2, default=Decimal('7.99'), help_text='Adult monthly subscription price', max_digits=10)),
                ('adult_annual_price', models.DecimalField(decimal_places=2, default=Decimal('79.00'), help_text='Adult annual subscription price', max_digits=10)),
                ('founding_lifetime_price', models.DecimalField(decimal_places=2, default=Decimal('59.00'), help_text='Founding Member lifetime one-time price', max_digits=10)),
                ('founding_quarterly_bonus', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Quarterly bonus per qualified referral for Founding Members', max_digits=10)),
                ('referral_bonus', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Referral bonus - both referrer and referred user receive this', max_digits=10)),
                ('suggestion_reward', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Reward for implemented feature suggestions', max_digits=10)),
                ('suggestions_per_month_limit', models.PositiveIntegerField(default=3, help_text='Maximum feature suggestions per user per month')),
                ('referral_qualification_days', models.PositiveIntegerField(default=90, help_text='Days a referred user must stay subscribed for Founding Member bonus')),
                ('stripe_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('2.9'), help_text='Stripe fee percentage (e.g., 2.9 for 2.9%)', max_digits=5)),
                ('stripe_fee_flat', models.DecimalField(decimal_places=2, default=Decimal('0.30'), help_text='Stripe flat fee per transaction', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Billing Configuration',
                'verbose_name_plural': 'Billing Configuration',
            },
        ),
    ]
