# Generated by Django 4.2.27 on 2026-01-12 16:56

from decimal import Decimal

from django.db import migrations


def create_initial_config(apps, schema_editor):
    """Create the initial billing configuration with default values."""
    BillingConfiguration = apps.get_model('billing', 'BillingConfiguration')

    if not BillingConfiguration.objects.exists():
        BillingConfiguration.objects.create(
            pk=1,
            business_name='Beacon Innovation LLC',
            product_name='Whole Life Journey',
            student_max_age=22,
            student_monthly_price=Decimal('4.99'),
            student_annual_price=Decimal('49.00'),
            adult_monthly_price=Decimal('7.99'),
            adult_annual_price=Decimal('79.00'),
            founding_lifetime_price=Decimal('59.00'),
            founding_quarterly_bonus=Decimal('5.00'),
            referral_bonus=Decimal('5.00'),
            suggestion_reward=Decimal('5.00'),
            suggestions_per_month_limit=3,
            referral_qualification_days=90,
            stripe_fee_percentage=Decimal('2.9'),
            stripe_fee_flat=Decimal('0.30'),
        )


def remove_initial_config(apps, schema_editor):
    """Remove the initial billing configuration (for rollback)."""
    BillingConfiguration = apps.get_model('billing', 'BillingConfiguration')
    BillingConfiguration.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_add_billing_configuration'),
    ]

    operations = [
        migrations.RunPython(create_initial_config, remove_initial_config),
    ]
