# Generated by Django 4.2.27 on 2026-01-15 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0003_populate_initial_billing_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPPromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='The VIP code users will enter (case-insensitive, stored uppercase)', max_length=50, unique=True)),
                ('description', models.CharField(help_text="Internal description (e.g., 'Beta tester reward')", max_length=255)),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='Maximum number of times this code can be used (0 = unlimited)')),
                ('current_uses', models.PositiveIntegerField(default=0, help_text='Number of times this code has been redeemed')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this code can currently be redeemed')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this code expires (null = never expires)', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vip_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VIP Promo Code',
                'verbose_name_plural': 'VIP Promo Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VIPPromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_promo_usages', to=settings.AUTH_USER_MODEL)),
                ('vip_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='billing.vippromocode')),
            ],
            options={
                'verbose_name': 'VIP Promo Code Usage',
                'verbose_name_plural': 'VIP Promo Code Usages',
                'ordering': ['-redeemed_at'],
                'unique_together': {('user', 'vip_code')},
            },
        ),
    ]
