# Generated by Django 4.2.27 on 2026-01-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_add_vip_promo_code_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingconfiguration',
            name='free_trial_days',
            field=models.PositiveIntegerField(default=7, help_text='Number of days for free trial (0 to disable trials)'),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='When the free trial ends (null = no trial or already expired)', null=True),
        ),
    ]
