# Generated by Django 4.2.27 on 2026-01-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_add_trial_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='pricing_tier',
            field=models.CharField(choices=[('free', 'Free'), ('faith_only', 'Faith Only (Free)'), ('student', 'Student ($3.99/mo)'), ('adult', 'Adult ($7.99/mo)'), ('founding', 'Founding Member (Lifetime)')], default='free', help_text="User's current pricing tier", max_length=20),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='subscription_status',
            field=models.CharField(choices=[('none', 'No Subscription'), ('trialing', 'Trialing'), ('active', 'Active'), ('faith_only', 'Faith Only (Free)'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('lifetime', 'Lifetime (Founding Member)')], default='none', help_text='Current subscription status', max_length=20),
        ),
    ]
