# Generated by Django 4.2.27 on 2026-01-24 11:16

import apps.mobile.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(help_text='Unique device identifier (UUID from iOS Keychain)', max_length=128)),
                ('device_name', models.CharField(blank=True, help_text="User-friendly device name (e.g., 'Danny's iPhone')", max_length=255)),
                ('device_model', models.CharField(blank=True, help_text="Device model (e.g., 'iPhone 15 Pro')", max_length=100)),
                ('os_version', models.CharField(blank=True, help_text="OS version (e.g., 'iOS 17.2')", max_length=50)),
                ('app_version', models.CharField(blank=True, help_text="WLJ app version (e.g., '1.0.0')", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Set to False to revoke all tokens for this device')),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Last API request from this device', null=True)),
                ('push_token', models.CharField(blank=True, help_text='APNs push notification token', max_length=255)),
                ('push_enabled', models.BooleanField(default=False, help_text='User has enabled push notifications')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mobile Device',
                'verbose_name_plural': 'Mobile Devices',
            },
        ),
        migrations.CreateModel(
            name='MobileAPIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(help_text='SHA-256 hash of the token', max_length=64, unique=True)),
                ('token_prefix', models.CharField(help_text='First 8 chars of token for identification', max_length=8)),
                ('is_active', models.BooleanField(default=True, help_text='Set to False to revoke this token')),
                ('expires_at', models.DateTimeField(help_text='Token expiration time')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this token was used', null=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, help_text='IP address when token was created', null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='mobile.mobiledevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mobile API Token',
                'verbose_name_plural': 'Mobile API Tokens',
            },
        ),
        migrations.CreateModel(
            name='HealthIngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('partial', 'Partial Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request_timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Client-provided timestamp')),
                ('payload_size_bytes', models.PositiveIntegerField(default=0, help_text='Size of the request payload')),
                ('metrics_received', models.PositiveIntegerField(default=0, help_text='Number of health metrics in request')),
                ('metrics_created', models.PositiveIntegerField(default=0, help_text='New records created')),
                ('metrics_updated', models.PositiveIntegerField(default=0, help_text='Existing records updated')),
                ('metrics_skipped', models.PositiveIntegerField(default=0, help_text='Duplicates or invalid records skipped')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if failed')),
                ('validation_errors', models.JSONField(blank=True, default=list, help_text='List of validation errors for individual metrics')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_ingestion_runs', to='mobile.mobiledevice')),
                ('token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_ingestion_runs', to='mobile.mobileapitoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_ingestion_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Ingestion Run',
                'verbose_name_plural': 'Health Ingestion Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileTokenExchangeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=apps.mobile.models.generate_exchange_code, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_by_device_id', models.CharField(blank=True, help_text='Device ID that consumed this code', max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_exchange_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Exchange Code',
                'verbose_name_plural': 'Token Exchange Codes',
                'indexes': [models.Index(fields=['code'], name='mobile_mobi_code_19cd9e_idx'), models.Index(fields=['user', 'is_used'], name='mobile_mobi_user_id_70e7cd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mobiledevice',
            index=models.Index(fields=['device_id'], name='mobile_mobi_device__949a66_idx'),
        ),
        migrations.AddIndex(
            model_name='mobiledevice',
            index=models.Index(fields=['user', 'is_active'], name='mobile_mobi_user_id_3920cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mobiledevice',
            unique_together={('user', 'device_id')},
        ),
        migrations.AddIndex(
            model_name='mobileapitoken',
            index=models.Index(fields=['token_hash'], name='mobile_mobi_token_h_4eb797_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileapitoken',
            index=models.Index(fields=['user', 'is_active'], name='mobile_mobi_user_id_437b83_idx'),
        ),
        migrations.AddIndex(
            model_name='healthingestionrun',
            index=models.Index(fields=['user', '-created_at'], name='mobile_heal_user_id_33d870_idx'),
        ),
        migrations.AddIndex(
            model_name='healthingestionrun',
            index=models.Index(fields=['status'], name='mobile_heal_status_98db5d_idx'),
        ),
        migrations.AddIndex(
            model_name='healthingestionrun',
            index=models.Index(fields=['-created_at'], name='mobile_heal_created_af7d9f_idx'),
        ),
    ]
