# Generated by Django 4.2.27 on 2026-07-06 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobile', '0002_diagnostic_weight_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthReimportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metrics', models.JSONField(default=list, help_text='HealthKit metric types to re-fetch (e.g. weight, body_fat, lean_body_mass).')),
                ('since_date', models.DateField(blank=True, help_text='Re-fetch samples on/after this local date. NULL = full history.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('scanned', models.PositiveIntegerField(default=0)),
                ('created', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reimport_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Reimport Request',
                'verbose_name_plural': 'Health Reimport Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='mobile_heal_user_id_853cef_idx'), models.Index(fields=['user', 'status'], name='mobile_heal_user_id_d9b1f7_idx')],
            },
        ),
    ]
