# Generated by Django 4.2.27 on 2026-07-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_healthingestionrun_metric_type_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthingestionrun',
            name='client_debug',
            field=models.JSONField(blank=True, default=dict, help_text='Optional client-reported glass-box telemetry for this request: what the iOS app fetched from HealthKit and intended to send, per type (e.g. {"steps": {"raw_samples": 412, "built": 7, "sent": 7}}). Lets us prove exactly where a metric disappears between Apple Health and the DB.'),
        ),
    ]
