# Generated by Django 5.2.9 on 2025-12-28 14:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consented_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When consent was given"
                    ),
                ),
                (
                    "consent_version",
                    models.CharField(
                        default="1.0",
                        help_text="Version of consent terms",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User who gave consent",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_consent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Scan Consent",
                "verbose_name_plural": "Scan Consents",
            },
        ),
        migrations.CreateModel(
            name="ScanLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique ID for this scan request",
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                            ("rate_limited", "Rate Limited"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Status of the scan request",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("food", "Food"),
                            ("medicine", "Medicine"),
                            ("supplement", "Supplement"),
                            ("receipt", "Receipt"),
                            ("document", "Document"),
                            ("workout_equipment", "Workout Equipment"),
                            ("barcode", "Barcode"),
                            ("unknown", "Unknown"),
                        ],
                        help_text="Category identified by AI",
                        max_length=30,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True, help_text="AI confidence score (0.0-1.0)", null=True
                    ),
                ),
                (
                    "items_json",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Detected items as JSON array",
                    ),
                ),
                (
                    "action_taken",
                    models.CharField(
                        blank=True,
                        help_text="What action the user chose (if any)",
                        max_length=100,
                    ),
                ),
                (
                    "image_size_kb",
                    models.PositiveIntegerField(
                        blank=True, help_text="Size of uploaded image in KB", null=True
                    ),
                ),
                (
                    "image_format",
                    models.CharField(
                        blank=True,
                        help_text="Image format (jpeg, png, webp)",
                        max_length=20,
                    ),
                ),
                (
                    "processing_time_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Time to process in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, help_text="Error code if failed", max_length=50
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who initiated the scan",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Scan Log",
                "verbose_name_plural": "Scan Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="scan_scanlo_user_id_69b0ca_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="scan_scanlo_status_91879a_idx",
                    ),
                    models.Index(
                        fields=["category", "-created_at"],
                        name="scan_scanlo_categor_f49362_idx",
                    ),
                ],
            },
        ),
    ]
