# Generated by Django 4.2.27 on 2026-03-02 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('chat', 'AI Chat'), ('scan', 'Camera Scan'), ('inventory', 'Inventory Photo'), ('pet', 'Pet Photo'), ('recipe', 'Recipe Image'), ('project', 'Project Cover'), ('document', 'Document'), ('note', 'Note Image'), ('medical', 'Medical Document')], max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('image_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 hash for dedup', max_length=64)),
                ('summary', models.TextField(blank=True, help_text='1-2 sentence summary')),
                ('detailed_description', models.TextField(blank=True, help_text='Rich natural-language analysis')),
                ('category', models.CharField(blank=True, help_text='Best-fit WLJ category', max_length=30)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('objects_identified', models.JSONField(blank=True, default=list)),
                ('text_detected', models.TextField(blank=True)),
                ('context_clues', models.TextField(blank=True)),
                ('relevance_tags', models.JSONField(blank=True, default=list)),
                ('actionable_insights', models.JSONField(blank=True, default=list)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, max_length=50)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('search_text', models.TextField(blank=True, editable=False, help_text='Combined text from all analysis fields for search')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image Analysis',
                'verbose_name_plural': 'Image Analyses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='scan_imagea_user_id_23ff8b_idx'), models.Index(fields=['user', 'source_type', '-created_at'], name='scan_imagea_user_id_88da97_idx'), models.Index(fields=['status', '-created_at'], name='scan_imagea_status_84fb58_idx'), models.Index(fields=['content_type', 'object_id'], name='scan_imagea_content_022378_idx')],
            },
        ),
    ]
