# Generated by Django 5.2.9 on 2026-01-03 04:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("purpose", "0003_add_habit_goal_and_entry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_via",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("ai_camera", "AI Camera Scan"),
                            ("import", "Data Import"),
                            ("api", "API"),
                        ],
                        default="manual",
                        help_text="How this entry was created",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Account name (e.g., 'Chase Checking', 'Emergency Fund')",
                        max_length=100,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            (
                                "Assets",
                                [
                                    ("checking", "Checking"),
                                    ("savings", "Savings"),
                                    ("cash", "Cash"),
                                    ("investment", "Investment"),
                                    ("property", "Property"),
                                    ("other_asset", "Other Asset"),
                                ],
                            ),
                            (
                                "Liabilities",
                                [
                                    ("credit_card", "Credit Card"),
                                    ("loan", "Loan"),
                                    ("mortgage", "Mortgage"),
                                    ("student_loan", "Student Loan"),
                                    ("other_liability", "Other Liability"),
                                ],
                            ),
                        ],
                        help_text="Type of financial account",
                        max_length=20,
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        blank=True,
                        help_text="Bank or financial institution name",
                        max_length=100,
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current account balance",
                        max_digits=14,
                    ),
                ),
                (
                    "balance_updated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the balance was last updated",
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("CAD", "Canadian Dollar"),
                            ("AUD", "Australian Dollar"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "account_number_last4",
                    models.CharField(
                        blank=True,
                        help_text="Last 4 digits of account number (for identification)",
                        max_length=4,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        default="#6366f1",
                        help_text="Hex color for UI display",
                        max_length=7,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon identifier for UI", max_length=50
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order in account lists"
                    ),
                ),
                (
                    "include_in_net_worth",
                    models.BooleanField(
                        default=True,
                        help_text="Include this account in net worth calculations",
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Hide from main views (but keep in calculations)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Account",
                "verbose_name_plural": "Financial Accounts",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="FinancialGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_via",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("ai_camera", "AI Camera Scan"),
                            ("import", "Data Import"),
                            ("api", "API"),
                        ],
                        default="manual",
                        help_text="How this entry was created",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Goal name (e.g., 'Emergency Fund', 'Pay off Credit Card')",
                        max_length=200,
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("savings", "Savings Goal"),
                            ("debt_payoff", "Debt Payoff"),
                            ("giving", "Giving Goal"),
                            ("purchase", "Major Purchase"),
                            ("emergency", "Emergency Fund"),
                            ("other", "Other"),
                        ],
                        default="savings",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Details about this goal"),
                ),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Target dollar amount",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "current_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current progress amount",
                        max_digits=12,
                    ),
                ),
                (
                    "target_date",
                    models.DateField(
                        blank=True, help_text="Target completion date", null=True
                    ),
                ),
                (
                    "started_at",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="When goal tracking started",
                    ),
                ),
                (
                    "completed_at",
                    models.DateField(
                        blank=True, help_text="When goal was completed", null=True
                    ),
                ),
                (
                    "goal_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#10b981",
                        help_text="Hex color for progress bar",
                        max_length=7,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="💰",
                        help_text="Emoji or icon",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "life_goal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked life goal from Purpose module",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_goals",
                        to="purpose.lifegoal",
                    ),
                ),
                (
                    "linked_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked savings or debt account",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_goals",
                        to="finance.financialaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Goal",
                "verbose_name_plural": "Financial Goals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransactionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Category name", max_length=100)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("income", "Income"),
                            ("expense", "Expense"),
                            ("transfer", "Transfer"),
                        ],
                        default="expense",
                        max_length=10,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6b7280",
                        help_text="Hex color for charts and UI",
                        max_length=7,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Emoji or icon identifier", max_length=50
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="System categories cannot be deleted"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive categories hidden from dropdowns",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category for sub-categories",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="finance.transactioncategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Owner (null for system categories)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction Category",
                "verbose_name_plural": "Transaction Categories",
                "ordering": ["category_type", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_via",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("ai_camera", "AI Camera Scan"),
                            ("import", "Data Import"),
                            ("api", "API"),
                        ],
                        default="manual",
                        help_text="How this entry was created",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(help_text="Transaction date")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount (positive=income, negative=expense)",
                        max_digits=12,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Transaction description or merchant name",
                        max_length=300,
                    ),
                ),
                (
                    "payee",
                    models.CharField(
                        blank=True,
                        help_text="Who received or sent the money",
                        max_length=200,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Check number, confirmation code, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "is_cleared",
                    models.BooleanField(
                        default=False, help_text="Transaction has cleared the account"
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False, help_text="This is a recurring transaction"
                    ),
                ),
                (
                    "is_opening_balance",
                    models.BooleanField(
                        default=False, help_text="This is the opening balance entry"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="User-defined tags"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Account this transaction belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="finance.financialaccount",
                    ),
                ),
                (
                    "transfer_pair",
                    models.OneToOneField(
                        blank=True,
                        help_text="Linked transaction for transfers between accounts",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfer_counterpart",
                        to="finance.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Transaction category",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="finance.transactioncategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_via",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("ai_camera", "AI Camera Scan"),
                            ("import", "Data Import"),
                            ("api", "API"),
                        ],
                        default="manual",
                        help_text="How this entry was created",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Payee/merchant name", max_length=200),
                ),
                (
                    "use_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times used (for sorting suggestions)",
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default category when this payee is selected",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_payees",
                        to="finance.transactioncategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payee",
                "verbose_name_plural": "Payees",
                "ordering": ["-use_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_via",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("ai_camera", "AI Camera Scan"),
                            ("import", "Data Import"),
                            ("api", "API"),
                        ],
                        default="manual",
                        help_text="How this entry was created",
                        max_length=20,
                    ),
                ),
                (
                    "month",
                    models.DateField(
                        help_text="Budget month (stored as first of month)"
                    ),
                ),
                (
                    "budgeted_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Planned spending limit",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "rollover_enabled",
                    models.BooleanField(
                        default=False, help_text="Roll unused budget to next month"
                    ),
                ),
                (
                    "rollover_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount rolled over from previous month",
                        max_digits=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category this budget applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="finance.transactioncategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget",
                "verbose_name_plural": "Budgets",
                "ordering": ["-month", "category__name"],
            },
        ),
        migrations.CreateModel(
            name="FinancialMetricSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_via",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("ai_camera", "AI Camera Scan"),
                            ("import", "Data Import"),
                            ("api", "API"),
                        ],
                        default="manual",
                        help_text="How this entry was created",
                        max_length=20,
                    ),
                ),
                ("snapshot_date", models.DateField(help_text="Date of this snapshot")),
                (
                    "total_assets",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sum of all asset account balances",
                        max_digits=14,
                    ),
                ),
                (
                    "total_liabilities",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sum of all liability account balances",
                        max_digits=14,
                    ),
                ),
                (
                    "net_worth",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Assets minus liabilities",
                        max_digits=14,
                    ),
                ),
                (
                    "monthly_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total income for the month",
                        max_digits=12,
                    ),
                ),
                (
                    "monthly_expenses",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total expenses for the month",
                        max_digits=12,
                    ),
                ),
                (
                    "monthly_cash_flow",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Income minus expenses",
                        max_digits=12,
                    ),
                ),
                (
                    "savings_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage of income saved",
                        max_digits=5,
                    ),
                ),
                (
                    "debt_to_income_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly debt payments / monthly income",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "liquid_assets",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Checking + Savings + Cash",
                        max_digits=14,
                    ),
                ),
                (
                    "emergency_fund_months",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Months of expenses covered by liquid assets",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Metric Snapshot",
                "verbose_name_plural": "Financial Metric Snapshots",
                "ordering": ["-snapshot_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "snapshot_date"],
                        name="finance_fin_user_id_54566f_idx",
                    )
                ],
                "unique_together": {("user", "snapshot_date")},
            },
        ),
        migrations.AddConstraint(
            model_name="transactioncategory",
            constraint=models.UniqueConstraint(
                fields=("user", "name", "category_type"),
                name="unique_user_category_name",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "date"], name="finance_tra_user_id_3294c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["account", "date"], name="finance_tra_account_588697_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["category", "date"], name="finance_tra_categor_e54d5a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="payee",
            unique_together={("user", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="budget",
            unique_together={("user", "month", "category")},
        ),
    ]
