# Generated by Django 5.2.9 on 2026-01-03 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial_finance_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budget",
            name="status",
        ),
        migrations.CreateModel(
            name="TransactionImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_via",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("ai_camera", "AI Camera Scan"),
                            ("import", "Data Import"),
                            ("api", "API"),
                        ],
                        default="manual",
                        help_text="How this entry was created",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded transaction file",
                        upload_to="finance/imports/%Y/%m/",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original name of uploaded file", max_length=255
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("ofx", "OFX"),
                            ("qfx", "QFX"),
                            ("qif", "QIF"),
                        ],
                        help_text="Type of file uploaded",
                        max_length=10,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                (
                    "import_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partial Success"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "rows_total",
                    models.PositiveIntegerField(
                        default=0, help_text="Total rows in file"
                    ),
                ),
                (
                    "rows_imported",
                    models.PositiveIntegerField(
                        default=0, help_text="Rows successfully imported"
                    ),
                ),
                (
                    "rows_skipped",
                    models.PositiveIntegerField(
                        default=0, help_text="Rows skipped (duplicates, errors)"
                    ),
                ),
                (
                    "rows_failed",
                    models.PositiveIntegerField(
                        default=0, help_text="Rows that failed to import"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When import processing started",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When import processing completed",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if import failed"
                    ),
                ),
                (
                    "error_details",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Detailed error information for each failed row",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="User notes about this import"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Account to import transactions into",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imports",
                        to="finance.financialaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction Import",
                "verbose_name_plural": "Transaction Imports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="import_record",
            field=models.ForeignKey(
                blank=True,
                help_text="Import record if this transaction was imported from a file",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="finance.transactionimport",
            ),
        ),
        migrations.AddIndex(
            model_name="transactionimport",
            index=models.Index(
                fields=["user", "created_at"], name="finance_tra_user_id_4c5283_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactionimport",
            index=models.Index(
                fields=["account", "created_at"], name="finance_tra_account_ac25f8_idx"
            ),
        ),
    ]
