# Generated by Django 5.2.9 on 2026-01-03 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_add_transaction_import"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_via",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("ai_camera", "AI Camera Scan"),
                            ("import", "Data Import"),
                            ("api", "API"),
                        ],
                        default="manual",
                        help_text="How this entry was created",
                        max_length=20,
                    ),
                ),
                (
                    "item_id",
                    models.CharField(
                        db_index=True,
                        help_text="Plaid Item ID (unique per institution connection)",
                        max_length=100,
                    ),
                ),
                (
                    "access_token_encrypted",
                    models.TextField(help_text="Encrypted Plaid access token"),
                ),
                (
                    "institution_id",
                    models.CharField(help_text="Plaid institution ID", max_length=50),
                ),
                (
                    "institution_name",
                    models.CharField(
                        help_text="Display name of the institution", max_length=200
                    ),
                ),
                (
                    "institution_logo",
                    models.URLField(
                        blank=True, help_text="URL to institution logo (from Plaid)"
                    ),
                ),
                (
                    "institution_color",
                    models.CharField(
                        blank=True,
                        help_text="Institution primary color (hex)",
                        max_length=7,
                    ),
                ),
                (
                    "connection_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending Initial Sync"),
                            ("error", "Error"),
                            ("disconnected", "Disconnected"),
                            ("reauth_required", "Requires Re-authentication"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        help_text="Plaid error code if connection has issues",
                        max_length=50,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Human-readable error message"
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last successful transaction sync",
                        null=True,
                    ),
                ),
                (
                    "last_sync_cursor",
                    models.CharField(
                        blank=True,
                        help_text="Plaid sync cursor for incremental updates",
                        max_length=500,
                    ),
                ),
                (
                    "transactions_synced",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total transactions synced from this connection",
                    ),
                ),
                (
                    "consent_given_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When user authorized this connection",
                    ),
                ),
                (
                    "consent_ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address when consent was given",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank Connection",
                "verbose_name_plural": "Bank Connections",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BankIntegrationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_via",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("ai_camera", "AI Camera Scan"),
                            ("import", "Data Import"),
                            ("api", "API"),
                        ],
                        default="manual",
                        help_text="How this entry was created",
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("connect", "Connected"),
                            ("disconnect", "Disconnected"),
                            ("sync", "Synced"),
                            ("error", "Error"),
                            ("reauth", "Re-authenticated"),
                            ("webhook", "Webhook Received"),
                        ],
                        max_length=20,
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional event details (redacted for security)",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Bank Integration Log",
                "verbose_name_plural": "Bank Integration Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="financialaccount",
            name="is_synced",
            field=models.BooleanField(
                default=False, help_text="Whether this account syncs with a bank"
            ),
        ),
        migrations.AddField(
            model_name="financialaccount",
            name="last_balance_sync",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time balance was synced from bank",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="financialaccount",
            name="plaid_account_id",
            field=models.CharField(
                blank=True,
                help_text="Plaid account ID for synced accounts",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="plaid_pending",
            field=models.BooleanField(
                default=False, help_text="Whether this is a pending Plaid transaction"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="plaid_transaction_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Plaid transaction ID for synced transactions",
                max_length=100,
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["plaid_transaction_id"], name="finance_tra_plaid_t_1cab2a_idx"
            ),
        ),
        migrations.AddField(
            model_name="bankconnection",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="financialaccount",
            name="bank_connection",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked bank connection if synced",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounts",
                to="finance.bankconnection",
            ),
        ),
        migrations.AddField(
            model_name="bankintegrationlog",
            name="bank_connection",
            field=models.ForeignKey(
                help_text="Related bank connection",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="finance.bankconnection",
            ),
        ),
        migrations.AddField(
            model_name="bankintegrationlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="bankconnection",
            index=models.Index(
                fields=["user", "connection_status"],
                name="finance_ban_user_id_3e9e7b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bankconnection",
            unique_together={("user", "item_id")},
        ),
        migrations.AddIndex(
            model_name="bankintegrationlog",
            index=models.Index(
                fields=["bank_connection", "action"],
                name="finance_ban_bank_co_5867b1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bankintegrationlog",
            index=models.Index(
                fields=["user", "created_at"], name="finance_ban_user_id_ca8e8a_idx"
            ),
        ),
    ]
