# Generated by Django 5.2.9 on 2026-01-03 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_add_bank_connection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("view", "Viewed"),
                            ("transfer", "Transferred"),
                            ("import", "Imported"),
                            ("export", "Exported"),
                            ("ai_query", "AI Query"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("account", "Account"),
                            ("transaction", "Transaction"),
                            ("budget", "Budget"),
                            ("goal", "Goal"),
                            ("import", "Import"),
                            ("bank_connection", "Bank Connection"),
                            ("ai_insight", "AI Insight"),
                        ],
                        max_length=30,
                    ),
                ),
                ("entity_id", models.IntegerField(blank=True, null=True)),
                ("success", models.BooleanField(default=True)),
                (
                    "details",
                    models.JSONField(
                        blank=True, default=dict, help_text="Redacted operation details"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Finance Audit Log",
                "verbose_name_plural": "Finance Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="finance_fin_user_id_624295_idx",
                    ),
                    models.Index(
                        fields=["action", "entity_type"],
                        name="finance_fin_action_98380d_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="finance_fin_entity__3eb437_idx",
                    ),
                ],
            },
        ),
    ]
