# Generated by Django 5.2.9 on 2026-01-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_fix_budget_status_field"),
    ]

    operations = []
