# Generated by Django 5.2.9 on 2026-01-03 15:11

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0010_fix_budget_status_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("archived", "Archived"),
                    ("deleted", "Deleted"),
                ],
                db_index=True,
                default="active",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="transactionimport",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Uploaded transaction file (deleted after processing for security)",
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="finance/imports/%Y/%m/",
            ),
        ),
    ]
