# Generated by Django 5.2.10 on 2026-01-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0011_use_local_storage_for_imports"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("archived", "Archived"),
                    ("deleted", "Deleted"),
                ],
                db_index=True,
                default="active",
                max_length=10,
            ),
        ),
    ]
