# Generated by Django 5.2.10 on 2026-01-08 14:00
# Modified to skip if column already exists (production has it from earlier migrations)

from django.db import migrations, models, connection


def column_exists(table_name, column_name):
    """Check if a column exists in the database."""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = %s AND column_name = %s
            )
        """, [table_name, column_name])
        return cursor.fetchone()[0]


def add_status_if_missing(apps, schema_editor):
    """Add status column only if it doesn't exist."""
    if not column_exists('finance_budget', 'status'):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                ALTER TABLE finance_budget
                ADD COLUMN status VARCHAR(10) DEFAULT 'active' NOT NULL
            """)
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS finance_budget_status_idx
                ON finance_budget (status)
            """)


def noop(apps, schema_editor):
    """No-op for reverse migration."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0011_use_local_storage_for_imports"),
    ]

    operations = [
        migrations.RunPython(add_status_if_missing, noop),
    ]
