# Generated by Django 4.2.27 on 2026-01-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_sync_budget_status_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaccount',
            name='account_type',
            field=models.CharField(choices=[('Assets', (('checking', 'Checking'), ('savings', 'Savings'), ('cash', 'Cash'), ('investment', 'Investment'), ('property', 'Property'), ('other_asset', 'Other Asset'))), ('Liabilities', (('credit_card', 'Credit Card'), ('loan', 'Loan'), ('mortgage', 'Mortgage'), ('student_loan', 'Student Loan'), ('other_liability', 'Other Liability')))], help_text='Type of financial account', max_length=20),
        ),
    ]
