# Generated by Django 4.2.27 on 2026-01-20 15:38

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0014_alter_financialaccount_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('name', models.CharField(help_text="Name of the recurring transaction (e.g., 'Netflix', 'Paycheck')", max_length=200)),
                ('transaction_type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], default='expense', help_text='Whether this is income or expense', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount (always positive, type determines sign)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payee', models.CharField(blank=True, help_text='Who receives or sends the money', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Notes for generated transactions')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Every Two Weeks'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('custom_pattern', models.CharField(blank=True, help_text="Custom recurrence pattern (e.g., 'every_3_weeks', 'monthly:15')", max_length=100)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='Day of month for monthly transactions (1-31)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, help_text='Day of week for weekly transactions (0=Monday, 6=Sunday)', null=True)),
                ('start_date', models.DateField(help_text='When this recurring transaction starts')),
                ('end_date', models.DateField(blank=True, help_text='When this recurring transaction ends (optional)', null=True)),
                ('next_due_date', models.DateField(help_text='Next scheduled occurrence')),
                ('last_generated_date', models.DateField(blank=True, help_text='Date of last generated transaction', null=True)),
                ('total_generated', models.PositiveIntegerField(default=0, help_text='Total transactions generated from this template')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this recurring transaction is active')),
                ('is_auto_post', models.BooleanField(default=False, help_text='Automatically create transactions (vs. reminder only)')),
                ('remind_days_before', models.PositiveSmallIntegerField(default=0, help_text='Days before due date to send reminder (0 = no reminder)')),
                ('account', models.ForeignKey(help_text='Account for this recurring transaction', on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to='finance.financialaccount')),
                ('category', models.ForeignKey(blank=True, help_text='Category for generated transactions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_transactions', to='finance.transactioncategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurring Transaction',
                'verbose_name_plural': 'Recurring Transactions',
                'ordering': ['next_due_date', 'name'],
                'indexes': [models.Index(fields=['user', 'is_active', 'next_due_date'], name='finance_rec_user_id_fd6534_idx'), models.Index(fields=['next_due_date'], name='finance_rec_next_du_8701fb_idx')],
            },
        ),
    ]
