# Generated by Django 4.2.27 on 2026-03-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_add_recurring_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source_id',
            field=models.CharField(blank=True, default='', help_text='Source record ID (document ID, email message ID, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('import', 'File Import'), ('email', 'Email Extraction'), ('document', 'Document Extraction'), ('receipt_scan', 'Receipt Scan'), ('plaid', 'Plaid Sync')], default='manual', help_text='How this transaction was created', max_length=20),
        ),
    ]
