# Generated by Django 4.2.27 on 2026-03-17 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0029_phase6b_completion'),
        ('finance', '0016_phase6a_knowledge_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Hash of normalized merchant+amount+date for dedup', max_length=64),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt_document',
            field=models.ForeignKey(blank=True, help_text='Linked receipt document (from email attachment)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_transactions', to='life.document'),
        ),
    ]
