# Generated by Django 4.2.27 on 2026-03-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_phase6b_tx_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankconnection',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='bankintegrationlog',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='budget',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='financialgoal',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='financialmetricsnapshot',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='payee',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionimport',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
    ]
