# Generated by Django 4.2.27 on 2026-08-25 01:54

import apps.core.current_context
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0018_routine_maintenance_bridge_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountEntityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('effective_from', models.DateField(db_index=True, help_text='First date this entity owned the account (inclusive).')),
                ('effective_to', models.DateField(blank=True, help_text='Last date this entity owned the account (inclusive). NULL = current.', null=True)),
                ('actor', models.CharField(choices=[('user', 'User'), ('migration', 'Migration'), ('system', 'System')], default='user', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Account Entity Assignment',
                'verbose_name_plural': 'Account Entity Assignments',
                'ordering': ['account_id', '-effective_from'],
            },
            bases=(apps.core.current_context.NarratableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AttributionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('scope', models.CharField(choices=[('recurring_series', 'Recurring series'), ('payee', 'Payee'), ('account', 'Account'), ('description_pattern', 'Description pattern')], db_index=True, max_length=24)),
                ('pattern', models.CharField(blank=True, default='', help_text='Reserved for the description_pattern scope. Unused in the MVP.', max_length=200)),
                ('origin', models.CharField(choices=[('user_confirmation', 'Created from a user confirmation'), ('user_authored', 'Authored by the user'), ('imported', 'Imported')], default='user_confirmation', max_length=24)),
                ('user_confirmed', models.BooleanField(default=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('rule_status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('expired', 'Expired')], db_index=True, default='active', max_length=16)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Attribution Rule',
                'verbose_name_plural': 'Attribution Rules',
                'ordering': ['-created_at'],
            },
            bases=(apps.core.current_context.NarratableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FinancialEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('entity_type', models.CharField(choices=[('personal', 'Personal'), ('household', 'Household / Shared'), ('business', 'Business'), ('other', 'Other'), ('unknown', 'Unknown')], db_index=True, default='business', help_text='Classification. This is the only part of an entity code may branch on.', max_length=16)),
                ('name', models.CharField(help_text="Display name exactly as the user typed it. Data, never logic.", max_length=120)),
                ('name_key', models.CharField(db_index=True, editable=False, help_text='Normalized (case/whitespace-insensitive) uniqueness key derived from name.', max_length=120)),
                ('is_default_personal', models.BooleanField(default=False, help_text="The user's default personal entity. Exactly one per user.")),
                ('is_active', models.BooleanField(default=True, help_text='Retired entities stay resolvable for historical attribution.')),
                ('space_ref', models.CharField(blank=True, default='', help_text='Forward hook for Space linkage (docs/WLJ_SECURITY_AUTHORIZATION_FRAMEWORK.md). UNUSED — no authorization logic reads this field.', max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Financial Entity',
                'verbose_name_plural': 'Financial Entities',
                'ordering': ['sort_order', 'name'],
            },
            bases=(apps.core.current_context.NarratableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TransactionAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('source', models.CharField(choices=[('user_direct', 'User chose directly'), ('user_rule', 'Applied from a user rule'), ('account_default', "Paying account's entity"), ('import_declared', 'Declared by the import source'), ('migration_bootstrap', 'Written by a migration'), ('model_suggested', 'Suggested in conversation')], db_index=True, max_length=24)),
                ('actor', models.CharField(choices=[('user', 'User'), ('rule', 'Rule'), ('import', 'Import'), ('migration', 'Migration'), ('system', 'System (deterministic refresh)')], max_length=16)),
                ('confidence', models.FloatField(default=1.0, help_text='0.0–1.0. User-confirmed rows are 1.0.')),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Concise references + scalars only. Never account numbers or tokens.')),
                ('user_confirmed', models.BooleanField(db_index=True, default=False, help_text='Only the confirmation service may set this. No rule path can.')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('attribution_status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded by a correction')], db_index=True, default='active', max_length=16)),
                ('share_basis', models.CharField(choices=[('full', 'Whole transaction'), ('percent', 'Percentage share'), ('amount', 'Fixed amount share')], default='full', help_text="Always 'full' in the MVP. Splits attach here without a schema change.", max_length=8)),
                ('share_value', models.DecimalField(blank=True, decimal_places=2, help_text="Percentage or amount when share_basis is not 'full'.", max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Transaction Attribution',
                'verbose_name_plural': 'Transaction Attributions',
                'ordering': ['-created_at'],
            },
            bases=(apps.core.current_context.NarratableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurring_source',
            field=models.ForeignKey(blank=True, help_text='The recurring commitment that generated this transaction, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_transactions', to='finance.recurringtransaction'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'recurring_source'], name='idx_txn_user_recurring_src'),
        ),
        migrations.AddField(
            model_name='transactionattribution',
            name='attributed_entity',
            field=models.ForeignKey(help_text='Who SHOULD bear this cost.', on_delete=django.db.models.deletion.PROTECT, related_name='attributions', to='finance.financialentity'),
        ),
        migrations.AddField(
            model_name='transactionattribution',
            name='paid_by_entity',
            field=models.ForeignKey(help_text="Who DID bear it — snapshot of the account's entity on the transaction date.", on_delete=django.db.models.deletion.PROTECT, related_name='paid_attributions', to='finance.financialentity'),
        ),
        migrations.AddField(
            model_name='transactionattribution',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions', to='finance.attributionrule'),
        ),
        migrations.AddField(
            model_name='transactionattribution',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='finance.transactionattribution'),
        ),
        migrations.AddField(
            model_name='transactionattribution',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='finance.transaction'),
        ),
        migrations.AddField(
            model_name='transactionattribution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialentity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attributionrule',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribution_rules', to='finance.financialaccount'),
        ),
        migrations.AddField(
            model_name='attributionrule',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attribution_rules', to='finance.financialentity'),
        ),
        migrations.AddField(
            model_name='attributionrule',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribution_rules', to='finance.payee'),
        ),
        migrations.AddField(
            model_name='attributionrule',
            name='recurring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribution_rules', to='finance.recurringtransaction'),
        ),
        migrations.AddField(
            model_name='attributionrule',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='finance.attributionrule'),
        ),
        migrations.AddField(
            model_name='attributionrule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountentityassignment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entity_assignments', to='finance.financialaccount'),
        ),
        migrations.AddField(
            model_name='accountentityassignment',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_assignments', to='finance.financialentity'),
        ),
        migrations.AddField(
            model_name='accountentityassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='transactionattribution',
            index=models.Index(fields=['user', 'attribution_status'], name='idx_txattr_user_status'),
        ),
        migrations.AddIndex(
            model_name='transactionattribution',
            index=models.Index(fields=['user', 'attributed_entity', 'attribution_status'], name='idx_txattr_user_entity'),
        ),
        migrations.AddIndex(
            model_name='transactionattribution',
            index=models.Index(fields=['user', 'paid_by_entity', 'attributed_entity', 'attribution_status'], name='idx_txattr_mismatch'),
        ),
        migrations.AddConstraint(
            model_name='transactionattribution',
            constraint=models.UniqueConstraint(condition=models.Q(('attribution_status', 'active'), ('share_basis', 'full'), ('status', 'active')), fields=('transaction',), name='uq_txattr_one_active_full'),
        ),
        migrations.AddIndex(
            model_name='financialentity',
            index=models.Index(fields=['user', 'entity_type', 'is_active'], name='idx_finentity_user_type'),
        ),
        migrations.AddConstraint(
            model_name='financialentity',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('status', 'active')), fields=('user', 'name_key'), name='uq_finentity_active_name_key'),
        ),
        migrations.AddConstraint(
            model_name='financialentity',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default_personal', True), ('status', 'active')), fields=('user',), name='uq_finentity_default_personal'),
        ),
        migrations.AddConstraint(
            model_name='financialentity',
            constraint=models.UniqueConstraint(condition=models.Q(('entity_type', 'unknown'), ('status', 'active')), fields=('user',), name='uq_finentity_unknown'),
        ),
        migrations.AddIndex(
            model_name='attributionrule',
            index=models.Index(fields=['user', 'rule_status', 'scope'], name='idx_attrrule_user_status'),
        ),
        migrations.AddIndex(
            model_name='attributionrule',
            index=models.Index(fields=['user', 'payee'], name='idx_attrrule_user_payee'),
        ),
        migrations.AddIndex(
            model_name='attributionrule',
            index=models.Index(fields=['user', 'recurring'], name='idx_attrrule_user_recur'),
        ),
        migrations.AddIndex(
            model_name='attributionrule',
            index=models.Index(fields=['user', 'account'], name='idx_attrrule_user_account'),
        ),
        migrations.AddIndex(
            model_name='accountentityassignment',
            index=models.Index(fields=['account', 'effective_from'], name='idx_acctentity_acct_from'),
        ),
        migrations.AddIndex(
            model_name='accountentityassignment',
            index=models.Index(fields=['user', 'entity'], name='idx_acctentity_user_entity'),
        ),
        migrations.AddConstraint(
            model_name='accountentityassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True), ('status', 'active')), fields=('account',), name='uq_acctentity_one_open'),
        ),
    ]
