# Generated by Django 4.2.27 on 2026-08-25 02:08

import apps.core.current_context
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0137_accept_owner_legacy_personal_knowledge'),
        ('ai', '0045_real_llm_authorization'),
        ('finance', '0020_f0_bootstrap_default_entities'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('kind', models.CharField(choices=[('entity_payment_mismatch', 'Expense paid by the wrong entity')], default='entity_payment_mismatch', max_length=32)),
                ('dedupe_key', models.CharField(db_index=True, help_text='Stable key shared with the canonical Insight for this pattern.', max_length=64)),
                ('payee_key', models.CharField(blank=True, default='', max_length=200)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('state', models.CharField(choices=[('detected', 'Detected'), ('presented', 'Presented'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('deferred', 'Deferred'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('verified_auto', 'Verified automatically'), ('verified_manual', 'Verified manually'), ('not_relevant', 'No longer relevant')], db_index=True, default='detected', max_length=20)),
                ('state_changed_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('deferred_until', models.DateField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('occurrences', models.PositiveIntegerField(default=0)),
                ('annual_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('baseline', models.JSONField(blank=True, default=dict, help_text='Truth captured at acceptance, so later evidence is provably NEW.')),
                ('verification_evidence', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('attributed_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities_as_bearer', to='finance.financialentity')),
                ('follow_up', models.ForeignKey(blank=True, help_text='The existing follow-through record — WLJ adds no second scheduler.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_opportunities', to='ai.conversationfollowup')),
                ('insight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_opportunities', to='core.insight')),
                ('paid_by_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities_as_payer', to='finance.financialentity')),
                ('recurring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='finance.recurringtransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Finance Opportunity',
                'verbose_name_plural': 'Finance Opportunities',
                'ordering': ['-annual_estimate', '-created_at'],
                'indexes': [models.Index(fields=['user', 'state'], name='idx_finopp_user_state'), models.Index(fields=['user', 'kind', 'state'], name='idx_finopp_user_kind')],
            },
            bases=(apps.core.current_context.NarratableMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='financeopportunity',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'dedupe_key'), name='uq_finopp_user_dedupe'),
        ),
    ]
