# Generated by Django 4.2.27 on 2026-08-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_provider_revocation_pending_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeauditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('view', 'Viewed'), ('transfer', 'Transferred'), ('import', 'Imported'), ('export', 'Exported'), ('ai_query', 'AI Query'), ('reset', 'Module Reset')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financeauditlog',
            name='entity_type',
            field=models.CharField(choices=[('account', 'Account'), ('transaction', 'Transaction'), ('budget', 'Budget'), ('goal', 'Goal'), ('import', 'Import'), ('bank_connection', 'Bank Connection'), ('ai_insight', 'AI Insight'), ('module', 'Finance Module')], max_length=30),
        ),
    ]
