# Generated by Django 4.2.27 on 2026-08-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_finance_reset_audit_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category_source',
            field=models.CharField(choices=[('none', 'Not categorized'), ('provider_mapped', 'Mapped from the provider'), ('rule', 'Applied from a user rule'), ('user', 'Chosen by the user')], db_index=True, default='none', help_text='How the WLJ category was decided. A user choice outranks every provider or inferred value and is never silently replaced.', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_authorized_date',
            field=models.DateField(blank=True, help_text='When the provider says it was authorized (may precede posting).', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_category',
            field=models.JSONField(blank=True, default=list, help_text="Provider's legacy category hierarchy, verbatim. Never overwritten."),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_category_confidence',
            field=models.CharField(blank=True, default='', help_text="Provider's confidence in its own classification (gates mapping).", max_length=16),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_category_detailed',
            field=models.CharField(blank=True, default='', help_text="Provider's personal-finance-category DETAILED value, verbatim.", max_length=128),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_category_primary',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Provider's personal-finance-category PRIMARY value, verbatim.", max_length=64),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_counterparties',
            field=models.JSONField(blank=True, default=list, help_text='Counterparty NAMES and TYPES only — never account identifiers.'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_merchant_name',
            field=models.CharField(blank=True, default='', help_text='Normalized merchant as the provider resolved it.', max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_payment_channel',
            field=models.CharField(blank=True, default='', help_text='online / in store / other — a transfer signal.', max_length=24),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_pending_transaction_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='The pending row this posted transaction replaces. The key to pending→posted matching; without it a pending and its posted twin become two transactions.', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_transaction_code',
            field=models.CharField(blank=True, default='', help_text="Provider transaction code (e.g. 'transfer', 'purchase').", max_length=32),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_classified_by',
            field=models.CharField(blank=True, choices=[('', 'Unset'), ('provider', 'Provider classification'), ('pairing', 'Matched to its counterpart'), ('user', 'Confirmed by the user')], default='', help_text='A user decision here outranks provider and pairing alike.', max_length=16),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_kind',
            field=models.CharField(blank=True, choices=[('', 'None'), ('internal_transfer', 'Internal transfer'), ('credit_card_payment', 'Credit-card payment'), ('refund', 'Refund'), ('reversal', 'Reversal')], default='', max_length=24),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_state',
            field=models.CharField(choices=[('unknown', 'Not yet assessed'), ('not_transfer', 'Ordinary activity'), ('candidate', 'Possible transfer — held for review'), ('confirmed', 'Confirmed transfer / payment')], db_index=True, default='unknown', help_text='CONFIRMED leaves spending totals; CANDIDATE is held out AND reviewed — never silently counted either way.', max_length=16),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transfer_state', 'date'], name='idx_txn_user_transfer'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['provider_pending_transaction_id'], name='idx_txn_pending_link'),
        ),
    ]
