# Generated by Django 4.2.27 on 2026-08-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_provider_provenance_and_transfer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankconnection',
            name='connection_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Connected — preparing transactions'), ('error', 'Error'), ('disconnected', 'Disconnected'), ('reauth_required', 'Requires Re-authentication'), ('revocation_pending', 'Disconnect pending — provider revocation failed')], default='pending', max_length=20),
        ),
    ]
