# Generated by Django 4.2.27 on 2026-08-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_connection_preparing_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankconnection',
            name='historical_update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='historical_update_complete',
            field=models.BooleanField(default=False, help_text='The provider has finished backfilling the FULL requested window. Until this is true, totals and baselines are provisional.'),
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='history_days_requested',
            field=models.PositiveIntegerField(blank=True, help_text='Days of history requested when this Item was created. Fixed at creation; widening it requires re-running Link in update mode.', null=True),
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='initial_update_complete',
            field=models.BooleanField(default=False, help_text='The provider has delivered the recent-window transactions.'),
        ),
    ]
