# Generated by Django 4.2.27 on 2026-08-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_history_coverage_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankconnection',
            name='history_days_requested',
            field=models.PositiveIntegerField(blank=True, help_text='Days of history requested when this Item was created. Decided ONCE, at creation: after Transactions initializes, days_requested has no effect, so a longer window requires a new Item.', null=True),
        ),
    ]
