# Generated by Django 4.2.27 on 2026-08-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_correct_history_window_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankconnection',
            name='last_webhook_rejected_at',
            field=models.DateTimeField(blank=True, help_text='When the provider last called us with a delivery we refused.', null=True),
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='last_webhook_rejection_reason',
            field=models.CharField(blank=True, default='', help_text='Verification reason code for that refusal. A WLJ-side fault and a genuinely unrecognised key are DIFFERENT codes on purpose.', max_length=64),
        ),
    ]
