# Generated by Django 4.2.27 on 2026-08-30 01:30

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_dedupe_provider_transactions_and_constrain'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transactioncategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), models.F('category_type'), condition=models.Q(('user__isnull', False)), name='uq_personal_category_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='transactioncategory',
            constraint=models.CheckConstraint(check=models.Q(('name', ''), _negated=True), name='ck_category_name_not_blank'),
        ),
    ]
