# Generated by Django 4.2.27 on 2026-08-30 02:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_category_uniqueness_guards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialgoal',
            name='started_at',
            field=models.DateField(default=django.utils.timezone.localdate, help_text="When goal tracking started (the user's local date)"),
        ),
    ]
