# Generated by Django 4.2.27 on 2026-08-30 21:35

import apps.core.current_context
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0033_correct_utc_dated_goal_start_retry'),
    ]

    operations = [
        migrations.CreateModel(
            name='TangibleAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('name', models.CharField(help_text="What you call it (e.g. 'Home', 'F-150')", max_length=200)),
                ('asset_type', models.CharField(choices=[('real_estate', 'Real estate'), ('vehicle', 'Vehicle'), ('boat', 'Boat / watercraft'), ('rv', 'Recreational vehicle'), ('other', 'Other tangible asset')], db_index=True, default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state_region', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('square_feet', models.PositiveIntegerField(blank=True, null=True)),
                ('make', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('model_year', models.PositiveIntegerField(blank=True, null=True)),
                ('vin', models.CharField(blank=True, max_length=32)),
                ('hull_identification_number', models.CharField(blank=True, max_length=32)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('engine_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('length_feet', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('include_in_net_worth', models.BooleanField(default=True, help_text='Counted in total assets and net worth while active')),
                ('entity', models.ForeignKey(blank=True, help_text='Who this belongs to, if you track that', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tangible_assets', to='finance.financialentity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tangible Asset',
                'verbose_name_plural': 'Tangible Assets',
                'ordering': ['asset_type', 'name'],
            },
            bases=(apps.core.current_context.NarratableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AssetValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('effective_date', models.DateField(help_text='The date this value is a statement ABOUT')),
                ('source', models.CharField(choices=[('manual', 'Entered by you'), ('appraisal', 'Professional appraisal'), ('comparable', 'Comparable sale'), ('provider', 'External estimate')], default='manual', max_length=20)),
                ('source_detail', models.CharField(blank=True, help_text='Who or what said so (appraiser, provider, listing…)', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_estimate', models.BooleanField(default=False, help_text='An estimate is labelled as one wherever it is shown')),
                ('range_low', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('range_high', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('confidence', models.CharField(blank=True, help_text='As reported by the provider', max_length=40)),
                ('limitations', models.TextField(blank=True, help_text='What the provider says this number does NOT mean')),
                ('retrieved_at', models.DateTimeField(blank=True, help_text='When it was fetched — distinct from what date it is about', null=True)),
                ('provider_key', models.CharField(blank=True, max_length=60)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='finance.tangibleasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Valuation',
                'verbose_name_plural': 'Asset Valuations',
                'ordering': ['-effective_date', '-id'],
            },
            bases=(apps.core.current_context.NarratableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AssetLoanLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secured_asset_links', to='finance.financialaccount')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_links', to='finance.tangibleasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Loan Link',
                'verbose_name_plural': 'Asset Loan Links',
                'ordering': ['id'],
            },
            bases=(apps.core.current_context.NarratableMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='tangibleasset',
            index=models.Index(fields=['user', 'asset_type', 'status'], name='finance_tan_user_id_eb9f5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='tangibleasset',
            constraint=models.CheckConstraint(check=models.Q(('name', ''), _negated=True), name='ck_asset_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='tangibleasset',
            constraint=models.CheckConstraint(check=models.Q(('purchase_price__isnull', True), ('purchase_price__gte', 0), _connector='OR'), name='ck_asset_purchase_price_non_negative'),
        ),
        migrations.AddIndex(
            model_name='assetvaluation',
            index=models.Index(fields=['asset', '-effective_date'], name='finance_ass_asset_i_72ebb4_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetvaluation',
            constraint=models.CheckConstraint(check=models.Q(('amount__gte', 0)), name='ck_valuation_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='assetvaluation',
            constraint=models.CheckConstraint(check=models.Q(('range_low__isnull', True), ('range_high__isnull', True), ('range_high__gte', models.F('range_low')), _connector='OR'), name='ck_valuation_range_ordered'),
        ),
        migrations.AddConstraint(
            model_name='assetloanlink',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('asset', 'account'), name='uq_active_asset_loan_link'),
        ),
    ]
