# Generated by Django 4.2.27 on 2026-08-31 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0034_tangible_asset_registry'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='economic_role',
            field=models.CharField(blank=True, choices=[('purchase', 'Purchase'), ('refund', 'Refund'), ('reimbursement', 'Reimbursement'), ('reversal_chargeback', 'Reversal / chargeback'), ('income', 'Income'), ('internal_transfer', 'Internal transfer'), ('card_payment', 'Credit-card payment'), ('savings_allocation', 'Savings allocation'), ('investment_contribution', 'Investment contribution'), ('debt_service', 'Debt service'), ('fee_or_interest_charged', 'Fee or interest charged'), ('cash_withdrawal', 'Cash withdrawal'), ('uncertain', 'Uncertain'), ('opening_balance', 'Opening balance')], db_index=True, help_text='P1 shadow: the role this plays in household economics', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='refund_of',
            field=models.ForeignKey(blank=True, help_text='The original purchase, when the link is proven', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='finance.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='role_classified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='role_classifier_version',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='transaction',
            name='role_confidence',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='role_reason',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='transaction',
            name='role_source',
            field=models.CharField(blank=True, choices=[('derived', 'Inferred by WLJ'), ('provider', 'Provider classification'), ('pairing', 'Matched to its counterpart'), ('user', 'Confirmed by you')], max_length=16, null=True),
        ),
    ]
