# Generated by Django 4.2.27 on 2026-08-31 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0035_p1_economic_role_shadow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='economic_role',
            field=models.CharField(blank=True, choices=[('purchase', 'Purchase'), ('refund', 'Refund'), ('reimbursement', 'Reimbursement'), ('reversal_chargeback', 'Reversal / chargeback'), ('income', 'Income'), ('internal_transfer', 'Internal transfer'), ('card_payment', 'Credit-card payment'), ('savings_allocation', 'Savings allocation'), ('investment_contribution', 'Investment contribution'), ('debt_service', 'Debt service'), ('fee_or_interest_charged', 'Fee or interest charged'), ('cash_withdrawal', 'Cash withdrawal'), ('uncertain', 'Uncertain'), ('loan_proceeds', 'Loan proceeds / borrowed funds'), ('opening_balance', 'Opening balance')], db_index=True, help_text='P1 shadow: the role this plays in household economics', max_length=32, null=True),
        ),
    ]
