# Generated by Django 4.2.27 on 2026-08-31 01:01

import apps.core.current_context
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0036_alter_transaction_economic_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('scope', models.CharField(choices=[('category', 'A whole category'), ('rule', 'Anything matching a rule'), ('payee', 'One payee or merchant'), ('recurring_series', 'One recurring series'), ('transaction', 'One transaction')], db_index=True, max_length=20)),
                ('payee', models.CharField(blank=True, default='', help_text='Normalised payee/merchant name this classification applies to.', max_length=200)),
                ('match_contains', models.CharField(blank=True, default='', help_text='For a rule: a case-insensitive fragment of the description.', max_length=200)),
                ('necessity', models.CharField(choices=[('essential', 'Essential — I have to pay this'), ('discretionary', 'Discretionary — this is a choice'), ('unknown', 'Not yet decided')], default='unknown', max_length=16)),
                ('variability', models.CharField(choices=[('fixed', 'Fixed — the same every time'), ('variable', 'Variable — the amount moves'), ('unknown', 'Not yet decided')], default='unknown', max_length=16)),
                ('levers', models.JSONField(blank=True, default=list, help_text='Zero or more of cancellable/negotiable/reducible/avoidable/deferrable. They co-occur, so this is a list, not a choice.')),
                ('source', models.CharField(choices=[('user', 'You decided this'), ('inferred', 'WLJ inferred it'), ('provider', 'The bank suggested it')], db_index=True, default='user', max_length=12)),
                ('note', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controllability_classifications', to='finance.transactioncategory')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controllability_classifications', to='finance.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spending classification',
                'indexes': [models.Index(fields=['user', 'scope', 'status'], name='finance_spe_user_id_7dc48b_idx'), models.Index(fields=['user', 'payee'], name='finance_spe_user_id_25928d_idx')],
            },
            bases=(apps.core.current_context.NarratableMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='spendingclassification',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'transaction'), name='uniq_active_controllability_per_transaction'),
        ),
        migrations.AddConstraint(
            model_name='spendingclassification',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'category'), name='uniq_active_controllability_per_category'),
        ),
        migrations.AddConstraint(
            model_name='spendingclassification',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active'), models.Q(('payee', ''), _negated=True)), fields=('user', 'payee'), name='uniq_active_controllability_per_payee'),
        ),
    ]
