# Generated by Django 4.2.27 on 2026-08-31 01:07

import apps.core.current_context
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0037_spendingclassification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('payee', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('kind', models.CharField(choices=[('bill', 'Bill'), ('subscription', 'Subscription'), ('income', 'Recurring income'), ('debt_payment', 'Debt payment'), ('transfer', 'Transfer'), ('savings_allocation', 'Savings allocation'), ('other', 'Other')], db_index=True, default='bill', max_length=24)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Every two weeks'), ('semimonthly', 'Twice a month'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semiannual', 'Twice a year'), ('annual', 'Annually'), ('irregular', 'Irregular — predictable, but not on a schedule')], default='monthly', max_length=16)),
                ('amount_expected', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_variable', models.BooleanField(default=False, help_text='The amount genuinely moves. A range is the honest answer; a single expected figure would be invented.')),
                ('next_due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('last_seen_date', models.DateField(blank=True, null=True)),
                ('first_seen_date', models.DateField(blank=True, null=True)),
                ('occurrence_count', models.PositiveIntegerField(default=0)),
                ('review_state', models.CharField(choices=[('candidate', 'Detected — awaiting your review'), ('confirmed', 'Confirmed by you'), ('ignored', 'Not a real obligation')], db_index=True, default='candidate', max_length=12)),
                ('source', models.CharField(choices=[('detected', 'Detected by WLJ'), ('user', 'You created it')], default='detected', max_length=12)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=8)),
                ('detector_version', models.CharField(blank=True, default='', max_length=16)),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='How the detector reached this: occurrence dates, gap statistics, amount spread. Kept so a proposal can be argued with.')),
                ('note', models.TextField(blank=True, default='')),
                ('account', models.ForeignKey(blank=True, help_text='Which account it is paid from or into.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring', to='finance.financialaccount')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring', to='finance.transactioncategory')),
                ('liability', models.ForeignKey(blank=True, help_text='For a debt payment: the liability being serviced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_debt_payments', to='finance.financialaccount')),
                ('merged_into', models.ForeignKey(blank=True, help_text='Set when the user merges two series; the record is kept, not deleted, so the history it explains does not disappear.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='finance.recurringseries')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Recurring series',
                'ordering': ['-confidence', 'name'],
            },
            bases=(apps.core.current_context.NarratableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurring_series',
            field=models.ForeignKey(blank=True, help_text='The repeating series this row is an occurrence of.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.recurringseries'),
        ),
        migrations.AddIndex(
            model_name='recurringseries',
            index=models.Index(fields=['user', 'review_state', 'status'], name='finance_rec_user_id_5872de_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringseries',
            index=models.Index(fields=['user', 'kind', 'status'], name='finance_rec_user_id_3bb0cb_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringseries',
            index=models.Index(fields=['user', 'next_due_date'], name='finance_rec_user_id_4a62e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurringseries',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active'), models.Q(('payee', ''), _negated=True)), fields=('user', 'payee', 'frequency', 'kind'), name='uniq_active_recurring_per_payee_freq_kind'),
        ),
    ]
