# Generated by Django 4.2.27 on 2026-08-31 01:18

import apps.core.current_context
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0038_recurringseries_transaction_recurring_series_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('apr', models.DecimalField(blank=True, decimal_places=3, help_text='Annual percentage rate, e.g. 6.750', max_digits=6, null=True)),
                ('interest_method', models.CharField(choices=[('simple', 'Simple interest'), ('amortised', 'Amortised (a fixed payment schedule)'), ('revolving', 'Revolving (a credit line)'), ('unknown', 'Not known')], default='unknown', max_length=16)),
                ('minimum_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contractual_payment', models.DecimalField(blank=True, decimal_places=2, help_text='The scheduled payment, where that differs from the minimum.', max_digits=12, null=True)),
                ('due_day', models.PositiveSmallIntegerField(blank=True, help_text='Day of the month the payment is due.', null=True)),
                ('original_principal', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('origination_date', models.DateField(blank=True, null=True)),
                ('remaining_term_months', models.PositiveIntegerField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('payoff_amount', models.DecimalField(blank=True, decimal_places=2, help_text='A quoted payoff figure. It expires — see payoff_quote_expires.', max_digits=14, null=True)),
                ('payoff_quote_expires', models.DateField(blank=True, null=True)),
                ('promotional_apr', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('promotional_apr_ends', models.DateField(blank=True, null=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=2, help_text='Recurring servicing or annual fees.', max_digits=10, null=True)),
                ('prepayment_penalty', models.CharField(blank=True, default='', max_length=200)),
                ('note', models.TextField(blank=True, default='')),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('calculation_version', models.CharField(blank=True, default='', max_length=16)),
                ('account', models.OneToOneField(help_text='The liability these terms describe. The account may be imported or created by hand — both are first-class.', on_delete=django.db.models.deletion.CASCADE, related_name='loan_terms', to='finance.financialaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan terms',
                'verbose_name_plural': 'Loan terms',
            },
            bases=(apps.core.current_context.NarratableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LoanTermsChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('field', models.CharField(max_length=40)),
                ('old_value', models.CharField(blank=True, default='', max_length=120)),
                ('new_value', models.CharField(blank=True, default='', max_length=120)),
                ('source', models.CharField(choices=[('provider', 'Imported from the institution'), ('statement', 'Read from a statement and confirmed by you'), ('user', 'Entered by you'), ('unavailable', 'Not available')], default='user', max_length=16)),
                ('as_of', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='finance.loanterms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan terms change',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'terms', '-created_at'], name='finance_loa_user_id_f05b40_idx')],
            },
            bases=(apps.core.current_context.NarratableMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='loanterms',
            index=models.Index(fields=['user', 'status'], name='finance_loa_user_id_78f76f_idx'),
        ),
    ]
