# Generated by Django 4.2.27 on 2026-08-31 01:22

import apps.core.current_context
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0039_loanterms_loantermschange_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('kind', models.CharField(choices=[('cancel', 'Cancel it'), ('downgrade', 'Move to a cheaper tier'), ('negotiate', 'Ask for a better price'), ('reduce_frequency', 'Buy it less often'), ('reduce_category', 'Spend less in this category'), ('move_to_entity', 'Charge it to the entity that benefits'), ('eliminate_duplicate', 'You are paying for this twice'), ('correct_classification', 'This looks miscategorised')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('rationale', models.TextField(blank=True, default='')),
                ('payee', models.CharField(blank=True, default='', max_length=200)),
                ('projected_monthly_savings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='What WLJ calculates could be saved. NOT what has been saved.', max_digits=12)),
                ('realized_monthly_savings', models.DecimalField(blank=True, decimal_places=2, help_text='What actually happened, observed from transactions after the fact.', max_digits=12, null=True)),
                ('observed_from', models.DateField(blank=True, null=True)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=8)),
                ('effort', models.CharField(choices=[('low', 'A few minutes'), ('medium', 'A phone call'), ('high', 'A real project')], default='medium', max_length=8)),
                ('disruption', models.CharField(choices=[('low', 'Nobody notices'), ('medium', 'Some change'), ('high', 'A real sacrifice')], default='medium', max_length=8)),
                ('decision', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('rejected', 'Not for me'), ('snoozed', 'Later'), ('done', 'Done')], db_index=True, default='proposed', max_length=12)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, default='', max_length=300)),
                ('snooze_until', models.DateField(blank=True, null=True)),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Transaction ids and the calculation behind the figure. An opportunity that cannot show its working is a guess.')),
                ('engine_version', models.CharField(blank=True, default='', max_length=16)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='finance.transactioncategory')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='finance.recurringseries')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Savings opportunities',
                'ordering': ['-projected_monthly_savings'],
                'indexes': [models.Index(fields=['user', 'decision', 'status'], name='finance_sav_user_id_f20c38_idx'), models.Index(fields=['user', '-projected_monthly_savings'], name='finance_sav_user_id_555fe6_idx')],
            },
            bases=(apps.core.current_context.NarratableMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='savingsopportunity',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active'), ('series__isnull', False)), fields=('user', 'kind', 'series'), name='uniq_active_opportunity_per_series_kind'),
        ),
    ]
