# Generated by Django 4.2.27 on 2026-08-31 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0040_savingsopportunity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringseries',
            name='declared_template',
            field=models.ForeignKey(blank=True, help_text='A user-written RecurringTransaction template describing the same commitment. Cross-referenced so one subscription is not presented as two things.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observed_series', to='finance.recurringtransaction'),
        ),
    ]
