# Generated by Django 4.2.27 on 2026-08-31 11:12

import apps.core.current_context
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0041_recurringseries_declared_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetWorthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('as_of', models.DateField(db_index=True)),
                ('basis', models.CharField(choices=[('observed', 'Observed — the values WLJ held that day'), ('reconstructed', 'Reconstructed from records, and labelled as such')], default='observed', max_length=16)),
                ('cash_and_financial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('investments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('tangible_assets', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('liabilities', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('net_worth', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('unvalued_asset_count', models.PositiveIntegerField(default=0)),
                ('excluded_asset_count', models.PositiveIntegerField(default=0)),
                ('stale_valuation_count', models.PositiveIntegerField(default=0)),
                ('calculation_version', models.CharField(blank=True, default='', max_length=16)),
                ('composition', models.JSONField(blank=True, default=dict, help_text='Per-account and per-asset contributions, so every total can be opened rather than trusted.')),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Net worth snapshot',
                'ordering': ['-as_of'],
                'indexes': [models.Index(fields=['user', '-as_of'], name='finance_net_user_id_5de1a8_idx')],
            },
            bases=(apps.core.current_context.NarratableMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='networthsnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'as_of'), name='uniq_active_networth_snapshot_per_day'),
        ),
    ]
