# Generated by Django 4.2.27 on 2026-08-31 11:17

import apps.core.current_context
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0042_networthsnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('decision', models.CharField(help_text='The economic role applied, or `leave_uncertain` when the user deliberately declined to decide.', max_length=32)),
                ('group_key', models.CharField(blank=True, default='', max_length=200)),
                ('group_label', models.CharField(blank=True, default='', max_length=200)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('previous_state', models.JSONField(blank=True, default=list)),
                ('batch_status', models.CharField(choices=[('applied', 'Applied'), ('undone', 'Undone')], db_index=True, default='applied', max_length=12)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('created_rule', models.ForeignKey(blank=True, help_text='Set when the user turned this decision into an enduring rule.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_batches', to='finance.spendingclassification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Review batches',
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['user', '-applied_at'], name='finance_rev_user_id_7c30aa_idx')],
            },
            bases=(apps.core.current_context.NarratableMixin, models.Model),
        ),
    ]
