# Generated by Django 4.2.27 on 2026-08-31 11:24

import apps.core.current_context
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0043_reviewbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('reserve', 'Reserve floor — do not go below this'), ('sinking_fund', 'Sinking fund — building towards a known cost')], db_index=True, default='sinking_fund', max_length=16)),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, help_text='What it should reach. Null means you have not decided, and WLJ will not decide for you.', max_digits=14, null=True)),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('monthly_contribution', models.DecimalField(blank=True, decimal_places=2, help_text='What you intend to put in each month. Committed cash in a forecast.', max_digits=12, null=True)),
                ('due_date', models.DateField(blank=True, help_text='When the cost lands, for a sinking fund.', null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('account', models.ForeignKey(blank=True, help_text='Where it is held, when it is held somewhere specific.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserves', to='finance.financialaccount')),
                ('goal', models.ForeignKey(blank=True, help_text='An existing goal this reserve represents — the Emergency Fund goal is the usual case. Linked, never duplicated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserves', to='finance.financialgoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash reserve',
                'ordering': ['kind', 'name'],
                'indexes': [models.Index(fields=['user', 'kind', 'status'], name='finance_cas_user_id_05012c_idx')],
            },
            bases=(apps.core.current_context.NarratableMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='cashreserve',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'name'), name='uniq_active_reserve_per_name'),
        ),
    ]
