# Generated by Django 4.2.27 on 2026-08-31 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0044_cashreserve_cashreserve_uniq_active_reserve_per_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsopportunity',
            name='abandoned_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='savingsopportunity',
            name='observation_days',
            field=models.PositiveIntegerField(default=60, help_text='How long WLJ watches before it will say whether it worked.'),
        ),
        migrations.AddField(
            model_name='savingsopportunity',
            name='outcome',
            field=models.CharField(choices=[('pending', 'Not yet looked at'), ('too_early', 'Too early to tell'), ('achieved', 'Achieved'), ('partially_achieved', 'Partly achieved'), ('not_achieved', 'Did not happen'), ('unmeasurable', 'Cannot be measured from transactions')], db_index=True, default='pending', max_length=24),
        ),
        migrations.AddField(
            model_name='savingsopportunity',
            name='outcome_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingsopportunity',
            name='outcome_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='savingsopportunity',
            name='started_on',
            field=models.DateField(blank=True, help_text='When the change was supposed to take effect. Measurement starts here.', null=True),
        ),
        migrations.AddField(
            model_name='savingsopportunity',
            name='target_debt',
            field=models.ForeignKey(blank=True, help_text='Where the freed money is meant to go. A direction, never a payment — WLJ moves no money.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_savings', to='finance.financialaccount'),
        ),
        migrations.AddField(
            model_name='savingsopportunity',
            name='target_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_savings', to='finance.financialgoal'),
        ),
        migrations.AlterField(
            model_name='savingsopportunity',
            name='decision',
            field=models.CharField(choices=[('proposed', 'Suggested'), ('accepted', 'Accepted'), ('rejected', 'Not for me'), ('snoozed', 'Later'), ('planned', 'In the plan'), ('done', 'I have done this'), ('abandoned', 'Gave up on it')], db_index=True, default='proposed', max_length=12),
        ),
    ]
