# Generated by Django 4.2.27 on 2026-08-31 11:42

import apps.core.current_context
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0045_savingsopportunity_abandoned_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoffScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('strategy', models.CharField(default='avalanche', help_text='minimum, snowball, avalanche or custom.', max_length=16)),
                ('extra_monthly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('lump_sum', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('custom_order', models.JSONField(blank=True, default=list, help_text='Debt keys in the order the user chose, for the custom strategy.')),
                ('plan_state', models.CharField(choices=[('draft', 'Draft — comparing options'), ('active_plan', 'The plan I am following'), ('paused', 'Paused'), ('archived_plan', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('activated_on', models.DateField(blank=True, null=True)),
                ('projected', models.JSONField(blank=True, default=dict)),
                ('calculation_version', models.CharField(blank=True, default='', max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payoff scenario',
                'ordering': ['-activated_on', 'name'],
                'indexes': [models.Index(fields=['user', 'plan_state', 'status'], name='finance_pay_user_id_cf553c_idx')],
            },
            bases=(apps.core.current_context.NarratableMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='payoffscenario',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'name'), name='uniq_active_payoff_scenario_name'),
        ),
        migrations.AddConstraint(
            model_name='payoffscenario',
            constraint=models.UniqueConstraint(condition=models.Q(('plan_state', 'active_plan'), ('status', 'active')), fields=('user',), name='uniq_one_active_payoff_plan'),
        ),
    ]
