# Generated by Django 4.2.27 on 2026-03-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_add_team_record_and_game_pitchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='record_season',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
