# Generated by Django 4.2.27 on 2026-03-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_add_team_record_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameevent',
            name='game_note',
            field=models.CharField(blank=True, default='', help_text="Game context from ESPN notes (e.g. 'Sweet 16', 'Wild Card')", max_length=200),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='game_type',
            field=models.CharField(choices=[('regular', 'Regular Season'), ('postseason', 'Postseason'), ('tournament', 'Tournament')], default='regular', max_length=20),
        ),
    ]
