# Generated by Django 4.2.27 on 2026-05-24 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyArc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('era_label', models.CharField(blank=True, max_length=80)),
                ('order', models.PositiveIntegerField()),
                ('opening_note', models.TextField()),
                ('closing_note', models.TextField()),
                ('estimated_days', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False, help_text="When True, the arc is available to users. The loader's sequence/gap validation (no missing day_numbers from 1 to N) runs only when is_active=True, so an arc may be authored incrementally while inactive.")),
            ],
            options={
                'verbose_name': 'journey arc',
                'verbose_name_plural': 'journey arcs',
                'ordering': ['journey_path', 'order'],
            },
        ),
        migrations.CreateModel(
            name='JourneyDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_number', models.PositiveIntegerField()),
                ('scripture_refs', models.JSONField(help_text="List of reference strings, e.g., ['Leviticus 1:1-17'].")),
                ('scripture_content', models.JSONField(help_text="Translation + ordered verse blocks. Shape: {'translation': 'WEB', 'blocks': [{ref, verse, text, red_letter}, ...]}")),
                ('context_before', models.TextField(help_text='Plain-English orientation before the reading.')),
                ('plain_english_simple', models.TextField(help_text='Tier 1 — approachable, accessible commentary.')),
                ('plain_english_standard', models.TextField(help_text='Tier 2 — default reading depth.')),
                ('plain_english_deeper', models.TextField(help_text='Tier 3 — historical, linguistic, cross-references.')),
                ('key_insight', models.CharField(help_text='One-sentence takeaway. Loader validates ≤ 200 chars.', max_length=200)),
                ('reflection_prompt', models.TextField(help_text='Single personal question — not guilt-inducing.')),
                ('application_action', models.CharField(help_text='One small concrete action. Loader validates ≤ 280 chars.', max_length=280)),
                ('confusion_topics', models.JSONField(default=list, help_text='List of {topic, plain_english_answer} objects. Loader validates ≥ 3 entries per day.')),
                ('retention_anchor', models.TextField(help_text='Connection to story arc (yesterday → today → tomorrow). Required for chronological arcs.')),
                ('arc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='journey.journeyarc')),
            ],
            options={
                'verbose_name': 'journey day',
                'verbose_name_plural': 'journey days',
                'ordering': ['arc', 'day_number'],
                'unique_together': {('arc', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='JourneyPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('narrative_overview', models.TextField()),
                ('cover_image_url', models.URLField(blank=True)),
                ('estimated_weeks', models.PositiveIntegerField(default=0)),
                ('difficulty_default', models.CharField(choices=[('simple', 'Simple'), ('standard', 'Standard'), ('deeper', 'Deeper')], default='standard', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='When True, the path is available to users. Defaults False so newly loaded paths require explicit publish.')),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'journey path',
                'verbose_name_plural': 'journey paths',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('current_day_number', models.PositiveIntegerField(default=1)),
                ('journey_status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('preferred_difficulty', models.CharField(choices=[('simple', 'Simple'), ('standard', 'Standard'), ('deeper', 'Deeper')], default='standard', max_length=20)),
                ('reminder_time', models.TimeField(blank=True, help_text='Off by default; user opts in.', null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_engaged_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('momentum_score', models.FloatField(default=1.0)),
                ('current_arc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_user_journeys', to='journey.journeyarc')),
                ('journey_path', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_journeys', to='journey.journeypath')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user journey',
                'verbose_name_plural': 'user journeys',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='journeyarc',
            name='journey_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcs', to='journey.journeypath'),
        ),
        migrations.CreateModel(
            name='UserJourneyDayProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reflection_notes', models.TextField(blank=True)),
                ('application_committed', models.BooleanField(default=False)),
                ('difficulty_at_completion', models.CharField(blank=True, choices=[('simple', 'Simple'), ('standard', 'Standard'), ('deeper', 'Deeper')], help_text='Snapshot of difficulty tier at the moment the day was marked complete.', max_length=20)),
                ('journey_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='journey.journeyday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('user_journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_progress', to='journey.userjourney')),
            ],
            options={
                'verbose_name': 'user journey day progress',
                'verbose_name_plural': 'user journey day progress records',
                'ordering': ['user_journey', 'journey_day'],
                'unique_together': {('user_journey', 'journey_day')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='journeyarc',
            unique_together={('journey_path', 'slug'), ('journey_path', 'order')},
        ),
    ]
