# Generated by Django 4.2.27 on 2026-05-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjourney',
            name='last_visited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
