# ==============================================================================
# File: apps/faith/management/commands/load_noah_plan.py
# Project: Whole Life Journey - Django 5.x Personal Wellness/Journaling App
# Description: Management command to create "Noah: Righteous in His Generation" reading plan
# Owner: Danny Jenkins (admin@wholelifejourney.com)
# Created: 2026-01-20
# Last Updated: 2026-01-20
# ==============================================================================
"""
Management command to create the Noah reading plan.

Creates a 7-day reading plan covering Noah's story:
- Day 1: Genesis 5:28-6:8 - A World Gone Wrong
- Day 2: Genesis 6:9-22 - Building by Faith
- Day 3: Genesis 7:1-24 - The Flood Begins
- Day 4: Genesis 8:1-22 - The Waters Recede
- Day 5: Genesis 9:1-17 - God's Covenant with Noah
- Day 6: Genesis 9:18-10:32 - After the Flood
- Day 7: Hebrews 11:7, 1 Peter 3:18-22, 2 Peter 2:4-9 - Noah in the New Testament

Each day includes:
- Context summary (who, when, setting)
- Commentary at 3 difficulty levels (Beginner, Intermediate, Advanced)
- Reflection prompts

Biblical accuracy verified. Non-denominational, Bible-based content.
"""

from django.core.management.base import BaseCommand
from apps.faith.models import ReadingPlanTemplate, ReadingPlanDay


class Command(BaseCommand):
    help = "Load Noah: Righteous in His Generation reading plan"

    def handle(self, *args, **options):
        self.stdout.write("Loading Noah reading plan...")

        template = self._create_noah_plan()
        self.stdout.write(f"  Created: {template.title} ({template.duration_days} days)")

        self.stdout.write(self.style.SUCCESS("Noah reading plan loaded successfully!"))

    def _create_noah_plan(self):
        """Create Noah: Righteous in His Generation reading plan."""
        template, created = ReadingPlanTemplate.objects.get_or_create(
            slug="noah-righteous-generation",
            defaults={
                "title": "Noah: Righteous in His Generation",
                "description": "A 7-day journey through the story of Noah, one of the most dramatic accounts in Scripture. From a world corrupted by violence to a family preserved through faith, Noah's story reveals God's judgment on sin, His mercy toward the righteous, and His covenant faithfulness. This study explores the flood narrative while connecting it to New Testament themes of salvation, baptism, and patient endurance.",
                "category": "book",
                "difficulty": "beginner",
                "duration_days": 7,
                "topics": ["noah", "flood", "ark", "covenant", "righteousness", "judgment", "salvation", "faith"],
                "series": "People of the Bible",
                "series_order": 3,
                "allowed_emails": [],
                "is_active": True,
                "is_featured": True,
            }
        )

        if not created:
            # Plan exists, skip day creation
            return template

        # Noah reading plan days
        days = [
            {
                "day_number": 1,
                "title": "A World Gone Wrong",
                "scripture_references": ["Genesis 5:28-32", "Genesis 6:1-8"],
                "context_summary": "Genesis 5 concludes the genealogy from Adam through Seth to Noah, spanning roughly 1,000-1,500 years (the exact timeframe depends on how one interprets the genealogical numbers). By the time of Noah, humanity has multiplied but so has wickedness. The world that began 'very good' in Genesis 1 has become so corrupted that God expresses grief over His creation. Yet in this dark time, one man finds favor with God.",
                "commentary_beginner": "Noah's father Lamech named him hoping he would bring relief from the curse on the ground (Genesis 3:17-19). The genealogy shows people living extraordinarily long lives—Methuselah lived 969 years! But long life didn't mean righteous life. By Noah's time, wickedness had spread everywhere. The mysterious passage about 'sons of God' and 'daughters of men' (6:1-4) has puzzled readers for centuries, but the main point is clear: humanity was corrupt. Every thought of the human heart was 'only evil all the time' (6:5). This grieved God deeply. The Hebrew word for 'grieved' describes emotional pain—God was hurt by what humanity had become. He decided to start over. But Noah was different. He 'found favor' (grace) in God's eyes—the first time this word appears in the Bible. Even in a totally corrupt world, one man walked faithfully with God.",
                "commentary_intermediate": "The genealogy of chapter 5 uses a repeated formula emphasizing both longevity and mortality: 'and then he died.' This refrain echoes the curse of Genesis 3. Lamech's naming of Noah (from a root meaning 'rest' or 'comfort') expressed hope for relief from the ground's curse. The 'sons of God' passage (6:1-4) has three main interpretations: (1) fallen angels who took human wives, (2) the godly line of Seth intermarrying with Cain's ungodly line, or (3) tyrannical rulers claiming divine status. The Nephilim ('fallen ones' or 'giants') add to the mystery. Regardless of interpretation, the result is clear: corruption and violence filled the earth. God's grief (6:6) uses the Hebrew nacham—the same word for 'repent' or 'relent'—showing God's genuine emotional response to sin. The 120-year period (6:3) likely refers to the remaining time before the flood rather than a new human lifespan limit. 'Finding grace' (chen, 6:8) introduces a key biblical concept: unmerited divine favor that becomes the foundation for Noah's salvation.",
                "commentary_advanced": "The Sethite genealogy (chapter 5) contrasts with Cain's line (4:17-24) in its structure and theological purpose. While Cain's line emphasizes cultural achievement and escalating violence (Lamech's song of vengeance, 4:23-24), Seth's line traces the faithful remnant. The extreme lifespans have generated various interpretations: literal years, different year-counting systems, or symbolic/literary conventions common in ancient Near Eastern king lists. The 'sons of God' (bene elohim) terminology appears elsewhere for divine beings (Job 1:6, 2:1, 38:7; Psalm 29:1), supporting the angelic interpretation held by many early Jewish and Christian interpreters. However, the broader context emphasizes human corruption, favoring the Sethite interpretation for some scholars. The term Nephilim reappears in Numbers 13:33, where Israelite spies describe Canaan's inhabitants. God's self-reflection in 6:6-7 employs anthropomorphic language that Jewish interpreters have long wrestled with—how can the unchanging God 'regret'? The text depicts divine pathos without implying divine imperfection. The word 'favor' (chen) initiates a salvation-by-grace theme that runs through Scripture: Noah doesn't earn salvation but receives it as gift, setting precedent for Abraham, Israel, and ultimately believers in Christ.",
                "reflection_prompt": "In a world where 'every inclination of the thoughts of the human heart was only evil all the time,' Noah stood out as righteous. What does it mean to be faithful when everyone around you is going the opposite direction? How does knowing that God grieves over sin affect your understanding of Him?",
            },
            {
                "day_number": 2,
                "title": "Building by Faith",
                "scripture_references": ["Genesis 6:9-22"],
                "context_summary": "God reveals His plan to Noah: a catastrophic flood will destroy all life on earth, but Noah and his family will be saved through an ark. The detailed instructions for the ark's construction demonstrate God's care in providing a way of escape. Noah's obedience, building for decades without seeing rain, becomes a model of faith that the New Testament celebrates.",
                "commentary_beginner": "Noah was 'a righteous man, blameless among the people of his time, and he walked faithfully with God' (6:9). Like Enoch before him (5:24), Noah had a close relationship with God. While the world was filled with violence, Noah lived differently. God told Noah His plan: He would send a flood to destroy all life because of the earth's corruption. But God would establish a covenant with Noah—a solemn promise. God gave Noah exact instructions: build an ark (a large box-shaped boat) 450 feet long, 75 feet wide, and 45 feet high (using the standard 18-inch cubit). It would have three decks, one door, and a roof. Noah was to bring his wife, his three sons (Shem, Ham, and Japheth), their wives, and pairs of every kind of animal—seven pairs of 'clean' animals and birds, one pair of others. He was also to store food for everyone. The chapter ends simply: 'Noah did everything just as God commanded him' (6:22). Imagine building this massive boat with no power tools, possibly far from water, while neighbors mocked. But Noah obeyed.",
                "commentary_intermediate": "The phrase 'These are the generations of Noah' (6:9) marks a new section in Genesis's structure (toledot formula). Noah is described with three terms: righteous (tsaddiq—legally and morally upright), blameless (tamim—complete, whole, having integrity), and walking with God (the same phrase used of Enoch). 'In his generation' acknowledges the contrast with his contemporaries without diminishing his righteousness. The ark's dimensions create a ratio of 30:5:3 (length:width:height), proportions that modern naval architects recognize as remarkably stable for a vessel meant to float rather than sail. The Hebrew word for ark (tebah) appears only here and in Exodus 2:3 (Moses's basket)—both vessels of salvation floating on water. God's covenant announcement (6:18) is the first explicit covenant mention in Scripture, though the concept appears earlier. The 'clean' and 'unclean' animal distinction (7:2) anticipates Levitical law, suggesting either Mosaic authorship or an earlier tradition. The detail about Noah's sons being married (6:18) indicates Noah was likely 500+ years old when building began (cf. 5:32)—decades of faithful construction.",
                "commentary_advanced": "The literary structure of the flood narrative exhibits remarkable chiastic (symmetrical) patterning, with the apex at 8:1 ('God remembered Noah'). The ark's specifications using 'cubit' (ammah) measurements reflect ancient Near Eastern building conventions. The 30:5:3 ratio produces exceptional stability; hydrodynamic studies confirm such proportions would right themselves even in extreme conditions. Comparison with Mesopotamian flood narratives (Gilgamesh, Atrahasis) reveals both similarities (divine warning, ark construction, animal preservation) and profound differences (monotheism, ethical cause for flood, covenant resolution). The Babylonian vessel is a cube—nautically absurd—while Genesis describes a practical design. The gopher wood (6:14) remains unidentified; the term appears only here. 'Pitch' (kopher) shares a root with 'atonement' (kippur), perhaps foreshadowing substitutionary covering. The phrase 'male and female' (6:19) echoes the creation account (1:27), emphasizing that the ark preserves the created order. God Himself will shut the door (7:16), assuming responsibility for those inside and outside. Noah's silent obedience throughout (he doesn't speak until 9:25) contrasts with Abraham's intercession, Moses's objections, or Jonah's flight—different faithful responses to divine commission.",
                "reflection_prompt": "Noah spent decades building an ark when there was no visible evidence of coming disaster. He trusted God's word over his circumstances. What has God asked you to do that doesn't make sense to the world around you? What helps you persevere when you can't see the outcome?",
            },
            {
                "day_number": 3,
                "title": "The Flood Begins",
                "scripture_references": ["Genesis 7:1-24"],
                "context_summary": "After years of preparation, the day arrives. God invites Noah's family into the ark, the animals enter as God directs, and the Lord Himself shuts the door. Then the catastrophe begins—springs of the great deep burst forth and the heavens open. For forty days and nights, rain falls as waters rise, eventually covering even the highest mountains. Every living thing outside the ark perishes.",
                "commentary_beginner": "God told Noah, 'Go into the ark, you and your whole family, because I have found you righteous in this generation' (7:1). Notice: God found Noah righteous—it was God's assessment, not Noah's claim. Take seven pairs of every clean animal and one pair of every unclean animal, God said, and in seven days the rain will begin. Noah was 600 years old when the flood came. On the seventeenth day of the second month, 'all the springs of the great deep burst forth, and the floodgates of the heavens were opened' (7:11). This wasn't just rain—it was as if creation itself was being undone. Water came from below (underground springs) and above (torrential rain). The waters rose for 40 days, lifting the ark high above the earth. Eventually the water covered the mountains by more than 20 feet. Everything with the breath of life died—people, animals, birds, everything on dry ground. 'Only Noah was left, and those with him in the ark' (7:23). But there's a beautiful detail: 'The LORD shut him in' (7:16). God Himself closed the door, protecting those inside.",
                "commentary_intermediate": "God's invitation 'Come into the ark' (7:1, some translations) suggests God's presence within—Noah enters where God is. The distinction between 'clean' and 'unclean' animals (seven pairs vs. one pair) provides for post-flood sacrifice (8:20) and dietary needs while preserving species. The precise dating (7:11—600th year, 2nd month, 17th day) grounds the narrative in historical specificity, though interpreting ancient calendars remains debated. The 'fountains of the great deep' (tehom rabbah) and 'windows of heaven' invoke creation language (1:2, 6-7)—the flood is creation in reverse, the separation of waters being undone. The 40-day period becomes significant throughout Scripture: Moses on Sinai, Elijah's journey, Jesus's temptation. The waters covering mountains by 15 cubits (7:20) ensures complete submersion and perhaps relates to the ark's draft. God shutting the door (7:16) is profoundly personal—He doesn't delegate this act. Those inside are secured by divine action; those outside are excluded by the same. The chiastic structure of the flood narrative places emphasis on God 'remembering' Noah (8:1) at the center, not the destruction.",
                "commentary_advanced": "The flood account employs deliberate creation-reversal imagery. The 'deep' (tehom, 7:11) recalls the primordial waters of 1:2 before divine ordering. The 'windows of heaven' (arubboth hashamayim) suggest the raqia (firmament/expanse) of 1:6-8 being breached. Bird, cattle, creature, and 'everything that creeps' (7:21) echo the creation categories of chapter 1, now being destroyed. The phrase 'all flesh' (kol-basar) appears repeatedly, emphasizing comprehensive judgment. The duration formulae create complex chronology: 40 days of rain, 150 days of prevailing waters, 150 days of receding, specific dates for landing and emergence—totaling approximately one year. Ancient Near Eastern parallels describe floods lasting 7 days (Gilgamesh) or varying periods; Genesis's extended timeframe emphasizes cosmic scope. The statement that waters prevailed 'exceedingly' (me'od me'od, 7:19) uses emphatic doubling. God 'shutting' (sagar) the door employs a term used elsewhere for God closing and opening (e.g., 1 Samuel 1:5-6), emphasizing divine sovereignty over who enters salvation. The ark as microcosm preserves the created order through judgment, anticipating biblical patterns of remnant preservation through catastrophe.",
                "reflection_prompt": "When God shut the door, it was both protection for those inside and exclusion for those outside. The opportunity to enter had passed. How does this image affect your sense of urgency about responding to God's invitation? What does it mean that God Himself secured those who trusted Him?",
            },
            {
                "day_number": 4,
                "title": "The Waters Recede",
                "scripture_references": ["Genesis 8:1-22"],
                "context_summary": "After months of floating on a world covered by water, hope begins to emerge. God 'remembers' Noah—not that He had forgotten, but He now acts on Noah's behalf. The waters recede, the ark comes to rest on the mountains of Ararat, and Noah tests the conditions by sending out birds. Finally, after more than a year in the ark, God commands Noah to come out. Noah's first act is worship.",
                "commentary_beginner": "The most important verse may be the first: 'But God remembered Noah' (8:1). God hadn't forgotten—He never does. This means God turned His attention to act on Noah's behalf. God sent a wind over the earth, the springs and rain stopped, and the waters began to recede. After 150 days, the ark came to rest on the mountains of Ararat (in modern-day Turkey). About two and a half months later, mountaintops became visible. Noah opened the window and sent out a raven, which kept flying back and forth. Then he sent a dove, but it returned because there was nowhere to land. After seven days, he sent the dove again, and this time it returned with a fresh olive leaf—proof that plants were growing again! Seven days later, the dove didn't return at all. Noah removed the ark's covering and saw dry ground. But he waited for God's command before leaving. When God said 'Come out,' Noah, his family, and all the animals left the ark. Noah's first act was to build an altar and sacrifice some of the clean animals to the LORD. God was pleased with the sacrifice and made a promise: 'Never again will I curse the ground because of humans... never again will I destroy all living creatures' (8:21).",
                "commentary_intermediate": "The Hebrew word 'remembered' (zakar, 8:1) is covenantal language—God acting on behalf of those with whom He has relationship (cf. Exodus 2:24, when God 'remembered' His covenant with Abraham and delivered Israel). The 'wind' (ruach) God sent recalls the Spirit (same word) hovering over waters in 1:2—recreation imagery. The ark resting on 'the mountains of Ararat' indicates a region (in modern Armenia/Turkey), not a specific peak; later tradition identified Mount Ararat specifically. The bird-sending sequence—raven then dove—parallels ancient Near Eastern accounts (Gilgamesh), though with different results and meaning. The raven, an unclean scavenger, would survive on floating carrion; the dove needed clean landing. The olive leaf (8:11) symbolizes returning life and peace, imagery that persists today. Noah waits for divine permission to exit despite seeing dry ground (8:14 vs. 8:15-16)—a model of obedience rather than presumption. The 'pleasing aroma' (8:21) becomes technical terminology for acceptable sacrifice throughout Leviticus. God's promise contains honest anthropology: 'every inclination of the human heart is evil from childhood' (8:21)—the flood didn't cure humanity's sinfulness, but God pledges never to respond this way again.",
                "commentary_advanced": "The structural center of the flood chiasm is 8:1: 'God remembered Noah.' This theological apex transforms the narrative from judgment to restoration. The verb zakar carries covenantal weight—when God 'remembers' Abraham (19:29), Rachel (30:22), Hannah (1 Samuel 1:19), Israel in Egypt (Exodus 2:24), He acts salvifically. The ruach (wind/spirit) and waters evoke creation's first day (1:2), suggesting de-creation now moves toward re-creation. The Ararat location's identification with Urartu (Assyrian records) places the landing in the north—the direction from which subsequent nations spread (chapter 10). The 150-day period's relationship to the preceding 40 days has generated calendrical discussion; some see overlapping periods, others sequential. The raven-dove pairing may represent clean/unclean or death/life symbolism. Noah's altar is the first explicitly mentioned in Scripture. The 'pleasing aroma' (reach nichoach) uses a wordplay on Noah's name—the 'rest' his father hoped for finds expression in God's restful acceptance. The divine self-deliberation (8:21-22) parallels 6:5-7 but reverses the trajectory: acknowledging unchanged human nature yet committing to preservation. The seasonal cycle promise (8:22) establishes the stable natural order presupposed throughout Scripture.",
                "reflection_prompt": "'God remembered Noah'—not that God ever forgot, but He acted on Noah's behalf at the right time. When you're waiting on God in difficult circumstances, how does this truth encourage you? What does Noah's patient obedience (waiting for God's command even when he could see dry ground) teach about trusting God's timing?",
            },
            {
                "day_number": 5,
                "title": "God's Covenant with Noah",
                "scripture_references": ["Genesis 9:1-17"],
                "context_summary": "God blesses Noah and his sons with language echoing the original creation blessing. He establishes the first explicit covenant in Scripture—an unconditional promise never to destroy the earth by flood again. The rainbow becomes the sign of this covenant, a reminder not just for humanity but, remarkably, for God Himself.",
                "commentary_beginner": "God blessed Noah and his sons with words similar to what He told Adam and Eve: 'Be fruitful and increase in number and fill the earth' (9:1; cf. 1:28). A fresh start! But things had changed. Animals would now fear humans, and for the first time, God permitted eating meat (before, Genesis 1:29 suggests a vegetarian diet). However, blood was forbidden—blood represents life, and life belongs to God. God also established a crucial principle: 'Whoever sheds human blood, by humans shall their blood be shed; for in the image of God has God made mankind' (9:6). Human life is sacred because we bear God's image. Then God made a covenant—a solemn, binding promise. He would never again destroy all life by flood. And He gave a sign: the rainbow. 'Whenever I bring clouds over the earth and the rainbow appears in the clouds, I will remember my covenant' (9:14-15). The rainbow wasn't just for humans to remember—God said He would see it and remember! This covenant was unconditional—it didn't depend on human behavior but on God's faithfulness.",
                "commentary_intermediate": "The blessing to Noah (9:1-7) both echoes and modifies the creation mandate. 'Be fruitful and multiply' repeats, but 'rule' becomes 'fear and dread'—the harmonious human-animal relationship is broken. Meat-eating is permitted but blood-eating prohibited, establishing a principle that continues through Levitical law (Leviticus 17:10-14) and into the early church (Acts 15:29). The blood prohibition connects to blood's role as atonement (Leviticus 17:11). The image of God language (9:6) is remarkable—despite the fall, despite the flood, humans still bear God's image, grounding the sanctity of human life. The covenant (berit, 9:9-17) is explicitly stated as being with 'every living creature'—cosmic in scope. It's unilateral and unconditional; God binds Himself regardless of human response. The rainbow (qeshet, literally 'bow' as in weapon) may symbolize God hanging up His war bow, pointing it toward heaven rather than earth—a warrior at rest. God's statement that He will 'remember' the covenant inverts the concept from 8:1; as God remembered Noah to save him, He will remember His promise never to destroy again.",
                "commentary_advanced": "The Noahic covenant establishes what some theologians call 'common grace'—God's commitment to preserve creation and human society despite ongoing sin. The text carefully parallels 1:28-29 while introducing significant modifications: dominion language (radah, kabash) is replaced with fear/dread terminology; plant-eating expands to animal-eating with blood prohibition. The blood-life equation (9:4) establishes a principle (nephesh—life/soul is 'in' the blood) foundational to sacrificial theology. The 'image of God' affirmation (9:6) is theologically significant—the image wasn't erased by fall or flood. The chiastic structure of 9:6 ('sheds blood/by humans...humans/blood shed') emphasizes correspondence between crime and consequence. The covenant employs legal terminology: God 'establishes' (heqim) rather than 'cuts' (karat) the covenant, suggesting confirming something already implicit (6:18). Its scope—'all flesh,' 'every living creature'—is emphatically universal. The rainbow as 'sign' (ot) parallels circumcision (17:11) and Sabbath (Exodus 31:13). God saying He will 'see' and 'remember' employs anthropomorphic language that early Jewish interpreters debated—the Targums often modified such phrases to protect divine transcendence. The covenant's unconditional nature makes it the foundation for all subsequent biblical covenants.",
                "reflection_prompt": "The rainbow covenant was unconditional—God bound Himself to faithfulness regardless of human behavior. He even said the rainbow would remind Him of His promise. What does it mean to you that God's commitment to His creation doesn't depend on your performance? How does this foundational covenant point toward the unconditional grace we find in Christ?",
            },
            {
                "day_number": 6,
                "title": "After the Flood",
                "scripture_references": ["Genesis 9:18-29", "Genesis 10:1-32"],
                "context_summary": "The story takes a troubling turn as Noah plants a vineyard, becomes drunk, and is shamefully exposed by his son Ham. The consequences ripple through subsequent generations. Chapter 10, the 'Table of Nations,' traces Noah's descendants who spread across the earth, fulfilling the command to 'fill the earth.' This genealogy provides the backdrop for all biblical history to follow.",
                "commentary_beginner": "After the flood, Noah became a farmer and planted a vineyard. One day he drank too much wine and lay naked in his tent. His son Ham saw his father's nakedness and told his two brothers outside. But Shem and Japheth took a garment, walked in backward, and covered their father without looking at him. They showed respect while Ham showed disrespect. When Noah woke up and learned what had happened, he pronounced a curse on Ham's son Canaan and blessings on Shem and Japheth. This may seem harsh, but ancient cultures understood that how you treat your parents reveals your character. Ham's disrespect had consequences that extended to his descendants. Noah lived 350 years after the flood and died at 950 years old. Chapter 10 lists Noah's descendants—the 70 nations that spread across the earth. From Japheth came peoples who settled in Europe and western Asia. From Ham came peoples of Africa and Canaan. From Shem came the Semitic peoples, including eventually Abraham and the Israelites. Every human on earth descends from Noah's family.",
                "commentary_intermediate": "The vineyard incident reveals that the flood didn't change human nature. Noah, the righteous man, becomes drunk—the first mention of wine in Scripture. Ham 'saw' (ra'ah) his father's nakedness, and while interpretive debate continues about whether this implies additional offense, the Hebrew text focuses on the contrast between Ham's response and his brothers'. Shem and Japheth's backward approach with the garment shows deliberate effort to preserve their father's dignity. Noah's curse falls on Canaan (Ham's son) rather than Ham directly, which has generated much discussion. One explanation: the curse relates to Canaan's descendants (the Canaanites) whose eventual displacement by Israel's conquest is being anticipated. This passage has been tragically misused to justify racism; such interpretations violate the text's meaning and biblical teaching on human dignity. The Table of Nations (chapter 10) is unique in ancient literature—no other culture traced all humanity to a common origin. The pattern of 70 nations (some count 72) may be symbolic of completeness. The Shemite line is listed last to create transition toward Abraham's story.",
                "commentary_advanced": "The Ham incident has generated extensive interpretive history. The phrase 'saw the nakedness of his father' (9:22) may be idiom for something more serious (cf. Leviticus 18:6-18, where 'uncovering nakedness' means sexual violation), though the text's restraint makes certainty impossible. Some scholars suggest Ham's offense was voyeurism and mockery; others see castration or incest. The contrast with Shem and Japheth's respectful covering emphasizes honor versus shame. The curse on Canaan rather than Ham may reflect: (1) ancient concepts of children embodying parental character, (2) prophetic anticipation of Israel-Canaan relations, or (3) textual corruption. The phrase 'servant of servants' (ebed abadim, 9:25) is superlative—lowest of servants. The blessings on Shem and Japheth have messianic implications: 'Blessed be the LORD, the God of Shem' points toward Shem's line bearing special divine relationship (Abraham, Israel, Christ). The Table of Nations employs varied genealogical formulae reflecting sources and literary purposes. Its 70 nations symbolize world completeness (cf. 70 Israelites entering Egypt, Genesis 46:27; 70 disciples sent out, Luke 10:1). The phrase 'each with its own language' (10:5, 20, 31) anticipates Babel (chapter 11). Peoples are traced geographically (Japheth north/west, Ham south, Shem east) while remaining theologically ordered.",
                "reflection_prompt": "Even Noah, called righteous, failed after the flood. The flood didn't cure humanity's sin problem. How does this honest portrayal of biblical heroes encourage you about God's grace toward imperfect people? What does it teach about the need for something more than judgment to transform human hearts?",
            },
            {
                "day_number": 7,
                "title": "Noah in the New Testament",
                "scripture_references": ["Hebrews 11:7", "1 Peter 3:18-22", "2 Peter 2:4-9", "Matthew 24:37-39"],
                "context_summary": "The New Testament writers return to Noah's story repeatedly, finding in it lessons about faith, salvation, and preparedness for judgment. Noah becomes an example of faith that acts on God's word, and the ark becomes a picture of salvation through Christ. The flood itself becomes a pattern for both baptism and final judgment.",
                "commentary_beginner": "The New Testament celebrates Noah as a hero of faith. Hebrews 11:7 says, 'By faith Noah, when warned about things not yet seen, in holy fear built an ark to save his family.' Noah believed God's warning about an invisible, unprecedented flood and acted on it. His faith 'condemned the world'—not by words but by actions that showed what real trust in God looks like. Peter makes a remarkable connection: just as Noah and his family (eight people) were 'saved through water,' so baptism now saves us—not the physical washing, but 'the pledge of a clear conscience toward God' through Jesus Christ's resurrection (1 Peter 3:20-21). The ark floating through judgment waters becomes a picture of how we are brought safely through judgment in Christ. In 2 Peter 2, Noah is called 'a preacher of righteousness' preserved when God judged the ungodly. And Jesus Himself used Noah's day as a warning: 'As it was in the days of Noah, so it will be at the coming of the Son of Man. People were eating and drinking, marrying... and they knew nothing about what would happen until the flood came' (Matthew 24:37-39). Life went on as normal—until suddenly it didn't. Be ready!",
                "commentary_intermediate": "Hebrews 11:7 presents Noah as faith's paradigm: he was warned about 'things not yet seen' (invisible, unprecedented disaster), responded with 'holy fear' (reverent seriousness), built the ark (active obedience), saved his household (faith benefits others), and 'condemned the world' (his faith exposed others' unbelief). He became 'heir of the righteousness that is in accordance with faith'—language connecting him to Abraham and ultimately to justification doctrine. Peter's use of Noah is richly typological. The flood waters that destroyed also delivered (the ark floated above judgment); likewise baptism represents passing through judgment safely in Christ. 'Not the removal of dirt from the body' emphasizes that salvation isn't in the ritual itself but in what it represents—appeal to God through Christ's resurrection. The 'eight souls' saved through water anticipates the church preserved through the 'water' of judgment. 2 Peter's reference to Noah as a 'preacher of righteousness' (though Genesis doesn't record his sermons) suggests the tradition that Noah warned his generation during the building years. Jesus's comparison (Matthew 24, Luke 17) emphasizes not wickedness but normalcy—ordinary life continuing without awareness of impending judgment. The unexpectedness of judgment, not the sinfulness of eating and marrying, is His point.",
                "commentary_advanced": "The New Testament's use of Noah demonstrates sophisticated typological reading. Hebrews 11:7 employs key terms: 'warned' (chrematistheis—divinely instructed, used of prophetic revelation), 'not yet seen' (mēdepō blepomenōn—invisible realities requiring faith), 'reverent fear' (eulabētheis—a term used of Christ in 5:7). Noah's faith 'condemned' (katekrinen) the world—his obedience served as implicit judgment on their disobedience. His becoming heir of 'righteousness according to faith' (tēs kata pistin dikaiosynēs) links Noah to Abrahamic and Pauline justification theology. 1 Peter 3:18-22 is among the most debated passages in the NT. The connection between Christ preaching to 'spirits in prison' (3:19) and Noah's generation has generated multiple interpretations: Christ's descent to Hades, His preaching through Noah beforehand, or angelic proclamation. The 'antitype' (antitypon, 3:21) establishes typological correspondence between flood/ark and baptism/salvation. The appeal/pledge (eperōtēma) of a good conscience may reference baptismal confession. Peter's emphasis that eight were saved 'through water' (di' hydatos) carries intentional ambiguity—both 'by means of' and 'through the midst of.' The water was both instrument of judgment and medium of salvation. Jesus's Noah comparison (Matthew 24:37-39) fits the 'days of the Son of Man' discourse, paralleling unexpected judgment with ordinary activities (eating, drinking, marrying—morally neutral actions). The thief-in-the-night imagery and faithful/unfaithful servant parables extend the application.",
                "reflection_prompt": "Noah's story points beyond itself—to faith that acts on God's unseen promises, to salvation through judgment, to the need for readiness when Christ returns. What does Noah's example teach you about living by faith in promises not yet fulfilled? How does knowing that judgment came suddenly in Noah's day affect how you live today?",
            },
        ]

        for day_data in days:
            ReadingPlanDay.objects.get_or_create(
                plan=template,
                day_number=day_data["day_number"],
                defaults={
                    "title": day_data["title"],
                    "scripture_references": day_data["scripture_references"],
                    "context_summary": day_data["context_summary"],
                    "commentary_beginner": day_data["commentary_beginner"],
                    "commentary_intermediate": day_data["commentary_intermediate"],
                    "commentary_advanced": day_data["commentary_advanced"],
                    "reflection_prompt": day_data["reflection_prompt"],
                }
            )

        return template
