# ==============================================================================
# File: apps/faith/management/commands/load_ten_commandments_plan.py
# Project: Whole Life Journey - Django 5.x Personal Wellness/Journaling App
# Description: Management command to create "The Ten Commandments" reading plan
# Owner: Danny Jenkins (admin@wholelifejourney.com)
# Created: 2026-01-21
# Last Updated: 2026-01-21
# ==============================================================================
"""
Management command to create the Ten Commandments reading plan.

Creates a 10-day reading plan through the Ten Commandments:
- Each day focuses on one commandment
- Primary texts: Exodus 20 and Deuteronomy 5
- Includes Jesus' teaching on each commandment where applicable
- Cross-references to New Testament applications

Each day includes:
- Context summary (historical and theological setting)
- Commentary at 3 difficulty levels (Beginner, Intermediate, Advanced)
- Reflection prompts

Biblical accuracy verified. Non-denominational, Bible-based content.
"""

from django.core.management.base import BaseCommand
from apps.faith.models import ReadingPlanTemplate, ReadingPlanDay


class Command(BaseCommand):
    help = "Load The Ten Commandments reading plan"

    def handle(self, *args, **options):
        self.stdout.write("Loading Ten Commandments reading plan...")

        template = self._create_ten_commandments_plan()
        self.stdout.write(f"  Created: {template.title} ({template.duration_days} days)")

        self.stdout.write(self.style.SUCCESS("Ten Commandments reading plan loaded successfully!"))

    def _create_ten_commandments_plan(self):
        """Create The Ten Commandments reading plan."""
        template, created = ReadingPlanTemplate.objects.get_or_create(
            slug="the-ten-commandments",
            defaults={
                "title": "The Ten Commandments",
                "description": "A 10-day journey through the Ten Commandments—God's foundational moral law given to Israel at Mount Sinai. These commandments reveal God's character, define covenant relationship, and provide the ethical foundation for both Old and New Testaments. Each day explores one commandment in its original context (Exodus 20, Deuteronomy 5), examines how Jesus interpreted and deepened it, and considers its application for life today. Far from being outdated rules, the Ten Commandments remain central to understanding God's will for human flourishing.",
                "category": "topic",
                "difficulty": "intermediate",
                "duration_days": 10,
                "topics": ["ten commandments", "law", "moses", "sinai", "covenant", "ethics", "obedience", "holiness", "worship", "love"],
                "series": "Bible Foundations",
                "series_order": 1,
                "allowed_emails": [],
                "is_active": True,
                "is_featured": True,
            }
        )

        if not created:
            # Plan exists, skip day creation
            return template

        # Ten Commandments reading plan days
        days = [
            {
                "day_number": 1,
                "title": "No Other Gods",
                "scripture_references": ["Exodus 20:1-3", "Deuteronomy 5:6-7", "Matthew 22:37-38", "Isaiah 45:5-6"],
                "context_summary": "The Ten Commandments were given at Mount Sinai approximately three months after Israel's exodus from Egypt (Exodus 19:1). God had just delivered His people from slavery through mighty acts—the plagues, the Passover, the parting of the Red Sea. Now, at Sinai, He establishes a covenant relationship with them. The commandments are not arbitrary rules but the terms of relationship with the God who had already saved them. The preamble ('I am the LORD your God, who brought you out of Egypt') grounds the commands in grace: obedience flows from gratitude for deliverance already accomplished.",
                "commentary_beginner": "Before God gives a single command, He reminds Israel who He is: 'I am the LORD your God, who brought you out of Egypt, out of the land of slavery.' This is crucial! God doesn't start with 'Do this!' He starts with 'I saved you.' The commandments aren't ways to earn God's favor—they're instructions for people He has already rescued. The first commandment is foundational: 'You shall have no other gods before me.' In the ancient world, people worshiped many gods—gods of sun, rain, fertility, war. Egypt had hundreds of deities. But the God of Israel declares there is no other. 'Before me' can mean 'in my presence' or 'besides me' or 'in preference to me'—all are true. God alone is worthy of worship. Everything else in the commandments builds on this. If we get this wrong, nothing else works. Jesus called this the greatest commandment: 'Love the Lord your God with all your heart and with all your soul and with all your mind' (Matthew 22:37). Total devotion to the one true God is the foundation of the entire moral life.",
                "commentary_intermediate": "The Hebrew word translated 'LORD' is the divine name YHWH (Yahweh), revealed to Moses at the burning bush (Exodus 3:14-15). This is God's covenant name, distinguishing Him from all other so-called gods. The exodus serves as Israel's defining salvation event—God's power demonstrated against Egypt's gods (Exodus 12:12). The phrase 'no other gods before me' (lo yihyeh-leka elohim acherim al-panay) uses the plural 'elohim' for other gods, but the command treats them not as non-existent but as illegitimate rivals. Israel lived among peoples who worshiped many deities; the temptation to add Yahweh to a pantheon or to hedge bets with other gods would be constant. This commandment demands exclusive loyalty—a relationship more like marriage than casual acquaintance. The Shema (Deuteronomy 6:4-5) expands this: 'Hear, O Israel: The LORD our God, the LORD is one. Love the LORD your God with all your heart and with all your soul and with all your strength.' Jesus identified this as the greatest commandment (Matthew 22:37-38; Mark 12:29-30). Paul's statement 'there is but one God, the Father, from whom all things came' (1 Corinthians 8:6) reaffirms this monotheistic foundation for Christian ethics.",
                "commentary_advanced": "The Decalogue's prologue establishes the suzerainty-treaty framework common in ancient Near Eastern covenants: the great king identifies himself and recounts his gracious acts before stipulating covenant obligations. The self-identification 'I am YHWH your God' (anoki YHWH eloheka) combines the emphatic first-person pronoun with the divine name, asserting both identity and relationship. The exodus reference functions as what biblical scholars call the 'historical prologue'—grace precedes law. The first commandment's prohibition uses the Hebrew preposition 'al-panay' (before my face/in my presence), which some interpret spatially (no idols in worship spaces), others as relational priority (no rivals), and others as comprehensive exclusion (none besides me). Ancient Israel's context was henotheistic polytheism—acknowledging many gods while primarily worshiping one. This commandment demands strict monolatry that eventually developed into explicit monotheism (Isaiah 45:5-6: 'I am the LORD, and there is no other; apart from me there is no God'). The New Testament applies this commandment not only to literal idol worship but to anything that usurps God's place—money (Matthew 6:24), self (Philippians 3:19), or created things (Romans 1:25). Jesus's designation of the love command as 'first and greatest' (Matthew 22:38) shows the commandment's continuing centrality.",
                "reflection_prompt": "God introduces Himself as the One who saves before He gives commands. How does remembering what God has done for you shape your motivation to follow Him? What competes for first place in your heart—what might function as 'other gods' in your life?",
            },
            {
                "day_number": 2,
                "title": "No Idols",
                "scripture_references": ["Exodus 20:4-6", "Deuteronomy 5:8-10", "Romans 1:21-25", "1 John 5:21"],
                "context_summary": "The second commandment addresses how God is to be worshiped—or rather, how He is not to be worshiped. While the first commandment identifies who to worship (God alone), the second concerns the manner of worship (without images). Ancient peoples universally represented their gods with images—statues, carvings, pictures. These weren't seen as the gods themselves but as locations where the deity's presence could be accessed. Israel was forbidden from creating any such representation of YHWH. This commandment also introduces the concept of God's jealousy and the generational consequences of covenant faithfulness or unfaithfulness.",
                "commentary_beginner": "After commanding exclusive worship, God forbids making images to represent Him: 'You shall not make for yourself an image in the form of anything in heaven above or on the earth beneath or in the waters below.' This seems strange to us—why can't we have pictures of God? In the ancient world, idols weren't just decorations. People believed the god actually inhabited or was accessible through the image. Worshipers would bow to the statue, bring it food, and treat it as if the god were present there. But the true God cannot be contained in anything we make. Any image reduces Him. A statue can't speak, act, or save—it makes God seem limited, controllable, manageable. Israel would repeatedly fall into idol worship throughout their history, and it always led them away from the true God. God calls Himself 'jealous'—not in a petty human way, but like a husband who won't share his wife with another. He loves His people and won't tolerate rivals. The warning about consequences 'to the third and fourth generation' doesn't mean God punishes innocent children, but that idol worship creates patterns that damage families for generations. Yet His love extends 'to a thousand generations' of those who love Him—mercy far exceeds judgment!",
                "commentary_intermediate": "The second commandment prohibits 'pesel' (carved image) and 'temunah' (likeness/form). The comprehensive scope—heaven, earth, waters—excludes any created thing as a representation of God. Ancient peoples didn't necessarily believe statues were gods; rather, images served as localized access points for divine presence and power. Israel's God, however, had already provided His own 'image'—humanity itself (Genesis 1:26-27). The invisible God chose to be represented by living persons, not crafted objects. The prohibition applies specifically to images used for worship ('bow down to them or worship them'), not to all artistic representation. The tabernacle itself would contain cherubim and other images, but these were not objects of worship. God's self-description as 'jealous' (qanna) uses marriage imagery—Israel is His covenant bride (cf. Hosea 1-3; Ezekiel 16). The intergenerational consequences describe the natural effects of covenant unfaithfulness: children raised in idol-worshiping homes typically follow their parents' practices, and the cumulative social effects of turning from God compound over generations. The contrast between 'three or four generations' of consequence and 'a thousand generations' of love demonstrates that God's mercy vastly exceeds His judgment. The New Testament applies this commandment broadly: Paul describes exchanging God's glory for created images (Romans 1:23), and John's final word to Christians is 'keep yourselves from idols' (1 John 5:21).",
                "commentary_advanced": "The prohibition of images addresses the fundamental human tendency to domesticate the divine. Ancient Near Eastern religions used cult images as the locus of divine presence—rituals would 'open the mouth' of a statue to enable the god to inhabit it. Israel's prohibition was radical: YHWH's presence was mediated not through crafted images but through His word, His acts, and eventually His tabernacle/temple—none of which could be manipulated or controlled. The 'jealousy' (qin'ah) of God employs covenant-marriage terminology; the same root describes a husband's response to adultery (Numbers 5:14). Divine jealousy is not insecurity but exclusive love demanding exclusive loyalty. The generational consequences ('punishing the children... to the third and fourth generation') have troubled interpreters. Ezekiel 18 clarifies that individuals are responsible for their own sin. The Exodus passage describes the corporate effects of covenantal patterns: unfaithfulness creates cultures and family systems that perpetuate themselves, while faithfulness creates blessing that extends far longer ('thousands of generations'). The New Testament's 'idol' (eidolon) language expands beyond physical statues to include anything that replaces God—greed is idolatry (Colossians 3:5), self-worship is idolatry (Philippians 3:19). Calvin's observation that the human heart is 'a perpetual factory of idols' recognizes this commandment's enduring relevance. John's closing exhortation (1 John 5:21) suggests that sophisticated believers still need this warning.",
                "reflection_prompt": "An idol is anything that takes God's place in our hearts—it could be money, success, relationships, comfort, or even religious practices. What might you be tempted to 'bow down to'? How can you ensure that nothing becomes a substitute for the living God?",
            },
            {
                "day_number": 3,
                "title": "God's Name",
                "scripture_references": ["Exodus 20:7", "Deuteronomy 5:11", "Matthew 5:33-37", "Matthew 6:9"],
                "context_summary": "The third commandment protects God's name from misuse. In biblical thought, a name is not merely a label but represents the person's character, reputation, and authority. To know someone's name is to have access to them; to invoke someone's name is to call upon their presence and power. God had revealed His personal name, YHWH, to Israel—an extraordinary gift of intimacy. This commandment guards against trivializing, manipulating, or profaning that sacred name. It has implications for oath-taking, false prophecy, and how believers represent God to the world.",
                "commentary_beginner": "The third commandment says not to 'misuse' (or 'take in vain') the name of the LORD your God. In the Bible, names are deeply significant—they represent who someone really is. God revealed His personal name, YHWH (often translated 'LORD' in capital letters), to Moses at the burning bush. This was an incredible privilege! Other nations had many gods, but Israel knew their God's actual name. To misuse this name meant treating something precious as if it were worthless ('vain' means empty or worthless). How might people misuse God's name? Using it carelessly in conversation, swearing oaths by God's name without intending to keep them, or claiming to speak for God when He hasn't spoken. False prophets who said 'Thus says the LORD' when God had said nothing broke this commandment. The warning is serious: the LORD 'will not hold anyone guiltless' who misuses His name. Jesus expanded on this teaching. In the Sermon on the Mount (Matthew 5:33-37), He taught that instead of swearing elaborate oaths by God's name, we should simply let our 'yes be yes' and our 'no be no.' Our honesty shouldn't depend on invoking God's name—we should be truthful all the time. Jesus also taught us to pray 'hallowed be your name' (Matthew 6:9)—asking that God's name be treated as holy throughout the earth.",
                "commentary_intermediate": "The Hebrew phrase 'lo tissa et-shem YHWH eloheka lashav' literally means 'you shall not lift up/carry the name of YHWH your God to emptiness/falsehood.' The word 'shav' can mean emptiness, worthlessness, or falsehood. The primary ancient application concerned oaths: invoking God's name to guarantee the truth of a statement or promise (Leviticus 19:12). To swear by YHWH and then lie or fail to fulfill the vow was to use God's name to support falsehood—making God complicit in deceit. The commandment also applied to false prophecy—speaking 'in the name of the LORD' when God had not spoken (Deuteronomy 18:20). More broadly, Israel was to bear (carry) God's name with honor, not shame; they represented YHWH to the nations. When they sinned, God's name was 'profaned among the nations' (Ezekiel 36:20-23). Jesus's teaching on oaths (Matthew 5:33-37) doesn't merely prohibit false swearing but calls for such consistent truthfulness that oaths become unnecessary. The one who always tells the truth needs no special formula to be believed. The Lord's Prayer petition 'hallowed be your name' asks for God's name to be treated as holy—by the one praying and throughout the world. This commandment thus calls believers to live in ways that honor God's reputation.",
                "commentary_advanced": "The third commandment operates at multiple levels. Grammatically, 'nasa' (to lift/carry) suggests bearing God's name as a representative bears credentials—Israel carries YHWH's name as His covenant people. The term 'shav' encompasses both emptiness (treating as trivial) and falsehood (deceptive use). Oath formulas like 'as YHWH lives' invoked divine witness to statements; false oaths constituted practical atheism—acting as if God wouldn't notice or respond. Prophetic speech 'in the name of YHWH' claimed divine authorization; false prophecy therefore misappropriated divine authority (Jeremiah 23:25-32). The commandment's communal dimension is significant: Israel's behavior affected how surrounding nations perceived YHWH. Ezekiel's oracle about God's name being 'profaned among the nations' through Israel's conduct (Ezekiel 36:20-23) shows that misuse extends beyond verbal formulas to behavioral representation. Jesus's antithesis in the Sermon on the Mount (Matthew 5:33-37) intensifies the commandment: rather than specifying when oaths are permitted, He calls for consistent truthfulness that renders oaths unnecessary. The deeper issue is integrity—correspondence between word and reality. The Lord's Prayer petition 'hagiastheto to onoma sou' (may your name be made holy) asks for divine action that results in universal reverence for God's name—a petition with eschatological dimensions (cf. Ezekiel 36:23). For Christians, bearing the name of Christ (Acts 11:26) extends this commandment's application.",
                "reflection_prompt": "We 'carry' God's name as His people—others form impressions of God based on our lives. How do your words and actions affect God's reputation? In what ways might you be taking God's name 'in vain' through careless speech or inconsistent living?",
            },
            {
                "day_number": 4,
                "title": "The Sabbath",
                "scripture_references": ["Exodus 20:8-11", "Deuteronomy 5:12-15", "Mark 2:27-28", "Hebrews 4:9-11"],
                "context_summary": "The fourth commandment establishes a rhythm of work and rest modeled on God's own pattern in creation. This is the longest of the Ten Commandments, indicating its importance. Uniquely, the two versions in Exodus and Deuteronomy give different theological rationales: Exodus grounds the Sabbath in creation (God rested on the seventh day), while Deuteronomy grounds it in redemption (Israel was delivered from slavery). Both reasons matter. The Sabbath is simultaneously about honoring God as Creator and experiencing the freedom that comes from His salvation.",
                "commentary_beginner": "The Sabbath commandment calls Israel to 'remember' and 'keep' the seventh day as holy—set apart from the other days. For six days, work; on the seventh, rest. This applied to everyone: the head of household, children, servants, even animals and foreigners living among them. No one was to be worked without rest. But why? Exodus gives one reason: 'For in six days the LORD made the heavens and the earth, the sea, and all that is in them, but he rested on the seventh day.' God Himself modeled the pattern. Deuteronomy gives another reason: 'Remember that you were slaves in Egypt.' Slaves don't get days off. Pharaoh worked the Israelites relentlessly. But God freed them, and the Sabbath was a weekly reminder that they were no longer slaves. The Sabbath was about trust: could Israel stop working and trust God to provide? It was about worship: setting time aside for God. And it was about compassion: ensuring rest even for servants and animals. Jesus taught that 'the Sabbath was made for man, not man for the Sabbath' (Mark 2:27). It's a gift, not a burden! And Jesus declared Himself 'Lord even of the Sabbath'—He has authority over how it's observed. The New Testament letter to the Hebrews speaks of a 'Sabbath-rest' that remains for God's people—an ultimate rest that we enter through faith in Christ.",
                "commentary_intermediate": "The Sabbath commandment is unique in several ways: it's the longest commandment, it includes a positive command ('remember,' 'observe') alongside the prohibition, and it provides two different theological groundings. The Exodus rationale connects to creation theology: God's pattern of work and rest provides the model for human existence. The Deuteronomy rationale connects to redemption: freed slaves now experience the rest that Egypt denied them. These aren't contradictory but complementary—the Sabbath celebrates both God as Creator and God as Redeemer. The commandment's social dimension is striking: it extends to servants, foreigners, and even animals. No one in Israel's society could be worked without rest. This made Israel distinctive in the ancient world and demonstrated that humans are not merely production units. The word 'sabbath' (shabbat) comes from the verb 'to cease' or 'to rest.' It involves both stopping work and setting the day apart as holy. The New Testament shows Jesus engaging in Sabbath controversies, not to abolish the Sabbath but to correct legalistic distortions (Mark 2:23-3:6). His declaration that 'the Sabbath was made for man, not man for the Sabbath' restores its original purpose as gift, not burden. Hebrews 4:9-11 interprets the Sabbath typologically: physical rest points to spiritual rest entered through faith. The early church's gathering on the 'first day of the week' (Sunday, the resurrection day) eventually became the Christian pattern.",
                "commentary_advanced": "The Sabbath commandment's dual rationale in Exodus (creation) and Deuteronomy (redemption) has generated extensive discussion. Some scholars see deuteronomic 'update' reflecting later theological development; others see the two reasons as original, complementary perspectives—creation and redemption being two facets of God's single purpose. The verb 'zakhor' (remember) in Exodus implies the Sabbath predated Sinai (cf. Exodus 16's manna narrative); 'shamor' (observe/keep) in Deuteronomy emphasizes ongoing obedience. The extension to all members of society—including non-Israelites and animals—reflects the creation basis: all creatures share the Creator's rhythm. The prophets both critiqued perfunctory Sabbath observance (Isaiah 1:13) and anticipated its eschatological fulfillment (Isaiah 56:2-8; 66:23). Second Temple Judaism developed elaborate Sabbath regulations (39 categories of forbidden work in the Mishnah), which Jesus critiqued not as abrogating Sabbath but as missing its purpose. His self-designation as 'Lord of the Sabbath' (kyrios tou sabbatou, Mark 2:28) claims authority to interpret its proper observance. The Hebrews passage (4:1-11) develops the Sabbath's typological significance: Canaan rest, weekly rest, and eschatological rest form a continuous theological trajectory. The 'sabbatismos' (Sabbath-rest) remaining for God's people (Hebrews 4:9) uses a distinctive term suggesting ongoing observance—though debated whether this means literal Sabbath-keeping or entering God's rest through faith. Christian practice shifted to Sunday as 'the Lord's day' (Revelation 1:10), commemorating resurrection while retaining Sabbath's rhythm and purpose.",
                "reflection_prompt": "The Sabbath was given as a gift—a reminder that we are not slaves and that our value doesn't depend on productivity. How well do you practice rest? What keeps you from trusting God enough to stop working? How might regular rest be an act of faith?",
            },
            {
                "day_number": 5,
                "title": "Honor Your Parents",
                "scripture_references": ["Exodus 20:12", "Deuteronomy 5:16", "Ephesians 6:1-3", "Mark 7:9-13"],
                "context_summary": "The fifth commandment transitions from duties toward God (commandments 1-4) to duties toward other people (commandments 5-10). Honoring parents stands at this pivotal position because parents represent God's authority in the family and because the family is the foundation of society. This is the first commandment with a promise attached: long life in the land. In a culture without retirement systems or social security, honoring parents meant providing for their care in old age. This commandment has implications for family relationships, social stability, and the transmission of faith across generations.",
                "commentary_beginner": "The fifth commandment is simple but profound: 'Honor your father and your mother.' It's the first commandment that deals with how we treat other people, and it comes with a promise: 'so that you may live long in the land.' What does it mean to 'honor'? The Hebrew word means to treat as weighty, valuable, significant. For children, this means obedience and respect. For adult children, it means continued respect and care—especially as parents age. In ancient Israel without pensions or nursing homes, children were responsible for their elderly parents. To dishonor them was to abandon them. Why does this commandment come right after the commands about God? Because parents are our first teachers about God. They pass down faith, values, and identity. To reject parents' authority was often to reject their God too. Society depends on strong families; when children despise parents, social bonds collapse. Jesus upheld this commandment even while teaching that following Him might require painful family separations (Matthew 10:37). He criticized religious leaders who used technicalities to avoid caring for their parents while appearing pious (Mark 7:9-13). Paul repeated this commandment for Christians, calling it 'the first commandment with a promise' (Ephesians 6:1-3). Honor doesn't mean parents are always right or that abuse should be tolerated. But it does mean recognizing the dignity of those through whom God gave us life.",
                "commentary_intermediate": "The Hebrew verb 'kabed' (honor) literally means 'to make heavy' or 'give weight to'—treating parents as persons of significance rather than dismissing them. This commandment bridges the two tablets: duties to God (1-4) and duties to others (6-10). Parents occupy this transitional position because they represent divine authority in the home—they are God's agents in bringing children into existence and raising them. The promise of long life 'in the land' has corporate as well as individual dimensions: societies that maintain family bonds flourish; those that don't, collapse. Deuteronomy's addition 'that it may go well with you' reinforces this. The commandment applied throughout life, not just childhood: adult children bore responsibility for aging parents. Proverbs repeatedly contrasts children who honor parents with those who despise or abuse them (Proverbs 19:26; 20:20; 30:17). The seriousness of this command is seen in laws prescribing death for striking or cursing parents (Exodus 21:15, 17)—though these likely addressed extreme cases of elder abuse rather than childish disobedience. Jesus affirmed the commandment while exposing the Pharisees' evasion through 'Corban' (Mark 7:9-13)—declaring property dedicated to God to avoid using it for parental support. Paul's citation in Ephesians 6:1-3 shows the commandment's continuing validity for Christians, while adding the reciprocal duty: 'Fathers, do not exasperate your children' (Ephesians 6:4).",
                "commentary_advanced": "The fifth commandment's position has generated discussion since antiquity. Jewish tradition sometimes numbered it with the first tablet (duties to God), recognizing parents as God's representatives. The Hebrew 'kabed' (from kbd, 'heavy') contrasts with 'qalal' ('curse,' literally 'make light of')—honoring versus treating as insignificant. The absence of age-limitation is significant: unlike Ephesians' 'children, obey,' Exodus and Deuteronomy address all Israelites regarding ongoing parental honor. Ancient Near Eastern parallels exist (Hammurabi's Code addresses parental mistreatment), but Israel's commandment is distinctively unconditional—no qualifications about worthy parents. The land-promise connects to covenant blessing; Deuteronomy's addition 'that it may go well with you' uses terminology associated with covenant prosperity. The death penalty for striking or cursing parents (Exodus 21:15, 17; Leviticus 20:9) seems harsh but addresses elder abuse in a society where elderly parents were vulnerable to mistreatment by children controlling resources. Jesus's Corban controversy (Mark 7:9-13) illustrates how religious practice can circumvent the commandment's intent: declaring assets 'devoted to God' technically fulfilled a vow while practically depriving parents of support. The term 'word of God' for this commandment (Mark 7:13) shows Jesus's high view of the Decalogue. Paul's 'first commandment with a promise' (Ephesians 6:2) accurately notes its unique position in the Decalogue, applying it universally ('in the Lord') while adding reciprocal parental responsibility to avoid provoking children.",
                "reflection_prompt": "How do you currently honor your parents (or parent figures)? If they are living, what practical ways might you show them dignity and care? If they have passed, how can you honor their memory and the good they invested in your life?",
            },
            {
                "day_number": 6,
                "title": "Do Not Murder",
                "scripture_references": ["Exodus 20:13", "Deuteronomy 5:17", "Matthew 5:21-26", "1 John 3:15"],
                "context_summary": "The sixth commandment protects human life with just two words in Hebrew: 'lo tirtsach' (you shall not murder). This commandment is grounded in the creation of humans in God's image (Genesis 9:6)—to murder a person is to destroy an image-bearer of God. The Hebrew word 'ratsach' refers specifically to unlawful killing; the same verb is used for both intentional murder and unintentional manslaughter, but not for judicial execution or killing in war. Jesus dramatically expanded the commandment's scope, teaching that the anger and contempt at murder's root also violate God's intent.",
                "commentary_beginner": "This commandment seems obvious—of course we shouldn't murder! But there's more here than meets the eye. First, the command protects human life because humans are made in God's image (Genesis 9:6). Every person—regardless of age, ability, status, or nationality—carries the image of God. To murder someone is to destroy something precious to God. The Hebrew word used here ('ratsach') refers to illegal killing. The Old Testament distinguishes between murder (which is always forbidden), accidental killing (for which cities of refuge were provided), and other types of killing (like judicial execution or war) that operated under different principles. But here's where it gets challenging: Jesus went beyond the act to the heart. In the Sermon on the Mount (Matthew 5:21-26), He said that anyone who is angry with a brother or sister is subject to judgment, and whoever says 'You fool!' is in danger of hellfire. That's shocking! Jesus is saying that the hatred and contempt that lead to murder are themselves violations of this command. You don't have to pull a trigger to break this commandment—you can break it with your heart. John makes this explicit: 'Anyone who hates a brother or sister is a murderer' (1 John 3:15). This commandment calls us not just to avoid killing but to root out the anger, hatred, and dehumanization that lead to it.",
                "commentary_intermediate": "The Hebrew 'lo tirtsach' is one of the Decalogue's shortest commands—just two words. The verb 'ratsach' has specific connotations: it's used for illegal killing (murder and manslaughter) but not for judicial execution (Hebrew 'harag' or 'mut') or killing in war (Hebrew 'nakah'). Numbers 35:16-21 uses 'ratsach' for both intentional murder and unintentional killing, with different consequences for each. This commandment doesn't address every ethical question about taking life but establishes the baseline: human life is sacred and must not be taken without just cause. The foundation is Genesis 9:6: 'Whoever sheds human blood, by humans shall their blood be shed; for in the image of God has God made mankind.' Murder is wrong because it destroys an image-bearer of God. Jesus's interpretation in Matthew 5:21-26 follows a pattern throughout the Sermon on the Mount: 'You have heard... but I tell you.' He doesn't abolish the commandment but deepens it, addressing the inner disposition that produces murder. Anger (orge), contemptuous insults ('Raca,' an Aramaic term of derision), and dismissive labels ('fool,' moros) are on a continuum with murder—they dehumanize the other person. Jesus's teaching on reconciliation (5:23-26) shows the positive flip side: actively pursue peace with those you've wronged or who've wronged you. First John 3:15's equation of hatred with murder isn't hyperbole but spiritual reality: hatred is murder in the heart.",
                "commentary_advanced": "The sixth commandment's verb 'ratsach' occurs 46 times in the Hebrew Bible, primarily for illegal killing (murder, Numbers 35:16-21; manslaughter, Deuteronomy 4:42; blood-avenger killing, Numbers 35:27). It's never used for judicial execution or warfare, suggesting semantic distinction from other killing-verbs. The commandment's brevity ('lo tirtsach'—two words) parallels commandments 7-9, creating a series of terse prohibitions protecting fundamental human goods: life, marriage, property, reputation. The theological grounding in the imago Dei (Genesis 9:6) makes murder an assault on God Himself—destroying His image-bearers. Jesus's antithesis (Matthew 5:21-26) operates on the principle that commandments have both a minimum standard (the act prohibited) and a maximum intention (the virtue required). Murder is prohibited; love is required. The continuum from anger to contempt to murder shows how internal disposition produces external action. The term 'Raca' (probably from Aramaic 'reqa,' empty-headed) and 'moros' (fool) represent escalating dehumanization—treating persons as worthless. Jesus's insistence on reconciliation before worship (5:23-24) establishes that vertical relationship with God cannot be maintained while horizontal relationships are broken. First John's 'everyone who hates his brother is a murderer' (3:15) uses the same logic: the seed contains the fruit. The early church's consistent opposition to abortion, infanticide, and gladiatorial combat shows how broadly they applied this commandment against contemporary cultural practices.",
                "reflection_prompt": "Jesus taught that anger and contempt are on the same spectrum as murder. Is there anyone you've dehumanized in your heart—through hatred, dismissiveness, or demeaning thoughts? What would it look like to actively pursue reconciliation and to see that person as an image-bearer of God?",
            },
            {
                "day_number": 7,
                "title": "Do Not Commit Adultery",
                "scripture_references": ["Exodus 20:14", "Deuteronomy 5:18", "Matthew 5:27-30", "Hebrews 13:4"],
                "context_summary": "The seventh commandment protects the marriage covenant—the most intimate human relationship. In Scripture, marriage is not merely a social contract but a covenant mirroring God's faithfulness to His people. Adultery doesn't just break a rule; it betrays trust, shatters families, and violates a sacred bond. The prophets frequently used adultery as a metaphor for Israel's unfaithfulness to God, showing how seriously Scripture treats this sin. Jesus, like He did with murder, extended the commandment to address the lustful heart from which adultery springs.",
                "commentary_beginner": "God's command against adultery protects marriage—one of His first gifts to humanity. Marriage is more than a contract; it's a covenant, a sacred promise of faithfulness 'till death do us part.' Adultery breaks that promise in the most intimate way possible. It betrays trust, inflicts deep wounds, and tears families apart. Children suffer. Communities suffer. And the bond between husband and wife—meant to be a safe place of love and trust—is shattered. Throughout the Bible, God uses marriage as a picture of His relationship with His people. When the prophets described Israel worshiping other gods, they called it adultery (see Hosea, Ezekiel 16). God is the faithful husband; His people kept running to 'lovers' (other gods). This shows how seriously God takes marital faithfulness—it reflects His own character. Jesus, as He did with murder, went deeper than the act to the heart. In Matthew 5:27-30, He said that looking at someone lustfully is already committing adultery in the heart. That seems extreme! But Jesus understood that actions begin as thoughts. The lustful look, unchecked, leads to the adulterous act. By addressing the root, Jesus calls us to purity of heart, not just purity of behavior. This commandment isn't just about avoiding a sin; it's about honoring the gift of marriage and the God who created it.",
                "commentary_intermediate": "The Hebrew 'lo tin'af' parallels the previous commandment's brevity: just two words prohibiting adultery. In the ancient Near East, adultery typically referred specifically to sexual relations with another man's wife; the commandment protected both the marriage covenant and family lineage. But Scripture's broader ethic encompasses all sexual immorality (porneia), not just technically-defined adultery. The marriage covenant is treated with special seriousness because it mirrors the covenant relationship between God and His people. The prophets Hosea, Jeremiah, and Ezekiel extensively use marital imagery: Israel as unfaithful wife, YHWH as betrayed but pursuing husband. Hosea's own marriage to unfaithful Gomer becomes a prophetic sign-act. This theological weight explains why adultery appears in Scripture's most serious sin-lists and why Proverbs warns so extensively against it (Proverbs 5-7). Jesus's teaching in Matthew 5:27-30 again deepens the commandment by addressing the inner life. 'Looking lustfully' translates a phrase indicating intentional, desirous gazing—not mere noticing but cultivating desire. The hyperbolic language about gouging out eyes and cutting off hands makes a serious point: radical measures are appropriate to deal with sin that leads to destruction. Jesus's teachings on divorce (Matthew 19:3-9) further show His high view of marriage: God's original intent was permanent, faithful union. Hebrews 13:4's declaration that 'marriage should be honored by all' and the 'marriage bed kept pure' summarizes the New Testament's continuation of this commandment.",
                "commentary_advanced": "The seventh commandment's verb 'na'af' refers specifically to adultery, distinguished from 'zanah' (sexual immorality/prostitution). In its original context, the commandment protected the integrity of Israelite family structures, lineage, and inheritance. The married woman was central: adultery was defined by her status (a man with an unmarried woman faced different laws). However, the commandment's canonical context broadens its application: the Song of Songs celebrates marital sexuality, Proverbs warns against both male and female seduction (chs. 5-7), and prophetic literature uses adultery metaphorically for covenant unfaithfulness (Hosea 2:2; Jeremiah 3:8-9; Ezekiel 16:32). Jesus's antithesis (Matthew 5:27-28) employs the phrase 'pros to epithymesai auten' (with the purpose of lusting for her), indicating intentional cultivation of desire, not involuntary attraction. The 'heart' (kardia) as locus of adultery shows continuity with Jesus's teaching that defilement comes from within (Mark 7:21). The hyperbolic language about self-mutilation (5:29-30) functions rhetorically: since sin's source is the will, not the body, physical mutilation wouldn't help; the point is the seriousness of the issue and the necessity of decisive action against sin. The 'one flesh' theology of Genesis 2:24, cited by Jesus in divorce discussions (Matthew 19:5), provides the positive vision: marriage as permanent union reflecting God's faithful, exclusive love. Paul's extension of this imagery to Christ and the church (Ephesians 5:22-33) shows the commandment's ultimate theological significance: human marriage images divine-human covenant.",
                "reflection_prompt": "Jesus said that lustful looking is adultery of the heart. In our image-saturated culture, this is challenging. How do you guard your eyes and your heart? If you're married, how do you actively cultivate faithfulness—not just avoiding wrong, but nurturing right?",
            },
            {
                "day_number": 8,
                "title": "Do Not Steal",
                "scripture_references": ["Exodus 20:15", "Deuteronomy 5:19", "Ephesians 4:28", "Luke 19:1-10"],
                "context_summary": "The eighth commandment protects property—the right of people to own things that belong to them. This seems straightforward, but the implications are profound. Property represents labor, provision for family, and security for the future. Theft violates not just property rights but personal dignity—it treats the victim as someone whose work and possessions don't matter. Scripture's teaching on property is balanced: ownership is legitimate, but so is generosity; theft is forbidden, but so is hoarding. The New Testament transforms the negative prohibition into a positive calling: work honestly so you can give to others.",
                "commentary_beginner": "The command 'You shall not steal' protects what belongs to others. This includes obvious theft—taking someone's money or possessions—but extends much further. You can steal by cheating in business, not paying fair wages, borrowing and not returning, plagiarizing someone's work, or taking credit for what others accomplished. In the ancient world, theft could be devastating. A stolen ox wasn't just property; it was a family's livelihood. To steal from the poor was to threaten their survival. That's why the prophets thundered against those who stole from the vulnerable through unjust scales, rigged courts, or predatory lending (Amos 8:4-6). But the Bible's view of property isn't simply 'what's mine is mine.' Yes, ownership is legitimate—but so is generosity. The same Law that prohibits theft also commands leaving gleanings for the poor (Leviticus 19:9-10) and canceling debts periodically (Deuteronomy 15). The New Testament transforms the prohibition into a positive command. Paul writes: 'Anyone who has been stealing must steal no longer, but must work, doing something useful with their own hands, that they may have something to share with those in need' (Ephesians 4:28). The opposite of stealing isn't just not stealing—it's working so you can give! The story of Zacchaeus (Luke 19:1-10) shows what repentance from theft looks like: he gave half his possessions to the poor and paid back four times what he had stolen.",
                "commentary_intermediate": "The Hebrew 'lo tignov' (you shall not steal) uses a verb that covers all types of theft—property, but also potentially kidnapping (stealing persons, as in Exodus 21:16). The commandment assumes the legitimacy of private property while establishing its limits. Property rights in Israel weren't absolute—they were bounded by covenant obligations. The land ultimately belonged to God (Leviticus 25:23), and laws about gleaning, Sabbath years, and Jubilee prevented permanent accumulation while protecting the vulnerable. The prophets' denunciations of theft often targeted systemic injustice: merchants using dishonest scales (Amos 8:5), rulers seizing fields through corrupt courts (1 Kings 21), employers withholding wages (Jeremiah 22:13). These were theft even if technically 'legal.' The wisdom literature warns against both the desperation that drives stealing and the greed that hoards (Proverbs 30:8-9). Jesus's teaching assumed property rights (parables of talents, laborers in vineyard) while warning against wealth's spiritual dangers (Matthew 6:19-21; Luke 12:13-21). The early church practiced radical generosity (Acts 2:44-45; 4:32-35), but Ananias and Sapphira's sin was not keeping property but lying about it (Acts 5:4). Paul's transformation in Ephesians 4:28 is striking: the former thief should now work—not merely for self-sufficiency but to have resources for giving. Theft takes; love gives. The command thus points toward generosity as its positive fulfillment.",
                "commentary_advanced": "The eighth commandment's verb 'ganav' encompasses property theft, but Exodus 21:16 and Deuteronomy 24:7 use the same root for kidnapping, leading some scholars to see person-stealing as the primary reference (reading commandments 6-8 as protecting life, marriage, and persons). However, the broader biblical usage of 'ganav' for property theft (Genesis 31:19; Joshua 7:11) supports the traditional interpretation. Israel's property ethic was distinctive: land belonged to God and was allocated to tribes and families as inheritance; the Jubilee laws (Leviticus 25) prevented permanent alienation. Property served human flourishing, not the reverse. Prophetic critique targeted theft accomplished through legal mechanisms: unjust scales (Hosea 12:7), bribery (Isaiah 1:23), debt manipulation (Nehemiah 5:1-5), and judicial corruption (Amos 5:12). The Hebrew term 'ashaq' (oppression/extortion) and 'gazal' (robbery/violent taking) complement 'ganav' in describing economic injustice. Jesus's temple cleansing (Mark 11:17, citing Jeremiah 7:11, 'den of robbers') shows theft's religious dimension: corrupt religious commerce robs God. The Zacchaeus narrative (Luke 19:1-10) demonstrates repentance's economic expression: restitution exceeding legal requirements (fourfold, per Exodus 22:1 for stolen sheep). Paul's Ephesians 4:28 formulation moves beyond negative prohibition through neutral self-sufficiency to positive generosity—an ethic of productive contribution to community. The eschatological vision anticipates a world without theft because abundance removes motive (Isaiah 65:21-22).",
                "reflection_prompt": "Theft can be subtle—padding an expense report, wasting an employer's time, downloading pirated content, failing to pay fair prices. Are there areas where you've rationalized taking what isn't yours? How might you move from 'not stealing' to working so you can give?",
            },
            {
                "day_number": 9,
                "title": "Do Not Bear False Witness",
                "scripture_references": ["Exodus 20:16", "Deuteronomy 5:20", "Colossians 3:9-10", "John 8:44"],
                "context_summary": "The ninth commandment protects truth—specifically truth-telling in legal and social contexts. The language of 'witness' points to the courtroom: in ancient Israel, testimony could determine life or death. False witness could condemn the innocent or acquit the guilty. But the commandment extends beyond courtrooms to all truthful speech: gossip, slander, deception, and dishonesty in relationships all violate its spirit. Scripture consistently presents God as a God of truth, Satan as 'the father of lies,' and His people as those who must reflect His truthful character.",
                "commentary_beginner": "The ninth commandment forbids being a 'false witness against your neighbor.' In ancient Israel, the courtroom context was primary. There were no police investigations, forensic evidence, or security cameras. Justice depended on witnesses. If you saw a crime, your testimony could convict or acquit. False testimony could literally get an innocent person executed (that's what happened to Naboth in 1 Kings 21, when two false witnesses accused him so the king could steal his vineyard). The Law was so serious about this that false witnesses received the punishment they tried to inflict on others (Deuteronomy 19:16-21). But the commandment applies far beyond courtrooms. Gossip bears false witness—spreading unverified or exaggerated stories about people. Slander bears false witness—deliberately damaging someone's reputation. Flattery bears false witness—saying things we don't mean to manipulate people. Even silence can bear false witness—when we let lies stand unchallenged. Jesus called Satan 'the father of lies' (John 8:44). Lying is demonic at its root. God, by contrast, is truth itself; He cannot lie (Titus 1:2). When we lie, we act like Satan's children. When we tell the truth, we act like God's. Paul tells the Colossians to stop lying to each other because they've 'taken off the old self' and 'put on the new self' in Christ (Colossians 3:9-10). Truth-telling is part of our new identity.",
                "commentary_intermediate": "The Hebrew 'ed shaqer' (false witness) uses courtroom terminology. In Israel's legal system, a minimum of two witnesses was required for conviction (Deuteronomy 17:6; 19:15), and witnesses bore serious responsibility. The 'lex talionis' applied to false testimony: whatever the false witness attempted to bring upon the accused would be done to them (Deuteronomy 19:16-21). This wasn't vindictive but protective—it created powerful disincentive against false accusation. Notably, Deuteronomy 5:20 uses 'ed shav' (vain/empty witness) rather than Exodus's 'ed shaqer' (lying witness); both are prohibited, broadening the commandment from deliberate lies to careless, unverified testimony. The commandment protects the neighbor's reputation and life. Proverbs extensively addresses speech ethics: lying lips are an abomination (12:22), a false witness will perish (21:28), and gossip separates close friends (16:28; 17:9). The prophets condemned false prophecy as the ultimate 'false witness'—speaking lies in God's name (Jeremiah 23:25-32). Jesus's trial featured conflicting false witnesses (Mark 14:56-59), demonstrating how the innocent suffer from this sin. Paul's ethical instructions include 'putting away falsehood' and 'speaking truth with neighbors' (Ephesians 4:25), while Colossians 3:9-10 grounds truth-telling in the believer's new identity in Christ. The contrast between Satan as 'father of lies' (John 8:44) and Christ as 'the truth' (John 14:6) shows the spiritual stakes: truthfulness aligns us with God; deception aligns us with His enemy.",
                "commentary_advanced": "The ninth commandment's legal setting ('ed'—witness) has led some scholars to limit its application to formal testimony, but biblical usage extends to all reliable or unreliable speech about others. The term 'shaqer' (lie/falsehood) appears in contexts beyond courtrooms (Psalm 119:163; Proverbs 6:17), while the parallel 'shav' (empty/vain) in Deuteronomy 5:20 suggests even truthful-but-careless testimony falls under prohibition. The 'neighbor' (rea') is covenant-community member, though Scripture extends truth-obligations broadly. Israel's distinctive requirement of multiple witnesses (Deuteronomy 17:6; 19:15; Numbers 35:30) contrasted with surrounding legal systems and provided structural protection against false accusation. The false witness law's talion principle (Deuteronomy 19:16-21) served both deterrent and restorative functions. Prophetic literature's extensive condemnation of false prophecy (Jeremiah 14:14; 23:25-32; Ezekiel 13) represents the most serious form of false witness—lying about God's words. Jesus's teaching intensifies the commandment: oaths were designed to guarantee truth, but Jesus calls for such consistent truthfulness that oaths become unnecessary (Matthew 5:33-37). The Johannine literature's truth-emphasis is striking: Jesus is truth incarnate (John 14:6), the Spirit is 'Spirit of truth' (John 14:17; 15:26; 16:13), Satan is 'father of lies' (John 8:44), and walking in truth characterizes authentic discipleship (1 John 1:6; 2 John 4; 3 John 3-4). Colossians 3:9-10's grounding of truthfulness in the 'new self' being renewed in knowledge after its Creator's image connects truth-telling to creation theology: humans image the God who is truth.",
                "reflection_prompt": "Beyond outright lies, how do you handle truth? Do you exaggerate, leave out important details, or stay silent when truth needs to be spoken? Are there relationships where you're pretending to be something you're not? What would it look like to be known as someone whose word can be trusted?",
            },
            {
                "day_number": 10,
                "title": "Do Not Covet",
                "scripture_references": ["Exodus 20:17", "Deuteronomy 5:21", "Luke 12:15", "Romans 7:7-8", "Colossians 3:5"],
                "context_summary": "The tenth commandment is unique: it addresses the inner life—what happens in the heart before any action occurs. While the previous commandments prohibited acts (murder, adultery, theft), this one prohibits desire itself. Coveting is wanting what belongs to someone else—the neighbor's house, spouse, servants, animals, or anything that is theirs. This commandment reveals that God cares about more than behavior; He cares about the heart from which behavior flows. It also functions as a summary: break this commandment in your heart, and you're on the path to breaking all the others.",
                "commentary_beginner": "The final commandment goes beneath behavior to the heart: 'You shall not covet.' To covet means to desire intensely, especially wanting what belongs to someone else. The commandment lists examples: your neighbor's house, wife, servants, ox, donkey—'anything that belongs to your neighbor.' This is different from the other commandments. You can tell if someone murdered, stole, or lied. But coveting happens inside, where only God and you can see. Why does God care about desires? Because desires lead to actions. James 1:14-15 explains: 'Each person is tempted when they are dragged away by their own evil desire and enticed. Then, after desire has conceived, it gives birth to sin.' David coveted Bathsheba—and it led to adultery and murder. Ahab coveted Naboth's vineyard—and it led to false witness and murder. Covetousness is the seed; the other sins are the fruit. Paul said this commandment was the one that revealed his sinfulness (Romans 7:7-8). He could appear to keep the other commandments outwardly, but this one exposed his heart. Jesus warned, 'Watch out! Be on your guard against all kinds of greed; life does not consist in an abundance of possessions' (Luke 12:15). Contentment is the opposite of covetousness—finding satisfaction in what God has provided rather than craving what He hasn't. Paul learned to be content in all circumstances (Philippians 4:11-13). The cure for covetousness is gratitude and trust: thanking God for what we have and trusting that He knows what we need.",
                "commentary_intermediate": "The tenth commandment's uniqueness lies in prohibiting desire (Hebrew 'chamad'—to desire, covet, take pleasure in) rather than action. Deuteronomy 5:21 uses both 'chamad' and hitavveh (desire, lust, crave), emphasizing the internal nature. The detailed list—house, wife, servants, animals, 'anything'—comprehensively covers what neighbors possess. This commandment reveals the Torah's concern with heart-orientation, not merely external compliance. Coveting is the root from which other sins grow: David's coveting led to adultery and murder (2 Samuel 11); Achan's coveting led to theft (Joshua 7:21); Ahab's coveting led to false witness and murder (1 Kings 21). Paul found this commandment uniquely convicting (Romans 7:7-8): 'I would not have known what coveting really was if the law had not said, 'You shall not covet.' But sin, seizing the opportunity afforded by the commandment, produced in me every kind of coveting.' The commandment exposed his heart when external conformity might have deceived him. Jesus's teaching consistently emphasizes heart-level righteousness (Matthew 5-7; 15:19) and warns specifically against covetousness/greed (pleonexia)—which Luke 12:15 equates with life orientation. Paul calls covetousness 'idolatry' (Colossians 3:5; Ephesians 5:5)—a striking connection back to commandments 1-2. Coveting puts things in God's place, trusting possessions rather than the Provider. The antidote is contentment (Philippians 4:11-13; 1 Timothy 6:6-8; Hebrews 13:5)—satisfaction rooted in relationship with God rather than accumulation.",
                "commentary_advanced": "The tenth commandment's interiority has generated extensive discussion. Some scholars argue 'chamad' includes the taking (not just desiring)—based on passages where coveting leads to acquisition (Joshua 7:21; Micah 2:2). However, the commandment's structure (desiring what belongs to the neighbor) and Deuteronomy's addition of hitavveh support the traditional interpretation: the prohibition addresses desire itself. The commandment thus reveals Torah's interest in disposition, not merely action—an interest developed extensively in wisdom literature (Proverbs 4:23: 'guard your heart') and prophetic emphasis on heart-transformation (Jeremiah 31:33; Ezekiel 36:26). The detailed list in Exodus 20:17 places 'house' first (possibly meaning household/estate), while Deuteronomy 5:21 separates 'wife' with distinct verb, perhaps elevating her status above property. The progression neighbor's house → wife → servants → animals → 'anything' moves from most to least valuable, comprehensively covering possessions. Paul's autobiographical reflection (Romans 7:7-8) treats this commandment as summarizing Torah's convicting function: sin uses the commandment as 'opportunity' (aphorme, base of operations) to produce 'every kind of coveting.' The commandment thus exposes what external compliance conceals. The identification of covetousness with idolatry (Colossians 3:5; Ephesians 5:5) connects the final commandment to the first: both address ultimate allegiance. Augustine's famous analysis saw all sin as disordered desire (concupiscentia); the tenth commandment addresses sin at this fundamental level. The commandment points toward regeneration: only transformed hearts can truly fulfill Torah's intent.",
                "reflection_prompt": "Coveting often hides beneath respectable surfaces—comparing ourselves to others, feeling entitled to more, or believing we need what someone else has to be happy. What triggers discontent in you? How might gratitude and trust in God's provision replace the craving for more?",
            },
        ]

        for day_data in days:
            ReadingPlanDay.objects.get_or_create(
                plan=template,
                day_number=day_data["day_number"],
                defaults={
                    "title": day_data["title"],
                    "scripture_references": day_data["scripture_references"],
                    "context_summary": day_data["context_summary"],
                    "commentary_beginner": day_data["commentary_beginner"],
                    "commentary_intermediate": day_data["commentary_intermediate"],
                    "commentary_advanced": day_data["commentary_advanced"],
                    "reflection_prompt": day_data["reflection_prompt"],
                }
            )

        return template
