# ==============================================================================
# File: apps/faith/management/commands/load_daniel_plan.py
# Project: Whole Life Journey - Django 5.x Personal Wellness/Journaling App
# Description: Management command to create "Daniel: Faith in Exile" reading plan
# Owner: Danny Jenkins (admin@wholelifejourney.com)
# Created: 2026-01-20
# Last Updated: 2026-01-20
# ==============================================================================
"""
Management command to create the Daniel reading plan.

Creates a 12-day reading plan through the book of Daniel:
- Days 1-6: Narratives (Daniel 1-6)
- Days 7-12: Visions (Daniel 7-12)

Each day includes:
- Context summary (who, when, setting)
- Commentary at 3 difficulty levels (Beginner, Intermediate, Advanced)
- Reflection prompts

Biblical accuracy verified. Non-denominational, Bible-based content.
"""

from django.core.management.base import BaseCommand
from apps.faith.models import ReadingPlanTemplate, ReadingPlanDay


class Command(BaseCommand):
    help = "Load Daniel: Faith in Exile reading plan"

    def handle(self, *args, **options):
        self.stdout.write("Loading Daniel reading plan...")

        template = self._create_daniel_plan()
        self.stdout.write(f"  Created: {template.title} ({template.duration_days} days)")

        self.stdout.write(self.style.SUCCESS("Daniel reading plan loaded successfully!"))

    def _create_daniel_plan(self):
        """Create Daniel: Faith in Exile reading plan."""
        template, created = ReadingPlanTemplate.objects.get_or_create(
            slug="daniel-faith-in-exile",
            defaults={
                "title": "Daniel: Faith in Exile",
                "description": "A 12-day journey through the book of Daniel, a powerful story of faith under pressure. Taken captive to Babylon as a teenager, Daniel maintained his integrity and trust in God through decades of service under pagan kings. The first half contains dramatic narratives (the fiery furnace, the lions' den), while the second half reveals apocalyptic visions pointing to God's ultimate victory. Daniel's example shows that faithful living is possible even in hostile environments.",
                "category": "book",
                "difficulty": "intermediate",
                "duration_days": 12,
                "topics": ["daniel", "exile", "babylon", "faith", "prophecy", "apocalyptic", "sovereignty", "faithfulness"],
                "series": "People of the Bible",
                "series_order": 4,
                "allowed_emails": [],
                "is_active": True,
                "is_featured": True,
            }
        )

        if not created:
            # Plan exists, skip day creation
            return template

        # Daniel reading plan days
        days = [
            {
                "day_number": 1,
                "title": "Tested and Faithful",
                "scripture_references": ["Daniel 1:1-21"],
                "context_summary": "In 605 BC, Babylon conquered Jerusalem. King Nebuchadnezzar took the best and brightest young men from Judah's nobility to serve in his court—including Daniel and his three friends. Far from home, facing immense pressure to conform to Babylonian culture, these teenagers made choices that set the course for their entire lives. The book of Daniel was likely written during the exile (6th century BC) and addresses the question: How do God's people remain faithful when surrounded by a dominant pagan culture?",
                "commentary_beginner": "When Babylon conquered Jerusalem, King Nebuchadnezzar selected the finest young men from Judah's royal families for training in his palace. Daniel and his three friends—Hananiah, Mishael, and Azariah—were among them. They were given Babylonian names (Belteshazzar, Shadrach, Meshach, and Abednego) and enrolled in a three-year program to learn Babylonian language, literature, and customs. They were even given food from the king's own table! But here's where Daniel showed remarkable courage: he 'resolved not to defile himself' with the royal food and wine. Maybe the food had been offered to idols, or maybe it violated Jewish dietary laws—the text doesn't explain. What matters is that Daniel drew a line. He asked permission to eat only vegetables and water for ten days as a test. At the end, Daniel and his friends looked healthier than the others! God honored their faithfulness, giving them exceptional wisdom and understanding. Daniel could even interpret dreams and visions. After their training, the king found them ten times better than all his other advisors.",
                "commentary_intermediate": "The opening verses set the theological framework: 'The Lord delivered' Jerusalem into Nebuchadnezzar's hand (1:2). Even in exile, God is sovereign. The young men's selection criteria (1:4) emphasize physical, intellectual, and social excellence—Babylon wanted the best. The name changes attempted to replace their Hebrew identities (containing references to Yahweh and El) with Babylonian ones (honoring Bel, Marduk, etc.). Daniel's 'resolve' (literally 'set upon his heart') represents a decision made before the pressure came. The specific reason for refusing the food isn't stated—possibilities include idol-dedication, non-kosher preparation, or symbolic rejection of total assimilation. Notably, Daniel uses diplomatic wisdom: he requests a test rather than issuing demands, working within the system while maintaining his convictions. The ten-day period and vegetable diet succeed, demonstrating God's faithfulness to those who honor Him. The summary statement (1:17-20) connects their wisdom directly to God's gift, while also noting Daniel's special ability with visions and dreams—setting up the rest of the book.",
                "commentary_advanced": "Daniel 1 establishes the book's central tension: Babylonian imperial power versus God's sovereign purposes. The Hebrew term for 'resolve' (yasem al-libbo, 1:8) indicates a deliberate, prior commitment—Daniel's decision preceded the temptation. The issue of 'defilement' (ga'al) involves ritual/covenant categories; whatever the specific concern, Daniel maintained Jewish identity within acceptable boundaries while excelling in Babylonian wisdom. The contrast with Nebuchadnezzar's 'three years' (1:5) and God's 'ten days' (1:12-14) subtly suggests divine timeline sovereignty. The literary structure creates irony: Babylon tries to remake these Jews, but God shapes them for His purposes. The term 'wisdom' (chokmah) connects Daniel to Israel's wisdom tradition; his dream-interpretation ability links him to Joseph. The book's bilingual nature (Hebrew in 1:1-2:4a, 8-12; Aramaic in 2:4b-7:28) may reflect its dual audience: the Aramaic section addresses international themes, while the Hebrew sections particularly concern Israel. Daniel and his friends become models of what Walter Brueggemann calls 'negotiating identity in empire'—participating without capitulating.",
                "reflection_prompt": "Daniel 'resolved' not to compromise before the pressure came. What decisions could you make now—before you're in the situation—about how you'll live when your faith is tested? Where might you need to draw a line while still being diplomatic and gracious?",
            },
            {
                "day_number": 2,
                "title": "The King's Dream",
                "scripture_references": ["Daniel 2:1-49"],
                "context_summary": "King Nebuchadnezzar has a troubling dream and makes an impossible demand: his advisors must tell him both the dream and its interpretation, or be executed. None of Babylon's wise men can do it. Daniel requests time, gathers his friends to pray, and God reveals the mystery. The dream describes a great statue representing successive world empires, ultimately destroyed by a stone 'not cut by human hands.' This chapter establishes a key theme: earthly kingdoms rise and fall, but God's kingdom will endure forever.",
                "commentary_beginner": "King Nebuchadnezzar had a disturbing dream that he couldn't shake. He summoned all his magicians, enchanters, and astrologers, demanding they tell him what he had dreamed AND what it meant. This was impossible! Usually, they'd hear the dream and then make up an interpretation. When they protested, the king ordered all the wise men of Babylon executed—including Daniel and his friends. Daniel asked for time and immediately gathered his friends to pray. That night, God revealed the mystery to Daniel in a vision. Daniel's prayer of thanksgiving (2:20-23) is beautiful: 'He changes times and seasons; he deposes kings and raises up others.' The dream showed a giant statue: head of gold, chest of silver, belly of bronze, legs of iron, feet of iron mixed with clay. A rock 'not cut by human hands' struck the statue and became a mountain filling the earth. Daniel explained: the head of gold was Nebuchadnezzar's Babylon. After him would come inferior kingdoms (silver, bronze, iron). But ultimately, God would establish a kingdom that would never be destroyed. Nebuchadnezzar was so impressed he fell prostrate before Daniel, acknowledging Daniel's God as 'God of gods and Lord of kings.' Daniel was promoted to rule over Babylon, and he made sure his friends received positions too.",
                "commentary_intermediate": "The king's demand creates an impossible test that exposes the limitations of pagan wisdom. The wise men's honest confession—'No one can reveal it to the king except the gods, and they do not live among humans' (2:11)—is theologically ironic: Daniel's God does reveal mysteries because He is not remote. Daniel's response to crisis shows a pattern: request time, gather community, pray, receive revelation, give God glory. His prayer-hymn (2:20-23) emphasizes God's sovereignty over history and wisdom—the very things Babylon claimed for its gods and kings. The statue vision uses a common ancient motif of declining ages (gold to silver to bronze to iron), but Daniel transforms it theologically: human empires progressively weaken and will ultimately be replaced by God's eternal kingdom. The 'stone not cut by human hands' indicates divine, not human, origin. Traditional interpretation identifies the kingdoms as Babylon, Medo-Persia, Greece, and Rome, with God's kingdom established through Christ. Daniel's interpretation demonstrates extraordinary courage: he tells the most powerful man on earth that his kingdom will fall. The chapter ends with pagan acknowledgment of Israel's God—a recurring pattern in Daniel.",
                "commentary_advanced": "Daniel 2 introduces apocalyptic literature's 'four kingdom' schema that reappears in chapter 7. The narrative structure follows a court conflict pattern: crisis, hero's intervention, success, promotion. The Aramaic term 'raz' (mystery, 2:18-19, 27-30, 47) becomes important in later Jewish and Christian usage. Daniel's prayer combines hymnic elements (doxology, divine attributes) with thanksgiving for specific revelation. The metals' decreasing value but increasing hardness may symbolize declining glory but growing brutality. The iron-clay mixture (2:43) suggests inherent instability—'they will not remain united.' The 'stone' (eben) destroying human empires and becoming a 'great mountain' (tur rab) echoes Isaianic imagery (Isaiah 2:2-4) of God's end-time kingdom. The phrase 'not cut by human hands' (di-la biyedayin, 2:34, 45) emphasizes supernatural origin. Nebuchadnezzar's prostration and offering to Daniel (2:46) is shocking—a Jewish exile receiving quasi-divine honors from Babylon's king. This reversal of expected power dynamics anticipates the book's climax. The identification of specific kingdoms remains debated; some see Media as a separate kingdom, affecting the schema's application.",
                "reflection_prompt": "When faced with an impossible situation, Daniel's first response was to gather his friends and pray. How do you respond to crises? What role does community prayer play in your life when you face overwhelming challenges?",
            },
            {
                "day_number": 3,
                "title": "The Fiery Furnace",
                "scripture_references": ["Daniel 3:1-30"],
                "context_summary": "Nebuchadnezzar constructs a ninety-foot golden statue and commands everyone to bow down and worship it. Daniel's three friends—Shadrach, Meshach, and Abednego—refuse. Their defiance enrages the king, who heats a furnace seven times hotter than normal and has them thrown in. But instead of death, they encounter deliverance—and a mysterious fourth figure walking with them in the flames.",
                "commentary_beginner": "King Nebuchadnezzar made an enormous golden statue—ninety feet tall!—and commanded everyone to bow down when music played. Anyone who refused would be thrown into a blazing furnace. Some jealous officials reported that three Jews—Shadrach, Meshach, and Abednego—refused to worship the image. (Where was Daniel? The text doesn't say—perhaps on business elsewhere.) Nebuchadnezzar was furious. He gave them one more chance: bow down or burn. Their answer is one of the most courageous statements in Scripture: 'The God we serve is able to deliver us... But even if he does not, we want you to know that we will not serve your gods or worship the image' (3:17-18). Even if God doesn't rescue us, we still won't bow. The king ordered the furnace heated seven times hotter. The soldiers who threw them in died from the heat. But then Nebuchadnezzar leaped up in amazement: 'Weren't there three men? I see four walking around in the fire, unbound and unharmed, and the fourth looks like a son of the gods!' He called them out. Not a hair was singed; they didn't even smell like smoke! The king blessed their God and promoted them, decreeing that no one could speak against their God.",
                "commentary_intermediate": "The ninety-foot statue (60 cubits high, 6 wide) may represent Nebuchadnezzar's attempt to unify his diverse empire through shared worship. The musical ensemble listing (3:5, 7, 10, 15) emphasizes the coordinated, imperial nature of this worship. The accusation against the Jews uses loaded language: 'pay no attention to you' (3:12) suggests not just religious nonconformity but political disloyalty. The friends' response (3:16-18) contains profound theology: God is able to deliver, but they don't presume on His methods. Their 'even if not' faith doesn't manipulate God with expected outcomes. The sevenfold heating demonstrates both the king's fury and the miracle's magnitude—the executioners die but the condemned live. The 'fourth figure' is described by the pagan king as 'like a son of the gods' (3:25)—his theological categories are limited, but he recognizes something supernatural. Many Christians see this as a pre-incarnate appearance of Christ (a 'Christophany'). The three men emerge without even the smell of fire—complete deliverance. Nebuchadnezzar's decree (3:29) is not conversion but acknowledgment of power. The chapter models both the reality of persecution and the possibility of divine deliverance, while affirming that faithfulness doesn't depend on deliverance.",
                "commentary_advanced": "The statue's dimensions (60x6 cubits) may carry symbolic significance; some note the absence of the number 7 (perfection) in contrast to God's works. The musical instruments listed include several Greek loanwords, which some scholars cite as evidence for late dating; others explain them as terms for Greek instruments known in 6th-century Babylon through trade. The accusation formula 'they pay no attention to you, O king' (la samū 'alak malka, 3:12) is politically charged—religious nonconformity equals lèse-majesté. The theological statement in 3:17-18 employs conditional clauses ('if... if not') that preserve both divine sovereignty and human uncertainty about outcomes. This models faith that trusts God's character regardless of circumstances. The phrase 'like a son of the gods' (kebar 'elahin, 3:25) uses Aramaic vocabulary that Nebuchadnezzar would understand as a divine or angelic being. The Christian interpretation as Christ finds support in the pattern of God's presence with His people in trial (Isaiah 43:2). The preservation of the trio—clothing intact, no smoke smell—demonstrates comprehensive deliverance. The chapter functions as paradigm for the faithful community facing imperial pressure: resistance may bring suffering, but God accompanies His people and may deliver them, though that deliverance is not guaranteed or manipulable.",
                "reflection_prompt": "'Even if He does not deliver us, we will not bow.' This is faith that doesn't depend on outcomes. How do you maintain faithfulness when you can't see how God will work? What would 'even if not' faith look like in your current circumstances?",
            },
            {
                "day_number": 4,
                "title": "The King's Humiliation",
                "scripture_references": ["Daniel 4:1-37"],
                "context_summary": "This unique chapter is narrated by Nebuchadnezzar himself—a pagan king testifying to God's power. After a disturbing dream about a great tree being cut down, Daniel interprets it as a warning: unless the king humbles himself, he will be driven mad and live like an animal. When Nebuchadnezzar fails to heed the warning, the prophecy comes true. After seven years of madness, he looks to heaven, acknowledges God's sovereignty, and is restored.",
                "commentary_beginner": "This chapter is remarkable—it's told from Nebuchadnezzar's perspective! The mighty king is writing to tell everyone what the Most High God has done. He had a terrifying dream: a giant tree that reached to heaven was ordered cut down, with only the stump remaining. The person represented by the tree would live like an animal for 'seven times' (probably seven years). When Daniel heard the dream, he was troubled—the interpretation meant bad news for the king. Daniel urged Nebuchadnezzar to renounce his sins and show kindness to the oppressed, perhaps then the disaster would be averted. Twelve months later, the king was walking on his palace roof, admiring his great Babylon. 'Is not this the great Babylon I have built by my mighty power and for the glory of my majesty?' (4:30). Immediately a voice from heaven announced judgment. The king went mad, was driven from people, ate grass like cattle, and grew hair and nails like claws. For seven years he lived as an animal. Then 'I, Nebuchadnezzar, raised my eyes toward heaven, and my sanity was restored' (4:34). He praised the Most High, acknowledging that God's dominion is eternal and 'He does as He pleases with the powers of heaven.' The king was restored to his throne with even greater honor. His final words: 'Those who walk in pride He is able to humble' (4:37).",
                "commentary_intermediate": "The chapter's epistolary frame (4:1-3, 34-37) presents Nebuchadnezzar's personal testimony—unique in Scripture. The tree vision draws on widespread ancient Near Eastern imagery of the cosmic tree (cf. Ezekiel 31). The decree to leave the stump 'with its roots' (4:15) hints at hope for restoration. The 'seven times' probably indicates seven years, emphasizing complete divine judgment. Daniel's reaction—troubled for an hour, wishing the dream applied to enemies instead (4:19)—shows genuine care for the king despite his paganism. The counsel to 'renounce sins by doing what is right' (4:27) reflects prophetic calls to repentance (cf. Isaiah 58). The twelve-month delay suggests grace period for response. The king's boastful speech (4:30) triggers immediate fulfillment, illustrating the principle that 'pride goes before destruction' (Proverbs 16:18). The condition described resembles boanthropy—a psychological disorder where one believes oneself to be an animal. Some Babylonian texts may reference Nebuchadnezzar's absence from public life. The turning point comes when Nebuchadnezzar 'raised his eyes toward heaven' (4:34)—physical posture reflecting spiritual reorientation. His restoration exceeds his former state (4:36), demonstrating that humility before God leads to true greatness.",
                "commentary_advanced": "Daniel 4 functions as a 'conversion narrative' for Nebuchadnezzar, structured around the theme of divine sovereignty humbling human pride. The Aramaic term 'watchers' (irim, 4:13, 17, 23) for angelic beings appears only here in the Hebrew Bible but is common in later Jewish literature (1 Enoch). The 'band of iron and bronze' around the stump (4:15, 23) has been variously interpreted: protection of the remnant, restraint during madness, or metaphor for the condition's severity. The seven times/years represents complete divine action. The phrase 'Heaven rules' (4:26) is the only place in the Old Testament where 'Heaven' substitutes for God's name—a practice common in later Judaism and the New Testament ('kingdom of heaven'). The king's boast (4:30) parodies the Babel narrative (Genesis 11); Babylon represents human autonomy against God. The condition's public nature—living with wild animals, dew-soaked body, eagle-like hair and bird-like nails (4:33)—systematically strips away royal dignity. Historical evidence for this period in Nebuchadnezzar's reign is limited; the Prayer of Nabonidus from Qumran describes a similar affliction for a later Babylonian king, leading some scholars to see tradition conflation. The restoration formula emphasizes that true sovereignty comes from submission to the Most High. Nebuchadnezzar's doxology (4:34-35) matches genuine Old Testament theology, raising questions about the depth of his conversion.",
                "reflection_prompt": "Nebuchadnezzar's pride led to his downfall; his humility led to restoration. Where might pride be creeping into your heart—taking credit for what God has done, or believing you've achieved things by your own power? What would it look like to 'raise your eyes to heaven'?",
            },
            {
                "day_number": 5,
                "title": "The Writing on the Wall",
                "scripture_references": ["Daniel 5:1-31"],
                "context_summary": "Decades have passed. Nebuchadnezzar is dead, and Belshazzar now rules Babylon. During a great feast, Belshazzar desecrates the sacred vessels from Jerusalem's temple by drinking wine from them while praising Babylonian gods. Suddenly, a mysterious hand appears and writes on the wall. None of Babylon's wise men can read it. Daniel, now elderly, is summoned and delivers God's judgment: Babylon will fall that very night. By morning, Belshazzar is dead and the Persians have conquered the city.",
                "commentary_beginner": "King Belshazzar threw a huge party for a thousand nobles. In a shocking act of arrogance, he ordered the gold and silver cups taken from Jerusalem's temple brought in so they could drink from them while praising their gods. Suddenly, a human hand appeared and wrote mysterious words on the wall. The king was terrified—his face turned pale and his knees knocked together! None of his wise men could read or interpret the writing. The queen mother remembered Daniel and told Belshazzar about him. Daniel was brought in, now an old man. He refused the king's rewards but agreed to interpret the writing. First, Daniel reminded Belshazzar about Nebuchadnezzar's humbling—a lesson Belshazzar knew but ignored. 'You have set yourself up against the Lord of heaven' by desecrating the temple vessels (5:23). The writing said: MENE, MENE, TEKEL, PARSIN. Daniel interpreted: MENE—God has numbered your kingdom's days; TEKEL—you have been weighed and found wanting; PARSIN—your kingdom is divided and given to the Medes and Persians. That very night, Belshazzar was killed, and Darius the Mede took over the kingdom. The kingdom that seemed invincible fell in a single night.",
                "commentary_intermediate": "Historical records indicate Belshazzar was regent while his father Nabonidus was absent, explaining why he offers Daniel the 'third highest' position (5:7, 16, 29)—he himself was second. The desecration of temple vessels (5:2-4) represents not just sacrilege but deliberate defiance of Yahweh. The mysterious hand writing (5:5) creates supernatural terror; Belshazzar's physical reaction (pale face, loose joints, knocking knees) emphasizes the loss of royal composure. The queen mother (likely Nebuchadnezzar's widow) remembers Daniel—suggesting he had been overlooked in the new administration. Daniel's refusal of rewards (5:17) differs from his acceptance in chapter 2, perhaps reflecting his assessment of Belshazzar's character or the imminence of judgment. His rehearsal of Nebuchadnezzar's story (5:18-21) emphasizes that Belshazzar knew this history but 'did not humble yourself' (5:22). The writing's words are Aramaic terms for weights/monetary units: MENE (mina), TEKEL (shekel), PARSIN (half-minas). Daniel transforms them into verbs: numbered, weighed, divided. The wordplay on PARSIN/Persians is intentional. Greek historian Herodotus and other sources describe the Persian capture of Babylon by diverting the Euphrates River and entering through the riverbed—the city fell with stunning speed. The transition from Babylon to Persia shifts world empire, as Daniel's earlier visions predicted.",
                "commentary_advanced": "The Nabonidus Chronicle and other cuneiform sources provide historical context: Nabonidus, the actual king, was absent; his son Belshazzar (Bel-shar-usur) governed as regent. The feast's timing during a siege (if the Persians were already at the walls) would emphasize either Babylonian overconfidence or Belshazzar's desperate denial. The temple vessel desecration (5:2-4) violates ancient Near Eastern conventions about respecting conquered gods' property; even by Mesopotamian standards, this was impious. The hand writing 'near the lampstand' (5:5) places it in optimal visibility. The Aramaic nouns MENE, TEKEL, PERES (singular of PARSIN) function as wordplays: (1) as weights—mina, shekel, half-mina; (2) as verbs—numbered, weighed, divided; (3) as political reference—Media, Persia (or perhaps mina = king, shekel = prince, divided kingdom). The phrase 'weighed in the balances' (5:27) uses judgment imagery common in Egyptian and Mesopotamian religion—but here Yahweh does the weighing. The identification of 'Darius the Mede' (5:31) remains historically problematic; some identify him with Gubaru (a governor), Cyrus himself, or see the account as conflating traditions. The chapter's theological message is clear: God judges nations that defy Him, and kingdom transitions occur by His decree, not merely by military power.",
                "reflection_prompt": "Belshazzar knew his grandfather's story but 'did not humble himself.' Knowledge without obedience brings greater accountability. Is there truth you know but haven't acted on? What lesson from others' experiences have you been ignoring?",
            },
            {
                "day_number": 6,
                "title": "The Lions' Den",
                "scripture_references": ["Daniel 6:1-28"],
                "context_summary": "The Persian Empire has replaced Babylon, but Daniel's excellence continues. Now serving under Darius, Daniel's success provokes jealousy among the other administrators. They devise a trap: convince the king to decree that for thirty days, prayer to anyone except the king is punishable by death. Daniel, knowing the decree, continues his pattern of prayer—and is thrown to the lions. But God sends an angel to shut the lions' mouths.",
                "commentary_beginner": "Under the new Persian government, Daniel was appointed one of three chief administrators. He was so exceptional that King Darius planned to put him in charge of the entire kingdom. This made the other administrators jealous. They tried to find something wrong with Daniel's work, but they couldn't—'he was trustworthy and neither corrupt nor negligent' (6:4). So they decided to trap him through his faith. They convinced Darius to sign a law: for thirty days, anyone who prayed to any god or man except the king would be thrown to the lions. The law couldn't be changed—not even by the king. When Daniel heard about the decree, he went home, opened his windows toward Jerusalem, and prayed three times a day—just as he had always done. He didn't hide or stop. The officials caught him and reported to the king. Darius was devastated—he liked Daniel!—and tried all day to find a loophole, but he couldn't. Daniel was thrown into the lions' den. The king couldn't sleep that night. At first light, he rushed to the den: 'Daniel, servant of the living God, has your God been able to rescue you?' Daniel answered! 'My God sent his angel, and he shut the mouths of the lions. I was found innocent.' Darius had Daniel lifted out—without a scratch. Then he threw the accusers into the den, and they were killed before they hit the ground.",
                "commentary_intermediate": "The chapter's structure parallels chapter 3: jealous officials, impossible decree, faithful resistance, miraculous deliverance, pagan king's acknowledgment. Daniel's excellence (6:3) uses a term suggesting he was 'distinguished' by an exceptional spirit—the same quality noted in chapters 1, 4, and 5. The officials' admission that the only accusation possible relates to 'the law of his God' (6:5) is high praise indeed. The thirty-day restriction on prayer, presented as honoring the king, may have political motivation—consolidating Darius's authority in newly conquered territory. Daniel's continued prayer toward Jerusalem (6:10) reflects Solomon's prayer at the temple's dedication (1 Kings 8:46-50) and the practice of diaspora Jews. His open windows demonstrate that he neither hid nor flaunted his practice—he simply continued his faithful pattern. Darius's distress (6:14) and sleepless night (6:18) show genuine care for Daniel. His greeting at dawn—'servant of the living God'—already reflects changed theology. Daniel's explanation emphasizes innocence before both God and king (6:22); his resistance was not rebellion but faithfulness. The accusers' death (6:24) follows ancient Near Eastern justice (cf. Esther 7:10). Darius's decree (6:26-27) goes beyond Nebuchadnezzar's acknowledgments—he commands reverence for Daniel's God and describes Him as the 'living God' whose kingdom endures.",
                "commentary_advanced": "The historical setting during 'Darius the Mede' (6:1) remains debated; see discussion at chapter 5. The administrative structure (120 satraps, 3 chief administrators) roughly corresponds to Persian governmental practice, though details vary in sources. The irrevocable nature of Persian law (6:8, 12, 15) is referenced in Esther 1:19 and 8:8; some scholars question whether this was actual practice or literary convention emphasizing the impossibility of human rescue. Daniel's prayer practice 'just as he had done before' (6:10) demonstrates that his faithfulness wasn't a response to persecution but a continuation of lifelong habit—crisis reveals character formed beforehand. The phrase 'windows opened toward Jerusalem' (6:10) may allude to 1 Kings 8:48 and shows orientation toward the temple and homeland. The sealed stone (6:17) anticipates another sealed stone before a death chamber (Matthew 27:66). Daniel's survival among the lions while the accusers die instantly confirms divine intervention—the lions weren't sated. Darius's decree (6:26-27) forms the climax of the book's first half: a pagan emperor commands universal reverence for Daniel's God, who 'rescues and saves; he performs signs and wonders in the heavens and on the earth.' The chapter models faithful resistance that respects governmental authority when possible while maintaining ultimate allegiance to God.",
                "reflection_prompt": "Daniel's prayer life was already established before the crisis came. When pressure came, he simply continued what he'd always done. What spiritual habits are you building now that will sustain you when challenges arise? What would it look like to pray 'just as you have done before' when opposition comes?",
            },
            {
                "day_number": 7,
                "title": "Four Beasts and the Ancient of Days",
                "scripture_references": ["Daniel 7:1-28"],
                "context_summary": "The second half of Daniel shifts from narrative to apocalyptic visions. In this foundational chapter, Daniel sees four terrifying beasts rising from the sea—representing world empires. But then the scene shifts to heaven's throne room, where the 'Ancient of Days' sits in judgment. One 'like a son of man' approaches and receives eternal dominion over all peoples. This chapter profoundly influenced later Jewish and Christian understanding of God's kingdom and the Messiah.",
                "commentary_beginner": "This vision happened earlier in Daniel's life—during Belshazzar's first year. Daniel saw four great beasts coming out of a churning sea. The first was like a lion with eagle's wings. The second was a bear raised up on one side, with ribs in its mouth. The third was like a leopard with four wings and four heads. The fourth was terrifying beyond description—with iron teeth, bronze claws, and ten horns. These beasts represent kingdoms (just like the statue in chapter 2). But then the scene changed to heaven. Daniel saw the 'Ancient of Days'—God Himself on His throne. His clothing was white as snow, His hair like pure wool. Flames surrounded His throne, and thousands upon thousands attended Him. Court was in session, and judgment was pronounced. The fourth beast was destroyed. Then someone 'like a son of man' came on the clouds of heaven and approached the Ancient of Days. He was given authority, glory, and sovereign power. 'All nations and peoples of every language worshiped him. His dominion is an everlasting dominion that will not pass away' (7:14). Daniel was troubled by all this. An angel explained that the beasts are four kingdoms, but 'the holy people of the Most High will receive the kingdom and possess it forever.' Though a terrifying king (represented by the horn with eyes and a boastful mouth) will persecute the saints for a time, ultimately God's kingdom will triumph.",
                "commentary_intermediate": "Daniel 7 parallels chapter 2 but shifts perspective from external appearance (statue) to inner character (beasts). The 'great sea' (7:2) represents chaos and opposition to God in ancient Near Eastern mythology. The four beasts are generally identified: lion with wings = Babylon (cf. Jeremiah 4:7, 49:19-22); bear = Medo-Persia (raised side = Persia's dominance); leopard with four heads = Greece (four heads = Alexander's successors); terrifying beast = Rome (or, in some interpretations, the Seleucid Empire). The 'little horn' (7:8) with eyes and boasting mouth represents a specific oppressive king—often identified as Antiochus IV Epiphanes (who desecrated the temple in 167 BC) or a future antichrist figure. The 'Ancient of Days' vision (7:9-10) provides Scripture's most detailed throne room scene. White garments and hair symbolize purity and eternity. The 'son of man' figure (7:13-14) is deliberately mysterious—he is human-like ('like a son of man') yet rides the clouds (a divine prerogative in ancient Near Eastern thought) and receives universal worship. Jesus's self-designation as 'Son of Man' draws directly from this passage, as does His response at His trial (Mark 14:62). The 'time, times and half a time' (7:25) likely means 3.5 years—half of seven, symbolizing a broken or incomplete period of tribulation.",
                "commentary_advanced": "Daniel 7 is foundational for apocalyptic literature and New Testament Christology. The Aramaic 'bar enash' (son of man, 7:13) functions as both a human designation (unlike the beasts) and, through the cloud-riding imagery, as a divine figure. The phrase 'one like a son of man' maintains ambiguity—he resembles a human yet receives worship. Jewish interpretation debated whether this figure is corporate (representing Israel) or individual (messianic). Jesus's use of 'Son of Man' as His primary self-designation drew on this passage, combining human and divine aspects. The 'saints of the Most High' (7:18, 21-22, 25, 27) who receive the kingdom could be angels, Israel, or faithful Jews; the term's ambiguity may be intentional, as human and divine communities collaborate in God's purposes. The 'little horn' making war against the saints 'until the Ancient of Days came' (7:21-22) establishes a pattern: tribulation precedes vindication. The numerical symbolism (ten horns, three uprooted, time/times/half-time) invites interpretive engagement while resisting precise decoding. The chapter's literary structure moves from threat (beasts) to hope (divine throne) to vindication (son of man's reception of eternal dominion), providing the interpretive framework for apocalyptic expectation. This vision shapes both Jesus's teaching and Revelation's imagery.",
                "reflection_prompt": "Daniel saw terrifying powers rising and falling, but the vision climaxes with God's throne and the triumph of His kingdom. When you look at powerful forces in today's world, how does this vision of God's ultimate victory shape your perspective? What does it mean that 'the holy people of the Most High will receive the kingdom'?",
            },
            {
                "day_number": 8,
                "title": "The Ram and the Goat",
                "scripture_references": ["Daniel 8:1-27"],
                "context_summary": "Two years after the vision of chapter 7, Daniel receives another vision—this time in Hebrew rather than Aramaic, signaling its particular relevance to Israel. A ram with two horns (Medo-Persia) is attacked by a goat with a prominent horn (Greece/Alexander). The goat's horn breaks and is replaced by four horns, from which emerges a small horn who desecrates the temple. This prophecy finds striking fulfillment in Antiochus IV Epiphanes, whose persecution sparked the Maccabean revolt.",
                "commentary_beginner": "In this vision, Daniel saw a ram with two horns standing by a river. The ram was powerful, charging west, north, and south—no animal could stand against it. Then a goat came from the west, so fast its feet didn't touch the ground. It had a prominent horn between its eyes. The goat attacked the ram furiously and shattered its horns. The goat became very great, but at the height of its power, the large horn broke off and four smaller horns grew in its place. From one of these came a 'little horn' that grew toward the south, east, and the Beautiful Land (Israel). It grew until it reached the heavens, threw down some of the starry host, and set itself up against the 'Prince of the host.' It stopped the daily sacrifices and desecrated the sanctuary. The angel Gabriel explained: the ram is Medo-Persia; the goat is Greece; the large horn is the first king (Alexander the Great); the four horns are the kingdoms that replaced his empire. The little horn is a fierce king who will cause devastation and destroy the 'holy people,' but 'he will be destroyed, but not by human power' (8:25). Daniel was exhausted and ill for days after this vision. He was appalled by it and didn't understand it.",
                "commentary_intermediate": "The switch from Aramaic to Hebrew in chapter 8 signals material particularly relevant to the Jewish community. The two-horned ram (8:3-4) is explicitly identified as Medo-Persia (8:20); the higher horn rising later = Persia's eventual dominance over Media. The goat from the west with the conspicuous horn (8:5-8) is Greece/Alexander (8:21); his swift conquest (feet not touching ground) captured the Persian Empire in just over a decade (334-323 BC). Alexander's death at 32 ('at the height of its power') and the division of his empire among four generals ('four prominent horns,' 8:8, 22) is remarkably specific. The 'little horn' (8:9-12, 23-25) finds precise historical fulfillment in Antiochus IV Epiphanes (175-164 BC), who: (1) attacked Egypt (south), (2) attacked Palestine (Beautiful Land), (3) claimed divine honors (reaching toward heaven), (4) stopped temple sacrifices, (5) desecrated the sanctuary. The '2,300 evenings and mornings' (8:14) likely refers to 1,150 days of suspended sacrifice—approximately the period of Antiochus's desecration (167-164 BC). The temple's 'reconsecration' (8:14) was celebrated as Hanukkah. Gabriel's instruction to 'seal up the vision' (8:26) indicates its fulfillment lies in the distant future (from Daniel's perspective). The historical precision has led critical scholars to date the book to the Maccabean period; traditional interpretation sees genuine prophecy.",
                "commentary_advanced": "Daniel 8 provides the most historically specific vision in the book, with explicit naming of Medo-Persia and Greece. The geographical detail ('Ulai canal,' 8:2) places Daniel in the Persian capital of Susa—whether in vision or in person. The horn imagery connects to chapter 7's horn symbolism. The 'little horn' here (8:9) differs from chapter 7's little horn; the two may represent the same pattern in different imperial contexts (Seleucid vs. Roman, or Antiochus as type of Antichrist). The phrase 'master of intrigue' (8:23, mebin chidot) characterizes Antiochus's deceptive diplomacy. His persecution of 'the mighty ones and the holy people' (8:24) aligns with 1-2 Maccabees' accounts. The 2,300 'evenings and mornings' has been interpreted as: (1) 2,300 days, (2) 1,150 days (representing evening and morning sacrifices), or (3) symbolic of incomplete time. Gabriel's appearance as interpreter (8:16) is significant—this is the first biblical naming of an angel (Gabriel appears again in 9:21 and in the Gospels). The instruction that the vision concerns 'the time of the end' (8:17, 19) creates tension with historical fulfillment in Antiochus, leading some to see double fulfillment—Antiochus as type and a future figure as antitype. Daniel's physical collapse (8:27) demonstrates the overwhelming nature of apocalyptic revelation.",
                "reflection_prompt": "This prophecy found precise fulfillment in events 400 years after Daniel. What does such accurate prophecy tell you about God's knowledge and sovereignty over history? How does knowing that God has already revealed history's trajectory affect your trust in Him for your own future?",
            },
            {
                "day_number": 9,
                "title": "Daniel's Prayer and the Seventy Weeks",
                "scripture_references": ["Daniel 9:1-27"],
                "context_summary": "This chapter records one of Scripture's most powerful prayers and one of its most debated prophecies. Daniel, now elderly, discovers in Jeremiah that Jerusalem's desolation was to last seventy years. Rather than just waiting, he responds with intense prayer—confession, petition, and appeal to God's character. The angel Gabriel then reveals the prophecy of 'seventy weeks'—a timeline pointing to both the coming of an 'Anointed One' and future tribulation.",
                "commentary_beginner": "Daniel was reading the prophet Jeremiah and discovered that Jerusalem would be desolate for seventy years (Jeremiah 25:11-12, 29:10). Realizing the time was almost complete, Daniel didn't just wait—he prayed! His prayer (9:4-19) is a model of confession and petition. He acknowledged Israel's sin: 'We have sinned and done wrong... we have not listened to your servants the prophets.' He didn't blame others but identified with his people: 'We have sinned.' He appealed to God's character: His righteousness, mercy, and the fact that Israel bore His name. 'We do not make requests because we are righteous, but because of your great mercy.' While Daniel was still praying, Gabriel came to him. Gabriel told him about 'seventy sevens' (usually understood as seventy weeks of years, or 490 years). This period would accomplish six things: to finish transgression, to put an end to sin, to atone for wickedness, to bring in everlasting righteousness, to seal up vision and prophecy, and to anoint the Most Holy Place. An 'Anointed One' (Messiah) would come, but would be 'cut off.' The city and sanctuary would be destroyed, and there would be war and desolation. This prophecy is famously difficult, but it clearly points to Christ's coming and His rejection, and perhaps to future events as well.",
                "commentary_intermediate": "Daniel's discovery of Jeremiah's prophecy (9:2) shows that prophets studied earlier prophets—Scripture interprets Scripture. But knowledge prompted prayer, not passive waiting. Daniel's prayer follows the pattern of great intercessors (Moses, Solomon, Ezra, Nehemiah): acknowledgment of God's covenant faithfulness, confession of national sin, appeal to God's reputation, and plea for mercy. Note the repeated corporate language: 'we have sinned' (9:5, 8, 11, 15). The confession is specific: they violated Torah, ignored prophets, and deserve the curses Moses warned about (9:11-13). The appeal to God's 'great mercies' (9:18) rather than human righteousness is theologically crucial. Gabriel's arrival 'in swift flight' at the time of evening sacrifice (9:21) connects to temple worship. The 'seventy sevens' builds on Jeremiah's seventy years—a sabbatical principle (Leviticus 26:34-35). The timeline is debated, but many see: 7 weeks (49 years) for Jerusalem's rebuilding; 62 weeks (434 years) until an 'Anointed One'; then the Anointed One is 'cut off' (killed); and 1 final week of tribulation (perhaps divided in half). If the decree is Artaxerxes' in 458 or 445 BC, the 483 years reach approximately to Christ's ministry. The destruction of 'city and sanctuary' (9:26) was fulfilled in 70 AD. The final week remains debated—fulfilled in the first century or yet future.",
                "commentary_advanced": "Daniel 9 combines exemplary prayer with notoriously complex prophecy. The prayer's language echoes Deuteronomy's covenant curses (cf. Daniel 9:11-13 with Deuteronomy 28-30) and parallels Solomon's temple prayer (1 Kings 8). The phrase 'seventy sevens' (shabua' shiv'im, 9:24) uses the term for 'week' but clearly means units of seven years, multiplying Jeremiah's seventy years by seven. The six purposes (9:24) describe comprehensive redemption: negative (ending transgression, sin, wickedness) and positive (righteousness, prophecy's fulfillment, Most Holy anointing). The 'Anointed One' (mashiach) appears twice (9:25-26); whether these are the same figure or different (e.g., a priestly figure and a kingly one) is debated. The 'cutting off' (yikkaret, 9:26) uses covenant language for death/destruction. The 'he' in 9:27 who makes and breaks a covenant is ambiguous—is it the Messiah or the destroyer? Christian interpretations have varied: (1) fulfilled entirely in Christ and the first-century destruction of Jerusalem; (2) gap between the 69th and 70th weeks, with the 70th week still future (dispensationalism); (3) continuous fulfillment through church history (historicism). The precision of some calculations (e.g., Sir Robert Anderson's calculation reaching exactly to Jesus's triumphal entry) is intriguing but depends on disputed assumptions about the starting date and calendar used. The chapter's theological message transcends chronological debates: God's plan includes both redemption and judgment, with Messiah's coming as the pivot.",
                "reflection_prompt": "Daniel's response to prophetic truth was prayer—intense, confessing, God-centered prayer. When you learn something from Scripture, does it prompt you to pray? What aspects of Daniel's prayer—his confession, his humility, his appeal to God's character—could shape your own prayer life?",
            },
            {
                "day_number": 10,
                "title": "Spiritual Warfare",
                "scripture_references": ["Daniel 10:1-21"],
                "context_summary": "Daniel's final vision begins with a stunning encounter. After three weeks of mourning and fasting, Daniel sees a glorious figure—so overwhelming that his companions flee and Daniel himself loses all strength. This heavenly messenger reveals that he was delayed twenty-one days by 'the prince of the Persian kingdom' until Michael came to help. This chapter provides one of Scripture's clearest windows into the reality of spiritual warfare behind earthly events.",
                "commentary_beginner": "In the third year of Cyrus king of Persia, Daniel received a final revelation. He had been mourning and fasting for three weeks—no choice food, no meat, no wine, no lotions. Then, standing by the Tigris River, he saw a man dressed in linen, with a belt of fine gold. His body was like topaz, his face like lightning, his eyes like flaming torches, his arms and legs like burnished bronze, and his voice like the sound of a multitude. Daniel alone saw the vision—his companions felt such terror they fled and hid. Daniel himself lost all strength; he turned pale and fell into a deep sleep with his face to the ground. A hand touched him and set him trembling on hands and knees. The messenger told Daniel he was 'highly esteemed' and should stand up. He explained his delay: 'The prince of the Persian kingdom resisted me twenty-one days. Then Michael, one of the chief princes, came to help me.' He was referring to a spiritual battle! Evil spiritual powers influence nations, but God's angels fight against them. The messenger came to explain 'what will happen to your people in the latter days' and would return to fight the prince of Persia. 'No one supports me against them except Michael, your prince' (10:21). There's a real spiritual battle happening that we can't see.",
                "commentary_intermediate": "The vision's timing—Cyrus's third year (536 BC)—places it after the first return of exiles to Jerusalem. Daniel's three weeks of mourning may relate to concern for the returnees or preparation for revelation. The glorious figure (10:5-6) is described similarly to the 'son of man' in 7:13 and shares features with Christ in Revelation 1:12-16, leading some to see this as Christ; others distinguish this messenger (who needs Michael's help) from Christ. Daniel's reaction—overwhelming weakness—echoes similar experiences (Isaiah 6:5, Ezekiel 1:28, Revelation 1:17). The twenty-one day delay reveals that heavenly messengers can be opposed by powerful spiritual beings. The 'prince of Persia' is not the human king but a demonic power influencing that empire. Michael is identified as 'one of the chief princes' (10:13) and later as 'your prince' (10:21) and 'the great prince who protects your people' (12:1). This hierarchy of angels and demons suggests organized spiritual conflict over nations and peoples. The messenger's statement that he will return to fight the prince of Persia, 'and when I go, the prince of Greece will come' (10:20), shows ongoing spiritual struggle as empires transition. Daniel's experience—receiving revelation while aware of its toll—mirrors prophetic experience throughout Scripture.",
                "commentary_advanced": "Daniel 10 provides the most explicit Old Testament description of cosmic conflict influencing history. The glorious figure's description (10:5-6) employs theophanic language (cf. Ezekiel 1, 8:2) using elements of divine appearance: linen (priestly), lightning, fire, bronze. Whether this is a christophany or an exalted angel is debated; the figure's need for Michael's help (10:13) suggests the latter, unless one distinguishes this figure from the 'one like a son of man' in 10:16, 18. Daniel's physical response—loss of strength, deep sleep, trembling—follows the pattern of prophetic commissioning experiences. The 'prince of Persia' (sar-malkhut paras, 10:13, 20) introduces the concept of territorial spirits—angelic beings, apparently fallen, who exercise influence over nations. This concept appears in Deuteronomy 32:8-9 (LXX: 'according to the number of the angels of God') and informs New Testament understanding of 'rulers,' 'authorities,' and 'powers' (Ephesians 6:12). Michael's identification as 'one of the chief princes' (10:13), later 'the great prince who protects your people' (12:1), establishes his special relationship to Israel—he is Israel's guardian angel. The twenty-one day conflict (matching Daniel's twenty-one days of prayer) suggests human intercession relates to angelic warfare. The revelation that comes in chapters 11-12 concerns 'the latter days' (10:14)—Israel's future under God's sovereignty despite appearances.",
                "reflection_prompt": "Daniel's prayer and fasting connected to spiritual warfare happening in unseen realms. How does knowing there's a real spiritual dimension to events change how you view world events, national situations, or personal struggles? How should this reality shape your prayer life?",
            },
            {
                "day_number": 11,
                "title": "Wars and Prophecy",
                "scripture_references": ["Daniel 11:1-45"],
                "context_summary": "This chapter contains the most detailed prophecy in Scripture, tracing conflicts between powers 'north' and 'south' of Israel. Much of it corresponds precisely to the wars between the Ptolemaic (Egypt) and Seleucid (Syria) kingdoms in the centuries following Alexander's death. The prophecy climaxes with a figure who desecrates the temple and exalts himself above every god—descriptions partially fulfilled in Antiochus IV but pointing beyond to an ultimate 'man of lawlessness.'",
                "commentary_beginner": "The angel continued revealing what would happen. First, four more Persian kings, then a mighty Greek king (Alexander) whose kingdom would be divided but 'not to his own descendants.' Then comes detailed prophecy about the 'king of the South' (Egypt's Ptolemaic rulers) and the 'king of the North' (Syria's Seleucid rulers) fighting over 'the Beautiful Land' (Israel). These prophecies correspond remarkably to history from about 323-164 BC—marriages, betrayals, battles, and alliances that actually happened. The focus intensifies on a 'contemptible person' (11:21) who gains power through intrigue, invades the south, and sets himself against 'the holy covenant.' He will 'desecrate the temple fortress and abolish the daily sacrifice. Then they will set up the abomination that causes desolation' (11:31). Some will fall away, but 'those who are wise will instruct many' and some will die as martyrs. This describes Antiochus IV Epiphanes (175-164 BC), who persecuted the Jews and desecrated the temple. But the prophecy seems to look beyond Antiochus to an even more terrible figure: one who 'will exalt and magnify himself above every god' (11:36), who 'will pitch his royal tents between the seas at the beautiful holy mountain. Yet he will come to his end, and no one will help him' (11:45). Jesus referred to the 'abomination of desolation' as still future (Matthew 24:15).",
                "commentary_intermediate": "Daniel 11 traces history with stunning precision. The four Persian kings (11:2) are likely Cambyses, pseudo-Smerdis, Darius I, and Xerxes. The mighty Greek king (11:3) is Alexander, whose empire was divided among four generals but not to his family (11:4). The Ptolemaic-Seleucid conflicts (11:5-20) can be correlated with historical events: marriages (11:6—Berenice to Antiochus II), revenge (11:7-9—Ptolemy III's invasion), battles (11:10-19—Antiochus III's campaigns). The 'contemptible person' (11:21) is Antiochus IV Epiphanes, who: took the throne through intrigue (11:21), broke treaties (11:22-24), invaded Egypt (11:25-28), was stopped by Roman ships ('ships of Kittim,' 11:30), and took out his frustration on the Jews (11:30-35). The 'abomination of desolation' (11:31) refers to the altar to Zeus he erected in the temple. The 'wise' (maskilim) who instruct many may refer to the Hasidim and Maccabees. But from 11:36, many scholars see the prophecy moving beyond Antiochus to a future figure—the details no longer match known history. The final king exalts himself above all gods, worships 'a god of fortresses,' and meets his end between 'the seas and the beautiful holy mountain.' Jesus's reference to Daniel's 'abomination' as future (Matthew 24:15) supports seeing an Antiochus/Antichrist pattern.",
                "commentary_advanced": "Daniel 11 presents the most historically detailed prophecy in Scripture, raising interpretive challenges. Critical scholarship generally dates the book to the Maccabean period, seeing 11:1-39 as 'prophecy after the fact' (vaticinium ex eventu); traditional scholarship sees genuine prediction. The correlation with Hellenistic history is remarkably precise through Antiochus IV. The transition point to future prophecy is debated: some place it at 11:36, others earlier, some see no transition (all fulfilled in Antiochus). The phrase 'abomination of desolation' (shiqquts meshomem, 11:31; also 12:11) became central to later Jewish and Christian expectation. The Maccabean literature (1 Maccabees 1:54, 59) interprets it as the pagan altar; Jesus reapplies it to a future event (Matthew 24:15, Mark 13:14), suggesting typological fulfillment. The king who 'exalts himself above every god' (11:36-39) has features that don't precisely match Antiochus: different theology (no gods, or 'a god of fortresses'), different allies, different end. Paul's 'man of lawlessness' (2 Thessalonians 2:3-4) seems to draw on this passage. The chapter demonstrates a pattern common in prophecy: near fulfillment (Antiochus) serves as type for fuller fulfillment (Antichrist). The precision of fulfilled prophecy grounds confidence in what remains future.",
                "reflection_prompt": "This chapter shows that God knows history's details before they happen—even complex political intrigues and battles. How does such precise knowledge affect your trust in God regarding your own uncertain future? What comfort is there in knowing that even the 'abomination' figures have appointed ends?",
            },
            {
                "day_number": 12,
                "title": "The Time of the End",
                "scripture_references": ["Daniel 12:1-13"],
                "context_summary": "Daniel's final chapter describes a time of unprecedented distress, the resurrection of the dead, and the ultimate fate of the righteous and wicked. It includes mysterious time periods (1,290 days, 1,335 days) and the instruction to 'seal' the words until the end. Daniel is told to 'go your way'—he will rest and rise to receive his allotted inheritance. This chapter profoundly shaped Jewish and Christian hope for resurrection and final judgment.",
                "commentary_beginner": "The final chapter begins with a time of distress 'such as has not happened from the beginning of nations.' But Michael, the great angel prince who protects God's people, will arise. 'Everyone whose name is found written in the book will be delivered.' Then comes one of the Old Testament's clearest statements about resurrection: 'Multitudes who sleep in the dust of the earth will awake: some to everlasting life, others to shame and everlasting contempt' (12:2). Those who are wise and lead many to righteousness 'will shine like the brightness of the heavens... like the stars for ever and ever' (12:3). Daniel was told to 'seal the words of the scroll until the time of the end.' Two others appeared, and one asked, 'How long until these astonishing things are fulfilled?' The answer: 'a time, times and half a time' (3.5 years). Daniel didn't understand and asked again. The reply was that the words are 'sealed until the time of the end.' The wicked will not understand, but the wise will. Two time periods are given: 1,290 days (to the abomination of desolation) and 1,335 days ('Blessed is the one who waits for and reaches the end of the 1,335 days'). Finally, Daniel receives personal assurance: 'As for you, go your way till the end. You will rest and then at the end of the days you will rise to receive your allotted inheritance' (12:13). Even Daniel would die, rest, and be resurrected.",
                "commentary_intermediate": "Daniel 12 provides the Old Testament's clearest resurrection hope. The 'time of distress' (12:1) echoes Jesus's 'great tribulation' (Matthew 24:21, quoting Daniel). Michael's protective role continues from chapter 10. The 'book' containing names (12:1) appears in Exodus 32:32-33, Psalm 69:28, and extensively in Revelation. The resurrection statement (12:2) is remarkable for its clarity: bodily resurrection (from 'the dust'), universal scope ('multitudes'), and dual destinies (everlasting life vs. shame). The 'maskilim' (wise ones, 12:3) who lead many to righteousness—possibly teachers and martyrs—receive special honor as 'stars.' The instruction to 'seal' the scroll (12:4) means to preserve and authenticate it for the future; 'knowledge will increase' may mean understanding of these prophecies will grow as fulfillment approaches. The 'time, times and half a time' (12:7) = 3.5 years, matching 7:25 and appearing in Revelation as 42 months or 1,260 days. The 1,290 and 1,335 days create 30-day and 45-day extensions beyond 1,260—possibly for temple cleansing and full restoration (the original Hanukkah celebration?). Daniel's personal word (12:13) assures him of resurrection: he will 'rest' (die) and 'rise' (be resurrected) to receive his 'allotment' (inheritance). This is covenant language—Daniel will share in the promised land's ultimate fulfillment.",
                "commentary_advanced": "Daniel 12 provides the theological climax: resolution of the cosmic conflict comes through resurrection and judgment. The phrase 'such as has not happened' (12:1) became standard eschatological language (cf. Mark 13:19). The Hebrew term for 'awake' (yaqitsu, 12:2) links resurrection to awakening from sleep—a metaphor continuing in the New Testament (1 Thessalonians 4:13-14). The phrase 'everlasting contempt' (dir'on olam) appears only here and Isaiah 66:24, which Jesus quotes as warning (Mark 9:48). The wise shining 'like the stars' (12:3) may reflect the belief that the righteous join the heavenly host (cf. 1 Enoch, 2 Baruch). The instruction to 'seal the book' (12:4) contrasts with Revelation 22:10, where the command is reversed—'do not seal up'—because the time has drawn near. The 'time, times and half a time' appears in Revelation 12:14, showing direct literary dependence. The variations in time periods (1,260, 1,290, 1,335 days) have generated extensive speculation; perhaps they represent stages of restoration after tribulation. Daniel's final commission—'go your way' (lek)—echoes Abraham's commission (Genesis 12:1). The phrase 'at the end of the days' (leqets hayyamim, 12:13) uses resurrection language and covenant inheritance terminology. Daniel's story thus ends with hope: whatever happens in history, the faithful will rise to receive their allotted inheritance. The book's apocalyptic vision provides comfort to the persecuted: God remains sovereign, vindication is coming, and death is not the end.",
                "reflection_prompt": "Daniel ends with the assurance of resurrection—he will 'rest' and then 'rise' to receive his inheritance. How does resurrection hope shape how you face difficulties, aging, or even death? What does it mean to you that Daniel's story ends not with his death, but with his future rising?",
            },
        ]

        for day_data in days:
            ReadingPlanDay.objects.get_or_create(
                plan=template,
                day_number=day_data["day_number"],
                defaults={
                    "title": day_data["title"],
                    "scripture_references": day_data["scripture_references"],
                    "context_summary": day_data["context_summary"],
                    "commentary_beginner": day_data["commentary_beginner"],
                    "commentary_intermediate": day_data["commentary_intermediate"],
                    "commentary_advanced": day_data["commentary_advanced"],
                    "reflection_prompt": day_data["reflection_prompt"],
                }
            )

        return template
