# ==============================================================================
# File: apps/faith/management/commands/load_creation_fall_redemption_plan.py
# Project: Whole Life Journey - Django 5.x Personal Wellness/Journaling App
# Description: Management command to create "Creation, Fall & Redemption" reading plan
# Owner: Danny Jenkins (admin@wholelifejourney.com)
# Created: 2026-01-21
# Last Updated: 2026-01-21
# ==============================================================================
"""
Management command to create the Creation, Fall & Redemption reading plan.

Creates an 8-day reading plan covering the biblical narrative arc:
- Days 1-3: Creation (Genesis 1-2)
- Day 4: The Fall (Genesis 3:1-13)
- Day 5: Consequences (Genesis 3:14-24)
- Day 6: Sin's Spread (Romans 5:12-21)
- Day 7: Redemption in Christ (Romans 5, 1 Corinthians 15)
- Day 8: All Things New (Revelation 21-22)

Each day includes:
- Context summary (theological and narrative setting)
- Commentary at 3 difficulty levels (Beginner, Intermediate, Advanced)
- Reflection prompts

Biblical accuracy verified. Non-denominational, Bible-based content.
"""

from django.core.management.base import BaseCommand
from apps.faith.models import ReadingPlanTemplate, ReadingPlanDay


class Command(BaseCommand):
    help = "Load Creation, Fall & Redemption reading plan"

    def handle(self, *args, **options):
        self.stdout.write("Loading Creation, Fall & Redemption reading plan...")

        template = self._create_creation_fall_redemption_plan()
        self.stdout.write(f"  Created: {template.title} ({template.duration_days} days)")

        self.stdout.write(self.style.SUCCESS("Creation, Fall & Redemption reading plan loaded successfully!"))

    def _create_creation_fall_redemption_plan(self):
        """Create Creation, Fall & Redemption reading plan."""
        template, created = ReadingPlanTemplate.objects.get_or_create(
            slug="creation-fall-redemption",
            defaults={
                "title": "Creation, Fall & Redemption",
                "description": "An 8-day journey through the Bible's grand narrative: from the goodness of creation, through humanity's fall into sin, to redemption in Christ and the promise of new creation. This foundational study traces the storyline that runs through all of Scripture. Understanding this arc—creation, fall, redemption, restoration—provides the framework for understanding every other part of the Bible. These aren't just ancient stories; they explain who we are, what went wrong, and what God is doing to make all things new.",
                "category": "topic",
                "difficulty": "intermediate",
                "duration_days": 8,
                "topics": ["creation", "fall", "sin", "redemption", "salvation", "adam", "christ", "new creation", "genesis", "revelation"],
                "series": "Bible Foundations",
                "series_order": 2,
                "allowed_emails": [],
                "is_active": True,
                "is_featured": True,
            }
        )

        if not created:
            # Plan exists, skip day creation
            return template

        # Creation, Fall & Redemption reading plan days
        days = [
            {
                "day_number": 1,
                "title": "Creation: God's Masterpiece",
                "scripture_references": ["Genesis 1:1-25", "Psalm 33:6-9", "John 1:1-3"],
                "context_summary": "The Bible opens not with argument but with announcement: 'In the beginning God created the heavens and the earth.' Genesis 1 is not primarily a scientific textbook but a theological declaration—God is the source of everything that exists, and everything He made was good. The creation account establishes fundamental truths: God exists before and independent of creation; He creates by His word; creation has order, purpose, and value. Understanding creation correctly is essential because it shapes how we understand everything else—ourselves, our world, our problem, and our hope.",
                "commentary_beginner": "The Bible begins with the most important statement ever written: 'In the beginning God created the heavens and the earth.' Before anything else existed, God was there. He didn't form the world from pre-existing materials; He spoke, and things came into being. 'And God said, Let there be light, and there was light.' This is repeated throughout the chapter—God speaks, and it happens. His word has creative power. Notice the pattern: God creates, then evaluates. After each act of creation, we read 'and God saw that it was good.' Light is good. Land and seas are good. Plants are good. Sun, moon, and stars are good. Sea creatures and birds are good. Land animals are good. God is not distant or detached from His creation—He delights in it! The world wasn't an accident or the result of cosmic forces. It was intentionally designed by a good God who pronounced it good. This matters because it tells us the world has meaning and purpose. It's not random. And the problems we see in the world today—suffering, evil, death—are not how things were supposed to be. They came later. The original creation was very good.",
                "commentary_intermediate": "Genesis 1 employs a carefully structured literary framework: six days of creation followed by a seventh day of rest. The first three days establish realms (light/darkness, sky/waters, land/seas with vegetation), while days four through six fill those realms with rulers (sun/moon/stars, birds/fish, land animals/humans). This structure emphasizes order emerging from chaos, culminating in humanity. The Hebrew word 'bara' (create) is used exclusively of divine activity in Scripture—only God 'creates' in this sense. The repeated phrase 'and God said' (wayomer elohim) appears ten times, connecting creation to God's powerful word. Psalm 33:6 affirms: 'By the word of the LORD the heavens were made.' John's Gospel deliberately echoes Genesis: 'In the beginning was the Word... all things were made through him' (John 1:1-3), identifying Christ as the agent of creation. The sevenfold declaration 'it was good' (tov) culminates in 'very good' (tov meod) after humanity's creation. 'Good' here means functioning according to design, fulfilling intended purpose—not merely morally neutral. The creation account establishes God's sovereignty, wisdom, and benevolence as foundational to understanding reality. Everything that follows in Scripture must be read against this backdrop of original goodness.",
                "commentary_advanced": "Genesis 1:1-2:3 functions as a theological prologue establishing the worldview framework for the entire canon. The opening phrase 'bereshit bara elohim' has been translated as an absolute beginning ('In the beginning God created') or a temporal clause ('When God began to create'). Either way, the text asserts God's priority and sovereignty over all that exists. The term 'elohim' (grammatically plural but taking singular verbs when referring to Israel's God) introduces divine majesty. The 'formless and void' (tohu wabohu) state of 1:2 describes not chaos opposing God but the raw material awaiting His ordering word. The Spirit (ruach) 'hovering' uses the same verb as a bird hovering over its young (Deuteronomy 32:11), suggesting nurturing presence. The creation-by-word motif establishes divine transcendence (God doesn't struggle with matter) while the careful ordering demonstrates divine wisdom. Ancient Near Eastern parallels exist (Enuma Elish, Atrahasis), but Genesis demythologizes them: no divine conflict, no gods emerging from creation, no human beings as afterthought to serve the gods. The seven-day structure culminates not in humanity but in Sabbath—rest as the goal of creation, not mere cessation but completion and enjoyment. The temple imagery is significant: ancient temples were built in stages, inaugurated over seven days, and the deity 'rested' there. Creation is God's cosmic temple where He dwells with His image-bearers. This framing anticipates Revelation 21-22's new creation as the ultimate temple where God dwells with humanity.",
                "reflection_prompt": "God looked at His creation and declared it 'good.' When you look at the natural world—sunsets, mountains, oceans, the intricacy of a leaf—what does it tell you about the God who made it? How might viewing creation as God's intentional masterpiece change how you interact with the world around you?",
            },
            {
                "day_number": 2,
                "title": "Humanity: Made in God's Image",
                "scripture_references": ["Genesis 1:26-2:3", "Psalm 8:3-8", "Genesis 9:6"],
                "context_summary": "The climax of creation is not the sun or the seas but humanity—male and female created in God's image. This single phrase, 'image of God' (imago Dei), is one of the most significant concepts in Scripture. It distinguishes humans from all other creatures, grounds human dignity and rights, defines our purpose, and explains why we matter to God. The creation of humanity is described with special care: God deliberates ('Let us make'), creates personally, blesses specifically, and commissions directly. Understanding what it means to bear God's image is essential to understanding ourselves.",
                "commentary_beginner": "After five days of creating, God pauses and says something different: 'Let us make mankind in our image, in our likeness.' This is the first time God deliberates before creating. Animals were made 'according to their kinds,' but humans are made according to God's likeness. What does 'image of God' mean? In the ancient world, kings would place statues (images) of themselves throughout their kingdoms to represent their authority and presence. Humans are God's living images, placed in creation to represent Him and reflect His character. This gives every human being incredible dignity. Every person you meet—regardless of age, ability, race, or status—bears the image of God. That's why murder is so serious (Genesis 9:6): to destroy a human being is to attack God's image. Genesis also tells us 'male and female he created them.' Both men and women equally bear God's image. Neither is more fully human or more valuable than the other. Then God blessed them and gave them a mission: 'Be fruitful and increase in number; fill the earth and subdue it. Rule over the fish in the sea and the birds in the sky.' Humans are given responsibility to care for creation as God's representatives—not to exploit it, but to steward it wisely. We are not accidents of evolution or meaningless specks in a vast universe. We are image-bearers of the living God, created with purpose and dignity.",
                "commentary_intermediate": "The phrase 'image of God' (tselem elohim) and 'likeness' (demut) appear together in Genesis 1:26. While scholars debate precise distinctions, together they indicate that humans uniquely represent and resemble God in creation. The 'us' in 'Let us make' has been interpreted as divine council (angels), plural of majesty, or intra-Trinitarian dialogue. Whatever the grammar, the deliberation emphasizes special intention. Image-bearing involves at minimum: rational and moral capacity, relational nature (made for relationship with God and others), representative function (ruling on God's behalf), and creative capability (subduing and cultivating). The blessing to 'be fruitful and multiply' extends God's creative work through human procreation. The mandate to 'subdue' (kabash) and 'rule' (radah) are strong terms, but in context they describe benevolent stewardship, not exploitation—Adam is later placed in the garden to 'work it and take care of it' (2:15), using terms of service and protection. Psalm 8 reflects on humanity's exalted position: 'You have made them a little lower than the angels and crowned them with glory and honor. You made them rulers over the works of your hands.' This dignity is intrinsic (based on creation, not achievement) and universal (applying to all humans regardless of capacity or status). The image, though marred by the fall, remains the basis for human rights and the prohibition against murder (Genesis 9:6). Redemption in Christ involves restoration and transformation of the image (Colossians 3:10; 2 Corinthians 3:18).",
                "commentary_advanced": "The imago Dei concept has generated extensive theological reflection. Structural interpretations locate the image in human capacities (reason, will, language, moral awareness). Functional interpretations emphasize the role of ruling as God's representative (the image is what we do). Relational interpretations focus on the capacity for relationship with God and others (the image is how we relate). These need not be mutually exclusive. The ancient Near Eastern background is illuminating: in Egypt and Mesopotamia, kings were described as the image of god, representing divine authority on earth. Genesis democratizes this concept—every human, not just royalty, bears the divine image. The plural 'Let us make' (na'aseh) remains debated. The divine council interpretation (God addressing heavenly beings) has ancient support but raises questions about their role in creation. The royal plural is grammatically unusual in Hebrew. Trinitarian interpretation, while theologically appropriate, may read later doctrine into an early text. Perhaps the plurality simply emphasizes the momentous nature of this creative act. The terms tselem (image/statue) and demut (likeness/resemblance) may function as hendiadys, together indicating concrete representation. The image involves embodiment—humans are not souls trapped in bodies but embodied beings whose physical existence is integral to their identity. This has implications for resurrection hope: we anticipate not escape from the body but resurrection of the body. The mandate to rule connects to Christ as the true image (Colossians 1:15) and true human (Son of Man) who exercises dominion as God intended (Hebrews 2:5-9). Believers are being conformed to Christ's image (Romans 8:29), the eschatological goal of redemption.",
                "reflection_prompt": "You are made in God's image—not because of what you do or accomplish, but simply because of who you are. How does this truth affect how you see yourself? How should it affect how you treat others, especially those society considers 'less valuable'? What would it look like to live today as God's image-bearer?",
            },
            {
                "day_number": 3,
                "title": "The Garden: Life with God",
                "scripture_references": ["Genesis 2:4-25", "Ezekiel 28:13", "Revelation 22:1-2"],
                "context_summary": "Genesis 2 zooms in on the sixth day, providing a closer look at humanity's creation and original environment. The garden of Eden represents more than a beautiful location—it's the place where God dwells with His people, the original temple-garden where heaven and earth meet. Here we see humanity's purpose (to work and keep the garden), humanity's provision (every tree good for food), humanity's limitation (one tree forbidden), and humanity's relationship (not good to be alone). This chapter shows us what life was meant to be: purposeful work, abundant provision, clear boundaries, and intimate relationship—with God and with each other.",
                "commentary_beginner": "Genesis 2 gives us a closer look at how God made the first humans. The LORD God 'formed a man from the dust of the ground and breathed into his nostrils the breath of life, and the man became a living being.' This is intimate, personal—like a potter shaping clay. God didn't just speak humanity into existence from a distance; He personally formed Adam and breathed life into him. Then God planted a garden in Eden—a paradise with beautiful trees, abundant fruit, and a river flowing through it. He placed Adam there with a job: 'to work it and take care of it.' Work isn't a curse from the fall; it was part of the original good design. We were made for purposeful activity. God provided generously: 'You are free to eat from any tree in the garden.' Amazing abundance! But there was one limit: 'You must not eat from the tree of the knowledge of good and evil, for when you eat from it you will certainly die.' One tree. One boundary. This wasn't arbitrary restriction but protection. The tree represented the choice to trust God's definition of good and evil or to decide for themselves. Then God said something surprising: 'It is not good for the man to be alone.' In a creation God had declared 'very good,' something was 'not good'—Adam's solitude. So God made woman from Adam's side, and when Adam saw her, he burst into poetry: 'This is now bone of my bones and flesh of my flesh!' The chapter ends with this beautiful picture: 'Adam and his wife were both naked, and they felt no shame.' Complete openness, complete trust, nothing to hide. This was life as God designed it.",
                "commentary_intermediate": "Genesis 2:4 begins a new section with the formula 'these are the generations' (toledot), which structures Genesis. This account complements chapter 1, focusing on humanity and the garden. The name 'LORD God' (Yahweh Elohim) combines God's covenant name (Yahweh) with the creation term (Elohim). The formation of Adam from 'dust' (aphar) emphasizes human creatureliness and mortality (3:19: 'to dust you shall return'). But the 'breath of life' (nishmat chayyim) directly from God indicates special divine investment. The garden 'in Eden' (eden means 'delight' or 'abundance') is planted by God Himself—a sanctuary prepared for His image-bearers. The river flowing out to water the earth (2:10-14) and the presence of gold and precious stones (2:11-12) echo temple imagery; Ezekiel 28:13 explicitly describes Eden as a holy mountain with precious stones. The verbs 'work' (abad) and 'keep' (shamar) are later used for Levitical service in the tabernacle, reinforcing that Eden was a sacred space. The prohibition regarding the tree of knowledge of good and evil establishes a boundary for human freedom. 'Good and evil' likely means 'everything'—the tree represents autonomous moral authority, deciding for oneself apart from God what is right and wrong. The creation of woman addresses Adam's solitude: the animals are helpers in general tasks, but none is a suitable counterpart (kenegdo—corresponding to him, his equal). The surgery-like description (deep sleep, taking a rib) and Adam's joyful recognition ('at last!') emphasize that male and female together complete God's design. The nakedness-without-shame conclusion (2:25) describes relational wholeness before sin—complete transparency and vulnerability without fear.",
                "commentary_advanced": "The relationship between Genesis 1 and 2 has generated considerable discussion. Source critics traditionally assigned them to different authors (P and J), but canonical reading sees them as complementary perspectives: chapter 1 provides the cosmic framework, chapter 2 the anthropological focus. The formation of Adam from adamah (ground) involves wordplay: the 'earthling' from earth, humanity from humus. The divine breath directly animating Adam distinguishes human life from animal life (though animals also receive the breath of life, Genesis 1:30; 7:22). The Eden narrative employs royal-priestly imagery: the garden is a sanctuary, Adam is its priestly guardian, and the tree of life symbolizes the life that flows from God's presence. Ancient Near Eastern parallels include Mesopotamian garden imagery and the concept of divine gardens, but Genesis transforms these motifs. The tree of knowledge of good and evil has been interpreted variously: moral knowledge, sexual awareness, wisdom for ruling, or autonomous determination of what is good and evil. The merism 'good and evil' often means 'everything' (cf. 2 Samuel 14:17), suggesting the tree represents comprehensive wisdom—specifically, the prerogative to determine right and wrong that belongs to God alone. The creation of woman from Adam's 'side' (tsela, often translated 'rib' but more commonly meaning 'side' elsewhere) emphasizes correspondence and unity rather than derivation or subordination. The exclamation 'bone of my bones' uses covenant language (cf. 2 Samuel 5:1). The etymology of 'woman' (ishah) from 'man' (ish) may be folk etymology but emphasizes their correspondence. The note about leaving father and mother (2:24) reflects the narrator's perspective for future readers—marriage establishes a new primary loyalty. The nakedness motif (2:25) sets up the contrast with 3:7; shame enters with sin. The garden thus presents the original design: purposeful vocation, abundant provision, clear boundary, divine presence, and intimate human relationship—all of which the fall disrupts.",
                "reflection_prompt": "Eden represents what life was meant to be: meaningful work, generous provision, clear boundaries, and deep relationship. Which of these do you most long for in your own life? What glimpses of 'Eden' do you experience now? How does knowing God's original design shape your hope for what He is ultimately restoring?",
            },
            {
                "day_number": 4,
                "title": "The Fall: Sin Enters the World",
                "scripture_references": ["Genesis 3:1-13", "Romans 5:12", "James 1:14-15"],
                "context_summary": "Genesis 3 describes the moment everything changed. The serpent questions God's word, contradicts God's warning, and promises godlike knowledge. Eve sees, takes, eats, and gives to her husband. Immediately their eyes are opened—but to shame, not enlightenment. They hide from each other and from God. When God comes walking in the garden, they flee from the One whose presence was their greatest joy. This chapter explains why the world is the way it is: not because God made it broken, but because humanity chose rebellion. Understanding the fall is essential to understanding ourselves and our need for redemption.",
                "commentary_beginner": "Everything was perfect in the garden. Adam and Eve had meaningful work, abundant food, beautiful surroundings, and most importantly, friendship with God. Then the serpent appeared. The serpent was 'more crafty than any of the wild animals.' He began by questioning God's word: 'Did God really say, You must not eat from any tree in the garden?' Notice the twist—God had said they could eat from any tree except one. The serpent made God sound stingy and restrictive. Eve corrected him but added her own twist: she said they couldn't even touch the tree, which God hadn't said. Then the serpent directly contradicted God: 'You will not certainly die. For God knows that when you eat from it your eyes will be opened, and you will be like God, knowing good and evil.' The serpent suggested God was holding out on them—that the forbidden tree would make them equal to God. Eve looked at the tree differently now: 'good for food, pleasing to the eye, and desirable for gaining wisdom.' She took some and ate it. She gave some to her husband, who was with her, and he ate. What happened next? 'Then the eyes of both of them were opened, and they realized they were naked.' They felt shame for the first time. They sewed fig leaves together to cover themselves. Then they heard God walking in the garden and hid among the trees. Think about that—hiding from the God who loved them, whose presence was their greatest delight. God called out: 'Where are you?' Adam answered: 'I heard you in the garden, and I was afraid because I was naked; so I hid.' Everything had changed. Fear, shame, and hiding had replaced openness, trust, and joy.",
                "commentary_intermediate": "The serpent (nachash) is introduced without explanation but is later identified with Satan (Revelation 12:9; 20:2). His craftiness (arum) puns on the couple's nakedness (arummim, 2:25)—wordplay linking the tempter with coming shame. The serpent's strategy follows a pattern: question God's word ('Did God really say?'), deny God's warning ('You will not certainly die'), and impugn God's motives ('God knows... you will be like God'). The temptation targets human autonomy—the desire to define good and evil for ourselves rather than trust God's definition. Eve's response shows the progression described in James 1:14-15: desire, then sin, then death. She saw that the tree was 'good for food' (physical desire), 'pleasing to the eye' (aesthetic appeal), and 'desirable for gaining wisdom' (intellectual/spiritual ambition). First John 2:16 echoes this threefold pattern: 'the lust of the flesh, the lust of the eyes, and the pride of life.' Adam's role is troubling: he was 'with her' (3:6), apparently passive during the temptation. Both failed—she in taking, he in silent complicity. The promised eye-opening occurs, but instead of becoming like God, they become aware of their vulnerability and shame. The fig-leaf covering represents human attempts at self-remedy—inadequate covering for their newly exposed condition. Their hiding from God is the essence of sin's effect: broken relationship, disrupted communion. God's question 'Where are you?' is not informational but relational—He seeks the one who hides. The blame-shifting that follows (Adam blames Eve and implicitly God; Eve blames the serpent) shows sin's corrupting effect on relationships: instead of unity, accusation; instead of responsibility, deflection.",
                "commentary_advanced": "The fall narrative operates on multiple literary levels: historical event, archetypal pattern, and theological explanation. The serpent functions as both creature and symbol; the New Testament identification with Satan (Revelation 12:9) doesn't negate the literal serpent but recognizes the spiritual reality behind it. The serpent's question subtly distorts God's command, changing the emphasis from generous permission ('you may freely eat from any tree') to restrictive prohibition ('you must not eat from any tree'). Eve's response compounds the distortion by adding 'or touch it'—either her own embellishment or Adam's faulty transmission. The serpent's denial ('you will not certainly die') directly contradicts God's warning and reframes the prohibition as divine jealousy rather than divine protection. The phrase 'knowing good and evil' (yode'e tov wara') describes a divine prerogative (Genesis 3:22); the temptation is to seize by disobedience what God had not granted by permission. The woman's threefold perception of the tree (ta'awah—desirable, taawa—craving, nechemad—coveted) engages all human faculties. The syntax of 3:6 is compressed: 'she took... she ate... she gave... he ate'—quick succession emphasizing the deed's simplicity and irreversibility. The immediate consequence is not death (which comes later) but shame and fear, indicating damaged relationships: with self (shame), with each other (covering), and with God (hiding). God's approach 'walking in the garden in the cool of the day' (3:8) suggests regular communion now disrupted. The Hebrew le-ruach ha-yom might mean 'in the wind of the day' or 'in the spirit of the day'—possibly theophanic language. The interrogation sequence (3:9-13) gives opportunity for confession but receives only excuse: Adam blames 'the woman you put here with me'—implicating both Eve and God. Eve blames the serpent. Neither accepts responsibility. This pattern—sin, shame, hiding, blame—remains the human pattern apart from grace.",
                "reflection_prompt": "The serpent's strategy was to make God seem restrictive and untrustworthy. Where do you find yourself questioning whether God's commands are really for your good? When you fail, do you tend to hide and blame, or confess and receive grace? What would it look like to respond to God's 'Where are you?' with honesty rather than hiding?",
            },
            {
                "day_number": 5,
                "title": "The Consequences: Death and Exile",
                "scripture_references": ["Genesis 3:14-24", "Romans 6:23", "Genesis 3:15"],
                "context_summary": "Following the fall, God pronounces judgment—but even in judgment, there is grace. The serpent is cursed; the ground is cursed; but the humans, though they face severe consequences, are not cursed. Pain in childbearing, conflict in marriage, toilsome labor, and physical death become the human lot. Most significantly, Adam and Eve are exiled from the garden, cut off from the tree of life and from God's immediate presence. Yet hidden in the curse on the serpent is the first promise of redemption: the offspring of the woman will crush the serpent's head. This is the protoevangelium—the first gospel announcement.",
                "commentary_beginner": "After the fall, God pronounced consequences. First, the serpent: 'Cursed are you above all livestock and wild animals! You will crawl on your belly and eat dust.' The serpent was degraded, made lowest of all creatures. But then God said something mysterious: 'I will put enmity between you and the woman, and between your offspring and hers; he will crush your head, and you will strike his heel.' This is the first hint of the gospel! Someday, a descendant of the woman would defeat the serpent—crushing his head while being wounded himself. Christians see this fulfilled in Jesus. To Eve, God said childbearing would involve great pain, and her relationship with her husband would involve struggle and conflict. What was designed for joy and partnership would now be marked by pain and tension. To Adam, God said the ground was cursed because of him. Work, which was meant to be fulfilling, would now involve 'painful toil,' thorns and thistles, sweat and frustration—'until you return to the ground, since from it you were taken; for dust you are and to dust you will return.' Death had entered the world. Then came exile. God made garments of skin to clothe Adam and Eve—the first animal death, a hint that covering sin requires sacrifice. He drove them out of the garden and placed cherubim and a flaming sword to guard the way to the tree of life. They could no longer reach the tree that would let them live forever. This sounds harsh, but it was actually mercy: imagine living forever in a fallen, broken state! The way back to eternal life would require a different path—one God would provide through the offspring of the woman.",
                "commentary_intermediate": "The judgment oracles of Genesis 3:14-19 follow the order of interrogation (serpent, woman, man) and establish the conditions of post-fall existence. The serpent's curse (3:14-15) goes beyond the animal to the spiritual reality behind it. The 'enmity' (eyvah) between serpent and woman, and between their respective 'seed' (zera), establishes ongoing conflict. The singular 'he' (hu) who will crush the serpent's head while having his heel struck has been understood messianically since ancient times (the Septuagint uses the masculine pronoun despite 'seed' being grammatically neuter). This protoevangelium ('first gospel') anticipates the ultimate victory over evil through a human descendant. The woman's consequences (3:16) affect her distinctive roles: motherhood involves multiplied pain (itstsabon, the same word used for Adam's toil), and her relationship with her husband involves 'desire' (teshuqah) and 'rule' (mashal). The same terms appear in 4:7 describing sin's desire for Cain and his need to master it, suggesting a conflict dynamic rather than mere attraction. The man's consequences (3:17-19) affect his work: the ground (adamah) is cursed, producing thorns and thistles; labor becomes toilsome (itstsabon again); and death claims the body that came from dust. Notably, the man and woman are not cursed—the serpent and ground are. The clothing God provides (3:21) requires animal death, prefiguring the sacrificial system. The expulsion (3:22-24) prevents eternal existence in a fallen state and establishes the cherubim as guardians of God's holy space—they later appear in the tabernacle and temple, guarding the way to God's presence. The way back to the tree of life runs through redemption, not around it.",
                "commentary_advanced": "The judgment oracles employ poetic parallelism and carefully structured divine speech. The serpent's judgment (3:14-15) moves from curse formula to prophetic announcement. The enmity declared is not merely natural antipathy between humans and snakes but cosmic conflict between the forces aligned with the deceiver and those aligned with God. The 'seed' (zera) is collective (offspring) but the singular pronouns point toward an individual who embodies the line. Ancient Jewish interpretation (Targums, Dead Sea Scrolls) and Christian tradition find messianic significance here. The 'crushing' (shuf) of the head versus heel indicates asymmetric outcomes: the serpent inflicts injury; the offspring delivers fatal defeat. Revelation 12 and 20 portray the fulfillment of this conflict. The woman's oracle (3:16) is notoriously difficult. The 'desire' (teshuqah) appears only here, Genesis 4:7, and Song of Songs 7:10. In Genesis 4:7, sin's 'desire' for Cain is predatory, and he must 'rule' (mashal) over it. This parallel suggests 3:16 describes not romantic desire but a conflict-ridden relationship where the woman's desire is to control and the man's response is domination—a corruption of the partnership of 2:18-24. Alternatively, some read it as desire for the husband despite the pain of childbearing, with male rule as protection or distortion. The interpretation affects understanding of gender relationships significantly. Adam's oracle connects his labor to the ground's curse (3:17-19). The term 'itstsabon' (painful toil) links woman's childbearing pain and man's agricultural frustration. The death pronouncement ('to dust you shall return') executes the warning of 2:17. The 'tunics of skin' (3:21) have been interpreted as evidence of animal sacrifice, divine provision replacing inadequate human effort, or simply practical necessity. The expulsion from Eden represents not vindictive punishment but protective prevention of eternal fallen existence. The cherubim (3:24), winged throne-guardians in ancient Near Eastern iconography, become Israel's reminder that access to God's presence requires purification. The tabernacle's cherubim-flanked mercy seat marks the place where atonement enables approach.",
                "reflection_prompt": "Even in pronouncing consequences, God provided covering and promised eventual victory. The gospel is hidden in the curse. Where do you see both the effects of the fall in your own life (painful toil, relational struggle, mortality) and glimpses of God's grace within those difficulties? How does the promise of Genesis 3:15 give you hope?",
            },
            {
                "day_number": 6,
                "title": "Sin Spreads: Adam's Legacy",
                "scripture_references": ["Romans 5:12-21", "Genesis 4:1-16", "Romans 3:23"],
                "context_summary": "The effects of Adam's sin didn't stay in the garden. Genesis 4 immediately shows sin's spread: Cain murders his brother Abel. By Genesis 6, 'every inclination of the thoughts of the human heart was only evil all the time.' Paul's letter to the Romans explains the theological significance: through Adam, sin entered the world, and death through sin. All humanity is implicated in Adam's fall—we are not merely sinners because we sin; we sin because we are caught in Adam's predicament. Understanding our solidarity with Adam is essential to understanding our need for a second Adam who can undo what the first Adam did.",
                "commentary_beginner": "What happened in the garden didn't stay in the garden. The very next chapter shows how quickly sin spread. Adam and Eve's first son, Cain, became angry when God accepted his brother Abel's offering but not his own. God warned Cain: 'Sin is crouching at your door; it desires to have you, but you must rule over it.' Cain didn't listen. He killed his brother. In one generation, humanity went from eating forbidden fruit to committing murder. By the time of Noah (Genesis 6), things had gotten so bad that 'every inclination of the thoughts of the human heart was only evil all the time.' Sin is like an infection that spreads and worsens. Paul explains in Romans why this happened: 'Sin entered the world through one man, and death through sin, and in this way death came to all people, because all sinned' (Romans 5:12). We often think: 'That was Adam's choice, not mine. Why should I be affected?' But Paul says we're all connected to Adam. He was our representative. When he fell, we fell with him. Think of it like a family. If your great-grandfather lost the family fortune through foolish choices, you'd be born into poverty even though you didn't make those choices. We're born into a world damaged by Adam's sin, with hearts inclined toward rebellion. 'All have sinned and fall short of the glory of God' (Romans 3:23). This isn't just about Adam long ago—each of us, given the same choice, would have done what Adam did. We do it every day in smaller ways. We need help from outside ourselves.",
                "commentary_intermediate": "Romans 5:12-21 is one of the most theologically dense passages in Scripture, establishing the parallel between Adam and Christ. Paul's argument: 'sin entered the world through one man, and death through sin, and in this way death came to all people, because all sinned' (5:12). The phrase 'because all sinned' (eph' ho pantes hemarton) has been interpreted as: (1) all sinned individually, confirming Adam's pattern; (2) all sinned 'in Adam' as their representative; or (3) all sinned as a result of inherited sinfulness. The broader context supports representative solidarity: Adam's one act brought condemnation and death to all (5:15-18), not merely as example but as source. The comparison with Christ makes this clear: just as Christ's one act brings righteousness to many (not merely as example), so Adam's one act brought sin to many. The parallel would break down if Adam only influenced while Christ actually accomplished. Genesis 4's narrative illustrates sin's spread: Cain's murder, Lamech's boastful violence (4:23-24), and humanity's comprehensive corruption by Genesis 6:5. Paul describes the human condition in Romans 1-3: Gentiles suppress truth and descend into idolatry and immorality; Jews, despite having the law, fail to keep it. The conclusion: 'all have sinned and fall short of the glory of God' (3:23). 'Fall short' (hysterountai) is present tense—we continually fail to reflect God's glory as image-bearers were meant to. Sin is universal, not because we each independently make Adam's choice, but because we are Adam's descendants, sharing his nature and confirming his choice in our own sins. This solidarity in Adam is the necessary background for solidarity in Christ.",
                "commentary_advanced": "Romans 5:12-21 develops Adam-Christ typology that has generated extensive theological reflection. The structure is comparative: as through Adam, so through Christ—but the comparison repeatedly notes that the gift exceeds the trespass (5:15, 17, 20). The critical phrase 'eph' ho pantes hemarton' (5:12) has been translated 'because all sinned' (causal), 'in whom all sinned' (locative, taking Adam as the antecedent), or 'with the result that all sinned' (consecutive). Augustine's influential reading, based on the Latin 'in quo,' understood all humanity as seminally present in Adam and thus participating in his sin. Eastern Orthodoxy typically emphasizes inherited mortality more than inherited guilt. Protestant theology, especially Reformed, emphasizes both federal headship (Adam as covenant representative) and corruption (inherited sinfulness). The parallel with Christ supports representative understanding: 'through the obedience of the one man the many will be made righteous' (5:19)—not merely influenced toward righteousness but constituted righteous. If Christ's act actually accomplishes something for those he represents, so does Adam's. The intrusion of law (5:20) serves to highlight sin rather than cure it: 'the law was brought in so that the trespass might increase'—sin becomes transgression when it violates explicit command. But grace responds superabundantly: 'where sin increased, grace increased all the more.' The reign metaphor concludes the section: sin reigned in death through Adam; grace reigns through righteousness unto eternal life through Christ. The two kingdoms are asymmetric: sin's reign leads only to death, while grace's reign leads to life. Understanding Adamic solidarity is prerequisite to grasping Christic solidarity—we must see ourselves as lost in Adam before we can see ourselves as found in Christ.",
                "reflection_prompt": "It's easy to think of sin as just individual mistakes, but Scripture presents it as a condition we inherit and confirm through our choices. How do you see the effects of 'Adamic' fallenness in yourself and the world around you? Why is it important to recognize how deep our problem is before we can appreciate how great God's solution is?",
            },
            {
                "day_number": 7,
                "title": "Redemption: Christ the Second Adam",
                "scripture_references": ["Romans 5:15-21", "1 Corinthians 15:21-22, 45-49", "Philippians 2:5-11"],
                "context_summary": "If Adam's disobedience brought sin and death to all humanity, what could reverse it? Only another representative human who succeeded where Adam failed. Paul calls Jesus 'the last Adam' and 'the second man.' Where Adam grasped for equality with God and fell, Christ—who was equal with God—humbled himself to become human and obedient even to death. Where Adam's one transgression brought condemnation, Christ's one act of righteousness brings justification. Where Adam's disobedience made many sinners, Christ's obedience makes many righteous. The gospel is not just about forgiveness of individual sins; it's about a new humanity in a new Adam.",
                "commentary_beginner": "We saw that Adam's sin affected all humanity. The good news is that Jesus came as a 'second Adam' to undo what the first Adam did. Paul explains: 'For if the many died by the trespass of the one man, how much more did God's grace and the gift that came by the grace of the one man, Jesus Christ, overflow to the many!' (Romans 5:15). Notice the 'how much more.' Adam's sin was powerful, but Christ's grace is more powerful. Adam brought death; Christ brings life. Adam's disobedience made us sinners; Christ's obedience makes us righteous. Paul makes the comparison explicit in 1 Corinthians 15: 'For since death came through a man, the resurrection of the dead comes also through a man. For as in Adam all die, so in Christ all will be made alive' (15:21-22). He calls Jesus 'the last Adam' and 'the second man from heaven.' Where Adam was made from dust and fell, Christ came from heaven and succeeded. What did Christ do that Adam failed to do? Think about Christ's temptation in the wilderness. Satan tempted him with the same basic offer: satisfy your desires apart from God's will. But Jesus refused. At every point where Adam failed, Jesus succeeded. He was obedient to the Father all the way to the cross. Philippians 2 says Jesus didn't grasp at equality with God (unlike Adam who grasped for it); instead, he humbled himself, became a servant, and was obedient even to death. And because of this, God exalted him to the highest place. Jesus is the human being Adam was supposed to be. When we trust in Christ, we're transferred from Adam's family to Christ's family—from a humanity defined by sin and death to a new humanity defined by righteousness and life.",
                "commentary_intermediate": "Romans 5:15-21 develops the Adam-Christ parallel with repeated 'much more' statements: the gift is not like the trespass—it exceeds it. Adam's one sin brought condemnation; Christ's one act of righteousness brings justification (5:16, 18). Adam's disobedience made the many sinners; Christ's obedience makes the many righteous (5:19). Grace doesn't merely balance sin; it super-abounds (5:20). The 'one act of righteousness' (dikaioma) likely refers to Christ's entire obedient life culminating in his death—not a single moment but a unified work of obedience. First Corinthians 15 places Adam-Christ typology in resurrection context. Death came through Adam; resurrection comes through Christ (15:21-22). The 'in Adam/in Christ' language indicates solidarity and representation. Verses 45-49 contrast the two Adams: the first Adam became a 'living being' (psyche zosa, quoting Genesis 2:7); the last Adam became a 'life-giving spirit' (pneuma zoopoioun). The first is 'of the earth, earthy'; the second is 'from heaven.' Believers currently bear the image of the earthly man (Adam) but will bear the image of the heavenly man (Christ). Philippians 2:5-11 provides the narrative of Christ's redemptive work. The pre-existent Christ, 'being in very nature God,' did not consider equality with God something to be 'grasped' (harpagmon)—a probable contrast with Adam's grasping. Instead, he emptied himself, took the form of a servant, became human, and humbled himself to the point of death, 'even death on a cross.' This obedience is rewarded with exaltation: the name above every name, universal confession that 'Jesus Christ is Lord.' Christ succeeds precisely where Adam failed: trusting God rather than grasping, obeying rather than rebelling, serving rather than seizing. His success becomes ours through union with him.",
                "commentary_advanced": "The Adam-Christ typology is not mere comparison but soteriological foundation. The 'one' (heis) is emphatic throughout Romans 5:15-19: one man sinned, one man's righteousness; many affected in both cases. The logic requires that Adam's act objectively affected humanity's status, not merely provided an example—otherwise the parallel with Christ's objective accomplishment breaks down. The 'many' (polloi) in 5:15, 19 (from Isaiah 53:11-12) indicates the scope of representation rather than limitation. Christ's 'obedience' (hupakoe, 5:19) encompasses his entire mission, not just isolated acts. Some distinguish 'active obedience' (fulfilling the law's requirements) and 'passive obedience' (suffering the law's penalty); both are likely in view. First Corinthians 15:45's quotation of Genesis 2:7 ('the first man Adam became a living being') is followed by Paul's own extension: 'the last Adam became a life-giving spirit.' The contrast psychikos/pneumatikos appears throughout the chapter (15:44, 46). The 'spiritual body' of resurrection is not immaterial but is animated by the Spirit rather than merely by natural life. Adam represents one kind of humanity (mortal, earthy, from below); Christ represents another (immortal, heavenly, from above). The eschatological shift has begun: those in Christ already participate in resurrection life though they await bodily resurrection. Philippians 2:6-11 may incorporate early Christian hymn material. The term harpagmos (something to be grasped/exploited) is rare and debated: did Christ not grasp at equality he didn't have, or did he not exploit equality he did have? The latter fits the context: unlike Adam who grasped for divine status, Christ possessed it but emptied himself (ekenosen), taking the form of a slave. His human obedience (to the point of death) results in divine vindication (exaltation, the name above all names). The pattern is not only exemplary but representative: Christ's humanity is the new humanity, and believers are incorporated into it through union with him. The goal of salvation is conformity to Christ's image (Romans 8:29)—becoming fully human as God intended, which Adam failed to achieve.",
                "reflection_prompt": "Adam fell by grasping for more than God had given; Christ succeeded by humbling himself and trusting God completely. Which pattern characterizes your life? Where are you tempted to 'grasp' for what God hasn't given? What would it look like to follow Jesus' example of trusting, humble obedience?",
            },
            {
                "day_number": 8,
                "title": "Restoration: All Things New",
                "scripture_references": ["Revelation 21:1-22:5", "Isaiah 65:17-25", "Romans 8:19-23"],
                "context_summary": "The Bible's storyline ends not with escape from creation but with the renewal of creation. Revelation 21-22 pictures a new heaven and new earth where God dwells with humanity, death is no more, and the tree of life is accessible once again. The curse of Genesis 3 is reversed: no more tears, no more pain, no more night. The garden has become a city—the garden-temple expanded to fill the earth. This is not merely restoration to Eden but consummation beyond Eden: what Adam could have achieved through obedience, Christ has secured forever. Creation, fall, redemption, restoration—the story that began in a garden ends in a garden-city where God's presence fills all in all.",
                "commentary_beginner": "The Bible ends where it began—but even better. Genesis started with a garden; Revelation ends with a garden-city. Genesis had a tree of life; Revelation has the tree of life restored, bearing fruit every month and with leaves 'for the healing of the nations.' Genesis showed God walking with humanity; Revelation shows God dwelling permanently with His people: 'Look! God's dwelling place is now among the people, and he will dwell with them' (21:3). But this isn't just going back to Eden. It's Eden perfected and expanded. The garden has become a city—the New Jerusalem—'coming down out of heaven from God, prepared as a bride beautifully dressed for her husband.' Everything lost in the fall is restored and more. 'He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain, for the old order of things has passed away' (21:4). The curse is gone. Death is defeated. No more hiding from God—'they will see his face' (22:4). The broken relationship between God and humanity is fully healed. Notice what's not there: no temple (because God and the Lamb are the temple), no sun or moon (because God's glory provides light), and no night (because darkness has been banished). The gates are never shut because there's no more danger. The nations bring their glory into the city because everything good in human culture is purified and included. This is what God was always working toward. Creation was 'very good,' but the new creation is glorious beyond imagination. This is our hope: not floating on clouds forever, but living in resurrected bodies in a renewed creation, with God, forever. The story isn't over until 'all things' are made new.",
                "commentary_intermediate": "Revelation 21-22 completes the biblical narrative with a vision of consummated redemption. The 'new heaven and new earth' (21:1) echoes Isaiah 65:17 and 66:22—prophetic hope for cosmic renewal, not annihilation. The first earth 'passing away' and the sea being 'no more' symbolize the removal of chaos and threat; in ancient cosmology, the sea represented danger and evil. The New Jerusalem 'coming down from heaven' (21:2, 10) indicates divine initiative—the future is God's gift, not human construction. The city as 'bride' combines two images: urban civilization and covenant relationship. God's dwelling (skene, 21:3) with humanity uses tabernacle language; the incarnational presence of John 1:14 ('the Word became flesh and dwelt [eskenosen] among us') becomes permanent cosmic reality. The fourfold negation—no tears, death, mourning, crying, or pain (21:4)—reverses Genesis 3's curses. God's declaration 'I am making everything new' (21:5) is present tense: renewal is underway and will be complete. The city's measurements (21:15-17) are symbolic: 12,000 stadia (the twelve tribes multiplied by 1,000) in cubic form (like the Holy of Holies). The entire city is a Most Holy Place where God's presence fills everything. The absence of a temple (21:22) doesn't mean absence of worship but total presence of God—the temple has expanded to fill all reality. The tree of life from Eden returns (22:2), now bearing monthly fruit and providing healing for nations—abundance and reconciliation beyond the original garden. The throne of God and the Lamb (22:1, 3) establishes the Christological center of new creation. Servants who 'see his face' (22:4) experience what was forbidden to Moses and dangerous after the fall—direct, unmediated communion with God. The curse is 'no more' (22:3)—the comprehensive reversal of Genesis 3.",
                "commentary_advanced": "Revelation 21-22 synthesizes prophetic expectations (Isaiah 25, 60, 65-66; Ezekiel 40-48) with temple and garden imagery into a unified eschatological vision. The 'new' (kainos) heaven and earth indicates qualitative renewal rather than mere replacement; 2 Peter 3:10-13's 'destruction' language should be read in light of the flood analogy—transformation through judgment, not annihilation. The descent of the New Jerusalem (21:2, 10) counters the Babel narrative of human ascent; God completes what we cannot achieve. The bridal imagery (21:2, 9) combines with urban imagery to present redeemed humanity in both relational (covenant) and corporate (civic) terms. The dwelling-with-humanity motif (21:3) employs Ezekiel 37:27 language: the covenant formula 'they will be his people, and God himself will be with them and be their God.' The dimensions of the city (21:16) form a perfect cube—the only other cubic space in Scripture is the Holy of Holies. The city's foundations (twelve apostles) and gates (twelve tribes) unite Israel and the church in the one people of God. The absence of sea (21:1), night (21:25; 22:5), and temple (21:22) removes the barriers and boundaries that characterized the old order. The river of life (22:1) recalls both Eden's river (Genesis 2:10) and Ezekiel's temple river (Ezekiel 47)—life flowing from God's throne transforms everything it touches. The tree of life's monthly fruit and healing leaves suggest both abundance and the ongoing vitality of resurrection existence. The 'healing of the nations' (therapeia, 22:2) implies that national distinctions remain but are reconciled—cultural diversity without conflict. The servants' 'reign forever and ever' (22:5) fulfills humanity's original commission to rule (Genesis 1:26-28). The beatific vision—'they will see his face' (22:4)—represents the telos of human existence: unmediated knowledge of God. The narrative arc from creation to new creation demonstrates that redemption is not escape from materiality but its transformation; the resurrection of Christ's body anticipates the resurrection of all creation. The Pauline vision of creation 'groaning' for liberation (Romans 8:19-23) finds its answer here. Eschatological hope is thus not otherworldly but this-worldly in its renewed form: embodied existence in a renewed cosmos, in perfect communion with God and one another, forever.",
                "reflection_prompt": "The Bible ends not with escape from the world but with the world made new—a city where God dwells with His people, tears are wiped away, and the tree of life is accessible again. How does this vision of ultimate restoration shape how you live today? What difference does it make to know that God is making 'all things new'—including you?",
            },
        ]

        for day_data in days:
            ReadingPlanDay.objects.get_or_create(
                plan=template,
                day_number=day_data["day_number"],
                defaults={
                    "title": day_data["title"],
                    "scripture_references": day_data["scripture_references"],
                    "context_summary": day_data["context_summary"],
                    "commentary_beginner": day_data["commentary_beginner"],
                    "commentary_intermediate": day_data["commentary_intermediate"],
                    "commentary_advanced": day_data["commentary_advanced"],
                    "reflection_prompt": day_data["reflection_prompt"],
                }
            )

        return template
