# Generated by Django 5.2.9 on 2025-12-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="Whole Life Journey",
                        help_text="The name of your site",
                        max_length=100,
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        default="Your personal life operating system",
                        help_text="A short tagline displayed on the landing page",
                        max_length=200,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Site logo (recommended size: 200x64 pixels)",
                        null=True,
                        upload_to="site/",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="Favicon (recommended: 32x32 PNG)",
                        null=True,
                        upload_to="site/",
                    ),
                ),
                (
                    "default_theme",
                    models.CharField(
                        default="minimal",
                        help_text="Default theme for new users",
                        max_length=50,
                    ),
                ),
                (
                    "allow_registration",
                    models.BooleanField(
                        default=True, help_text="Allow new users to register"
                    ),
                ),
                (
                    "require_email_verification",
                    models.BooleanField(
                        default=False,
                        help_text="Require email verification for new accounts",
                    ),
                ),
                (
                    "faith_enabled_by_default",
                    models.BooleanField(
                        default=True,
                        help_text="Enable Faith module by default for new users",
                    ),
                ),
                (
                    "footer_text",
                    models.CharField(
                        blank=True,
                        default="© 2025 Whole Life Journey. All rights reserved.",
                        max_length=200,
                    ),
                ),
                (
                    "privacy_policy_url",
                    models.URLField(blank=True, help_text="Link to privacy policy"),
                ),
                (
                    "terms_url",
                    models.URLField(blank=True, help_text="Link to terms of service"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Configuration",
                "verbose_name_plural": "Site Configuration",
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique identifier (e.g., 'minimal', 'faith')",
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'Minimal / Life Focus')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Short description of the theme's feel",
                        max_length=200,
                    ),
                ),
                (
                    "color_primary",
                    models.CharField(
                        default="#6b7280",
                        help_text="Primary color (hex, e.g., #6b7280)",
                        max_length=7,
                    ),
                ),
                (
                    "color_secondary",
                    models.CharField(
                        default="#f9fafb",
                        help_text="Secondary/background color",
                        max_length=7,
                    ),
                ),
                (
                    "color_accent",
                    models.CharField(
                        default="#6366f1",
                        help_text="Accent color for buttons, links",
                        max_length=7,
                    ),
                ),
                (
                    "color_text",
                    models.CharField(
                        default="#374151", help_text="Main text color", max_length=7
                    ),
                ),
                (
                    "color_text_muted",
                    models.CharField(
                        default="#6b7280",
                        help_text="Muted/secondary text color",
                        max_length=7,
                    ),
                ),
                (
                    "color_background",
                    models.CharField(
                        default="#ffffff",
                        help_text="Page background color",
                        max_length=7,
                    ),
                ),
                (
                    "color_surface",
                    models.CharField(
                        default="#f3f4f6",
                        help_text="Card/surface background color",
                        max_length=7,
                    ),
                ),
                (
                    "color_border",
                    models.CharField(
                        default="#e5e7eb", help_text="Border color", max_length=7
                    ),
                ),
                (
                    "dark_color_primary",
                    models.CharField(
                        default="#9ca3af",
                        help_text="Primary color in dark mode",
                        max_length=7,
                    ),
                ),
                (
                    "dark_color_secondary",
                    models.CharField(
                        default="#111827",
                        help_text="Secondary color in dark mode",
                        max_length=7,
                    ),
                ),
                (
                    "dark_color_accent",
                    models.CharField(
                        default="#818cf8",
                        help_text="Accent color in dark mode",
                        max_length=7,
                    ),
                ),
                (
                    "dark_color_text",
                    models.CharField(
                        default="#f9fafb",
                        help_text="Text color in dark mode",
                        max_length=7,
                    ),
                ),
                (
                    "dark_color_text_muted",
                    models.CharField(
                        default="#9ca3af",
                        help_text="Muted text in dark mode",
                        max_length=7,
                    ),
                ),
                (
                    "dark_color_background",
                    models.CharField(
                        default="#030712",
                        help_text="Background in dark mode",
                        max_length=7,
                    ),
                ),
                (
                    "dark_color_surface",
                    models.CharField(
                        default="#1f2937",
                        help_text="Surface color in dark mode",
                        max_length=7,
                    ),
                ),
                (
                    "dark_color_border",
                    models.CharField(
                        default="#374151",
                        help_text="Border color in dark mode",
                        max_length=7,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Make this theme available to users"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Use as default theme for new users"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in theme selector (lower = first)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Theme",
                "verbose_name_plural": "Themes",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
