# Generated by Django 5.2.9 on 2025-12-26 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_siteconfiguration_theme"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChoiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique identifier (e.g., 'mood', 'milestone_type')",
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'Mood', 'Milestone Type')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what this category is for"
                    ),
                ),
                (
                    "app_label",
                    models.CharField(
                        blank=True,
                        help_text="App that uses this (e.g., 'journal', 'faith', 'health')",
                        max_length=50,
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="System categories cannot be deleted"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Choice Category",
                "verbose_name_plural": "Choice Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ChoiceOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Value stored in database (e.g., 'happy', 'urgent')",
                        max_length=50,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display label (e.g., 'Happy 😊', 'Urgent')",
                        max_length=100,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Emoji or icon class (e.g., '😊', 'fa-smile')",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Color hex code (e.g., '#10b981')",
                        max_length=7,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in dropdown (lower = first)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Show in dropdowns"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, help_text="Pre-selected option"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="core.choicecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Choice Option",
                "verbose_name_plural": "Choice Options",
                "ordering": ["category", "sort_order", "label"],
                "unique_together": {("category", "value")},
            },
        ),
    ]
