# Generated by Django 5.2.9 on 2025-12-26 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_choicecategory_choiceoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.FloatField(default=0, help_text='Total run time in seconds')),
                ('status', models.CharField(choices=[('passed', 'All Passed'), ('failed', 'Some Failed'), ('error', 'Has Errors')], default='passed', max_length=10)),
                ('total_tests', models.PositiveIntegerField(default=0)),
                ('passed', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('apps_tested', models.TextField(help_text='Comma-separated list of apps tested')),
                ('pass_rate', models.DecimalField(decimal_places=2, default=0, help_text='Pass rate as percentage', max_digits=5)),
                ('git_branch', models.CharField(blank=True, max_length=100)),
                ('git_commit', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'verbose_name': 'Test Run',
                'verbose_name_plural': 'Test Runs',
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='TestRunDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('passed', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('failed_tests', models.TextField(blank=True, help_text='JSON list of failed test names')),
                ('error_tests', models.TextField(blank=True, help_text='JSON list of error test names')),
                ('error_details', models.TextField(blank=True, help_text='Full error tracebacks')),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.testrun')),
            ],
            options={
                'ordering': ['app_name'],
            },
        ),
    ]
