# Generated by Django 5.2.9 on 2025-12-28 14:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_test_run_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CameraScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        help_text="Original captured image",
                        upload_to="camera_scans/%Y/%m/",
                    ),
                ),
                (
                    "detected_category",
                    models.CharField(
                        choices=[
                            ("food", "Food"),
                            ("packaged_food", "Packaged Food"),
                            ("medicine", "Medicine"),
                            ("supplement", "Supplement"),
                            ("receipt", "Receipt"),
                            ("document", "Document"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="AI confidence score (0-1)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "raw_ai_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full AI output for audit and reprocessing",
                    ),
                ),
                (
                    "extracted_text",
                    models.TextField(
                        blank=True, help_text="OCR results from the image"
                    ),
                ),
                ("extracted_brand", models.CharField(blank=True, max_length=200)),
                (
                    "extracted_product_name",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "extracted_serving_size",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "extracted_nutrition_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured nutrition facts extracted from the image",
                    ),
                ),
                (
                    "extracted_barcode",
                    models.CharField(
                        blank=True, help_text="Detected barcode value", max_length=50
                    ),
                ),
                (
                    "device_info",
                    models.CharField(
                        blank=True, help_text="Device/browser info", max_length=200
                    ),
                ),
                (
                    "lighting_quality",
                    models.CharField(
                        blank=True,
                        help_text="AI assessment of image quality (good/fair/poor)",
                        max_length=20,
                    ),
                ),
                ("scanned_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("discarded", "Discarded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "processing_error",
                    models.TextField(
                        blank=True, help_text="Error message if processing failed"
                    ),
                ),
                (
                    "action_taken",
                    models.CharField(
                        blank=True,
                        help_text="Action taken: 'food_logged', 'medicine_added', 'saved', 'discarded'",
                        max_length=50,
                    ),
                ),
                (
                    "action_reference_type",
                    models.CharField(
                        blank=True,
                        help_text="Model type created: 'health.FoodEntry', 'health.Medicine'",
                        max_length=50,
                    ),
                ),
                (
                    "action_reference_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="ID of the created record", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "camera scan",
                "verbose_name_plural": "camera scans",
                "ordering": ["-scanned_at"],
            },
        ),
    ]
