# Generated by Django 5.2.9 on 2025-12-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_created_via_field"),
        ("core", "0005_food_tracking"),
    ]

    operations = []
