# Generated by Django 5.2.9 on 2025-12-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_merge_0005_add_created_via_field_0005_food_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="camerascan",
            name="created_via",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Entry"),
                    ("ai_camera", "AI Camera Scan"),
                    ("import", "Data Import"),
                    ("api", "API"),
                ],
                default="manual",
                help_text="How this entry was created",
                max_length=20,
            ),
        ),
    ]
