# Generated by Django 5.2.9 on 2025-12-28 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_camerascan_created_via"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short, descriptive title (e.g., 'AI Camera Scanning')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Brief description of what's new. Keep it user-friendly."
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("feature", "New Feature"),
                            ("fix", "Bug Fix"),
                            ("enhancement", "Enhancement"),
                            ("security", "Security Update"),
                        ],
                        default="feature",
                        help_text="Type of release note for categorization and display",
                        max_length=20,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="Optional version number (e.g., '1.2.0')",
                        max_length=20,
                    ),
                ),
                (
                    "release_date",
                    models.DateField(help_text="Date this was released/deployed"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Only published entries are shown to users",
                    ),
                ),
                (
                    "is_major",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as major update for visual emphasis",
                    ),
                ),
                (
                    "learn_more_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional link to documentation or blog post",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Release Note",
                "verbose_name_plural": "Release Notes",
                "ordering": ["-release_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserReleaseNoteView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_viewed_at",
                    models.DateTimeField(
                        help_text="When the user last dismissed the What's New popup"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="release_note_view",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Release Note View",
                "verbose_name_plural": "User Release Note Views",
            },
        ),
    ]
