# Generated by Django 5.2.9 on 2025-12-30 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_dashboard_end_fast_fix_note"),
        ("core", "0012_weight_nutrition_goals_release_notes"),
    ]

    operations = []
