# Generated by Django 5.2.9 on 2025-12-30 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_assistant_chat_history_release_note"),
        ("core", "0014_dashboard_tile_shortcuts_release_note"),
    ]

    operations = []
