# Generated by Django 5.2.9 on 2025-12-30 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_fitness_tile_metrics_release_note"),
        ("core", "0016_merge_medical_providers"),
    ]

    operations = []
