# Generated by Django 5.2.9 on 2025-12-30 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_personal_assistant_module_release_note"),
        ("core", "0018_add_assistant_focus_release_note"),
    ]

    operations = []
