# Generated by Django 5.2.9 on 2025-12-31 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_improved_help_system_release_note"),
        ("core", "0022_task_search_release_note"),
    ]

    operations = []
