# Generated by Django 5.2.9 on 2025-12-31 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_add_cascading_menu_release_note"),
        ("core", "0024_memory_verse_release_note"),
    ]

    operations = []
