# Generated by Django 5.2.9 on 2026-01-01 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_journal_book_view_fix_release_note"),
        ("core", "0030_weight_loss_graph_release_note"),
    ]

    operations = []
