# Generated by Django 4.2.27 on 2026-01-12 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0043_nutrition_scan_icons_release_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, help_text='UUID for correlating logs', max_length=36)),
                ('method', models.CharField(help_text='HTTP method (GET, POST, etc.)', max_length=10)),
                ('path', models.CharField(db_index=True, help_text='API endpoint path', max_length=500)),
                ('query_string', models.TextField(blank=True, default='', help_text='Query parameters (sanitized)')),
                ('api_key_name', models.CharField(blank=True, db_index=True, default='', help_text='Name/identifier of API key used (not the key itself)', max_length=100)),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='Client IP address')),
                ('user_agent', models.CharField(blank=True, default='', help_text='User agent string', max_length=500)),
                ('status_code', models.PositiveSmallIntegerField(db_index=True, help_text='HTTP response status code')),
                ('response_time_ms', models.PositiveIntegerField(help_text='Response time in milliseconds')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if request failed')),
                ('is_anomaly', models.BooleanField(db_index=True, default=False, help_text='Flagged as anomalous by detection system')),
                ('anomaly_reason', models.CharField(blank=True, default='', help_text='Reason for anomaly flag', max_length=200)),
                ('anomaly_score', models.FloatField(default=0.0, help_text='Anomaly score (0-1, higher = more anomalous)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Request Log',
                'verbose_name_plural': 'API Request Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address', 'created_at'], name='core_apireq_ip_addr_4dafe2_idx'), models.Index(fields=['api_key_name', 'created_at'], name='core_apireq_api_key_68e506_idx'), models.Index(fields=['path', 'created_at'], name='core_apireq_path_57a05e_idx'), models.Index(fields=['status_code', 'created_at'], name='core_apireq_status__f4e350_idx'), models.Index(fields=['is_anomaly', 'created_at'], name='core_apireq_is_anom_538aa0_idx')],
            },
        ),
    ]
