# Generated by Django 4.2.27 on 2026-01-20 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0046_fatsecret_integration_release_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('medicine', 'Medicine Reminder'), ('medicine_refill', 'Medicine Refill'), ('task', 'Task Due'), ('event', 'Calendar Event'), ('prayer', 'Prayer Reminder'), ('reading_plan', 'Reading Plan'), ('fasting', 'Fasting Reminder'), ('significant_event', 'Significant Event'), ('milestone', 'Goal Milestone'), ('finance', 'Finance Alert'), ('journal', 'Journal Prompt'), ('system', 'System')], db_index=True, default='system', help_text='Type of notification', max_length=20)),
                ('title', models.CharField(help_text='Short notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message body')),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate to when notification is clicked', max_length=500)),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji for the notification', max_length=50)),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Whether the user has read this notification')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was marked as read', null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the source object', null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, help_text='When this notification should be shown (null = immediate)', null=True)),
                ('email_sent', models.BooleanField(default=False, help_text='Whether an email was sent for this notification')),
                ('email_sent_at', models.DateTimeField(blank=True, help_text='When the email was sent', null=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Type of the source object', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='User this notification is for', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='core_notifi_user_id_f286cd_idx'), models.Index(fields=['user', 'category', '-created_at'], name='core_notifi_user_id_aa7732_idx'), models.Index(fields=['scheduled_for', 'is_read'], name='core_notifi_schedul_f2623c_idx')],
            },
        ),
    ]
