# Generated by Django 4.2.27 on 2026-02-06 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0051_ai_personal_context_release_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typical_start_hour', models.FloatField(default=8.0, help_text='Average hour the user starts their day (e.g., 6.5 = 6:30am)')),
                ('typical_end_hour', models.FloatField(default=22.0, help_text='Average hour the user ends their day (e.g., 22.5 = 10:30pm)')),
                ('earliest_start_hour', models.FloatField(default=8.0, help_text='Earliest recorded day start (10th percentile)')),
                ('sample_days', models.PositiveIntegerField(default=0, help_text='Number of days of data used to compute this pattern')),
                ('last_computed', models.DateTimeField(auto_now=True, help_text='When this pattern was last recalculated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_pattern', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity Pattern',
                'verbose_name_plural': 'User Activity Patterns',
            },
        ),
        migrations.CreateModel(
            name='UserDailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text="The calendar date of activity (in user's timezone)")),
                ('first_seen', models.TimeField(help_text='Earliest interaction time on this date')),
                ('last_seen', models.TimeField(help_text='Latest interaction time on this date')),
                ('interaction_count', models.PositiveIntegerField(default=1, help_text='Number of page views on this date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Daily Activity',
                'verbose_name_plural': 'User Daily Activities',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
