# Generated by Django 4.2.27 on 2026-02-15 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0052_add_user_activity_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnedMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(help_text="The user's original phrase (e.g., 'the scripture', 'my goal')", max_length=255)),
                ('meaning_type', models.CharField(help_text="Category of meaning (e.g., 'scripture', 'goal', 'health_entry')", max_length=100)),
                ('meaning_identifier', models.CharField(help_text="Specific identifier (e.g., 'John 3:16', 'goal_id:42')", max_length=255)),
                ('confidence_score', models.FloatField(default=0.8, help_text='0.0 to 1.0 — grows with usage, must meet threshold to auto-use')),
                ('usage_count', models.IntegerField(default=1, help_text='Number of times this mapping has been used')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this mapping was applied', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft disable without deleting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_learned_mapping',
                'ordering': ['-confidence_score', '-usage_count'],
            },
        ),
        migrations.CreateModel(
            name='ContextSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_type', models.CharField(help_text="Type of context (e.g., 'scripture_page', 'health_entry', 'goal')", max_length=100)),
                ('context_identifier', models.CharField(help_text='Specific identifier for this context', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data (page title, entry details, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_context_snapshot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClarificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_input', models.TextField(help_text='What the user originally said')),
                ('clarification_question', models.TextField(help_text='What the AI asked for clarification')),
                ('user_response', models.TextField(help_text="The user's clarifying response")),
                ('resolved_meaning', models.TextField(help_text='The final resolved meaning after clarification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learned_mapping', models.ForeignKey(blank=True, help_text='The mapping created/updated from this clarification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clarification_logs', to='core.learnedmapping')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_clarification_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='learnedmapping',
            index=models.Index(fields=['user', 'phrase'], name='idx_mapping_user_phrase'),
        ),
        migrations.AddIndex(
            model_name='learnedmapping',
            index=models.Index(fields=['user', 'confidence_score'], name='idx_mapping_user_confidence'),
        ),
        migrations.AddIndex(
            model_name='learnedmapping',
            index=models.Index(fields=['user', 'meaning_type'], name='idx_mapping_user_type'),
        ),
        migrations.AddIndex(
            model_name='contextsnapshot',
            index=models.Index(fields=['user', 'context_type', '-created_at'], name='idx_ctx_user_type_date'),
        ),
        migrations.AddIndex(
            model_name='clarificationlog',
            index=models.Index(fields=['user', '-created_at'], name='idx_clarify_user_date'),
        ),
    ]
