# Generated by Django 4.2.27 on 2026-02-15 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0053_add_slcme_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(help_text="e.g., 'health', 'goals', 'scripture', 'journal'", max_length=100)),
                ('insight_type', models.CharField(help_text="e.g., 'weight_trend_up', 'goal_deadline_risk'", max_length=120)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('positive', 'Positive'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0, help_text='0.0 to 1.0 — only notify if >= rule threshold')),
                ('explain_why', models.TextField(help_text='Human explanation of why this was generated')),
                ('evidence', models.JSONField(default=dict, help_text='Structured provenance: dates, values, record ids, rule_name')),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('dismissed', 'Dismissed')], default='new', max_length=20)),
                ('dedupe_key', models.CharField(db_index=True, max_length=255)),
                ('notified_at', models.DateTimeField(blank=True, help_text='When user was notified (None = not notified)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pie_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_ai_insight',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'module', 'insight_type'], name='idx_insight_user_mod_type'), models.Index(fields=['user', 'status', '-created_at'], name='idx_insight_user_status'), models.Index(fields=['dedupe_key'], name='idx_insight_dedupe')],
            },
        ),
    ]
