# Generated by Django 4.2.27 on 2026-02-15 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0055_add_prie_prediction_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_data', models.JSONField(default=dict, help_text='Structured state snapshot keyed by module.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sae_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User State',
                'verbose_name_plural': 'User States',
                'db_table': 'core_user_state',
                'indexes': [models.Index(fields=['user'], name='core_user_s_user_id_300ba5_idx'), models.Index(fields=['last_updated'], name='core_user_s_last_up_5917e3_idx')],
            },
        ),
    ]
