# Generated by Django 4.2.27 on 2026-02-15 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0056_add_sae_user_state_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(help_text='The raw user input that was interpreted')),
                ('page_context', models.JSONField(blank=True, default=dict, help_text='Page context dict at time of interpretation')),
                ('parsed_intent', models.CharField(blank=True, help_text="Primary intent detected (e.g., 'log_weight', 'create_goal')", max_length=100)),
                ('parsed_domain', models.CharField(blank=True, help_text="Domain module resolved (e.g., 'health', 'faith')", max_length=50)),
                ('parsed_entities', models.JSONField(blank=True, default=dict, help_text='Structured entities extracted {name: value}')),
                ('parsed_time_expression', models.CharField(blank=True, help_text='Time expression detected (before HTIE resolution)', max_length=200)),
                ('overall_confidence', models.FloatField(default=0.0, help_text='Overall interpretation confidence (0.0-1.0)')),
                ('intent_confidence', models.FloatField(default=0.0, help_text='Intent-specific confidence (0.0-1.0)')),
                ('entity_confidence', models.FloatField(default=0.0, help_text='Entity extraction confidence (0.0-1.0)')),
                ('is_ambiguous', models.BooleanField(default=False, help_text='Whether the input was flagged as ambiguous')),
                ('ambiguity_type', models.CharField(blank=True, help_text='Type of ambiguity detected (intent, entity, domain, multi_intent)', max_length=50)),
                ('clarification_question', models.TextField(blank=True, help_text='Clarification question generated (if ambiguous)')),
                ('alternative_intents', models.JSONField(blank=True, default=list, help_text='Alternative intent candidates [{intent, confidence}]')),
                ('used_slcme', models.BooleanField(default=False, help_text='Whether SLCME contributed to resolution')),
                ('used_sae', models.BooleanField(default=False, help_text='Whether SAE state contributed to resolution')),
                ('used_context', models.BooleanField(default=False, help_text='Whether page context contributed to resolution')),
                ('was_correct', models.BooleanField(blank=True, help_text='Whether the interpretation was correct (set after execution)', null=True)),
                ('correction_applied', models.CharField(blank=True, help_text='What the user actually meant (if corrected)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Semantic Decision Log',
                'verbose_name_plural': 'Semantic Decision Logs',
                'db_table': 'core_semantic_decision_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_semant_user_id_485d14_idx'), models.Index(fields=['parsed_intent', '-created_at'], name='core_semant_parsed__f71128_idx'), models.Index(fields=['is_ambiguous', '-created_at'], name='core_semant_is_ambi_3a86f0_idx')],
            },
        ),
    ]
