# Generated by Django 4.2.27 on 2026-02-15 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0059_add_guidance_lifecycle_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('briefing_date', models.DateField(help_text='The date this briefing covers.')),
                ('summary', models.TextField(help_text='Human-readable briefing summary text.')),
                ('state_snapshot', models.JSONField(blank=True, default=dict, help_text='SAE state at briefing time.')),
                ('guidance_snapshot', models.JSONField(blank=True, default=dict, help_text='PGE guidance items included in briefing.')),
                ('insight_snapshot', models.JSONField(blank=True, default=dict, help_text='PIE insights included in briefing.')),
                ('prediction_snapshot', models.JSONField(blank=True, default=dict, help_text='PRIE predictions included in briefing.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Briefing',
                'verbose_name_plural': 'Daily Briefings',
                'db_table': 'core_daily_briefing',
                'ordering': ['-briefing_date'],
            },
        ),
        migrations.RenameIndex(
            model_name='guidanceitem',
            new_name='core_guidan_user_id_989892_idx',
            old_name='core_guidanc_user_id_active_idx',
        ),
        migrations.RenameIndex(
            model_name='guidanceitem',
            new_name='core_guidan_user_id_e072b6_idx',
            old_name='core_guidanc_user_id_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='guidanceitem',
            new_name='core_guidan_user_id_e4deeb_idx',
            old_name='core_guidanc_user_id_act_pri_idx',
        ),
        migrations.RenameIndex(
            model_name='guidanceitem',
            new_name='core_guidan_dedupe__981d5e_idx',
            old_name='core_guidanc_dedupe_idx',
        ),
        migrations.RenameIndex(
            model_name='guidanceitem',
            new_name='core_guidan_expires_cfc879_idx',
            old_name='core_guidanc_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='guidanceitem',
            new_name='core_guidan_snoozed_0e58e4_idx',
            old_name='core_guidanc_snoozed_idx',
        ),
        migrations.AddField(
            model_name='dailybriefing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_briefings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='dailybriefing',
            constraint=models.UniqueConstraint(fields=('user', 'briefing_date'), name='unique_user_briefing_date'),
        ),
    ]
