# Generated by Django 4.2.27 on 2026-02-15 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0060_daily_briefing'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidanceLearningProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_guidance_seen', models.IntegerField(default=0, help_text='Total guidance items shown to this user.')),
                ('total_guidance_acknowledged', models.IntegerField(default=0, help_text='Total guidance items acknowledged.')),
                ('total_guidance_dismissed', models.IntegerField(default=0, help_text='Total guidance items dismissed.')),
                ('total_guidance_acted', models.IntegerField(default=0, help_text='Total guidance items acted upon.')),
                ('avg_response_time_seconds', models.FloatField(default=0.0, help_text='Average seconds between guidance creation and user action.')),
                ('responsiveness_score', models.FloatField(default=0.5, help_text='Composite responsiveness score (0.0-1.0).')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guidance_learning_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guidance Learning Profile',
                'verbose_name_plural': 'Guidance Learning Profiles',
                'db_table': 'core_guidance_learning_profile',
            },
        ),
        migrations.CreateModel(
            name='GuidanceLearningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('acknowledged', 'Acknowledged'), ('dismissed', 'Dismissed'), ('acted', 'Acted Upon'), ('ignored', 'Ignored')], max_length=20)),
                ('event_timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_time_seconds', models.FloatField(default=0.0, help_text='Seconds between guidance creation and this event.')),
                ('guidance_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_events', to='core.guidanceitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidance_learning_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guidance Learning Event',
                'verbose_name_plural': 'Guidance Learning Events',
                'db_table': 'core_guidance_learning_event',
                'ordering': ['-event_timestamp'],
            },
        ),
    ]
