# Generated by Django 4.2.27 on 2026-02-15 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_guidance_learning'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledIntelligenceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text='Unique identifier matching a registered task.', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', help_text='Human-readable description of what this task does.', max_length=255)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='When this task last executed.', null=True)),
                ('next_run_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this task should next execute.')),
                ('run_interval_seconds', models.IntegerField(default=86400, help_text='Seconds between runs.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this task is enabled.')),
                ('last_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', help_text='Status of the most recent run.', max_length=20)),
                ('last_error', models.TextField(blank=True, default='', help_text='Error message from the most recent failed run.')),
                ('run_count', models.IntegerField(default=0, help_text='Total number of successful runs.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scheduled Intelligence Task',
                'verbose_name_plural': 'Scheduled Intelligence Tasks',
                'db_table': 'core_scheduled_intelligence_task',
                'ordering': ['task_name'],
            },
        ),
    ]
