# Generated by Django 4.2.27 on 2026-02-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_scheduled_intelligence_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_name', models.CharField(help_text="Lock identifier (e.g., 'apscheduler_main').", max_length=100, unique=True)),
                ('locked_at', models.DateTimeField(help_text='When the lock was acquired or last refreshed.')),
                ('locked_by', models.CharField(help_text='Hostname-PID of the process holding the lock.', max_length=255)),
            ],
            options={
                'verbose_name': 'Scheduler Lock',
                'verbose_name_plural': 'Scheduler Locks',
                'db_table': 'core_scheduler_lock',
            },
        ),
    ]
