# Generated by Django 4.2.27 on 2026-02-15 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0063_scheduler_lock'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyIntelligenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(help_text='Monday of the report week.')),
                ('week_end_date', models.DateField(help_text='Sunday of the report week.')),
                ('summary', models.TextField(help_text="Natural language summary of the week's intelligence.")),
                ('state_delta_snapshot', models.JSONField(default=dict, help_text='State changes between week start and end.')),
                ('insight_snapshot', models.JSONField(default=dict, help_text='Key insights from the week.')),
                ('prediction_snapshot', models.JSONField(default=dict, help_text='Important predictions from the week.')),
                ('guidance_snapshot', models.JSONField(default=dict, help_text='Guidance items and lifecycle activity.')),
                ('learning_snapshot', models.JSONField(default=dict, help_text='GLOE learning profile snapshot for the week.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_intelligence_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly Intelligence Report',
                'verbose_name_plural': 'Weekly Intelligence Reports',
                'db_table': 'core_weekly_intelligence_report',
                'ordering': ['-week_start_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='weeklyintelligencereport',
            constraint=models.UniqueConstraint(fields=('user', 'week_start_date'), name='unique_weekly_report_per_user'),
        ),
    ]
