# Generated by Django 4.2.27 on 2026-02-15 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0064_weekly_intelligence_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_engine', models.CharField(choices=[('PIE', 'Proactive Insight Engine'), ('PRIE', 'Predictive Intelligence Engine'), ('PGE', 'Proactive Guidance Engine'), ('DBE', 'Daily Briefing Engine'), ('WIRE', 'Weekly Intelligence Report Engine')], help_text='Which engine produced the intelligence output.', max_length=10)),
                ('source_object_type', models.CharField(help_text='Model name of source object (e.g., GuidanceItem, DailyBriefing).', max_length=100)),
                ('source_object_id', models.IntegerField(help_text='PK of the source object.')),
                ('title', models.CharField(help_text='Short title of the intelligence output.', max_length=255)),
                ('explanation', models.TextField(help_text='Human-readable explanation of why this was generated.')),
                ('confidence_explanation', models.TextField(blank=True, help_text='Why the confidence score is what it is.', null=True)),
                ('evidence', models.JSONField(default=list, help_text='List of evidence objects with type, id, date, summary, url.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explain_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Explain Record',
                'verbose_name_plural': 'Explain Records',
                'db_table': 'core_explain_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'source_engine'], name='idx_explain_user_engine'), models.Index(fields=['user', 'source_object_type', 'source_object_id'], name='idx_explain_user_obj')],
            },
        ),
    ]
