# Generated by Django 4.2.27 on 2026-02-15 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0065_explain_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('medicine', 'Medicine Reminder'), ('medicine_refill', 'Medicine Refill'), ('task', 'Task Due'), ('event', 'Calendar Event'), ('prayer', 'Prayer Reminder'), ('reading_plan', 'Reading Plan'), ('fasting', 'Fasting Reminder'), ('significant_event', 'Significant Event'), ('milestone', 'Goal Milestone'), ('finance', 'Finance Alert'), ('journal', 'Journal Prompt'), ('system', 'System'), ('intelligence', 'Intelligence')], db_index=True, default='system', help_text='Type of notification', max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveredNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_engine', models.CharField(choices=[('PGE', 'Proactive Guidance Engine'), ('DBE', 'Daily Briefing Engine'), ('WIRE', 'Weekly Intelligence Report Engine')], help_text='Which engine produced the intelligence output.', max_length=10)),
                ('source_object_type', models.CharField(help_text='Model name of source object (e.g., GuidanceItem).', max_length=100)),
                ('source_object_id', models.IntegerField(help_text='PK of the source object.')),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, default='', max_length=500)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('skip_reason', models.CharField(blank=True, help_text='Why delivery was skipped (quiet hours, throttle, dedupe, etc.).', max_length=200, null=True)),
                ('dedupe_hash', models.CharField(help_text='SHA-256 hash for deduplication.', max_length=64, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra delivery metadata (notification_id, error details, etc.).')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivered_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivered Notification',
                'verbose_name_plural': 'Delivered Notifications',
                'db_table': 'core_delivered_notification',
                'ordering': ['-delivered_at'],
                'indexes': [models.Index(fields=['user', 'delivered_at'], name='idx_dne_user_delivered'), models.Index(fields=['user', 'channel', 'delivered_at'], name='idx_dne_user_chan_delivered')],
            },
        ),
    ]
