# Generated by Django 4.2.27 on 2026-02-15 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0066_delivery_notification_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualitySuppressionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_hash', models.CharField(help_text='SHA-256 of guidance_type + key evidence IDs + title', max_length=64)),
                ('suppressed_until', models.DateTimeField(help_text='Do not show this guidance again until this time')),
                ('last_seen_at', models.DateTimeField(help_text='Last time this guidance signature was generated')),
                ('last_priority', models.IntegerField(default=3, help_text='Priority when last suppressed (1=Critical, 5=Info)')),
                ('count', models.IntegerField(default=1, help_text='Number of times this guidance signature has been seen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_suppressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quality Suppression Record',
                'verbose_name_plural': 'Quality Suppression Records',
                'db_table': 'core_quality_suppression',
            },
        ),
        migrations.CreateModel(
            name='QualityMetricAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Monday of the metric week')),
                ('rule_type', models.CharField(help_text='Guidance type / rule that generated items', max_length=120)),
                ('domain', models.CharField(help_text='Module domain (health, goals, habits, etc.)', max_length=100)),
                ('delivered_count', models.IntegerField(default=0)),
                ('acted_count', models.IntegerField(default=0)),
                ('dismissed_count', models.IntegerField(default=0)),
                ('snoozed_count', models.IntegerField(default=0)),
                ('acknowledged_count', models.IntegerField(default=0)),
                ('suppressed_count', models.IntegerField(default=0)),
                ('avg_response_seconds', models.FloatField(blank=True, help_text='Average time to user action in seconds', null=True)),
                ('usefulness_score', models.FloatField(default=0.5, help_text='Composite usefulness score 0.0-1.0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quality Metric Aggregate',
                'verbose_name_plural': 'Quality Metric Aggregates',
                'db_table': 'core_quality_metric_aggregate',
                'ordering': ['-week_start', '-usefulness_score'],
                'indexes': [models.Index(fields=['week_start', 'usefulness_score'], name='idx_qmetric_week_score')],
            },
        ),
        migrations.AddConstraint(
            model_name='qualitymetricaggregate',
            constraint=models.UniqueConstraint(fields=('week_start', 'rule_type', 'domain'), name='unique_quality_metric_week_rule_domain'),
        ),
        migrations.AddIndex(
            model_name='qualitysuppressionrecord',
            index=models.Index(fields=['user', 'suppressed_until'], name='idx_suppression_user_until'),
        ),
        migrations.AddConstraint(
            model_name='qualitysuppressionrecord',
            constraint=models.UniqueConstraint(fields=('user', 'signature_hash'), name='unique_user_suppression_signature'),
        ),
    ]
