# Generated by Django 4.2.27 on 2026-02-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_icqg_quality_suppression_and_metrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligenceMetricsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(help_text='Date this snapshot covers (one per day).')),
                ('guidance_total', models.IntegerField(default=0)),
                ('guidance_acknowledged', models.IntegerField(default=0)),
                ('guidance_dismissed', models.IntegerField(default=0)),
                ('guidance_acted', models.IntegerField(default=0)),
                ('guidance_expired', models.IntegerField(default=0)),
                ('guidance_acceptance_rate', models.FloatField(default=0.0, help_text='acknowledged / total (0.0-1.0).')),
                ('guidance_action_rate', models.FloatField(default=0.0, help_text='acted / total (0.0-1.0).')),
                ('guidance_avg_response_seconds', models.FloatField(default=0.0, help_text='Average seconds from guidance creation to user action.')),
                ('predictions_total', models.IntegerField(default=0)),
                ('predictions_active', models.IntegerField(default=0)),
                ('predictions_expired', models.IntegerField(default=0)),
                ('predictions_avg_confidence', models.FloatField(default=0.0, help_text='Average confidence score across active predictions (0.0-1.0).')),
                ('deliveries_total', models.IntegerField(default=0)),
                ('deliveries_sent', models.IntegerField(default=0)),
                ('deliveries_skipped', models.IntegerField(default=0)),
                ('deliveries_failed', models.IntegerField(default=0)),
                ('deliveries_success_rate', models.FloatField(default=0.0, help_text='sent / total (0.0-1.0).')),
                ('deliveries_by_channel', models.JSONField(default=dict, help_text='Channel breakdown: {"in_app": 5, "email": 2, ...}.')),
                ('active_users_count', models.IntegerField(default=0)),
                ('avg_responsiveness_score', models.FloatField(default=0.0, help_text='Average GLOE responsiveness across active users (0.0-1.0).')),
                ('avg_usefulness_score', models.FloatField(default=0.0, help_text='Average ICQG usefulness score (0.0-1.0).')),
                ('total_suppressed', models.IntegerField(default=0, help_text='Total guidance items suppressed by quality gate.')),
                ('persona_effectiveness_scores', models.JSONField(default=dict, help_text='Per-style action/dismiss rates: {"supportive": {"total": 10, "acted": 5, "dismissed": 2, "action_rate": 0.5, "dismiss_rate": 0.2}, ...}.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_intelligencemetricssnapshot',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.AlterField(
            model_name='deliverednotification',
            name='channel',
            field=models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='intelligencemetricssnapshot',
            constraint=models.UniqueConstraint(fields=('snapshot_date',), name='unique_snapshot_per_day'),
        ),
    ]
