# Generated by Django 4.2.27 on 2026-02-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_add_blueprint_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaloperatingblueprint',
            name='accountability_style',
            field=models.CharField(choices=[('light', 'Light'), ('standard', 'Standard'), ('firm', 'Firm')], default='standard', help_text='How firm the CoS should be (light/standard/firm)', max_length=10),
        ),
        migrations.AddField(
            model_name='personaloperatingblueprint',
            name='calibration_complete',
            field=models.BooleanField(default=False, help_text='Whether initial calibration period is complete'),
        ),
        migrations.AddField(
            model_name='personaloperatingblueprint',
            name='calibration_day',
            field=models.PositiveSmallIntegerField(default=0, help_text='Day counter for calibration mode (0-14)'),
        ),
        migrations.AddField(
            model_name='personaloperatingblueprint',
            name='event_reflections_enabled',
            field=models.BooleanField(default=True, help_text='Whether CoS follows up after events with reflections'),
        ),
        migrations.AddField(
            model_name='personaloperatingblueprint',
            name='governance_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='User override history for CoS preferences'),
        ),
        migrations.AddField(
            model_name='personaloperatingblueprint',
            name='question_frequency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='How often CoS asks questions (low/medium/high)', max_length=10),
        ),
        migrations.AddField(
            model_name='personaloperatingblueprint',
            name='relationship_suggestions_enabled',
            field=models.BooleanField(default=False, help_text='Whether CoS suggests relationship actions'),
        ),
        migrations.AddField(
            model_name='personaloperatingblueprint',
            name='sensitivity_tags',
            field=models.JSONField(blank=True, default=list, help_text="Topics requiring sensitivity (e.g. ['medicine','relationships','faith'])"),
        ),
    ]
