# Generated by Django 4.2.27 on 2026-02-18 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0070_blueprint_governance_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('calendar', 'Calendar Event'), ('workout', 'Workout'), ('social', 'Social Event'), ('health', 'Health Anomaly')], max_length=20)),
                ('source_id', models.CharField(help_text='ID of the source object (LifeEvent.id, WorkoutSession.id, etc.)', max_length=100)),
                ('source_title', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('expired', 'Expired')], db_index=True, default='pending', max_length=15)),
                ('scheduled_for', models.DateTimeField(help_text='When to deliver this reflection (12-24h after event)')),
                ('questions', models.JSONField(blank=True, default=list, help_text='Pre-generated reflection questions')),
                ('answers', models.JSONField(blank=True, default=dict, help_text='User responses keyed by question index')),
                ('action_items_created', models.JSONField(blank=True, default=list, help_text='Task/event IDs created from reflection answers')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reflections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Reflection',
                'verbose_name_plural': 'Event Reflections',
                'ordering': ['-scheduled_for'],
                'indexes': [models.Index(fields=['user', 'status', 'scheduled_for'], name='core_eventr_user_id_5e0da7_idx')],
            },
        ),
    ]
