# Generated by Django 4.2.27 on 2026-02-18 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0071_eventreflection'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLearnedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stated_values', models.JSONField(blank=True, default=list, help_text="Values the user has explicitly stated (e.g., 'family first', 'discipline').")),
                ('repeated_frustrations', models.JSONField(blank=True, default=list, help_text='Recurring frustrations across conversations.')),
                ('recurring_goals', models.JSONField(blank=True, default=list, help_text='Goals mentioned repeatedly.')),
                ('non_negotiables', models.JSONField(blank=True, default=list, help_text='Things the user has said they will never compromise on.')),
                ('relationship_priorities', models.JSONField(blank=True, default=list, help_text='People and relationships explicitly prioritized.')),
                ('identity_statements', models.JSONField(blank=True, default=list, help_text="'I am' statements the user has made.")),
                ('motivational_triggers', models.JSONField(blank=True, default=list, help_text='Things that energize or motivate the user.')),
                ('avoidance_patterns', models.JSONField(blank=True, default=list, help_text='Patterns or topics the user consistently avoids.')),
                ('total_extractions', models.IntegerField(default=0)),
                ('last_extraction_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learned_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Learned Profile',
                'verbose_name_plural': 'User Learned Profiles',
                'db_table': 'core_user_learned_profile',
            },
        ),
        migrations.CreateModel(
            name='InterventionEffectivenessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_interventions', models.IntegerField(default=0)),
                ('total_accepted', models.IntegerField(default=0)),
                ('total_dismissed', models.IntegerField(default=0)),
                ('total_drift_resolved', models.IntegerField(default=0, help_text='Interventions where drift decreased within 24h.')),
                ('effectiveness_score', models.FloatField(default=0.5, help_text='0-1 score based on acceptance + drift resolution rate.')),
                ('avg_response_time_seconds', models.FloatField(default=0.0)),
                ('escalation_speed_modifier', models.FloatField(default=0.0, help_text='Modifier for escalation timing. Negative = slower, positive = faster.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_effectiveness_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_intervention_effectiveness_profile',
            },
        ),
        migrations.CreateModel(
            name='InsightEngagementProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_insights_shown', models.IntegerField(default=0)),
                ('total_viewed', models.IntegerField(default=0)),
                ('total_acted', models.IntegerField(default=0)),
                ('total_dismissed', models.IntegerField(default=0)),
                ('engagement_score', models.FloatField(default=0.5, help_text='Composite engagement score 0-1.')),
                ('preferred_severity', models.CharField(blank=True, help_text='Severity level user engages with most (info/positive/warning/critical).', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight_engagement_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_insight_engagement_profile',
            },
        ),
        migrations.CreateModel(
            name='BriefingEngagementProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_briefings_generated', models.IntegerField(default=0)),
                ('total_briefings_opened', models.IntegerField(default=0)),
                ('total_reports_generated', models.IntegerField(default=0)),
                ('total_reports_opened', models.IntegerField(default=0)),
                ('avg_time_spent_seconds', models.FloatField(default=0.0)),
                ('open_rate', models.FloatField(default=0.0, help_text='Briefings opened / briefings generated.')),
                ('preferred_length', models.CharField(default='standard', help_text='concise / standard / detailed — derived from engagement.', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='briefing_engagement_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_briefing_engagement_profile',
            },
        ),
        migrations.CreateModel(
            name='PredictionOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_value', models.FloatField(blank=True, help_text='Actual observed value at predicted_date.', null=True)),
                ('error_abs', models.FloatField(default=0.0, help_text='Absolute error: |predicted - actual|')),
                ('error_pct', models.FloatField(default=0.0, help_text='Percentage error: |predicted - actual| / |actual| * 100')),
                ('accuracy_score', models.FloatField(default=0.0, help_text='Accuracy 0-1 (1 = perfect). Based on inverse of error_pct.')),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='core.prediction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_outcomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_prediction_outcome',
                'ordering': ['-validated_at'],
                'indexes': [models.Index(fields=['user', 'validated_at'], name='core_predic_user_id_60782b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PredictionAccuracyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(max_length=120)),
                ('total_validated', models.IntegerField(default=0)),
                ('total_accurate', models.IntegerField(default=0, help_text='Count where accuracy_score >= 0.7')),
                ('avg_accuracy', models.FloatField(default=0.5)),
                ('avg_error_pct', models.FloatField(default=0.0)),
                ('confidence_adjustment', models.FloatField(default=0.0, help_text='Adjustment factor (-0.3 to +0.2) applied to future predictions.')),
                ('last_validated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_accuracy_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_prediction_accuracy_profile',
                'indexes': [models.Index(fields=['user', 'prediction_type'], name='core_predic_user_id_8524f1_idx')],
                'unique_together': {('user', 'prediction_type')},
            },
        ),
        migrations.CreateModel(
            name='LearningExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('stated_value', 'Stated Value'), ('frustration', 'Frustration'), ('recurring_goal', 'Recurring Goal'), ('non_negotiable', 'Non-Negotiable'), ('relationship_priority', 'Relationship Priority'), ('identity_statement', 'Identity Statement'), ('motivational_trigger', 'Motivational Trigger'), ('avoidance_pattern', 'Avoidance Pattern')], max_length=30)),
                ('extracted_text', models.TextField(help_text='The learned item text.')),
                ('source_message', models.TextField(blank=True, help_text='The user message this was extracted from (for transparency).')),
                ('confidence', models.FloatField(default=0.7, help_text='Extraction confidence 0-1.')),
                ('is_confirmed', models.BooleanField(default=False, help_text='Whether user has confirmed this extraction.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_extractions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_learning_extraction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'category'], name='core_learni_user_id_2949ef_idx'), models.Index(fields=['user', 'created_at'], name='core_learni_user_id_00911a_idx')],
            },
        ),
        migrations.CreateModel(
            name='InsightEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('viewed', 'Viewed'), ('acted', 'Acted Upon'), ('dismissed', 'Dismissed')], max_length=20)),
                ('event_at', models.DateTimeField(auto_now_add=True)),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='core.insight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insight_engagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_insight_engagement',
                'ordering': ['-event_at'],
                'indexes': [models.Index(fields=['user', 'event_at'], name='core_insigh_user_id_18fffa_idx'), models.Index(fields=['insight', 'event_type'], name='core_insigh_insight_e9a355_idx')],
            },
        ),
        migrations.CreateModel(
            name='BriefingEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('daily_briefing', 'Daily Briefing'), ('weekly_report', 'Weekly Report')], max_length=20)),
                ('content_id', models.PositiveIntegerField(help_text='PK of DailyBriefing or WeeklyIntelligenceReport.')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, help_text='Approximate seconds spent viewing.')),
                ('scrolled_to_end', models.BooleanField(default=False, help_text='Whether user scrolled through entire content.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefing_engagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_briefing_engagement',
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['user', 'content_type', 'opened_at'], name='core_briefi_user_id_37c167_idx')],
            },
        ),
    ]
