# Generated by Django 4.2.27 on 2026-02-19 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0072_phase4_cos_feedback_learning'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernanceAlignmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('core_values', 'Core Values'), ('success_definition', 'Success Definition'), ('chaos_protection', 'Chaos Protection'), ('top_three', 'Top Three'), ('module_classification', 'Module Classification'), ('complete', 'Complete')], default='core_values', max_length=30)),
                ('responses', models.JSONField(blank=True, default=dict, help_text='Collected responses by stage key')),
                ('pending_modules', models.JSONField(blank=True, default=list, help_text='Module keys still awaiting classification')),
                ('is_complete', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='governance_alignment_session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Governance Alignment Session',
                'verbose_name_plural': 'Governance Alignment Sessions',
                'db_table': 'core_governancealignmentsession',
            },
        ),
        migrations.CreateModel(
            name='GovernanceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(help_text="Module or area key: 'faith', 'health.weight', 'journal', 'goals', etc.", max_length=50)),
                ('display_name', models.CharField(help_text="Human-readable name shown to user (e.g. 'Morning Prayer', 'Workout')", max_length=100)),
                ('commitment_level', models.CharField(choices=[('non_negotiable', 'Non-Negotiable'), ('important', 'Important'), ('flexible', 'Flexible')], default='important', max_length=15)),
                ('importance_weight', models.FloatField(default=1.0, help_text="Multiplier for this area's impact on DriftPressure (0.3-2.0)")),
                ('escalation_preference', models.CharField(choices=[('gentle', 'Gentle'), ('direct', 'Direct'), ('firm', 'Firm')], default='direct', max_length=10)),
                ('declared_reason', models.TextField(blank=True, help_text="User's stated reason for this classification (their own words)")),
                ('tied_goal_ids', models.JSONField(blank=True, default=list, help_text='IDs of LifeGoal objects tied to this area')),
                ('review_interval_days', models.PositiveIntegerField(default=14, help_text='Days between recalibration checks')),
                ('last_reviewed_at', models.DateTimeField(blank=True, help_text='Last time user was asked about this classification', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governance_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Governance Profile',
                'verbose_name_plural': 'Governance Profiles',
                'db_table': 'core_governanceprofile',
                'ordering': ['commitment_level', 'module_key'],
                'unique_together': {('user', 'module_key')},
            },
        ),
    ]
