# Generated by Django 4.2.27 on 2026-02-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_phase5_governance_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlearnedprofile',
            name='commitments_made',
            field=models.JSONField(blank=True, default=list, help_text='Promises or commitments the user stated they would do.'),
        ),
        migrations.AddField(
            model_name='userlearnedprofile',
            name='health_concerns',
            field=models.JSONField(blank=True, default=list, help_text='Health issues, injuries, or physical concerns mentioned.'),
        ),
        migrations.AddField(
            model_name='userlearnedprofile',
            name='life_event_mentions',
            field=models.JSONField(blank=True, default=list, help_text='Upcoming life events mentioned with date/context.'),
        ),
        migrations.AlterField(
            model_name='learningextraction',
            name='category',
            field=models.CharField(choices=[('stated_value', 'Stated Value'), ('frustration', 'Frustration'), ('recurring_goal', 'Recurring Goal'), ('non_negotiable', 'Non-Negotiable'), ('relationship_priority', 'Relationship Priority'), ('identity_statement', 'Identity Statement'), ('motivational_trigger', 'Motivational Trigger'), ('avoidance_pattern', 'Avoidance Pattern'), ('health_concern', 'Health Concern'), ('life_event_mention', 'Life Event Mention'), ('commitment_made', 'Commitment Made')], max_length=30),
        ),
    ]
