# Generated by Django 4.2.27 on 2026-02-21 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0074_add_executive_memory_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrationDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dominant_scenario', models.CharField(max_length=50)),
                ('secondary_scenarios', models.JSONField(blank=True, default=list)),
                ('fused_signals', models.JSONField(blank=True, default=dict)),
                ('intervention_style', models.CharField(max_length=30)),
                ('surfaced_items', models.JSONField(blank=True, default=list)),
                ('suppressed_items', models.JSONField(blank=True, default=list)),
                ('narrative', models.TextField(blank=True, default='')),
                ('raw_signals', models.JSONField(blank=True, default=dict)),
                ('scenario_scores', models.JSONField(blank=True, default=dict)),
                ('user_response', models.CharField(blank=True, max_length=255, null=True)),
                ('outcome_score', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitration_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_arbitration_decision_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='core_arbitr_user_id_1933fe_idx'), models.Index(fields=['dominant_scenario'], name='core_arbitr_dominan_db93c1_idx')],
            },
        ),
    ]
