# Generated by Django 4.2.27 on 2026-02-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_ual_arbitration_decision_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineSpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=36)),
                ('engine_name', models.CharField(max_length=10)),
                ('span_name', models.CharField(help_text='Sub-step name: collect_signals, classify_scenario, etc.', max_length=100)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('status', models.CharField(default='success', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'core_diag_engine_span',
                'ordering': ['started_at'],
                'indexes': [models.Index(fields=['trace_id'], name='idx_engspan_trace')],
            },
        ),
        migrations.CreateModel(
            name='EngineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, help_text='UUID correlating all engine runs within one request/task.', max_length=36)),
                ('engine_name', models.CharField(help_text='Engine acronym: UAL, ICQG, DNE, DBE, SAE, PIE, PRIE, PGE, etc.', max_length=10)),
                ('phase', models.SmallIntegerField(help_text='Intelligence pipeline phase (1=Interp, 2=Exec, 3=Post).')),
                ('started_at', models.DateTimeField(help_text='When this engine execution began.')),
                ('ended_at', models.DateTimeField(blank=True, help_text='When this engine execution completed.', null=True)),
                ('duration_ms', models.IntegerField(default=0, help_text='Execution duration in milliseconds.')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('skipped', 'Skipped')], default='success', max_length=10)),
                ('error_type', models.CharField(blank=True, default='', help_text='Exception class name on error.', max_length=200)),
                ('error_message', models.TextField(blank=True, default='', help_text='Exception message on error.')),
                ('input_fingerprint', models.CharField(blank=True, default='', help_text='SHA256 of input args for dedup/correlation.', max_length=64)),
                ('output_fingerprint', models.CharField(blank=True, default='', help_text='SHA256 of output for change detection.', max_length=64)),
                ('user_id', models.IntegerField(blank=True, help_text='User ID if engine was invoked for a specific user.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Engine-specific metadata (items_processed, etc.).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_diag_engine_run',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['trace_id'], name='idx_engrun_trace'), models.Index(fields=['engine_name', '-started_at'], name='idx_engrun_eng_time'), models.Index(fields=['-started_at'], name='idx_engrun_time')],
            },
        ),
        migrations.CreateModel(
            name='DecisionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=36)),
                ('decision_type', models.CharField(choices=[('arbitration', 'Arbitration Scenario'), ('suppression', 'Quality Suppression'), ('delivery_route', 'Delivery Routing'), ('guidance_rank', 'Guidance Ranking'), ('insight_filter', 'Insight Filtering'), ('noise_budget', 'Noise Budget'), ('prediction_store', 'Prediction Storage'), ('other', 'Other')], max_length=20)),
                ('engine_name', models.CharField(help_text='Which engine made this decision.', max_length=10)),
                ('decision', models.CharField(help_text="The decision: 'SCENARIO=HEALTH_CRITICAL', 'SUPPRESS=repeat_72h'.", max_length=200)),
                ('rationale', models.TextField(blank=True, default='', help_text='Human-readable explanation of why.')),
                ('inputs_summary', models.JSONField(blank=True, default=dict, help_text='Key inputs that influenced this decision.')),
                ('affected_items', models.JSONField(blank=True, default=list, help_text='Items affected (guidance IDs, notification IDs, etc.).')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, help_text='Decision confidence score if applicable.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_diag_decision_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trace_id'], name='idx_decision_trace'), models.Index(fields=['-created_at'], name='idx_decision_time')],
            },
        ),
    ]
