# Generated by Django 4.2.27 on 2026-02-21 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0075_ual_arbitration_decision_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitrationdecisionlog',
            name='capacity_score',
            field=models.FloatField(default=0.5, help_text='Capacity composite score 0-1.'),
        ),
        migrations.AddField(
            model_name='arbitrationdecisionlog',
            name='capacity_state',
            field=models.CharField(default='NORMAL', help_text='CRITICAL / LOW / NORMAL / HIGH_CAPACITY.', max_length=20),
        ),
        migrations.AddField(
            model_name='arbitrationdecisionlog',
            name='confidence_level',
            field=models.CharField(default='MODERATE', help_text='LOW / MODERATE / HIGH based on confidence gap.', max_length=20),
        ),
        migrations.CreateModel(
            name='WeightAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(max_length=50)),
                ('signal', models.CharField(max_length=50)),
                ('baseline_weight', models.FloatField(help_text='Original weight from SCENARIO_WEIGHTS.')),
                ('adjustment_delta', models.FloatField(default=0.0, help_text='Current offset from baseline. Clamped ±0.10.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_weight_adjustment',
            },
        ),
        migrations.CreateModel(
            name='ScenarioHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dominant_scenario', models.CharField(max_length=50)),
                ('intervention_style', models.CharField(max_length=30)),
                ('capacity_state', models.CharField(default='NORMAL', max_length=20)),
                ('suppressed_count', models.IntegerField(default=0)),
                ('surfaced_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_scenario_history',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyCapacityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('capacity_score', models.FloatField(help_text='Composite capacity score 0-1.')),
                ('capacity_state', models.CharField(help_text='CRITICAL / LOW / NORMAL / HIGH_CAPACITY.', max_length=20)),
                ('sleep_deficit', models.FloatField(default=0.0)),
                ('mood_decline', models.FloatField(default=0.0)),
                ('emotional_load', models.FloatField(default=0.0)),
                ('schedule_overload', models.FloatField(default=0.0)),
                ('open_loop_count', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_daily_capacity_log',
                'ordering': ['-date'],
            },
        ),
        migrations.AddConstraint(
            model_name='weightadjustment',
            constraint=models.UniqueConstraint(fields=('user', 'scenario', 'signal'), name='unique_weight_per_user_scenario_signal'),
        ),
        migrations.AddIndex(
            model_name='scenariohistory',
            index=models.Index(fields=['user', '-date'], name='core_scenar_user_id_457b15_idx'),
        ),
        migrations.AddIndex(
            model_name='scenariohistory',
            index=models.Index(fields=['dominant_scenario'], name='core_scenar_dominan_ca9430_idx'),
        ),
        migrations.AddConstraint(
            model_name='scenariohistory',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_scenario_per_user_day'),
        ),
        migrations.AddIndex(
            model_name='dailycapacitylog',
            index=models.Index(fields=['user', '-date'], name='core_daily__user_id_c70981_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailycapacitylog',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_capacity_per_user_day'),
        ),
    ]
