# Generated by Django 4.2.27 on 2026-02-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_diagnostics_engine_run_span_decision'),
        ('core', '0076_ual_v2_stability_adaptation'),
    ]

    operations = [
    ]
