# Generated by Django 4.2.27 on 2026-02-21 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0077_merge_20260221_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentNudgeMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surfaced_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.CharField(max_length=50)),
                ('semantic_tag', models.CharField(help_text='Lightweight tag for semantic deduplication (scenario, composite, or commitment_key).', max_length=100)),
                ('trace_id', models.CharField(blank=True, default='', help_text='Optional trace ID linking to ArbitrationDecisionLog.', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_nudges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_recent_nudge_memory',
                'ordering': ['-surfaced_at'],
                'indexes': [models.Index(fields=['user', '-surfaced_at'], name='core_recent_user_id_46d40d_idx'), models.Index(fields=['semantic_tag'], name='core_recent_semanti_4fe7c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='InterventionResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scenario', models.CharField(max_length=50)),
                ('surfaced_count', models.IntegerField(default=0)),
                ('complied_count', models.IntegerField(default=0)),
                ('ignored_count', models.IntegerField(default=0)),
                ('overrode_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_response_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_intervention_response_log',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='core_interv_user_id_be30aa_idx'), models.Index(fields=['scenario'], name='core_interv_scenari_5dd739_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='interventionresponselog',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'scenario'), name='unique_intervention_response_per_user_day_scenario'),
        ),
    ]
