# Generated by Django 4.2.27 on 2026-02-21 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0078_recentnudgememory_interventionresponselog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('rerun_engine', 'Re-run Engine'), ('requeue_job', 'Requeue Last Job'), ('clear_suppression_cache', 'Clear Suppression Cache'), ('restart_scheduler', 'Restart Scheduler Task'), ('acknowledge_anomaly', 'Acknowledge Anomaly'), ('other', 'Other')], max_length=30)),
                ('engine_name', models.CharField(blank=True, default='', help_text='Target engine (if applicable).', max_length=10)),
                ('trace_id', models.CharField(blank=True, default='', help_text='Trace ID for the triggered action.', max_length=36)),
                ('notes', models.TextField(blank=True, default='', help_text='Admin notes or auto-generated context.')),
                ('result_status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('result_detail', models.TextField(blank=True, default='', help_text='Result message or error detail.')),
            ],
            options={
                'db_table': 'core_admin_intervention',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EngineExpectedCadence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_name', models.CharField(help_text='Engine acronym: UAL, SAE, PIE, etc.', max_length=10, unique=True)),
                ('expected_interval_seconds', models.IntegerField(help_text='Expected run interval in seconds.')),
                ('expected_jitter_seconds', models.IntegerField(default=60, help_text='Allowed late window before marking LATE.')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether heartbeat monitoring is enabled for this engine.')),
                ('notes', models.TextField(blank=True, default='', help_text="Admin notes about this engine's expected behavior.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_engine_expected_cadence',
                'ordering': ['engine_name'],
            },
        ),
        migrations.CreateModel(
            name='OpsNarrativeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posture', models.CharField(choices=[('OK', 'OK'), ('DEGRADED', 'Degraded'), ('AT_RISK', 'At Risk')], help_text='System posture: OK / DEGRADED / AT_RISK.', max_length=10)),
                ('headline', models.CharField(blank=True, default='', help_text='One-sentence system posture headline.', max_length=200)),
                ('bullets_now', models.JSONField(default=list, help_text='What\'s happening right now: ["UAL running normally", ...]')),
                ('recommendations', models.JSONField(default=list, help_text='Actionable recommendations: ["Re-run DBE manually", ...]')),
                ('watching_next', models.JSONField(default=list, help_text='What SAME is watching: ["PRIE cadence drift", ...]')),
                ('supporting_metrics', models.JSONField(blank=True, default=dict, help_text='Key metrics that informed this narrative.')),
            ],
            options={
                'db_table': 'core_ops_narrative_snapshot',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='idx_narrative_time')],
            },
        ),
        migrations.CreateModel(
            name='OpsAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(choices=[('P1', 'P1 — Critical'), ('P2', 'P2 — Warning'), ('P3', 'P3 — Info')], max_length=2)),
                ('engine_name', models.CharField(blank=True, default='', help_text='Affected engine (blank for cross-engine anomalies).', max_length=10)),
                ('anomaly_type', models.CharField(choices=[('MISSED_RUN', 'Missed Run'), ('ERROR_SPIKE', 'Error Spike'), ('CONFIDENCE_VOLATILITY', 'Confidence Volatility'), ('SUPPRESSION_STORM', 'Suppression Storm'), ('LOOPING_REMINDER', 'Looping Reminder'), ('ENGINE_STARVATION', 'Engine Starvation'), ('DELIVERY_RETRY_SPIKE', 'Delivery Retry Spike')], max_length=25)),
                ('summary', models.TextField(help_text='Human-readable anomaly summary.')),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='References to EngineRun / DecisionRecord / Heartbeat data.')),
                ('suggested_actions', models.JSONField(blank=True, default=list, help_text='List of suggested admin actions.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this anomaly is still active.')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When this anomaly was resolved/deactivated.', null=True)),
            ],
            options={
                'db_table': 'core_ops_anomaly',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='idx_anomaly_active'), models.Index(fields=['engine_name', '-created_at'], name='idx_anomaly_engine')],
            },
        ),
        migrations.CreateModel(
            name='EngineHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_name', models.CharField(db_index=True, max_length=10)),
                ('observed_at', models.DateTimeField(help_text='When this heartbeat was computed.')),
                ('status', models.CharField(choices=[('OK', 'OK'), ('MISSED', 'Missed'), ('LATE', 'Late'), ('ERROR', 'Error')], help_text='OK / MISSED / LATE / ERROR', max_length=10)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='When the engine last ran (from EngineRun).', null=True)),
                ('next_expected_at', models.DateTimeField(blank=True, help_text='When the next run is expected.', null=True)),
                ('lateness_seconds', models.IntegerField(default=0, help_text='How many seconds late (0 if on time or early).')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context: error counts, run counts, etc.')),
            ],
            options={
                'db_table': 'core_engine_heartbeat',
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['engine_name', '-observed_at'], name='idx_heartbeat_eng_time'), models.Index(fields=['-observed_at'], name='idx_heartbeat_time')],
            },
        ),
        migrations.AddConstraint(
            model_name='engineexpectedcadence',
            constraint=models.UniqueConstraint(fields=('engine_name',), name='unique_cadence_per_engine'),
        ),
        migrations.AddField(
            model_name='adminintervention',
            name='admin_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_interventions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='adminintervention',
            index=models.Index(fields=['-created_at'], name='idx_intervention_time'),
        ),
        migrations.AddIndex(
            model_name='adminintervention',
            index=models.Index(fields=['engine_name', '-created_at'], name='idx_intervention_eng_time'),
        ),
    ]
