# Generated by Django 4.2.27 on 2026-02-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_vegas_ops_wall_v2_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemIntegritySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='System integrity score 0.0–100.0.')),
                ('posture', models.CharField(choices=[('OPTIMAL', 'Optimal'), ('NOMINAL', 'Nominal'), ('DEGRADED', 'Degraded'), ('CRITICAL', 'Critical')], help_text='Derived from score: OPTIMAL/NOMINAL/DEGRADED/CRITICAL.', max_length=10)),
                ('components', models.JSONField(blank=True, default=dict, help_text='Score breakdown by component.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_system_integrity_snapshot',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='idx_integrity_time')],
            },
        ),
    ]
