# Generated by Django 4.2.27 on 2026-02-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_system_integrity_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsanomaly',
            name='escalation_count',
            field=models.IntegerField(default=0, help_text='Number of times this anomaly has been escalated.'),
        ),
        migrations.AddField(
            model_name='opsanomaly',
            name='last_escalated_at',
            field=models.DateTimeField(blank=True, help_text='When this anomaly was last escalated.', null=True),
        ),
        migrations.AddField(
            model_name='opsanomaly',
            name='original_severity',
            field=models.CharField(blank=True, choices=[('P1', 'P1 — Critical'), ('P2', 'P2 — Warning'), ('P3', 'P3 — Info')], default='', help_text='Severity when first created (before any escalation).', max_length=2),
        ),
    ]
