# Generated by Django 4.2.27 on 2026-02-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_anomaly_escalation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminintervention',
            name='is_system_initiated',
            field=models.BooleanField(default=False, help_text='True if triggered by autonomous remediation, not a human.'),
        ),
        migrations.AlterField(
            model_name='adminintervention',
            name='action_type',
            field=models.CharField(choices=[('rerun_engine', 'Re-run Engine'), ('requeue_job', 'Requeue Last Job'), ('clear_suppression_cache', 'Clear Suppression Cache'), ('restart_scheduler', 'Restart Scheduler Task'), ('acknowledge_anomaly', 'Acknowledge Anomaly'), ('auto_rerun_engine', 'Auto Re-run Engine'), ('auto_clear_suppression', 'Auto Clear Suppression Cache'), ('other', 'Other')], max_length=30),
        ),
    ]
