# Generated by Django 4.2.27 on 2026-02-21 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_intervention_system_initiated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasenote',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='releasenote',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
