# Generated by Django 4.2.27 on 2026-02-21 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0083_fixture_safe_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAMEExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_source', models.CharField(choices=[('scheduled', 'Scheduled (Celery Beat)'), ('manual', 'Manual (Admin)')], help_text='How this cycle was triggered.', max_length=10)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('timeout', 'Timeout'), ('skipped', 'Skipped (lock held)')], default='queued', help_text='Current execution state.', max_length=10)),
                ('celery_task_id', models.CharField(blank=True, default='', help_text='Celery AsyncResult task ID.', max_length=255)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this execution was initiated.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When execution finished.', null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Execution duration in milliseconds.', null=True)),
                ('error_detail', models.TextField(blank=True, default='', help_text='Error message if status is failed.')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='Admin who triggered manually (null for scheduled).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_same_execution_log',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='idx_same_exec_time')],
            },
        ),
    ]
