# Generated by Django 4.2.27 on 2026-02-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_engineexecutionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduler_name', models.CharField(choices=[('ISE', 'Intelligence Scheduler Engine'), ('SAME', 'SAME Monitoring Cycle')], help_text='Which scheduler process this heartbeat tracks.', max_length=10, unique=True)),
                ('last_tick_at', models.DateTimeField(db_index=True, help_text='When the scheduler last completed a cycle.')),
                ('expected_interval_seconds', models.IntegerField(help_text='Expected interval between ticks in seconds.')),
                ('cycle_result', models.JSONField(blank=True, default=dict, help_text='Summary of the last cycle (executed, skipped, failed).')),
                ('alive_threshold_multiplier', models.FloatField(default=1.5, help_text='Drift multiplier for ALIVE->DELAYED transition.')),
                ('offline_threshold_multiplier', models.FloatField(default=3.0, help_text='Drift multiplier for DELAYED->OFFLINE transition.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_scheduler_heartbeat',
            },
        ),
    ]
