# Generated by Django 4.2.27 on 2026-02-22 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0086_schedulerheartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaloperatingblueprint',
            name='cos_learning_mode_active',
            field=models.BooleanField(default=False, help_text='Independent Learning Mode toggle. When True, UAIO execution, PIE, PRIE, and domain writes are suppressed. SAE reads and governance evaluation remain active.'),
        ),
        migrations.CreateModel(
            name='UserPriorityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(help_text="Top-level module (e.g. 'health', 'faith', 'purpose')", max_length=30)),
                ('sub_module_key', models.CharField(blank=True, default='', help_text="Sub-module path (e.g. 'health.weight', 'health.cognitive.focus'). Empty string = module-level priority.", max_length=60)),
                ('declared_priority_level', models.PositiveSmallIntegerField(choices=[(1, 'Non-Negotiable'), (2, 'Important'), (3, 'Flexible')], default=3, help_text='1=Non-Negotiable, 2=Important, 3=Flexible')),
                ('importance_weight', models.DecimalField(decimal_places=1, default=1.0, help_text='Derived from priority level: 3.0 / 2.0 / 1.0', max_digits=3)),
                ('declared_reason', models.TextField(blank=True, help_text='Why this matters to the user (from Learning Mode conversation)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Priority Profile',
                'verbose_name_plural': 'User Priority Profiles',
                'ordering': ['-importance_weight', 'module_key', 'sub_module_key'],
                'unique_together': {('user', 'module_key', 'sub_module_key')},
            },
        ),
    ]
