# Generated by Django 4.2.27 on 2026-02-23 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0022_add_time_period_to_aiinsight'),
        ('core', '0087_cos_phase1_learning_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_text', models.TextField(help_text='The commitment action text (case-preserved)')),
                ('commitment_type', models.CharField(choices=[('DO', 'Do'), ('DECIDE', 'Decide'), ('SCHEDULE', 'Schedule'), ('STOP', 'Stop')], default='DO', max_length=10)),
                ('time_boundary', models.DateTimeField(help_text='Concrete deadline for this commitment')),
                ('time_boundary_display', models.CharField(blank=True, help_text="Human-readable time phrase (e.g., 'by tomorrow at 5pm')", max_length=100)),
                ('done_definition', models.TextField(blank=True, help_text='One-sentence definition of done. Required only for vague actions.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('closed_success', 'Closed — Honored'), ('closed_missed', 'Closed — Missed'), ('cancelled', 'Cancelled'), ('renegotiated', 'Renegotiated')], db_index=True, default='pending', max_length=20)),
                ('closure_type', models.CharField(blank=True, choices=[('user_confirmed', 'User Confirmed Done'), ('user_missed', 'User Confirmed Missed'), ('cancelled', 'Cancelled'), ('renegotiated', 'Replaced by Renegotiation'), ('expired', 'Expired Past Deadline')], max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('tier_at_creation', models.CharField(blank=True, help_text='CLEAN / EARLY_EROSION / STRUCTURAL_DRIFT at commitment time', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, help_text='Conversation where this commitment was created (traceability only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments', to='ai.assistantconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commitment',
                'verbose_name_plural': 'Commitments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommitmentRenegotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_time_boundary', models.DateTimeField(help_text='Time boundary before renegotiation attempt')),
                ('requested_time_boundary', models.DateTimeField(blank=True, help_text='New time boundary requested (null if no new time provided)', null=True)),
                ('tier_at_time', models.CharField(help_text='CLEAN / EARLY_EROSION / STRUCTURAL_DRIFT at renegotiation time', max_length=20)),
                ('was_blocked', models.BooleanField(default=False, help_text='True if renegotiation was blocked due to tier')),
                ('blocked_choice_selected', models.CharField(blank=True, choices=[('A', 'Keep original with minimum version'), ('B', 'Cancel and accept consequence')], help_text='Which choice user selected when blocked (A or B)', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renegotiations', to='core.commitment')),
            ],
            options={
                'verbose_name': 'Commitment Renegotiation',
                'verbose_name_plural': 'Commitment Renegotiations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['commitment', 'created_at'], name='core_commit_commitm_6d97c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommitmentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('commitments_made', models.PositiveIntegerField(default=0)),
                ('commitments_honored', models.PositiveIntegerField(default=0)),
                ('commitments_missed', models.PositiveIntegerField(default=0)),
                ('commitments_renegotiated', models.PositiveIntegerField(default=0)),
                ('commitments_cancelled', models.PositiveIntegerField(default=0)),
                ('honor_rate', models.FloatField(default=0.0, help_text='Ratio of honored / (honored + missed), 0-1')),
                ('avg_time_to_closure_minutes', models.FloatField(default=0.0, help_text='Average minutes from creation to closure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitment_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commitment Analytics',
                'verbose_name_plural': 'Commitment Analytics',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='commitment',
            index=models.Index(fields=['user', 'status'], name='core_commit_user_id_2b2d8a_idx'),
        ),
        migrations.AddIndex(
            model_name='commitment',
            index=models.Index(fields=['user', 'time_boundary'], name='core_commit_user_id_6312e5_idx'),
        ),
        migrations.AddIndex(
            model_name='commitment',
            index=models.Index(fields=['user', 'status', 'created_at'], name='core_commit_user_id_e3c8a2_idx'),
        ),
    ]
