# Generated by Django 4.2.27 on 2026-02-23 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0088_commitment_system_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='timezone_at_creation',
            field=models.CharField(blank=True, help_text="IANA timezone at commitment creation (e.g., 'America/New_York')", max_length=50),
        ),
        migrations.AddField(
            model_name='commitment',
            name='timezone_at_last_recalculation',
            field=models.CharField(blank=True, help_text='IANA timezone when time_boundary was last recalculated due to timezone change', max_length=50),
        ),
        migrations.CreateModel(
            name='Tier1OverrideEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflicting_block_description', models.TextField(help_text='Description of the block that was scheduled over Tier 1')),
                ('escalation_level_at_time', models.CharField(blank=True, help_text='CLEAN / EARLY_EROSION / STRUCTURAL_DRIFT at override time', max_length=20)),
                ('density_score_at_time', models.FloatField(default=0.0, help_text='Calendar density score (0.0-1.0) at override time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_block', models.ForeignKey(help_text='The Tier 1 block that was overridden', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='override_events_original', to='core.scheduledblock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier1_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='core_tier1o_user_id_c149e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeadlineSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_24h', models.JSONField(default=list, help_text='Commitments/goals/blocks due within 24 hours')),
                ('due_72h', models.JSONField(default=list, help_text='Commitments/goals/blocks due within 72 hours (excluding 24h)')),
                ('due_7d', models.JSONField(default=list, help_text='Commitments/goals/blocks due within 7 days (excluding 72h)')),
                ('collision_flags', models.JSONField(default=list, help_text='Pairs of deadlines with <2h gap, or days with >3 hard deadlines')),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['user', 'computed_at'], name='core_deadli_user_id_dd1281_idx')],
            },
        ),
    ]
