# Generated by Django 4.2.27 on 2026-02-23 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0089_commitment_timezone_at_creation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.PositiveSmallIntegerField(choices=[(0, 'CLEAN'), (1, 'EARLY_EROSION'), (2, 'STRUCTURAL_DRIFT')], default=0, help_text='Current escalation level (0=CLEAN, 1=EARLY_EROSION, 2=STRUCTURAL_DRIFT)')),
                ('peak_level_7d', models.PositiveSmallIntegerField(choices=[(0, 'CLEAN'), (1, 'EARLY_EROSION'), (2, 'STRUCTURAL_DRIFT')], default=0, help_text='Peak escalation level in last 7 days')),
                ('consecutive_clean_days', models.PositiveIntegerField(default=0, help_text='Number of consecutive clean days for recovery gate')),
                ('last_escalation_at', models.DateTimeField(blank=True, help_text='When escalation last increased', null=True)),
                ('last_de_escalation_at', models.DateTimeField(blank=True, help_text='When escalation last decreased (recovery gate passed)', null=True)),
                ('window_start', models.DateTimeField(blank=True, help_text='Start of current recovery evaluation window', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra state metadata (recovery reasons, etc.)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'escalation state',
                'verbose_name_plural': 'escalation states',
                'indexes': [models.Index(fields=['user'], name='core_escala_user_id_cc8862_idx')],
            },
        ),
        migrations.CreateModel(
            name='EscalationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_level', models.PositiveSmallIntegerField(help_text='Level before transition')),
                ('to_level', models.PositiveSmallIntegerField(help_text='Level after transition')),
                ('trigger', models.CharField(choices=[('THRESHOLD_OVERRIDE', 'Threshold Override'), ('RECOVERY_DECAY', 'Recovery Decay'), ('EROSION_DETECTED', 'Erosion Detected'), ('FLOOR_APPLIED', 'Floor Applied'), ('DAILY_UPDATE', 'Daily Update')], help_text='What caused this transition', max_length=30)),
                ('behavior_key', models.CharField(blank=True, help_text='Behavior key that triggered the event (if applicable)', max_length=100)),
                ('rationale', models.JSONField(default=dict, help_text='Detailed rationale for transition (recovery reasons, thresholds, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='core_escala_user_id_29fdef_idx'), models.Index(fields=['user', 'to_level'], name='core_escala_user_id_ae3ff1_idx')],
            },
        ),
        migrations.CreateModel(
            name='BehavioralTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior_key', models.CharField(help_text='Behavior key being tracked (e.g., PRAYER, WORKOUT)', max_length=100)),
                ('trend_direction', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], default='stable', max_length=10)),
                ('confidence', models.FloatField(default=0.0, help_text='Confidence in trend assessment (0.0-1.0)')),
                ('data_points', models.PositiveIntegerField(default=0, help_text='Number of events considered in computation')),
                ('window_start', models.DateField(help_text='Start of evaluation window')),
                ('window_end', models.DateField(help_text='End of evaluation window')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_trends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'behavioral trend',
                'verbose_name_plural': 'behavioral trends',
                'indexes': [models.Index(fields=['user', 'behavior_key'], name='core_behavi_user_id_cc1128_idx')],
                'unique_together': {('user', 'behavior_key')},
            },
        ),
    ]
