# Generated by Django 4.2.27 on 2026-02-23 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0090_phase3_escalation_continuity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressureWeightConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('density_weight', models.PositiveSmallIntegerField(default=30, help_text='Weight for calendar density (0–100)')),
                ('compression_weight', models.PositiveSmallIntegerField(default=20, help_text='Weight for workload compression (0–100)')),
                ('breach_weight', models.PositiveSmallIntegerField(default=20, help_text='Weight for habit breach risk (0–100)')),
                ('erosion_weight', models.PositiveSmallIntegerField(default=15, help_text='Weight for goal erosion (0–100)')),
                ('collision_weight', models.PositiveSmallIntegerField(default=15, help_text='Weight for deadline collision (0–100)')),
                ('active', models.BooleanField(default=True, help_text='Only one config should be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pressure Weight Config',
                'verbose_name_plural': 'Pressure Weight Configs',
            },
        ),
        migrations.CreateModel(
            name='PressureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure_index', models.PositiveSmallIntegerField(default=0, help_text='Composite Pressure Index (0–100)')),
                ('density_score', models.FloatField(default=0.0, help_text='Calendar density score (0.0–1.0)')),
                ('compression_score', models.FloatField(default=0.0, help_text='Workload compression score (0.0–1.0)')),
                ('breach_risk_score', models.FloatField(default=0.0, help_text='Habit breach probability (0.0–1.0)')),
                ('erosion_score', models.FloatField(default=0.0, help_text='Goal trajectory erosion score (0.0–1.0)')),
                ('collision_score', models.FloatField(default=0.0, help_text='Deadline collision score (0.0–1.0)')),
                ('horizon_days', models.PositiveSmallIntegerField(default=7, help_text='Forecast horizon in days (7, 14, or 30)')),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Baseline variance, debug info, component details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pressure_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pressure Snapshot',
                'verbose_name_plural': 'Pressure Snapshots',
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['user', '-computed_at'], name='core_pressu_user_id_690426_idx')],
            },
        ),
    ]
