# Generated by Django 4.2.27 on 2026-02-23 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0092_phase4_default_pressure_weights'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectiveRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('TIME_BLOCK_SUGGESTION', 'Time Block Suggestion'), ('EARLY_RENEGOTIATION_PROMPT', 'Early Renegotiation Prompt'), ('CAPACITY_WARNING', 'Capacity Warning'), ('DEADLINE_FOCUS_PLAN', 'Deadline Focus Plan')], max_length=30)),
                ('title', models.CharField(help_text='Short user-facing title (human language)', max_length=200)),
                ('message', models.TextField(help_text='User-facing message (human language, no jargon)')),
                ('call_to_action', models.JSONField(blank=True, default=dict, help_text='Options A/B/C with text and action_key')),
                ('status', models.CharField(choices=[('active', 'Active'), ('dismissed', 'Dismissed'), ('accepted', 'Accepted'), ('executed_elsewhere', 'Executed Elsewhere'), ('expired', 'Expired')], default='active', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=50, help_text='Higher = more urgent (0-100)')),
                ('related_object_type', models.CharField(blank=True, help_text="Model name of the related object (e.g. 'Commitment')", max_length=50)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('risk_window_start', models.DateTimeField(blank=True, help_text='Start of the risk window this recommendation covers', null=True)),
                ('risk_window_end', models.DateTimeField(blank=True, help_text='End of the risk window this recommendation covers', null=True)),
                ('dismissal_reason', models.CharField(blank=True, help_text='Why dismissed: not_relevant, bad_timing, already_handled', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Raw scores/inputs for audit (CPI, density, breach prob, etc.)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protective_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Protective Recommendation',
                'verbose_name_plural': 'Protective Recommendations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', 'created_at'], name='core_protec_user_id_58c873_idx'), models.Index(fields=['user', 'recommendation_type', '-created_at'], name='core_protec_user_id_4e90bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProtectiveAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('DEADLINE_24H', 'Deadline 24h'), ('DEADLINE_4H', 'Deadline 4h'), ('DEADLINE_1H', 'Deadline 1h'), ('CAPACITY', 'Capacity'), ('COLLISION', 'Collision')], max_length=20)),
                ('message', models.TextField(help_text='Human language alert message')),
                ('call_to_action', models.JSONField(blank=True, default=dict, help_text='CTA options for user input when required')),
                ('scheduled_for', models.DateTimeField(help_text='When this alert should be delivered')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('suppressed_by_throttle', 'Suppressed by Throttle'), ('cancelled', 'Cancelled')], default='pending', max_length=25)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Raw metrics + throttle info for audit')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protective_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Protective Alert',
                'verbose_name_plural': 'Protective Alerts',
                'ordering': ['scheduled_for'],
                'indexes': [models.Index(fields=['user', 'scheduled_for', 'delivery_status'], name='core_protec_user_id_0b91e0_idx'), models.Index(fields=['user', 'related_object_type', 'related_object_id'], name='core_protec_user_id_652c03_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProtectiveActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED_RECOMMENDATION', 'Created Recommendation'), ('DISMISSED', 'Dismissed'), ('ACCEPTED', 'Accepted'), ('ALERT_DELIVERED', 'Alert Delivered'), ('ALERT_SUPPRESSED', 'Alert Suppressed'), ('AUTO_DECISION_MADE', 'Auto Decision Made'), ('ALERT_CANCELLED', 'Alert Cancelled'), ('RECOMMENDATION_EXPIRED', 'Recommendation Expired')], max_length=30)),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('rationale', models.TextField(blank=True, help_text='Human-readable reason for this action')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protective_action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Protective Action Log',
                'verbose_name_plural': 'Protective Action Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='core_protec_user_id_115550_idx'), models.Index(fields=['event_type', '-timestamp'], name='core_protec_event_t_dc0512_idx')],
            },
        ),
    ]
