# Generated by Django 4.2.27 on 2026-02-23 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_phase5_protective_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opsanomaly',
            name='anomaly_type',
            field=models.CharField(choices=[('MISSED_RUN', 'Missed Run'), ('ERROR_SPIKE', 'Error Spike'), ('CONFIDENCE_VOLATILITY', 'Confidence Volatility'), ('SUPPRESSION_STORM', 'Suppression Storm'), ('LOOPING_REMINDER', 'Looping Reminder'), ('ENGINE_STARVATION', 'Engine Starvation'), ('DELIVERY_RETRY_SPIKE', 'Delivery Retry Spike'), ('COMMITMENT_RACE_CONDITION', 'Commitment Race Condition')], max_length=25),
        ),
        migrations.CreateModel(
            name='EngineRunToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_name', models.CharField(help_text="Engine or task name (e.g., 'run_protective_sweep').", max_length=30)),
                ('user_id', models.IntegerField(blank=True, help_text='User ID if this is a per-user engine run. Null for global tasks.', null=True)),
                ('window_key', models.CharField(help_text="Time-window key for dedup (e.g., '2026-02-23T14:00').", max_length=100)),
                ('acquired_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this token was acquired.')),
                ('expires_at', models.DateTimeField(help_text='Token expiry — stale after this time.')),
                ('acquired_by', models.CharField(help_text='Hostname-PID of the process that acquired this token.', max_length=255)),
                ('completed', models.BooleanField(default=False, help_text='Set to True when the run finishes successfully.')),
            ],
            options={
                'verbose_name': 'Engine Run Token',
                'verbose_name_plural': 'Engine Run Tokens',
                'db_table': 'core_engine_run_token',
                'indexes': [models.Index(fields=['engine_name', 'expires_at'], name='idx_run_token_expiry')],
            },
        ),
        migrations.AddConstraint(
            model_name='engineruntoken',
            constraint=models.UniqueConstraint(fields=('engine_name', 'user_id', 'window_key'), name='unique_engine_run_token'),
        ),
    ]
