# Generated by Django 4.2.27 on 2026-02-23 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0094_phase6_observability_concurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionrecord',
            name='decision_type',
            field=models.CharField(choices=[('arbitration', 'Arbitration Scenario'), ('suppression', 'Quality Suppression'), ('delivery_route', 'Delivery Routing'), ('guidance_rank', 'Guidance Ranking'), ('insight_filter', 'Insight Filtering'), ('noise_budget', 'Noise Budget'), ('prediction_store', 'Prediction Storage'), ('validation', 'Pre-Release Validation'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='opsanomaly',
            name='anomaly_type',
            field=models.CharField(choices=[('MISSED_RUN', 'Missed Run'), ('ERROR_SPIKE', 'Error Spike'), ('CONFIDENCE_VOLATILITY', 'Confidence Volatility'), ('SUPPRESSION_STORM', 'Suppression Storm'), ('LOOPING_REMINDER', 'Looping Reminder'), ('ENGINE_STARVATION', 'Engine Starvation'), ('DELIVERY_RETRY_SPIKE', 'Delivery Retry Spike'), ('COMMITMENT_RACE_CONDITION', 'Commitment Race Condition'), ('STRUCTURAL_VIOLATION', 'Structural Violation'), ('NUMERIC_DEVIATION', 'Numeric Deviation'), ('VALIDATOR_CRASH', 'Validator Crash')], max_length=25),
        ),
        migrations.CreateModel(
            name='SelfError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.IntegerField(choices=[(1, 'Minor'), (2, 'Moderate'), (3, 'Critical')], help_text='1=Minor, 2=Moderate, 3=Critical.')),
                ('category', models.CharField(choices=[('STRUCTURAL', 'Structural'), ('NUMERIC', 'Numeric'), ('GOVERNANCE', 'Governance')], help_text='STRUCTURAL, NUMERIC, or GOVERNANCE.', max_length=15)),
                ('trigger_code', models.CharField(db_index=True, help_text='Machine-readable trigger: BANNED_TERM_LEAKED, THRESHOLD_EXPOSED, VALIDATOR_CRASH, NUMERIC_DEVIATION.', max_length=50)),
                ('trigger_detail', models.TextField(blank=True, help_text='What was detected (the specific term, pattern, or error).')),
                ('original_response_hash', models.CharField(blank=True, help_text='SHA-256 of original response for correlation (not the response itself).', max_length=64)),
                ('was_blocked', models.BooleanField(default=False, help_text='True = response was replaced; False = observe-only.')),
                ('engine_run_trace_id', models.UUIDField(blank=True, help_text='Links to EngineRun trace_id for full tracing.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context (flexible).')),
                ('user', models.ForeignKey(blank=True, help_text='User context when error occurred (null for system-level).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='self_errors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Self-Error',
                'verbose_name_plural': 'Self-Errors',
                'db_table': 'core_selferror',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trigger_code', 'created_at'], name='idx_selferror_trigger_time'), models.Index(fields=['level', 'created_at'], name='idx_selferror_level_time')],
            },
        ),
    ]
