# Generated by Django 4.2.27 on 2026-02-24 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendar_engine', '0004_phase9_idempotency_not_null'),
        ('core', '0095_phase8_self_governance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstate',
            name='schedule_instability_last_updated',
            field=models.DateTimeField(blank=True, help_text='When schedule_instability_score was last recalculated.', null=True),
        ),
        migrations.AddField(
            model_name='userstate',
            name='schedule_instability_score',
            field=models.IntegerField(default=0, help_text='Rolling 7-day schedule instability points total.'),
        ),
        migrations.CreateModel(
            name='DriftSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('schedule_instability', 'Schedule Instability')], max_length=30)),
                ('window_start', models.DateField()),
                ('window_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_drift_signal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('time_shift', 'Time Shift'), ('date_change', 'Date Change'), ('canceled', 'Canceled')], max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('instability_points', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('idempotency_key', models.CharField(help_text='Deterministic key for log deduplication', max_length=128)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('calendar_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='calendar_engine.calendarevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_execution_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_schedule_execution_log',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['user', 'occurred_at'], name='core_schedu_user_id_461d2d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='scheduleexecutionlog',
            constraint=models.UniqueConstraint(fields=('user', 'idempotency_key'), name='uq_schedule_exec_log_user_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='driftsignal',
            constraint=models.UniqueConstraint(fields=('user', 'signal_type', 'window_start'), name='uq_drift_signal_user_type_window'),
        ),
    ]
