# Generated by Django 4.2.27 on 2026-02-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_phase10_rename_schedule_execution_log_to_execution_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlearnedprofile',
            name='explanation_preferences',
            field=models.JSONField(blank=True, default=list, help_text='Detected preferences for response depth: brief, detailed, etc.'),
        ),
        migrations.AddField(
            model_name='userlearnedprofile',
            name='time_patterns',
            field=models.JSONField(blank=True, default=list, help_text='Time-of-day behavioral patterns (morning routines, evening reflections).'),
        ),
        migrations.AlterField(
            model_name='learningextraction',
            name='category',
            field=models.CharField(choices=[('stated_value', 'Stated Value'), ('frustration', 'Frustration'), ('recurring_goal', 'Recurring Goal'), ('non_negotiable', 'Non-Negotiable'), ('relationship_priority', 'Relationship Priority'), ('identity_statement', 'Identity Statement'), ('motivational_trigger', 'Motivational Trigger'), ('avoidance_pattern', 'Avoidance Pattern'), ('health_concern', 'Health Concern'), ('life_event_mention', 'Life Event Mention'), ('commitment_made', 'Commitment Made'), ('explanation_preference', 'Explanation Preference'), ('time_pattern', 'Time Pattern')], max_length=30),
        ),
    ]
