# Generated by Django 4.2.27 on 2026-02-25 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0098_userlearnedprofile_explanation_preferences_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_a', models.CharField(max_length=50)),
                ('domain_b', models.CharField(max_length=50)),
                ('correlation_type', models.CharField(help_text="e.g., 'sleep_mood', 'exercise_energy', 'finance_stress'", max_length=100)),
                ('strength', models.CharField(choices=[('strong', 'Strong'), ('moderate', 'Moderate'), ('weak', 'Weak')], max_length=20)),
                ('strength_score', models.FloatField(help_text='0.0 to 1.0 — statistical strength of the correlation')),
                ('direction', models.CharField(default='positive', help_text="'positive' (both increase) or 'inverse' (one increases, other decreases)", max_length=20)),
                ('narrative', models.TextField(help_text='Natural language description for CoS to reference in conversation')),
                ('evidence_summary', models.TextField(help_text="Brief evidence explanation (e.g., '14 of 18 low-sleep days had negative mood')")),
                ('evidence', models.JSONField(default=dict, help_text='Raw data points, dates, metric values supporting the correlation')),
                ('data_points', models.IntegerField(default=0, help_text='Number of data points used to compute the correlation')),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('expired', 'Expired')], default='active', max_length=20)),
                ('dedupe_key', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_correlations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_domain_correlation',
                'ordering': ['-strength_score', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='core_domain_user_id_539a00_idx'), models.Index(fields=['user', 'correlation_type'], name='core_domain_user_id_a46f2a_idx'), models.Index(fields=['dedupe_key'], name='core_domain_dedupe__92f4d5_idx')],
            },
        ),
    ]
