# Generated by Django 4.2.27 on 2026-02-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_cdce_domain_correlation'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaloperatingblueprint',
            name='eae_enabled',
            field=models.BooleanField(default=False, help_text='Executive Arbitration Engine (Phase 8). When True, EAE controls what intelligence is surfaced across chat, push, briefings, and Command Center. When False, existing behavior is unchanged.'),
        ),
    ]
