# Generated by Django 4.2.27 on 2026-03-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_personaloperatingblueprint_eae_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='COASHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduler_score', models.IntegerField(default=100, help_text='Scheduler subsystem health score (0-100).')),
                ('engine_score', models.IntegerField(default=100, help_text='Engine subsystem health score (0-100).')),
                ('freshness_score', models.IntegerField(default=100, help_text='Intelligence freshness health score (0-100).')),
                ('overall_score', models.IntegerField(default=100, help_text='Weighted overall system health score (0-100).')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Full breakdown of all subsystem score components.')),
                ('computed_at', models.DateTimeField(help_text='When these scores were last computed.')),
            ],
            options={
                'db_table': 'core_coas_health_snapshot',
            },
        ),
        migrations.CreateModel(
            name='OperationalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsystem', models.CharField(choices=[('scheduler', 'Scheduler'), ('engine', 'Engine'), ('freshness', 'Intelligence Freshness'), ('overall', 'Overall System')], help_text='Which COAS subsystem triggered this alert.', max_length=20)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('alert', 'Alert'), ('critical', 'Critical')], help_text='Alert severity based on health score.', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', help_text='Alert lifecycle status.', max_length=15)),
                ('health_score', models.IntegerField(help_text='Health score (0-100) at time of alert.')),
                ('message', models.TextField(help_text='Human-readable alert message for CoS chat.')),
                ('diagnostic_prompt_text', models.TextField(blank=True, default='', help_text='Structured diagnostic prompt for Claude Code (critical alerts only).')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Score breakdown and contributing factors.')),
                ('dedupe_key', models.CharField(blank=True, db_index=True, help_text="Deduplication key, e.g. 'scheduler_critical'.", max_length=100)),
                ('last_notified_at', models.DateTimeField(blank=True, help_text='When admins were last notified about this alert.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When this alert was resolved (score recovered).', null=True)),
            ],
            options={
                'db_table': 'core_operational_alert',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='idx_opalert_time'), models.Index(fields=['subsystem', '-created_at'], name='idx_opalert_subsys_time'), models.Index(fields=['subsystem', 'status'], name='idx_opalert_subsys_status')],
            },
        ),
    ]
