# Generated by Django 4.2.27 on 2026-03-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_coashealthsnapshot_operationalalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineheartbeat',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('MISSED', 'Missed'), ('LATE', 'Late'), ('ERROR', 'Error'), ('NEVER_RUN', 'Never Run')], help_text='OK / MISSED / LATE / ERROR / NEVER_RUN', max_length=10),
        ),
    ]
