# Generated by Django 4.2.27 on 2026-03-08 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0101_coashealthsnapshot_operationalalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoSSituationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(auto_now=True, help_text='When this situation state was last computed.')),
                ('dominant_concern', models.TextField(blank=True, default='', help_text="The single most important thing CoS should communicate. e.g. 'Medication gap: morning dose 3h overdue'")),
                ('top_priority', models.TextField(blank=True, default='', help_text="The recommended next action. e.g. 'Log morning medications before anything else'")),
                ('situation_mode', models.CharField(choices=[('morning_orientation', 'Morning Orientation'), ('midday_checkpoint', 'Midday Checkpoint'), ('afternoon_focus', 'Afternoon Focus'), ('evening_review', 'Evening Review'), ('weekend_reflection', 'Weekend Reflection'), ('urgent_intervention', 'Urgent Intervention'), ('celebration', 'Celebration'), ('recovery', 'Recovery')], default='morning_orientation', help_text='Current interaction mode based on time, state, and signals.', max_length=30)),
                ('changes_since_last_interaction', models.JSONField(blank=True, default=list, help_text='List of {what, when, significance} dicts since last user interaction.')),
                ('escalations', models.JSONField(blank=True, default=list, help_text='Things getting worse since last check.')),
                ('resolutions', models.JSONField(blank=True, default=list, help_text='Things resolved since last check.')),
                ('opening_sentence', models.TextField(blank=True, default='', help_text="Pre-computed first sentence for CoS response. e.g. 'Good morning. Quick overview: 2 tasks due, medication not logged yet.'")),
                ('suppressed_signals', models.JSONField(blank=True, default=list, help_text='Signals filtered by EAE noise budget (transparency).')),
                ('last_user_interaction', models.DateTimeField(blank=True, help_text='When the user last interacted with the system.', null=True)),
                ('messages_since_briefing', models.IntegerField(default=0, help_text='Number of messages exchanged since last daily briefing.')),
                ('user_acknowledged_signals', models.JSONField(blank=True, default=list, help_text='Signal IDs the user has acknowledged/responded to.')),
                ('previous_dominant_concern', models.TextField(blank=True, default='', help_text='Previous dominant concern for delta detection.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cos_situation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CoS Situation State',
                'verbose_name_plural': 'CoS Situation States',
                'db_table': 'core_cos_situation_state',
                'indexes': [models.Index(fields=['user'], name='core_cos_si_user_id_b59ecd_idx'), models.Index(fields=['computed_at'], name='core_cos_si_compute_6dd270_idx'), models.Index(fields=['situation_mode'], name='core_cos_si_situati_2c9ce5_idx')],
            },
        ),
    ]
