# Generated by Django 4.2.27 on 2026-03-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_add_cos_situation_state'),
        ('core', '0102_alter_engineheartbeat_status'),
    ]

    operations = [
    ]
