# Generated by Django 4.2.27 on 2026-03-09 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0103_merge_20260308_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_type', models.CharField(choices=[('family_relationship', 'Family Relationship'), ('death', 'Death / Loss'), ('health_condition', 'Health Condition'), ('life_milestone', 'Life Milestone'), ('personal_value', 'Personal Value'), ('life_circumstance', 'Life Circumstance'), ('preference', 'Preference'), ('other', 'Other')], help_text='Category of personal fact', max_length=50)),
                ('subject_name', models.CharField(blank=True, default='', help_text="Name of the person or subject (e.g., 'Nana', 'Sarah', 'Dad')", max_length=200)),
                ('relationship', models.CharField(blank=True, default='', help_text="Relationship to user (e.g., 'wife\\'s mother', 'daughter', 'spouse')", max_length=100)),
                ('fact_text', models.TextField(help_text="Human-readable fact (e.g., 'Nana (Linda) passed away several years ago')")),
                ('confidence', models.FloatField(default=0.8, help_text='AI extraction confidence (0.0 to 1.0)')),
                ('source', models.CharField(choices=[('conversation', 'Extracted from conversation'), ('manual', 'User-provided directly')], default='conversation', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text="User can deactivate facts they don't want used")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_facts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_personal_fact',
                'ordering': ['fact_type', '-created_at'],
                'indexes': [models.Index(fields=['user', 'fact_type', 'is_active'], name='idx_pfact_user_type_active'), models.Index(fields=['user', 'is_active'], name='idx_pfact_user_active')],
            },
        ),
    ]
