# Generated by Django 4.2.27 on 2026-03-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_add_personal_fact_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMaturitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(help_text='Date this snapshot covers.', unique=True)),
                ('infrastructure_score', models.IntegerField(default=0, help_text='Infrastructure health (0-100).')),
                ('infrastructure_details', models.JSONField(blank=True, default=dict, help_text='Breakdown: scheduler, engine, freshness scores.')),
                ('intelligence_score', models.IntegerField(default=0, help_text='CoS intelligence quality (0-100).')),
                ('intelligence_details', models.JSONField(blank=True, default=dict, help_text='Breakdown: memory util, proactive delivery, domain coverage.')),
                ('safety_score', models.IntegerField(default=0, help_text='Execution safety (0-100).')),
                ('safety_details', models.JSONField(blank=True, default=dict, help_text='Breakdown: success rate, learning mode integrity.')),
                ('domain_coverage_score', models.IntegerField(default=0, help_text='Domain coverage completeness (0-100).')),
                ('domain_coverage_details', models.JSONField(blank=True, default=dict, help_text='Per-domain breakdown.')),
                ('life_impact_score', models.IntegerField(default=0, help_text='Life impact (0-100).')),
                ('life_impact_details', models.JSONField(blank=True, default=dict, help_text='Breakdown: goal progress, routine adherence, engagement.')),
                ('overall_score', models.IntegerField(default=0, help_text='Weighted composite maturity score (0-100).')),
                ('recommendations', models.JSONField(blank=True, default=list, help_text='Auto-generated improvement recommendations.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_systemmaturitysnapshot',
                'ordering': ['-snapshot_date'],
                'get_latest_by': 'snapshot_date',
            },
        ),
        migrations.AddConstraint(
            model_name='systemmaturitysnapshot',
            constraint=models.UniqueConstraint(fields=('snapshot_date',), name='unique_maturity_per_day'),
        ),
    ]
