# Generated by Django 4.2.27 on 2026-03-11 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0105_systemmaturitysnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDecisionPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_type', models.CharField(max_length=60)),
                ('context_key', models.CharField(help_text="Normalized context identifier (e.g., 'mutate_task:recurring')", max_length=120)),
                ('preferred_action', models.CharField(blank=True, max_length=20)),
                ('confirm_count', models.PositiveIntegerField(default=0)),
                ('cancel_count', models.PositiveIntegerField(default=0)),
                ('edit_count', models.PositiveIntegerField(default=0)),
                ('custom_counts', models.JSONField(blank=True, default=dict, help_text='Counts for custom option values beyond confirm/cancel/edit')),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('confidence', models.FloatField(default=0.0)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Decision Preference',
                'verbose_name_plural': 'User Decision Preferences',
                'db_table': 'core_userdecisionpreference',
                'indexes': [models.Index(fields=['user', 'intent_type'], name='core_userde_user_id_0fbcea_idx')],
                'unique_together': {('user', 'intent_type', 'context_key')},
            },
        ),
        migrations.CreateModel(
            name='PendingAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('crud', 'CRUD Confirmation'), ('disambiguation', 'Disambiguation'), ('clarification', 'Entity Clarification')], max_length=20)),
                ('intent_type', models.CharField(max_length=60)),
                ('parameters', models.JSONField(default=dict)),
                ('options', models.JSONField(blank=True, default=list)),
                ('confirmation_message', models.TextField(blank=True)),
                ('original_input', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('edited', 'Edited')], default='pending', max_length=15)),
                ('executed', models.BooleanField(default=False)),
                ('resolved_action', models.CharField(blank=True, help_text='The option the user selected (confirm/cancel/edit/etc.)', max_length=20)),
                ('recon_decision', models.CharField(blank=True, max_length=20)),
                ('recon_context', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pending Action',
                'verbose_name_plural': 'Pending Actions',
                'db_table': 'core_pendingaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', 'created_at'], name='core_pendin_user_id_27abec_idx')],
            },
        ),
    ]
