# Generated by Django 4.2.27 on 2026-03-10 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0105_systemmaturitysnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOperatingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_data', models.JSONField(default=dict, help_text='Structured behavioral synthesis keyed by dimension. Phase 1 dimensions: productive_windows, deferral_patterns, momentum_phase.')),
                ('sample_days', models.IntegerField(default=0, help_text='Number of days of usable activity data in the computation window.')),
                ('last_computed', models.DateTimeField(blank=True, help_text='When this profile was last recomputed.', null=True)),
                ('version', models.IntegerField(default=1, help_text='Schema version of profile_data structure.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operating_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Operating Profile',
                'verbose_name_plural': 'User Operating Profiles',
                'db_table': 'core_user_operating_profile',
                'indexes': [models.Index(fields=['user'], name='core_user_o_user_id_0e6a67_idx'), models.Index(fields=['last_computed'], name='core_user_o_last_co_88ee30_idx')],
            },
        ),
    ]
