# Generated by Django 4.2.27 on 2026-03-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_add_user_operating_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroperatingprofile',
            name='previous_profile_data',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of the prior profile_data before recomputation. Used for drift detection — comparing old vs new profiles.'),
        ),
        migrations.AlterField(
            model_name='useroperatingprofile',
            name='profile_data',
            field=models.JSONField(default=dict, help_text="Structured behavioral synthesis keyed by dimension. Phase 1 dimensions: productive_windows, deferral_patterns, momentum_phase. Also contains 'behavior_drift' metadata when shifts are detected."),
        ),
        migrations.AlterField(
            model_name='useroperatingprofile',
            name='version',
            field=models.IntegerField(default=2, help_text='Schema version of profile_data structure.'),
        ),
    ]
