# Generated by Django 4.2.27 on 2026-03-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_add_operating_profile_drift_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIActionMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intent_type', models.CharField(help_text='Intent type attempted (e.g. create_task, log_weight).', max_length=100)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('blocked', 'Blocked'), ('failure', 'Failure')], help_text='Action outcome: success, blocked, or failure.', max_length=10)),
                ('error_category', models.CharField(blank=True, default='', help_text='Failure/block category (e.g. safety_blocked, internal_error).', max_length=50)),
                ('duration_ms', models.IntegerField(default=0, help_text='Total execution time in milliseconds.')),
                ('user_id', models.IntegerField(blank=True, help_text='User ID (no FK to avoid joins on hot path).', null=True)),
            ],
            options={
                'db_table': 'core_ai_action_metric',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='idx_aafr_time'), models.Index(fields=['outcome', '-created_at'], name='idx_aafr_outcome_time')],
            },
        ),
    ]
