# Generated by Django 4.2.27 on 2026-03-11 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_userdecisionpreference_pendingaction'),
        ('core', '0107_add_operating_profile_drift_fields'),
    ]

    operations = [
    ]
