# Generated by Django 4.2.27 on 2026-03-11 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_add_ai_action_metric'),
        ('core', '0108_merge_20260311_0950'),
    ]

    operations = [
    ]
