# Generated by Django 4.2.27 on 2026-03-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_merge_20260311_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIThresholdConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_min_chat', models.FloatField(default=0.4, help_text='Minimum confidence to surface in chat (EAE)')),
                ('confidence_min_push', models.FloatField(default=0.6, help_text='Minimum confidence for push notifications (EAE)')),
                ('confidence_min_briefing', models.FloatField(default=0.3, help_text='Minimum confidence for briefing inclusion (EAE)')),
                ('confidence_high_threshold', models.FloatField(default=0.85, help_text='High confidence threshold (EAE)')),
                ('confidence_low_threshold', models.FloatField(default=0.5, help_text='Low confidence threshold (EAE)')),
                ('capacity_high_threshold', models.FloatField(default=0.75, help_text='User is in high-capacity state (UAL/EAE)')),
                ('capacity_normal_threshold', models.FloatField(default=0.45, help_text='User is in normal-capacity state (UAL/EAE)')),
                ('capacity_low_threshold', models.FloatField(default=0.25, help_text='User is in low-capacity state (UAL/EAE)')),
                ('budget_chat', models.PositiveSmallIntegerField(default=3, help_text='Default cognitive units per chat session (EAE)')),
                ('budget_push', models.PositiveSmallIntegerField(default=1, help_text='Default cognitive units per push notification (EAE)')),
                ('budget_global_daily', models.PositiveSmallIntegerField(default=8, help_text='Global daily cognitive unit cap across all channels (EAE)')),
                ('high_fatigue_threshold', models.FloatField(default=0.6, help_text='Fatigue score above which interventions are suppressed')),
                ('low_fatigue_threshold', models.FloatField(default=0.3, help_text='Fatigue score below which full intervention is allowed')),
                ('breach_probability_threshold', models.FloatField(default=0.6, help_text='Breach probability threshold for protective alerts')),
                ('dne_max_alerts_per_hour', models.PositiveSmallIntegerField(default=3, help_text='Maximum protective alerts per hour')),
                ('dne_max_alerts_per_day', models.PositiveSmallIntegerField(default=10, help_text='Maximum protective alerts per day')),
                ('cos_context_cache_ttl', models.PositiveIntegerField(default=45, help_text='CoS context cache TTL in seconds (fast-changing data)')),
                ('stable_cache_ttl', models.PositiveIntegerField(default=300, help_text='Stable data cache TTL in seconds (slowly-changing data)')),
                ('active', models.BooleanField(default=True, help_text='Only one config should be active at a time')),
                ('notes', models.TextField(blank=True, default='', help_text='Reason for this configuration change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Threshold Config',
                'verbose_name_plural': 'AI Threshold Configs',
            },
        ),
    ]
