# Generated by Django 4.2.27 on 2026-03-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_add_ai_threshold_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='aithresholdconfig',
            name='insight_freshness_hours',
            field=models.PositiveSmallIntegerField(default=48, help_text='Hours before stored insights are considered stale'),
        ),
        migrations.AddField(
            model_name='aithresholdconfig',
            name='max_actions_per_message',
            field=models.PositiveSmallIntegerField(default=5, help_text='Maximum actions per single chat message'),
        ),
        migrations.AddField(
            model_name='aithresholdconfig',
            name='max_backdate_days',
            field=models.PositiveSmallIntegerField(default=365, help_text='Maximum days in the past for backdated entries'),
        ),
        migrations.AddField(
            model_name='aithresholdconfig',
            name='max_cross_domain_per_day',
            field=models.PositiveSmallIntegerField(default=4, help_text='Maximum cross-domain insights per user per day'),
        ),
        migrations.AddField(
            model_name='aithresholdconfig',
            name='max_destructive_per_minute',
            field=models.PositiveSmallIntegerField(default=2, help_text='Maximum destructive actions per minute per user'),
        ),
        migrations.AddField(
            model_name='aithresholdconfig',
            name='max_future_days',
            field=models.PositiveSmallIntegerField(default=365, help_text='Maximum days in the future for scheduled actions'),
        ),
        migrations.AddField(
            model_name='aithresholdconfig',
            name='max_general_per_minute',
            field=models.PositiveSmallIntegerField(default=10, help_text='Maximum general actions per minute per user'),
        ),
        migrations.AddField(
            model_name='aithresholdconfig',
            name='max_insights_per_6h_window',
            field=models.PositiveSmallIntegerField(default=5, help_text='Maximum PIE insights per 6-hour window (noise budget)'),
        ),
        migrations.AddField(
            model_name='aithresholdconfig',
            name='max_insights_per_day',
            field=models.PositiveSmallIntegerField(default=12, help_text='Maximum PIE insights per user per day (noise budget)'),
        ),
        migrations.AddField(
            model_name='aithresholdconfig',
            name='max_notifications_per_day',
            field=models.PositiveSmallIntegerField(default=3, help_text='Maximum insight notifications per user per day'),
        ),
    ]
