# Generated by Django 4.2.27 on 2026-03-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_add_threshold_budget_and_ratelimit_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLatencySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(blank=True, help_text='User ID (no FK to avoid joins on hot path).', null=True)),
                ('path', models.CharField(default='non_stream', help_text='Pipeline path: non_stream or stream.', max_length=20)),
                ('total_ms', models.FloatField(help_text='Total end-to-end latency in milliseconds.')),
                ('stages', models.JSONField(default=dict, help_text='Stage-level latency breakdown {stage_name: duration_ms}.')),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Request metadata: model, token counts, route info.')),
            ],
            options={
                'db_table': 'core_chat_latency_snapshot',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='idx_chat_latency_time'), models.Index(fields=['user_id', '-created_at'], name='idx_chat_latency_user')],
            },
        ),
    ]
