# Generated by Django 4.2.27 on 2026-03-12 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_chat_latency_snapshot'),
        ('core', '0112_cleanup_stale_streak_plateau'),
    ]

    operations = [
    ]
