# Generated by Django 4.2.27 on 2026-03-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_merge_20260312_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminintervention',
            name='action_type',
            field=models.CharField(choices=[('rerun_engine', 'Re-run Engine'), ('requeue_job', 'Requeue Last Job'), ('clear_suppression_cache', 'Clear Suppression Cache'), ('restart_scheduler', 'Restart Scheduler Task'), ('acknowledge_anomaly', 'Acknowledge Anomaly'), ('auto_rerun_engine', 'Auto Re-run Engine'), ('auto_clear_suppression', 'Auto Clear Suppression Cache'), ('trigger_signal_aggregation', 'Trigger Signal Aggregation'), ('trigger_goal_momentum', 'Trigger Goal Momentum'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='adminintervention',
            name='engine_name',
            field=models.CharField(blank=True, default='', help_text='Target engine or pipeline subsystem (if applicable).', max_length=50),
        ),
    ]
