# Generated by Django 4.2.27 on 2026-03-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_alter_opsanomaly_anomaly_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opsanomaly',
            name='anomaly_type',
            field=models.CharField(choices=[('MISSED_RUN', 'Missed Run'), ('ERROR_SPIKE', 'Error Spike'), ('CONFIDENCE_VOLATILITY', 'Confidence Volatility'), ('SUPPRESSION_STORM', 'Suppression Storm'), ('LOOPING_REMINDER', 'Looping Reminder'), ('ENGINE_STARVATION', 'Engine Starvation'), ('DELIVERY_RETRY_SPIKE', 'Delivery Retry Spike'), ('COMMITMENT_RACE_CONDITION', 'Commitment Race Condition'), ('STRUCTURAL_VIOLATION', 'Structural Violation'), ('NUMERIC_DEVIATION', 'Numeric Deviation'), ('VALIDATOR_CRASH', 'Validator Crash'), ('VALIDATOR_SPIKE', 'Validator Block Spike'), ('SIGNAL_DROUGHT', 'Signal Drought'), ('SIGNAL_LOW_DIVERSITY', 'Signal Low Diversity')], max_length=25),
        ),
        migrations.CreateModel(
            name='ValidatorMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.CharField(choices=[('pass', 'Pass'), ('block', 'Block'), ('observe', 'Observe'), ('crash', 'Crash')], help_text='Validation outcome: pass, block, observe, or crash.', max_length=10)),
                ('policy', models.CharField(choices=[('none', 'No violation'), ('structural', 'Structural (banned terms)'), ('action_claim', 'Unverifiable action claim'), ('numeric', 'Numeric deviation'), ('crash', 'Validator crash')], default='none', help_text='Which policy triggered (if any).', max_length=15)),
                ('duration_ms', models.IntegerField(default=0, help_text='Validation execution time in milliseconds.')),
                ('user_id', models.IntegerField(blank=True, help_text='User ID (no FK to avoid joins on hot path).', null=True)),
            ],
            options={
                'db_table': 'core_validator_metric',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='idx_validator_time'), models.Index(fields=['outcome', '-created_at'], name='idx_validator_outcome_time')],
            },
        ),
    ]
