# Generated by Django 4.2.27 on 2026-03-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_rename_goals_to_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingaction',
            name='action_type',
            field=models.CharField(choices=[('crud', 'CRUD Confirmation'), ('disambiguation', 'Disambiguation'), ('clarification', 'Entity Clarification'), ('proactive_checkin', 'Proactive Check-In')], max_length=20),
        ),
    ]
