# Generated by Django 4.2.27 on 2026-03-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_add_proactive_checkin_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governanceprofile',
            name='commitment_level',
            field=models.CharField(choices=[('foundational', 'Foundational'), ('important', 'Important'), ('flexible', 'Flexible')], default='important', max_length=15),
        ),
    ]
