# Generated by Django 4.2.27 on 2026-03-23 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0120_routine_maintenance_bridge'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(help_text='Signal type: possible_completion, effort_signal, etc.', max_length=50)),
                ('domain', models.CharField(help_text='Domain: faith, health, journal, purpose.', max_length=50)),
                ('item', models.CharField(blank=True, help_text='Specific item: prayer, workout, journal_entry, etc.', max_length=100, null=True)),
                ('fingerprint', models.CharField(help_text='Unique signal identity: {type}:{domain}:{item}:{date}', max_length=255)),
                ('response', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('source', models.CharField(help_text='Where the signal was detected: journal, workout_notes, etc.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='core_signal_user_id_ba7843_idx'), models.Index(fields=['fingerprint'], name='core_signal_fingerp_4aab2c_idx')],
            },
        ),
    ]
