# Generated by Django 4.2.27 on 2026-03-23 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0121_signalfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='Name of the scheduled item (routine item name, medicine name, etc.)', max_length=200)),
                ('domain_type', models.CharField(choices=[('routine', 'Routine'), ('workout', 'Workout'), ('journal', 'Journal'), ('medicine', 'Medicine')], help_text='Which domain this item belongs to.', max_length=20)),
                ('scheduled_time', models.DateTimeField(help_text='When the item was scheduled to happen.')),
                ('actual_time', models.DateTimeField(blank=True, help_text='When the item was actually completed. Null if missed.', null=True)),
                ('execution_quality', models.CharField(choices=[('on_target', 'On Target'), ('late', 'Late'), ('missed_window', 'Missed Window'), ('missed', 'Missed')], help_text='Quality assessment of execution timing.', max_length=20)),
                ('date', models.DateField(help_text='The date this signal applies to.')),
                ('source_model', models.CharField(blank=True, help_text='Model that triggered this signal (e.g., RoutineLog, MedicineLog).', max_length=50)),
                ('source_id', models.PositiveIntegerField(blank=True, help_text='PK of the source object.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'date'], name='core_execut_user_id_8f0741_idx'), models.Index(fields=['user', 'domain_type', 'date'], name='core_execut_user_id_239990_idx'), models.Index(fields=['execution_quality'], name='core_execut_executi_9d8a0d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='executionsignal',
            constraint=models.UniqueConstraint(fields=('user', 'item_name', 'domain_type', 'date'), name='unique_execution_signal_per_item_day'),
        ),
    ]
