# Generated by Django 4.2.27 on 2026-05-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_purge_stale_fasting_correlations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cossituationstate',
            name='situation_mode',
            field=models.CharField(choices=[('morning_orientation', 'Morning Orientation'), ('midday_checkpoint', 'Midday Checkpoint'), ('afternoon_focus', 'Afternoon Focus'), ('evening_review', 'Evening Review'), ('weekend_reflection', 'Weekend Reflection'), ('urgent_intervention', 'Urgent Intervention'), ('celebration', 'Celebration'), ('recovery', 'Recovery'), ('off_rhythm', 'Off Rhythm'), ('returning', 'Returning')], default='morning_orientation', help_text='Current interaction mode based on time, state, and signals.', max_length=30),
        ),
    ]
