# Generated by Django 4.2.27 on 2026-05-25 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0124_alter_cossituationstate_situation_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthBriefingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('briefing_id', models.CharField(help_text='SHA-256 of (user, generated_at, composer_version, evidence_hash).', max_length=64, unique=True)),
                ('generated_at', models.DateTimeField(help_text='When the composer produced this briefing (UTC).')),
                ('composer_version', models.CharField(help_text='Semver string of the composer that produced this snapshot.', max_length=20)),
                ('payload', models.JSONField(help_text='Full HealthBriefing serialized to dict; never includes raw rows.')),
                ('expires_at', models.DateTimeField(help_text='generated_at + ttl_seconds. Snapshots remain queryable past this.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_briefing_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'health briefing snapshot',
                'verbose_name_plural': 'health briefing snapshots',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['user', '-generated_at'], name='core_health_user_id_587145_idx'), models.Index(fields=['expires_at'], name='core_health_expires_a69bd6_idx')],
            },
        ),
    ]
