# Generated by Django 4.2.27 on 2026-06-27 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0125_health_briefing_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorDirective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(choices=[('identity', 'Identity'), ('preference', 'Preference'), ('pattern', 'Pattern'), ('guidance', 'Guidance')], default='preference', max_length=16)),
                ('key', models.CharField(max_length=80)),
                ('observation', models.TextField(help_text='What was noticed.')),
                ('meaning', models.TextField(blank=True, help_text='Why it matters.')),
                ('behavior_change', models.TextField(help_text='How Beth should behave differently.')),
                ('confidence', models.FloatField(default=0.5)),
                ('source', models.CharField(choices=[('told', 'Told by Danny'), ('observed', 'Observed repeatedly'), ('derived', 'Derived from analysis'), ('confirmed', 'Confirmed by Danny'), ('corrected', 'Corrected by Danny')], default='observed', max_length=16)),
                ('evidence', models.TextField(blank=True, help_text="Supports 'why do you think that?'")),
                ('evidence_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('weak', 'Weak'), ('retired', 'Retired')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_reinforced_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_directives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confidence', '-evidence_count'],
                'indexes': [models.Index(fields=['user', 'status'], name='core_behavi_user_id_73b5d3_idx'), models.Index(fields=['user', '-confidence'], name='core_behavi_user_id_9872be_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='behaviordirective',
            constraint=models.UniqueConstraint(fields=('user', 'key'), name='uniq_behavior_directive_user_key'),
        ),
    ]
