# Generated by Django 4.2.27 on 2026-07-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_repair_cross_mission_milestone_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opsanomaly',
            name='engine_name',
            field=models.CharField(blank=True, default='', help_text='Affected engine or scheduled-task name (blank for cross-engine anomalies). Widened to 128 for full Celery Beat task names (OPS-1).', max_length=128),
        ),
        migrations.CreateModel(
            name='ScheduledTaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text="Celery task name, e.g. 'dashboard_v2.compute_nightly_momentum'.", max_length=128, unique=True)),
                ('ran_at', models.DateTimeField(help_text='When this task last completed.')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], default='success', max_length=10)),
                ('duration_ms', models.IntegerField(default=0, help_text='Execution duration in milliseconds (0 if unknown).')),
                ('error_message', models.TextField(blank=True, default='', help_text='Exception message on error (truncated).')),
            ],
            options={
                'db_table': 'core_scheduled_task_run',
                'ordering': ['-ran_at'],
                'indexes': [models.Index(fields=['-ran_at'], name='idx_schedrun_time')],
            },
        ),
    ]
