# Generated by Django 4.2.27 on 2026-07-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_alter_opsanomaly_engine_name_scheduledtaskrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(help_text='Date this snapshot covers (one row per day).')),
                ('measured_at', models.DateTimeField(help_text='When these values were last measured (updated intra-day).')),
                ('db_bytes', models.BigIntegerField(blank=True, help_text='pg_database_size(current_database()) in bytes; NULL if unmeasurable.', null=True)),
                ('redis_used_bytes', models.BigIntegerField(blank=True, help_text='Redis used_memory in bytes; NULL if unmeasurable.', null=True)),
                ('redis_max_bytes', models.BigIntegerField(blank=True, help_text='Redis maxmemory in bytes (0/NULL = no limit configured).', null=True)),
                ('redis_evicted_keys', models.BigIntegerField(blank=True, help_text='Cumulative Redis evicted_keys counter; NULL if unmeasurable.', null=True)),
                ('disk_used_bytes', models.BigIntegerField(blank=True, help_text='Used bytes on the monitored mount; NULL if unmeasurable.', null=True)),
                ('disk_total_bytes', models.BigIntegerField(blank=True, help_text='Total bytes on the monitored mount; NULL if unmeasurable.', null=True)),
            ],
            options={
                'db_table': 'core_storage_snapshot',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='storagesnapshot',
            constraint=models.UniqueConstraint(fields=('snapshot_date',), name='unique_storage_snapshot_per_day'),
        ),
    ]
