# Generated by Django 4.2.27 on 2026-07-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_storagesnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('anomaly_id', models.IntegerField(blank=True, null=True)),
                ('anomaly_type', models.CharField(max_length=25)),
                ('engine_name', models.CharField(blank=True, default='', max_length=128)),
                ('monitor_key', models.CharField(help_text="Recovery handler that owns this attempt (e.g. 'scheduled_task').", max_length=64)),
                ('classification', models.CharField(choices=[('R0', 'R0 — Observe only'), ('R1', 'R1 — Safe idempotent'), ('R2', 'R2 — Low-risk service'), ('R3', 'R3 — Stateful (approval)'), ('R4', 'R4 — Destructive (engineering)')], max_length=2)),
                ('phase', models.CharField(choices=[('DIAGNOSED', 'Diagnosed'), ('RECOVER_ATTEMPTED', 'Recover attempted'), ('VERIFIED', 'Verified healthy'), ('CLOSED', 'Incident closed (verified)'), ('ESCALATED', 'Escalated to engineering'), ('SKIPPED_COOLDOWN', 'Skipped — cooldown'), ('SKIPPED_UNSAFE', 'Skipped — unsafe classification')], max_length=24)),
                ('outcome', models.CharField(blank=True, choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING_VERIFICATION', 'Pending verification')], default='', max_length=24)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('action_taken', models.TextField(blank=True, default='', help_text='Deterministic description of the action.')),
                ('evidence_before', models.JSONField(blank=True, default=dict)),
                ('evidence_after', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='', help_text='Captured exception text (never swallowed).')),
            ],
            options={
                'db_table': 'core_recovery_attempt',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['anomaly_type', 'engine_name', '-created_at'], name='idx_recovery_key'), models.Index(fields=['outcome', '-created_at'], name='idx_recovery_outcome')],
            },
        ),
    ]
