# Generated by Django 4.2.27 on 2026-07-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_recoveryattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opsanomaly',
            name='anomaly_type',
            field=models.CharField(choices=[('MISSED_RUN', 'Missed Run'), ('ERROR_SPIKE', 'Error Spike'), ('CONFIDENCE_VOLATILITY', 'Confidence Volatility'), ('SUPPRESSION_STORM', 'Suppression Storm'), ('LOOPING_REMINDER', 'Looping Reminder'), ('ENGINE_STARVATION', 'Engine Starvation'), ('DELIVERY_RETRY_SPIKE', 'Delivery Retry Spike'), ('COMMITMENT_RACE_CONDITION', 'Commitment Race Condition'), ('STRUCTURAL_VIOLATION', 'Structural Violation'), ('NUMERIC_DEVIATION', 'Numeric Deviation'), ('VALIDATOR_CRASH', 'Validator Crash'), ('VALIDATOR_SPIKE', 'Validator Block Spike'), ('SIGNAL_DROUGHT', 'Signal Drought'), ('SIGNAL_LOW_DIVERSITY', 'Signal Low Diversity'), ('MATURITY_SNAPSHOT_STALE', 'Maturity Snapshot Stale')], max_length=25),
        ),
    ]
