# Generated by Django 4.2.27 on 2026-07-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_alter_opsanomaly_anomaly_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveryattempt',
            name='mode',
            field=models.CharField(choices=[('ACTIVE', 'Active (real)'), ('SHADOW', 'Shadow (simulated)')], db_index=True, default='ACTIVE', max_length=8),
        ),
        migrations.AlterField(
            model_name='recoveryattempt',
            name='outcome',
            field=models.CharField(blank=True, choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING_VERIFICATION', 'Pending verification'), ('SHADOW_SIMULATED', 'Shadow (simulated — no action taken)')], default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='recoveryattempt',
            name='phase',
            field=models.CharField(choices=[('DIAGNOSED', 'Diagnosed'), ('RECOVER_ATTEMPTED', 'Recover attempted'), ('VERIFIED', 'Verified healthy'), ('CLOSED', 'Incident closed (verified)'), ('ESCALATED', 'Escalated to engineering'), ('SKIPPED_COOLDOWN', 'Skipped — cooldown'), ('SKIPPED_UNSAFE', 'Skipped — unsafe classification'), ('SHADOW', 'Shadow — simulated only (no action)')], max_length=24),
        ),
    ]
