# Generated by Django 4.2.27 on 2026-07-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_recoveryattempt_mode_alter_recoveryattempt_outcome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveryattempt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
