# Generated by Django 4.2.27 on 2026-07-13 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0133_recoveryattempt_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichTextImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='rich_text/images/%Y/%m/')),
                ('source_label', models.CharField(blank=True, default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rich_text_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rich Text Image',
                'verbose_name_plural': 'Rich Text Images',
                'ordering': ['-created_at'],
            },
        ),
    ]
