# Generated by Django 4.2.27 on 2026-08-18 11:35

import apps.core.current_context
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0043_m1_persona_registry_reconciliation'),
        ('people', '0004_personmention_and_more'),
        ('core', '0135_expire_nutrition_transformation_correlations'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalKnowledgeFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('_statement', models.TextField(blank=True, db_column='statement', default='', help_text="ENCRYPTED. The fact in the user's own words. Data, never an instruction, and never a WLJ-authored interpretation.")),
                ('topic', models.CharField(db_index=True, default='other', help_text='Knowledge area. Topic.* are suggestions, not a constraint — an emergent topic must be storable without a deploy.', max_length=64)),
                ('subject_label', models.CharField(blank=True, db_index=True, default='', help_text='Free-text subject when no canonical entity exists. NOT an identity record — it never becomes a person.', max_length=200)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text="Sparse deterministic attributes, ONLY where unambiguous (e.g. {'relation': 'spouse', 'since': 1997}). Absent by default; a fact needing none stores none.")),
                ('provenance', models.CharField(choices=[('interview', 'Getting to Know You'), ('explicit', 'User said remember this'), ('about_me_entry', 'Added in About Me'), ('candidate_accepted', 'Accepted from conversation'), ('imported', 'Imported'), ('legacy_extraction', 'Legacy extraction (unverified)')], db_index=True, default='about_me_entry', help_text='How this was acquired. Permanent.', max_length=32)),
                ('sensitivity', models.CharField(choices=[('normal', 'Normal'), ('sensitive', 'Sensitive')], db_index=True, default='normal', help_text='SENSITIVE is excluded from standing context entirely; it is retrievable only on-subject.', max_length=16)),
                ('review_state', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('reviewed', 'Reviewed by user'), ('user_authored', 'Authored by user')], db_index=True, default='user_authored', help_text='Only reviewed/user-authored knowledge may enter standing context.', max_length=16)),
                ('confidence', models.FloatField(default=1.0, help_text='Extraction confidence. Explicitly taught facts are 1.0.')),
                ('fact_status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded by a correction')], db_index=True, default='active', help_text='A correction marks the old row SUPERSEDED and creates a new ACTIVE row. History is preserved, never destroyed.', max_length=16)),
                ('pinned', models.BooleanField(db_index=True, default=False, help_text='User forced this into the always-on standing tier (still subject to the hard cap and the absolute sensitivity exclusion).')),
                ('as_of', models.DateField(blank=True, help_text='When the fact became true, if the user supplied it. WLJ never infers a precision the user did not give.', null=True)),
                ('source_conversation', models.ForeignKey(blank=True, help_text="Where it came from — makes 'forget everything from that chat' possible.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_knowledge_facts', to='ai.assistantconversation')),
                ('subject_person', models.ForeignKey(blank=True, help_text='Canonical people.Person this fact is about, when one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_knowledge_facts', to='people.person')),
                ('superseded_by', models.ForeignKey(blank=True, help_text='The correction that replaced this fact.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='core.personalknowledgefact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal Knowledge Fact',
                'verbose_name_plural': 'Personal Knowledge Facts',
                'db_table': 'core_personal_knowledge_fact',
                'ordering': ['topic', '-created_at'],
                'indexes': [models.Index(fields=['user', 'fact_status', 'status'], name='idx_pk_user_factstatus'), models.Index(fields=['user', 'topic', 'fact_status'], name='idx_pk_user_topic'), models.Index(fields=['user', 'sensitivity', 'review_state'], name='idx_pk_user_sens_review'), models.Index(fields=['user', 'pinned'], name='idx_pk_user_pinned')],
            },
            bases=(apps.core.current_context.NarratableMixin, models.Model),
        ),
    ]
