# Generated by Django 4.2.27 on 2026-09-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_accept_owner_legacy_personal_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalknowledgefact',
            name='last_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When the user last confirmed this is still true. Confirming pushes the horizon forward rather than creating a duplicate fact.', null=True),
        ),
        migrations.AddField(
            model_name='personalknowledgefact',
            name='revalidate_after',
            field=models.DateField(blank=True, db_index=True, help_text='Situational facts only. NOT an expiry date and never a deletion trigger: past this date the fact stops being treated as unquestioned current truth and becomes something to CHECK. WLJ never decides a fact stopped being true because time passed — only the person can say that. NULL means durable: no horizon, no revalidation.', null=True),
        ),
    ]
