# Generated by Django 4.2.27 on 2026-02-18 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='How the user refers to this person', max_length=200)),
                ('person_type', models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('mentor', 'Mentor'), ('other', 'Other')], default='other', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this person')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive people are hidden but not deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_people', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='InteractionSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_date', models.DateField()),
                ('signal_type', models.CharField(choices=[('mention', 'Mention in text'), ('event', 'Calendar event'), ('call', 'Phone call'), ('message', 'Message'), ('manual', 'Manual entry')], default='mention', max_length=20)),
                ('confidence', models.FloatField(default=0.8, help_text='How confident the system is in this match (0.0-1.0)')),
                ('source_type', models.CharField(choices=[('journal', 'Journal Entry'), ('calendar', 'Calendar Event'), ('reflection', 'Reflection Answer'), ('manual', 'Manual Entry'), ('chat', 'Chat Conversation')], max_length=20)),
                ('source_id', models.CharField(blank=True, help_text='ID of the source record', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='ai_relationships.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interaction Signal',
                'verbose_name_plural': 'Interaction Signals',
                'ordering': ['-signal_date'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(help_text='Specific relationship: spouse, child, parent, friend, boss, etc.', max_length=50)),
                ('importance_tier', models.PositiveSmallIntegerField(default=3, help_text='1=innermost circle, 2=close, 3=outer circle')),
                ('cadence_target', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], help_text='How often the user wants to connect with this person', max_length=15)),
                ('last_interaction', models.DateField(blank=True, help_text='Date of most recent interaction signal', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='ai_relationships.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relationship',
                'verbose_name_plural': 'Relationships',
                'ordering': ['importance_tier', 'person__display_name'],
                'unique_together': {('user', 'person')},
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['user', 'is_active'], name='ai_relation_user_id_9d3dcd_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionsignal',
            index=models.Index(fields=['user', 'person', 'signal_date'], name='ai_relation_user_id_631953_idx'),
        ),
    ]
