# Generated by Django 4.2.27 on 2026-01-14 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this capture entry', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Title for this capture (can be auto-generated from summary)', max_length=255)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Duration of the audio recording in seconds', null=True)),
                ('audio_file_url', models.URLField(blank=True, help_text='S3 signed URL for the audio file', max_length=500)),
                ('audio_expires_at', models.DateTimeField(blank=True, help_text='When the S3 signed URL expires', null=True)),
                ('transcript', models.TextField(blank=True, help_text='Full transcript from Whisper')),
                ('summary', models.TextField(blank=True, help_text='AI-generated BLUF summary')),
                ('category', models.CharField(blank=True, choices=[('faith', 'Faith'), ('organize', 'Organize')], help_text='Primary category for this capture', max_length=20)),
                ('subcategory', models.CharField(blank=True, choices=[('sermon', 'Sermon'), ('bible_study', 'Bible Study'), ('devotional', 'Devotional'), ('meeting', 'Meeting'), ('notes', 'Notes'), ('personal', 'Personal')], help_text='Subcategory for this capture', max_length=20)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('transcribing', 'Transcribing'), ('summarizing', 'Summarizing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='uploading', help_text='Current processing status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('user', models.ForeignKey(help_text='User who created this capture', on_delete=django.db.models.deletion.CASCADE, related_name='capture_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Capture Entry',
                'verbose_name_plural': 'Capture Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='capture_cap_user_id_870d87_idx'), models.Index(fields=['status', '-created_at'], name='capture_cap_status_6e0a77_idx'), models.Index(fields=['category', '-created_at'], name='capture_cap_categor_33d0d0_idx')],
            },
        ),
    ]
