# Generated by Django 4.2.27 on 2026-01-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='captureentry',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the audio expiration reminder email was sent', null=True),
        ),
    ]
