# Generated by Django 4.2.27 on 2026-01-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0002_add_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='captureentry',
            name='completion_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the delayed processing completion email was sent', null=True),
        ),
    ]
