# Generated by Django 4.2.27 on 2026-01-23 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capture', '0003_add_completion_email_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='captureentry',
            name='pending_client_id',
            field=models.CharField(blank=True, help_text='Links to PendingCapture.client_id for upload tracking', max_length=36),
        ),
        migrations.CreateModel(
            name='PendingCapture',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this pending capture', primary_key=True, serialize=False)),
                ('client_id', models.CharField(help_text='UUID generated by client browser for this recording', max_length=36)),
                ('device_name', models.CharField(blank=True, help_text='Device/browser identifier for cross-device awareness', max_length=100)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Duration of the recording in seconds', null=True)),
                ('file_size_bytes', models.PositiveIntegerField(blank=True, help_text='Size of the audio file in bytes', null=True)),
                ('mime_type', models.CharField(default='audio/webm', help_text='MIME type of the audio file', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Upload'), ('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('downloaded', 'Downloaded'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], db_index=True, default='pending', help_text='Current status of this pending capture', max_length=20)),
                ('upload_attempts', models.PositiveSmallIntegerField(default=0, help_text='Number of upload attempts made')),
                ('last_upload_attempt_at', models.DateTimeField(blank=True, help_text='When the last upload attempt was made', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Error message from last failed attempt')),
                ('last_heartbeat_at', models.DateTimeField(auto_now_add=True, help_text='Last time client pinged (for stale detection)')),
                ('last_reminder_at', models.DateTimeField(blank=True, help_text='When the last reminder notification was sent', null=True)),
                ('is_partial', models.BooleanField(default=False, help_text='True if this is from an interrupted recording (user navigated away)')),
                ('capture_entry', models.OneToOneField(blank=True, help_text='The CaptureEntry created when upload succeeded', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_capture', to='capture.captureentry')),
                ('user', models.ForeignKey(help_text='User who created this pending capture', on_delete=django.db.models.deletion.CASCADE, related_name='pending_captures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pending Capture',
                'verbose_name_plural': 'Pending Captures',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', '-created_at'], name='capture_pen_user_id_ae8abe_idx'), models.Index(fields=['client_id'], name='capture_pen_client__0abf9b_idx')],
                'unique_together': {('user', 'client_id')},
            },
        ),
    ]
