# Generated by Django 4.2.27 on 2026-03-17 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0004_pending_capture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(help_text='Signal taxonomy type (e.g., health_activity, faith_practice)', max_length=30)),
                ('domain', models.CharField(help_text='LifeDomain slug (e.g., health, faith)', max_length=20)),
                ('confidence', models.FloatField(help_text='Validated extraction confidence 0.0-1.0')),
                ('extracted_text', models.TextField(help_text='The phrase from the transcript indicating this behavior')),
                ('direction', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], default='positive', help_text='Positive = behavior occurred, Negative = skipped/missed', max_length=10)),
                ('extractor_type', models.CharField(help_text='Which extractor produced this (emotional_tone, health_behavior, etc.)', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_signals', to='capture.captureentry')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entry', 'signal_type'], name='capture_cap_entry_i_80749c_idx'), models.Index(fields=['entry', 'created_at'], name='capture_cap_entry_i_7c99da_idx')],
            },
        ),
    ]
