# Generated by Django 4.2.27 on 2026-07-11 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capture', '0005_phase55_extraction_signals'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultimodalArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sha256', models.CharField(db_index=True, help_text='Content hash — artifact-level dedup + integrity. WLJ hashes; never parses.', max_length=64)),
                ('content_type', models.CharField(max_length=100)),
                ('storage_ref', models.CharField(blank=True, max_length=500)),
                ('kind', models.CharField(blank=True, help_text='Model-declared kind (scale_photo, dexcom, receipt, …) — a label, not truth.', max_length=50)),
                ('status', models.CharField(choices=[('received', 'Received'), ('resolved', 'Resolved'), ('duplicate', 'Duplicate'), ('rejected', 'Rejected')], default='received', max_length=20)),
                ('resolved_intent', models.CharField(blank=True, max_length=80)),
                ('resolved_object_type', models.CharField(blank=True, max_length=80)),
                ('resolved_object_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimodal_artifacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Multimodal Artifact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='multimodalartifact',
            constraint=models.UniqueConstraint(fields=('user', 'sha256'), name='uniq_user_artifact_hash'),
        ),
    ]
