# Generated by Django 4.2.27 on 2026-07-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0006_multimodalartifact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimodalartifact',
            name='byte_size',
            field=models.PositiveIntegerField(blank=True, help_text='Original size in bytes (metadata + integrity check).', null=True),
        ),
        migrations.AddField(
            model_name='multimodalartifact',
            name='storage_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('stored', 'Stored'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', help_text='Durable-storage lifecycle. Written by the background persist task.', max_length=20),
        ),
    ]
