# Generated by Django 4.2.27 on 2026-07-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0007_multimodalartifact_byte_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimodalartifact',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Deterministically extracted text/transcript (pdfplumber, Whisper, …). Literal decode — never an interpretation. The model reasons over this.'),
        ),
        migrations.AddField(
            model_name='multimodalartifact',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, help_text='Pages/segments (metadata).', null=True),
        ),
        migrations.AddField(
            model_name='multimodalartifact',
            name='perception_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed'), ('unsupported', 'Unsupported'), ('none', 'None')], db_index=True, default='none', help_text='Deterministic-extraction lifecycle. Written by the background perceive task.', max_length=20),
        ),
    ]
