# Generated by Django 4.2.27 on 2026-07-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0008_multimodalartifact_extracted_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimodalartifact',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Filename the user uploaded (identity + retrieval; may be blank for chat images).', max_length=255),
        ),
    ]
