# Generated by Django 4.2.27 on 2026-07-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0009_multimodalartifact_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimodalartifact',
            name='frames',
            field=models.JSONField(blank=True, default=list, help_text="Video only: sampled representative frames [{t: seconds, b64: jpeg}] delivered to the model's image-perception path. Deterministic decode."),
        ),
        migrations.AlterField(
            model_name='multimodalartifact',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, help_text='Pages/segments/frames (metadata).', null=True),
        ),
    ]
