# Generated by Django 4.2.27 on 2026-07-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0010_multimodalartifact_frames_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimodalartifact',
            name='source_conversation_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
