# Generated by Django 4.2.27 on 2026-07-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0011_multimodalartifact_source_conversation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimodalartifact',
            name='associations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
