# Generated by Django 5.2.9 on 2025-12-25 02:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "is_faith_specific",
                    models.BooleanField(
                        default=False,
                        help_text="Only show when Faith module is enabled",
                    ),
                ),
                ("scripture_reference", models.CharField(blank=True, max_length=100)),
                ("scripture_text", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prompts",
                        to="core.category",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("entry_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "mood",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("great", "Great"),
                            ("good", "Good"),
                            ("okay", "Okay"),
                            ("low", "Low"),
                            ("difficult", "Difficult"),
                        ],
                        max_length=20,
                    ),
                ),
                ("word_count", models.PositiveIntegerField(default=0)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="journal_entries", to="core.category"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="journal_entries", to="core.tag"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entries",
                        to="journal.journalprompt",
                    ),
                ),
            ],
            options={
                "verbose_name": "journal entry",
                "verbose_name_plural": "journal entries",
                "ordering": ["-entry_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EntryLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        help_text="The model type of the target (e.g., 'journal.JournalEntry', 'health.FastingWindow')",
                        max_length=50,
                    ),
                ),
                ("target_id", models.PositiveIntegerField()),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("related", "Related"),
                            ("inspired_by", "Inspired By"),
                            ("during", "During"),
                            ("reflection_on", "Reflection On"),
                        ],
                        default="related",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_links",
                        to="journal.journalentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("source", "target_type", "target_id")},
            },
        ),
    ]
