# Generated by Django 4.2.27 on 2026-01-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_add_created_via_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('emoji', models.CharField(help_text='Emoji representation', max_length=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='emotions',
            field=models.ManyToManyField(blank=True, help_text="How you're feeling (select multiple)", related_name='journal_entries', to='journal.emotion'),
        ),
    ]
