# Generated by Django 4.2.27 on 2026-01-12

from django.db import migrations


def create_emotions(apps, schema_editor):
    """Create default emotions for journal entries."""
    Emotion = apps.get_model('journal', 'Emotion')

    emotions_data = [
        # Original mood-like emotions
        {'name': 'Great', 'slug': 'great', 'emoji': '😊', 'order': 1},
        {'name': 'Good', 'slug': 'good', 'emoji': '🙂', 'order': 2},
        {'name': 'Okay', 'slug': 'okay', 'emoji': '😐', 'order': 3},
        {'name': 'Low', 'slug': 'low', 'emoji': '😔', 'order': 4},
        {'name': 'Difficult', 'slug': 'difficult', 'emoji': '😢', 'order': 5},
        # New requested emotions
        {'name': 'Angry', 'slug': 'angry', 'emoji': '😠', 'order': 6},
        {'name': 'Sad', 'slug': 'sad', 'emoji': '😢', 'order': 7},
        {'name': 'Excited', 'slug': 'excited', 'emoji': '🤩', 'order': 8},
        {'name': 'Anxious', 'slug': 'anxious', 'emoji': '😰', 'order': 9},
        # Additional useful emotions
        {'name': 'Grateful', 'slug': 'grateful', 'emoji': '🙏', 'order': 10},
        {'name': 'Hopeful', 'slug': 'hopeful', 'emoji': '🌟', 'order': 11},
        {'name': 'Calm', 'slug': 'calm', 'emoji': '😌', 'order': 12},
        {'name': 'Tired', 'slug': 'tired', 'emoji': '😴', 'order': 13},
        {'name': 'Energetic', 'slug': 'energetic', 'emoji': '⚡', 'order': 14},
    ]

    for data in emotions_data:
        Emotion.objects.get_or_create(
            slug=data['slug'],
            defaults={
                'name': data['name'],
                'emoji': data['emoji'],
                'order': data['order'],
                'is_active': True,
            }
        )


def remove_emotions(apps, schema_editor):
    """Remove default emotions."""
    Emotion = apps.get_model('journal', 'Emotion')
    slugs = [
        'great', 'good', 'okay', 'low', 'difficult',
        'angry', 'sad', 'excited', 'anxious',
        'grateful', 'hopeful', 'calm', 'tired', 'energetic',
    ]
    Emotion.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_add_emotions'),
    ]

    operations = [
        migrations.RunPython(create_emotions, remove_emotions),
    ]
