# Generated by Django 4.2.27 on 2026-03-14 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_populate_emotions'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(help_text='Signal taxonomy type (e.g., health_activity, faith_practice)', max_length=30)),
                ('domain', models.CharField(help_text='LifeDomain slug (e.g., health, faith, mind)', max_length=20)),
                ('confidence', models.FloatField(help_text='Extraction confidence 0.0-1.0')),
                ('extracted_text', models.TextField(help_text='The exact phrase from the journal that indicates this behavior')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='journal.journalentry')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entry', 'signal_type'], name='journal_jou_entry_i_10bce7_idx')],
            },
        ),
    ]
