# Generated by Django 4.2.27 on 2026-03-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_add_stressed_overwhelmed_emotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
    ]
