# Generated by Django 4.2.27 on 2026-07-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_routine_maintenance_bridge_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='body_plain',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
