# Generated by Django 4.2.27 on 2026-07-19 22:06

import apps.core.current_context
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0014_normalize_mention_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('state', models.CharField(choices=[('active', 'Active'), ('reviewing', 'Reviewing'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=12)),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate, help_text='The date this journal is about')),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('generated_draft', models.TextField(blank=True, default='')),
                ('resulting_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_conversations', to='journal.journalentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'state'], name='journal_jou_user_id_777f5c_idx')],
            },
            bases=(apps.core.current_context.NarratableMixin, models.Model),
        ),
    ]
