# Generated by Django 4.2.27 on 2026-07-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_journalconversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='entry_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
