# Generated by Django 4.2.27 on 2026-07-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0016_journalentry_entry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalconversation',
            name='written_body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
