# Generated by Django 4.2.27 on 2026-03-02 02:04

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scan', '0002_add_image_analysis'),
        ('health', '0049_alter_workoutplan_days_per_week'),
        ('life', '0016_task_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Household name (e.g., 'Jenkins Family')", max_length=100)),
                ('grocery_cycle_days', models.PositiveIntegerField(default=7, help_text='Typical days between grocery trips')),
                ('primary_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_households', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Household',
                'verbose_name_plural': 'Households',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_name', models.CharField(db_index=True, help_text="Normalized name (e.g., 'chicken breast')", max_length=200, unique=True)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Alternative names: ["chicken", "boneless chicken", "pollo"]')),
                ('category', models.CharField(choices=[('protein', 'Protein'), ('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('grain', 'Grain/Carb'), ('dairy', 'Dairy'), ('fat', 'Fat/Oil'), ('spice', 'Spice/Seasoning'), ('condiment', 'Condiment/Sauce'), ('beverage', 'Beverage'), ('legume', 'Legume/Bean'), ('nut', 'Nut/Seed'), ('sweetener', 'Sweetener'), ('baking', 'Baking'), ('other', 'Other')], db_index=True, max_length=20)),
                ('carb_density', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Carbs per 100g', max_digits=6)),
                ('protein_density', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Protein per 100g', max_digits=6)),
                ('storage_type', models.CharField(choices=[('pantry', 'Pantry/Shelf'), ('refrigerator', 'Refrigerator'), ('freezer', 'Freezer'), ('counter', 'Counter')], default='pantry', max_length=20)),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, help_text='Typical shelf life in days', null=True)),
                ('substitution_group', models.CharField(blank=True, db_index=True, help_text="Group for interchangeable ingredients (e.g., 'poultry')", max_length=100)),
                ('default_unit', models.CharField(default='g', help_text='Default measurement unit', max_length=30)),
                ('default_quantity', models.DecimalField(decimal_places=2, default=Decimal('100'), help_text='Default quantity in default_unit', max_digits=8)),
                ('low_carb_alternative', models.ForeignKey(blank=True, help_text='Lower-carb substitute for diabetes-aware planning', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='meals.ingredient')),
                ('nutrition_source', models.ForeignKey(blank=True, help_text='Primary FoodItem for nutrition data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_links', to='health.fooditem')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'ordering': ['canonical_name'],
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('projected_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=Decimal('0.5'), max_digits=3)),
                ('notes', models.TextField(blank=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='meals.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meal Plan',
                'verbose_name_plural': 'Meal Plans',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('raw_text', models.TextField(blank=True, help_text='Raw OCR text from receipt')),
                ('parsed_json', models.JSONField(blank=True, default=dict, help_text='Structured parse result')),
                ('store', models.CharField(blank=True, max_length=200)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='meals.household')),
                ('scan_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='scan.scanlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['-receipt_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_name', models.CharField(max_length=300)),
                ('raw_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=8)),
                ('unit', models.CharField(default='piece', max_length=20)),
                ('match_confidence', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Confidence of ingredient match (0-1)', max_digits=3)),
                ('ingredient', models.ForeignKey(blank=True, help_text='Matched ingredient (null if unmatched)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_items', to='meals.ingredient')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='meals.receipt')),
            ],
            options={
                'verbose_name': 'Receipt Item',
                'verbose_name_plural': 'Receipt Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10)),
                ('unit', models.CharField(default='piece', max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='How confident we are this is still in stock (0-1)', max_digits=3)),
                ('last_confirmed_at', models.DateTimeField(default=django.utils.timezone.now, help_text="When the user last confirmed this item's presence")),
                ('expiration_date_estimated', models.DateField(blank=True, help_text='Estimated expiration based on shelf life', null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_items', to='meals.household')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pantry_entries', to='meals.ingredient')),
            ],
            options={
                'verbose_name': 'Pantry Item',
                'verbose_name_plural': 'Pantry Items',
                'ordering': ['ingredient__canonical_name'],
                'unique_together': {('household', 'ingredient')},
            },
        ),
        migrations.CreateModel(
            name='MealPlanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='dinner', max_length=10)),
                ('serving_count', models.PositiveSmallIntegerField(default=1)),
                ('inventory_impact_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of ingredients needed vs available at plan time')),
                ('score', models.DecimalField(blank=True, decimal_places=3, help_text='Meal score when this entry was planned', max_digits=5, null=True)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='meals.mealplan')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_entries', to='life.recipe')),
            ],
            options={
                'verbose_name': 'Meal Plan Entry',
                'verbose_name_plural': 'Meal Plan Entries',
                'ordering': ['date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delta_quantity', models.DecimalField(decimal_places=3, help_text='Positive = added, negative = consumed/removed', max_digits=10)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('receipt', 'Receipt Scan'), ('meal_plan', 'Meal Plan Deduction'), ('expiration', 'Expired Removal'), ('correction', 'User Correction')], default='manual', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('pantry_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='meals.pantryitem')),
            ],
            options={
                'verbose_name': 'Inventory Transaction',
                'verbose_name_plural': 'Inventory Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DietaryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('carb_limit_daily', models.DecimalField(blank=True, decimal_places=1, help_text='Max daily carbs in grams', max_digits=6, null=True)),
                ('protein_target_daily', models.DecimalField(blank=True, decimal_places=1, help_text='Target daily protein in grams', max_digits=6, null=True)),
                ('calorie_target', models.PositiveIntegerField(blank=True, help_text='Target daily calories', null=True)),
                ('fat_limit_daily', models.DecimalField(blank=True, decimal_places=1, help_text='Max daily fat in grams', max_digits=6, null=True)),
                ('dietary_flags', models.JSONField(blank=True, default=list, help_text='Flags: ["vegetarian", "gluten_free", "dairy_free", ...]')),
                ('diabetes_sensitive', models.BooleanField(default=False, help_text='Enable diabetes-aware meal scoring (lower glycemic, carb-conscious)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dietary Profile',
                'verbose_name_plural': 'Dietary Profiles',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, help_text="Amount (null for 'to taste')", max_digits=8, null=True)),
                ('unit', models.CharField(choices=[('tsp', 'teaspoon'), ('tbsp', 'tablespoon'), ('fl_oz', 'fluid ounce'), ('cup', 'cup'), ('ml', 'milliliter'), ('l', 'liter'), ('g', 'gram'), ('oz', 'ounce'), ('lb', 'pound'), ('kg', 'kilogram'), ('piece', 'piece'), ('slice', 'slice'), ('clove', 'clove'), ('bunch', 'bunch'), ('sprig', 'sprig'), ('pinch', 'pinch'), ('dash', 'dash'), ('can', 'can'), ('jar', 'jar'), ('package', 'package'), ('to_taste', 'to taste'), ('as_needed', 'as needed')], default='piece', max_length=20)),
                ('preparation_notes', models.CharField(blank=True, help_text="e.g., 'diced', 'minced', 'room temperature'", max_length=200)),
                ('is_optional', models.BooleanField(default=False)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('original_text', models.CharField(blank=True, help_text='Original free-text line before parsing', max_length=300)),
                ('parse_confidence', models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Confidence of the parse (0-1)', max_digits=3)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_uses', to='meals.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_ingredients', to='life.recipe')),
            ],
            options={
                'verbose_name': 'Recipe Ingredient',
                'verbose_name_plural': 'Recipe Ingredients',
                'ordering': ['order_index'],
                'unique_together': {('recipe', 'ingredient', 'order_index')},
            },
        ),
        migrations.CreateModel(
            name='HouseholdMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='meals.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Household Membership',
                'verbose_name_plural': 'Household Memberships',
                'unique_together': {('household', 'user')},
            },
        ),
    ]
