# Generated by Django 4.2.27 on 2026-03-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='meals_activated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when meal intelligence met minimum activation threshold', null=True),
        ),
    ]
