# Generated by Django 4.2.27 on 2026-03-02 14:05

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_add_meals_activated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('receipt', 'Receipt Scan'), ('meal_plan', 'Meal Plan Deduction'), ('expiration', 'Expired Removal'), ('correction', 'User Correction'), ('photo_scan', 'Photo Scan')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='PantryScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_type', models.CharField(choices=[('fridge', 'Fridge'), ('pantry', 'Pantry Shelf'), ('freezer', 'Freezer')], max_length=10)),
                ('overall_confidence', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Average confidence of confirmed detections', max_digits=3)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the session was confirmed/completed', null=True)),
                ('items_detected', models.PositiveIntegerField(default=0, help_text='Total items detected by AI')),
                ('items_confirmed', models.PositiveIntegerField(default=0, help_text='Items confirmed by user')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_scan_sessions', to='meals.household')),
            ],
            options={
                'verbose_name': 'Pantry Scan Session',
                'verbose_name_plural': 'Pantry Scan Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PantryPhotoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Photo of pantry/fridge/freezer contents', upload_to='pantry_scans/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False, help_text='Whether Vision AI has processed this image')),
                ('raw_detection_json', models.JSONField(blank=True, default=dict, help_text='Raw detection output from Vision AI')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='meals.pantryscansession')),
            ],
            options={
                'verbose_name': 'Pantry Photo Upload',
                'verbose_name_plural': 'Pantry Photo Uploads',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PantryPhotoDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detected_label', models.CharField(help_text='Label as detected by Vision AI', max_length=200)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='AI confidence in detection (0-1)', max_digits=3)),
                ('suggested_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='AI-suggested quantity', max_digits=8, null=True)),
                ('unit', models.CharField(blank=True, default='piece', help_text='Suggested unit for the quantity', max_length=20)),
                ('confirmed', models.BooleanField(default=False, help_text='User confirmed this detection')),
                ('rejected', models.BooleanField(default=False, help_text='User rejected this detection')),
                ('matched_ingredient', models.ForeignKey(blank=True, help_text='Matched canonical ingredient (editable by user)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_detections', to='meals.ingredient')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='meals.pantryscansession')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='meals.pantryphotoupload')),
            ],
            options={
                'verbose_name': 'Pantry Photo Detection',
                'verbose_name_plural': 'Pantry Photo Detections',
                'ordering': ['-confidence_score'],
            },
        ),
    ]
