# Generated by Django 4.2.27 on 2026-03-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_phase12_pantry_photo_intelligence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantryphotoupload',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo of pantry/fridge/freezer contents (optional — processed in-memory)', null=True, upload_to='pantry_scans/%Y/%m/'),
        ),
    ]
