# Generated by Django 4.2.27 on 2026-03-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_pantry_photo_image_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='confirmation_status',
            field=models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='receipt',
            name='image',
            field=models.ImageField(blank=True, help_text='Uploaded receipt image', null=True, upload_to='receipts/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_type',
            field=models.CharField(choices=[('grocery', 'Grocery'), ('restaurant', 'Restaurant'), ('retail', 'Retail'), ('unknown', 'Unknown')], db_index=True, default='unknown', help_text='Classification determines domain routing', max_length=20),
        ),
        migrations.AddField(
            model_name='receiptitem',
            name='category',
            field=models.CharField(blank=True, help_text='Item category (e.g., produce, dairy, meat)', max_length=50),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='raw_text',
            field=models.TextField(blank=True, help_text='Raw OCR text or pasted text from receipt'),
        ),
    ]
