# Generated by Django 4.2.27 on 2026-03-08 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_receipt_ingestion_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, help_text='Original receipt if this is a detected duplicate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='meals.receipt'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('cash', 'Cash'), ('credit', 'Credit Card'), ('debit', 'Debit Card'), ('ebt', 'EBT/SNAP'), ('mobile', 'Mobile Pay'), ('other', 'Other')], default='', help_text='Payment method detected from receipt', max_length=20),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash for deduplication', max_length=64),
        ),
        migrations.AddField(
            model_name='receipt',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pre-tax subtotal from receipt', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tax amount from receipt', max_digits=10, null=True),
        ),
    ]
