# Generated by Django 4.2.27 on 2026-03-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_receipt_hardening_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='processing_error',
            field=models.TextField(blank=True, default='', help_text='Error message if async processing failed'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='confirmation_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('failed', 'Processing Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
