# Generated by Django 4.2.27 on 2026-03-08 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0007_receipt_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryitem',
            name='storage_location',
            field=models.CharField(choices=[('pantry', 'Pantry'), ('fridge', 'Fridge'), ('freezer', 'Freezer'), ('other', 'Other'), ('unknown', 'Unknown')], db_index=True, default='unknown', help_text='Physical storage location (pantry, fridge, freezer)', max_length=10),
        ),
        migrations.AddField(
            model_name='receipt',
            name='processing_progress',
            field=models.PositiveSmallIntegerField(default=0, help_text='Processing progress 0-100'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='processing_stage',
            field=models.CharField(blank=True, choices=[('upload', 'Upload Complete'), ('image_processing', 'Image Processing'), ('vision_extraction', 'Vision Extraction'), ('item_parsing', 'Item Parsing'), ('classification', 'Classification'), ('complete', 'Complete')], default='', help_text='Current processing stage', max_length=20),
        ),
        migrations.CreateModel(
            name='StorageOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name_lower', models.CharField(db_index=True, help_text='Lowercase product name for matching', max_length=200, unique=True)),
                ('product_name_display', models.CharField(blank=True, help_text='Original casing for display', max_length=200)),
                ('storage_location', models.CharField(choices=[('pantry', 'Pantry'), ('fridge', 'Fridge'), ('freezer', 'Freezer'), ('other', 'Other'), ('unknown', 'Unknown')], help_text='User-selected storage location', max_length=10)),
                ('set_by', models.ForeignKey(blank=True, help_text='User who set this override', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Storage Override',
                'verbose_name_plural': 'Storage Overrides',
            },
        ),
    ]
