# Generated by Django 4.2.27 on 2026-03-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_storage_location_and_receipt_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('receipt', 'Receipt Scan'), ('meal_plan', 'Meal Plan Deduction'), ('expiration', 'Expired Removal'), ('correction', 'User Correction'), ('photo_scan', 'Photo Scan'), ('barcode', 'Barcode Scan')], default='manual', max_length=20),
        ),
    ]
