# Generated by Django 4.2.27 on 2026-07-18 13:08

import apps.core.current_context
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0011_recipe_alter_mealplanentry_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('receipt', 'Receipt Scan'), ('meal_plan', 'Meal Plan Deduction'), ('preparation', 'Meal Preparation'), ('expiration', 'Expired Removal'), ('correction', 'User Correction'), ('photo_scan', 'Photo Scan'), ('barcode', 'Barcode Scan')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='PreparationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('recipe_title', models.CharField(blank=True, help_text='Snapshot of the recipe title (provenance; survives recipe deletion)', max_length=200)),
                ('servings_prepared', models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='How many servings were prepared (scales the deduction)', max_digits=6)),
                ('preparation_status', models.CharField(choices=[('intended', 'Intended'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=12)),
                ('deduction_status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('partial', 'Partially applied'), ('skipped', 'Skipped (no structured ingredients)'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('prepared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='Client-supplied key; a repeat with the same key is a no-op replay', max_length=100, null=True, unique=True)),
                ('deduction_summary', models.JSONField(blank=True, default=dict, help_text='Per-ingredient audit: required / available / deducted / shortage / unsupported-conversion (deterministic provenance)')),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_events', to='meals.household')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparation_events', to='meals.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preparation Event',
                'verbose_name_plural': 'Preparation Events',
                'ordering': ['-prepared_at'],
            },
            bases=(apps.core.current_context.NarratableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Leftover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('recipe_title', models.CharField(blank=True, max_length=200)),
                ('servings', models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Servings of leftovers remaining (as stated at preparation)', max_digits=6)),
                ('storage_location', models.CharField(blank=True, choices=[('pantry', 'Pantry'), ('fridge', 'Fridge'), ('freezer', 'Freezer'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=10, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leftovers', to='meals.household')),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leftovers', to='meals.preparationevent')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leftovers', to='meals.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leftover',
                'verbose_name_plural': 'Leftovers',
                'ordering': ['-created_at'],
            },
            bases=(apps.core.current_context.NarratableMixin, models.Model),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='preparation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='meals.preparationevent'),
        ),
    ]
