# Generated by Django 4.2.27 on 2026-07-18 13:34

import apps.core.current_context
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0103_healthkitdailymetric_and_more'),
        ('meals', '0012_alter_inventorytransaction_source_preparationevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('recipe_title', models.CharField(blank=True, max_length=200)),
                ('servings_consumed', models.DecimalField(decimal_places=2, max_digits=6)),
                ('meal_type', models.CharField(blank=True, max_length=20)),
                ('consumed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('food_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_consumptions', to='health.foodentry')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_consumptions', to='meals.household')),
                ('leftover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumptions', to='meals.leftover')),
                ('preparation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumptions', to='meals.preparationevent')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumptions', to='meals.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meal Consumption',
                'verbose_name_plural': 'Meal Consumptions',
                'ordering': ['-consumed_at'],
            },
            bases=(apps.core.current_context.NarratableMixin, models.Model),
        ),
    ]
