# Generated by Django 4.2.27 on 2026-07-18 13:52

import apps.core.current_context
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0013_mealconsumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='leftover',
            name='depleted_at',
            field=models.DateTimeField(blank=True, help_text='When the leftover reached a terminal disposition', null=True),
        ),
        migrations.AddField(
            model_name='leftover',
            name='disposition',
            field=models.CharField(choices=[('available', 'Available'), ('consumed', 'Fully consumed'), ('discarded', 'Discarded'), ('expired', 'Expired')], db_index=True, default='available', max_length=12),
        ),
        migrations.AlterField(
            model_name='leftover',
            name='servings',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Servings of leftovers remaining (never negative)', max_digits=6),
        ),
        migrations.CreateModel(
            name='FoodWasteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('recipe_title', models.CharField(blank=True, max_length=200)),
                ('event_type', models.CharField(choices=[('discarded', 'Discarded'), ('expired', 'Expired')], max_length=12)),
                ('servings', models.DecimalField(decimal_places=2, help_text='Servings discarded / expired in this event', max_digits=6)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(default='user', max_length=24)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_waste_events', to='meals.household')),
                ('leftover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_events', to='meals.leftover')),
                ('preparation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_events', to='meals.preparationevent')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_events', to='meals.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Food Waste Event',
                'verbose_name_plural': 'Food Waste Events',
                'ordering': ['-occurred_at'],
            },
            bases=(apps.core.current_context.NarratableMixin, models.Model),
        ),
    ]
