# Generated by Django 4.2.27 on 2026-07-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0014_leftover_depleted_at_leftover_disposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='base_measure',
            field=models.CharField(choices=[('mass', 'Mass (grams)'), ('volume', 'Volume (millilitres)'), ('count', 'Count (discrete units)')], default='count', help_text='How this ingredient is intrinsically measured for deduction', max_length=6),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='density_g_per_ml',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Grams per millilitre — bridges mass<->volume deterministically (only set where a real density is known)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='container_type',
            field=models.CharField(blank=True, choices=[('bottle', 'Bottle'), ('jar', 'Jar'), ('can', 'Can'), ('bag', 'Bag'), ('box', 'Box'), ('carton', 'Carton'), ('package', 'Package'), ('tub', 'Tub'), ('count', 'Loose / count')], max_length=16),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='net_content',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Usable amount in ONE full container, in net_content_unit (g/ml/count)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pantryitem',
            name='net_content_unit',
            field=models.CharField(blank=True, help_text="Base unit for net_content: 'g', 'ml', or 'count'", max_length=10),
        ),
    ]
