# Generated by Django 4.2.27 on 2026-07-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0017_pantry_remaining_base_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, help_text='Deterministic identity key derived from canonical_name', max_length=200),
        ),
    ]
