# Generated by Django 4.2.27 on 2026-01-26 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='Unique identifier (sudoku, kenken, nonogram, word_ladder, memory_matrix)', unique=True)),
                ('name', models.CharField(help_text='Display name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Brief description of the game')),
                ('category', models.CharField(choices=[('logic', 'Logic'), ('math', 'Math Logic'), ('visual', 'Visual Logic'), ('language', 'Language'), ('memory', 'Memory')], help_text='Primary cognitive skill category', max_length=20)),
                ('icon_svg', models.TextField(blank=True, help_text='SVG icon for the game tile')),
                ('color_primary', models.CharField(default='#6366f1', help_text='Primary theme color (hex)', max_length=7)),
                ('color_secondary', models.CharField(default='#818cf8', help_text='Secondary theme color (hex)', max_length=7)),
                ('difficulty_levels', models.JSONField(default=list, help_text="Available difficulty levels ['easy', 'medium', 'hard', 'expert']")),
                ('default_difficulty', models.CharField(default='medium', help_text='Default difficulty for new players', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this game is available to users')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order in the hub (lower = first)')),
            ],
            options={
                'verbose_name': 'Brain Training Game',
                'verbose_name_plural': 'Brain Training Games',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserOverallStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('total_completed', models.PositiveIntegerField(default=0)),
                ('total_time_seconds', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0, help_text='Current consecutive days with any brain training')),
                ('longest_streak', models.PositiveIntegerField(default=0, help_text='Longest consecutive days with any brain training')),
                ('last_played_date', models.DateField(blank=True, null=True)),
                ('favorite_game', models.ForeignKey(blank=True, help_text='Most-played game', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='brain_training.game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brain_training_overall_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Overall Stats',
                'verbose_name_plural': 'User Overall Stats',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge_id', models.CharField(db_index=True, help_text='Unique hash identifier for this challenge', max_length=64, unique=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], db_index=True, default='medium', max_length=20)),
                ('puzzle_data', models.JSONField(help_text='Puzzle configuration (grid, clues, etc.) - safe to send to client')),
                ('solution_hash', models.CharField(help_text='SHA-256 hash of the solution for integrity checks', max_length=64)),
                ('solution_data', models.JSONField(help_text='Actual solution data for server-side verification')),
                ('average_time_seconds', models.PositiveIntegerField(default=0, help_text='Average completion time across all users')),
                ('completion_count', models.PositiveIntegerField(default=0, help_text='Number of successful completions')),
                ('attempt_count', models.PositiveIntegerField(default=0, help_text='Total number of attempts')),
                ('is_pregenerated', models.BooleanField(default=False, help_text='Whether this was pre-generated (vs on-demand)')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='brain_training.game')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('total_completed', models.PositiveIntegerField(default=0)),
                ('total_time_seconds', models.PositiveIntegerField(default=0)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('best_score', models.PositiveIntegerField(default=0)),
                ('best_time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('current_streak', models.PositiveIntegerField(default=0, help_text='Current consecutive days played')),
                ('longest_streak', models.PositiveIntegerField(default=0, help_text='Longest consecutive days played')),
                ('last_played_date', models.DateField(blank=True, help_text='Last date this game was played', null=True)),
                ('preferred_difficulty', models.CharField(default='medium', help_text="User's most-played difficulty level", max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='brain_training.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brain_training_game_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Game Stats',
                'verbose_name_plural': 'User Game Stats',
                'unique_together': {('user', 'game')},
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the user started this challenge')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the user completed (or abandoned) the challenge', null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, help_text='Total active time spent on this challenge')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('timeout', 'Timed Out')], db_index=True, default='in_progress', max_length=20)),
                ('mistakes', models.PositiveIntegerField(default=0, help_text='Number of incorrect inputs')),
                ('hints_used', models.PositiveIntegerField(default=0, help_text='Number of hints requested')),
                ('score', models.PositiveIntegerField(default=0, help_text='Calculated score based on time, mistakes, hints')),
                ('current_state', models.JSONField(blank=True, default=dict, help_text='Current puzzle state for resuming')),
                ('platform', models.CharField(blank=True, help_text='ios, android, web', max_length=20)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='brain_training.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brain_training_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game Session',
                'verbose_name_plural': 'Game Sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='brain_train_user_id_9754cc_idx'), models.Index(fields=['user', 'challenge', '-started_at'], name='brain_train_user_id_caafbf_idx'), models.Index(fields=['user', 'started_at'], name='brain_train_user_id_67f3dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, help_text='The date these stats are for')),
                ('sessions_started', models.PositiveIntegerField(default=0)),
                ('sessions_completed', models.PositiveIntegerField(default=0)),
                ('total_time_seconds', models.PositiveIntegerField(default=0)),
                ('best_time_seconds', models.PositiveIntegerField(blank=True, help_text='Best (lowest) completion time of the day', null=True)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('best_score', models.PositiveIntegerField(default=0)),
                ('total_mistakes', models.PositiveIntegerField(default=0)),
                ('total_hints', models.PositiveIntegerField(default=0)),
                ('easy_completed', models.PositiveIntegerField(default=0)),
                ('medium_completed', models.PositiveIntegerField(default=0)),
                ('hard_completed', models.PositiveIntegerField(default=0)),
                ('expert_completed', models.PositiveIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='brain_training.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brain_training_daily_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Stats',
                'verbose_name_plural': 'Daily Stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='brain_train_user_id_82ae07_idx'), models.Index(fields=['user', 'game', 'date'], name='brain_train_user_id_6a7e75_idx')],
                'unique_together': {('user', 'game', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ChallengeQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, help_text='Position in queue (0 = next up)')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='brain_training.challenge')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='brain_training.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brain_training_queue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Challenge Queue',
                'verbose_name_plural': 'Challenge Queues',
                'ordering': ['user', 'game', 'position'],
                'indexes': [models.Index(fields=['user', 'game', 'position'], name='brain_train_user_id_261b68_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['game', 'difficulty'], name='brain_train_game_id_470959_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['game', 'difficulty', 'created_at'], name='brain_train_game_id_f08fe6_idx'),
        ),
    ]
