# Generated by Django 5.2.10 on 2026-02-01 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brain_training", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "Brain Training Exercise",
                "verbose_name_plural": "Brain Training Exercises",
            },
        ),
    ]
