"""
Django Models for WLJ Personal Assistant System.

Owner: admin@wholelifejourney.com

This module provides database models for persisting improvement tasks
with full lifecycle tracking for the self-improving assistant system.
"""

import secrets
import uuid
from datetime import timedelta
from django.conf import settings
from django.db import models
from django.utils import timezone


# Token expiry time in hours
APPROVAL_TOKEN_EXPIRY_HOURS = 24


class TaskStatusTransitionError(Exception):
    """Exception raised for invalid task status transitions."""
    pass


class ImprovementTaskModel(models.Model):
    """
    Django model to persist improvement tasks with full lifecycle tracking.

    This model stores tasks generated by the gap detection system and tracks
    their progress through the improvement workflow.
    """

    # Status choices for the task lifecycle
    STATUS_NEW = 'new'
    STATUS_PENDING_APPROVAL = 'pending_approval'
    STATUS_APPROVED = 'approved'
    STATUS_REJECTED = 'rejected'
    STATUS_IN_PROGRESS = 'in_progress'
    STATUS_TESTING = 'testing'
    STATUS_COMPLETED = 'completed'
    STATUS_ERROR = 'error'
    STATUS_ROLLED_BACK = 'rolled_back'

    STATUS_CHOICES = [
        (STATUS_NEW, 'New'),
        (STATUS_PENDING_APPROVAL, 'Pending Approval'),
        (STATUS_APPROVED, 'Approved'),
        (STATUS_REJECTED, 'Rejected'),
        (STATUS_IN_PROGRESS, 'In Progress'),
        (STATUS_TESTING, 'Testing'),
        (STATUS_COMPLETED, 'Completed'),
        (STATUS_ERROR, 'Error'),
        (STATUS_ROLLED_BACK, 'Rolled Back'),
    ]

    # Valid status transitions
    ALLOWED_TRANSITIONS = {
        STATUS_NEW: [STATUS_PENDING_APPROVAL, STATUS_APPROVED],
        STATUS_PENDING_APPROVAL: [STATUS_APPROVED, STATUS_REJECTED, STATUS_NEW],
        STATUS_APPROVED: [STATUS_IN_PROGRESS, STATUS_PENDING_APPROVAL],
        STATUS_REJECTED: [STATUS_NEW],  # Can retry rejected tasks
        STATUS_IN_PROGRESS: [STATUS_TESTING, STATUS_ERROR, STATUS_APPROVED],
        STATUS_TESTING: [STATUS_COMPLETED, STATUS_ERROR, STATUS_IN_PROGRESS],
        STATUS_COMPLETED: [STATUS_ROLLED_BACK],
        STATUS_ERROR: [STATUS_NEW, STATUS_APPROVED, STATUS_ROLLED_BACK],
        STATUS_ROLLED_BACK: [STATUS_NEW],
    }

    # Gap type choices (matching GapType enum values)
    GAP_TYPE_UNKNOWN_DATA_TYPE = 'unknown_data_type'
    GAP_TYPE_MISSING_KEYWORDS = 'missing_keywords'
    GAP_TYPE_NO_DATA_METHOD = 'no_data_method'
    GAP_TYPE_UNSUPPORTED_QUERY_PATTERN = 'unsupported_query_pattern'

    GAP_TYPE_CHOICES = [
        (GAP_TYPE_UNKNOWN_DATA_TYPE, 'Unknown Data Type'),
        (GAP_TYPE_MISSING_KEYWORDS, 'Missing Keywords'),
        (GAP_TYPE_NO_DATA_METHOD, 'No Data Method'),
        (GAP_TYPE_UNSUPPORTED_QUERY_PATTERN, 'Unsupported Query Pattern'),
    ]

    # Severity choices (matching GapSeverity enum values)
    SEVERITY_LOW = 'low'
    SEVERITY_MEDIUM = 'medium'
    SEVERITY_HIGH = 'high'

    SEVERITY_CHOICES = [
        (SEVERITY_LOW, 'Low - Keyword Addition'),
        (SEVERITY_MEDIUM, 'Medium - New Query Method'),
        (SEVERITY_HIGH, 'High - Application Change'),
    ]

    # Primary key
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        help_text='Unique identifier for the task'
    )

    # Core task information
    title = models.CharField(
        max_length=255,
        help_text='Brief title describing the improvement task'
    )
    description = models.JSONField(
        default=dict,
        help_text='Structured description with objective, inputs, actions, output'
    )
    gap_type = models.CharField(
        max_length=50,
        choices=GAP_TYPE_CHOICES,
        help_text='Type of knowledge gap that triggered this task'
    )
    severity = models.CharField(
        max_length=20,
        choices=SEVERITY_CHOICES,
        help_text='Severity level indicating implementation effort'
    )
    original_query = models.TextField(
        help_text='The original user query that revealed the gap'
    )
    suggested_fix = models.TextField(
        help_text='Human-readable description of the suggested fix'
    )
    code_template = models.TextField(
        blank=True,
        help_text='Generated code template for implementing the fix'
    )
    test_template = models.TextField(
        blank=True,
        help_text='Generated test code template for verifying the fix'
    )

    # Approval workflow
    requires_approval = models.BooleanField(
        default=True,
        help_text='Whether this task requires manual approval before execution'
    )
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default=STATUS_NEW,
        help_text='Current status in the task lifecycle'
    )

    # Timestamps
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text='When the task was created'
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        help_text='When the task was last updated'
    )
    approved_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text='When the task was approved'
    )
    completed_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text='When the task was completed'
    )

    # User tracking - who triggered the gap detection
    triggered_by_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='triggered_improvement_tasks',
        help_text='User whose query triggered this improvement task'
    )

    # Approval tracking
    approved_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='approved_improvement_tasks',
        help_text='User who approved the task'
    )

    # Error tracking
    error_message = models.TextField(
        blank=True,
        help_text='Error message if the task failed'
    )

    # Git tracking
    git_commit_before = models.CharField(
        max_length=40,
        blank=True,
        help_text='Git commit SHA before changes were applied'
    )
    git_commit_after = models.CharField(
        max_length=40,
        blank=True,
        help_text='Git commit SHA after changes were applied'
    )

    # Approval token for secure email-based approval
    approval_token = models.CharField(
        max_length=64,
        blank=True,
        help_text='Secure one-time token for email-based approval'
    )
    approval_token_created_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text='When the approval token was generated'
    )

    # Rejection tracking
    rejected_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text='When the task was rejected'
    )
    rejection_reason = models.TextField(
        blank=True,
        help_text='Reason for rejecting the task'
    )

    # Rollback tracking
    rolled_back_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text='When the task was rolled back'
    )
    rollback_reason = models.TextField(
        blank=True,
        help_text='Reason for rolling back the task'
    )

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Improvement Task'
        verbose_name_plural = 'Improvement Tasks'
        indexes = [
            models.Index(fields=['status']),
            models.Index(fields=['gap_type']),
            models.Index(fields=['severity']),
            models.Index(fields=['created_at']),
            models.Index(fields=['requires_approval', 'status']),
        ]

    def __str__(self):
        return f"{self.title} ({self.get_status_display()})"

    def transition_status(self, new_status, user=None, error_message=None):
        """
        Transition the task to a new status with validation.

        Args:
            new_status: The target status to transition to.
            user: Optional user performing the transition (for approval).
            error_message: Optional error message (for error status).

        Raises:
            TaskStatusTransitionError: If the transition is not allowed.

        Returns:
            True if the transition was successful.
        """
        if new_status not in dict(self.STATUS_CHOICES):
            raise TaskStatusTransitionError(
                f"Invalid status: '{new_status}'. "
                f"Valid statuses are: {[s[0] for s in self.STATUS_CHOICES]}"
            )

        allowed = self.ALLOWED_TRANSITIONS.get(self.status, [])
        if new_status not in allowed:
            raise TaskStatusTransitionError(
                f"Cannot transition from '{self.status}' to '{new_status}'. "
                f"Allowed transitions: {allowed}"
            )

        self.status = new_status

        # Handle special status transitions
        if new_status == self.STATUS_APPROVED:
            self.approved_at = timezone.now()
            if user:
                self.approved_by = user

        elif new_status == self.STATUS_COMPLETED:
            self.completed_at = timezone.now()
            self.error_message = ''

        elif new_status == self.STATUS_ERROR:
            if error_message:
                self.error_message = error_message

        elif new_status == self.STATUS_NEW:
            # Reset approval when returning to new
            self.approved_at = None
            self.approved_by = None
            self.completed_at = None

        self.save()
        return True

    def to_dict(self):
        """
        Convert the model instance to a dictionary for serialization.

        Returns:
            Dictionary representation of the task suitable for JSON serialization.
        """
        # Build triggered_by_user info
        triggered_by_info = None
        if self.triggered_by_user:
            triggered_by_info = {
                'email': self.triggered_by_user.email,
                'name': self.triggered_by_user.get_full_name() or self.triggered_by_user.email,
                'id': self.triggered_by_user.id,
            }

        return {
            'id': str(self.id),
            'title': self.title,
            'description': self.description,
            'gap_type': self.gap_type,
            'gap_type_display': self.get_gap_type_display(),
            'severity': self.severity,
            'severity_display': self.get_severity_display(),
            'original_query': self.original_query,
            'suggested_fix': self.suggested_fix,
            'code_template': self.code_template,
            'test_template': self.test_template,
            'requires_approval': self.requires_approval,
            'status': self.status,
            'status_display': self.get_status_display(),
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None,
            'approved_at': self.approved_at.isoformat() if self.approved_at else None,
            'approved_by': self.approved_by.email if self.approved_by else None,
            'triggered_by_user': triggered_by_info,
            'completed_at': self.completed_at.isoformat() if self.completed_at else None,
            'error_message': self.error_message,
            'git_commit_before': self.git_commit_before,
            'git_commit_after': self.git_commit_after,
            'rolled_back_at': self.rolled_back_at.isoformat() if self.rolled_back_at else None,
            'rollback_reason': self.rollback_reason,
        }

    @classmethod
    def create_from_improvement_task(cls, improvement_task):
        """
        Create a model instance from an ImprovementTask dataclass.

        Args:
            improvement_task: An ImprovementTask instance from task_generator.

        Returns:
            A new ImprovementTaskModel instance (not saved).
        """
        from .task_generator import generate_test_template

        # Determine initial status based on requires_approval
        initial_status = (
            cls.STATUS_PENDING_APPROVAL
            if improvement_task.requires_approval
            else cls.STATUS_APPROVED
        )

        # Generate test template if not provided
        test_template = ''
        if improvement_task.gap_type:
            test_template = generate_test_template(
                improvement_task.gap_type,
                improvement_task.original_query.split()[-1] if improvement_task.original_query else 'unknown'
            )

        return cls(
            title=improvement_task.title,
            description={
                'objective': improvement_task.description,
                'suggested_fix': improvement_task.suggested_fix,
                'test_requirements': improvement_task.test_requirements,
            },
            gap_type=improvement_task.gap_type.value if improvement_task.gap_type else cls.GAP_TYPE_MISSING_KEYWORDS,
            severity=improvement_task.severity.value if improvement_task.severity else cls.SEVERITY_LOW,
            original_query=improvement_task.original_query,
            suggested_fix=improvement_task.suggested_fix,
            code_template=improvement_task.code_template,
            test_template=test_template,
            requires_approval=improvement_task.requires_approval,
            status=initial_status,
        )

    def generate_approval_token(self):
        """
        Generate a secure one-time approval token.

        Returns:
            The generated token string.
        """
        self.approval_token = secrets.token_urlsafe(32)
        self.approval_token_created_at = timezone.now()
        self.save(update_fields=['approval_token', 'approval_token_created_at'])
        return self.approval_token

    def is_token_valid(self, token):
        """
        Check if the provided token is valid and not expired.

        Args:
            token: The token string to validate.

        Returns:
            True if the token is valid and not expired, False otherwise.
        """
        if not self.approval_token or not token:
            return False

        if self.approval_token != token:
            return False

        if not self.approval_token_created_at:
            return False

        # Check if token has expired
        expiry_time = self.approval_token_created_at + timedelta(hours=APPROVAL_TOKEN_EXPIRY_HOURS)
        if timezone.now() > expiry_time:
            return False

        return True

    def clear_approval_token(self):
        """Clear the approval token after use (one-time use)."""
        self.approval_token = ''
        self.approval_token_created_at = None
        self.save(update_fields=['approval_token', 'approval_token_created_at'])

    def approve(self, user=None):
        """
        Approve the task and clear the token.

        Args:
            user: Optional user who approved the task.

        Returns:
            True if approval was successful.
        """
        self.transition_status(self.STATUS_APPROVED, user=user)
        self.clear_approval_token()
        return True

    def reject(self, reason=''):
        """
        Reject the task with an optional reason.

        Args:
            reason: Optional reason for rejection.

        Returns:
            True if rejection was successful.
        """
        self.status = self.STATUS_REJECTED
        self.rejected_at = timezone.now()
        self.rejection_reason = reason
        self.clear_approval_token()
        self.save()
        return True

    def rollback(self, reason=''):
        """
        Rollback the task with a reason.

        Args:
            reason: Required reason for rollback.

        Raises:
            TaskStatusTransitionError: If task cannot be rolled back.

        Returns:
            True if rollback status change was successful.
        """
        self.transition_status(self.STATUS_ROLLED_BACK)
        self.rolled_back_at = timezone.now()
        self.rollback_reason = reason
        self.save(update_fields=['rolled_back_at', 'rollback_reason'])
        return True
