# Generated by Django 5.2.9 on 2025-12-25 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScriptureVerse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="e.g., 'Philippians 4:6-7'", max_length=100
                    ),
                ),
                ("text", models.TextField()),
                (
                    "translation",
                    models.CharField(
                        choices=[
                            ("ESV", "English Standard Version"),
                            ("NIV", "New International Version"),
                            ("BSB", "Berean Standard Bible"),
                            ("NKJV", "New King James Version"),
                            ("NLT", "New Living Translation"),
                        ],
                        default="ESV",
                        max_length=10,
                    ),
                ),
                ("book_name", models.CharField(max_length=50)),
                (
                    "book_order",
                    models.PositiveIntegerField(
                        help_text="Order in the Bible (Genesis=1, Revelation=66)"
                    ),
                ),
                ("chapter", models.PositiveIntegerField()),
                ("verse_start", models.PositiveIntegerField()),
                ("verse_end", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "themes",
                    models.JSONField(
                        default=list,
                        help_text="Themes like 'peace', 'trust', 'strength', 'comfort', 'guidance'",
                    ),
                ),
                (
                    "contexts",
                    models.JSONField(
                        default=list,
                        help_text="Contexts like 'anxiety', 'grief', 'gratitude', 'morning', 'evening'",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "scripture verse",
                "verbose_name_plural": "scripture verses",
                "ordering": ["book_order", "chapter", "verse_start"],
            },
        ),
        migrations.CreateModel(
            name="FaithMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "milestone_type",
                    models.CharField(
                        choices=[
                            ("salvation", "Accepted Christ"),
                            ("baptism", "Baptism"),
                            ("rededication", "Rededication"),
                            ("answered_prayer", "Answered Prayer"),
                            ("spiritual_insight", "Spiritual Insight"),
                            ("community", "Church/Community Moment"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.TextField(blank=True)),
                (
                    "scripture_reference",
                    models.CharField(
                        blank=True,
                        help_text="A verse connected to this milestone",
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "faith milestone",
                "verbose_name_plural": "faith milestones",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PrayerRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "is_personal",
                    models.BooleanField(
                        default=True, help_text="Personal prayer vs. praying for others"
                    ),
                ),
                (
                    "person_or_situation",
                    models.CharField(
                        blank=True,
                        help_text="Who or what you're praying for",
                        max_length=200,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("normal", "Normal"), ("urgent", "Urgent")],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("is_answered", models.BooleanField(default=False)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "answer_notes",
                    models.TextField(
                        blank=True, help_text="How God answered this prayer"
                    ),
                ),
                (
                    "remind_daily",
                    models.BooleanField(
                        default=False, help_text="Include in daily prayer reminders"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "prayer request",
                "verbose_name_plural": "prayer requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyVerse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "theme",
                    models.CharField(
                        blank=True,
                        help_text="Optional theme for the day",
                        max_length=50,
                    ),
                ),
                (
                    "reflection_prompt",
                    models.TextField(
                        blank=True,
                        help_text="Optional reflection question for this verse",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "verse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_assignments",
                        to="faith.scriptureverse",
                    ),
                ),
            ],
            options={
                "verbose_name": "daily verse",
                "verbose_name_plural": "daily verses",
                "ordering": ["-date"],
            },
        ),
    ]
