# Generated by Django 5.2.9 on 2025-12-28 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faith", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedVerse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference",
                    models.CharField(
                        help_text="e.g., 'Philippians 4:6-7'", max_length=100
                    ),
                ),
                ("text", models.TextField()),
                (
                    "translation",
                    models.CharField(
                        choices=[
                            ("ESV", "English Standard Version"),
                            ("NIV", "New International Version"),
                            ("BSB", "Berean Standard Bible"),
                            ("NKJV", "New King James Version"),
                            ("NLT", "New Living Translation"),
                            ("KJV", "King James Version"),
                        ],
                        default="ESV",
                        max_length=10,
                    ),
                ),
                ("book_name", models.CharField(max_length=50)),
                (
                    "book_order",
                    models.PositiveIntegerField(
                        help_text="Order in the Bible (Genesis=1, Revelation=66)"
                    ),
                ),
                ("chapter", models.PositiveIntegerField()),
                ("verse_start", models.PositiveIntegerField()),
                ("verse_end", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "themes",
                    models.JSONField(
                        default=list,
                        help_text="Personal themes like 'peace', 'trust', 'strength'",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Personal notes about this verse"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "saved verse",
                "verbose_name_plural": "saved verses",
                "ordering": ["book_order", "chapter", "verse_start"],
            },
        ),
    ]
