# Generated by Django 5.2.9 on 2025-12-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faith", "0004_add_created_via_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedverse",
            name="is_memory_verse",
            field=models.BooleanField(
                default=False,
                help_text="Mark this verse as a memory verse to display on the dashboard",
            ),
        ),
    ]
