# Generated by Django 5.2.9 on 2026-01-01 13:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faith", "0005_add_memory_verse_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingPlanTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("topical", "Topical Study"),
                            ("book", "Book Study"),
                            ("chronological", "Chronological"),
                            ("devotional", "Devotional"),
                        ],
                        default="topical",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        help_text="Total days to complete the plan"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, help_text="Optional cover image URL for the plan"
                    ),
                ),
                (
                    "topics",
                    models.JSONField(
                        default=list,
                        help_text="Topics covered: forgiveness, prayer, stress, marriage, etc.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Show prominently on reading plans page",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "reading plan template",
                "verbose_name_plural": "reading plan templates",
                "ordering": ["-is_featured", "title"],
            },
        ),
        migrations.CreateModel(
            name="BibleBookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_via",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("ai_camera", "AI Camera Scan"),
                            ("import", "Data Import"),
                            ("api", "API"),
                        ],
                        default="manual",
                        help_text="How this entry was created",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="e.g., 'John 3' or 'Romans 8:28'", max_length=100
                    ),
                ),
                ("translation", models.CharField(default="ESV", max_length=10)),
                ("book_name", models.CharField(max_length=50)),
                (
                    "book_order",
                    models.PositiveIntegerField(
                        help_text="Order in the Bible (Genesis=1, Revelation=66)"
                    ),
                ),
                ("chapter", models.PositiveIntegerField()),
                (
                    "verse",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional: specific verse within chapter",
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional label for this bookmark",
                        max_length=200,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Why you bookmarked this passage"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bible bookmark",
                "verbose_name_plural": "Bible bookmarks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BibleHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_via",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("ai_camera", "AI Camera Scan"),
                            ("import", "Data Import"),
                            ("api", "API"),
                        ],
                        default="manual",
                        help_text="How this entry was created",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="e.g., 'John 3:16' or 'Romans 8:28-30'",
                        max_length=100,
                    ),
                ),
                ("text", models.TextField(help_text="The highlighted text content")),
                ("translation", models.CharField(default="ESV", max_length=10)),
                ("book_name", models.CharField(max_length=50)),
                (
                    "book_order",
                    models.PositiveIntegerField(
                        help_text="Order in the Bible (Genesis=1, Revelation=66)"
                    ),
                ),
                ("chapter", models.PositiveIntegerField()),
                ("verse_start", models.PositiveIntegerField()),
                ("verse_end", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("yellow", "Yellow"),
                            ("green", "Green"),
                            ("blue", "Blue"),
                            ("pink", "Pink"),
                            ("purple", "Purple"),
                            ("orange", "Orange"),
                        ],
                        default="yellow",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bible highlight",
                "verbose_name_plural": "Bible highlights",
                "ordering": ["book_order", "chapter", "verse_start"],
            },
        ),
        migrations.CreateModel(
            name="BibleStudyNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_via",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("ai_camera", "AI Camera Scan"),
                            ("import", "Data Import"),
                            ("api", "API"),
                        ],
                        default="manual",
                        help_text="How this entry was created",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(help_text="e.g., 'John 3:16-21'", max_length=100),
                ),
                ("translation", models.CharField(default="ESV", max_length=10)),
                ("book_name", models.CharField(max_length=50)),
                (
                    "book_order",
                    models.PositiveIntegerField(
                        help_text="Order in the Bible (Genesis=1, Revelation=66)"
                    ),
                ),
                ("chapter", models.PositiveIntegerField()),
                ("verse_start", models.PositiveIntegerField()),
                ("verse_end", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional title for this note",
                        max_length=200,
                    ),
                ),
                ("content", models.TextField(help_text="Your study notes")),
                (
                    "tags",
                    models.JSONField(
                        default=list,
                        help_text="Tags for organizing notes: theology, application, context, etc.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bible study note",
                "verbose_name_plural": "Bible study notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReadingPlanDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_number",
                    models.PositiveIntegerField(
                        help_text="Which day in the plan (1, 2, 3...)"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional title for this day's reading",
                        max_length=200,
                    ),
                ),
                (
                    "scripture_references",
                    models.JSONField(
                        default=list,
                        help_text="List of Scripture references for this day",
                    ),
                ),
                (
                    "reflection_prompt",
                    models.TextField(
                        blank=True,
                        help_text="Reflection question or prompt for this day",
                    ),
                ),
                (
                    "devotional_text",
                    models.TextField(
                        blank=True, help_text="Optional devotional/commentary text"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="faith.readingplantemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "reading plan day",
                "verbose_name_plural": "reading plan days",
                "ordering": ["plan", "day_number"],
                "unique_together": {("plan", "day_number")},
            },
        ),
        migrations.CreateModel(
            name="UserReadingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_via",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("ai_camera", "AI Camera Scan"),
                            ("import", "Data Import"),
                            ("api", "API"),
                        ],
                        default="manual",
                        help_text="How this entry was created",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "In Progress"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("current_day", models.PositiveIntegerField(default=1)),
                (
                    "reminder_time",
                    models.TimeField(
                        blank=True,
                        help_text="Daily reminder time for this plan",
                        null=True,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_plans",
                        to="faith.readingplantemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user reading plan",
                "verbose_name_plural": "user reading plans",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="UserReadingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_via",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("ai_camera", "AI Camera Scan"),
                            ("import", "Data Import"),
                            ("api", "API"),
                        ],
                        default="manual",
                        help_text="How this entry was created",
                        max_length=20,
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Personal notes or reflections for this day's reading",
                    ),
                ),
                (
                    "plan_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="faith.readingplanday",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_completions",
                        to="faith.userreadingplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "reading progress",
                "verbose_name_plural": "reading progress entries",
                "ordering": ["user_plan", "plan_day__day_number"],
                "unique_together": {("user_plan", "plan_day")},
            },
        ),
    ]
