# Generated by Django 5.1.4

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faith', '0006_bible_reading_plans_and_study_tools'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreadingplan',
            old_name='status',
            new_name='plan_status',
        ),
    ]
