# Generated by Django 4.2.27 on 2026-01-18 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faith', '0009_add_translation_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingPlanAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Control Freak Assessment'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Instructions or context for the assessment')),
                ('questions', models.JSONField(default=list, help_text='List of questions with id, text, min_label, max_label')),
                ('score_ranges', models.JSONField(default=list, help_text='Score interpretation ranges with label and description')),
                ('min_score_per_question', models.PositiveIntegerField(default=1, help_text='Minimum score value (e.g., 1)')),
                ('max_score_per_question', models.PositiveIntegerField(default=5, help_text='Maximum score value (e.g., 5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='faith.readingplanday')),
            ],
            options={
                'verbose_name': 'reading plan assessment',
                'verbose_name_plural': 'reading plan assessments',
                'ordering': ['plan_day', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='UserAssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('responses', models.JSONField(default=dict, help_text='Question ID to score mapping')),
                ('total_score', models.PositiveIntegerField(default=0, help_text='Sum of all response scores')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='faith.readingplanassessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('user_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_responses', to='faith.userreadingplan')),
            ],
            options={
                'verbose_name': 'assessment response',
                'verbose_name_plural': 'assessment responses',
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'assessment', 'user_plan')},
            },
        ),
    ]
