# Generated by Django 4.2.27 on 2026-01-18 17:27

from django.db import migrations


# Clean devotional texts without ** markdown markers
DEVOTIONAL_TEXTS = {
    1: """Awareness: Seeing What We've Been Missing

Before we can address a blind spot, we have to see it. Just like we can't see the car in our blind spot without intentionally looking, we often can't see our control issues without honest examination.

Adam and Eve lived in perfect harmony with God—no shame, no fear, no need to control. Then the serpent introduced a lie: "You will be like God." The first blind spot was born from the desire to control what only God should control.

In Genesis 3, the serpent's temptation was fundamentally about control. Our desire to control is, at its root, our desire to be God. We don't think of it that way—but that's the blind spot.

Prayer Focus: Ask God to reveal blind spots you can't see on your own. Be willing to see what you haven't wanted to see.""",

    2: """Understanding What Feeds the Blind Spot

The blind spot of control is fed by a mindset of worry.

The Greek word for "worry" means "to divide into fragments." That's exactly what worry does—it takes your focused mind and fragments it like a grenade, splintering your attention into dozens of "what-ifs."

Jesus asks a piercing question: "Can any one of you by worrying add a single hour to your life?" Worry is the engine that drives our need to control. We worry because we don't trust. We control because we're afraid.

Why Jesus is against worry:

- Worry divides our minds and fragments our focus
- Worry is unproductive—it can't change the past or the future, it only messes up today
- Worry robs our joy and turns blessings into burdens
- Worry is unhealthy, leading to acid reflux, high blood pressure, and sleep disorders
- Worry is unchristian—it's a trust issue disguised as responsibility

Prayer Focus: Name your worries out loud to God. Don't try to solve them—just name them.""",

    3: """Exposing the Lie We Believe

The Illusion: We think we will have peace if we have control over our health, our marriage, our finances, our co-workers, our neighbors, the ministry team we lead.

The Truth: That's as deceiving as the serpent's lie in the garden.

Consider what we actually can't control:

Our health future — We might be diagnosed with cancer, Alzheimer's, or MS. We can make good decisions, get our check-ups, eat healthy—but we can't control outcomes.

Our family's future — Our parents, spouse, or kids might make bad choices. We can pray, support, forgive, and love—but we can't control their choices.

Our financial future — Do you control the stock market? Your Roth IRA? Things can change in a heartbeat.

Our country's future — We can vote, be good citizens—but we can't control the political climate.

"When we try to control everything, we enjoy nothing."

"What we attempt to control the most often reveals where we trust God the least."

Prayer Focus: Ask God to show you the illusion you've been believing—that control brings peace.""",

    4: """Recognizing How Control Shows Up in Behavior

When Christians try to control things, we typically use one of three tools:

1. Spiritualizing
"I think God wants you to date this young man."
"I think God wants you to take this job."
Using God as the trump card sounds spiritual—but it can be manipulation dressed in religious language.

2. Punishing
"If you can't get better than a B, you don't deserve to have friends over."
We throw out punishment to control behavior.

3. Disconnecting
"I'm not yelling. I'm not screaming. I just won't talk."
"I'm going to unfriend you."
"I'm not coming to church until you acknowledge I'm right."

As Pastor said: "It's easy to feel quite righteous about this because I'm not yelling or screaming at anybody. Oh, you're angry. You're just doing it in a different form."

Prayer Focus: Confess specific instances where you've used these tools. Ask God to replace control with trust.""",

    5: """Replacing Control with Dependence on God

Today, read Matthew 6:25-34 as a responsive reading. After each section, speak the trust statement out loud:

"Therefore I tell you, do not worry about your life..."
Say: "I trust that God will meet my needs—financially, physically, and emotionally."

"Look at the birds of the air... Are you not much more valuable than they?"
Say: "I trust that God cares for me and loves me."

"Can any one of you by worrying add a single hour to your life?"
Say: "I trust that God has numbered my days."

"See how the flowers of the field grow..."
Say: "I trust that doing my best is enough."

"But seek first his kingdom and his righteousness..."
Say: "I trust that God and His kingdom are the best way to win over worry."

"Therefore do not worry about tomorrow..."
Say: "I trust God to take care of tomorrow."

The key truth: "The opposite of control is not chaos. The opposite of control is trust."

Prayer Focus: Pray through each trust statement again, personalizing it for your specific situation.""",

    6: """Surrender and Freedom

"Cast all your anxiety on him because he cares for you." — 1 Peter 5:7

The Jerusalem Bible translates it: "Unload all your worries on him, since he's looking after you."

Four Steps to Freedom:

1. Admit you have a problem with control.
For some of us, this is the hardest step. Are you trying to control things? Be honest.

2. Surrender.
Wave the white flag. Say out loud: "God, I can't control this. I'm handing it to you."

3. Remember: the opposite of control is not chaos—it's trust.
When we remember we belong to God, it's easier to surrender. Letting go is actually freeing.

4. Live one day at a time.
There are two days we should never worry about: yesterday and tomorrow.

The ultimate proof of God's care:
If we trust Jesus to carry away our sin and make us right with God—can't we trust Him with our finances? Our marriage? Our children? Our work?

"If we can trust in God's hands for our salvation, can't we put all these other things in his hands? God's like, 'That's small potatoes.' Because He did the greatest thing by laying down His life for us."

Prayer Focus: Name the specific thing you're surrendering. Wave your white flag. Ask God for grace to trust Him one day at a time—starting today.""",
}

# Scripture references for each day
SCRIPTURE_REFERENCES = {
    1: ["Genesis 2:15-25", "Genesis 3:1-7"],
    2: ["Matthew 6:25-27"],
    3: ["Matthew 6:28-32"],
    4: ["James 4:1-10"],
    5: ["Matthew 6:25-34"],
    6: ["1 Peter 5:6-11", "Psalm 37:1-9"],
}


def update_devotional_texts(apps, schema_editor):
    """Update devotional texts to remove ** markdown markers and ensure scripture refs."""
    ReadingPlanDay = apps.get_model('faith', 'ReadingPlanDay')

    for day_number, text in DEVOTIONAL_TEXTS.items():
        # Update the record for the Blind Spots reading plan (pk=100)
        update_data = {'devotional_text': text}
        if day_number in SCRIPTURE_REFERENCES:
            update_data['scripture_references'] = SCRIPTURE_REFERENCES[day_number]

        ReadingPlanDay.objects.filter(
            plan_id=100,
            day_number=day_number
        ).update(**update_data)


def reverse_migration(apps, schema_editor):
    """No-op reverse - we don't want to restore the ** markers."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('faith', '0010_reading_plan_assessments'),
    ]

    operations = [
        migrations.RunPython(update_devotional_texts, reverse_migration),
    ]
