# Generated by Django 4.2.27 on 2026-01-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faith', '0011_update_blind_spots_devotional_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingplantemplate',
            name='allowed_emails',
            field=models.JSONField(blank=True, default=list, help_text='List of email addresses allowed to access this plan. Empty = public.'),
        ),
        migrations.AddField(
            model_name='readingplantemplate',
            name='series',
            field=models.CharField(blank=True, help_text="Series name within the source (e.g., 'Blind Spots')", max_length=200),
        ),
        migrations.AddField(
            model_name='readingplantemplate',
            name='series_order',
            field=models.PositiveIntegerField(default=0, help_text='Order within series (e.g., 1 for Week 1, 2 for Week 2)'),
        ),
        migrations.AddField(
            model_name='readingplantemplate',
            name='source',
            field=models.CharField(blank=True, help_text="Source of the content (e.g., 'Seymour Heights Christian Church')", max_length=200),
        ),
        migrations.AddField(
            model_name='readingplantemplate',
            name='source_abbreviation',
            field=models.CharField(blank=True, help_text="Short form for display (e.g., 'SHCC')", max_length=20),
        ),
    ]
