# Generated by Django 4.2.27 on 2026-01-18 19:56

from django.db import migrations


def populate_shcc_plans(apps, schema_editor):
    """Set source, series, and access control for SHCC reading plans."""
    ReadingPlanTemplate = apps.get_model('faith', 'ReadingPlanTemplate')

    allowed_emails = ["dannyjenkins71@gmail.com", "heatherjenkins74@gmail.com"]

    # Week 2: Surrendering My Blind Spots (slug: surrendering-blind-spots, pk: 100)
    ReadingPlanTemplate.objects.filter(slug="surrendering-blind-spots").update(
        source="Seymour Heights Christian Church",
        source_abbreviation="SHCC",
        series="Blind Spots",
        series_order=2,
        allowed_emails=allowed_emails,
    )

    # Week 1: Opening Your Eyes (slug: blind-spots-opening-eyes, pk: 101)
    ReadingPlanTemplate.objects.filter(slug="blind-spots-opening-eyes").update(
        source="Seymour Heights Christian Church",
        source_abbreviation="SHCC",
        series="Blind Spots",
        series_order=1,
        allowed_emails=allowed_emails,
    )


def reverse_populate(apps, schema_editor):
    """Reverse the data migration."""
    ReadingPlanTemplate = apps.get_model('faith', 'ReadingPlanTemplate')

    ReadingPlanTemplate.objects.filter(
        slug__in=["surrendering-blind-spots", "blind-spots-opening-eyes"]
    ).update(
        source="",
        source_abbreviation="",
        series="",
        series_order=0,
        allowed_emails=[],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('faith', '0012_add_reading_plan_source_series_access'),
    ]

    operations = [
        migrations.RunPython(populate_shcc_plans, reverse_populate),
    ]
