# Generated by Django 4.2.27 on 2026-01-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faith', '0013_populate_shcc_reading_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingplanday',
            name='commentary_advanced',
            field=models.TextField(blank=True, help_text='Scholarly depth: word studies, historical context, cross-references'),
        ),
        migrations.AddField(
            model_name='readingplanday',
            name='commentary_beginner',
            field=models.TextField(blank=True, help_text='Simple explanations for those new to Bible study'),
        ),
        migrations.AddField(
            model_name='readingplanday',
            name='commentary_intermediate',
            field=models.TextField(blank=True, help_text='Deeper context for those familiar with the Bible but wanting more understanding'),
        ),
        migrations.AddField(
            model_name='readingplanday',
            name='context_summary',
            field=models.TextField(blank=True, help_text='High-level context: who is speaking, audience, time frame, key takeaway'),
        ),
        migrations.AddField(
            model_name='readingplanday',
            name='scripture_content',
            field=models.JSONField(blank=True, default=list, help_text="Inline scripture with text and red letter ranges for Jesus' words"),
        ),
    ]
