# Generated by Django 4.2.27 on 2026-01-21 04:30

from django.db import migrations


def update_gospel_plans(apps, schema_editor):
    """Update Gospel reading plans to use source/series grouping."""
    ReadingPlanTemplate = apps.get_model('faith', 'ReadingPlanTemplate')

    # All Gospels go in same series "The Four Gospels" so they display in one grid
    gospel_updates = {
        'journey-through-matthew': {'series_order': 1},
        'journey-through-mark': {'series_order': 2},
        'journey-through-luke': {'series_order': 3},
        'journey-through-john': {'series_order': 4},
    }

    for slug, updates in gospel_updates.items():
        ReadingPlanTemplate.objects.filter(slug=slug).update(
            source='The Four Gospels',
            source_abbreviation='Gospels',
            series='The Four Gospels',
            series_order=updates['series_order'],
            is_featured=False,
        )


def reverse_gospel_plans(apps, schema_editor):
    """Revert Gospel reading plans to original grouping."""
    ReadingPlanTemplate = apps.get_model('faith', 'ReadingPlanTemplate')

    slugs = [
        'journey-through-matthew',
        'journey-through-mark',
        'journey-through-luke',
        'journey-through-john',
    ]

    ReadingPlanTemplate.objects.filter(slug__in=slugs).update(
        source='',
        source_abbreviation='',
        series='The Gospels',
        is_featured=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('faith', '0014_add_difficulty_level_content'),
    ]

    operations = [
        migrations.RunPython(update_gospel_plans, reverse_gospel_plans),
    ]
