# Generated by Django 4.2.27 on 2026-01-21

from django.db import migrations


def fix_gospel_series(apps, schema_editor):
    """Fix Gospel plans to all be in same series for single grid display."""
    ReadingPlanTemplate = apps.get_model('faith', 'ReadingPlanTemplate')

    # Update all four Gospels to have the same series name
    slugs = [
        'journey-through-matthew',
        'journey-through-mark',
        'journey-through-luke',
        'journey-through-john',
    ]

    ReadingPlanTemplate.objects.filter(slug__in=slugs).update(
        series='The Four Gospels',
    )


def reverse_fix(apps, schema_editor):
    """Revert to individual series names."""
    ReadingPlanTemplate = apps.get_model('faith', 'ReadingPlanTemplate')

    updates = {
        'journey-through-matthew': 'Matthew',
        'journey-through-mark': 'Mark',
        'journey-through-luke': 'Luke',
        'journey-through-john': 'John',
    }

    for slug, series in updates.items():
        ReadingPlanTemplate.objects.filter(slug=slug).update(series=series)


class Migration(migrations.Migration):

    dependencies = [
        ('faith', '0015_update_gospel_plans_grouping'),
    ]

    operations = [
        migrations.RunPython(fix_gospel_series, reverse_fix),
    ]
