# Generated by Django 4.2.27 on 2026-01-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faith', '0016_fix_gospel_plans_single_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingplanassessment',
            name='is_reflection_only',
            field=models.BooleanField(default=False, help_text='If true, just collect answers without scoring'),
        ),
    ]
