"""
Data migration: Complete the Journey Through Mark reading plan.

The original loader had an early-return bug: if the template already existed,
no ReadingPlanDay records were created. Additionally, the plan only covered
Mark 1-13 (16 days), missing chapters 14-16. This migration:

1. Ensures ALL 19 ReadingPlanDay records exist (1-19, Mark 1-16)
2. Updates duration_days from 16 to 19
3. Creates UserReadingProgress entries for any active/paused user plans
   so users see all days immediately
"""

from django.db import migrations


# fmt: off
MARK_DAYS = [
    {
        "day_number": 1,
        "title": "The Servant Announced",
        "scripture_references": ["Mark 1:1-20"],
        "context_summary": "Mark begins abruptly with John the Baptist preparing the way for Jesus. After His baptism and temptation, Jesus begins His Galilean ministry and calls His first disciples. The author is John Mark, companion of Peter, writing for Roman Christians around 65-70 AD.",
        "commentary_beginner": "Mark doesn't start with a birth story\u2014he jumps right into action! John the Baptist appeared in the wilderness, preparing people for Jesus by calling them to repent and be baptized. Then Jesus came from Nazareth to be baptized. The Spirit descended on Him like a dove, and God's voice said, 'You are my Son, whom I love.' After 40 days of temptation in the wilderness, Jesus began preaching: 'The time has come! The kingdom of God is near. Repent and believe the good news!' Walking by the Sea of Galilee, He called fishermen Simon and Andrew, then James and John. They immediately left their nets and followed Him.",
        "commentary_intermediate": "Mark's opening line declares his thesis: Jesus is Christ (Messiah) and Son of God. The Isaiah/Malachi citations establish Jesus in the prophetic story. John's role as Elijah-like forerunner links to Malachi 4:5. The baptism reveals Jesus' identity; the temptation (briefly told\u2014just two verses!) proves His qualification. 'The time has come' (kairos) suggests appointed, decisive time. The disciples' immediate response demonstrates Jesus' compelling authority. 'Fishers of men' transforms their occupation into mission. Mark's characteristic 'immediately' (euthys) appears for the first time\u2014it occurs over 40 times, creating urgency.",
        "commentary_advanced": "Mark's incipit ('beginning of the gospel') may echo Genesis 1:1 or reference the starting point of the Christian proclamation. The composite OT citation (Mal 3:1; Isa 40:3) is attributed only to Isaiah, following ancient citation conventions. The passive 'was baptized' (ebaptisth\u0113) and 'being driven' (ekball\u014d\u2014same word for exorcism) into the wilderness emphasize divine initiative. The Spirit 'tearing open' (schizomenous) the heavens uses violent language anticipating the temple veil being torn. Mark's temptation brevity (contrast Matthew/Luke) fits his action-focused style. The call narrative's structure (Jesus walking, seeing, calling, disciples responding) provides a model of discipleship.",
        "reflection_prompt": "The first disciples 'immediately' left everything to follow Jesus. What would it look like for you to respond to Jesus with that kind of immediacy and abandon?",
    },
    {
        "day_number": 2,
        "title": "The Servant's Authority",
        "scripture_references": ["Mark 1:21-45"],
        "context_summary": "A single dramatic day in Capernaum: Jesus teaches in the synagogue, casts out a demon, heals Peter's mother-in-law, heals many that evening, prays early the next morning, and heals a leper. His fame spreads throughout Galilee.",
        "commentary_beginner": "Jesus went to the synagogue in Capernaum and taught. People were amazed\u2014He taught with authority, not like the regular teachers! A man with an evil spirit interrupted, but Jesus commanded, 'Be quiet! Come out of him!' The demon obeyed. At Peter's house, Jesus healed Peter's mother-in-law from a fever. By evening, the whole town gathered at the door! Jesus healed many sick people and drove out demons. Early the next morning, He went to a quiet place to pray. Then Jesus healed a man with leprosy, touching him and making him clean.",
        "commentary_intermediate": "Mark compresses remarkable events into one 'day in the life' of Jesus. The authority (exousia) in teaching is matched by authority over demons\u2014the unclean spirit recognizes Jesus ('Holy One of God') before humans do. The messianic secret begins: 'Be quiet!' Jesus' prayer and desire to 'go elsewhere' shows His mission focus beyond local popularity. The leper's healing breaks boundaries\u2014leprosy meant social/religious exclusion. Jesus' touch reverses expected contamination.",
        "commentary_advanced": "The Capernaum synagogue teaching introduces key Markan themes: Jesus' authority and the demons' supernatural knowledge. 'Unclean spirit' (pneuma akatharton) contrasts with 'Holy One of God' (ho hagios tou theou)\u2014cosmic conflict. Peter's mother-in-law 'serving' (di\u0113konei) uses the same verb as Jesus' self-description (10:45). The leper's 'if you are willing' (ean thel\u0113s) questions intent, not power. 'Moved with compassion' (splanchnistheis)\u2014some manuscripts read 'moved with anger' (orgistheis), possibly original.",
        "reflection_prompt": "Jesus took time to pray alone before dawn even when crowds demanded His attention. How do you prioritize time with God when life gets busy?",
    },
    {
        "day_number": 3,
        "title": "The Servant Confronts",
        "scripture_references": ["Mark 2:1-28"],
        "context_summary": "Jesus returns to Capernaum and faces growing opposition from religious leaders. He heals a paralyzed man, calls the tax collector Levi (Matthew), and defends His disciples' practices regarding fasting and Sabbath. Conflict with the Pharisees begins to intensify.",
        "commentary_beginner": "Jesus was teaching in a packed house when four friends lowered a paralyzed man through the roof! Jesus first said, 'Your sins are forgiven'\u2014which shocked the religious leaders (only God can forgive sins!). To prove His authority, Jesus healed the man. Everyone was amazed! Later, Jesus called Levi, a tax collector, to follow Him\u2014and then ate dinner with 'sinners.' When criticized, Jesus said, 'I haven't come to call the righteous, but sinners.' He also taught that new wine needs new wineskins\u2014His message was too fresh for old religious forms.",
        "commentary_intermediate": "The paralytic story demonstrates Jesus' authority to forgive sins\u2014a divine prerogative. 'Son of Man' appears here first in Mark, the title Jesus prefers for Himself. Levi's call mirrors the earlier fishermen's call but is more shocking\u2014tax collectors were despised traitors. The new wine/wineskins parable signals that Jesus' movement can't be contained in old religious structures. The Sabbath controversies (grain picking, healing) build toward the deadly conflict of 3:6.",
        "commentary_advanced": "The paralytic's forgiveness ('Your sins are forgiven'\u2014aphientai) uses divine passive. The scribes correctly perceive the claim: 'Who can forgive sins but God alone?' Jesus' 'Son of Man' usage echoes Daniel 7:13-14. Levi sitting 'at the tax booth' (epi to tel\u014dnion) indicates his role in Rome's economic oppression. 'Sinners' (hamart\u014dloi) was a technical term for those outside Pharisaic standards. The bridegroom metaphor (2:19-20) anticipates Jesus' death\u2014the first passion prediction.",
        "reflection_prompt": "Jesus called Levi\u2014someone most 'religious' people avoided. Is there anyone you tend to write off as too far gone? How might Jesus see them differently?",
    },
    {
        "day_number": 4,
        "title": "The Servant Chooses",
        "scripture_references": ["Mark 3:1-35"],
        "context_summary": "Opposition escalates as Jesus heals on the Sabbath and Pharisees plot against Him. Jesus withdraws to the lake, where crowds follow. He appoints twelve apostles, then faces accusations of being demon-possessed. His family thinks He's lost His mind. Jesus redefines true family as those who do God's will.",
        "commentary_beginner": "Jesus healed a man with a shriveled hand on the Sabbath\u2014right in front of religious leaders who were watching to accuse Him! They were furious and began plotting with Herod's supporters to kill Jesus. But crowds kept following Him, and people were healed just by touching Him. Jesus went up a mountain and chose twelve men to be His apostles\u2014His inner circle who would learn from Him and preach. When His own family came to take Him home (they thought He was crazy!), Jesus said His true family is anyone who does God's will.",
        "commentary_intermediate": "The Sabbath healing in the synagogue puts Jesus in direct confrontation with Pharisees\u2014He's angry (org\u0113) at their hardness of heart. The strange alliance of Pharisees and Herodians (political enemies united against Jesus) shows the threat He poses. The Twelve are called to 'be with Him' and to preach\u2014relationship before mission. Simon gets the name Peter (rock). The Beelzebul controversy introduces 'blasphemy against the Holy Spirit'\u2014attributing God's work to Satan. Jesus' biological family is superseded by spiritual family.",
        "commentary_advanced": "The 'Herodians' (H\u0113r\u014ddianoi) are mentioned only in Mark and Matthew\u2014likely political supporters of Herod Antipas. The Twelve's appointment 'on the mountain' echoes Moses and Sinai (Exod 24). The list includes 'Iscariot' (Iskari\u014dth)\u2014possibly 'man of Kerioth' or 'sicarius' (dagger-man). The unforgivable sin is not a single statement but a settled stance of calling the Holy Spirit's work demonic. 'Mother and brothers' (3:31) suggests Jesus' biological family didn't yet believe (cf. John 7:5). The new kinship is based on doing God's will (thel\u0113ma tou theou).",
        "reflection_prompt": "Jesus chose ordinary, flawed people to be His apostles. How does this encourage you about your own usefulness to God? What does it mean to 'be with Him' before doing work for Him?",
    },
    {
        "day_number": 5,
        "title": "The Servant Teaches",
        "scripture_references": ["Mark 4:1-34"],
        "context_summary": "Jesus teaches the crowds in parables from a boat on the Sea of Galilee. He tells the parable of the sower, explains why He uses parables, and shares additional parables about the Kingdom: the lamp, the growing seed, and the mustard seed. He explains the sower parable privately to His disciples.",
        "commentary_beginner": "Jesus taught large crowds using parables\u2014stories with hidden meanings. The parable of the sower describes a farmer scattering seed: some falls on the path (eaten by birds), some on rocky ground (springs up but dies), some among thorns (choked), and some on good soil (produces a huge harvest). Jesus explained that the seed is God's word, and the soils represent different responses. Some people hear but don't understand; some believe briefly; some get distracted by worries and wealth; but some truly receive it and bear fruit\u201430, 60, even 100 times what was sown!",
        "commentary_intermediate": "The parables function both to reveal and conceal\u2014those with 'ears to hear' understand, while the hard-hearted remain blind. The sower parable is foundational: 'Don't you understand this parable? How then will you understand any parable?' The seed growing secretly (unique to Mark) emphasizes God's mysterious work apart from human effort. The mustard seed's contrast between tiny beginning and large result encourages the small movement of Jesus' followers. Jesus interprets the sower privately\u2014disciples have inside access.",
        "commentary_advanced": "The parable purpose statement (4:11-12) cites Isaiah 6:9-10, part of Isaiah's call narrative where hardening is both judgment and mercy (preventing deeper judgment). 'Mystery' (myst\u0113rion) of the Kingdom refers to insider revelation, not incomprehensibility. The soil allegory's emphasis on hearing (akouein) appears eight times. The seed growing 'by itself' (automat\u0113, 4:28) stresses divine sovereignty. The mustard seed hyperbole (smallest seed, largest garden plant) fits apocalyptic imagery of Ezekiel 17:22-24 and Daniel 4:12 about the coming Kingdom.",
        "reflection_prompt": "The parable warns about thorns\u2014'worries of this life, deceitfulness of wealth, and desires for other things.' Which of these poses the greatest threat to your spiritual fruitfulness?",
    },
    {
        "day_number": 6,
        "title": "The Servant Commands",
        "scripture_references": ["Mark 4:35-5:20"],
        "context_summary": "Jesus demonstrates authority over nature and the supernatural. He calms a violent storm on the Sea of Galilee, terrifying His disciples. Then He crosses to Gentile territory and liberates a man possessed by a legion of demons, sending them into a herd of pigs that rush into the sea.",
        "commentary_beginner": "Jesus and His disciples were crossing the Sea of Galilee when a furious storm hit. Waves crashed into the boat while Jesus slept! The terrified disciples woke Him: 'Teacher, don't you care if we drown?' Jesus stood up and simply said, 'Quiet! Be still!' The wind stopped completely. 'Why are you so afraid? Do you still have no faith?' they asked. On the other side, a wild man possessed by many demons lived among tombs. No one could subdue him. When he saw Jesus, he ran and fell at His feet! Jesus commanded the demons out\u2014they entered a herd of pigs that rushed into the sea. The healed man wanted to follow Jesus, but Jesus told him to go tell his family what God had done.",
        "commentary_intermediate": "The storm-calming uses the same 'rebuke' (epitima\u014d) vocabulary as exorcisms\u2014Jesus has authority over chaos. The disciples' question 'Who is this?' advances Mark's identity theme. The Gerasene demoniac lives in Gentile territory (pigs indicate non-Jewish area). 'Legion' (5,000-6,000 soldiers) suggests massive demonic oppression. The demons recognize Jesus ('Son of the Most High God') before humans do. The townspeople's fear and rejection after healing contrasts with the healed man's desire to follow. Jesus commissions him as the first Gentile missionary.",
        "commentary_advanced": "The storm narrative echoes Jonah 1 (sleeping during storm, awoken, sea calmed) and Old Testament theophanies where God rebukes the sea (Ps 89:9, 104:7). 'Quiet! Be still!' (si\u014dpa, pephim\u014dso) uses the perfect tense\u2014'be muzzled and stay muzzled.' The Gerasene region is Decapolis\u2014Hellenistic cities east of Galilee. The demon's 'What do you want with me?' (ti emoi kai soi) is identical to 1 Kings 17:18. 'Adjure you by God' (horkiz\u014d) ironically uses exorcism formula against Jesus. The pigs' destruction may signify unclean spirits returning to the abyss. The healed man's testimony in the Decapolis prepares for Jesus' later Gentile mission.",
        "reflection_prompt": "The disciples asked, 'Who is this? Even the wind and waves obey Him!' How would you answer that question? What storms in your life need Jesus' calming word?",
    },
    {
        "day_number": 7,
        "title": "The Servant Heals",
        "scripture_references": ["Mark 5:21-43"],
        "context_summary": "Two desperate people\u2014a synagogue leader and an unclean woman\u2014encounter Jesus. Jairus begs Jesus to heal his dying daughter. On the way, a woman with a 12-year bleeding condition touches Jesus' cloak and is healed. Despite news of the girl's death, Jesus raises her back to life.",
        "commentary_beginner": "Jairus, an important synagogue leader, fell at Jesus' feet begging Him to heal his dying 12-year-old daughter. As Jesus went with him, a huge crowd pressed around. A woman who had been bleeding for 12 years pushed through and touched Jesus' cloak. She'd spent all her money on doctors and only gotten worse. Instantly she was healed! Jesus knew power had gone out from Him and asked who touched Him. The terrified woman confessed, and Jesus said, 'Daughter, your faith has healed you. Go in peace.' Then word came: Jairus' daughter had died. But Jesus said, 'Don't be afraid; just believe.' He took the parents in, held the girl's hand, and said, 'Little girl, get up!' She stood up and walked around!",
        "commentary_intermediate": "The 'sandwich' structure (Jairus' request, woman healed, girl raised) is Mark's literary technique. Both stories involve 12 years\u2014the woman's illness and the girl's age\u2014emphasizing completeness of restoration. The bleeding made the woman ritually unclean for 12 years; touching Jesus should defile Him, but instead she's cleansed. 'Daughter' (thygat\u0113r) is Jesus' only use of this address\u2014she's welcomed into God's family. The mourners' laughter at Jesus shows genuine death. 'Talitha koum' preserves Jesus' Aramaic\u2014Mark's audience hears Jesus' actual voice.",
        "commentary_advanced": "The woman's hemorrhage (en rhysei haimatos) rendered her perpetually unclean (Lev 15:25-30), excluding her from worship and society. Her touch of Jesus' garment reverses expected contamination\u2014purity flows from Jesus. 'Power' (dynamis) going out suggests Jesus' healing costs Him. Jairus represents the establishment (archisun\u0101g\u014dgos) humbling himself. 'Asleep' (katheud\u014d) may be euphemism or may indicate the temporary nature of death before Jesus. 'Talitha koum' (5:41) and 'Ephphatha' (7:34) are rare Aramaic preservations emphasizing Peter's eyewitness testimony behind Mark. The secrecy command (5:43) maintains the messianic secret.",
        "reflection_prompt": "The bleeding woman had 'faith enough' to just touch Jesus' cloak. Jairus had to keep believing even after his daughter died. What step of faith might Jesus be asking of you today?",
    },
    {
        "day_number": 8,
        "title": "The Servant Rejected",
        "scripture_references": ["Mark 6:1-29"],
        "context_summary": "Jesus returns to His hometown of Nazareth but is rejected by those who knew Him as a child. He sends out the Twelve on mission with authority over evil spirits. Meanwhile, Herod Antipas hears about Jesus and recalls how he beheaded John the Baptist at his wife's scheming.",
        "commentary_beginner": "Jesus went home to Nazareth and taught in the synagogue. People were amazed but also offended\u2014isn't this just the carpenter, Mary's son? They couldn't believe anything special about someone they'd watched grow up. Jesus could do few miracles there because of their unbelief. 'A prophet is honored everywhere except in his hometown.' Jesus then sent the Twelve out in pairs with authority over evil spirits. They were to travel light\u2014no extra provisions\u2014and depend on hospitality. If rejected, shake the dust off your feet. Meanwhile, King Herod heard about Jesus and worried He was John the Baptist risen from the dead. The story of John's murder follows: Herodias tricked Herod into executing John as a birthday party favor.",
        "commentary_intermediate": "Nazareth's rejection stems from familiarity\u2014they see only 'the carpenter' (ho tekt\u014dn). 'Brothers and sisters' are named, suggesting real siblings (James, Joses, Judas, Simon). Jesus' inability to do miracles there isn't about power but about appropriate context\u2014faith matters. The disciples' mission mirrors Jesus' ministry (preaching, exorcism, healing) and anticipates their post-resurrection work. Traveling without provisions teaches dependence on God and hospitality. Herod's guilty conscience makes him think Jesus is John resurrected. The detailed account of John's death (the only extended narrative without Jesus present) parallels Jesus' coming passion.",
        "commentary_advanced": "'The carpenter' (ho tekt\u014dn) was broader than woodworker\u2014general construction work. The phrase 'Is not this the carpenter?' may be derogatory. Some manuscripts read 'the carpenter's son' (as in Matthew). Herod Antipas was technically 'tetrarch' not 'king' (Mark's usage may be colloquial or ironic). Herodias was originally married to Herod's half-brother Philip. John's rebuke about the marriage being 'not lawful' (ouk exestin) references Leviticus 18:16, 20:21. Salome's dance and Herod's rash oath echo the Esther narrative but end in death rather than deliverance. John's burial by his disciples parallels Jesus' burial.",
        "reflection_prompt": "Familiarity bred contempt in Nazareth. Are there ways you've become too familiar with Jesus\u2014reducing Him to a comfortable, manageable figure rather than the powerful Lord?",
    },
    {
        "day_number": 9,
        "title": "The Servant Provides",
        "scripture_references": ["Mark 6:30-56"],
        "context_summary": "The apostles return from their mission. Jesus tries to give them rest, but crowds follow. Moved with compassion, He teaches them and then feeds 5,000 men with five loaves and two fish. That night He walks on water to His struggling disciples. Wherever He goes, people are healed.",
        "commentary_beginner": "The apostles returned excited about all they'd done. Jesus invited them to rest in a quiet place, but crowds got there first. Instead of being annoyed, Jesus felt compassion\u2014'they were like sheep without a shepherd'\u2014and taught them. When evening came, Jesus told the disciples to feed the crowd. They had only five loaves and two fish. Jesus blessed the food, broke it, and everyone ate until full\u2014over 5,000 men! Twelve baskets of leftovers remained. Later, the disciples were struggling to row against the wind when Jesus walked on the water toward them. They thought He was a ghost! 'Take courage! It is I. Don't be afraid.' He got in the boat and the wind died down. They were completely amazed\u2014they still hadn't understood about the loaves.",
        "commentary_intermediate": "'Sheep without a shepherd' (6:34) echoes Numbers 27:17 and Ezekiel 34\u2014Israel's leaders have failed; Jesus is the true Shepherd-King. The feeding miracle recalls Moses and manna but surpasses it. 'Green grass' indicates springtime, near Passover. The sequence (took, blessed, broke, gave) anticipates the Last Supper. Twelve baskets suggest provision for all twelve tribes\u2014complete provision for Israel. Walking on water demonstrates divine identity (Job 9:8, Psalm 77:19\u2014God alone walks on the sea). 'It is I' (ego eimi) may carry divine name overtones. The disciples' failure to understand links back to 'hardened hearts.'",
        "commentary_advanced": "The feeding's symbolic dimensions: Jesus as new Moses (wilderness, bread), true David-shepherd (2 Sam 5:2), and messianic host of the eschatological banquet (Isa 25:6-8). 'Companies' (symposia symposia, prasiai prasiai) in groups of 50 and 100 echoes Israel's wilderness organization (Exod 18:21). The 'fourth watch' (3-6 AM) timing emphasizes the disciples' long struggle. 'He intended to pass by them' (parerchomai) uses theophany language (Exod 33:19, 22; 1 Kings 19:11)\u2014Jesus isn't abandoning them but revealing Himself. Their 'hardened hearts' (pep\u014dromen\u0113 kardia) anticipates the Pharisees' hardness (3:5) and becomes a recurring theme. The summary statement (6:53-56) shows widespread healing ministry.",
        "reflection_prompt": "The disciples had just fed 5,000 people miraculously, yet hours later they were afraid on the sea. Why is it so hard to remember God's past faithfulness when facing new challenges?",
    },
    {
        "day_number": 10,
        "title": "The Servant Corrects",
        "scripture_references": ["Mark 7:1-37"],
        "context_summary": "Pharisees from Jerusalem criticize Jesus' disciples for eating with unwashed hands. Jesus challenges their use of tradition to avoid God's commands and declares all foods clean. He then travels to Gentile territory, heals a Syrophoenician woman's daughter and a deaf-mute man.",
        "commentary_beginner": "Religious leaders from Jerusalem criticized Jesus' disciples for not washing their hands the 'right' way before eating. Jesus turned it around: 'You hypocrites! You honor God with your lips, but your hearts are far from Him.' He exposed how they used religious traditions to avoid actually obeying God\u2014like the 'Corban' loophole that let people avoid helping their parents. Jesus taught that what defiles a person isn't what goes in (food) but what comes out (evil thoughts, greed, malice). Then in Gentile territory, a Greek woman begged Jesus to heal her demon-possessed daughter. Jesus' response seemed harsh\u2014'First let the children eat; it's not right to throw their food to the dogs.' But she replied cleverly about dogs eating children's crumbs, and Jesus praised her faith and healed her daughter.",
        "commentary_intermediate": "The handwashing dispute concerns oral tradition (tradition of the elders), not hygiene or biblical law. Jesus quotes Isaiah 29:13 to expose the gap between worship and heart. The 'Corban' example shows how tradition can nullify Scripture\u2014declaring something 'devoted to God' to avoid supporting parents. 'Nothing outside a person can defile them' is revolutionary\u2014it struck at the heart of Jewish purity laws. The Syrophoenician woman's encounter is Jesus' only extended conversation with a Gentile. 'Children' (Jews) and 'dogs' (Gentiles) was common distinction; she turns it around cleverly. Jesus' 'first' suggests priority not exclusion. The deaf-mute's healing uses physical actions and 'Ephphatha' (Aramaic 'Be opened')\u2014reminiscent of Isaiah 35:5-6's messianic age.",
        "commentary_advanced": "The tradition of the elders (paradosis t\u014dn presbyter\u014dn) represents Pharisaic oral law later codified in the Mishnah. Jesus distinguishes divine commandment (entol\u0113 tou theou) from human tradition. Mark's aside 'Thus he declared all foods clean' (7:19b) is editorial interpretation\u2014its implications took decades to work out in the early church (Acts 10). The Syrophoenician woman is 'Hell\u0113nis, Syrophonikissa' (Greek-speaking, from Syrian Phoenicia)\u2014thoroughly Gentile. 'Dogs' (kynaria) is diminutive (puppies), possibly softening the insult. Her response models persistence and wit. 'Ephphatha' preserves Jesus' Aramaic, connecting this healing to the deaf-mute's literal and Israel's metaphorical deafness. The messianic secret ('tell no one') is again disobeyed.",
        "reflection_prompt": "Jesus said defilement comes from within\u2014evil thoughts, greed, pride. Which of the vices He listed (7:21-22) do you most need to guard against in your own heart?",
    },
    {
        "day_number": 11,
        "title": "The Servant Reveals",
        "scripture_references": ["Mark 8:1-38"],
        "context_summary": "Jesus feeds 4,000 people in Gentile territory. Pharisees demand a sign; Jesus warns against their 'yeast.' After healing a blind man in two stages, Jesus asks the crucial question: 'Who do you say I am?' Peter confesses Him as the Christ, but Jesus predicts His suffering and rebukes Peter for opposing God's plan.",
        "commentary_beginner": "Jesus fed another huge crowd\u2014this time 4,000 people with seven loaves. The disciples still worried about having no bread despite seeing two feeding miracles! Jesus asked, 'Do you have eyes but fail to see, ears but fail to hear?' He healed a blind man in two stages\u2014first partial sight, then clear vision. Then came the big question: 'Who do people say I am?' Various answers came\u2014John the Baptist, Elijah, a prophet. 'But who do you say I am?' Peter declared, 'You are the Messiah!' But when Jesus explained that the Messiah must suffer and die, Peter protested. Jesus' response was shocking: 'Get behind me, Satan!' Then Jesus taught that following Him means denying yourself and taking up your cross.",
        "commentary_intermediate": "The second feeding in Gentile territory parallels the first (Jewish territory), suggesting Jesus' mission includes both. Seven baskets (spyris\u2014larger than the twelve kophinos) may symbolize Gentile completeness. The disciples' continued confusion about bread shows spiritual dullness\u2014they've seen but not understood. The two-stage blind man healing uniquely illustrates the disciples' own slow-growing sight. Peter's confession is the Gospel's turning point\u2014now Jesus can teach about His suffering. 'Get behind me, Satan' recalls the temptation\u2014Peter unknowingly offers the same shortcut. 'Take up your cross' would shock hearers\u2014crucifixion was Rome's shameful execution. Losing life to save it inverts worldly wisdom.",
        "commentary_advanced": "The '4,000' in Gentile Decapolis with 'seven' baskets contrasts with '5,000' in Jewish Galilee with 'twelve' baskets\u2014careful parallelism. The Pharisees' demand for 'a sign from heaven' (s\u0113meion apo tou ouranou) seeks authenticating miracle; Jesus' refusal implies His works already authenticate. The 'yeast' warning (8:15) uniquely includes 'yeast of Herod'\u2014political corruption alongside religious. The blind man's two-stage healing (unique to Mark) functions as parable: disciples see partially, full sight comes later. Caesarea Philippi's setting near pagan shrines makes Peter's confession pointed. 'Christ' (Christos = Messiah) is a political title; Jesus redefines it through suffering. The passion prediction uses 'dei' (must)\u2014divine necessity. Peter's rebuke (epitima\u014d) uses the same verb Jesus used on demons. The 'this generation' that will see the Son of Man coming (9:1) likely refers to the Transfiguration.",
        "reflection_prompt": "Peter confessed Jesus as Christ but rejected the cross. Are there ways you want Jesus' benefits without His way of self-denial? What does 'taking up your cross' look like for you?",
    },
    {
        "day_number": 12,
        "title": "The Servant's Glory",
        "scripture_references": ["Mark 9:1-50"],
        "context_summary": "Jesus is transfigured before Peter, James, and John\u2014His glory revealed on the mountain. Coming down, He heals a boy the other disciples couldn't help. He predicts His death again and teaches about true greatness, hell's reality, and radical commitment. 'Salt' and 'peace' become watchwords.",
        "commentary_beginner": "Six days after Peter's confession, Jesus took Peter, James, and John up a high mountain. Suddenly His clothes became dazzling white\u2014brighter than any bleach could make them! Moses and Elijah appeared and talked with Jesus. Peter wanted to build shelters, but a cloud covered them and God's voice said, 'This is my Son, whom I love. Listen to Him!' Coming down, Jesus healed a demon-possessed boy the other disciples couldn't help. 'Everything is possible for one who believes,' Jesus said. The father cried, 'I do believe; help my unbelief!' Jesus predicted His death again, but the disciples argued about which of them was greatest. Jesus said the first must be last and servant of all. Using a child as an example, He taught about welcoming others in His name.",
        "commentary_intermediate": "The Transfiguration reveals Jesus' divine glory\u2014metamorpho\u014d means essential transformation, not just appearance. Moses and Elijah represent the Law and Prophets, now superseded by Jesus. Peter's 'shelters' (sk\u0113nas) may reference the Feast of Tabernacles' messianic expectations. 'Listen to Him' echoes Deuteronomy 18:15\u2014Jesus is the prophet like Moses. The boy's healing teaches about prayer and faith working together. 'This kind' of demon requires prayer (some manuscripts add 'and fasting'). The second passion prediction is simpler but met with the disciples' fear and silence. The 'greatest' argument shows complete misunderstanding\u2014Jesus teaches that true greatness is serving. The 'millstone' warning about causing little ones to sin uses hyperbole for emphasis. 'Salt' preserves and seasons\u2014disciples must maintain their distinctiveness.",
        "commentary_advanced": "The 'six days' (9:2) may evoke Sinai's cloud covering for six days before Moses entered (Exod 24:16). 'Metamorpho\u014d' (transfigured) indicates real change, not optical illusion. Moses and Elijah's 'departure' discussion (Luke 9:31) connects to exodus/death terminology. Peter's 'Rabbi' (9:5) is less than his earlier 'Christ' confession\u2014confusion returns. The divine voice combines Psalm 2:7 (coronation), Isaiah 42:1 (Servant), and Deuteronomy 18:15 (Prophet). The epileptic boy's symptoms (described in detail) echo the disciples' own spiritual deafness/dumbness. 'I believe; help my unbelief' captures authentic faith\u2014trust mixed with struggle. The 'salt' saying (9:49-50) is difficult\u2014possible links to covenant salt (Lev 2:13), purifying judgment, or preserving peace. 'Have salt among yourselves' may mean maintaining distinctiveness while living at peace.",
        "reflection_prompt": "The father cried, 'I believe; help my unbelief!' This is one of the most honest prayers in Scripture. What would it look like for you to pray with that kind of honesty about your own struggles with faith?",
    },
    {
        "day_number": 13,
        "title": "The Servant's Way",
        "scripture_references": ["Mark 10:1-52"],
        "context_summary": "Jesus travels toward Jerusalem, teaching about divorce, blessing children, challenging a rich man, and predicting His death a third time. James and John request positions of honor; Jesus teaches servant leadership. Blind Bartimaeus receives his sight and follows Jesus on the road.",
        "commentary_beginner": "Jesus traveled toward Jerusalem, teaching along the way. Pharisees tested Him about divorce; Jesus pointed to God's original design\u2014one man, one woman, lifelong union. When people brought children for blessing and disciples tried to stop them, Jesus was indignant: 'Let the little children come to me!' A rich man asked how to inherit eternal life. He'd kept the commandments, but Jesus said, 'Sell everything, give to the poor, and follow me.' The man went away sad\u2014he had great wealth. 'It's easier for a camel to go through a needle's eye than for a rich person to enter God's Kingdom.' But with God, all things are possible! When James and John asked for top positions, Jesus taught that the greatest must serve. Near Jericho, blind Bartimaeus cried out for mercy. Jesus healed him, and he followed Jesus on the road.",
        "commentary_intermediate": "The divorce question reflects the Shammai/Hillel debate. Jesus goes beyond both, pointing to creation: 'What God has joined, let no one separate.' The exception clause in Matthew is absent here\u2014Mark emphasizes the absolute ideal. 'Receive the kingdom like a child' means dependent trust, not innocence. The rich man's failure contrasts with the disciples who 'left everything.' The third passion prediction is most detailed\u2014mocking, spitting, flogging, death, resurrection. James and John's request shows persistent misunderstanding. Jesus' 'cup' and 'baptism' mean suffering. 'Ransom for many' (lytron anti poll\u014dn) is key atonement theology. Bartimaeus' 'Son of David' is messianic acclamation. His casting off his cloak and following 'on the road' (to Jerusalem) models discipleship.",
        "commentary_advanced": "The divorce discussion uses 'test' (peiraz\u014d)\u2014the same word as Satan's temptation. Jesus' hardness of heart (skl\u0113rokardia) diagnosis echoes Moses' concession (Deut 24:1). The 'one flesh' (mia sarx) citation from Genesis 2:24 grounds marriage in creation order. The rich man is 'good' (agathos) in his question\u2014Jesus redirects: 'Why call me good? No one is good except God alone.' This either deflects divinity or implies it. The camel/needle's eye is deliberately absurd hyperbole\u2014no gate, rope, or other softening. 'Ransom' (lytron) is the only Mark/Matthew occurrence, foundational for substitutionary atonement. 'For many' (anti poll\u014dn) uses substitutionary preposition. Bartimaeus (bar Timaios\u2014'son of Timaios') is named, suggesting known figure in early church. His title 'Rabbouni' (10:51) is heightened form of 'Rabbi.'",
        "reflection_prompt": "The rich man went away sad because he couldn't let go of his wealth. Bartimaeus immediately threw off his cloak and followed Jesus. What might you need to 'throw off' to follow Jesus more freely?",
    },
    {
        "day_number": 14,
        "title": "The Servant Enters",
        "scripture_references": ["Mark 11:1-33"],
        "context_summary": "Jesus enters Jerusalem as King, riding a donkey while crowds wave palm branches and shout 'Hosanna!' He curses an unfruitful fig tree and clears the temple of merchants. The fig tree withers, illustrating judgment on fruitless Israel. Religious leaders challenge Jesus' authority; He responds with a counter-question.",
        "commentary_beginner": "Jesus sent disciples to find a donkey, telling them exactly where it would be. He rode into Jerusalem while crowds spread cloaks and branches on the road, shouting, 'Hosanna! Blessed is he who comes in the name of the Lord!' This fulfilled prophecy about the Messiah coming humbly on a donkey. Jesus entered the temple and saw people buying and selling. He drove them out: 'My house will be called a house of prayer for all nations, but you've made it a den of robbers!' The religious leaders began looking for a way to kill Him. The next day, a fig tree Jesus had cursed had withered completely\u2014a picture of Israel's spiritual fruitlessness. 'Have faith in God,' Jesus said. 'Whatever you ask in prayer, believe you have received it, and it will be yours.'",
        "commentary_intermediate": "The donkey procurement shows Jesus' foreknowledge or prearrangement. Zechariah 9:9 describes a peaceful king on a donkey, not a warhorse. 'Hosanna' means 'save now!' (Psalm 118:25-26). The temple cleansing targets the commercialization of worship, particularly in the Court of the Gentiles meant for Gentile prayer. 'Den of robbers' (Jer 7:11) indicts corruption. The fig tree episode brackets the temple cleansing (Mark's sandwich structure)\u2014both illustrate judgment on fruitless Israel. Jesus' teaching on faith and prayer follows from the fig tree's response to His word. Forgiving others is essential for answered prayer. The authority question from religious leaders leads to Jesus' counter-question about John's baptism\u2014exposing their political calculation rather than genuine seeking.",
        "commentary_advanced": "The colt 'never ridden' (p\u014dlon... eph' hon oudeis oup\u014d anthr\u014dp\u014dn ekathisen) fulfills the requirement for sacred use (Num 19:2, Deut 21:3, 1 Sam 6:7). The Psalm 118 acclamation was used at pilgrim festivals; 'Blessed is the coming kingdom of our father David' adds explicit messianic interpretation. The temple action combines Isaiah 56:7 ('house of prayer for all nations') with Jeremiah 7:11 ('den of robbers')\u2014Jesus acts as prophet critiquing the system. The fig tree's 'not the season for figs' (11:13) makes the cursing seem unreasonable unless understood symbolically\u2014Israel should bear fruit regardless. The withering happens 'from the roots' (ek rhiz\u014dn)\u2014radical judgment. The 'mountain' (11:23) likely refers to the Mount of Olives or temple mount\u2014eschatological language. The authority question uses exousia (11:28)\u2014the same word marking Jesus' ministry since 1:22.",
        "reflection_prompt": "Jesus cleared the temple because it had become about commerce rather than prayer and worship. What 'money changers' might need to be cleared from your life so your heart can be a true house of prayer?",
    },
    {
        "day_number": 15,
        "title": "The Servant Teaches",
        "scripture_references": ["Mark 12:1-44"],
        "context_summary": "Jesus tells a parable about tenants who kill the vineyard owner's son. He answers tricky questions about taxes to Caesar, resurrection, and the greatest commandment. He warns about hypocritical teachers and praises a poor widow who gives all she has.",
        "commentary_beginner": "Jesus told a story about a vineyard owner who rented to tenants. When he sent servants to collect fruit, they beat and killed them. Finally he sent his own son\u2014surely they'd respect him! But they killed the son to get the inheritance. The owner will destroy those tenants and give the vineyard to others. Religious leaders knew Jesus was talking about them! They tried to trap Him with questions. 'Should we pay taxes to Caesar?' If He said no, He'd be a revolutionary; if yes, He'd seem to approve of Roman oppression. Jesus asked for a coin: 'Whose image is this?' Caesar's. 'Give to Caesar what is Caesar's, and to God what is God's.' Amazing! The greatest commandment? Love God with all your heart, and love your neighbor as yourself. Then Jesus pointed out a poor widow putting two tiny coins in the offering\u2014'She gave more than all the rich because she gave everything she had.'",
        "commentary_intermediate": "The vineyard parable (Isaiah 5 background) clearly allegorizes Israel's history: God (owner), Israel (vineyard), leaders (tenants), prophets (servants), Jesus (son). The 'cornerstone' citation (Psalm 118:22-23) adds resurrection hope\u2014the rejected stone becomes central. The tribute question's 'image' (eik\u014dn) implies humans bear God's image\u2014give yourselves to God! The Sadducees' resurrection question uses an absurd scenario; Jesus answers from the Torah they accept: 'I am the God of Abraham...' (present tense\u2014they're alive!). The scribe who agrees about love over sacrifice earns 'You are not far from the kingdom.' Jesus' question about David's son/Lord (Psalm 110:1) suggests Messiah is greater than Davidic. The widow's 'two small coins' (lepta duo) is everything she had to live on\u2014radical trust.",
        "commentary_advanced": "The parable's vineyard echoes Isaiah 5:1-7 (beloved's vineyard = Israel). The 'beloved son' (huios agap\u0113tos) uses Jesus' baptismal title. 'Outside the vineyard' (12:8) may anticipate Jesus' death outside Jerusalem. The cornerstone citation combines rejection and exaltation themes. The Herodians' involvement (12:13) shows political-religious alliance against Jesus. 'Image and inscription' (eik\u014dn kai epigraph\u0113) on the denarius was Tiberius with divine claims\u2014Jesus' answer is subversive while appearing compliant. Sadducees' levirate marriage scenario (Deut 25:5-6) was a standard anti-resurrection argument. Jesus' 'like angels' corrects their materialistic assumptions. The Shema (Deut 6:4-5) plus neighbor love (Lev 19:18) summarizes Torah. The scribe's agreement goes beyond debate to insight. The widow's 'whole life' (holon ton bion) emphasizes totality of her giving\u2014a model of discipleship before Jesus gives His all.",
        "reflection_prompt": "The widow gave 'everything she had to live on.' Jesus valued her tiny gift above large donations from the rich. What does this teach you about the measure God uses to evaluate giving and sacrifice?",
    },
    {
        "day_number": 16,
        "title": "The Servant Predicts",
        "scripture_references": ["Mark 13:1-37"],
        "context_summary": "On the Mount of Olives, Jesus predicts the temple's destruction and teaches about the end times. He warns of false messiahs, persecution, and cosmic upheaval. The Son of Man will come with power and glory. No one knows the day or hour\u2014watch and be ready!",
        "commentary_beginner": "As they left the temple, a disciple admired its massive stones. Jesus shocked them: 'Not one stone will be left on another\u2014every one will be thrown down!' On the Mount of Olives, Peter, James, John, and Andrew asked when this would happen. Jesus warned of deception: 'Many will come claiming to be me.' There will be wars, earthquakes, and famines\u2014but that's just the beginning. His followers will be persecuted, arrested, and hated. But the gospel must be preached to all nations! When they see 'the abomination of desolation,' flee immediately! After that tribulation, the sun and moon will darken, stars will fall, and the Son of Man will come with clouds, power, and glory. Angels will gather the chosen from everywhere. Learn from the fig tree: when it sprouts, summer is near. Watch! No one knows the exact time\u2014not angels, not even the Son\u2014only the Father. Be alert! You don't know when the master returns.",
        "commentary_intermediate": "Mark 13 (the 'Olivet Discourse') addresses both the temple's destruction (70 AD) and the end times. The temple's massive stones (some 40 feet long, 12 feet high) seemed indestructible. 'Birth pains' (\u014ddines) is apocalyptic imagery\u2014the old age dying to birth the new. The 'abomination of desolation' (Daniel 9:27, 11:31) likely references a desecrating event in the temple. 'Let the reader understand' may be Mark's note to readers about prophetic interpretation. The cosmic imagery (sun, moon, stars) draws on Isaiah 13:10, 34:4\u2014theophanic language for God's intervention. The fig tree parable teaches discernment of signs, not date-setting. Even Jesus in His humanity didn't know the day\u2014emphasizing mystery and the call to watchfulness. The doorkeeper illustration calls for constant readiness.",
        "commentary_advanced": "The discourse's interpretation is debated: preterist (fulfilled in 70 AD), futurist (yet to come), or both (near/far horizons). 'These things' (tauta, 13:4, 29, 30) and 'that day' (ekein\u0113s t\u0113s h\u0113meras, 13:32) may distinguish near and far events. The 'abomination' (bdelygma t\u0113s er\u0113m\u014dse\u014ds) in Daniel refers to Antiochus IV's altar; here possibly to Roman standards in the temple or a future figure. 'Son of Man coming with clouds' quotes Daniel 7:13-14\u2014vindication and authority. 'This generation' (h\u0113 genea haut\u0113, 13:30) could mean Jesus' contemporaries, the human race, or the generation seeing final signs. Jesus' ignorance (oude ho huios, 13:32) reflects His kenotic humanity; some early manuscripts omit this. The four watches (evening, midnight, rooster-crow, dawn) structure the Passion narrative. 'Gr\u0113goreo' (stay awake/watch) becomes a key virtue\u2014the disciples will fail in Gethsemane.",
        "reflection_prompt": "Jesus emphasized readiness over date-setting. 'Be on guard! Be alert!' If you knew Jesus was returning this week, what would you do differently? Why not live that way now?",
    },
    {
        "day_number": 17,
        "title": "The Servant Anointed and Betrayed",
        "scripture_references": ["Mark 14:1-72"],
        "context_summary": "The Passion narrative begins. A woman anoints Jesus at Bethany while Judas plots betrayal. Jesus shares the Last Supper with His disciples, institutes the Lord's Supper, and predicts Peter's denial. In Gethsemane, He agonizes in prayer, is arrested, and stands trial before the Sanhedrin. Peter denies Him three times.",
        "commentary_beginner": "Two days before Passover, religious leaders plotted to arrest Jesus secretly. At dinner in Bethany, a woman poured expensive perfume on Jesus' head. Some were angry at the 'waste,' but Jesus said she was preparing His body for burial\u2014'She has done a beautiful thing.' Judas went to the chief priests to betray Jesus. On Passover, Jesus sent disciples to prepare a room. During supper, He said, 'One of you will betray me.' They were sad, asking 'Surely not I?' He took bread, broke it: 'This is my body.' Then the cup: 'This is my blood of the covenant, poured out for many.' He told Peter, 'Before the rooster crows twice, you will deny me three times.' In Gethsemane, Jesus was deeply distressed: 'Father, take this cup from me. Yet not what I will, but what you will.' The disciples kept falling asleep. Judas arrived with an armed crowd and betrayed Jesus with a kiss. Everyone fled. Before the high priest, witnesses gave false testimony. Jesus finally declared, 'I am' the Christ. They condemned Him. Outside, Peter denied Jesus three times\u2014and wept.",
        "commentary_intermediate": "Mark 14 weaves contrasting responses to Jesus: the woman's extravagant devotion versus Judas' calculated betrayal. The 300 denarii value equals a year's wages\u2014her act is prophetic, preparing for burial. The Last Supper's 'blood of the covenant' echoes Exodus 24:8 (Sinai covenant) with 'poured out for many' from Isaiah 53:12 (the Suffering Servant). Gethsemane ('oil press') is fitting for crushing anguish. 'Abba, Father' reveals intimate relationship amid crisis. Jesus asks for the cup's removal\u2014a genuine human struggle, not theatrical. The three prayers mirror three denials. The young man fleeing naked (14:51-52) is unique to Mark\u2014possibly Mark himself. Before the Sanhedrin, Jesus' 'I am' (eg\u014d eimi) is His clearest self-identification, combining Messiah (Psalm 110:1) and Son of Man (Daniel 7:13). Peter's denial fulfills Jesus' prediction exactly\u2014the rooster's second crow triggers his breakdown.",
        "commentary_advanced": "The anointing pericope frames the Passion between devotion and betrayal. The woman's act fulfills a prophetic/royal function (cf. 1 Sam 16:13), though Jesus reinterprets it as burial preparation. Mark's 'wherever the gospel is preached' (14:9) breaks the narrative frame\u2014a post-Easter perspective embedded in the story. The Last Supper's covenant theology is debated: new covenant (Jer 31:31-34) or renewed Sinai covenant? 'For many' (hyper poll\u014dn) is Semitic inclusive language ('for all'). Gethsemane's 'the hour' (h\u0113 h\u014dra) and 'the cup' (to pot\u0113rion) are loaded theological terms\u2014the appointed time and God's wrath/judgment. 'Abba' (14:36) is Aramaic preserved in Greek text\u2014rare in prayer, suggesting authentic Jesus tradition. The naked young man (neaniskos, 14:51-52) has generated theories: Mark's signature, baptismal symbolism, or contrast with the 'young man' (neaniskos) at the tomb (16:5) who is clothed in white. The Sanhedrin trial's historicity is debated\u2014nighttime trial violates Mishnaic rules, though those rules may be later codifications. Jesus' 'I am' (eg\u014d eimi) combined with 'you will see' merges present claim with future vindication. Peter's tears (eklain) represent the failure of human resolve without divine empowerment\u2014a theme Mark's audience would recognize from their own persecutions.",
        "reflection_prompt": "In Gethsemane, Jesus modeled honest prayer: telling God what He wanted, yet surrendering to God's will. How do you balance honesty and surrender in your own prayers during difficult times?",
    },
    {
        "day_number": 18,
        "title": "The Servant Crucified",
        "scripture_references": ["Mark 15:1-47"],
        "context_summary": "Jesus stands trial before Pilate, is mocked by soldiers, and is crucified at Golgotha. Darkness covers the land. Jesus cries out and dies. The temple curtain tears from top to bottom. A Roman centurion declares, 'Truly this man was the Son of God!' Joseph of Arimathea buries Jesus in a tomb.",
        "commentary_beginner": "Early morning, the Jewish leaders handed Jesus to Pilate, the Roman governor. Pilate asked, 'Are you the King of the Jews?' Jesus answered, 'You say so.' The crowd chose to release Barabbas (a murderer) instead of Jesus. Soldiers mocked Jesus with a purple robe and crown of thorns: 'Hail, King of the Jews!' They forced Simon of Cyrene to carry Jesus' cross to Golgotha ('Place of the Skull'). They crucified Him at 9 AM. The sign read: 'The King of the Jews.' Two robbers hung beside Him. People mocked: 'Save yourself! Come down from the cross!' At noon, darkness covered everything for three hours. At 3 PM, Jesus cried out, 'My God, my God, why have you forsaken me?' With a loud cry, He died. The temple curtain ripped from top to bottom! A centurion watching said, 'Surely this man was the Son of God!' Women who had followed Jesus watched from a distance. Joseph of Arimathea asked Pilate for the body and laid Jesus in a rock-cut tomb, rolling a stone over the entrance.",
        "commentary_intermediate": "Mark's crucifixion account is stark and unflinching. The Barabbas episode is ironic: the innocent dies so the guilty goes free\u2014a substitutionary picture. The soldiers' mockery unwittingly proclaims truth: purple robe and crown = actual kingship. Simon of Cyrene (father of Alexander and Rufus, known to Mark's community\u2014Romans 16:13?) represents the call to take up one's cross (8:34). The three-hour darkness echoes Amos 8:9 and Exodus 10:22\u2014divine judgment and cosmic significance. Jesus' cry (Psalm 22:1) is not despair but lament\u2014Psalm 22 moves from forsakenness to vindication and universal praise. The torn curtain (from top to bottom\u2014God's action) signals open access to God's presence. The centurion's confession is the climax of Mark's Christology: a Gentile soldier, seeing how Jesus died, makes the confession the disciples never could. The women's presence preserves witness continuity. Joseph's bold act (tolm\u0113sas) risks defilement and political consequences.",
        "commentary_advanced": "Mark's Passion narrative follows a three-hour structure: crucifixion at the third hour (9 AM), darkness at the sixth (noon), death at the ninth (3 PM). This may reflect liturgical time-keeping for early Christian worship. The Barabbas scene's textual tradition is complex\u2014some manuscripts name him 'Jesus Barabbas,' heightening the irony: 'Jesus, son of the father' vs. Jesus, the actual Son of the Father. The centurion's 'Son of God' (huios theou) forms an inclusio with Mark 1:1. Without the article ('a son of God' vs 'the Son of God'), it's ambiguous in Greek\u2014but Mark's readers know the full meaning. The cry of dereliction (El\u014di, El\u014di, lema sabachthani) is Aramaic/Hebrew, the most authentic of all passion sayings. The bystanders' confusion with Elijah (\u0112lian) may be wordplay or genuine misunderstanding. The torn curtain (katapetasma, either inner or outer) symbolizes the end of temple mediation. Mark's crucifixion strips away all human glory\u2014no repentant thief (Luke), no 'It is finished' (John), no earthquake saints (Matthew). Just abandonment, darkness, a cry, and death. This is Mark's theology of the cross in its rawest form. The burial by Joseph (a council member\u2014the same council that condemned Jesus) introduces ambiguity: was he a secret disciple or simply performing pious duty? Mark says 'waiting for the kingdom of God' (prosdechomenos t\u0113n basileian), leaving readers to decide.",
        "reflection_prompt": "The centurion recognized who Jesus was by watching how He died. What does it mean that Jesus' identity was most clearly revealed not in miracles or teaching, but in suffering? How does this shape your understanding of strength and weakness?",
    },
    {
        "day_number": 19,
        "title": "The Servant Risen",
        "scripture_references": ["Mark 16:1-20"],
        "context_summary": "On Sunday morning, three women go to anoint Jesus' body. They find the stone rolled away and a young man in white who announces: 'He has risen! He is not here.' The longer ending records Jesus' appearances and His final commission: 'Go into all the world and preach the gospel to all creation.'",
        "commentary_beginner": "When the Sabbath was over, Mary Magdalene, Mary the mother of James, and Salome bought spices to anoint Jesus' body. Very early Sunday morning, they went to the tomb, wondering, 'Who will roll away the stone?' But it was already rolled back! Inside, a young man in a white robe said, 'Don't be alarmed. You are looking for Jesus who was crucified. He has risen! He is not here. See the place where they laid Him. Go, tell His disciples and Peter that He is going ahead of you to Galilee.' The women fled, trembling and amazed. [The longer ending adds:] Jesus appeared first to Mary Magdalene, then to two disciples walking in the country, then to the eleven as they ate. He said, 'Go into all the world and preach the gospel to all creation. Whoever believes and is baptized will be saved.' After speaking, Jesus was taken up into heaven and sat at the right hand of God. The disciples went out and preached everywhere, and the Lord worked with them, confirming the message with signs.",
        "commentary_intermediate": "Mark's resurrection account is striking in its brevity. The women's spice-buying assumes no resurrection expectation\u2014this is raw grief meeting divine surprise. The 'young man' (neaniskos) in white echoes the young man who fled naked at Jesus' arrest (14:51-52)\u2014now clothed, present at the empty tomb. 'And Peter' is a personal restoration message\u2014the denier is not forgotten. The original ending at 16:8 ('they said nothing to anyone, for they were afraid') is shocking: fear, silence, and incompleteness. This may be deliberate\u2014Mark invites the reader to complete the story through their own response to the risen Christ. The longer ending (16:9-20), likely added later, harmonizes with the other Gospels: appearances to Mary Magdalene, two disciples, and the eleven. The Great Commission ('Go into all the world') universalizes the gospel beyond Jewish boundaries. The signs (casting out demons, speaking in tongues, handling serpents, healing the sick) reflect early church experience in Acts.",
        "commentary_advanced": "The ending of Mark is the most debated textual problem in the New Testament. The earliest manuscripts (Sinaiticus, Vaticanus) end at 16:8 with 'ephobounto gar' ('for they were afraid')\u2014ending a Greek sentence (and an entire Gospel) with 'gar' is grammatically unusual but not unprecedented. Three main positions exist: (1) Mark intentionally ended at 16:8, creating an open ending that forces reader response; (2) the original ending was lost; (3) Mark was interrupted before finishing. The longer ending (16:9-20) is absent from the best manuscripts and differs in vocabulary and style, but was known by the 2nd century (Irenaeus quotes 16:19). It may preserve authentic early tradition even if not original to Mark. The 'young man' (neaniskos) clothed in a white robe (stol\u0113n leuk\u0113n) has generated extensive scholarly discussion\u2014angel, baptismal symbol, or literary device? His message contains the core kerygma: crucified, risen, going before you. 'Going ahead to Galilee' (proagei hymas) recalls 14:28 and represents return to the place of calling and mission\u2014not Jerusalem (Luke/John) but Galilee where discipleship began. The women's silence (16:8) creates the 'messianic secret's' final paradox: the greatest secret (resurrection) produces the greatest silence. Yet Mark's Gospel exists\u2014someone told. The reader knows the ending because they hold it in their hands. Mark's abrupt close is arguably the most brilliant literary ending in antiquity\u2014it transforms every reader from spectator to participant.",
        "reflection_prompt": "The angel's message included 'and Peter'\u2014a personal invitation to the one who had failed most publicly. What does it mean to you that the risen Jesus specifically sought out the one who denied Him? Is there an area of failure where you need to hear your name called?",
    },
]
# fmt: on


def complete_mark_plan(apps, schema_editor):
    """Ensure all 19 days exist for Journey Through Mark and update duration."""
    ReadingPlanTemplate = apps.get_model("faith", "ReadingPlanTemplate")
    ReadingPlanDay = apps.get_model("faith", "ReadingPlanDay")
    UserReadingPlan = apps.get_model("faith", "UserReadingPlan")
    UserReadingProgress = apps.get_model("faith", "UserReadingProgress")

    try:
        template = ReadingPlanTemplate.objects.get(slug="journey-through-mark")
    except ReadingPlanTemplate.DoesNotExist:
        # Plan hasn't been loaded yet — loader will create it with all 19 days
        return

    # Update duration_days and description
    template.duration_days = 19
    template.description = (
        "A 19-day journey through the complete Gospel of Mark, "
        "the shortest and most action-packed Gospel. Mark portrays "
        "Jesus as the powerful Servant who acts decisively. Written "
        "for a Roman audience, it emphasizes what Jesus did more "
        "than what He said."
    )
    template.save()

    # Create ALL ReadingPlanDay records (get_or_create is safe for existing ones)
    new_days = []
    for day_data in MARK_DAYS:
        day, created = ReadingPlanDay.objects.get_or_create(
            plan=template,
            day_number=day_data["day_number"],
            defaults={
                "title": day_data["title"],
                "scripture_references": day_data["scripture_references"],
                "context_summary": day_data["context_summary"],
                "commentary_beginner": day_data["commentary_beginner"],
                "commentary_intermediate": day_data["commentary_intermediate"],
                "commentary_advanced": day_data["commentary_advanced"],
                "reflection_prompt": day_data["reflection_prompt"],
            },
        )
        if created:
            new_days.append(day)

    # Create UserReadingProgress for any active/paused user plans missing days
    if new_days:
        active_plans = UserReadingPlan.objects.filter(
            template=template,
            plan_status__in=["active", "paused"],
        )
        for user_plan in active_plans:
            for day in new_days:
                UserReadingProgress.objects.get_or_create(
                    user_plan=user_plan,
                    plan_day=day,
                    defaults={"user": user_plan.user},
                )


def reverse_mark_plan(apps, schema_editor):
    """Remove days 17-19 and revert duration (days 1-16 are kept)."""
    ReadingPlanTemplate = apps.get_model("faith", "ReadingPlanTemplate")
    ReadingPlanDay = apps.get_model("faith", "ReadingPlanDay")

    try:
        template = ReadingPlanTemplate.objects.get(slug="journey-through-mark")
    except ReadingPlanTemplate.DoesNotExist:
        return

    # Remove only the new days (cascades to UserReadingProgress)
    ReadingPlanDay.objects.filter(
        plan=template,
        day_number__in=[17, 18, 19],
    ).delete()

    template.duration_days = 16
    template.save()


class Migration(migrations.Migration):

    dependencies = [
        ("faith", "0018_routine_maintenance_bridge_choices"),
    ]

    operations = [
        migrations.RunPython(complete_mark_plan, reverse_mark_plan),
    ]
