# Generated by Django 4.2.27 on 2026-07-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faith', '0021_refresh_gospel_plan_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblestudynote',
            name='content_plain',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='faithmilestone',
            name='description_plain',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='answer_notes_plain',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='description_plain',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
