# Generated by Django 4.2.27 on 2026-07-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faith', '0023_backfill_faith_richtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='category',
            field=models.CharField(blank=True, choices=[('family', 'Family & relationships'), ('health', 'Health & healing'), ('provision', 'Work & provision'), ('guidance', 'Guidance & decisions'), ('gratitude', 'Gratitude & praise'), ('growth', 'Spiritual growth'), ('others', 'Others & the world')], default='', help_text='A gentle grouping for this prayer', max_length=20),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='reminder_time',
            field=models.TimeField(blank=True, help_text='Optional time of day for a reminder (future-ready)', null=True),
        ),
    ]
