# Generated by Django 4.2.27 on 2026-08-07 14:09

from django.db import migrations, models
from django.db.models.functions import TruncDate


def backfill_reading_date(apps, schema_editor):
    """Seed reading_date for existing completed rows from completed_at's date.

    For legacy rows the two truths were conflated, so completed_at's date is
    the best available occurrence date. After this, every is_completed row has
    a reading_date, and going forward mark_complete() sets it explicitly — so
    the completed_at-vs-reading_date reads stay identical for all historical
    data (no streak/history regression) and only diverge for genuine off-day
    completions (the new capability).
    """
    UserReadingProgress = apps.get_model('faith', 'UserReadingProgress')
    (UserReadingProgress.objects
     .filter(is_completed=True, completed_at__isnull=False, reading_date__isnull=True)
     .update(reading_date=TruncDate('completed_at')))


class Migration(migrations.Migration):

    dependencies = [
        ('faith', '0024_prayerrequest_archived_at_prayerrequest_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreadingprogress',
            name='reading_date',
            field=models.DateField(blank=True, db_index=True, help_text='Calendar day this reading satisfies (the occurrence). Distinct from completed_at (when it was marked done).', null=True),
        ),
        migrations.RunPython(backfill_reading_date, migrations.RunPython.noop),
    ]
