# Generated by Django 5.2.9 on 2025-12-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="dashboard_config",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
