# Generated by Django 5.2.9 on 2025-12-25 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userpreferences_dashboard_config"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="termsacceptance",
            options={
                "ordering": ["-accepted_at"],
                "verbose_name": "terms acceptance",
                "verbose_name_plural": "terms acceptances",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelOptions(
            name="userpreferences",
            options={
                "verbose_name": "user preferences",
                "verbose_name_plural": "user preferences",
            },
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="hobbies",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of user's hobbies/interests for personalization",
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="termsacceptance",
            name="accepted_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=255, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into the admin site.",
            ),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="accent_color",
            field=models.CharField(
                blank=True,
                help_text="Custom hex color to override theme accent",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="ai_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable AI-powered insights and reflections"
            ),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="dashboard_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Dashboard tile layout and visibility settings",
            ),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="faith_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable Faith module and faith-aware content"
            ),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="theme",
            field=models.CharField(
                choices=[
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("faith", "Christian Faith"),
                    ("sports", "Sports & Performance"),
                    ("nature", "Animals & Nature"),
                    ("outdoors", "Outdoors & Adventure"),
                    ("minimal", "Minimal / Life Focus"),
                ],
                default="minimal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="User's timezone for date/time display",
                max_length=50,
            ),
        ),
    ]
