# Generated by Django 5.2.9 on 2025-12-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_termsacceptance_options_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="finances_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable Finances module for budget tracking and financial goals",
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="goals_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable Goals module for setting and tracking personal goals",
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="habits_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable Habits module for building and tracking daily habits",
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="health_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable Health module for tracking weight, fasting, heart rate, and glucose",
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="journal_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable Journal module for daily reflections and entries",
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="relationships_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable Relationships module for tracking connections and interactions",
            ),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="faith_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable Faith module with Scripture, prayers, and faith-aware content",
            ),
        ),
    ]
