# Generated by Django 5.2.9 on 2025-12-25 20:34

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_userpreferences_finances_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Profile picture (optional)",
                null=True,
                upload_to=apps.users.models.user_avatar_path,
            ),
        ),
    ]
