# Generated by Django 5.2.9 on 2025-12-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="life_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable Life module for projects, tasks, calendar, inventory, pets, recipes, and documents",
            ),
        ),
    ]
