# Generated by Django 5.2.9 on 2025-12-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_userpreferences_life_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="purpose_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable Purpose module for annual direction, goals, intentions, and reflections",
            ),
        ),
    ]
