# Generated by Django 5.2.9 on 2025-12-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_userpreferences_purpose_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="ai_coaching_style",
            field=models.CharField(
                choices=[
                    ("gentle", "Gentle Guide"),
                    ("supportive", "Supportive Partner"),
                    ("direct", "Direct Coach"),
                ],
                default="supportive",
                help_text="AI personality style for insights and feedback",
                max_length=20,
            ),
        ),
    ]
