# Generated by Django 5.2.9 on 2025-12-26 23:19

from django.db import migrations


def noop(apps, schema_editor):
    """
    No-op migration.

    Superuser creation is now handled by the management command
    `create_superuser_from_env` which runs at startup.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userpreferences_ai_coaching_style'),
    ]

    operations = [
        migrations.RunPython(noop, noop),
    ]
