# Generated by Django 5.2.9 on 2025-12-26 23:19

import os
from django.db import migrations


def create_superuser(apps, schema_editor):
    """
    Create initial superuser from environment variables.

    Set these in Railway:
    - DJANGO_SUPERUSER_EMAIL
    - DJANGO_SUPERUSER_PASSWORD
    """
    email = os.environ.get('DJANGO_SUPERUSER_EMAIL')
    password = os.environ.get('DJANGO_SUPERUSER_PASSWORD')

    if not email or not password:
        print("Skipping superuser creation: DJANGO_SUPERUSER_EMAIL or DJANGO_SUPERUSER_PASSWORD not set")
        return

    User = apps.get_model('users', 'User')

    # Check if superuser already exists
    if User.objects.filter(email=email).exists():
        print(f"Superuser {email} already exists, skipping creation")
        return

    # Create the superuser
    user = User.objects.create(
        email=email,
        is_staff=True,
        is_superuser=True,
        is_active=True,
    )
    user.set_password(password)
    user.save()

    # Create UserPreferences for the superuser
    UserPreferences = apps.get_model('users', 'UserPreferences')
    UserPreferences.objects.get_or_create(user=user)

    print(f"Created superuser: {email}")


def reverse_superuser(apps, schema_editor):
    """Reverse migration - do nothing (don't delete the superuser)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userpreferences_ai_coaching_style'),
    ]

    operations = [
        migrations.RunPython(create_superuser, reverse_superuser),
    ]
