# Generated by Django 5.2.9 on 2025-12-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_create_initial_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='faith_enabled',
            field=models.BooleanField(default=True, help_text='Enable Faith module with Scripture, prayers, and faith-aware content'),
        ),
    ]
