# Generated by Django 5.2.9 on 2025-12-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_change_faith_default_to_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='default_bible_translation',
            field=models.CharField(blank=True, default='', help_text="Default Bible translation ID for Scripture lookup (e.g., 'de4e12af7f28f599-02' for KJV)", max_length=50),
        ),
    ]
