# Generated by Django 5.2.9 on 2025-12-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_add_default_bible_translation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreferences",
            name="ai_coaching_style",
            field=models.CharField(
                default="supportive",
                help_text="AI coaching style key (loaded from CoachingStyle model)",
                max_length=50,
            ),
        ),
    ]
