# Generated by Django 5.2.9 on 2025-12-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_add_ai_data_consent"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="show_whats_new",
            field=models.BooleanField(
                default=True,
                help_text="Show 'What's New' popup when new features are released",
            ),
        ),
    ]
