# Generated by Django 5.2.9 on 2025-12-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_add_ai_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreferences",
            name="ai_profile",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Personal details for AI personalization (age, family, interests, goals, health conditions, etc.)",
                max_length=2000,
            ),
        ),
    ]
