# Generated by Django 5.2.9 on 2025-12-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_alter_userpreferences_ai_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="default_fasting_type",
            field=models.CharField(
                choices=[
                    ("16:8", "16:8 Intermittent Fasting"),
                    ("18:6", "18:6 Extended Fast"),
                    ("20:4", "20:4 Warrior Diet"),
                    ("OMAD", "OMAD (One Meal A Day)"),
                    ("24h", "24 Hour Fast"),
                    ("36h", "36 Hour Extended Fast"),
                    ("custom", "Custom"),
                ],
                default="16:8",
                help_text="Your preferred fasting schedule. This will be pre-selected when starting a new fast.",
                max_length=10,
            ),
        ),
    ]
