# Generated by Django 5.2.9 on 2025-12-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_add_default_fasting_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="carbs_percentage",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Target percentage of calories from carbohydrates (0-100)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="daily_calorie_goal",
            field=models.PositiveIntegerField(
                blank=True, help_text="Daily caloric intake goal", null=True
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="fat_percentage",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Target percentage of calories from fat (0-100)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="protein_percentage",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Target percentage of calories from protein (0-100)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="weight_goal",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Target weight goal",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="weight_goal_target_date",
            field=models.DateField(
                blank=True, help_text="Target date to achieve weight goal", null=True
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="weight_goal_unit",
            field=models.CharField(
                choices=[("lb", "Pounds"), ("kg", "Kilograms")],
                default="lb",
                help_text="Unit for weight goal",
                max_length=2,
            ),
        ),
    ]
