# Generated by Django 5.2.9 on 2025-12-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_add_weight_nutrition_goals"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="personal_assistant_consent",
            field=models.BooleanField(
                default=False,
                help_text="User consents to Personal Assistant accessing journal entries, tasks, goals, health data for personalized coaching",
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="personal_assistant_consent_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when user consented to Personal Assistant data access",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="personal_assistant_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable Personal Assistant for AI-powered daily guidance, priorities, and coaching",
            ),
        ),
    ]
