# Generated by Django 5.2.9 on 2025-12-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_add_personal_assistant_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number in E.164 format (e.g., +1XXXXXXXXXX)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="phone_verified",
            field=models.BooleanField(
                default=False,
                help_text="Has the phone number been verified via SMS code?",
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="phone_verified_at",
            field=models.DateTimeField(
                blank=True, help_text="When the phone was verified", null=True
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="sms_consent",
            field=models.BooleanField(
                default=False,
                help_text="User has consented to receive SMS notifications",
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="sms_consent_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When user consented to SMS notifications",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="sms_enabled",
            field=models.BooleanField(
                default=False, help_text="Master toggle for SMS notifications"
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="sms_event_reminders",
            field=models.BooleanField(
                default=True, help_text="Send SMS reminders for calendar events"
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="sms_fasting_reminders",
            field=models.BooleanField(
                default=False, help_text="Send fasting window reminders"
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="sms_medicine_refill_alerts",
            field=models.BooleanField(
                default=True, help_text="Send SMS alerts when medicine supply is low"
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="sms_medicine_reminders",
            field=models.BooleanField(
                default=True, help_text="Send SMS reminders for medicine doses"
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="sms_prayer_reminders",
            field=models.BooleanField(
                default=False, help_text="Send daily prayer reminders"
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="sms_quiet_end",
            field=models.TimeField(default="07:00", help_text="End of quiet hours"),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="sms_quiet_hours_enabled",
            field=models.BooleanField(
                default=True, help_text="Respect quiet hours for SMS notifications"
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="sms_quiet_start",
            field=models.TimeField(
                default="22:00", help_text="Start of quiet hours (no SMS)"
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="sms_task_reminders",
            field=models.BooleanField(
                default=True, help_text="Send SMS reminders for task due dates"
            ),
        ),
    ]
