# Generated by Django 5.2.9 on 2025-12-31 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_sms_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreferences",
            name="sms_quiet_end",
            field=models.TimeField(
                default=datetime.time(7, 0), help_text="End of quiet hours"
            ),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="sms_quiet_start",
            field=models.TimeField(
                default=datetime.time(22, 0), help_text="Start of quiet hours (no SMS)"
            ),
        ),
    ]
