# Generated by Django 5.2.9 on 2025-12-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_fix_quiet_hours_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="sms_significant_event_reminders",
            field=models.BooleanField(
                default=True,
                help_text="Send SMS reminders for significant events (birthdays, anniversaries)",
            ),
        ),
    ]
