# Generated by Django 5.2.9 on 2026-01-03 20:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_convert_legacy_timezones"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPBlocklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.CharField(
                        db_index=True,
                        help_text="IPv4 or IPv6 address to block",
                        max_length=45,
                    ),
                ),
                (
                    "cidr_range",
                    models.CharField(
                        blank=True,
                        help_text="Optional CIDR notation for range blocks (e.g., /24)",
                        max_length=50,
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Block"),
                            ("automated", "Automated Block"),
                            ("temporary", "Temporary Block"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for blocking this IP"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this block expires (null = permanent)",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who created this block",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ip_blocks_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "IP blocklist entry",
                "verbose_name_plural": "IP blocklist entries",
                "db_table": "users_ip_blocklist",
                "ordering": ["-created_at"],
            },
        ),
    ]
