# Generated by Django 5.2.9 on 2026-01-03 20:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_add_ip_blocklist"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisposableEmailDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        db_index=True,
                        help_text="Domain name (e.g., 'tempmail.com')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("added_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "source",
                    models.CharField(
                        default="manual",
                        help_text="How this domain was added (manual, import, api)",
                        max_length=50,
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this domain is confirmed as disposable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disposable email domain",
                "verbose_name_plural": "Disposable email domains",
                "db_table": "users_disposable_email_domain",
                "ordering": ["domain"],
            },
        ),
    ]
