# Generated by Django 5.2.9 on 2026-01-03 23:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_add_disposable_email_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignupAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email_hash",
                    models.CharField(
                        help_text="SHA-256 hash of normalized email address",
                        max_length=64,
                    ),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        help_text="SHA-256 hash of IP address", max_length=64
                    ),
                ),
                (
                    "fingerprint_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash of device fingerprint data",
                        max_length=64,
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="Browser user agent string",
                        max_length=500,
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True,
                        help_text="Two-letter country code from IP geolocation",
                        max_length=2,
                    ),
                ),
                (
                    "risk_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Composite risk score (0.0 = safe, 1.0 = high risk)",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="unknown",
                        help_text="Categorized risk level",
                        max_length=20,
                    ),
                ),
                (
                    "captcha_score",
                    models.FloatField(
                        blank=True,
                        help_text="reCAPTCHA v3 score (0.0-1.0, higher is more human)",
                        null=True,
                    ),
                ),
                (
                    "ip_reputation_score",
                    models.FloatField(
                        blank=True,
                        help_text="IP reputation score from external service",
                        null=True,
                    ),
                ),
                (
                    "email_risk_score",
                    models.FloatField(
                        blank=True,
                        help_text="Email risk score (disposable, typosquat, etc.)",
                        null=True,
                    ),
                ),
                (
                    "behavioral_score",
                    models.FloatField(
                        blank=True,
                        help_text="Behavioral analysis score (timing, mouse movement)",
                        null=True,
                    ),
                ),
                (
                    "device_score",
                    models.FloatField(
                        blank=True,
                        help_text="Device fingerprint uniqueness/trust score",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("allowed", "Allowed"),
                            ("challenged", "Challenged"),
                            ("blocked", "Blocked"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="pending",
                        help_text="Current status of signup attempt",
                        max_length=20,
                    ),
                ),
                (
                    "block_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("rate_limited", "Rate Limited"),
                            ("high_risk", "High Risk Score"),
                            ("disposable_email", "Disposable Email"),
                            ("honeypot", "Honeypot Triggered"),
                            ("blocklist", "IP/Email Blocklist"),
                            ("captcha_failed", "CAPTCHA Failed"),
                        ],
                        help_text="Reason for blocking if status is 'blocked'",
                        max_length=30,
                    ),
                ),
                (
                    "captcha_verified",
                    models.BooleanField(
                        default=False, help_text="CAPTCHA challenge passed"
                    ),
                ),
                (
                    "phone_verified",
                    models.BooleanField(
                        default=False, help_text="Phone number verified via SMS"
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(
                        default=False, help_text="Email address verified via link"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the signup attempt was initiated",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the signup was completed (user created)",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User created from this attempt (if completed)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signup_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Signup attempt",
                "verbose_name_plural": "Signup attempts",
                "db_table": "users_signup_attempt",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at", "status"],
                        name="users_signu_created_493288_idx",
                    ),
                    models.Index(
                        fields=["ip_hash", "created_at"],
                        name="users_signu_ip_hash_5559a2_idx",
                    ),
                    models.Index(
                        fields=["email_hash", "created_at"],
                        name="users_signu_email_h_de793c_idx",
                    ),
                ],
            },
        ),
    ]
