# Generated by Django 5.2.10 on 2026-01-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_add_assistant_confirm_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='dismissed_intro_banners',
            field=models.JSONField(blank=True, default=list, help_text='List of module intro banners the user has dismissed'),
        ),
    ]
