# Generated by Django 5.2.10 on 2026-01-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_add_dismissed_intro_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='search_history',
            field=models.JSONField(blank=True, default=list, help_text='List of recent search queries (max 10 items)'),
        ),
    ]
