# Generated by Django 5.2.10 on 2026-01-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_add_search_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='ai_profile_nudge_dismissed',
            field=models.BooleanField(default=False, help_text='User has permanently dismissed the AI profile setup nudge'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='ai_profile_nudge_snoozed_until',
            field=models.DateTimeField(blank=True, null=True, help_text="If set, hide the AI profile nudge until this datetime (for 'remind me later')"),
        ),
    ]
