# Generated by Django 5.2.10 on 2026-01-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_ai_profile_nudge_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='health_features',
            field=models.JSONField(blank=True, default=dict, help_text='Sub-feature toggles for Health module'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='organize_features',
            field=models.JSONField(blank=True, default=dict, help_text='Sub-feature toggles for Organize module'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='goals_features',
            field=models.JSONField(blank=True, default=dict, help_text='Sub-feature toggles for Goals module'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='faith_features',
            field=models.JSONField(blank=True, default=dict, help_text='Sub-feature toggles for Faith module'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='journal_features',
            field=models.JSONField(blank=True, default=dict, help_text='Sub-feature toggles for Journal module'),
        ),
    ]
