# Generated by Django 4.2.27 on 2026-01-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_userpreferences_default_fasting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth for age verification (must be 13+ to use service)', null=True),
        ),
    ]
