# Generated by Django 4.2.27 on 2026-01-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_add_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='capture_enabled',
            field=models.BooleanField(default=True, help_text='Enable Capture module for audio recording and transcription'),
        ),
    ]
