# Generated by Django 4.2.27 on 2026-01-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_capture_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('prefer_not_to_say', 'Prefer not to say')], help_text='Used to personalize health features such as cycle tracking', max_length=20, null=True),
        ),
    ]
