# Generated by Django 4.2.27 on 2026-01-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_add_gender_to_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='development_notice_seen_at',
            field=models.DateTimeField(blank=True, help_text='When the user saw the development notice modal', null=True),
        ),
    ]
