# Generated by Django 4.2.27 on 2026-01-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_add_development_notice_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='faith_only_selected_at',
            field=models.DateTimeField(blank=True, help_text='When the user selected the Faith Only plan (used for upgrade prompt scheduling)', null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='faith_only_upgrade_month2_shown',
            field=models.BooleanField(default=False, help_text='Has the Month 2 upgrade prompt been shown?'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='faith_only_upgrade_month2_shown_at',
            field=models.DateTimeField(blank=True, help_text='When the Month 2 upgrade prompt was shown', null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='faith_only_upgrade_month3_shown',
            field=models.BooleanField(default=False, help_text='Has the Month 3 (final) upgrade prompt been shown?'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='faith_only_upgrade_month3_shown_at',
            field=models.DateTimeField(blank=True, help_text='When the Month 3 upgrade prompt was shown', null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='faith_only_upgrade_week1_shown',
            field=models.BooleanField(default=False, help_text='Has the Week 1 upgrade prompt been shown?'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='faith_only_upgrade_week1_shown_at',
            field=models.DateTimeField(blank=True, help_text='When the Week 1 upgrade prompt was shown', null=True),
        ),
    ]
