# Generated by Django 4.2.27 on 2026-01-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_add_faith_only_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='sms_milestone_reminders',
            field=models.BooleanField(default=True, help_text='Send SMS reminders for approaching goal milestones'),
        ),
    ]
