# Generated by Django 4.2.27 on 2026-01-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_add_milestone_reminders_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='dismissed_quarterly_reviews',
            field=models.JSONField(blank=True, default=list, help_text="List of quarterly reviews the user has dismissed (e.g., '2026-Q1')"),
        ),
    ]
