# Generated by Django 4.2.27 on 2026-01-20 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_add_dismissed_quarterly_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='email_notification_frequency',
            field=models.CharField(choices=[('immediate', 'Immediate (as they occur)'), ('daily_digest', 'Daily Digest')], default='daily_digest', help_text='How often to receive email notifications', max_length=20),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Master toggle for email notifications'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notification_reminder_time',
            field=models.TimeField(default=datetime.time(7, 0), help_text='Daily reminder time for reading plans and other scheduled notifications'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notification_setup_shown',
            field=models.BooleanField(default=False, help_text='Has the notification setup popup been shown to this user?'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Master toggle for in-app notifications'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notify_email_event',
            field=models.BooleanField(default=True, help_text='Email notifications for calendar events'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notify_email_finance',
            field=models.BooleanField(default=True, help_text='Email notifications for finance alerts'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notify_email_journal',
            field=models.BooleanField(default=True, help_text='Email notifications for journal prompts'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notify_email_medicine',
            field=models.BooleanField(default=True, help_text='Email notifications for medicine reminders'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notify_email_milestone',
            field=models.BooleanField(default=True, help_text='Email notifications for goal milestones'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notify_email_prayer',
            field=models.BooleanField(default=True, help_text='Email notifications for prayer reminders'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notify_email_reading_plan',
            field=models.BooleanField(default=True, help_text='Email notifications for reading plan reminders'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notify_email_significant_event',
            field=models.BooleanField(default=True, help_text='Email notifications for significant events'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notify_email_task',
            field=models.BooleanField(default=True, help_text='Email notifications for task due dates'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notify_inapp_event',
            field=models.BooleanField(default=True, help_text='In-app notifications for calendar events'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notify_inapp_finance',
            field=models.BooleanField(default=True, help_text='In-app notifications for finance alerts'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notify_inapp_journal',
            field=models.BooleanField(default=True, help_text='In-app notifications for journal prompts'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notify_inapp_medicine',
            field=models.BooleanField(default=True, help_text='In-app notifications for medicine reminders'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notify_inapp_milestone',
            field=models.BooleanField(default=True, help_text='In-app notifications for goal milestones'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notify_inapp_prayer',
            field=models.BooleanField(default=True, help_text='In-app notifications for prayer reminders'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notify_inapp_reading_plan',
            field=models.BooleanField(default=True, help_text='In-app notifications for reading plan reminders'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notify_inapp_significant_event',
            field=models.BooleanField(default=True, help_text='In-app notifications for significant events'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notify_inapp_task',
            field=models.BooleanField(default=True, help_text='In-app notifications for task due dates'),
        ),
    ]
