# Generated by Django 4.2.27 on 2026-01-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_notification_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='dashboard_setup_complete',
            field=models.BooleanField(default=False, help_text='Whether user has completed dashboard tile customization setup'),
        ),
    ]
