# Generated by Django 4.2.27 on 2026-01-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_dashboard_setup_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='show_goal_deadline_badges',
            field=models.BooleanField(default=True, help_text='Show deadline badges on goals (Due in X days, Past target date, etc.)'),
        ),
    ]
