# Generated by Django 4.2.27 on 2026-01-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_add_show_goal_deadline_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='reading_plan_difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner - New to Bible study'), ('intermediate', 'Intermediate - Familiar but want more context'), ('advanced', 'Advanced - Deep dive with scholarly insights')], default='intermediate', help_text='Preferred difficulty level for reading plan commentary', max_length=20),
        ),
    ]
