# Generated by Django 4.2.27 on 2026-01-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_add_reading_plan_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='_ai_personal_context',
            field=models.TextField(blank=True, db_column='ai_personal_context', default='', help_text='Encrypted: Facts learned about the user from AI conversations for personalized responses'),
        ),
    ]
