# Generated by Django 4.2.27 on 2026-01-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_add_ai_personal_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='notify_email_capture',
            field=models.BooleanField(default=True, help_text='Email notifications for capture processing completion'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='notify_inapp_capture',
            field=models.BooleanField(default=True, help_text='In-app notifications for capture processing completion'),
        ),
    ]
