# Generated by Django 4.2.27 on 2026-01-24 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_capture_notification_prefs'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFAEmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='6-digit verification code', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this code expires (10 minutes from creation)')),
                ('used', models.BooleanField(default=False, help_text='Whether this code has been used')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the code was used', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address that requested the code', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_email_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MFA email code',
                'verbose_name_plural': 'MFA email codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
