# Generated by Django 4.2.27 on 2026-01-25 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_mfa_email_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text="Unique identifier (e.g., 'journal', 'health', 'faith')", max_length=50, unique=True)),
                ('name', models.CharField(help_text="Display name shown in navigation (e.g., 'Journal', 'Health')", max_length=50)),
                ('description', models.CharField(blank=True, help_text='Brief description of what this module does', max_length=200)),
                ('icon_svg', models.TextField(help_text='SVG path data for the module icon')),
                ('route_name', models.CharField(help_text="Django URL name for the module home (e.g., 'journal:home')", max_length=100)),
                ('default_order', models.PositiveIntegerField(default=0, help_text='Default display order for new users')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this module is available to users')),
                ('preference_field', models.CharField(blank=True, help_text="UserPreferences field name for enable toggle (e.g., 'journal_enabled')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Module Definition',
                'verbose_name_plural': 'Module Definitions',
                'ordering': ['default_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserModulePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this module appears in navigation')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text="User's custom display order (lower numbers appear first)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='users.moduledefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Module Preference',
                'verbose_name_plural': 'User Module Preferences',
                'ordering': ['sort_order', 'module__default_order'],
                'unique_together': {('user', 'module')},
            },
        ),
    ]
