# Generated by Django 4.2.27 on 2026-01-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_add_module_navigation_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='hide_nav_on_scroll',
            field=models.BooleanField(default=False, help_text='Hide navigation bars when scrolling down on mobile (show on scroll up)'),
        ),
    ]
