# Generated by Django 4.2.27 on 2026-01-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_add_hide_nav_on_scroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='desktop_nav_collapsed',
            field=models.BooleanField(default=False, help_text='Collapse the desktop left rail to icons only'),
        ),
    ]
