# Generated by Claude - data migration to populate ModuleDefinition records

from django.db import migrations


def populate_module_definitions(apps, schema_editor):
    """Ensure ModuleDefinition records exist."""
    ModuleDefinition = apps.get_model('users', 'ModuleDefinition')

    modules = [
        {
            'slug': 'journal',
            'name': 'Journal',
            'description': 'Daily reflections and journal entries',
            'icon_svg': '<path d="M12 20h9M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"/>',
            'route_name': 'journal:home',
            'default_order': 1,
            'is_active': True,
            'preference_field': 'journal_enabled',
        },
        {
            'slug': 'health',
            'name': 'Health',
            'description': 'Track weight, fitness, nutrition, and wellness',
            'icon_svg': '<path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/>',
            'route_name': 'health:home',
            'default_order': 2,
            'is_active': True,
            'preference_field': 'health_enabled',
        },
        {
            'slug': 'faith',
            'name': 'Faith',
            'description': 'Scripture, prayers, and spiritual growth',
            'icon_svg': '<path d="M12 2v20M7 7h10"/>',
            'route_name': 'faith:home',
            'default_order': 3,
            'is_active': True,
            'preference_field': 'faith_enabled',
        },
        {
            'slug': 'life',
            'name': 'Organize',
            'description': 'Projects, tasks, calendar, and home management',
            'icon_svg': '<path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/>',
            'route_name': 'life:home',
            'default_order': 4,
            'is_active': True,
            'preference_field': 'life_enabled',
        },
        {
            'slug': 'purpose',
            'name': 'Goals',
            'description': 'Life goals, intentions, and yearly focus',
            'icon_svg': '<circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/>',
            'route_name': 'purpose:home',
            'default_order': 5,
            'is_active': True,
            'preference_field': 'purpose_enabled',
        },
        {
            'slug': 'finance',
            'name': 'Finance',
            'description': 'Budget tracking and financial goals',
            'icon_svg': '<path d="M12 1v22M17 5H9.5a3.5 3.5 0 000 7h5a3.5 3.5 0 010 7H6"/>',
            'route_name': 'finance:dashboard',
            'default_order': 6,
            'is_active': True,
            'preference_field': 'finances_enabled',
        },
        {
            'slug': 'capture',
            'name': 'Capture',
            'description': 'Audio recording and transcription',
            'icon_svg': '<path d="M12 1a3 3 0 0 0-3 3v8a3 3 0 0 0 6 0V4a3 3 0 0 0-3-3z"/><path d="M19 10v2a7 7 0 0 1-14 0v-2"/><line x1="12" y1="19" x2="12" y2="23"/><line x1="8" y1="23" x2="16" y2="23"/>',
            'route_name': 'capture:list',
            'default_order': 7,
            'is_active': True,
            'preference_field': 'capture_enabled',
        },
    ]

    for module_data in modules:
        ModuleDefinition.objects.update_or_create(
            slug=module_data['slug'],
            defaults=module_data,
        )


def reverse_migration(apps, schema_editor):
    # Don't delete data on reverse - too risky
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_add_desktop_nav_collapsed'),
    ]

    operations = [
        migrations.RunPython(populate_module_definitions, reverse_migration),
    ]
