# Generated by Claude - data migration to fix module route_names
# This migration ensures all route_name values are properly namespaced

from django.db import migrations


def fix_route_names(apps, schema_editor):
    """Fix any module definitions with incorrect route_name values."""
    ModuleDefinition = apps.get_model('users', 'ModuleDefinition')

    # Mapping of slug -> correct route_name
    correct_routes = {
        'journal': 'journal:home',
        'health': 'health:landing',  # Landing page at /health/, not /health/physical/
        'faith': 'faith:home',
        'life': 'life:home',
        'purpose': 'purpose:home',
        'finance': 'finance:dashboard',
        'capture': 'capture:list',
    }

    for slug, route_name in correct_routes.items():
        ModuleDefinition.objects.filter(slug=slug).update(route_name=route_name)


def reverse_migration(apps, schema_editor):
    # No reverse needed - just leave data as-is
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_populate_module_definitions'),
    ]

    operations = [
        migrations.RunPython(fix_route_names, reverse_migration),
    ]
