# Generated by Django 4.2.27 on 2026-01-25 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_fix_module_route_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_hash', models.CharField(db_index=True, help_text="SHA-256 hash of the deleted user's email (for fraud detection)", max_length=64)),
                ('user_id_was', models.PositiveIntegerField(help_text='The original user ID (for reference, user no longer exists)')),
                ('account_created_at', models.DateTimeField(help_text='When the account was originally created')),
                ('account_deleted_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the account was deleted')),
                ('deletion_method', models.CharField(choices=[('user_self_service', 'User Self-Service'), ('admin_request', 'Admin Request'), ('gdpr_request', 'GDPR Right to Erasure'), ('legal_request', 'Legal/Court Order'), ('fraud_account', 'Fraud Account Removal'), ('inactive_cleanup', 'Inactive Account Cleanup')], default='user_self_service', max_length=32)),
                ('ip_hash', models.CharField(blank=True, help_text='SHA-256 hash of IP address that initiated deletion', max_length=64)),
                ('deletion_summary', models.JSONField(default=dict, help_text="Summary of data deleted: {'journal_entries': 50, 'health_entries': 100, ...}")),
                ('reason', models.TextField(blank=True, help_text="User's stated reason for deletion (optional, sanitized of PII)")),
                ('data_exported', models.BooleanField(default=False, help_text='Whether user downloaded their data before deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Account Deletion Audit',
                'verbose_name_plural': 'Account Deletion Audits',
                'db_table': 'users_account_deletion_audit',
                'ordering': ['-account_deleted_at'],
            },
        ),
    ]
