# Generated by Django 4.2.27 on 2026-01-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_account_deletion_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_app_review_account',
            field=models.BooleanField(default=False, help_text='App review demo account - bypasses MFA and security checks.'),
        ),
    ]
