# Generated by Django 4.2.27 on 2026-01-26 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_add_is_app_review_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='default_bible_translation',
            field=models.CharField(blank=True, default='', help_text="Default Bible translation ID for Scripture lookup (e.g., '3034' for BSB)", max_length=50),
        ),
        migrations.CreateModel(
            name='AllowedInternationalEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Email address allowed to sign up from outside the USA', max_length=254, unique=True)),
                ('name', models.CharField(blank=True, help_text="Friendly name for reference (e.g., 'Mom', 'Friend John')", max_length=100)),
                ('note', models.TextField(blank=True, help_text='Optional note about why this email was whitelisted')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('used_at', models.DateTimeField(blank=True, help_text='When this email was used to sign up', null=True)),
                ('added_by', models.ForeignKey(blank=True, help_text='Admin who added this whitelist entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='international_email_whitelist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Allowed international email',
                'verbose_name_plural': 'Allowed international emails',
                'db_table': 'users_allowed_international_email',
                'ordering': ['-added_at'],
            },
        ),
    ]
