# Generated by Django 4.2.27 on 2026-01-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_add_allowed_international_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='custom_accent',
            field=models.CharField(blank=True, default='', help_text='Custom accent color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='custom_background',
            field=models.CharField(blank=True, default='', help_text='Custom background color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='custom_primary',
            field=models.CharField(blank=True, default='', help_text='Custom primary/header color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='custom_surface',
            field=models.CharField(blank=True, default='', help_text='Custom surface/card color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='custom_text',
            field=models.CharField(blank=True, default='', help_text='Custom text color (hex)', max_length=7),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='theme',
            field=models.CharField(choices=[('scholar', 'Scholar'), ('momentum', 'Momentum'), ('wanderer', 'Wanderer'), ('creature', 'Creature'), ('sanctuary', 'Sanctuary'), ('zen', 'Zen'), ('electric', 'Electric'), ('coastal', 'Coastal'), ('ember', 'Ember'), ('midnight', 'Midnight'), ('custom', 'Custom')], default='sanctuary', max_length=20),
        ),
    ]
