# Generated by Django 4.2.27 on 2026-02-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_fix_health_route_to_landing'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='assistant_journal_checkins',
            field=models.BooleanField(default=True, help_text='Proactive journal reminders in chat (requires proactive checkins)'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='assistant_medicine_checkins',
            field=models.BooleanField(default=True, help_text='Proactive medicine dose reminders in chat (requires proactive checkins)'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='assistant_mood_checkins',
            field=models.BooleanField(default=True, help_text='Proactive mood check-ins after difficult days (requires proactive checkins)'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='assistant_proactive_checkins',
            field=models.BooleanField(default=True, help_text='Enable proactive check-in messages in assistant chat'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='assistant_workout_checkins',
            field=models.BooleanField(default=True, help_text='Proactive workout reminders in chat (requires proactive checkins)'),
        ),
    ]
