# Generated by Django 4.2.27 on 2026-02-11 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_cleanup_invalid_bible_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name for the link (e.g., 'Patient Portal')", max_length=100)),
                ('url', models.URLField(help_text="Full URL including https:// (e.g., 'https://myportal.com')", max_length=500)),
                ('sort_order', models.IntegerField(default=0, help_text='Order in which links appear (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'External Link',
                'verbose_name_plural': 'External Links',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
