# Generated by Django 4.2.27 on 2026-02-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_externallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='intelligence_email_enabled',
            field=models.BooleanField(default=False, help_text='Email notifications for intelligence outputs (opt-in, off by default)'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='intelligence_inapp_enabled',
            field=models.BooleanField(default=True, help_text='In-app notifications for intelligence outputs (guidance, briefings, reports)'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='intelligence_max_per_day',
            field=models.PositiveIntegerField(default=6, help_text='Maximum intelligence notifications per day'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='intelligence_max_per_hour',
            field=models.PositiveIntegerField(default=2, help_text='Maximum intelligence notifications per hour'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='intelligence_sms_enabled',
            field=models.BooleanField(default=False, help_text='SMS notifications for intelligence outputs (opt-in, off by default)'),
        ),
    ]
