# Generated by Django 4.2.27 on 2026-02-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_delivery_notification_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='intelligence_push_enabled',
            field=models.BooleanField(default=False, help_text='Push notifications for intelligence outputs (opt-in, off by default)'),
        ),
    ]
