# Generated by Django 4.2.27 on 2026-02-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_intelligence_push_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='cos_display_name',
            field=models.CharField(blank=True, default='', help_text='Custom display name for the Chief of Staff (leave blank for default)', max_length=50),
        ),
    ]
