# Generated by Django 4.2.27 on 2026-02-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_add_cos_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallink',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('finance', 'Finance & Banking'), ('health', 'Health & Medical'), ('work', 'Work & Productivity'), ('social', 'Social & Communication'), ('other', 'Other')], default='general', help_text='Category for grouping links', max_length=20),
        ),
        migrations.AddField(
            model_name='externallink',
            name='icon',
            field=models.CharField(choices=[('link', 'Link'), ('bank', 'Bank'), ('health', 'Health'), ('briefcase', 'Briefcase'), ('globe', 'Globe'), ('star', 'Star')], default='link', help_text='Icon displayed next to the link', max_length=20),
        ),
        migrations.AddField(
            model_name='externallink',
            name='mobile_app_url',
            field=models.CharField(blank=True, default='', help_text="Optional mobile deep link URL (e.g., 'chase://', 'bofa://app'). On mobile devices, this URL is attempted first. If the app is not installed, falls back to the standard web URL above.", max_length=500),
        ),
        migrations.AddField(
            model_name='externallink',
            name='open_in_new_tab',
            field=models.BooleanField(default=True, help_text='Whether the link opens in a new browser tab'),
        ),
        migrations.AddField(
            model_name='externallink',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this link has been opened'),
        ),
    ]
