# Generated by Django 4.2.27 on 2026-02-20 12:06

from django.db import migrations, models


def enable_ai_for_existing_users(apps, schema_editor):
    """Enable ai_enabled for all existing users."""
    UserPreferences = apps.get_model("users", "UserPreferences")
    UserPreferences.objects.filter(ai_enabled=False).update(ai_enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_add_deep_link_fields_to_externallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='ai_enabled',
            field=models.BooleanField(default=True, help_text='Enable AI-powered insights and reflections'),
        ),
        migrations.RunPython(
            enable_ai_for_existing_users,
            migrations.RunPython.noop,
        ),
    ]
