# Generated by Django 4.2.27 on 2026-02-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_enable_ai_for_all_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='cos_response_style',
            field=models.CharField(choices=[('concise', 'Concise'), ('balanced', 'Balanced'), ('strategic', 'Strategic'), ('deep_dive', 'Deep Dive')], default='balanced', help_text='Controls how detailed the Chief of Staff responses are', max_length=20),
        ),
    ]
