# Generated by Django 4.2.27 on 2026-02-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_cos_response_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='cos_v2_enabled',
            field=models.BooleanField(default=False, help_text='Enable CoS v2 features (action contracts, enhanced prompting, reflections, pattern detection)'),
        ),
    ]
