# Generated by Django 4.2.27 on 2026-03-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0075_update_relationships_nav_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduledefinition',
            name='always_available',
            field=models.BooleanField(default=False, help_text='Cannot be disabled by users (system layers, Life module)'),
        ),
        migrations.AddField(
            model_name='moduledefinition',
            name='app_names',
            field=models.JSONField(blank=True, default=list, help_text='App names for active-state matching in nav (e.g., ["health", "medical"])'),
        ),
        migrations.AddField(
            model_name='moduledefinition',
            name='auto_enable_on_first_use',
            field=models.BooleanField(default=False, help_text='Auto-enable when user first interacts with this module'),
        ),
        migrations.AddField(
            model_name='moduledefinition',
            name='catalog_type',
            field=models.CharField(choices=[('module', 'User Module'), ('system', 'System'), ('internal', 'Internal')], default='module', help_text='MODULE=user-toggleable, SYSTEM=always-on infrastructure, INTERNAL=invisible', max_length=20),
        ),
        migrations.AddField(
            model_name='moduledefinition',
            name='cos_participation',
            field=models.BooleanField(default=True, help_text='Whether Beth (CoS) may reference this module in reasoning'),
        ),
        migrations.AddField(
            model_name='moduledefinition',
            name='default_enabled',
            field=models.BooleanField(default=True, help_text='Whether enabled by default for new users'),
        ),
        migrations.AddField(
            model_name='moduledefinition',
            name='display_name',
            field=models.CharField(blank=True, help_text="Full display name (e.g., 'Health & Vitals'). Falls back to name.", max_length=100),
        ),
        migrations.AddField(
            model_name='moduledefinition',
            name='layer',
            field=models.PositiveSmallIntegerField(default=3, help_text='Architecture layer: 1=ingestion, 2=knowledge, 3=domain'),
        ),
        migrations.AddField(
            model_name='moduledefinition',
            name='mapped_domain_keys',
            field=models.JSONField(blank=True, default=list, help_text='Domain registry keys this module owns (e.g., ["health", "medical"])'),
        ),
        migrations.AddField(
            model_name='moduledefinition',
            name='show_in_navigation',
            field=models.BooleanField(default=True, help_text='Whether this module appears in navigation menus'),
        ),
        migrations.AddField(
            model_name='moduledefinition',
            name='show_in_preferences',
            field=models.BooleanField(default=True, help_text='Whether this appears on the Preferences page'),
        ),
        migrations.AddField(
            model_name='moduledefinition',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('coming_soon', 'Coming Soon'), ('internal', 'Internal Only')], default='active', help_text='Module lifecycle status', max_length=20),
        ),
        migrations.AddField(
            model_name='moduledefinition',
            name='sub_features',
            field=models.JSONField(blank=True, default=dict, help_text='Available sub-features: {"weight": {"label": "Weight", "default": true}, ...}'),
        ),
        migrations.AddField(
            model_name='moduledefinition',
            name='url_namespace',
            field=models.CharField(blank=True, help_text="Primary URL namespace (e.g., 'health')", max_length=50),
        ),
        migrations.AlterField(
            model_name='moduledefinition',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Global admin kill switch — False hides from everyone'),
        ),
        migrations.AlterField(
            model_name='moduledefinition',
            name='preference_field',
            field=models.CharField(blank=True, help_text="Legacy UserPreferences field name (e.g., 'journal_enabled')", max_length=50),
        ),
    ]
