# Generated by Django 4.2.27 on 2026-03-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0078_remove_notes_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='sports_enabled',
            field=models.BooleanField(default=False, help_text='Enable Sports module for tracking followed teams and game-day signals'),
        ),
    ]
