# Generated by Django 4.2.27 on 2026-03-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0081_add_emotional_domain_to_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='assistant_assertiveness',
            field=models.CharField(choices=[('gentle', 'Gentle'), ('firm_respectful', 'Firm but Respectful'), ('direct', 'Direct')], default='firm_respectful', help_text='Controls how assertively Beth intervenes on overdue/drift items. Gentle = fewer nudges, longer cooldowns. Direct = more nudges, shorter cooldowns.', max_length=20),
        ),
    ]
