# Generated by Django 4.2.27 on 2026-04-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0082_userpreferences_assistant_assertiveness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduledefinition',
            name='cos_participation',
            field=models.BooleanField(default=True, help_text='Whether CoS may reference this module in reasoning'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='assistant_assertiveness',
            field=models.CharField(choices=[('gentle', 'Gentle'), ('firm_respectful', 'Firm but Respectful'), ('direct', 'Direct')], default='firm_respectful', help_text='Controls how assertively CoS intervenes on overdue/drift items. Gentle = fewer nudges, longer cooldowns. Direct = more nudges, shorter cooldowns.', max_length=20),
        ),
    ]
