# Generated by Django 4.2.27 on 2026-04-06 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0083_alter_moduledefinition_cos_participation_and_more'),
        ('users', '0083_rename_medicine_to_intake_feature'),
    ]

    operations = [
    ]
