# Generated by Django 4.2.27 on 2026-06-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0084_merge_0083_conflicts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='use_chatgpt_cos',
            field=models.BooleanField(default=False, help_text='Use the new ChatGPT-powered Chief of Staff for this user (default: legacy Beth). Toggle off for instant rollback.'),
        ),
    ]
