# Generated by Django 4.2.27 on 2026-07-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0086_enable_chatgpt_cos_for_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='default_relationship',
            field=models.CharField(blank=True, choices=[('chief_of_staff', 'Chief of Staff'), ('best_friend', 'Best Friend'), ('trusted_companion', 'Trusted Companion'), ('executive_coach', 'Executive Coach'), ('mentor', 'Mentor'), ('accountability_partner', 'Accountability Partner'), ('trusted_advisor', 'Trusted Advisor'), ('teacher', 'Teacher'), ('parent_figure', 'Parent Figure')], default='', help_text='Default relationship baseline with the AI (blank = Chief of Staff default). A baseline, not a cage — the model still adapts expertise to the conversation.', max_length=32),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='personality_overlay',
            field=models.CharField(blank=True, default='', help_text="Optional personality/tone overlay for the AI (e.g. 'calm_wise'); blank = none. Flavor only — never restricts what the AI can do.", max_length=50),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='preference_learning_enabled',
            field=models.BooleanField(default=True, help_text='Allow the AI to learn your communication preferences from conversation (distinct from Learning Mode).'),
        ),
    ]
