# Generated by Django 4.2.27 on 2026-07-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0087_userpreferences_default_relationship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='use_model_interface',
            field=models.BooleanField(default=False, help_text='Use the new model-interface runtime (WLJ Truth/Actions/AI Relationship/Current Context exposed to the conversational model). Takes precedence over use_chatgpt_cos. Toggle off for instant rollback.'),
        ),
    ]
