# Generated by Django 4.2.27 on 2026-07-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0088_userpreferences_use_model_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='use_model_interface_writes',
            field=models.BooleanField(default=False, help_text='Enable ACTION (write) tools on the model-interface runtime. Default False = read-only. Only meaningful when use_model_interface is True.'),
        ),
    ]
