# Generated by Django 4.2.27 on 2026-08-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0094_enable_write_together_for_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='knowledge_invitations',
            field=models.CharField(choices=[('never', 'Never'), ('occasionally', 'Occasionally'), ('naturally', 'Naturally')], default='occasionally', help_text="How often the Chief of Staff may offer to learn more about the user. Initial-release default is 'occasionally' (trust calibration). WLJ deterministically enforces rate limits, declined-topic suppression and parked topics at EVERY setting; 'never' means never.", max_length=20),
        ),
    ]
