"""
IOCD — Intelligence Observability Models.

Stores daily system-wide metrics snapshots for intelligence engine
performance monitoring.

Project: Whole Life Journey
Path: apps/core/ai_observability/models.py

Copyright:
    (c) Whole Life Journey. All rights reserved.
"""

from django.db import models


class IntelligenceMetricsSnapshot(models.Model):
    """
    Daily system-wide intelligence metrics snapshot.

    Captures point-in-time metrics across all intelligence engines:
    guidance effectiveness, prediction coverage, delivery performance,
    user engagement, quality scores, and persona effectiveness.

    One record per day. Generated by observability_engine and
    scheduled via ISE.
    """

    class Meta:
        app_label = "core"
        db_table = "core_intelligencemetricssnapshot"
        ordering = ["-snapshot_date"]
        constraints = [
            models.UniqueConstraint(
                fields=["snapshot_date"],
                name="unique_snapshot_per_day",
            ),
        ]

    # Identity
    snapshot_date = models.DateField(
        help_text="Date this snapshot covers (one per day).",
    )

    # --- Guidance Effectiveness (from GuidanceItem) ---
    guidance_total = models.IntegerField(default=0)
    guidance_acknowledged = models.IntegerField(default=0)
    guidance_dismissed = models.IntegerField(default=0)
    guidance_acted = models.IntegerField(default=0)
    guidance_expired = models.IntegerField(default=0)
    guidance_acceptance_rate = models.FloatField(
        default=0.0,
        help_text="acknowledged / total (0.0-1.0).",
    )
    guidance_action_rate = models.FloatField(
        default=0.0,
        help_text="acted / total (0.0-1.0).",
    )
    guidance_avg_response_seconds = models.FloatField(
        default=0.0,
        help_text="Average seconds from guidance creation to user action.",
    )

    # --- Prediction Confidence & Coverage (from Prediction) ---
    predictions_total = models.IntegerField(default=0)
    predictions_active = models.IntegerField(default=0)
    predictions_expired = models.IntegerField(default=0)
    predictions_avg_confidence = models.FloatField(
        default=0.0,
        help_text="Average confidence score across active predictions (0.0-1.0).",
    )

    # --- Delivery Effectiveness (from DeliveredNotification) ---
    deliveries_total = models.IntegerField(default=0)
    deliveries_sent = models.IntegerField(default=0)
    deliveries_skipped = models.IntegerField(default=0)
    deliveries_failed = models.IntegerField(default=0)
    deliveries_success_rate = models.FloatField(
        default=0.0,
        help_text="sent / total (0.0-1.0).",
    )
    deliveries_by_channel = models.JSONField(
        default=dict,
        help_text='Channel breakdown: {"in_app": 5, "email": 2, ...}.',
    )

    # --- User Engagement (from GuidanceLearningProfile) ---
    active_users_count = models.IntegerField(default=0)
    avg_responsiveness_score = models.FloatField(
        default=0.0,
        help_text="Average GLOE responsiveness across active users (0.0-1.0).",
    )

    # --- Quality (from QualityMetricAggregate) ---
    avg_usefulness_score = models.FloatField(
        default=0.0,
        help_text="Average ICQG usefulness score (0.0-1.0).",
    )
    total_suppressed = models.IntegerField(
        default=0,
        help_text="Total guidance items suppressed by quality gate.",
    )

    # --- Persona Effectiveness (from GuidanceItem grouped by coaching style) ---
    persona_effectiveness_scores = models.JSONField(
        default=dict,
        help_text=(
            'Per-style action/dismiss rates: '
            '{"supportive": {"total": 10, "acted": 5, "dismissed": 2, '
            '"action_rate": 0.5, "dismiss_rate": 0.2}, ...}.'
        ),
    )

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Metrics Snapshot {self.snapshot_date}"
