"""
IOCD — Intelligence Observability Models.

Stores daily system-wide metrics snapshots for intelligence engine
performance monitoring, plus request-level diagnostics (EngineRun,
EngineSpan, DecisionRecord) for the Diagnostics Console and
Operations Wall.

Project: Whole Life Journey
Path: apps/core/ai_observability/models.py

Copyright:
    (c) Whole Life Journey. All rights reserved.
"""

from django.db import models
from django.utils import timezone


class IntelligenceMetricsSnapshot(models.Model):
    """
    Daily system-wide intelligence metrics snapshot.

    Captures point-in-time metrics across all intelligence engines:
    guidance effectiveness, prediction coverage, delivery performance,
    user engagement, quality scores, and persona effectiveness.

    One record per day. Generated by observability_engine and
    scheduled via ISE.
    """

    class Meta:
        app_label = "core"
        db_table = "core_intelligencemetricssnapshot"
        ordering = ["-snapshot_date"]
        constraints = [
            models.UniqueConstraint(
                fields=["snapshot_date"],
                name="unique_snapshot_per_day",
            ),
        ]

    # Identity
    snapshot_date = models.DateField(
        help_text="Date this snapshot covers (one per day).",
    )

    # --- Guidance Effectiveness (from GuidanceItem) ---
    guidance_total = models.IntegerField(default=0)
    guidance_acknowledged = models.IntegerField(default=0)
    guidance_dismissed = models.IntegerField(default=0)
    guidance_acted = models.IntegerField(default=0)
    guidance_expired = models.IntegerField(default=0)
    guidance_acceptance_rate = models.FloatField(
        default=0.0,
        help_text="acknowledged / total (0.0-1.0).",
    )
    guidance_action_rate = models.FloatField(
        default=0.0,
        help_text="acted / total (0.0-1.0).",
    )
    guidance_avg_response_seconds = models.FloatField(
        default=0.0,
        help_text="Average seconds from guidance creation to user action.",
    )

    # --- Prediction Confidence & Coverage (from Prediction) ---
    predictions_total = models.IntegerField(default=0)
    predictions_active = models.IntegerField(default=0)
    predictions_expired = models.IntegerField(default=0)
    predictions_avg_confidence = models.FloatField(
        default=0.0,
        help_text="Average confidence score across active predictions (0.0-1.0).",
    )

    # --- Delivery Effectiveness (from DeliveredNotification) ---
    deliveries_total = models.IntegerField(default=0)
    deliveries_sent = models.IntegerField(default=0)
    deliveries_skipped = models.IntegerField(default=0)
    deliveries_failed = models.IntegerField(default=0)
    deliveries_success_rate = models.FloatField(
        default=0.0,
        help_text="sent / total (0.0-1.0).",
    )
    deliveries_by_channel = models.JSONField(
        default=dict,
        help_text='Channel breakdown: {"in_app": 5, "email": 2, ...}.',
    )

    # --- User Engagement (from GuidanceLearningProfile) ---
    active_users_count = models.IntegerField(default=0)
    avg_responsiveness_score = models.FloatField(
        default=0.0,
        help_text="Average GLOE responsiveness across active users (0.0-1.0).",
    )

    # --- Quality (from QualityMetricAggregate) ---
    avg_usefulness_score = models.FloatField(
        default=0.0,
        help_text="Average ICQG usefulness score (0.0-1.0).",
    )
    total_suppressed = models.IntegerField(
        default=0,
        help_text="Total guidance items suppressed by quality gate.",
    )

    # --- Persona Effectiveness (from GuidanceItem grouped by coaching style) ---
    persona_effectiveness_scores = models.JSONField(
        default=dict,
        help_text=(
            'Per-style action/dismiss rates: '
            '{"supportive": {"total": 10, "acted": 5, "dismissed": 2, '
            '"action_rate": 0.5, "dismiss_rate": 0.2}, ...}.'
        ),
    )

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Metrics Snapshot {self.snapshot_date}"


# =========================================================================
# REQUEST-LEVEL DIAGNOSTICS MODELS
# =========================================================================


class EngineRun(models.Model):
    """
    Single execution of an intelligence engine within a trace.

    One trace may contain multiple EngineRun records (e.g., a dashboard
    request triggers UAL which triggers SAE, PIE, PRIE internally).
    """

    class Meta:
        app_label = "core"
        db_table = "core_diag_engine_run"
        ordering = ["-started_at"]
        indexes = [
            models.Index(fields=["trace_id"], name="idx_engrun_trace"),
            models.Index(
                fields=["engine_name", "-started_at"], name="idx_engrun_eng_time"
            ),
            models.Index(fields=["-started_at"], name="idx_engrun_time"),
        ]

    STATUS_CHOICES = [
        ("success", "Success"),
        ("error", "Error"),
        ("skipped", "Skipped"),
    ]

    trace_id = models.CharField(
        max_length=36,
        db_index=True,
        help_text="UUID correlating all engine runs within one request/task.",
    )
    engine_name = models.CharField(
        max_length=10,
        help_text="Engine acronym: UAL, ICQG, DNE, DBE, SAE, PIE, PRIE, PGE, etc.",
    )
    phase = models.SmallIntegerField(
        help_text="Intelligence pipeline phase (1=Interp, 2=Exec, 3=Post).",
    )

    started_at = models.DateTimeField(help_text="When this engine execution began.")
    ended_at = models.DateTimeField(
        null=True, blank=True, help_text="When this engine execution completed."
    )
    duration_ms = models.IntegerField(
        default=0, help_text="Execution duration in milliseconds."
    )

    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default="success")
    error_type = models.CharField(
        max_length=200,
        blank=True,
        default="",
        help_text="Exception class name on error.",
    )
    error_message = models.TextField(
        blank=True, default="", help_text="Exception message on error."
    )

    input_fingerprint = models.CharField(
        max_length=64,
        blank=True,
        default="",
        help_text="SHA256 of input args for dedup/correlation.",
    )
    output_fingerprint = models.CharField(
        max_length=64,
        blank=True,
        default="",
        help_text="SHA256 of output for change detection.",
    )

    user_id = models.IntegerField(
        null=True,
        blank=True,
        help_text="User ID if engine was invoked for a specific user.",
    )

    metadata = models.JSONField(
        default=dict,
        blank=True,
        help_text="Engine-specific metadata (items_processed, etc.).",
    )

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return (
            f"{self.engine_name} [{self.status}] "
            f"{self.duration_ms}ms ({self.trace_id[:8]})"
        )


class EngineSpan(models.Model):
    """
    Sub-step within an engine run (e.g., 'collect_signals', 'classify_scenario').

    Optional fine-grained tracing for engines with multi-step pipelines.
    """

    class Meta:
        app_label = "core"
        db_table = "core_diag_engine_span"
        ordering = ["started_at"]
        indexes = [
            models.Index(fields=["trace_id"], name="idx_engspan_trace"),
        ]

    trace_id = models.CharField(max_length=36, db_index=True)
    engine_name = models.CharField(max_length=10)
    span_name = models.CharField(
        max_length=100,
        help_text="Sub-step name: collect_signals, classify_scenario, etc.",
    )

    started_at = models.DateTimeField()
    ended_at = models.DateTimeField(null=True, blank=True)
    duration_ms = models.IntegerField(default=0)

    status = models.CharField(max_length=10, default="success")
    metadata = models.JSONField(default=dict, blank=True)

    def __str__(self):
        return (
            f"{self.engine_name}.{self.span_name} "
            f"[{self.status}] {self.duration_ms}ms"
        )


class DecisionRecord(models.Model):
    """
    Captures WHY an engine made a specific decision.

    Used by UAL (arbitration scenario selection), ICQG (suppression decisions),
    DNE (delivery routing decisions), PGE (guidance ranking), PIE (noise budget).
    """

    class Meta:
        app_label = "core"
        db_table = "core_diag_decision_record"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["trace_id"], name="idx_decision_trace"),
            models.Index(fields=["-created_at"], name="idx_decision_time"),
        ]

    DECISION_TYPES = [
        ("arbitration", "Arbitration Scenario"),
        ("suppression", "Quality Suppression"),
        ("delivery_route", "Delivery Routing"),
        ("guidance_rank", "Guidance Ranking"),
        ("insight_filter", "Insight Filtering"),
        ("noise_budget", "Noise Budget"),
        ("prediction_store", "Prediction Storage"),
        ("validation", "Pre-Release Validation"),
        ("other", "Other"),
    ]

    trace_id = models.CharField(max_length=36, db_index=True)
    decision_type = models.CharField(max_length=20, choices=DECISION_TYPES)
    engine_name = models.CharField(
        max_length=10, help_text="Which engine made this decision."
    )

    decision = models.CharField(
        max_length=200,
        help_text="The decision: 'SCENARIO=HEALTH_CRITICAL', 'SUPPRESS=repeat_72h'.",
    )
    rationale = models.TextField(
        blank=True,
        default="",
        help_text="Human-readable explanation of why.",
    )

    inputs_summary = models.JSONField(
        default=dict,
        blank=True,
        help_text="Key inputs that influenced this decision.",
    )
    affected_items = models.JSONField(
        default=list,
        blank=True,
        help_text="Items affected (guidance IDs, notification IDs, etc.).",
    )

    user_id = models.IntegerField(null=True, blank=True)
    confidence = models.FloatField(
        null=True, blank=True, help_text="Decision confidence score if applicable."
    )

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.engine_name} {self.decision_type}: {self.decision[:50]}"


# =========================================================================
# VEGAS OPS WALL v2 — HEARTBEAT + CADENCE + SAME MODELS
# =========================================================================


class EngineExpectedCadence(models.Model):
    """
    Configurable expected run cadence per engine.

    Replaces hardcoded ENGINE_CADENCES dict with database-driven config.
    Used by heartbeat calculator and SAME to detect missed/late runs.
    """

    class Meta:
        app_label = "core"
        db_table = "core_engine_expected_cadence"
        ordering = ["engine_name"]
        constraints = [
            models.UniqueConstraint(
                fields=["engine_name"],
                name="unique_cadence_per_engine",
            ),
        ]

    engine_name = models.CharField(
        max_length=10,
        unique=True,
        help_text="Engine acronym: UAL, SAE, PIE, etc.",
    )
    expected_interval_seconds = models.IntegerField(
        help_text="Expected run interval in seconds.",
    )
    expected_jitter_seconds = models.IntegerField(
        default=60,
        help_text="Allowed late window before marking LATE.",
    )
    is_enabled = models.BooleanField(
        default=True,
        help_text="Whether heartbeat monitoring is enabled for this engine.",
    )
    notes = models.TextField(
        blank=True,
        default="",
        help_text="Admin notes about this engine's expected behavior.",
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        interval = self.expected_interval_seconds
        if interval >= 86400:
            human = f"{interval // 86400}d"
        elif interval >= 3600:
            human = f"{interval // 3600}h"
        else:
            human = f"{interval // 60}m"
        return f"{self.engine_name} (every {human})"


class EngineHeartbeat(models.Model):
    """
    Tracks expected vs actual engine runs for cadence monitoring.

    Computed every 1-2 minutes by SAME or on-demand when Ops Wall polls.
    A run is MISSED if now > next_expected_at + jitter.
    A run is LATE if now > next_expected_at and <= next_expected_at + jitter.
    """

    class Meta:
        app_label = "core"
        db_table = "core_engine_heartbeat"
        ordering = ["-observed_at"]
        indexes = [
            models.Index(
                fields=["engine_name", "-observed_at"],
                name="idx_heartbeat_eng_time",
            ),
            models.Index(
                fields=["-observed_at"],
                name="idx_heartbeat_time",
            ),
        ]

    STATUS_CHOICES = [
        ("OK", "OK"),
        ("MISSED", "Missed"),
        ("LATE", "Late"),
        ("ERROR", "Error"),
        ("NEVER_RUN", "Never Run"),
    ]

    engine_name = models.CharField(max_length=10, db_index=True)
    observed_at = models.DateTimeField(
        help_text="When this heartbeat was computed.",
    )
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        help_text="OK / MISSED / LATE / ERROR / NEVER_RUN",
    )
    last_run_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When the engine last ran (from EngineRun).",
    )
    next_expected_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When the next run is expected.",
    )
    lateness_seconds = models.IntegerField(
        default=0,
        help_text="How many seconds late (0 if on time or early).",
    )
    metadata = models.JSONField(
        default=dict,
        blank=True,
        help_text="Additional context: error counts, run counts, etc.",
    )

    def __str__(self):
        return f"{self.engine_name} [{self.status}] at {self.observed_at}"


class AdminIntervention(models.Model):
    """
    Audit record for admin actions taken via the Ops Wall.

    Every action button (rerun engine, clear cache, requeue) creates
    one of these records for traceability.
    """

    class Meta:
        app_label = "core"
        db_table = "core_admin_intervention"
        ordering = ["-created_at"]
        indexes = [
            models.Index(
                fields=["-created_at"],
                name="idx_intervention_time",
            ),
            models.Index(
                fields=["engine_name", "-created_at"],
                name="idx_intervention_eng_time",
            ),
        ]

    ACTION_TYPES = [
        ("rerun_engine", "Re-run Engine"),
        ("requeue_job", "Requeue Last Job"),
        ("clear_suppression_cache", "Clear Suppression Cache"),
        ("restart_scheduler", "Restart Scheduler Task"),
        ("acknowledge_anomaly", "Acknowledge Anomaly"),
        ("auto_rerun_engine", "Auto Re-run Engine"),
        ("auto_clear_suppression", "Auto Clear Suppression Cache"),
        ("other", "Other"),
    ]

    RESULT_CHOICES = [
        ("success", "Success"),
        ("failure", "Failure"),
        ("pending", "Pending"),
    ]

    created_at = models.DateTimeField(auto_now_add=True)
    admin_user = models.ForeignKey(
        "users.User",
        on_delete=models.SET_NULL,
        null=True,
        related_name="admin_interventions",
    )
    action_type = models.CharField(max_length=30, choices=ACTION_TYPES)
    engine_name = models.CharField(
        max_length=10,
        blank=True,
        default="",
        help_text="Target engine (if applicable).",
    )
    trace_id = models.CharField(
        max_length=36,
        blank=True,
        default="",
        help_text="Trace ID for the triggered action.",
    )
    notes = models.TextField(
        blank=True,
        default="",
        help_text="Admin notes or auto-generated context.",
    )
    result_status = models.CharField(
        max_length=10,
        choices=RESULT_CHOICES,
        default="pending",
    )
    result_detail = models.TextField(
        blank=True,
        default="",
        help_text="Result message or error detail.",
    )
    is_system_initiated = models.BooleanField(
        default=False,
        help_text="True if triggered by autonomous remediation, not a human.",
    )

    def __str__(self):
        who = "system" if self.is_system_initiated else (
            self.admin_user.email if self.admin_user else "unknown"
        )
        return f"{self.action_type} on {self.engine_name} by {who}"


class OpsAnomaly(models.Model):
    """
    Persistent anomaly record created by SAME.

    Unlike the in-memory anomaly detection in ops_anomalies.py, these
    are stored in the database with lifecycle management (active/resolved).
    """

    class Meta:
        app_label = "core"
        db_table = "core_ops_anomaly"
        ordering = ["-created_at"]
        indexes = [
            models.Index(
                fields=["is_active", "-created_at"],
                name="idx_anomaly_active",
            ),
            models.Index(
                fields=["engine_name", "-created_at"],
                name="idx_anomaly_engine",
            ),
        ]

    SEVERITY_CHOICES = [
        ("P1", "P1 — Critical"),
        ("P2", "P2 — Warning"),
        ("P3", "P3 — Info"),
    ]

    ANOMALY_TYPES = [
        ("MISSED_RUN", "Missed Run"),
        ("ERROR_SPIKE", "Error Spike"),
        ("CONFIDENCE_VOLATILITY", "Confidence Volatility"),
        ("SUPPRESSION_STORM", "Suppression Storm"),
        ("LOOPING_REMINDER", "Looping Reminder"),
        ("ENGINE_STARVATION", "Engine Starvation"),
        ("DELIVERY_RETRY_SPIKE", "Delivery Retry Spike"),
        ("COMMITMENT_RACE_CONDITION", "Commitment Race Condition"),
        ("STRUCTURAL_VIOLATION", "Structural Violation"),
        ("NUMERIC_DEVIATION", "Numeric Deviation"),
        ("VALIDATOR_CRASH", "Validator Crash"),
    ]

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    severity = models.CharField(max_length=2, choices=SEVERITY_CHOICES)
    engine_name = models.CharField(
        max_length=10,
        blank=True,
        default="",
        help_text="Affected engine (blank for cross-engine anomalies).",
    )
    anomaly_type = models.CharField(max_length=25, choices=ANOMALY_TYPES)
    summary = models.TextField(
        help_text="Human-readable anomaly summary.",
    )
    evidence = models.JSONField(
        default=dict,
        blank=True,
        help_text="References to EngineRun / DecisionRecord / Heartbeat data.",
    )
    suggested_actions = models.JSONField(
        default=list,
        blank=True,
        help_text="List of suggested admin actions.",
    )
    is_active = models.BooleanField(
        default=True,
        help_text="Whether this anomaly is still active.",
    )
    resolved_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When this anomaly was resolved/deactivated.",
    )

    # Escalation fields
    original_severity = models.CharField(
        max_length=2,
        choices=SEVERITY_CHOICES,
        blank=True,
        default="",
        help_text="Severity when first created (before any escalation).",
    )
    escalation_count = models.IntegerField(
        default=0,
        help_text="Number of times this anomaly has been escalated.",
    )
    last_escalated_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When this anomaly was last escalated.",
    )

    def __str__(self):
        status = "ACTIVE" if self.is_active else "RESOLVED"
        esc = f" esc={self.escalation_count}" if self.escalation_count else ""
        return f"[{self.severity}] {self.anomaly_type} — {self.engine_name} ({status}{esc})"


class OpsNarrativeSnapshot(models.Model):
    """
    SAME narrative snapshot — system posture + commentary.

    Generated every poll window or every 2 minutes. Reads like
    a human operator commenting on system state.
    """

    class Meta:
        app_label = "core"
        db_table = "core_ops_narrative_snapshot"
        ordering = ["-created_at"]
        indexes = [
            models.Index(
                fields=["-created_at"],
                name="idx_narrative_time",
            ),
        ]

    POSTURE_CHOICES = [
        ("OK", "OK"),
        ("DEGRADED", "Degraded"),
        ("AT_RISK", "At Risk"),
    ]

    created_at = models.DateTimeField(auto_now_add=True)
    posture = models.CharField(
        max_length=10,
        choices=POSTURE_CHOICES,
        help_text="System posture: OK / DEGRADED / AT_RISK.",
    )
    headline = models.CharField(
        max_length=200,
        blank=True,
        default="",
        help_text="One-sentence system posture headline.",
    )
    bullets_now = models.JSONField(
        default=list,
        help_text='What\'s happening right now: ["UAL running normally", ...]',
    )
    recommendations = models.JSONField(
        default=list,
        help_text='Actionable recommendations: ["Re-run DBE manually", ...]',
    )
    watching_next = models.JSONField(
        default=list,
        help_text='What SAME is watching: ["PRIE cadence drift", ...]',
    )
    supporting_metrics = models.JSONField(
        default=dict,
        blank=True,
        help_text="Key metrics that informed this narrative.",
    )


class SystemIntegritySnapshot(models.Model):
    """
    Executive-level system health metric (0–100) computed every SAME cycle.

    Score reflects overall intelligence platform health considering:
    - Percentage of engines in OK status
    - Severity-weighted anomaly penalties (P1 > P2 > P3)
    - Error spike penalty
    - Suppression rate impact
    - Confidence volatility impact

    Posture is derived from score:
    - OPTIMAL: 90–100
    - NOMINAL: 70–89
    - DEGRADED: 40–69
    - CRITICAL: 0–39
    """

    class Meta:
        app_label = "core"
        db_table = "core_system_integrity_snapshot"
        ordering = ["-created_at"]
        indexes = [
            models.Index(
                fields=["-created_at"],
                name="idx_integrity_time",
            ),
        ]

    POSTURE_CHOICES = [
        ("OPTIMAL", "Optimal"),
        ("NOMINAL", "Nominal"),
        ("DEGRADED", "Degraded"),
        ("CRITICAL", "Critical"),
    ]

    score = models.FloatField(
        help_text="System integrity score 0.0–100.0.",
    )
    posture = models.CharField(
        max_length=10,
        choices=POSTURE_CHOICES,
        help_text="Derived from score: OPTIMAL/NOMINAL/DEGRADED/CRITICAL.",
    )
    components = models.JSONField(
        default=dict,
        blank=True,
        help_text="Score breakdown by component.",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Integrity {self.score:.1f} [{self.posture}] at {self.created_at}"


class SAMEExecutionLog(models.Model):
    """
    Execution metadata for every SAME cycle run.

    Records manual and scheduled trigger events with duration, status, and
    audit fields. Used by the Ops Command Center to display last run time,
    duration, trigger source, and manual execution state.
    """

    class Meta:
        app_label = "core"
        db_table = "core_same_execution_log"
        ordering = ["-started_at"]
        indexes = [
            models.Index(fields=["-started_at"], name="idx_same_exec_time"),
        ]

    TRIGGER_CHOICES = [
        ("scheduled", "Scheduled (Celery Beat)"),
        ("manual", "Manual (Admin)"),
    ]
    STATUS_CHOICES = [
        ("queued", "Queued"),
        ("running", "Running"),
        ("completed", "Completed"),
        ("failed", "Failed"),
        ("timeout", "Timeout"),
        ("skipped", "Skipped (lock held)"),
    ]

    trigger_source = models.CharField(
        max_length=10,
        choices=TRIGGER_CHOICES,
        help_text="How this cycle was triggered.",
    )
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default="queued",
        help_text="Current execution state.",
    )
    celery_task_id = models.CharField(
        max_length=255,
        blank=True,
        default="",
        help_text="Celery AsyncResult task ID.",
    )
    triggered_by = models.ForeignKey(
        "users.User",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        help_text="Admin who triggered manually (null for scheduled).",
    )
    started_at = models.DateTimeField(
        default=timezone.now,
        help_text="When this execution was initiated.",
    )
    completed_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When execution finished.",
    )
    duration_ms = models.IntegerField(
        null=True,
        blank=True,
        help_text="Execution duration in milliseconds.",
    )
    error_detail = models.TextField(
        blank=True,
        default="",
        help_text="Error message if status is failed.",
    )

    def __str__(self):
        return f"SAME {self.trigger_source} [{self.status}] at {self.started_at}"

    @classmethod
    def get_latest(cls):
        """Get the most recent execution log entry."""
        return cls.objects.first()

    @classmethod
    def is_execution_active(cls):
        """Check if a SAME execution is currently queued or running."""
        return cls.objects.filter(
            status__in=["queued", "running"],
            started_at__gte=timezone.now() - timezone.timedelta(minutes=5),
        ).exists()


class EngineExecutionLog(models.Model):
    """
    Execution metadata for per-engine manual/auto executions.

    Separate from SAMEExecutionLog (which tracks full SAME cycle runs).
    Records manual admin triggers and SAME auto-remediation runs
    for individual engines (DBE, WIRE, DNE, PGE).

    Used by the Ops Command Center for per-engine status polling,
    execution duration display, and audit trail.
    """

    class Meta:
        app_label = "core"
        db_table = "core_engine_execution_log"
        ordering = ["-started_at"]
        indexes = [
            models.Index(fields=["-started_at"], name="idx_eng_exec_time"),
            models.Index(
                fields=["engine_name", "-started_at"],
                name="idx_eng_exec_engine_time",
            ),
        ]

    TRIGGER_CHOICES = [
        ("manual", "Manual (Admin)"),
        ("auto_remediation", "Auto-Remediation (SAME)"),
    ]
    STATUS_CHOICES = [
        ("queued", "Queued"),
        ("running", "Running"),
        ("completed", "Completed"),
        ("failed", "Failed"),
        ("timeout", "Timeout"),
        ("skipped", "Skipped (frozen/disabled)"),
    ]

    engine_name = models.CharField(
        max_length=10,
        help_text="Engine acronym: DBE, WIRE, DNE, PGE.",
    )
    trigger_source = models.CharField(
        max_length=20,
        choices=TRIGGER_CHOICES,
        help_text="How this execution was triggered.",
    )
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default="queued",
        help_text="Current execution state.",
    )
    celery_task_id = models.CharField(
        max_length=255,
        blank=True,
        default="",
        help_text="Celery AsyncResult task ID.",
    )
    triggered_by = models.ForeignKey(
        "users.User",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="engine_executions",
        help_text="Admin who triggered manually (null for auto-remediation).",
    )
    started_at = models.DateTimeField(
        default=timezone.now,
        help_text="When this execution was initiated.",
    )
    completed_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When execution finished.",
    )
    duration_ms = models.IntegerField(
        null=True,
        blank=True,
        help_text="Execution duration in milliseconds.",
    )
    result_summary = models.JSONField(
        default=dict,
        blank=True,
        help_text='Engine return value, e.g. {"generated": 5, "errors": 0}.',
    )
    error_detail = models.TextField(
        blank=True,
        default="",
        help_text="Error message if status is failed.",
    )

    def __str__(self):
        return f"{self.engine_name} {self.trigger_source} [{self.status}] at {self.started_at}"

    @classmethod
    def is_engine_active(cls, engine_name):
        """Check if an execution is already queued/running for this engine."""
        return cls.objects.filter(
            engine_name=engine_name,
            status__in=["queued", "running"],
            started_at__gte=timezone.now() - timezone.timedelta(minutes=10),
        ).exists()

    @classmethod
    def get_latest_for_engine(cls, engine_name):
        """Get the most recent execution log for a specific engine."""
        return cls.objects.filter(engine_name=engine_name).first()


class SchedulerHeartbeat(models.Model):
    """
    Tracks whether the ISE scheduler process is alive.

    Single-row table updated atomically at the end of each scheduler cycle.
    The Command Center uses this to detect scheduler drift, silent failure,
    or worker death via drift_seconds = now - last_tick_at.

    Thresholds (configurable via threshold fields):
      ALIVE:   drift <= expected_interval * alive_threshold_multiplier
      DELAYED: drift <= expected_interval * offline_threshold_multiplier
      OFFLINE: drift > expected_interval * offline_threshold_multiplier
    """

    class Meta:
        app_label = "core"
        db_table = "core_scheduler_heartbeat"

    SCHEDULER_ISE = "ISE"
    SCHEDULER_SAME = "SAME"
    SCHEDULER_CHOICES = [
        (SCHEDULER_ISE, "Intelligence Scheduler Engine"),
        (SCHEDULER_SAME, "SAME Monitoring Cycle"),
    ]

    STATUS_CHOICES = [
        ("ALIVE", "Alive"),
        ("DELAYED", "Delayed"),
        ("OFFLINE", "Offline"),
    ]

    scheduler_name = models.CharField(
        max_length=10,
        unique=True,
        choices=SCHEDULER_CHOICES,
        help_text="Which scheduler process this heartbeat tracks.",
    )
    last_tick_at = models.DateTimeField(
        db_index=True,
        help_text="When the scheduler last completed a cycle.",
    )
    expected_interval_seconds = models.IntegerField(
        help_text="Expected interval between ticks in seconds.",
    )
    cycle_result = models.JSONField(
        default=dict,
        blank=True,
        help_text="Summary of the last cycle (executed, skipped, failed).",
    )
    alive_threshold_multiplier = models.FloatField(
        default=1.5,
        help_text="Drift multiplier for ALIVE->DELAYED transition.",
    )
    offline_threshold_multiplier = models.FloatField(
        default=3.0,
        help_text="Drift multiplier for DELAYED->OFFLINE transition.",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"SchedulerHeartbeat({self.scheduler_name}) last_tick={self.last_tick_at}"

    @property
    def drift_seconds(self):
        """Current drift: seconds since last tick."""
        return int((timezone.now() - self.last_tick_at).total_seconds())

    @property
    def status(self):
        """Compute status from drift and thresholds."""
        drift = self.drift_seconds
        alive_limit = self.expected_interval_seconds * self.alive_threshold_multiplier
        offline_limit = self.expected_interval_seconds * self.offline_threshold_multiplier
        if drift <= alive_limit:
            return "ALIVE"
        elif drift <= offline_limit:
            return "DELAYED"
        return "OFFLINE"

    @classmethod
    def get_for_scheduler(cls, scheduler_name):
        """Get the heartbeat record for a scheduler, or None."""
        try:
            return cls.objects.get(scheduler_name=scheduler_name)
        except cls.DoesNotExist:
            return None

    @classmethod
    def tick(cls, scheduler_name, expected_interval_seconds, cycle_result=None):
        """
        Record a scheduler tick. Atomic update_or_create.

        Called at the end of each scheduler cycle. Must never raise —
        failures are logged but do not crash the scheduler.
        """
        import logging

        logger = logging.getLogger(__name__)
        try:
            cls.objects.update_or_create(
                scheduler_name=scheduler_name,
                defaults={
                    "last_tick_at": timezone.now(),
                    "expected_interval_seconds": expected_interval_seconds,
                    "cycle_result": cycle_result or {},
                },
            )
        except Exception as e:
            logger.warning(
                "SchedulerHeartbeat.tick failed for %s: %s",
                scheduler_name, e,
            )


class OperationalAlert(models.Model):
    """
    COAS — Operational health alert with lifecycle tracking.

    Created when a COAS subsystem score drops below a threshold.
    Uses state-change alerting: only notifies admins when severity
    changes (worsens or recovers), never for the same persisting condition.

    Lifecycle: open → acknowledged → resolved
    """

    class Meta:
        app_label = "core"
        db_table = "core_operational_alert"
        ordering = ["-created_at"]
        indexes = [
            models.Index(
                fields=["-created_at"],
                name="idx_opalert_time",
            ),
            models.Index(
                fields=["subsystem", "-created_at"],
                name="idx_opalert_subsys_time",
            ),
            models.Index(
                fields=["subsystem", "status"],
                name="idx_opalert_subsys_status",
            ),
        ]

    SUBSYSTEM_CHOICES = [
        ("scheduler", "Scheduler"),
        ("engine", "Engine"),
        ("freshness", "Intelligence Freshness"),
        ("overall", "Overall System"),
    ]
    SEVERITY_CHOICES = [
        ("warning", "Warning"),
        ("alert", "Alert"),
        ("critical", "Critical"),
    ]
    STATUS_CHOICES = [
        ("open", "Open"),
        ("acknowledged", "Acknowledged"),
        ("resolved", "Resolved"),
    ]

    subsystem = models.CharField(
        max_length=20,
        choices=SUBSYSTEM_CHOICES,
        help_text="Which COAS subsystem triggered this alert.",
    )
    severity = models.CharField(
        max_length=10,
        choices=SEVERITY_CHOICES,
        help_text="Alert severity based on health score.",
    )
    status = models.CharField(
        max_length=15,
        choices=STATUS_CHOICES,
        default="open",
        help_text="Alert lifecycle status.",
    )
    health_score = models.IntegerField(
        help_text="Health score (0-100) at time of alert.",
    )
    message = models.TextField(
        help_text="Human-readable alert message for CoS chat.",
    )
    diagnostic_prompt_text = models.TextField(
        blank=True,
        default="",
        help_text="Structured diagnostic prompt for Claude Code (critical alerts only).",
    )
    details = models.JSONField(
        default=dict,
        blank=True,
        help_text="Score breakdown and contributing factors.",
    )
    dedupe_key = models.CharField(
        max_length=100,
        blank=True,
        db_index=True,
        help_text="Deduplication key, e.g. 'scheduler_critical'.",
    )
    last_notified_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When admins were last notified about this alert.",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    resolved_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When this alert was resolved (score recovered).",
    )

    def __str__(self):
        resolved = " RESOLVED" if self.resolved_at else ""
        return (
            f"[{self.severity.upper()}] {self.subsystem} "
            f"score={self.health_score} ({self.status}){resolved}"
        )


class COASHealthSnapshot(models.Model):
    """
    COAS — Latest health scores snapshot.

    Single-row table updated every 5 minutes by the check_system_health
    scheduled job. The Ops Wall reads this stored snapshot instead of
    recomputing scores live on every poll.
    """

    class Meta:
        app_label = "core"
        db_table = "core_coas_health_snapshot"

    scheduler_score = models.IntegerField(
        default=100,
        help_text="Scheduler subsystem health score (0-100).",
    )
    engine_score = models.IntegerField(
        default=100,
        help_text="Engine subsystem health score (0-100).",
    )
    freshness_score = models.IntegerField(
        default=100,
        help_text="Intelligence freshness health score (0-100).",
    )
    overall_score = models.IntegerField(
        default=100,
        help_text="Weighted overall system health score (0-100).",
    )
    details = models.JSONField(
        default=dict,
        blank=True,
        help_text="Full breakdown of all subsystem score components.",
    )
    computed_at = models.DateTimeField(
        help_text="When these scores were last computed.",
    )


class SystemMaturitySnapshot(models.Model):
    """
    Daily system maturity snapshot for trend tracking.

    Captures the 6-score maturity hierarchy (Phase 6) once per day.
    Enables trend charts, regression detection, and self-improvement
    recommendations in the Command Center.
    """

    class Meta:
        app_label = "core"
        db_table = "core_systemmaturitysnapshot"
        ordering = ["-snapshot_date"]
        get_latest_by = "snapshot_date"
        constraints = [
            models.UniqueConstraint(
                fields=["snapshot_date"],
                name="unique_maturity_per_day",
            ),
        ]

    snapshot_date = models.DateField(
        unique=True,
        help_text="Date this snapshot covers.",
    )

    # Level 1: Infrastructure
    infrastructure_score = models.IntegerField(
        default=0,
        help_text="Infrastructure health (0-100).",
    )
    infrastructure_details = models.JSONField(
        default=dict, blank=True,
        help_text="Breakdown: scheduler, engine, freshness scores.",
    )

    # Level 2: Intelligence Quality
    intelligence_score = models.IntegerField(
        default=0,
        help_text="CoS intelligence quality (0-100).",
    )
    intelligence_details = models.JSONField(
        default=dict, blank=True,
        help_text="Breakdown: memory util, proactive delivery, domain coverage.",
    )

    # Level 3: Execution Safety
    safety_score = models.IntegerField(
        default=0,
        help_text="Execution safety (0-100).",
    )
    safety_details = models.JSONField(
        default=dict, blank=True,
        help_text="Breakdown: success rate, learning mode integrity.",
    )

    # Level 4: Domain Coverage
    domain_coverage_score = models.IntegerField(
        default=0,
        help_text="Domain coverage completeness (0-100).",
    )
    domain_coverage_details = models.JSONField(
        default=dict, blank=True,
        help_text="Per-domain breakdown.",
    )

    # Level 5: Life Impact
    life_impact_score = models.IntegerField(
        default=0,
        help_text="Life impact (0-100).",
    )
    life_impact_details = models.JSONField(
        default=dict, blank=True,
        help_text="Breakdown: goal progress, routine adherence, engagement.",
    )

    # Composite
    overall_score = models.IntegerField(
        default=0,
        help_text="Weighted composite maturity score (0-100).",
    )

    # Recommendations generated for this snapshot
    recommendations = models.JSONField(
        default=list, blank=True,
        help_text="Auto-generated improvement recommendations.",
    )

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Maturity {self.snapshot_date}: {self.overall_score}/100"


class AIActionMetric(models.Model):
    """
    Per-attempt telemetry for AI-initiated mutations (AAFR).

    One row per execute_action() call. Lightweight with indexed columns
    for time-window aggregation. Used by the AI Action Success Rate tile
    on the Operations Wall.

    Outcomes:
      success — mutation completed normally
      blocked — prevented by safety gate (learning mode, safety engine)
      failure — attempted but errored (handler crash, internal error)
    """

    OUTCOME_CHOICES = [
        ("success", "Success"),
        ("blocked", "Blocked"),
        ("failure", "Failure"),
    ]

    class Meta:
        app_label = "core"
        db_table = "core_ai_action_metric"
        ordering = ["-created_at"]
        indexes = [
            models.Index(
                fields=["-created_at"],
                name="idx_aafr_time",
            ),
            models.Index(
                fields=["outcome", "-created_at"],
                name="idx_aafr_outcome_time",
            ),
        ]

    created_at = models.DateTimeField(auto_now_add=True)
    intent_type = models.CharField(
        max_length=100,
        help_text="Intent type attempted (e.g. create_task, log_weight).",
    )
    outcome = models.CharField(
        max_length=10,
        choices=OUTCOME_CHOICES,
        help_text="Action outcome: success, blocked, or failure.",
    )
    error_category = models.CharField(
        max_length=50,
        blank=True,
        default="",
        help_text="Failure/block category (e.g. safety_blocked, internal_error).",
    )
    duration_ms = models.IntegerField(
        default=0,
        help_text="Total execution time in milliseconds.",
    )
    user_id = models.IntegerField(
        null=True,
        blank=True,
        help_text="User ID (no FK to avoid joins on hot path).",
    )

    def __str__(self):
        return f"{self.intent_type} [{self.outcome}] {self.duration_ms}ms"


class ChatLatencySnapshot(models.Model):
    """
    Per-request latency breakdown for Beth chat responses.

    Records stage-level timing for every LLM-involved response so we can
    identify bottlenecks. Created by LatencyTrace.report() at the end of
    each send_message() / send_message_stream() call.

    Stages dict example:
        {
            "ROUTER_CLASSIFICATION": 45.2,
            "COS_CONTEXT_BUILD_TOTAL": 14800.5,
            "COS_BUILDER_health": 2100.0,
            "COS_BUILDER_intelligence": 3200.0,
            ...
            "SEMANTIC_MEMORY_RETRIEVAL": 560.3,
            "LLM_REQUEST": 8700.1,
            "POST_PROCESSING": 700.0,
            "TOTAL_REQUEST_TIME": 31200.5,
        }

    Meta dict example:
        {
            "model": "gpt-4o",
            "prompt_tokens": 6120,
            "completion_tokens": 180,
            "route_name": "no_match",
        }
    """

    class Meta:
        app_label = "core"
        db_table = "core_chat_latency_snapshot"
        ordering = ["-created_at"]
        indexes = [
            models.Index(
                fields=["-created_at"],
                name="idx_chat_latency_time",
            ),
            models.Index(
                fields=["user_id", "-created_at"],
                name="idx_chat_latency_user",
            ),
        ]

    created_at = models.DateTimeField(auto_now_add=True)
    user_id = models.IntegerField(
        null=True,
        blank=True,
        help_text="User ID (no FK to avoid joins on hot path).",
    )
    path = models.CharField(
        max_length=20,
        default="non_stream",
        help_text="Pipeline path: non_stream or stream.",
    )
    total_ms = models.FloatField(
        help_text="Total end-to-end latency in milliseconds.",
    )
    stages = models.JSONField(
        default=dict,
        help_text="Stage-level latency breakdown {stage_name: duration_ms}.",
    )
    meta = models.JSONField(
        default=dict,
        blank=True,
        help_text="Request metadata: model, token counts, route info.",
    )

    def __str__(self):
        return f"user={self.user_id} {self.path} {self.total_ms:.0f}ms @ {self.created_at}"
