# Generated by Django 4.2.27 on 2026-02-22 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('LLM', 'LLM / AI'), ('TTS', 'Text-to-Speech'), ('SMS', 'SMS'), ('EMAIL', 'Email'), ('NUTRITION_API', 'Nutrition API'), ('HOSTING', 'Hosting'), ('ANALYTICS', 'Analytics'), ('FINANCE_API', 'Finance API'), ('HEALTH_API', 'Health API'), ('OTHER', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Third-Party Vendor',
                'verbose_name_plural': 'Third-Party Vendors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VendorBillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('cost_usd', models.DecimalField(decimal_places=4, max_digits=10)),
                ('cost_type', models.CharField(choices=[('FIXED', 'Fixed'), ('VARIABLE', 'Variable')], max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='owner_finance.thirdpartyvendor')),
            ],
            options={
                'verbose_name': 'Vendor Billing Record',
                'verbose_name_plural': 'Vendor Billing Records',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscriptionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('FREE', 'Free'), ('FAITH_ONLY', 'Faith Only'), ('STUDENT', 'Student'), ('ADULT', 'Adult'), ('FOUNDING', 'Founding Member'), ('OWNER', 'Owner')], db_index=True, max_length=20)),
                ('monthly_price_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('effective_start', models.DateField()),
                ('effective_end', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription Snapshot',
                'verbose_name_plural': 'User Subscription Snapshots',
                'ordering': ['-effective_start'],
            },
        ),
        migrations.CreateModel(
            name='LLMUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('feature', models.CharField(choices=[('INTENT', 'Intent Recognition'), ('MAIN_RESPONSE', 'Main AI Response'), ('TRANSCRIPTION', 'Audio Transcription'), ('SUMMARIZATION', 'Transcript Summarization'), ('NUTRITION_AI', 'AI Nutrition Estimation'), ('VISION', 'Vision / Image Analysis'), ('SCAN', 'Scan (Barcode/Medicine/Product)'), ('HEALTHCARE_LOOKUP', 'Healthcare Provider Lookup'), ('JOURNAL_REFLECTION', 'Journal Reflection'), ('DAILY_INSIGHT', 'Daily Insight'), ('WEEKLY_SUMMARY', 'Weekly Summary'), ('COS_CHAT', 'CoS Chat'), ('EXEC_BRIEFING', 'Executive Briefing'), ('OTHER', 'Other')], db_index=True, max_length=30)),
                ('engine', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('escalated', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM Usage Event',
                'verbose_name_plural': 'LLM Usage Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='owner_finan_user_id_b7dd02_idx'), models.Index(fields=['feature', 'created_at'], name='owner_finan_feature_689d96_idx'), models.Index(fields=['model_name', 'created_at'], name='owner_finan_model_n_7911ad_idx'), models.Index(fields=['created_at', 'cost_usd'], name='owner_finan_created_ffca68_idx')],
            },
        ),
        migrations.CreateModel(
            name='LLMPriceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('effective_start', models.DateField()),
                ('effective_end', models.DateField(blank=True, null=True)),
                ('input_cost_per_1m_tokens_usd', models.DecimalField(decimal_places=4, max_digits=10)),
                ('output_cost_per_1m_tokens_usd', models.DecimalField(decimal_places=4, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_book_entries', to='owner_finance.thirdpartyvendor')),
            ],
            options={
                'verbose_name': 'LLM Price Book Entry',
                'verbose_name_plural': 'LLM Price Book Entries',
                'ordering': ['-effective_start'],
                'unique_together': {('vendor', 'model_name', 'effective_start')},
            },
        ),
    ]
