# Generated by Django 4.2.27 on 2026-02-22 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owner_finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetGuardrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scope', models.CharField(choices=[('TOTAL', 'Monthly Total'), ('PER_USER', 'Per User'), ('PER_FEATURE', 'Per Feature')], max_length=20)),
                ('scope_value', models.CharField(blank=True, help_text='Feature name if scope is PER_FEATURE', max_length=50, null=True)),
                ('budget_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period', models.CharField(choices=[('DAILY', 'Daily'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=10)),
                ('alert_threshold_pct', models.IntegerField(default=80, help_text='Alert when spend reaches this % of budget')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Budget Guardrail',
                'verbose_name_plural': 'Budget Guardrails',
                'ordering': ['scope', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DailyCostRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('feature', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('total_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('total_calls', models.PositiveIntegerField(default=0)),
                ('total_input_tokens', models.PositiveIntegerField(default=0)),
                ('total_output_tokens', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_cost_rollups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Cost Rollup',
                'verbose_name_plural': 'Daily Cost Rollups',
                'ordering': ['-date'],
                'unique_together': {('date', 'user', 'feature')},
            },
        ),
    ]
