# Generated by Django 4.2.27 on 2026-08-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_finance', '0002_budgetguardrail_dailycostrollup'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmusageevent',
            name='cached_input_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='llmusageevent',
            name='latency_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='llmusageevent',
            name='source',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='llmusageevent',
            name='success',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='llmusageevent',
            name='traffic_class',
            field=models.CharField(choices=[('production', 'Production (interactive)'), ('proactive', 'Proactive'), ('certification', 'Certification / Dev'), ('background', 'Background')], db_index=True, default='production', max_length=20),
        ),
        migrations.AddIndex(
            model_name='llmusageevent',
            index=models.Index(fields=['traffic_class', 'created_at'], name='owner_finan_traffic_b9e436_idx'),
        ),
        migrations.AddIndex(
            model_name='llmusageevent',
            index=models.Index(fields=['source', 'created_at'], name='owner_finan_source_d57a7a_idx'),
        ),
    ]
