# Generated by Django 4.2.27 on 2026-08-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_finance', '0003_llmusageevent_cached_input_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmusageevent',
            name='cost_is_known',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='llmusageevent',
            name='traffic_class',
            field=models.CharField(choices=[('unattributed', 'Unattributed (classification not asserted)'), ('production', 'Production (interactive)'), ('proactive', 'Proactive'), ('certification', 'Certification / Dev'), ('background', 'Background')], db_index=True, default='unattributed', max_length=20),
        ),
    ]
