# Generated by Django 5.2.9 on 2025-12-26 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LifeDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon name or emoji for display",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Hex color code (e.g., #6366f1)",
                        max_length=7,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Life Domain",
                "verbose_name_plural": "Life Domains",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ReflectionPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt_type",
                    models.CharField(
                        choices=[
                            ("year_end", "End of Year Reflection"),
                            ("year_start", "New Year Planning"),
                            ("quarterly", "Quarterly Review"),
                            ("monthly", "Monthly Check-in"),
                            ("custom", "Custom"),
                        ],
                        default="year_end",
                        max_length=20,
                    ),
                ),
                (
                    "question",
                    models.TextField(
                        help_text="The reflection question to ask the user"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional guidance or context for this prompt",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Reflection Prompt",
                "verbose_name_plural": "Reflection Prompts",
                "ordering": ["prompt_type", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="AnnualDirection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "year",
                    models.PositiveIntegerField(
                        help_text="The year this direction applies to"
                    ),
                ),
                (
                    "word_of_year",
                    models.CharField(
                        help_text="Your guiding word for this year", max_length=50
                    ),
                ),
                (
                    "word_explanation",
                    models.TextField(
                        blank=True,
                        help_text="Why did you choose this word? What does it mean to you?",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        blank=True,
                        help_text="Optional annual theme or focus area",
                        max_length=200,
                    ),
                ),
                (
                    "theme_description",
                    models.TextField(blank=True, help_text="Expand on your theme"),
                ),
                (
                    "anchor_text",
                    models.TextField(
                        blank=True,
                        help_text="A scripture, quote, or phrase to anchor your year",
                    ),
                ),
                (
                    "anchor_source",
                    models.CharField(
                        blank=True,
                        help_text="Source of the anchor (e.g., Proverbs 3:5-6, Author name)",
                        max_length=200,
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False, help_text="Is this the current year's direction?"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Annual Direction",
                "verbose_name_plural": "Annual Directions",
                "ordering": ["-year"],
                "unique_together": {("user", "year")},
            },
        ),
        migrations.CreateModel(
            name="ChangeIntention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "intention",
                    models.CharField(
                        help_text="The change you want to embody", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="What does this look like in practice?"
                    ),
                ),
                (
                    "motivation",
                    models.TextField(
                        blank=True, help_text="Why is this change important to you?"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("integrated", "Integrated"),
                            ("paused", "Paused"),
                            ("released", "Released"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "annual_direction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link this intention to a year's direction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intentions",
                        to="purpose.annualdirection",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Change Intention",
                "verbose_name_plural": "Change Intentions",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LifeGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="What is this goal about?"),
                ),
                (
                    "why_it_matters",
                    models.TextField(
                        blank=True, help_text="Why is this goal important to you?"
                    ),
                ),
                (
                    "success_looks_like",
                    models.TextField(
                        blank=True,
                        help_text="What does success look like? How will you know you've achieved this?",
                    ),
                ),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            ("year_1", "Within 1 Year"),
                            ("year_2", "1-2 Years"),
                            ("year_3", "2-3 Years"),
                            ("ongoing", "Ongoing"),
                        ],
                        default="year_1",
                        max_length=20,
                    ),
                ),
                (
                    "target_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional target completion date",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("released", "Released"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "reflection",
                    models.TextField(
                        blank=True,
                        help_text="Reflection after completing or releasing this goal",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "annual_direction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link this goal to a year's direction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goals",
                        to="purpose.annualdirection",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which life area does this goal belong to?",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goals",
                        to="purpose.lifedomain",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Life Goal",
                "verbose_name_plural": "Life Goals",
                "ordering": ["domain", "sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlanningAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("keep", "Keep"),
                            ("stop", "Stop"),
                            ("start", "Start"),
                            ("simplify", "Simplify"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="What will you keep/stop/start/simplify?"
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Why is this important?"),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "annual_direction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_actions",
                        to="purpose.annualdirection",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Planning Action",
                "verbose_name_plural": "Planning Actions",
                "ordering": ["action_type", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Reflection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reflection_type",
                    models.CharField(
                        choices=[
                            ("year_end", "End of Year"),
                            ("year_start", "New Year"),
                            ("quarterly", "Quarterly"),
                            ("custom", "Custom"),
                        ],
                        default="year_end",
                        max_length=20,
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        help_text="The year being reflected upon"
                    ),
                ),
                (
                    "quarter",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Quarter (1-4) if quarterly reflection",
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional title for this reflection",
                        max_length=200,
                    ),
                ),
                (
                    "is_complete",
                    models.BooleanField(
                        default=False, help_text="Have you finished this reflection?"
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ai_summary",
                    models.TextField(
                        blank=True, help_text="AI-generated summary of this reflection"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reflection",
                "verbose_name_plural": "Reflections",
                "ordering": ["-year", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReflectionResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.TextField(help_text="The question that was asked"),
                ),
                (
                    "response",
                    models.TextField(
                        blank=True, help_text="Your response to this prompt"
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prompt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responses",
                        to="purpose.reflectionprompt",
                    ),
                ),
                (
                    "reflection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="purpose.reflection",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
    ]
