# Generated by Django 5.2.9 on 2026-01-02 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purpose", "0002_add_created_via_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HabitGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_via",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("ai_camera", "AI Camera Scan"),
                            ("import", "Data Import"),
                            ("api", "API"),
                        ],
                        default="manual",
                        help_text="How this entry was created",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="The goal name/title", max_length=200),
                ),
                (
                    "purpose",
                    models.TextField(
                        help_text="Why this goal matters - the deeper meaning"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="When the goal period begins"),
                ),
                ("end_date", models.DateField(help_text="When the goal period ends")),
                (
                    "habit_required",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this goal requires daily habit tracking",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Additional details about the goal"
                    ),
                ),
                (
                    "success_criteria",
                    models.TextField(
                        blank=True, help_text="What does success look like?"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "annual_direction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link this goal to a year's direction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="habit_goals",
                        to="purpose.annualdirection",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        help_text="Life area this goal belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="habit_goals",
                        to="purpose.lifedomain",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Habit Goal",
                "verbose_name_plural": "Habit Goals",
                "ordering": ["-start_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="HabitEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="The calendar date for this entry"),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=True, help_text="Whether the habit was completed"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes about this day"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habit_entries",
                        to="purpose.habitgoal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Habit Entry",
                "verbose_name_plural": "Habit Entries",
                "ordering": ["-date"],
                "unique_together": {("goal", "date")},
            },
        ),
    ]
