# Generated by Django 4.2.27 on 2026-01-20 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purpose', '0003_add_habit_goal_and_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='What needs to be accomplished?', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Additional details about this milestone')),
                ('target_date', models.DateField(blank=True, help_text='When do you want to complete this milestone?', null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='purpose.lifegoal')),
            ],
            options={
                'verbose_name': 'Goal Milestone',
                'verbose_name_plural': 'Goal Milestones',
                'ordering': [models.OrderBy(models.F('target_date'), nulls_last=True), 'sort_order', 'created_at'],
            },
        ),
    ]
