# Generated by Django 4.2.27 on 2026-02-14 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purpose', '0004_add_goal_milestones'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('encouragement', 'Encouragement'), ('warning', 'Warning'), ('optimization', 'Optimization'), ('milestone', 'Milestone Celebration'), ('pattern', 'Pattern Detected')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('suggestion_data', models.JSONField(blank=True, default=dict, help_text="Structured suggestion data (e.g., {'new_target': 35})")),
                ('is_dismissed', models.BooleanField(default=False)),
                ('is_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Goal Insight',
                'verbose_name_plural': 'Goal Insights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='habitentry',
            options={'ordering': ['-date', '-session_number'], 'verbose_name': 'Habit Entry', 'verbose_name_plural': 'Habit Entries'},
        ),
        migrations.AlterUniqueTogether(
            name='habitentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='habitentry',
            name='count_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Count value (for COUNT goals)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='habitentry',
            name='duration_minutes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Duration in minutes (for DURATION goals)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='habitentry',
            name='session_number',
            field=models.PositiveIntegerField(default=1, help_text='Session number for goals with multiple daily sessions'),
        ),
        migrations.AddField(
            model_name='habitentry',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Measured value (for TARGET goals)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='habitentry',
            name='timer_started_at',
            field=models.DateTimeField(blank=True, help_text='When the timer was started (for DURATION goals)', null=True),
        ),
        migrations.AddField(
            model_name='habitgoal',
            name='category',
            field=models.CharField(blank=True, default='', help_text="Flexible categorization (e.g., 'reading', 'fitness')", max_length=100),
        ),
        migrations.AddField(
            model_name='habitgoal',
            name='frequency_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', help_text='How often this goal should be tracked', max_length=20),
        ),
        migrations.AddField(
            model_name='habitgoal',
            name='measurement_type',
            field=models.CharField(choices=[('binary', 'Binary (Yes/No)'), ('duration', 'Duration (Minutes)'), ('count', 'Count'), ('target', 'Target Value')], default='binary', help_text='How this goal is measured', max_length=20),
        ),
        migrations.AddField(
            model_name='habitgoal',
            name='sessions_per_week',
            field=models.PositiveIntegerField(blank=True, help_text='Target number of sessions per week', null=True),
        ),
        migrations.AddField(
            model_name='habitgoal',
            name='target_unit',
            field=models.CharField(blank=True, default='', help_text="Unit label for display (e.g., 'minutes', 'pages', 'glasses')", max_length=50),
        ),
        migrations.AddField(
            model_name='habitgoal',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target per session (minutes for duration, reps for count, etc.)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='habitentry',
            name='completed',
            field=models.BooleanField(default=True, help_text='Whether the session met the goal target'),
        ),
        migrations.AlterField(
            model_name='habitentry',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes about this session'),
        ),
        migrations.AlterUniqueTogether(
            name='habitentry',
            unique_together={('goal', 'date', 'session_number')},
        ),
        migrations.AddIndex(
            model_name='habitentry',
            index=models.Index(fields=['goal', 'date'], name='idx_habitentry_goal_date'),
        ),
        migrations.AddIndex(
            model_name='habitentry',
            index=models.Index(fields=['date', 'completed'], name='idx_habitentry_date_done'),
        ),
        migrations.AddIndex(
            model_name='habitgoal',
            index=models.Index(fields=['user', 'status'], name='idx_habitgoal_user_status'),
        ),
        migrations.AddIndex(
            model_name='habitgoal',
            index=models.Index(fields=['measurement_type'], name='idx_habitgoal_mtype'),
        ),
        migrations.AddField(
            model_name='goalinsight',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='purpose.habitgoal'),
        ),
    ]
