# Generated by Django 4.2.27 on 2026-02-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purpose', '0005_add_measurement_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitgoal',
            name='measurement_type',
            field=models.CharField(choices=[('binary', 'Binary (Yes/No)'), ('duration', 'Duration'), ('count', 'Count'), ('target', 'Target Value')], default='binary', help_text='How this goal is measured', max_length=20),
        ),
    ]
