# Generated by Django 4.2.27 on 2026-03-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purpose', '0006_alter_habitgoal_measurement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifegoal',
            name='commitment_level',
            field=models.CharField(choices=[('optional', 'Optional'), ('important', 'Important'), ('non_negotiable', 'Non-Negotiable')], default='important', help_text='How committed are you to this goal?', max_length=20),
        ),
    ]
