# Generated by Django 4.2.27 on 2026-03-14 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purpose', '0007_commitment_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitgoal',
            name='commitment_level',
            field=models.CharField(choices=[('optional', 'Optional'), ('important', 'Important'), ('non_negotiable', 'Non-Negotiable')], default='important', help_text='Non-negotiable habits trigger coaching if missed. Used by compensatory reasoning engine.', max_length=20),
        ),
        migrations.CreateModel(
            name='HabitGoalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_links', to='purpose.lifegoal')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_links', to='purpose.habitgoal')),
            ],
            options={
                'verbose_name': 'Habit-Goal Link',
                'verbose_name_plural': 'Habit-Goal Links',
                'unique_together': {('habit', 'goal')},
            },
        ),
    ]
