# Generated by Django 4.2.27 on 2026-03-14 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purpose', '0008_habitgoal_commitment_level_habitgoallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalSignalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(help_text='Signal type from taxonomy (e.g., health_activity, faith_practice)', max_length=30)),
                ('weight', models.FloatField(help_text='Relative importance 0.0-1.0. Weights should sum to ~1.0 per goal.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_sources', to='purpose.lifegoal')),
            ],
            options={
                'verbose_name': 'Goal Signal Source',
                'verbose_name_plural': 'Goal Signal Sources',
                'unique_together': {('goal', 'signal_type')},
            },
        ),
    ]
