# Generated by Django 4.2.27 on 2026-03-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purpose', '0009_goalsignalsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitgoal',
            name='is_foundational',
            field=models.BooleanField(default=False, help_text='Identity-level priority. Foundational habits are always surfaced first in the dashboard and receive visual emphasis.'),
        ),
        migrations.AddField(
            model_name='lifegoal',
            name='is_foundational',
            field=models.BooleanField(default=False, help_text='Identity-level priority. Foundational goals are always surfaced first in the dashboard and receive visual emphasis.'),
        ),
    ]
