# Generated by Django 4.2.27 on 2026-03-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purpose', '0010_habitgoal_is_foundational_lifegoal_is_foundational'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitgoal',
            name='commitment_level',
            field=models.CharField(choices=[('foundational', 'Foundational'), ('important', 'Important'), ('flexible', 'Flexible')], default='important', help_text='Non-negotiable habits trigger coaching if missed. Used by compensatory reasoning engine.', max_length=20),
        ),
        migrations.AlterField(
            model_name='lifegoal',
            name='commitment_level',
            field=models.CharField(choices=[('foundational', 'Foundational'), ('important', 'Important'), ('flexible', 'Flexible')], default='important', help_text='How committed are you to this goal?', max_length=20),
        ),
    ]
