# Generated by Django 4.2.27 on 2026-03-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purpose', '0011_normalize_commitment_to_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualdirection',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='changeintention',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='habitgoal',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='lifegoal',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='planningaction',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
    ]
