# Generated by Django 4.2.27 on 2026-05-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purpose', '0012_routine_maintenance_bridge_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifegoal',
            name='is_primary_mission',
            field=models.BooleanField(default=False, help_text='User-selected featured Mission. At most one active per user. Drives the dashboard Mission card and Chief of Staff mission coaching. This is an explicit user choice, not derived state.'),
        ),
        migrations.AddConstraint(
            model_name='lifegoal',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary_mission', True)), fields=('user',), name='one_primary_mission_per_user'),
        ),
    ]
