# Generated by Django 4.2.27 on 2026-05-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purpose', '0013_lifegoal_is_primary_mission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifegoal',
            name='mission_icon',
            field=models.CharField(blank=True, default='', help_text='Optional emoji/flag shown on the dashboard Mission card (e.g. a country flag for a travel goal). Purely decorative metadata — never inferred from the title.', max_length=16),
        ),
    ]
