# Generated by Django 4.2.27 on 2026-05-31 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purpose', '0015_backfill_france_mission_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifegoal',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Optional inspirational image for this goal (e.g. a race finish line, a dream location, a wedding photo). Shown on the Goal Detail inspiration section and as a small thumbnail on the dashboard Mission card. Purely motivational — never required.', null=True, upload_to='purpose/hero/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='lifegoal',
            name='motivation_note',
            field=models.TextField(blank=True, help_text='A short personal note about why this mission matters right now — read back to you in the Goal Inspiration section.'),
        ),
        migrations.CreateModel(
            name='GoalVictoryMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="The small win to celebrate (e.g. 'First 5K without stopping').", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional detail about this win.')),
                ('icon', models.CharField(blank=True, default='', help_text='Optional emoji marker for this win.', max_length=16)),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victory_milestones', to='purpose.lifegoal')),
            ],
            options={
                'verbose_name': 'Goal Victory Milestone',
                'verbose_name_plural': 'Goal Victory Milestones',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalMotivationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Short label for the link (e.g. 'Race Website', 'Inspiration').", max_length=80)),
                ('url', models.URLField(help_text='Where this link points.', max_length=500)),
                ('icon', models.CharField(blank=True, default='', help_text='Optional emoji shown before the label (e.g. 🏁, 📸, 🧾).', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motivation_links', to='purpose.lifegoal')),
            ],
            options={
                'verbose_name': 'Goal Motivation Link',
                'verbose_name_plural': 'Goal Motivation Links',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
