# Generated by Django 4.2.27 on 2026-06-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purpose', '0016_lifegoal_hero_image_lifegoal_motivation_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalmilestone',
            name='objective_metric',
            field=models.CharField(blank=True, choices=[('weight_lb', 'Weight (lbs)')], help_text='When set, this milestone auto-completes / uncompletes bidirectionally based on the named canonical metric. When null, the milestone behaves as an achievement (manual).', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='goalmilestone',
            name='objective_operator',
            field=models.CharField(blank=True, choices=[('lte', '≤')], help_text="Comparison operator. Phase 1 supports 'lte' only.", max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='goalmilestone',
            name='objective_target_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Numeric target. Paired with objective_metric.', max_digits=8, null=True),
        ),
    ]
