# Generated by Django 4.2.27 on 2026-07-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purpose', '0019_converge_title_form_weight_milestones'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifegoal',
            name='description_plain',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='lifegoal',
            name='motivation_note_plain',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='lifegoal',
            name='reflection_plain',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='lifegoal',
            name='success_looks_like_plain',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='lifegoal',
            name='why_it_matters_plain',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
