# Generated by Django 4.2.27 on 2026-02-24 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CosReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField(help_text='ID of the source entity')),
                ('text', models.TextField(help_text='The reflection content (free-text)')),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('mixed', 'Mixed')], help_text='Auto-detected or user-indicated sentiment', max_length=20)),
                ('activity_date', models.DateField(help_text='Date the reflected-upon activity occurred')),
                ('activity_type', models.CharField(blank=True, help_text='Type of activity (workout, meeting, bible_study, etc.)', max_length=50)),
                ('prompt_text', models.TextField(blank=True, help_text='The question/prompt that elicited this reflection')),
                ('content_type', models.ForeignKey(help_text='Type of the source entity', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cos_reflections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'activity_date'], name='cos_refl_user_date'), models.Index(fields=['user', 'content_type', 'object_id'], name='cos_refl_user_entity'), models.Index(fields=['user', 'activity_type', 'activity_date'], name='cos_refl_user_type_date')],
            },
        ),
        migrations.CreateModel(
            name='CosPromptSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField(help_text='ID of the source entity')),
                ('timing', models.CharField(choices=[('pre', 'Pre-activity'), ('post', 'Post-activity')], help_text='Whether this fires before or after the activity', max_length=4)),
                ('scheduled_for', models.DateTimeField(db_index=True, help_text='When to deliver this prompt')),
                ('lead_minutes', models.PositiveIntegerField(default=15, help_text='Minutes before activity start (for pre-activity prompts)')),
                ('activity_type', models.CharField(help_text='Type of activity (workout, meeting, bible_study, etc.)', max_length=50)),
                ('prompt_text', models.TextField(help_text='The prompt message to deliver')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('responded', 'Responded'), ('expired', 'Expired'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=10)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_positive', models.BooleanField(blank=True, help_text='True = Yes/positive, False = No/negative, None = no response', null=True)),
                ('response_text', models.TextField(blank=True, help_text='Optional free-text response from the user')),
                ('content_type', models.ForeignKey(help_text='Type of the source entity', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cos_prompt_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_for'],
                'indexes': [models.Index(fields=['user', 'status', 'scheduled_for'], name='cos_prompt_user_status_sched'), models.Index(fields=['status', 'scheduled_for'], name='cos_prompt_status_sched')],
            },
        ),
        migrations.CreateModel(
            name='CosGoalSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.CharField(help_text="Goal theme/category (e.g. 'fitness_consistency', 'sleep_improvement')", max_length=100)),
                ('suggestion_text', models.TextField(help_text='The suggested goal description')),
                ('evidence_summary', models.TextField(blank=True, help_text='Evidence from patterns/reflections supporting this suggestion')),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('opted_out', 'Opted Out')], default='suggested', max_length=15)),
                ('declined_count', models.PositiveIntegerField(default=0, help_text='How many times this theme has been declined (cumulative)')),
                ('opted_out', models.BooleanField(default=False, help_text='User opted out of suggestions for this theme')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cos_goal_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'theme', 'created_at'], name='cos_goal_user_theme_date'), models.Index(fields=['user', 'opted_out'], name='cos_goal_user_optout')],
            },
        ),
        migrations.CreateModel(
            name='CosAutoShiftLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField(help_text='ID of the shifted entity')),
                ('original_start', models.DateTimeField(help_text='Original start time before shift')),
                ('original_end', models.DateTimeField(help_text='Original end time before shift')),
                ('new_start', models.DateTimeField(help_text='New start time after shift')),
                ('new_end', models.DateTimeField(help_text='New end time after shift')),
                ('reason', models.TextField(help_text='Human-readable reason for the shift')),
                ('shift_type', models.CharField(choices=[('conflict_avoidance', 'Conflict Avoidance'), ('priority_rebalance', 'Priority Rebalance'), ('time_optimization', 'Time Optimization')], help_text='Category of shift', max_length=30)),
                ('priority_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], help_text='Priority of the shifted item', max_length=10)),
                ('user_confirmed', models.BooleanField(default=False, help_text='Whether user explicitly approved this shift')),
                ('auto_shifted', models.BooleanField(default=True, help_text='True if CoS shifted automatically (low priority only)')),
                ('content_type', models.ForeignKey(help_text='Type of the shifted entity', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cos_auto_shift_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='cos_shift_user_date')],
            },
        ),
    ]
