# Generated by Django 4.2.27 on 2026-02-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cos', '0001_phase1_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='cospromptschedule',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Contextual metadata (tone, style, delivery info)'),
        ),
    ]
