# Generated by Django 4.2.27 on 2026-02-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cos', '0002_add_metadata_to_prompt_schedule'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cosautoshiftlog',
            index=models.Index(fields=['user', 'content_type', 'object_id'], name='cos_shift_user_entity'),
        ),
        migrations.AddIndex(
            model_name='cosreflection',
            index=models.Index(fields=['user', 'sentiment', 'activity_date'], name='cos_refl_user_sentiment_date'),
        ),
    ]
