# Generated by Django 4.2.27 on 2026-02-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cos', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cospromptschedule',
            name='occurrence_date',
            field=models.DateField(blank=True, help_text='For recurring events: the specific occurrence date. NULL for non-recurring.', null=True),
        ),
        migrations.AddIndex(
            model_name='cospromptschedule',
            index=models.Index(fields=['user', 'content_type', 'object_id', 'occurrence_date', 'timing'], name='cos_prompt_entity_occ_timing'),
        ),
    ]
