# Generated by Django 4.2.27 on 2026-02-25 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EAEEscalationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('up', 'Escalation'), ('down', 'De-escalation')], help_text='Whether this was an escalation or de-escalation', max_length=10)),
                ('from_level', models.IntegerField(choices=[(0, 'Nominal'), (1, 'Elevated'), (2, 'Active'), (3, 'Critical'), (4, 'Override')], help_text='Escalation level before this transition')),
                ('to_level', models.IntegerField(choices=[(0, 'Nominal'), (1, 'Elevated'), (2, 'Active'), (3, 'Critical'), (4, 'Override')], help_text='Escalation level after this transition')),
                ('trigger_reason', models.CharField(help_text='Human-readable reason for this transition', max_length=200)),
                ('drift_risk_at_event', models.FloatField(help_text='Drift risk severity at the time of this event')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eae_escalation_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EAE Escalation Event',
                'verbose_name_plural': 'EAE Escalation Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EAEDecisionLog',
            fields=[
                ('decision_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('chat', 'Chat'), ('push', 'Push Notification'), ('sms', 'SMS'), ('email', 'Email'), ('briefing', 'Daily Briefing'), ('weekly_report', 'Weekly Report'), ('command_center', 'Command Center')], help_text='Channel this decision was made for', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('escalation_level', models.IntegerField(choices=[(0, 'Nominal'), (1, 'Elevated'), (2, 'Active'), (3, 'Critical'), (4, 'Override')], help_text='Escalation level when decision was made')),
                ('drift_risk_severity', models.FloatField(help_text='Drift risk severity at decision time (0-100)')),
                ('tone_band', models.CharField(choices=[('reflective_gentle', 'Reflective Gentle'), ('reflective_firm', 'Reflective Firm'), ('direct_clear', 'Direct Clear'), ('direct_urgent', 'Direct Urgent'), ('executive_override', 'Executive Override')], help_text='Tone band assigned for this decision', max_length=30)),
                ('primary_focus_label', models.CharField(blank=True, default='', help_text='Primary focus at decision time', max_length=100)),
                ('cognitive_units_json', models.JSONField(default=list, help_text='Full CognitiveUnit list that was surfaced')),
                ('suppressed_items_json', models.JSONField(default=list, help_text='Items that were suppressed with reason codes')),
                ('total_candidates', models.IntegerField(default=0, help_text='Total signals that entered arbitration')),
                ('surfaced_count', models.IntegerField(default=0, help_text='Number of cognitive units surfaced')),
                ('suppressed_count', models.IntegerField(default=0, help_text='Number of signals suppressed')),
                ('noise_budget_used', models.IntegerField(default=0, help_text='Cognitive units consumed by this decision')),
                ('noise_budget_max', models.IntegerField(default=3, help_text='Budget cap that was applied')),
                ('override_events_json', models.JSONField(blank=True, default=list, help_text='Override events applied during this decision')),
                ('reason_codes', models.JSONField(default=list, help_text='Machine-readable decision reason codes')),
                ('source_engines', models.JSONField(default=list, help_text='Engines that contributed signals to this decision')),
                ('arbitration_duration_ms', models.IntegerField(default=0, help_text='Time taken for arbitration in milliseconds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eae_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EAE Decision Log',
                'verbose_name_plural': 'EAE Decision Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EAEState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalation_level', models.IntegerField(choices=[(0, 'Nominal'), (1, 'Elevated'), (2, 'Active'), (3, 'Critical'), (4, 'Override')], default=0, help_text='Current escalation level (0=Nominal, 4=Override)')),
                ('escalation_since', models.DateTimeField(default=django.utils.timezone.now, help_text='When the current escalation level was set')),
                ('escalation_peak_drift', models.FloatField(default=0.0, help_text='Peak drift severity since last escalation change (for de-escalation gate)')),
                ('drift_risk_severity', models.FloatField(default=0.0, help_text='Current drift risk severity (0-100)')),
                ('primary_focus_label', models.CharField(blank=True, default='', help_text="Current primary focus label (e.g., 'Medication Adherence')", max_length=100)),
                ('primary_focus_module', models.CharField(blank=True, default='', help_text="Module of the primary focus (e.g., 'health')", max_length=50)),
                ('primary_focus_set_at', models.DateTimeField(blank=True, help_text='When the current primary focus was set', null=True)),
                ('focus_changes_today', models.IntegerField(default=0, help_text='Number of focus changes today (max 2)')),
                ('focus_date', models.DateField(blank=True, help_text='Date for daily focus reset tracking', null=True)),
                ('noise_budget_used_today', models.IntegerField(default=0, help_text='Cognitive units consumed today across all channels')),
                ('noise_budget_date', models.DateField(blank=True, help_text='Date for daily budget reset tracking', null=True)),
                ('last_arbitration_at', models.DateTimeField(blank=True, help_text='Timestamp of last arbitration run', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eae_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EAE State',
                'verbose_name_plural': 'EAE States',
                'indexes': [models.Index(fields=['escalation_level'], name='eae_state_esc_level')],
            },
        ),
        migrations.CreateModel(
            name='EAEOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(help_text="Signal type being overridden. Format: 'ENGINE:type' e.g., 'PIE:medication_adherence', 'PGE:habit_streak'", max_length=100)),
                ('override_type', models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary')], default='temporary', help_text='Whether this is a permanent or temporary suppression', max_length=20)),
                ('strike_count', models.IntegerField(default=1, help_text='Current strike count (1-3). At 3, suppression activates.')),
                ('cooldown_until', models.DateTimeField(blank=True, help_text='For temporary overrides: when the cooldown expires', null=True)),
                ('temporary_count_14d', models.IntegerField(default=0, help_text='Number of temporary cooldowns in last 14 days. At 3, auto-escalates to permanent.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eae_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EAE Override',
                'verbose_name_plural': 'EAE Overrides',
                'indexes': [models.Index(fields=['user', 'override_type'], name='eae_override_user_type')],
            },
        ),
        migrations.AddConstraint(
            model_name='eaeoverride',
            constraint=models.UniqueConstraint(fields=('user', 'signal_type'), name='unique_eae_override_per_user_signal'),
        ),
        migrations.AddIndex(
            model_name='eaeescalationevent',
            index=models.Index(fields=['user', '-created_at'], name='eae_esc_user_time'),
        ),
        migrations.AddIndex(
            model_name='eaedecisionlog',
            index=models.Index(fields=['user', '-created_at'], name='eae_dec_user_time'),
        ),
        migrations.AddIndex(
            model_name='eaedecisionlog',
            index=models.Index(fields=['channel', '-created_at'], name='eae_dec_chan_time'),
        ),
    ]
