# Generated by Django 4.2.27 on 2026-03-14 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_eae', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date this signal represents')),
                ('signal_type', models.CharField(help_text='Signal type from taxonomy (e.g., health_activity, faith_practice)', max_length=30)),
                ('domain', models.CharField(help_text='LifeDomain slug (e.g., health, faith, mind)', max_length=20)),
                ('signal_class', models.CharField(choices=[('verified_action', 'Verified Action'), ('verified_measurement', 'Verified Measurement'), ('inferred_behavior', 'Inferred Behavior'), ('derived_pattern', 'Derived Pattern')], help_text="Trust classification — determines Beth's framing", max_length=25)),
                ('score', models.FloatField(help_text='Normalized score 0.0–1.0')),
                ('confidence', models.FloatField(help_text='Confidence in the score 0.0–1.0')),
                ('source_signals', models.JSONField(default=dict, help_text='Evidence: which raw data contributed to this score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signal Snapshot',
                'verbose_name_plural': 'Signal Snapshots',
                'indexes': [models.Index(fields=['user', 'date'], name='idx_signal_user_date'), models.Index(fields=['user', 'signal_type', 'date'], name='idx_signal_user_type_date')],
                'unique_together': {('user', 'date', 'signal_type')},
            },
        ),
    ]
