# Generated by Django 4.2.27 on 2026-03-17 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_eae', '0003_align_signal_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_object_id', models.PositiveIntegerField()),
                ('source_type', models.CharField(choices=[('document', 'Document'), ('capture', 'Capture'), ('email', 'Email')], help_text='Source content type for quick filtering', max_length=10)),
                ('fact_type', models.CharField(choices=[('amount', 'Amount / Payment'), ('appointment', 'Appointment'), ('person', 'Person / Provider'), ('medication', 'Medication'), ('obligation', 'Obligation (Bill / Due / Renewal)'), ('subscription', 'Subscription')], help_text='Type of fact extracted', max_length=20)),
                ('structured_value', models.JSONField(default=dict, help_text='Typed structured data per fact_type')),
                ('confidence', models.FloatField(help_text='Final confidence (LLM_confidence × source_weight)')),
                ('extracted_text', models.TextField(help_text='Source text snippet that produced this fact')),
                ('effective_date', models.DateField(blank=True, help_text='Date the fact applies to (e.g., appointment date, due date)', null=True)),
                ('domain_hint', models.CharField(blank=True, default='', help_text='Suggested domain for signal mapping', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_facts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extracted Fact',
                'verbose_name_plural': 'Extracted Facts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'fact_type', 'effective_date'], name='idx_fact_user_type_date'), models.Index(fields=['user', 'created_at'], name='idx_fact_user_created'), models.Index(fields=['source_content_type', 'source_object_id'], name='idx_fact_source')],
            },
        ),
    ]
