# Generated by Django 4.2.27 on 2026-03-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_eae', '0004_phase6a_extracted_fact'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedfact',
            name='intent_type',
            field=models.CharField(blank=True, choices=[('bill_due', 'Bill Due — financial urgency'), ('schedule_commitment', 'Schedule Commitment — time block'), ('recurring_obligation', 'Recurring Obligation — subscription/payment')], default='', help_text='Semantic intent for signal metadata enrichment', max_length=30),
        ),
    ]
