# Generated by Django 4.2.27 on 2026-03-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_eae', '0005_phase6b_intent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalsnapshot',
            name='expected',
            field=models.BooleanField(default=True, help_text='Whether this signal was expected today (from Execution Truth Engine)'),
        ),
        migrations.AddField(
            model_name='signalsnapshot',
            name='state',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('partial', 'Partial'), ('missed', 'Missed'), ('skipped', 'Skipped'), ('not_expected', 'Not Expected')], default='', help_text='Execution state: completed/partial/missed/skipped/not_expected. Empty = legacy (infer from score: score>0 → completed, else missed)', max_length=20),
        ),
    ]
