# Generated by Django 4.2.27 on 2026-04-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_eae', '0006_signalsnapshot_expected_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalsnapshot',
            name='signal_class',
            field=models.CharField(choices=[('verified_action', 'Verified Action'), ('verified_measurement', 'Verified Measurement'), ('inferred_behavior', 'Inferred Behavior'), ('derived_pattern', 'Derived Pattern')], help_text='Trust classification — determines CoS framing', max_length=25),
        ),
    ]
