# Generated by Django 5.2.10 on 2026-02-13 02:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('life', '0010_gmail_integration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestCatalog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Canonical display name (e.g., 'White Blood Cell Count')", max_length=200, unique=True)),
                ('short_name', models.CharField(blank=True, help_text="Common abbreviation (e.g., 'WBC')", max_length=50)),
                ('category', models.CharField(choices=[('hematology', 'Hematology'), ('chemistry', 'Chemistry'), ('lipids', 'Lipids'), ('thyroid', 'Thyroid'), ('diabetes', 'Diabetes / Glycemic'), ('liver', 'Liver Function'), ('kidney', 'Kidney Function'), ('electrolytes', 'Electrolytes'), ('inflammation', 'Inflammation'), ('urinalysis', 'Urinalysis'), ('cardiac', 'Cardiac Markers'), ('vitamins', 'Vitamins & Minerals'), ('hormones', 'Hormones'), ('coagulation', 'Coagulation'), ('immunology', 'Immunology'), ('uncategorized', 'Uncategorized')], db_index=True, default='uncategorized', max_length=30)),
                ('default_unit', models.CharField(blank=True, help_text="Standard unit (e.g., 'mg/dL', 'x10^3/uL')", max_length=50)),
                ('default_range_low', models.CharField(blank=True, help_text='Default reference range lower bound', max_length=50)),
                ('default_range_high', models.CharField(blank=True, help_text='Default reference range upper bound', max_length=50)),
                ('loinc_code', models.CharField(blank=True, help_text='LOINC code if known', max_length=20)),
                ('is_system_seeded', models.BooleanField(default=False, help_text='True if loaded via migration seed data')),
                ('needs_review', models.BooleanField(db_index=True, default=False, help_text='True if auto-created during import and not yet reviewed')),
                ('description', models.TextField(blank=True, help_text='Description of what this test measures')),
                ('sort_order', models.IntegerField(default=0, help_text='Display ordering within category')),
            ],
            options={
                'verbose_name': 'Lab Test',
                'verbose_name_plural': 'Lab Test Catalog',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Completed')], default='pending', max_length=20)),
                ('total_rows_found', models.PositiveIntegerField(default=0)),
                ('rows_imported', models.PositiveIntegerField(default=0)),
                ('rows_skipped_duplicate', models.PositiveIntegerField(default=0)),
                ('rows_failed', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_summary', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import Batch',
                'verbose_name_plural': 'Import Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportErrorRow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField(help_text='Line/row number in the source document')),
                ('raw_test_name', models.CharField(blank=True, help_text='Raw test name as extracted', max_length=500)),
                ('raw_value', models.CharField(blank=True, help_text='Raw value as extracted', max_length=200)),
                ('raw_unit', models.CharField(blank=True, help_text='Raw unit as extracted', max_length=100)),
                ('raw_range', models.CharField(blank=True, help_text='Raw reference range as extracted', max_length=200)),
                ('raw_line', models.TextField(blank=True, help_text='The complete raw line/text that failed')),
                ('error_type', models.CharField(help_text='Error category (parse_error, validation_error, mapping_error, etc.)', max_length=50)),
                ('error_message', models.TextField(help_text='Human-readable error description')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_rows', to='medical.importbatch')),
            ],
            options={
                'verbose_name': 'Import Error',
                'verbose_name_plural': 'Import Errors',
                'ordering': ['import_batch', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='LabPanel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('panel_type', models.CharField(choices=[('cbc', 'Complete Blood Count (CBC)'), ('cmp', 'Comprehensive Metabolic Panel (CMP)'), ('bmp', 'Basic Metabolic Panel (BMP)'), ('lipid', 'Lipid Panel'), ('thyroid', 'Thyroid Panel'), ('a1c', 'Hemoglobin A1c'), ('urinalysis', 'Urinalysis'), ('liver', 'Liver Function Panel'), ('kidney', 'Renal Function Panel'), ('iron', 'Iron Studies'), ('inflammation', 'Inflammation Markers'), ('coagulation', 'Coagulation Panel'), ('vitamin', 'Vitamin Panel'), ('hormone', 'Hormone Panel'), ('cardiac', 'Cardiac Panel'), ('custom', 'Custom / Other')], default='custom', max_length=30)),
                ('name', models.CharField(help_text='Panel name as it appeared on the report', max_length=200)),
                ('collected_at', models.DateTimeField(help_text='When the specimen was collected')),
                ('provider', models.CharField(blank=True, help_text='Lab provider / ordering physician', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lab Panel',
                'verbose_name_plural': 'Lab Panels',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='LabTestAlias',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias', models.CharField(help_text='Normalized alias (casefolded, trimmed, collapsed whitespace)', max_length=200, unique=True)),
                ('canonical_test', models.ForeignKey(help_text='The canonical test this alias maps to', on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='medical.labtestcatalog')),
            ],
            options={
                'verbose_name': 'Lab Test Alias',
                'verbose_name_plural': 'Lab Test Aliases',
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='MedicalAuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('upload', 'Document Uploaded'), ('import', 'Lab Results Imported'), ('view', 'Results Viewed'), ('delete_doc', 'Document Deleted'), ('delete_results', 'Results Deleted'), ('export', 'Data Exported'), ('merge_test', 'Catalog Test Merged')], max_length=30)),
                ('detail', models.TextField(blank=True, help_text="Non-PHI details (e.g., 'Imported 42 results from batch xyz')")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Audit Log',
                'verbose_name_plural': 'Medical Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(help_text='Original uploaded filename', max_length=500)),
                ('file_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of the uploaded file for dedup', max_length=64)),
                ('page_count', models.PositiveIntegerField(default=0, help_text='Number of pages in the PDF')),
                ('extracted_text', models.TextField(blank=True, help_text='Raw extracted text (for debugging, NOT logged in app logs)')),
                ('extraction_method', models.CharField(blank=True, choices=[('text', 'Text extraction (pdfplumber)'), ('ocr', 'OCR (pytesseract)'), ('mixed', 'Mixed (text + OCR fallback)')], help_text='How text was extracted from the PDF', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('organize_document', models.OneToOneField(blank=True, help_text="Link to the Organize Document (category='medical')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_document', to='life.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Document',
                'verbose_name_plural': 'Medical Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='importbatch',
            name='medical_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='medical.medicaldocument'),
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_test_name', models.CharField(help_text='Original test name as extracted from the report', max_length=500)),
                ('value_text', models.CharField(help_text="Result value as text (e.g., '7.2', '>60', 'Negative')", max_length=200)),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=4, help_text="Parsed numeric value (null for non-numeric results like 'Negative')", max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement', max_length=100)),
                ('range_low', models.DecimalField(blank=True, decimal_places=4, help_text='Reference range lower bound (numeric)', max_digits=12, null=True)),
                ('range_high', models.DecimalField(blank=True, decimal_places=4, help_text='Reference range upper bound (numeric)', max_digits=12, null=True)),
                ('range_text', models.CharField(blank=True, help_text="Reference range as text (e.g., '<200', '70-99', 'Negative')", max_length=200)),
                ('abnormal_flag', models.CharField(blank=True, choices=[('', 'Normal / Within Range'), ('L', 'Low'), ('H', 'High'), ('LL', 'Critical Low'), ('HH', 'Critical High'), ('A', 'Abnormal (unspecified)')], db_index=True, default='', help_text='Abnormal flag from the report', max_length=5)),
                ('collected_at', models.DateTimeField(db_index=True, help_text='When the specimen was collected')),
                ('reported_at', models.DateTimeField(blank=True, help_text='When the result was reported', null=True)),
                ('provider', models.CharField(blank=True, help_text='Lab provider or ordering physician', max_length=200)),
                ('result_status', models.CharField(choices=[('final', 'Final'), ('preliminary', 'Preliminary'), ('pending_review', 'Pending Review')], default='final', max_length=20)),
                ('fingerprint', models.CharField(blank=True, db_index=True, help_text='SHA-256 fingerprint for duplicate detection', max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('import_batch', models.ForeignKey(blank=True, help_text='Import batch that created this result', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='medical.importbatch')),
                ('panel', models.ForeignKey(blank=True, help_text='Panel this result belongs to (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='medical.labpanel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('canonical_test', models.ForeignKey(blank=True, help_text='Mapped canonical test (null if unmapped)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='medical.labtestcatalog')),
                ('medical_document', models.ForeignKey(blank=True, help_text='Source medical document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='medical.medicaldocument')),
            ],
            options={
                'verbose_name': 'Lab Result',
                'verbose_name_plural': 'Lab Results',
                'ordering': ['-collected_at', 'raw_test_name'],
                'indexes': [models.Index(fields=['user', 'collected_at'], name='medical_lab_user_id_275a54_idx'), models.Index(fields=['user', 'canonical_test', 'collected_at'], name='medical_lab_user_id_6e2580_idx'), models.Index(fields=['user', 'abnormal_flag', 'collected_at'], name='medical_lab_user_id_393236_idx')],
            },
        ),
    ]
