# Generated by Django 4.2.27 on 2026-02-13 13:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_seed_lab_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabEducationContent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_plain_name', models.CharField(help_text="Plain-language name (e.g., 'White Blood Cell Count')", max_length=200)),
                ('what_it_measures', models.TextField(help_text='What this test measures, in plain language')),
                ('what_it_reflects', models.TextField(help_text='What this test reflects about body function')),
                ('low_general_associations', models.TextField(blank=True, help_text='What low values are commonly associated with (general causes)')),
                ('high_general_associations', models.TextField(blank=True, help_text='What high values are commonly associated with (general causes)')),
                ('common_influencing_factors', models.TextField(help_text='Common non-prescriptive factors that can influence results')),
                ('typical_panel', models.CharField(blank=True, help_text="Typical panel grouping (e.g., 'CBC', 'CMP', 'Lipid Panel')", max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When this content was last reviewed for accuracy', null=True)),
                ('is_system_generated', models.BooleanField(default=False, help_text='True if generated via seed migration')),
                ('lab_test', models.OneToOneField(help_text='The canonical lab test this education content describes', on_delete=django.db.models.deletion.CASCADE, related_name='education', to='medical.labtestcatalog')),
            ],
            options={
                'verbose_name': 'Lab Education Content',
                'verbose_name_plural': 'Lab Education Content',
                'ordering': ['lab_test__category', 'lab_test__sort_order'],
            },
        ),
    ]
