# Generated by Django 4.2.27 on 2026-02-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_seed_lab_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='date_estimated',
            field=models.BooleanField(default=False, help_text='True if collected_at was estimated (not extracted from document)'),
        ),
    ]
