# Generated by Django 4.2.27 on 2026-08-25 00:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_routine_maintenance_bridge_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationProductLabel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spl_setid', models.CharField(db_index=True, help_text='DailyMed SPL setid — the stable identifier of a label document', max_length=64, unique=True)),
                ('rxcui', models.CharField(blank=True, db_index=True, default='', help_text='RxNorm concept the product resolved to (identity authority)', max_length=32)),
                ('rxcui_tty', models.CharField(blank=True, default='', help_text='RxNorm term type of `rxcui` — M1 supports BN (brand name) only', max_length=16)),
                ('brand_name', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('generic_name', models.CharField(blank=True, default='', max_length=300)),
                ('labeler', models.CharField(blank=True, default='', help_text="The SPL's labeler of record (manufacturer or repackager)", max_length=300)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('dosage_and_administration', models.TextField(blank=True, default='', help_text='VERBATIM approved labelling text. Never summarized by WLJ.')),
                ('source', models.CharField(default='dailymed', help_text="Authoritative source of record for the label's identity/version", max_length=32)),
                ('source_url', models.URLField(blank=True, default='')),
                ('content_source', models.CharField(blank=True, default='', help_text='Where the parsed section TEXT was retrieved from, for this same setid', max_length=32)),
                ('spl_version', models.CharField(blank=True, default='', max_length=16)),
                ('effective_time', models.CharField(blank=True, default='', help_text="The label's own effective date, as the source reports it", max_length=32)),
                ('published_date', models.CharField(blank=True, default='', max_length=64)),
                ('retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('resolution_state', models.CharField(choices=[('resolved', 'Resolved'), ('ambiguous', 'Ambiguous — failed closed'), ('unsupported', 'Unsupported in this milestone'), ('no_label', 'No product label exists')], db_index=True, default='resolved', max_length=20)),
                ('resolution_note', models.CharField(blank=True, default='', help_text='Why resolution ended in this state — auditable, never a guess', max_length=500)),
            ],
            options={
                'verbose_name': 'Medication Product Label',
                'verbose_name_plural': 'Medication Product Labels',
                'indexes': [models.Index(fields=['brand_name'], name='medical_med_brand_n_122a46_idx'), models.Index(fields=['rxcui'], name='medical_med_rxcui_29357c_idx')],
            },
        ),
    ]
