# Generated by Django 4.2.27 on 2026-03-02 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meals', '0003_phase12_pantry_photo_intelligence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(help_text='First name', max_length=100)),
                ('last_name', models.CharField(blank=True, help_text='Last name (optional)', max_length=100)),
                ('display_name', models.CharField(blank=True, help_text='How the user refers to this person (auto-generated if blank)', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Email address (optional)', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Phone number (optional)', max_length=20, null=True)),
                ('relationship_type', models.CharField(choices=[('spouse', 'Spouse'), ('family', 'Family'), ('friend', 'Friend'), ('coworker', 'Coworker'), ('church', 'Church'), ('mentor', 'Mentor'), ('other', 'Other')], default='other', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Private notes about this person')),
                ('last_interaction_date', models.DateField(blank=True, help_text='Date of most recent interaction (auto-updated)', null=True)),
                ('interaction_count', models.PositiveIntegerField(default=0, help_text='Total interaction count (auto-updated)')),
                ('household', models.ForeignKey(blank=True, help_text='Link to household for shared visibility', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_contacts', to='meals.household')),
                ('owner', models.ForeignKey(help_text='User who owns this contact', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='relationships.person')),
            ],
            options={
                'verbose_name': 'Mention',
                'verbose_name_plural': 'Mentions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RelationshipInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context_type_label', models.CharField(choices=[('journal', 'Journal'), ('task', 'Task'), ('meal', 'Meal'), ('prayer', 'Prayer'), ('event', 'Event'), ('chat', 'Chat'), ('manual', 'Manual'), ('other', 'Other')], help_text='Human-readable context category', max_length=20)),
                ('interaction_date', models.DateField(help_text='Date of the interaction')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='relationships.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relationship Interaction',
                'verbose_name_plural': 'Relationship Interactions',
                'ordering': ['-interaction_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'person', 'interaction_date'], name='relationshi_user_id_c52c2b_idx'), models.Index(fields=['user', 'context_type_label'], name='relationshi_user_id_cbcbac_idx'), models.Index(fields=['content_type', 'object_id'], name='relationshi_content_52a876_idx'), models.Index(fields=['interaction_date'], name='relationshi_interac_93781e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['owner', 'status'], name='relationshi_owner_i_71d4a8_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['owner', 'first_name', 'last_name'], name='relationshi_owner_i_344d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['owner', 'last_interaction_date'], name='relationshi_owner_i_f2fcb0_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['household'], name='relationshi_househo_ca035d_idx'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('owner', 'first_name', 'last_name'), name='unique_active_person_per_owner'),
        ),
        migrations.AddIndex(
            model_name='mention',
            index=models.Index(fields=['person'], name='relationshi_person__2aed54_idx'),
        ),
        migrations.AddIndex(
            model_name='mention',
            index=models.Index(fields=['content_type', 'object_id'], name='relationshi_content_bab0fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='mention',
            constraint=models.UniqueConstraint(fields=('person', 'content_type', 'object_id'), name='unique_mention_per_object'),
        ),
    ]
