# Generated by Django 4.2.27 on 2026-03-02 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text="Group name (e.g., 'Small Group', 'Family')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of this group')),
                ('members', models.ManyToManyField(blank=True, help_text='People in this group', related_name='groups', to='relationships.person')),
                ('owner', models.ForeignKey(help_text='User who owns this group', on_delete=django.db.models.deletion.CASCADE, related_name='person_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person Group',
                'verbose_name_plural': 'Person Groups',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['owner', 'status'], name='relationshi_owner_i_e40174_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='persongroup',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('owner', 'name'), name='unique_active_group_per_owner'),
        ),
    ]
