# Generated by Django 4.2.27 on 2026-07-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0003_alter_person_relationship_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='notes_plain',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='persongroup',
            name='description_plain',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
