# Generated by Django 4.2.27 on 2026-07-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0005_backfill_relationships_richtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='relationship_type',
            field=models.CharField(choices=[('spouse', 'Spouse'), ('wife', 'Wife'), ('husband', 'Husband'), ('partner', 'Partner'), ('father', 'Father'), ('mother', 'Mother'), ('son', 'Son'), ('daughter', 'Daughter'), ('brother', 'Brother'), ('sister', 'Sister'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('grandson', 'Grandson'), ('granddaughter', 'Granddaughter'), ('aunt', 'Aunt'), ('uncle', 'Uncle'), ('cousin', 'Cousin'), ('niece', 'Niece'), ('nephew', 'Nephew'), ('family', 'Family (other)'), ('friend', 'Friend'), ('coworker', 'Coworker'), ('church', 'Church'), ('mentor', 'Mentor'), ('neighbor', 'Neighbor'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
