# Generated by Django 5.2.9 on 2025-12-31 01:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique ID for this notification",
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("medicine", "Medicine Dose"),
                            ("medicine_refill", "Medicine Refill"),
                            ("task", "Task"),
                            ("event", "Event"),
                            ("prayer", "Prayer"),
                            ("fasting", "Fasting"),
                            ("verification", "Verification"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        help_text="Type of reminder",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.CharField(help_text="SMS message content", max_length=320),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        db_index=True, help_text="When to send this SMS (UTC)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Delivery status",
                        max_length=20,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When the SMS was sent", null=True
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, help_text="When delivery was confirmed", null=True
                    ),
                ),
                (
                    "failed_at",
                    models.DateTimeField(
                        blank=True, help_text="When sending failed", null=True
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True, help_text="Error message if failed", max_length=500
                    ),
                ),
                (
                    "twilio_sid",
                    models.CharField(
                        blank=True,
                        help_text="Twilio message SID for tracking",
                        max_length=50,
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="ID of source object", null=True
                    ),
                ),
                (
                    "response_code",
                    models.CharField(
                        blank=True,
                        help_text="User's reply code (D, R, N, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "response_received_at",
                    models.DateTimeField(
                        blank=True, help_text="When user replied", null=True
                    ),
                ),
                (
                    "response_processed",
                    models.BooleanField(
                        default=False, help_text="Has the response been processed?"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of source object",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User this notification is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Notification",
                "verbose_name_plural": "SMS Notifications",
                "ordering": ["-scheduled_for"],
            },
        ),
        migrations.CreateModel(
            name="SMSResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "response_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique ID for this response",
                        unique=True,
                    ),
                ),
                (
                    "from_number",
                    models.CharField(
                        help_text="Phone number that sent the reply", max_length=20
                    ),
                ),
                ("body", models.TextField(help_text="Raw message body")),
                (
                    "twilio_sms_sid",
                    models.CharField(
                        blank=True,
                        help_text="Twilio SID of the incoming message",
                        max_length=50,
                    ),
                ),
                (
                    "parsed_action",
                    models.CharField(
                        choices=[
                            ("done", "Done/Taken"),
                            ("remind", "Remind Later"),
                            ("skip", "Skip"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        help_text="Parsed action from the reply",
                        max_length=20,
                    ),
                ),
                (
                    "remind_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minutes to wait before reminding again (if action=remind)",
                        null=True,
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the reply was received",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the action was executed", null=True
                    ),
                ),
                (
                    "action_taken",
                    models.CharField(
                        blank=True,
                        help_text="Description of what action was taken",
                        max_length=200,
                    ),
                ),
                (
                    "processing_error",
                    models.TextField(
                        blank=True, help_text="Error message if processing failed"
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        help_text="The notification this is a reply to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="sms.smsnotification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who sent this reply",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Response",
                "verbose_name_plural": "SMS Responses",
                "ordering": ["-received_at"],
            },
        ),
        migrations.AddIndex(
            model_name="smsnotification",
            index=models.Index(
                fields=["user", "-scheduled_for"], name="sms_smsnoti_user_id_c208a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smsnotification",
            index=models.Index(
                fields=["status", "scheduled_for"], name="sms_smsnoti_status_773b7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smsnotification",
            index=models.Index(
                fields=["category", "-scheduled_for"],
                name="sms_smsnoti_categor_824950_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="smsnotification",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="sms_smsnoti_content_317737_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="smsresponse",
            index=models.Index(
                fields=["from_number", "-received_at"],
                name="sms_smsresp_from_nu_cafb4c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="smsresponse",
            index=models.Index(
                fields=["user", "-received_at"], name="sms_smsresp_user_id_aee985_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smsresponse",
            index=models.Index(
                fields=["parsed_action", "-received_at"],
                name="sms_smsresp_parsed__78c5c9_idx",
            ),
        ),
    ]
