# Generated by Django 5.2.9 on 2025-12-31 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0001_sms_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smsnotification",
            name="category",
            field=models.CharField(
                choices=[
                    ("medicine", "Medicine Dose"),
                    ("medicine_refill", "Medicine Refill"),
                    ("task", "Task"),
                    ("event", "Event"),
                    ("prayer", "Prayer"),
                    ("fasting", "Fasting"),
                    ("significant_event", "Significant Event"),
                    ("verification", "Verification"),
                    ("system", "System"),
                ],
                db_index=True,
                help_text="Type of reminder",
                max_length=20,
            ),
        ),
    ]
