# Generated by Django 4.2.27 on 2026-01-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_alter_smsnotification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsnotification',
            name='category',
            field=models.CharField(choices=[('medicine', 'Medicine Dose'), ('medicine_refill', 'Medicine Refill'), ('task', 'Task'), ('event', 'Event'), ('prayer', 'Prayer'), ('fasting', 'Fasting'), ('significant_event', 'Significant Event'), ('milestone', 'Goal Milestone'), ('verification', 'Verification'), ('system', 'System')], db_index=True, help_text='Type of reminder', max_length=20),
        ),
    ]
