-- Team records update
UPDATE sports_team SET wins=12, losses=13 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='ARI' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb'));
UPDATE sports_team SET wins=18, losses=7 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='ATL' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb'));
UPDATE sports_team SET wins=15, losses=10 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='BAL' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb'));
UPDATE sports_team SET wins=14, losses=11 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='BOS' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb'));
UPDATE sports_team SET wins=12, losses=13 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='CHC' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb'));
UPDATE sports_team SET wins=10, losses=15 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='CIN' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb'));
UPDATE sports_team SET wins=14, losses=11 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='CLE' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb'));
UPDATE sports_team SET wins=7, losses=18 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='COL' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb'));
UPDATE sports_team SET wins=9, losses=16 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='DET' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb'));
UPDATE sports_team SET wins=17, losses=8 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='HOU' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb'));
UPDATE sports_team SET wins=8, losses=17 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='KC' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb'));
UPDATE sports_team SET wins=11, losses=14 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='LAA' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb'));
UPDATE sports_team SET wins=16, losses=9 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='LAD' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb'));
UPDATE sports_team SET wins=15, losses=10 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='MIL' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb'));
UPDATE sports_team SET wins=13, losses=12 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='MIN' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb'));
UPDATE sports_team SET wins=10, losses=15 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='NYM' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb'));
UPDATE sports_team SET wins=15, losses=10 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='NYY' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb'));
UPDATE sports_team SET wins=6, losses=19 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='OAK' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb'));
UPDATE sports_team SET wins=16, losses=9 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='PHI' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb'));
UPDATE sports_team SET wins=14, losses=11 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='SD' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb'));
UPDATE sports_team SET wins=12, losses=13 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='SEA' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb'));
UPDATE sports_team SET wins=13, losses=12 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='SFG' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb'));
UPDATE sports_team SET wins=11, losses=14 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='STL' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb'));
UPDATE sports_team SET wins=13, losses=12 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='TB' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb'));
UPDATE sports_team SET wins=11, losses=14 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='TEX' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb'));
UPDATE sports_team SET wins=12, losses=13 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='TOR' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb'));
UPDATE sports_team SET wins=9, losses=16 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='WSH' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb'));
UPDATE sports_team SET wins=5, losses=2 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='ATL' AND league_id=(SELECT id FROM sports_league WHERE slug='mls'));
UPDATE sports_team SET wins=2, losses=5 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='CHI' AND league_id=(SELECT id FROM sports_league WHERE slug='mls'));
UPDATE sports_team SET wins=3, losses=4 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='CIN' AND league_id=(SELECT id FROM sports_league WHERE slug='mls'));
UPDATE sports_team SET wins=4, losses=3 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='CLB' AND league_id=(SELECT id FROM sports_league WHERE slug='mls'));
UPDATE sports_team SET wins=2, losses=5 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='CLT' AND league_id=(SELECT id FROM sports_league WHERE slug='mls'));
UPDATE sports_team SET wins=3, losses=4 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='COL' AND league_id=(SELECT id FROM sports_league WHERE slug='mls'));
UPDATE sports_team SET wins=3, losses=4 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='DAL' AND league_id=(SELECT id FROM sports_league WHERE slug='mls'));
UPDATE sports_team SET wins=1, losses=6 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='DC' AND league_id=(SELECT id FROM sports_league WHERE slug='mls'));
UPDATE sports_team SET wins=2, losses=5 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='HOU' AND league_id=(SELECT id FROM sports_league WHERE slug='mls'));
UPDATE sports_team SET wins=6, losses=1 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='LAFC' AND league_id=(SELECT id FROM sports_league WHERE slug='mls'));
UPDATE sports_team SET wins=4, losses=3 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='LAG' AND league_id=(SELECT id FROM sports_league WHERE slug='mls'));
UPDATE sports_team SET wins=4, losses=3 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='MIA' AND league_id=(SELECT id FROM sports_league WHERE slug='mls'));
UPDATE sports_team SET wins=4, losses=3 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='MIN' AND league_id=(SELECT id FROM sports_league WHERE slug='mls'));
UPDATE sports_team SET wins=4, losses=3 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='NYC' AND league_id=(SELECT id FROM sports_league WHERE slug='mls'));
UPDATE sports_team SET wins=3, losses=4 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='NYRB' AND league_id=(SELECT id FROM sports_league WHERE slug='mls'));
UPDATE sports_team SET wins=5, losses=2 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='PHI' AND league_id=(SELECT id FROM sports_league WHERE slug='mls'));
UPDATE sports_team SET wins=3, losses=4 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='POR' AND league_id=(SELECT id FROM sports_league WHERE slug='mls'));
UPDATE sports_team SET wins=4, losses=3 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='RSL' AND league_id=(SELECT id FROM sports_league WHERE slug='mls'));
UPDATE sports_team SET wins=5, losses=2 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='SEA' AND league_id=(SELECT id FROM sports_league WHERE slug='mls'));
UPDATE sports_team SET wins=38, losses=38 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='ATL' AND league_id=(SELECT id FROM sports_league WHERE slug='nba'));
UPDATE sports_team SET wins=58, losses=18 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='BOS' AND league_id=(SELECT id FROM sports_league WHERE slug='nba'));
UPDATE sports_team SET wins=30, losses=46 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='CHI' AND league_id=(SELECT id FROM sports_league WHERE slug='nba'));
UPDATE sports_team SET wins=52, losses=24 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='CLE' AND league_id=(SELECT id FROM sports_league WHERE slug='nba'));
UPDATE sports_team SET wins=46, losses=30 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='DAL' AND league_id=(SELECT id FROM sports_league WHERE slug='nba'));
UPDATE sports_team SET wins=50, losses=26 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='DEN' AND league_id=(SELECT id FROM sports_league WHERE slug='nba'));
UPDATE sports_team SET wins=38, losses=38 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='GSW' AND league_id=(SELECT id FROM sports_league WHERE slug='nba'));
UPDATE sports_team SET wins=42, losses=34 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='IND' AND league_id=(SELECT id FROM sports_league WHERE slug='nba'));
UPDATE sports_team SET wins=36, losses=40 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='LAC' AND league_id=(SELECT id FROM sports_league WHERE slug='nba'));
UPDATE sports_team SET wins=44, losses=32 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='LAL' AND league_id=(SELECT id FROM sports_league WHERE slug='nba'));
UPDATE sports_team SET wins=40, losses=36 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='MIA' AND league_id=(SELECT id FROM sports_league WHERE slug='nba'));
UPDATE sports_team SET wins=48, losses=28 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='MIL' AND league_id=(SELECT id FROM sports_league WHERE slug='nba'));
UPDATE sports_team SET wins=44, losses=32 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='MIN' AND league_id=(SELECT id FROM sports_league WHERE slug='nba'));
UPDATE sports_team SET wins=46, losses=30 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='NYK' AND league_id=(SELECT id FROM sports_league WHERE slug='nba'));
UPDATE sports_team SET wins=55, losses=21 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='OKC' AND league_id=(SELECT id FROM sports_league WHERE slug='nba'));
UPDATE sports_team SET wins=39, losses=37 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='PHI' AND league_id=(SELECT id FROM sports_league WHERE slug='nba'));
UPDATE sports_team SET wins=40, losses=36 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='PHX' AND league_id=(SELECT id FROM sports_league WHERE slug='nba'));
UPDATE sports_team SET wins=44, losses=24 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='BOS' AND league_id=(SELECT id FROM sports_league WHERE slug='nhl'));
UPDATE sports_team SET wins=44, losses=24 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='CAR' AND league_id=(SELECT id FROM sports_league WHERE slug='nhl'));
UPDATE sports_team SET wins=34, losses=34 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='CGY' AND league_id=(SELECT id FROM sports_league WHERE slug='nhl'));
UPDATE sports_team SET wins=45, losses=23 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='COL' AND league_id=(SELECT id FROM sports_league WHERE slug='nhl'));
UPDATE sports_team SET wins=46, losses=22 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='DAL' AND league_id=(SELECT id FROM sports_league WHERE slug='nhl'));
UPDATE sports_team SET wins=43, losses=25 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='EDM' AND league_id=(SELECT id FROM sports_league WHERE slug='nhl'));
UPDATE sports_team SET wins=48, losses=20 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='FLA' AND league_id=(SELECT id FROM sports_league WHERE slug='nhl'));
UPDATE sports_team SET wins=37, losses=31 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='MIN' AND league_id=(SELECT id FROM sports_league WHERE slug='nhl'));
UPDATE sports_team SET wins=36, losses=32 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='NSH' AND league_id=(SELECT id FROM sports_league WHERE slug='nhl'));
UPDATE sports_team SET wins=42, losses=26 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='NYR' AND league_id=(SELECT id FROM sports_league WHERE slug='nhl'));
UPDATE sports_team SET wins=38, losses=30 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='TBL' AND league_id=(SELECT id FROM sports_league WHERE slug='nhl'));
UPDATE sports_team SET wins=38, losses=30 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='VAN' AND league_id=(SELECT id FROM sports_league WHERE slug='nhl'));
UPDATE sports_team SET wins=40, losses=28 WHERE id=(SELECT id FROM sports_team WHERE abbreviation='WPG' AND league_id=(SELECT id FROM sports_league WHERE slug='nhl'));

-- Probable pitchers update
UPDATE sports_gameevent SET home_probable_pitcher='Tarik Skubal', away_probable_pitcher='Tanner Bibee' WHERE home_team_id=(SELECT id FROM sports_team WHERE abbreviation='DET' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb')) AND away_team_id=(SELECT id FROM sports_team WHERE abbreviation='CLE' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb')) AND start_time='2026-03-24 22:40:00+0000';
UPDATE sports_gameevent SET home_probable_pitcher='Gerrit Cole', away_probable_pitcher='Brayan Bello' WHERE home_team_id=(SELECT id FROM sports_team WHERE abbreviation='NYY' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb')) AND away_team_id=(SELECT id FROM sports_team WHERE abbreviation='BOS' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb')) AND start_time='2026-03-24 23:05:00+0000';
UPDATE sports_gameevent SET home_probable_pitcher='Max Fried', away_probable_pitcher='Yoshinobu Yamamoto' WHERE home_team_id=(SELECT id FROM sports_team WHERE abbreviation='ATL' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb')) AND away_team_id=(SELECT id FROM sports_team WHERE abbreviation='LAD' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb')) AND start_time='2026-03-24 23:10:00+0000';
UPDATE sports_gameevent SET home_probable_pitcher='Freddy Peralta', away_probable_pitcher='Hunter Greene' WHERE home_team_id=(SELECT id FROM sports_team WHERE abbreviation='MIL' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb')) AND away_team_id=(SELECT id FROM sports_team WHERE abbreviation='CIN' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb')) AND start_time='2026-03-24 23:40:00+0000';
UPDATE sports_gameevent SET home_probable_pitcher='Framber Valdez', away_probable_pitcher='Nathan Eovaldi' WHERE home_team_id=(SELECT id FROM sports_team WHERE abbreviation='HOU' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb')) AND away_team_id=(SELECT id FROM sports_team WHERE abbreviation='TEX' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb')) AND start_time='2026-03-25 00:10:00+0000';
UPDATE sports_gameevent SET home_probable_pitcher='Justin Steele', away_probable_pitcher='Sonny Gray' WHERE home_team_id=(SELECT id FROM sports_team WHERE abbreviation='CHC' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb')) AND away_team_id=(SELECT id FROM sports_team WHERE abbreviation='STL' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb')) AND start_time='2026-03-25 00:15:00+0000';
UPDATE sports_gameevent SET home_probable_pitcher='Logan Webb', away_probable_pitcher='Yu Darvish' WHERE home_team_id=(SELECT id FROM sports_team WHERE abbreviation='SFG' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb')) AND away_team_id=(SELECT id FROM sports_team WHERE abbreviation='SD' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb')) AND start_time='2026-03-25 01:45:00+0000';
UPDATE sports_gameevent SET home_probable_pitcher='Luis Castillo', away_probable_pitcher='Tyler Anderson' WHERE home_team_id=(SELECT id FROM sports_team WHERE abbreviation='SEA' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb')) AND away_team_id=(SELECT id FROM sports_team WHERE abbreviation='LAA' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb')) AND start_time='2026-03-25 02:10:00+0000';
UPDATE sports_gameevent SET home_probable_pitcher='Gerrit Cole', away_probable_pitcher='Brayan Bello' WHERE home_team_id=(SELECT id FROM sports_team WHERE abbreviation='NYY' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb')) AND away_team_id=(SELECT id FROM sports_team WHERE abbreviation='BOS' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb')) AND start_time='2026-03-26 17:05:00+0000';
UPDATE sports_gameevent SET home_probable_pitcher='Max Fried', away_probable_pitcher='Yoshinobu Yamamoto' WHERE home_team_id=(SELECT id FROM sports_team WHERE abbreviation='ATL' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb')) AND away_team_id=(SELECT id FROM sports_team WHERE abbreviation='LAD' AND league_id=(SELECT id FROM sports_league WHERE slug='mlb')) AND start_time='2026-03-26 17:20:00+0000';
