-- =====================================================================
-- WLJ Sports Domain — Complete Data Seed
-- Run in DBeaver against the Railway PostgreSQL database
-- Safe to re-run (uses ON CONFLICT DO NOTHING)
-- =====================================================================

-- ─────────────────────────────────────────────────────────────────────
-- SPORTS (5)
-- ─────────────────────────────────────────────────────────────────────
INSERT INTO sports_sport (name, slug) VALUES
  ('Football', 'football'),
  ('Basketball', 'basketball'),
  ('Baseball', 'baseball'),
  ('Hockey', 'hockey'),
  ('Soccer', 'soccer')
ON CONFLICT (slug) DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────
-- LEAGUES (8)
-- ─────────────────────────────────────────────────────────────────────
INSERT INTO sports_league (sport_id, name, slug, abbreviation, is_college) VALUES
  ((SELECT id FROM sports_sport WHERE slug='football'),  'National Football League',       'nfl',    'NFL',    false),
  ((SELECT id FROM sports_sport WHERE slug='basketball'), 'National Basketball Association', 'nba',    'NBA',    false),
  ((SELECT id FROM sports_sport WHERE slug='baseball'),   'Major League Baseball',           'mlb',    'MLB',    false),
  ((SELECT id FROM sports_sport WHERE slug='hockey'),     'National Hockey League',          'nhl',    'NHL',    false),
  ((SELECT id FROM sports_sport WHERE slug='soccer'),     'Major League Soccer',             'mls',    'MLS',    false),
  ((SELECT id FROM sports_sport WHERE slug='football'),  'NCAA Football (FBS)',             'ncaaf',  'NCAAF',  true),
  ((SELECT id FROM sports_sport WHERE slug='basketball'), 'NCAA Men''s Basketball',          'ncaab',  'NCAAB',  true),
  ((SELECT id FROM sports_sport WHERE slug='baseball'),   'NCAA Baseball',                   'ncaabb', 'NCAABB', true)
ON CONFLICT (slug) DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────
-- NFL — 32 Teams
-- ─────────────────────────────────────────────────────────────────────
INSERT INTO sports_team (league_id, location, name, abbreviation, external_id, logo_url) VALUES
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'Buffalo',       'Bills',       'BUF', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'Miami',         'Dolphins',    'MIA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'New England',   'Patriots',    'NE',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'New York',      'Jets',        'NYJ', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'Baltimore',     'Ravens',      'BAL', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'Cincinnati',    'Bengals',     'CIN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'Cleveland',     'Browns',      'CLE', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'Pittsburgh',    'Steelers',    'PIT', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'Houston',       'Texans',      'HOU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'Indianapolis',  'Colts',       'IND', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'Jacksonville',  'Jaguars',     'JAX', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'Tennessee',     'Titans',      'TEN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'Denver',        'Broncos',     'DEN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'Kansas City',   'Chiefs',      'KC',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'Las Vegas',     'Raiders',     'LV',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'Los Angeles',   'Chargers',    'LAC', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'Dallas',        'Cowboys',     'DAL', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'New York',      'Giants',      'NYG', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'Philadelphia',  'Eagles',      'PHI', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'Washington',    'Commanders',  'WAS', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'Chicago',       'Bears',       'CHI', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'Detroit',       'Lions',       'DET', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'Green Bay',     'Packers',     'GB',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'Minnesota',     'Vikings',     'MIN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'Atlanta',       'Falcons',     'ATL', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'Carolina',      'Panthers',    'CAR', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'New Orleans',   'Saints',      'NO',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'Tampa Bay',     'Buccaneers',  'TB',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'Arizona',       'Cardinals',   'ARI', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'Los Angeles',   'Rams',        'LAR', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'San Francisco', '49ers',       'SF',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='nfl'), 'Seattle',       'Seahawks',    'SEA', '', '')
ON CONFLICT (league_id, abbreviation) DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────
-- NBA — 30 Teams
-- ─────────────────────────────────────────────────────────────────────
INSERT INTO sports_team (league_id, location, name, abbreviation, external_id, logo_url) VALUES
  ((SELECT id FROM sports_league WHERE slug='nba'), 'Boston',         'Celtics',        'BOS', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nba'), 'Brooklyn',       'Nets',           'BKN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nba'), 'New York',       'Knicks',         'NYK', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nba'), 'Philadelphia',   '76ers',          'PHI', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nba'), 'Toronto',        'Raptors',        'TOR', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nba'), 'Chicago',        'Bulls',          'CHI', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nba'), 'Cleveland',      'Cavaliers',      'CLE', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nba'), 'Detroit',        'Pistons',        'DET', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nba'), 'Indiana',        'Pacers',         'IND', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nba'), 'Milwaukee',      'Bucks',          'MIL', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nba'), 'Atlanta',        'Hawks',          'ATL', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nba'), 'Charlotte',      'Hornets',        'CHA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nba'), 'Miami',          'Heat',           'MIA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nba'), 'Orlando',        'Magic',          'ORL', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nba'), 'Washington',     'Wizards',        'WAS', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nba'), 'Denver',         'Nuggets',        'DEN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nba'), 'Minnesota',      'Timberwolves',   'MIN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nba'), 'Oklahoma City',  'Thunder',        'OKC', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nba'), 'Portland',       'Trail Blazers',  'POR', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nba'), 'Utah',           'Jazz',           'UTA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nba'), 'Golden State',   'Warriors',       'GSW', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nba'), 'Los Angeles',    'Clippers',       'LAC', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nba'), 'Los Angeles',    'Lakers',         'LAL', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nba'), 'Phoenix',        'Suns',           'PHX', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nba'), 'Sacramento',     'Kings',          'SAC', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nba'), 'Dallas',         'Mavericks',      'DAL', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nba'), 'Houston',        'Rockets',        'HOU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nba'), 'Memphis',        'Grizzlies',      'MEM', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nba'), 'New Orleans',    'Pelicans',       'NOP', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nba'), 'San Antonio',    'Spurs',          'SAS', '', '')
ON CONFLICT (league_id, abbreviation) DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────
-- MLB — 30 Teams
-- ─────────────────────────────────────────────────────────────────────
INSERT INTO sports_team (league_id, location, name, abbreviation, external_id, logo_url) VALUES
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'Baltimore',      'Orioles',       'BAL', '', ''),
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'Boston',         'Red Sox',       'BOS', '', ''),
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'New York',       'Yankees',       'NYY', '', ''),
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'Tampa Bay',      'Rays',          'TB',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'Toronto',        'Blue Jays',     'TOR', '', ''),
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'Chicago',        'White Sox',     'CWS', '', ''),
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'Cleveland',      'Guardians',     'CLE', '', ''),
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'Detroit',        'Tigers',        'DET', '', ''),
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'Kansas City',    'Royals',        'KC',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'Minnesota',      'Twins',         'MIN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'Houston',        'Astros',        'HOU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'Los Angeles',    'Angels',        'LAA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'Oakland',        'Athletics',     'OAK', '', ''),
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'Seattle',        'Mariners',      'SEA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'Texas',          'Rangers',       'TEX', '', ''),
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'Atlanta',        'Braves',        'ATL', '', ''),
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'Miami',          'Marlins',       'MIA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'New York',       'Mets',          'NYM', '', ''),
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'Philadelphia',   'Phillies',      'PHI', '', ''),
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'Washington',     'Nationals',     'WSH', '', ''),
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'Chicago',        'Cubs',          'CHC', '', ''),
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'Cincinnati',     'Reds',          'CIN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'Milwaukee',      'Brewers',       'MIL', '', ''),
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'Pittsburgh',     'Pirates',       'PIT', '', ''),
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'St. Louis',      'Cardinals',     'STL', '', ''),
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'Arizona',        'Diamondbacks',  'ARI', '', ''),
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'Colorado',       'Rockies',       'COL', '', ''),
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'Los Angeles',    'Dodgers',       'LAD', '', ''),
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'San Diego',      'Padres',        'SD',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='mlb'), 'San Francisco',  'Giants',        'SFG', '', '')
ON CONFLICT (league_id, abbreviation) DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────
-- NHL — 32 Teams
-- ─────────────────────────────────────────────────────────────────────
INSERT INTO sports_team (league_id, location, name, abbreviation, external_id, logo_url) VALUES
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'Boston',        'Bruins',         'BOS', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'Buffalo',       'Sabres',         'BUF', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'Detroit',       'Red Wings',      'DET', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'Florida',       'Panthers',       'FLA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'Montreal',      'Canadiens',      'MTL', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'Ottawa',        'Senators',       'OTT', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'Tampa Bay',     'Lightning',      'TBL', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'Toronto',       'Maple Leafs',    'TOR', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'Carolina',      'Hurricanes',     'CAR', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'Columbus',      'Blue Jackets',   'CBJ', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'New Jersey',    'Devils',         'NJD', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'New York',      'Islanders',      'NYI', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'New York',      'Rangers',        'NYR', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'Philadelphia',  'Flyers',         'PHI', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'Pittsburgh',    'Penguins',       'PIT', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'Washington',    'Capitals',       'WSH', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'Arizona',       'Coyotes',        'ARI', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'Chicago',       'Blackhawks',     'CHI', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'Colorado',      'Avalanche',      'COL', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'Dallas',        'Stars',          'DAL', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'Minnesota',     'Wild',           'MIN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'Nashville',     'Predators',      'NSH', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'St. Louis',     'Blues',          'STL', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'Winnipeg',      'Jets',           'WPG', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'Anaheim',       'Ducks',          'ANA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'Calgary',       'Flames',         'CGY', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'Edmonton',      'Oilers',         'EDM', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'Los Angeles',   'Kings',          'LAK', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'San Jose',      'Sharks',         'SJS', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'Seattle',       'Kraken',         'SEA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'Vancouver',     'Canucks',        'VAN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='nhl'), 'Vegas',         'Golden Knights', 'VGK', '', '')
ON CONFLICT (league_id, abbreviation) DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────
-- MLS — 29 Teams
-- ─────────────────────────────────────────────────────────────────────
INSERT INTO sports_team (league_id, location, name, abbreviation, external_id, logo_url) VALUES
  ((SELECT id FROM sports_league WHERE slug='mls'), 'Atlanta',           'United FC',      'ATL',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='mls'), 'Charlotte',         'FC',             'CLT',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='mls'), 'Chicago',           'Fire FC',        'CHI',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='mls'), 'Cincinnati',        'FC Cincinnati',  'CIN',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='mls'), 'Columbus',          'Crew',           'CLB',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='mls'), 'D.C.',              'United',         'DC',   '', ''),
  ((SELECT id FROM sports_league WHERE slug='mls'), 'Inter Miami',       'CF',             'MIA',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='mls'), 'CF Montreal',       'CF Montreal',    'MTL',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='mls'), 'Nashville',         'SC',             'NSH',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='mls'), 'New England',       'Revolution',     'NE',   '', ''),
  ((SELECT id FROM sports_league WHERE slug='mls'), 'New York',          'Red Bulls',      'NYRB', '', ''),
  ((SELECT id FROM sports_league WHERE slug='mls'), 'New York City',     'FC',             'NYC',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='mls'), 'Orlando City',      'SC',             'ORL',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='mls'), 'Philadelphia',      'Union',          'PHI',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='mls'), 'Toronto',           'FC',             'TOR',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='mls'), 'Austin',            'FC',             'ATX',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='mls'), 'Colorado',          'Rapids',         'COL',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='mls'), 'FC Dallas',         'FC Dallas',      'DAL',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='mls'), 'Houston',           'Dynamo FC',      'HOU',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='mls'), 'LA',                'Galaxy',         'LAG',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='mls'), 'Los Angeles',       'FC',             'LAFC', '', ''),
  ((SELECT id FROM sports_league WHERE slug='mls'), 'Minnesota',         'United FC',      'MIN',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='mls'), 'Portland',          'Timbers',        'POR',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='mls'), 'Real Salt Lake',    'Real Salt Lake', 'RSL',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='mls'), 'San Jose',          'Earthquakes',    'SJ',   '', ''),
  ((SELECT id FROM sports_league WHERE slug='mls'), 'Seattle',           'Sounders FC',    'SEA',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='mls'), 'Sporting Kansas City', 'Sporting KC', 'SKC',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='mls'), 'St. Louis',         'City SC',        'STL',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='mls'), 'Vancouver',         'Whitecaps FC',   'VAN',  '', '')
ON CONFLICT (league_id, abbreviation) DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────
-- NCAA Football (FBS) — 40 Teams
-- ─────────────────────────────────────────────────────────────────────
INSERT INTO sports_team (league_id, location, name, abbreviation, external_id, logo_url) VALUES
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Alabama',          'Crimson Tide',    'ALA',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Arkansas',         'Razorbacks',      'ARK',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Auburn',           'Tigers',          'AUB',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Florida',          'Gators',          'FLA',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Georgia',          'Bulldogs',        'UGA',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Kentucky',         'Wildcats',        'UK',   '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'LSU',              'Tigers',          'LSU',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Mississippi State', 'Bulldogs',       'MSU',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Missouri',         'Tigers',          'MIZ',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Ole Miss',         'Rebels',          'MISS', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'South Carolina',   'Gamecocks',       'SC',   '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Tennessee',        'Volunteers',      'TENN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Texas A&M',        'Aggies',          'TAMU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Vanderbilt',       'Commodores',      'VAN',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Oklahoma',         'Sooners',         'OU',   '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Texas',            'Longhorns',       'TEX',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Illinois',         'Fighting Illini', 'ILL',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Indiana',          'Hoosiers',        'IU',   '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Iowa',             'Hawkeyes',        'IOWA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Maryland',         'Terrapins',       'MD',   '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Michigan',         'Wolverines',      'MICH', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Michigan State',   'Spartans',        'MSU2', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Minnesota',        'Golden Gophers',  'MINN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Nebraska',         'Cornhuskers',     'NEB',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Northwestern',     'Wildcats',        'NW',   '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Ohio State',       'Buckeyes',        'OSU',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Oregon',           'Ducks',           'ORE',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Penn State',       'Nittany Lions',   'PSU',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Purdue',           'Boilermakers',    'PUR',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Rutgers',          'Scarlet Knights', 'RUT',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'USC',              'Trojans',         'USC',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'UCLA',             'Bruins',          'UCLA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Washington',       'Huskies',         'UW',   '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Wisconsin',        'Badgers',         'WIS',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Clemson',          'Tigers',          'CLEM', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Florida State',    'Seminoles',       'FSU',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Miami',            'Hurricanes',      'UM',   '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'Notre Dame',       'Fighting Irish',  'ND',   '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'North Carolina',   'Tar Heels',       'UNC',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaaf'), 'NC State',         'Wolfpack',        'NCST', '', '')
ON CONFLICT (league_id, abbreviation) DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────
-- NCAA Men's Basketball — 40 Teams
-- ─────────────────────────────────────────────────────────────────────
INSERT INTO sports_team (league_id, location, name, abbreviation, external_id, logo_url) VALUES
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Kansas',            'Jayhawks',       'KU',   '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Duke',             'Blue Devils',     'DUKE', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'North Carolina',   'Tar Heels',       'UNC',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Kentucky',         'Wildcats',        'UK',   '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Connecticut',      'Huskies',         'UCON', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Purdue',           'Boilermakers',    'PUR',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Gonzaga',          'Bulldogs',        'GONZ', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Villanova',        'Wildcats',        'NOVA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Houston',          'Cougars',         'HOU',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Alabama',          'Crimson Tide',    'ALA',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Tennessee',        'Volunteers',      'TENN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Arizona',          'Wildcats',        'ARIZ', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Baylor',           'Bears',           'BAY',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Creighton',        'Bluejays',        'CRE',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Indiana',          'Hoosiers',        'IU',   '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Iowa State',       'Cyclones',        'ISU',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Marquette',        'Golden Eagles',   'MARQ', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Michigan State',   'Spartans',        'MSU',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Auburn',           'Tigers',          'AUB',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Texas',            'Longhorns',       'TEX',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'UCLA',             'Bruins',          'UCLA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Virginia',         'Cavaliers',       'UVA',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Michigan',         'Wolverines',      'MICH', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Florida Atlantic', 'Owls',            'FAU',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'San Diego State',  'Aztecs',          'SDSU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Arkansas',         'Razorbacks',      'ARK',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Illinois',         'Fighting Illini', 'ILL',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Miami',            'Hurricanes',      'UM',   '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Ohio State',       'Buckeyes',        'OSU',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Oregon',           'Ducks',           'ORE',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Syracuse',         'Orange',          'SYR',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Louisville',       'Cardinals',       'LOU',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Xavier',           'Musketeers',      'XAV',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Wisconsin',        'Badgers',         'WIS',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Florida',          'Gators',          'FLA',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Memphis',          'Tigers',          'MEM',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'St. John''s',      'Red Storm',       'STJ',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Georgetown',       'Hoyas',           'GTWN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'Texas Tech',       'Red Raiders',     'TTU',  '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaab'), 'NC State',         'Wolfpack',        'NCST', '', '')
ON CONFLICT (league_id, abbreviation) DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────
-- NCAA Baseball D1 — 293 Teams (all conferences, SEC first)
-- ─────────────────────────────────────────────────────────────────────
-- Clear old incomplete set first
DELETE FROM sports_team WHERE league_id = (SELECT id FROM sports_league WHERE slug='ncaabb');

INSERT INTO sports_team (league_id, location, name, abbreviation, external_id, logo_url) VALUES
  -- SEC (16)
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Alabama', 'Crimson Tide', 'ALA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Arkansas', 'Razorbacks', 'ARK', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Auburn', 'Tigers', 'AUB', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Florida', 'Gators', 'FLA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Georgia', 'Bulldogs', 'UGA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Kentucky', 'Wildcats', 'UK', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'LSU', 'Tigers', 'LSU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Mississippi State', 'Bulldogs', 'MSU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Missouri', 'Tigers', 'MIZ', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Oklahoma', 'Sooners', 'OU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Ole Miss', 'Rebels', 'MISS', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'South Carolina', 'Gamecocks', 'SC', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Tennessee', 'Volunteers', 'TENN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Texas', 'Longhorns', 'TEX', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Texas A&M', 'Aggies', 'TAMU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Vanderbilt', 'Commodores', 'VAN', '', ''),
  -- ACC (18)
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Boston College', 'Eagles', 'BC', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'California', 'Golden Bears', 'CAL', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Clemson', 'Tigers', 'CLEM', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Duke', 'Blue Devils', 'DUKE', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Florida State', 'Seminoles', 'FSU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Georgia Tech', 'Yellow Jackets', 'GT', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Louisville', 'Cardinals', 'LOU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Miami', 'Hurricanes', 'UM', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'North Carolina', 'Tar Heels', 'UNC', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'NC State', 'Wolfpack', 'NCST', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Notre Dame', 'Fighting Irish', 'ND', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Pittsburgh', 'Panthers', 'PITT', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'SMU', 'Mustangs', 'SMU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Stanford', 'Cardinal', 'STAN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Syracuse', 'Orange', 'SYR', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Virginia', 'Cavaliers', 'UVA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Virginia Tech', 'Hokies', 'VT', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Wake Forest', 'Demon Deacons', 'WF', '', ''),
  -- Big 12 (16)
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Arizona', 'Wildcats', 'ARIZ', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Arizona State', 'Sun Devils', 'ASU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Baylor', 'Bears', 'BAY', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'BYU', 'Cougars', 'BYU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Cincinnati', 'Bearcats', 'CIN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Colorado', 'Buffaloes', 'COL', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Houston', 'Cougars', 'HOU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Iowa State', 'Cyclones', 'ISU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Kansas', 'Jayhawks', 'KU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Kansas State', 'Wildcats', 'KST', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Oklahoma State', 'Cowboys', 'OKST', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'TCU', 'Horned Frogs', 'TCU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Texas Tech', 'Red Raiders', 'TTU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'UCF', 'Knights', 'UCF', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Utah', 'Utes', 'UTAH', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'West Virginia', 'Mountaineers', 'WVU', '', ''),
  -- Big Ten (15)
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Illinois', 'Fighting Illini', 'ILL', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Indiana', 'Hoosiers', 'IU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Iowa', 'Hawkeyes', 'IOWA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Maryland', 'Terrapins', 'MD', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Michigan', 'Wolverines', 'MICH', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Michigan State', 'Spartans', 'MSU2', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Minnesota', 'Golden Gophers', 'MINN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Nebraska', 'Cornhuskers', 'NEB', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Northwestern', 'Wildcats', 'NW', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Ohio State', 'Buckeyes', 'OSU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Oregon State', 'Beavers', 'ORST', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Penn State', 'Nittany Lions', 'PSU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Purdue', 'Boilermakers', 'PUR', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Rutgers', 'Scarlet Knights', 'RUT', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Washington', 'Huskies', 'UW', '', ''),
  -- American Athletic (14)
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Charlotte', '49ers', 'CLT', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'East Carolina', 'Pirates', 'ECU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Florida Atlantic', 'Owls', 'FAU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Memphis', 'Tigers', 'MEM', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Navy', 'Midshipmen', 'NAVY', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'North Texas', 'Mean Green', 'UNT', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Rice', 'Owls', 'RICE', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'South Florida', 'Bulls', 'USF', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Temple', 'Owls', 'TEM', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Tulane', 'Green Wave', 'TUL', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Tulsa', 'Golden Hurricane', 'TLSA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'UAB', 'Blazers', 'UAB', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'UTSA', 'Roadrunners', 'UTSA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Wichita State', 'Shockers', 'WICH', '', ''),
  -- Sun Belt (14)
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Appalachian State', 'Mountaineers', 'APP', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Arkansas State', 'Red Wolves', 'ARST', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Coastal Carolina', 'Chanticleers', 'CCU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Georgia Southern', 'Eagles', 'GASO', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Georgia State', 'Panthers', 'GAST', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'James Madison', 'Dukes', 'JMU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Louisiana', 'Ragin'' Cajuns', 'ULL', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Louisiana-Monroe', 'Warhawks', 'ULM', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Marshall', 'Thundering Herd', 'MRSH', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Old Dominion', 'Monarchs', 'ODU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'South Alabama', 'Jaguars', 'USA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Southern Miss', 'Golden Eagles', 'USM', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Texas State', 'Bobcats', 'TXST', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Troy', 'Trojans', 'TROY', '', ''),
  -- Conference USA (10)
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'FIU', 'Panthers', 'FIU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Jacksonville State', 'Gamecocks', 'JVST', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Kennesaw State', 'Owls', 'KSU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Liberty', 'Flames', 'LIB', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Louisiana Tech', 'Bulldogs', 'LT', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Middle Tennessee', 'Blue Raiders', 'MTSU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'New Mexico State', 'Aggies', 'NMSU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Sam Houston', 'Bearkats', 'SHSU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'UT Arlington', 'Mavericks', 'UTA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Western Kentucky', 'Hilltoppers', 'WKU', '', ''),
  -- Mountain West (8)
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Air Force', 'Falcons', 'AF', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Fresno State', 'Bulldogs', 'FRES', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Nevada', 'Wolf Pack', 'NEV', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'New Mexico', 'Lobos', 'UNM', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'San Diego State', 'Aztecs', 'SDSU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'San Jose State', 'Spartans', 'SJSU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'UNLV', 'Rebels', 'UNLV', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Utah State', 'Aggies', 'USU', '', ''),
  -- West Coast (8)
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Gonzaga', 'Bulldogs', 'GONZ', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Loyola Marymount', 'Lions', 'LMU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Pacific', 'Tigers', 'PAC', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Pepperdine', 'Waves', 'PEP', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Portland', 'Pilots', 'PORT', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Saint Mary''s', 'Gaels', 'SMC', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'San Francisco', 'Dons', 'SFU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Santa Clara', 'Broncos', 'SCU', '', ''),
  -- Missouri Valley (10)
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Dallas Baptist', 'Patriots', 'DBU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Evansville', 'Purple Aces', 'EVAN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Illinois State', 'Redbirds', 'ILST', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Indiana State', 'Sycamores', 'INST', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Missouri State', 'Bears', 'MOST', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Southern Illinois', 'Salukis', 'SIU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'UIC', 'Flames', 'UIC', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Valparaiso', 'Beacons', 'VAL', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Belmont', 'Bruins', 'BELM', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Murray State', 'Racers', 'MURR', '', ''),
  -- Colonial Athletic (11)
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'College of Charleston', 'Cougars', 'COFC', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Delaware', 'Blue Hens', 'DEL', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Drexel', 'Dragons', 'DREX', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Elon', 'Phoenix', 'ELON', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Hofstra', 'Pride', 'HOF', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Monmouth', 'Hawks', 'MON', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Northeastern', 'Huskies', 'NEU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Stony Brook', 'Seawolves', 'SBU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Towson', 'Tigers', 'TOW', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'UNC Wilmington', 'Seahawks', 'UNCW', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'William & Mary', 'Tribe', 'WM', '', ''),
  -- Big East (9)
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Butler', 'Bulldogs', 'BUT', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Connecticut', 'Huskies', 'UCON', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Creighton', 'Bluejays', 'CRE', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Georgetown', 'Hoyas', 'GTWN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Providence', 'Friars', 'PROV', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Seton Hall', 'Pirates', 'SH', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'St. John''s', 'Red Storm', 'STJ', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Villanova', 'Wildcats', 'NOVA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Xavier', 'Musketeers', 'XAV', '', ''),
  -- Atlantic 10 (13)
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Dayton', 'Flyers', 'DAY', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Davidson', 'Wildcats', 'DVSN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Fordham', 'Rams', 'FOR', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'George Mason', 'Patriots', 'GMU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'George Washington', 'Revolutionaries', 'GWU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'La Salle', 'Explorers', 'LAS', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Massachusetts', 'Minutemen', 'UMASS', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Rhode Island', 'Rams', 'URI', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Richmond', 'Spiders', 'RICH', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Saint Louis', 'Billikens', 'SLU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'St. Bonaventure', 'Bonnies', 'SBN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'St. Joseph''s', 'Hawks', 'STJO', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'VCU', 'Rams', 'VCU', '', ''),
  -- ASUN (10)
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Bellarmine', 'Knights', 'BELL', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Central Arkansas', 'Bears', 'UCA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Eastern Kentucky', 'Colonels', 'EKU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Florida Gulf Coast', 'Eagles', 'FGCU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Jacksonville', 'Dolphins', 'JU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Lipscomb', 'Bisons', 'LIP', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'North Alabama', 'Lions', 'UNA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'North Florida', 'Ospreys', 'UNF', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Queens', 'Royals', 'QU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Stetson', 'Hatters', 'STET', '', ''),
  -- Southern (10)
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'The Citadel', 'Bulldogs', 'CIT', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'East Tennessee State', 'Buccaneers', 'ETSU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Furman', 'Paladins', 'FUR', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Mercer', 'Bears', 'MER', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Samford', 'Bulldogs', 'SAM', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'UNC Greensboro', 'Spartans', 'UNCG', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'VMI', 'Keydets', 'VMI', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Western Carolina', 'Catamounts', 'WCU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Wofford', 'Terriers', 'WOF', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Chattanooga', 'Mocs', 'UTC', '', ''),
  -- Big West (11)
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Cal Poly', 'Mustangs', 'CP', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Cal State Bakersfield', 'Roadrunners', 'CSUB', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Cal State Fullerton', 'Titans', 'CSUF', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Cal State Northridge', 'Matadors', 'CSUN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Hawaii', 'Rainbow Warriors', 'HAW', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Long Beach State', 'Beach', 'LBSU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'UC Davis', 'Aggies', 'UCD', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'UC Irvine', 'Anteaters', 'UCI', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'UC Riverside', 'Highlanders', 'UCR', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'UC San Diego', 'Tritons', 'UCSD', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'UC Santa Barbara', 'Gauchos', 'UCSB', '', ''),
  -- Patriot League (6)
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Army', 'Black Knights', 'ARMY', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Bucknell', 'Bison', 'BUCK', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Holy Cross', 'Crusaders', 'HC', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Lafayette', 'Leopards', 'LAF', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Lehigh', 'Mountain Hawks', 'LEH', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Navy', 'Midshipmen', 'NAVY2', '', ''),
  -- Ivy League (8)
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Brown', 'Bears', 'BRWN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Columbia', 'Lions', 'CLMB', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Cornell', 'Big Red', 'COR', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Dartmouth', 'Big Green', 'DART', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Harvard', 'Crimson', 'HARV', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Penn', 'Quakers', 'PENN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Princeton', 'Tigers', 'PRIN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Yale', 'Bulldogs', 'YALE', '', ''),
  -- Horizon League (8)
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Cleveland State', 'Vikings', 'CLST', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Illinois-Chicago', 'Flames', 'UIC2', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'IUPUI', 'Jaguars', 'IUPU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Milwaukee', 'Panthers', 'MILW', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Northern Kentucky', 'Norse', 'NKU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Oakland', 'Golden Grizzlies', 'OAK', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Wright State', 'Raiders', 'WRST', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Youngstown State', 'Penguins', 'YSU', '', ''),
  -- Ohio Valley (9)
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Morehead State', 'Eagles', 'MORE', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Southeast Missouri', 'Redhawks', 'SEMO', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'SIU Edwardsville', 'Cougars', 'SIUE', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Tennessee State', 'Tigers', 'TSU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Tennessee Tech', 'Golden Eagles', 'TTN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'UT Martin', 'Skyhawks', 'UTM', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Little Rock', 'Trojans', 'LR', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Southern Indiana', 'Screaming Eagles', 'USI', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Lindenwood', 'Lions', 'LIND', '', ''),
  -- Southland (9)
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Houston Christian', 'Huskies', 'HCU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Incarnate Word', 'Cardinals', 'IW', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Lamar', 'Cardinals', 'LAM', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'McNeese', 'Cowboys', 'MCN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'New Orleans', 'Privateers', 'UNO', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Nicholls', 'Colonels', 'NICH', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Northwestern State', 'Demons', 'NWST', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Southeastern Louisiana', 'Lions', 'SELA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Texas A&M-Corpus Christi', 'Islanders', 'AMCC', '', ''),
  -- Northeast (12)
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Bryant', 'Bulldogs', 'BRY', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Central Connecticut', 'Blue Devils', 'CCSU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Fairleigh Dickinson', 'Knights', 'FDU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Le Moyne', 'Dolphins', 'LEM', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'LIU', 'Sharks', 'LIU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Maine', 'Black Bears', 'ME', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Mercyhurst', 'Lakers', 'MERC', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Mount St. Mary''s', 'Mountaineers', 'MSM', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Sacred Heart', 'Pioneers', 'SHU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'St. Francis (PA)', 'Red Flash', 'SFP', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Stonehill', 'Skyhawks', 'STHL', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Wagner', 'Seahawks', 'WAG', '', ''),
  -- MEAC (8)
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Bethune-Cookman', 'Wildcats', 'BCU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Coppin State', 'Eagles', 'COPP', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Delaware State', 'Hornets', 'DSU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Howard', 'Bison', 'HOW', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Maryland-Eastern Shore', 'Hawks', 'UMES', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Norfolk State', 'Spartans', 'NSU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'North Carolina A&T', 'Aggies', 'NCAT', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'South Carolina State', 'Bulldogs', 'SCST', '', ''),
  -- SWAC (10)
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Alabama A&M', 'Bulldogs', 'AAMU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Alabama State', 'Hornets', 'ALST', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Alcorn State', 'Braves', 'ALCN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Grambling State', 'Tigers', 'GRAM', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Jackson State', 'Tigers', 'JKST', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Mississippi Valley State', 'Delta Devils', 'MVSU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Prairie View A&M', 'Panthers', 'PVAM', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Southern', 'Jaguars', 'SOU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Texas Southern', 'Tigers', 'TXSO', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Arkansas-Pine Bluff', 'Golden Lions', 'UAPB', '', ''),
  -- Summit League (6)
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'North Dakota State', 'Bison', 'NDSU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Omaha', 'Mavericks', 'OMA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Oral Roberts', 'Golden Eagles', 'ORU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'South Dakota State', 'Jackrabbits', 'SDST', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'St. Thomas (MN)', 'Tommies', 'STMN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Western Illinois', 'Leathernecks', 'WIU', '', ''),
  -- WAC (7)
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Abilene Christian', 'Wildcats', 'ACU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Grand Canyon', 'Antelopes', 'GCU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Seattle U', 'Redhawks', 'SEA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Southern Utah', 'Thunderbirds', 'SUU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Stephen F. Austin', 'Lumberjacks', 'SFA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Tarleton State', 'Texans', 'TARL', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Utah Valley', 'Wolverines', 'UVU', '', ''),
  -- America East (7)
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Albany', 'Great Danes', 'ALB', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Binghamton', 'Bearcats', 'BING', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Hartford', 'Hawks', 'HART', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'New Hampshire', 'Wildcats', 'UNH', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'NJIT', 'Highlanders', 'NJIT', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'UMass Lowell', 'River Hawks', 'UML', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Vermont', 'Catamounts', 'UVM', '', ''),
  -- MAAC (10)
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Canisius', 'Golden Griffins', 'CAN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Fairfield', 'Stags', 'FAIR', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Iona', 'Gaels', 'IONA', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Manhattan', 'Jaspers', 'MAN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Marist', 'Red Foxes', 'MRSJ', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Niagara', 'Purple Eagles', 'NIAG', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Quinnipiac', 'Bobcats', 'QUIN', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Rider', 'Broncs', 'RID', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Saint Peter''s', 'Peacocks', 'SPU', '', ''),
  ((SELECT id FROM sports_league WHERE slug='ncaabb'), 'Siena', 'Saints', 'SIEN', '', '')
ON CONFLICT (league_id, abbreviation) DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────
-- Verification
-- ─────────────────────────────────────────────────────────────────────
SELECT '=== TOTALS ===' AS info;
SELECT 'Sports: ' || COUNT(*) FROM sports_sport;
SELECT 'Leagues: ' || COUNT(*) FROM sports_league;
SELECT 'Teams: ' || COUNT(*) FROM sports_team;

SELECT l.abbreviation AS league, COUNT(t.id) AS teams
FROM sports_league l
LEFT JOIN sports_team t ON t.league_id = l.id
GROUP BY l.abbreviation
ORDER BY l.abbreviation;
