# Generated by Django 4.2.27 on 2026-03-12 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purpose', '0007_commitment_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparedCelebration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('celebration_type', models.CharField(choices=[('streak_milestone', 'Streak Milestone'), ('goal_milestone', 'Goal Milestone Completed'), ('weekly_discipline', 'Strong Weekly Discipline'), ('momentum_surge', 'Momentum Surge'), ('health_breakthrough', 'Health Breakthrough'), ('consistency_pattern', 'Consistency Pattern'), ('cross_domain', 'Cross-Domain Win')], max_length=30)),
                ('status', models.CharField(choices=[('ready', 'Ready to Reveal'), ('revealed', 'Revealed'), ('dismissed', 'Dismissed'), ('expired', 'Expired')], default='ready', max_length=20)),
                ('headline', models.CharField(help_text='Bold celebration headline', max_length=200)),
                ('narrative', models.TextField(help_text='Full celebration narrative with specifics')),
                ('evidence', models.JSONField(default=dict, help_text='Data backing the celebration')),
                ('domain', models.CharField(blank=True, help_text='Life domain (e.g., health, faith)', max_length=50)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revealed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='Celebration expires if not revealed within 7 days')),
                ('dedupe_key', models.CharField(db_index=True, max_length=255)),
                ('related_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celebrations', to='purpose.lifegoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='dashboard_v_user_id_a07e1e_idx'), models.Index(fields=['user', 'celebration_type', 'generated_at'], name='dashboard_v_user_id_57824d_idx')],
            },
        ),
        migrations.CreateModel(
            name='GoalMomentumSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('momentum_score', models.PositiveSmallIntegerField(help_text='0-100: How strongly moving toward this goal RIGHT NOW')),
                ('progress_score', models.PositiveSmallIntegerField(help_text='0-100: How far along the journey (milestone-based)')),
                ('drivers', models.JSONField(default=dict, help_text="Breakdown of momentum components. Example: {'habits': {'score': 28, 'label': '4/5 habits completed'}, ...}")),
                ('momentum_7d_avg', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('momentum_trend', models.CharField(blank=True, choices=[('rising', 'Rising'), ('stable', 'Stable'), ('falling', 'Falling')], max_length=20)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momentum_snapshots', to='purpose.lifegoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['user', 'snapshot_date'], name='dashboard_v_user_id_0f387a_idx')],
                'unique_together': {('user', 'goal', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='DailyProgressSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API')], default='manual', help_text='How this entry was created', max_length=20)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('routines_score', models.PositiveSmallIntegerField(default=0)),
                ('medicine_score', models.PositiveSmallIntegerField(default=0)),
                ('tasks_score', models.PositiveSmallIntegerField(default=0)),
                ('journaling_score', models.PositiveSmallIntegerField(default=0)),
                ('workout_score', models.PositiveSmallIntegerField(default=0)),
                ('faith_score', models.PositiveSmallIntegerField(default=0)),
                ('overall_score', models.PositiveSmallIntegerField(default=0, help_text='Weighted average of component scores, 0-100')),
                ('components', models.JSONField(default=dict, help_text="Raw component data for display. Example: {'routines_done': 3, 'routines_total': 5, 'meds_taken': 4, ...}")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['user', 'snapshot_date'], name='dashboard_v_user_id_114a3c_idx')],
                'unique_together': {('user', 'snapshot_date')},
            },
        ),
    ]
