# Generated by Django 4.2.27 on 2026-03-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_v2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='preparedcelebration',
            name='dashboard_v_user_id_a07e1e_idx',
        ),
        migrations.AddField(
            model_name='preparedcelebration',
            name='celebration_status',
            field=models.CharField(choices=[('ready', 'Ready to Reveal'), ('revealed', 'Revealed'), ('dismissed', 'Dismissed'), ('expired', 'Expired')], default='ready', max_length=20),
        ),
        migrations.AlterField(
            model_name='preparedcelebration',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10),
        ),
        migrations.AddIndex(
            model_name='preparedcelebration',
            index=models.Index(fields=['user', 'celebration_status'], name='dashboard_v_user_id_2aa4ff_idx'),
        ),
    ]
