# Generated by Django 4.2.27 on 2026-03-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_v2', '0002_remove_preparedcelebration_dashboard_v_user_id_a07e1e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparedcelebration',
            name='celebration_type',
            field=models.CharField(choices=[('streak_milestone', 'Consistency Milestone'), ('goal_milestone', 'Goal Milestone Completed'), ('weekly_discipline', 'Strong Weekly Discipline'), ('momentum_surge', 'Momentum Surge'), ('health_breakthrough', 'Health Breakthrough'), ('consistency_pattern', 'Consistency Pattern'), ('cross_domain', 'Cross-Domain Win')], max_length=30),
        ),
    ]
