# Generated by Django 4.2.27 on 2026-03-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_v2', '0003_alter_preparedcelebration_celebration_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalmomentumsnapshot',
            name='signal_scores',
            field=models.JSONField(default=dict, help_text="Per-signal-type scores from GoalSignalSource weighting. Example: {'health_activity': 0.85, 'medication_adherence': 1.0}"),
        ),
    ]
