# Generated by Django 4.2.27 on 2026-03-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_v2', '0004_goalmomentumsnapshot_signal_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprogresssnapshot',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='goalmomentumsnapshot',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
        migrations.AlterField(
            model_name='preparedcelebration',
            name='created_via',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20),
        ),
    ]
