# Generated by Django 4.2.27 on 2026-03-23 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard_v2', '0005_routine_maintenance_bridge_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(db_index=True, help_text='The date this expectation applies to')),
                ('domain', models.CharField(choices=[('medication', 'Medication'), ('workout', 'Workout'), ('routine', 'Routine'), ('task', 'Task'), ('journal', 'Journal'), ('faith', 'Faith')], help_text='Source domain (medication, workout, routine, task, journal, faith)', max_length=30)),
                ('scoring_bucket', models.CharField(choices=[('medication_doses', 'Medication Doses'), ('workouts', 'Workouts'), ('routine_items', 'Routine Items'), ('tasks', 'Tasks'), ('journal', 'Journal'), ('faith', 'Faith')], help_text='Which V2 summary card this event rolls into', max_length=30)),
                ('item_type', models.CharField(help_text="Model name or type identifier (e.g., 'MedicineSchedule', 'Task')", max_length=50)),
                ('item_id', models.PositiveIntegerField(blank=True, help_text='PK of the source record (schedule, task, etc.)', null=True)),
                ('item_label', models.CharField(help_text='Human-readable item name for display', max_length=255)),
                ('expected_at', models.TimeField(blank=True, help_text='When this item was expected (scheduled time)', null=True)),
                ('expected', models.BooleanField(default=True, help_text='Was this item expected/due on this date?')),
                ('actual_status', models.CharField(choices=[('none', 'No action taken'), ('completed', 'Completed'), ('completed_late', 'Completed Late'), ('skipped', 'Skipped'), ('rescheduled', 'Rescheduled'), ('open', 'Open / In Progress')], help_text='What actually happened', max_length=20)),
                ('final_status', models.CharField(choices=[('completed', 'Completed'), ('completed_late', 'Completed Late'), ('skipped', 'Skipped'), ('missed', 'Missed'), ('overdue', 'Overdue'), ('rescheduled', 'Rescheduled'), ('not_expected', 'Not Expected')], help_text='Scoring status after applying rules', max_length=20)),
                ('reason_code', models.CharField(choices=[('on_time', 'Completed within grace period'), ('after_grace', 'Completed after grace period expired'), ('no_log', 'No completion log found'), ('explicit_skip', 'Explicitly skipped by user'), ('explicit_missed', 'Explicitly marked as missed'), ('overdue_due_date', 'Past due date and still incomplete'), ('not_due_today', 'Not due/scheduled for this date'), ('inactive_schedule', 'Schedule is inactive or paused'), ('rest_day', 'Scheduled rest day'), ('rescheduled', 'Rescheduled to a different time'), ('satisfied_by_linked', 'Satisfied by linked event'), ('no_due_date', 'No due date assigned'), ('completed_today', 'Task completed on this date'), ('plan_active', 'Active reading plan for this date'), ('no_plan', 'No active reading plan'), ('entry_exists', 'Entry logged for this date'), ('no_entry', 'No entry found for this date'), ('asserted_on_time', 'User asserted on-time completion')], help_text='Why this item received its final_status', max_length=40)),
                ('reason_detail', models.JSONField(blank=True, default=dict, help_text='Additional context: grace period, linked items, metadata')),
                ('source_system', models.CharField(help_text='Which model/system produced this event', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_event', models.ForeignKey(blank=True, help_text='If this event was satisfied by another event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_events', to='dashboard_v2.complianceevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_date', 'expected_at'],
                'indexes': [models.Index(fields=['user', 'event_date'], name='dashboard_v_user_id_d17b55_idx'), models.Index(fields=['user', 'scoring_bucket', 'event_date'], name='dashboard_v_user_id_db8ebe_idx'), models.Index(fields=['user', 'domain', 'event_date'], name='dashboard_v_user_id_53bd18_idx'), models.Index(fields=['user', 'final_status', 'event_date'], name='dashboard_v_user_id_6c3677_idx')],
            },
        ),
    ]
