# Generated by Django 4.2.27 on 2026-03-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_v2', '0006_compliance_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceevent',
            name='is_primary',
            field=models.BooleanField(default=True, help_text='True if this event counts toward rollup scoring. Suppressed duplicates have is_primary=False.'),
        ),
        migrations.AddField(
            model_name='complianceevent',
            name='obligation_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Deterministic key grouping events that represent the same real-world obligation. Events sharing a key are reconciled so only one is score-bearing.', max_length=200),
        ),
        migrations.AddField(
            model_name='complianceevent',
            name='suppression_reason',
            field=models.CharField(blank=True, default='', help_text='Why this event was suppressed from scoring (empty = not suppressed)', max_length=50),
        ),
        migrations.AlterField(
            model_name='complianceevent',
            name='reason_code',
            field=models.CharField(choices=[('on_time', 'Completed within grace period'), ('after_grace', 'Completed after grace period expired'), ('no_log', 'No completion log found'), ('explicit_skip', 'Explicitly skipped by user'), ('explicit_missed', 'Explicitly marked as missed'), ('overdue_due_date', 'Past due date and still incomplete'), ('not_due_today', 'Not due/scheduled for this date'), ('inactive_schedule', 'Schedule is inactive or paused'), ('rest_day', 'Scheduled rest day'), ('rescheduled', 'Rescheduled to a different time'), ('satisfied_by_linked', 'Satisfied by linked event'), ('no_due_date', 'No due date assigned'), ('completed_today', 'Task completed on this date'), ('plan_active', 'Active reading plan for this date'), ('no_plan', 'No active reading plan'), ('entry_exists', 'Entry logged for this date'), ('no_entry', 'No entry found for this date'), ('asserted_on_time', 'User asserted on-time completion'), ('satisfied_by_linked_workout', 'Satisfied by linked workout completion'), ('duplicate_obligation', 'Duplicate obligation — not counted separately')], help_text='Why this item received its final_status', max_length=40),
        ),
        migrations.AddIndex(
            model_name='complianceevent',
            index=models.Index(fields=['user', 'obligation_key'], name='dashboard_v_user_id_3001f0_idx'),
        ),
    ]
