# Generated by Django 4.2.27 on 2026-03-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_v2', '0007_obligation_reconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceevent',
            name='obligation_identity',
            field=models.CharField(blank=True, default='', help_text='Stable identifier within obligation_type. e.g., WorkoutSchedule PK, MedicineSchedule PK, Task PK. Combined with type+user+date to form obligation_key.', max_length=100),
        ),
        migrations.AddField(
            model_name='complianceevent',
            name='obligation_type',
            field=models.CharField(blank=True, default='', help_text='Obligation category: workout, journal, faith_prayer, faith_bible, medication, task. Events with the same type+identity+date are one obligation.', max_length=30),
        ),
        migrations.AlterField(
            model_name='complianceevent',
            name='obligation_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Deterministic key: {type}:{user_id}:{date}:{identity}. Events sharing a key are reconciled so only one is score-bearing.', max_length=200),
        ),
        migrations.AlterField(
            model_name='complianceevent',
            name='reason_code',
            field=models.CharField(choices=[('on_time', 'Completed within grace period'), ('after_grace', 'Completed after grace period expired'), ('no_log', 'No completion log found'), ('explicit_skip', 'Explicitly skipped by user'), ('explicit_missed', 'Explicitly marked as missed'), ('overdue_due_date', 'Past due date and still incomplete'), ('not_due_today', 'Not due/scheduled for this date'), ('inactive_schedule', 'Schedule is inactive or paused'), ('rest_day', 'Scheduled rest day'), ('rescheduled', 'Rescheduled to a different time'), ('satisfied_by_linked', 'Satisfied by linked event'), ('no_due_date', 'No due date assigned'), ('completed_today', 'Task completed on this date'), ('plan_active', 'Active reading plan for this date'), ('no_plan', 'No active reading plan'), ('entry_exists', 'Entry logged for this date'), ('no_entry', 'No entry found for this date'), ('asserted_on_time', 'User asserted on-time completion'), ('satisfied_by_linked', 'Satisfied by linked activity'), ('satisfied_by_linked_workout', 'Satisfied by linked workout completion'), ('satisfied_by_linked_journal', 'Satisfied by linked journal entry'), ('satisfied_by_linked_faith', 'Satisfied by linked faith activity'), ('duplicate_obligation', 'Duplicate obligation — not counted separately')], help_text='Why this item received its final_status', max_length=40),
        ),
    ]
