# Generated by Django 5.2.9 on 2025-12-26 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=50)),
                ("model_used", models.CharField(max_length=50)),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Estimated cost in USD",
                        max_digits=10,
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily Dashboard Insight"),
                            ("weekly_summary", "Weekly Journal Summary"),
                            ("monthly_summary", "Monthly Journal Summary"),
                            ("reflection_prompt", "Reflection Prompt"),
                            ("goal_encouragement", "Goal Encouragement"),
                            ("health_insight", "Health Insight"),
                            ("prayer_encouragement", "Prayer Encouragement"),
                            ("entry_reflection", "Journal Entry Reflection"),
                        ],
                        max_length=30,
                    ),
                ),
                ("content", models.TextField()),
                ("related_object_type", models.CharField(blank=True, max_length=50)),
                (
                    "related_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "context_summary",
                    models.TextField(
                        blank=True, help_text="Summary of data used to generate"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this insight should be refreshed",
                        null=True,
                    ),
                ),
                ("was_helpful", models.BooleanField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_insights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "insight_type", "-created_at"],
                        name="ai_aiinsigh_user_id_063ffd_idx",
                    ),
                    models.Index(
                        fields=["user", "valid_until"],
                        name="ai_aiinsigh_user_id_7cf7db_idx",
                    ),
                ],
            },
        ),
    ]
