# Generated by Django 5.2.9 on 2025-12-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsight',
            name='coaching_style',
            field=models.CharField(blank=True, default='supportive', help_text='Coaching style used when generating this insight', max_length=20),
        ),
    ]
