# Generated by Django 5.2.9 on 2025-12-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_add_coaching_style_to_aiinsight"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoachingStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Unique identifier (e.g., 'southern_belle', 'texas_rancher')",
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name shown to users", max_length=100
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Brief description shown when user selects style",
                        max_length=300,
                    ),
                ),
                (
                    "prompt_instructions",
                    models.TextField(
                        help_text="Full AI prompt instructions for this coaching style"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this style is available for users to select",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Use this style as fallback if user's style is unavailable",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which styles appear in selection UI",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Coaching Style",
                "verbose_name_plural": "Coaching Styles",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
