# Generated by Django 5.2.9 on 2025-12-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_add_coaching_style_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachingstyle",
            name="icon",
            field=models.CharField(
                default="🤝", help_text="Emoji icon displayed in the UI", max_length=10
            ),
        ),
    ]
