# Generated by Django 5.2.9 on 2025-12-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0004_add_icon_to_coaching_style"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPromptConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt_type",
                    models.CharField(
                        choices=[
                            ("system_base", "System Base Prompt"),
                            ("daily_insight", "Daily Dashboard Insight"),
                            ("weekly_summary", "Weekly Journal Summary"),
                            ("journal_reflection", "Journal Entry Reflection"),
                            ("goal_progress", "Goal Progress Feedback"),
                            ("health_encouragement", "Health Encouragement"),
                            ("prayer_encouragement", "Prayer Encouragement"),
                            ("accountability_nudge", "Accountability Nudge"),
                            ("celebration", "Celebration Message"),
                            ("faith_context", "Faith Context Addition"),
                        ],
                        help_text="Type of prompt this configuration applies to",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for this configuration", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about this prompt configuration",
                    ),
                ),
                (
                    "system_instructions",
                    models.TextField(
                        help_text="Main instructions for the AI. Use {variables} for dynamic content."
                    ),
                ),
                (
                    "min_sentences",
                    models.PositiveIntegerField(
                        default=2, help_text="Minimum number of sentences in response"
                    ),
                ),
                (
                    "max_sentences",
                    models.PositiveIntegerField(
                        default=4, help_text="Maximum number of sentences in response"
                    ),
                ),
                (
                    "max_tokens",
                    models.PositiveIntegerField(
                        default=150, help_text="Maximum tokens for API response"
                    ),
                ),
                (
                    "tone_guidance",
                    models.TextField(
                        blank=True,
                        help_text="Additional tone/style guidance (e.g., 'Be warm but not preachy')",
                    ),
                ),
                (
                    "things_to_avoid",
                    models.TextField(
                        blank=True,
                        help_text="Things the AI should NOT do (e.g., 'Never shame the user')",
                    ),
                ),
                (
                    "example_responses",
                    models.TextField(
                        blank=True,
                        help_text="Example good responses for this prompt type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this configuration is currently in use",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Prompt Configuration",
                "verbose_name_plural": "AI Prompt Configurations",
                "ordering": ["prompt_type"],
            },
        ),
    ]
