# Generated by Django 5.2.9 on 2025-12-28 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0005_add_ai_prompt_config"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aiinsight",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "AI Insight",
                "verbose_name_plural": "AI Insights",
            },
        ),
        migrations.AlterModelOptions(
            name="aiusagelog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "AI Usage Log",
                "verbose_name_plural": "AI Usage Logs",
            },
        ),
    ]
