# Generated by Django 5.2.9 on 2025-12-29 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0006_alter_aiinsight_options_alter_aiusagelog_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated or user-provided conversation title",
                        max_length=200,
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("daily_checkin", "Daily Check-in"),
                            ("reflection", "Reflection Session"),
                            ("planning", "Planning Session"),
                            ("accountability", "Accountability Check"),
                            ("celebration", "Celebration"),
                            ("general", "General Conversation"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this conversation is currently active",
                    ),
                ),
                (
                    "context_summary",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated summary of conversation for continuity",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Assistant Conversation",
                "verbose_name_plural": "Assistant Conversations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AssistantMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Message"),
                            ("insight", "AI Insight"),
                            ("nudge", "Accountability Nudge"),
                            ("celebration", "Celebration"),
                            ("action_suggestion", "Action Suggestion"),
                            ("reflection_prompt", "Reflection Prompt"),
                            ("scripture", "Scripture Reference"),
                            ("priority_list", "Priority List"),
                            ("state_assessment", "State Assessment"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data for message (e.g., action URLs, priorities)",
                    ),
                ),
                ("was_helpful", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai.assistantconversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assistant Message",
                "verbose_name_plural": "Assistant Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyPriority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority_date", models.DateField()),
                (
                    "priority_type",
                    models.CharField(
                        choices=[
                            ("faith", "Faith & Spiritual"),
                            ("purpose", "Purpose & Goals"),
                            ("commitment", "Existing Commitment"),
                            ("maintenance", "Maintenance Task"),
                            ("health", "Health & Wellness"),
                            ("relationship", "Relationship"),
                            ("work", "Work & Career"),
                            ("personal", "Personal Growth"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "why_important",
                    models.TextField(
                        blank=True,
                        help_text="Connection to user's stated purpose/goals",
                    ),
                ),
                ("linked_task_id", models.PositiveIntegerField(blank=True, null=True)),
                ("linked_goal_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "linked_intention_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("user_dismissed", models.BooleanField(default=False)),
                ("generated_by_ai", models.BooleanField(default=True)),
                ("generation_context", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_priorities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Priority",
                "verbose_name_plural": "Daily Priorities",
                "ordering": ["priority_date", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ReflectionPromptQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt_text", models.TextField()),
                (
                    "prompt_context",
                    models.CharField(
                        choices=[
                            ("morning", "Morning Reflection"),
                            ("evening", "Evening Reflection"),
                            ("weekly", "Weekly Review"),
                            ("goal_related", "Goal-Related"),
                            ("intention_check", "Intention Check"),
                            ("gratitude", "Gratitude"),
                            ("faith", "Faith & Spiritual"),
                            ("challenge", "Challenge Processing"),
                            ("celebration", "Celebration"),
                            ("general", "General Reflection"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "relevance_reason",
                    models.TextField(
                        blank=True,
                        help_text="Why this prompt is relevant to the user right now",
                    ),
                ),
                ("linked_goal_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "linked_intention_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("linked_entry_id", models.PositiveIntegerField(blank=True, null=True)),
                ("is_shown", models.BooleanField(default=False)),
                ("shown_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user started journaling with this prompt",
                    ),
                ),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Some prompts are time-sensitive",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reflection_prompts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reflection Prompt",
                "verbose_name_plural": "Reflection Prompts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrendAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("week", "Weekly"),
                            ("month", "Monthly"),
                            ("quarter", "Quarterly"),
                            ("year", "Annual"),
                        ],
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("overall", "Overall Wellness"),
                            ("journal", "Journaling Patterns"),
                            ("productivity", "Productivity & Tasks"),
                            ("faith", "Faith Journey"),
                            ("health", "Health & Fitness"),
                            ("goals", "Goal Progress"),
                            ("mood", "Mood Patterns"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "summary",
                    models.TextField(help_text="AI-generated summary of the period"),
                ),
                (
                    "patterns_detected",
                    models.JSONField(
                        default=list, help_text="Patterns identified during this period"
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        default=list, help_text="AI recommendations based on analysis"
                    ),
                ),
                (
                    "comparison_to_previous",
                    models.TextField(
                        blank=True,
                        help_text="How this period compares to the previous period",
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        default=dict, help_text="Key metrics for this period"
                    ),
                ),
                ("was_helpful", models.BooleanField(blank=True, null=True)),
                ("user_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trend_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trend Analysis",
                "verbose_name_plural": "Trend Analyses",
                "ordering": ["-period_end", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserStateSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField()),
                ("journal_count_total", models.PositiveIntegerField(default=0)),
                ("journal_count_week", models.PositiveIntegerField(default=0)),
                ("journal_streak", models.PositiveIntegerField(default=0)),
                ("dominant_mood", models.CharField(blank=True, max_length=20)),
                ("tasks_completed_today", models.PositiveIntegerField(default=0)),
                ("tasks_completed_week", models.PositiveIntegerField(default=0)),
                ("tasks_overdue", models.PositiveIntegerField(default=0)),
                ("tasks_due_today", models.PositiveIntegerField(default=0)),
                ("active_goals", models.PositiveIntegerField(default=0)),
                ("completed_goals_month", models.PositiveIntegerField(default=0)),
                ("goal_progress_notes", models.TextField(blank=True)),
                ("active_prayers", models.PositiveIntegerField(default=0)),
                ("answered_prayers_month", models.PositiveIntegerField(default=0)),
                ("bible_study_entries_week", models.PositiveIntegerField(default=0)),
                (
                    "weight_current",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("weight_trend", models.CharField(blank=True, max_length=10)),
                ("fasts_completed_week", models.PositiveIntegerField(default=0)),
                ("workouts_week", models.PositiveIntegerField(default=0)),
                ("workout_streak", models.PositiveIntegerField(default=0)),
                (
                    "medicine_adherence",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("active_intentions", models.PositiveIntegerField(default=0)),
                (
                    "intention_alignment_score",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="AI-assessed alignment with stated intentions (0-100)",
                        null=True,
                    ),
                ),
                (
                    "ai_assessment",
                    models.TextField(
                        blank=True, help_text="AI's assessment of user state this day"
                    ),
                ),
                (
                    "alignment_gaps",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Areas where behavior doesn't match stated intentions",
                    ),
                ),
                (
                    "celebration_worthy",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Achievements worth celebrating",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User State Snapshot",
                "verbose_name_plural": "User State Snapshots",
                "ordering": ["-snapshot_date"],
            },
        ),
        migrations.AddIndex(
            model_name="assistantconversation",
            index=models.Index(
                fields=["user", "-updated_at"], name="ai_assistan_user_id_e50fdd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assistantconversation",
            index=models.Index(
                fields=["user", "is_active"], name="ai_assistan_user_id_b1347b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assistantmessage",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="ai_assistan_convers_a9a79b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dailypriority",
            index=models.Index(
                fields=["user", "priority_date"], name="ai_dailypri_user_id_7d1916_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailypriority",
            index=models.Index(
                fields=["user", "priority_date", "is_completed"],
                name="ai_dailypri_user_id_80b41b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reflectionpromptqueue",
            index=models.Index(
                fields=["user", "is_shown", "-created_at"],
                name="ai_reflecti_user_id_1b0643_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trendanalysis",
            index=models.Index(
                fields=["user", "-period_end"], name="ai_trendana_user_id_546583_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trendanalysis",
            index=models.Index(
                fields=["user", "period_type", "-period_end"],
                name="ai_trendana_user_id_1b71ef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userstatesnapshot",
            index=models.Index(
                fields=["user", "-snapshot_date"], name="ai_userstat_user_id_05bfcf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userstatesnapshot",
            unique_together={("user", "snapshot_date")},
        ),
    ]
