# Generated by Django 5.2.9 on 2026-01-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0007_dashboard_ai_personal_assistant"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstatesnapshot",
            name="active_habit_goals",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userstatesnapshot",
            name="habit_completion_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Average completion rate across active habit goals",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userstatesnapshot",
            name="habit_current_streak",
            field=models.PositiveIntegerField(
                default=0, help_text="Current longest streak across habit goals"
            ),
        ),
        migrations.AddField(
            model_name="userstatesnapshot",
            name="habit_goals_data",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Detailed habit goal data for AI analysis",
            ),
        ),
    ]
