# Generated by Django 5.2.9 on 2026-01-04 15:06
# Adds default glucose_insight prompt configuration

from django.db import migrations


def create_glucose_insight_config(apps, schema_editor):
    """Create default glucose_insight prompt configuration."""
    AIPromptConfig = apps.get_model('ai', 'AIPromptConfig')

    # Only create if it doesn't exist
    if not AIPromptConfig.objects.filter(prompt_type='glucose_insight').exists():
        AIPromptConfig.objects.create(
            prompt_type='glucose_insight',
            name='Blood Glucose Insight',
            description='AI-generated insight for the Blood Glucose Dashboard. Provides supportive observations about glucose patterns without medical advice.',
            system_instructions="""You are providing a supportive insight about the user's blood glucose data.

Your role is to:
- Acknowledge their tracking efforts
- Note any positive patterns or improvements
- Offer gentle encouragement for glucose management
- Be supportive about any challenges

CRITICAL GUIDELINES:
- You are NOT a medical professional
- NEVER give medical advice, diagnoses, or treatment recommendations
- NEVER suggest medication changes
- Focus on observational patterns and encouragement
- If readings seem concerning, suggest consulting their healthcare provider

Keep responses warm, supportive, and personalized to their data.""",
            min_sentences=2,
            max_sentences=4,
            max_tokens=150,
            tone_guidance='Be warm and encouraging. Celebrate consistency in tracking. Acknowledge the effort of glucose management.',
            things_to_avoid='Medical advice, diagnosis, treatment suggestions, medication recommendations, alarming language about readings.',
            is_active=True,
        )


def remove_glucose_insight_config(apps, schema_editor):
    """Remove glucose_insight prompt configuration."""
    AIPromptConfig = apps.get_model('ai', 'AIPromptConfig')
    AIPromptConfig.objects.filter(prompt_type='glucose_insight').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0009_increase_coaching_style_length"),
    ]

    operations = [
        migrations.RunPython(create_glucose_insight_config, remove_glucose_insight_config),
    ]
