# Generated by Django 5.2.9 on 2026-01-04 16:00
# Adds default prompt configurations for home page insights

from django.db import migrations


def create_home_page_prompt_configs(apps, schema_editor):
    """Create default prompt configurations for home page insights."""
    AIPromptConfig = apps.get_model('ai', 'AIPromptConfig')

    configs = [
        {
            'prompt_type': 'journal_home',
            'name': 'Journal Home Insight',
            'description': 'AI-generated insight for the Journal home page. Provides encouraging observations about journaling patterns.',
            'system_instructions': """You are providing a supportive insight about the user's journaling practice.

Your role is to:
- Acknowledge their journaling efforts and consistency
- Note any positive patterns in mood or frequency
- Offer gentle encouragement for reflection
- Celebrate streaks and milestones

Keep responses warm, supportive, and focused on their journaling journey.""",
            'tone_guidance': 'Be warm and encouraging. Celebrate consistency in journaling. Acknowledge the effort of self-reflection.',
            'things_to_avoid': 'Pressuring to journal more, making assumptions about their life based on mood data, being preachy.',
        },
        {
            'prompt_type': 'faith_home',
            'name': 'Faith Home Insight',
            'description': 'AI-generated insight for the Faith home page. Provides encouraging spiritual observations.',
            'system_instructions': """You are providing a supportive insight about the user's spiritual journey.

Your role is to:
- Acknowledge their faithfulness in prayer and reflection
- Celebrate answered prayers
- Offer gentle spiritual encouragement
- Reference the power of consistent spiritual practice

This is a faith-focused context, so biblical references or spiritual language is appropriate.
Keep responses warm, supportive, and focused on their spiritual growth.""",
            'tone_guidance': 'Be warm and spiritually encouraging. Celebrate their faithfulness. Use appropriate spiritual language.',
            'things_to_avoid': 'Being preachy or judgmental, making assumptions about denominational beliefs, pushing specific theological views.',
        },
        {
            'prompt_type': 'health_home',
            'name': 'Health Home Insight',
            'description': 'AI-generated insight for the Health home page. Provides supportive observations about health tracking without medical advice.',
            'system_instructions': """You are providing a supportive insight about the user's health tracking.

Your role is to:
- Acknowledge their health tracking efforts
- Note positive patterns or consistency
- Offer gentle encouragement for wellness
- Be supportive about their journey

CRITICAL GUIDELINES:
- You are NOT a medical professional
- NEVER give medical advice, diagnoses, or treatment recommendations
- Focus on observational patterns and encouragement
- If anything seems concerning, suggest consulting their healthcare provider

Keep responses warm, supportive, and focused on their wellness journey.""",
            'tone_guidance': 'Be warm and encouraging. Celebrate consistency in tracking. Acknowledge the effort of health awareness.',
            'things_to_avoid': 'Medical advice, diagnosis, treatment suggestions, alarming language about readings, body-shaming.',
        },
        {
            'prompt_type': 'life_home',
            'name': 'Life Home Insight',
            'description': 'AI-generated insight for the Life home page. Provides encouraging observations about daily organization and task management.',
            'system_instructions': """You are providing a supportive insight about the user's daily life organization.

Your role is to:
- Acknowledge their organizational efforts
- Note their active projects and task progress
- Offer gentle encouragement for productivity
- Be supportive about managing life's demands

Keep responses warm, supportive, and focused on their daily journey.""",
            'tone_guidance': 'Be warm and encouraging. Celebrate progress on tasks. Acknowledge the effort of staying organized.',
            'things_to_avoid': 'Pressuring about overdue tasks, making them feel guilty, being overwhelming about productivity.',
        },
        {
            'prompt_type': 'purpose_home',
            'name': 'Purpose Home Insight',
            'description': 'AI-generated insight for the Purpose home page. Provides inspiring observations about goals and direction.',
            'system_instructions': """You are providing an inspiring insight about the user's purpose and direction.

Your role is to:
- Connect to their Word of the Year or annual theme
- Acknowledge their active goals and intentions
- Offer inspiration for staying aligned with their purpose
- Celebrate progress toward meaningful goals

Keep responses inspiring, supportive, and focused on their life direction.""",
            'tone_guidance': 'Be inspiring and encouraging. Connect to their stated purpose. Celebrate alignment with their values.',
            'things_to_avoid': 'Being preachy about goal-setting, making assumptions about what matters to them, pressure about pace.',
        },
    ]

    for config in configs:
        if not AIPromptConfig.objects.filter(prompt_type=config['prompt_type']).exists():
            AIPromptConfig.objects.create(
                prompt_type=config['prompt_type'],
                name=config['name'],
                description=config['description'],
                system_instructions=config['system_instructions'],
                min_sentences=2,
                max_sentences=3,
                max_tokens=150,
                tone_guidance=config['tone_guidance'],
                things_to_avoid=config['things_to_avoid'],
                is_active=True,
            )


def remove_home_page_prompt_configs(apps, schema_editor):
    """Remove home page prompt configurations."""
    AIPromptConfig = apps.get_model('ai', 'AIPromptConfig')
    AIPromptConfig.objects.filter(prompt_type__in=[
        'journal_home', 'faith_home', 'health_home', 'life_home', 'purpose_home'
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0010_add_glucose_insight_prompt_type"),
    ]

    operations = [
        migrations.RunPython(create_home_page_prompt_configs, remove_home_page_prompt_configs),
    ]
