# Generated by Django 5.2.10 on 2026-01-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0013_add_metadata_to_assistantconversation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiinsight",
            name="insight_type",
            field=models.CharField(
                choices=[
                    ("daily", "Daily Dashboard Insight"),
                    ("weekly_summary", "Weekly Journal Summary"),
                    ("monthly_summary", "Monthly Journal Summary"),
                    ("reflection_prompt", "Reflection Prompt"),
                    ("goal_encouragement", "Goal Encouragement"),
                    ("health_insight", "Health Insight"),
                    ("glucose_insight", "Blood Glucose Insight"),
                    ("prayer_encouragement", "Prayer Encouragement"),
                    ("entry_reflection", "Journal Entry Reflection"),
                    ("journal_home", "Journal Home Insight"),
                    ("faith_home", "Faith Home Insight"),
                    ("health_home", "Health Home Insight"),
                    ("life_home", "Life Home Insight"),
                    ("purpose_home", "Purpose Home Insight"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="aipromptconfig",
            name="prompt_type",
            field=models.CharField(
                choices=[
                    ("system_base", "System Base Prompt"),
                    ("daily_insight", "Daily Dashboard Insight"),
                    ("weekly_summary", "Weekly Journal Summary"),
                    ("journal_reflection", "Journal Entry Reflection"),
                    ("goal_progress", "Goal Progress Feedback"),
                    ("health_encouragement", "Health Encouragement"),
                    ("glucose_insight", "Blood Glucose Insight"),
                    ("prayer_encouragement", "Prayer Encouragement"),
                    ("accountability_nudge", "Accountability Nudge"),
                    ("celebration", "Celebration Message"),
                    ("faith_context", "Faith Context Addition"),
                    ("journal_home", "Journal Home Insight"),
                    ("faith_home", "Faith Home Insight"),
                    ("health_home", "Health Home Insight"),
                    ("life_home", "Life Home Insight"),
                    ("purpose_home", "Purpose Home Insight"),
                ],
                help_text="Type of prompt this configuration applies to",
                max_length=30,
                unique=True,
            ),
        ),
    ]
