# Generated by Django 4.2.27 on 2026-01-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0015_add_drill_sergeant_coaching_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmessage',
            name='image_data',
            field=models.TextField(blank=True, help_text='Base64 encoded image data'),
        ),
        migrations.AddField(
            model_name='assistantmessage',
            name='image_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the image data should be auto-deleted (72 hours after creation)', null=True),
        ),
        migrations.AddField(
            model_name='assistantmessage',
            name='image_mime_type',
            field=models.CharField(blank=True, help_text="MIME type of the image (e.g., 'image/png')", max_length=50),
        ),
        migrations.AddIndex(
            model_name='assistantmessage',
            index=models.Index(fields=['image_expires_at'], name='ai_assistan_image_e_dd3d2a_idx'),
        ),
    ]
