# Generated by Django 4.2.27 on 2026-01-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0016_add_image_fields_to_assistant_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuesGuardrailPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this pattern', max_length=100)),
                ('pattern', models.TextField(help_text='Regex pattern to match (case-insensitive). Use \\b for word boundaries.')),
                ('category', models.CharField(choices=[('explicit', 'Explicit/Adult Content'), ('violence', 'Violence/Harm'), ('illegal', 'Illegal Activity'), ('injection', 'Prompt Injection'), ('hate', 'Hate Speech'), ('off_topic', 'Off-Topic/Controversial'), ('negative', 'Excessive Negativity'), ('other', 'Other')], default='other', help_text='Category of content this pattern detects', max_length=20)),
                ('severity', models.CharField(choices=[('refuse', 'Refuse - Block completely'), ('redirect', 'Redirect - Gentle redirection')], default='redirect', help_text='How to handle matches: refuse blocks, redirect suggests alternatives', max_length=10)),
                ('refusal_message', models.TextField(blank=True, help_text='Custom message for refusals. Leave blank for default.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this pattern is currently active')),
                ('applies_to_input', models.BooleanField(default=True, help_text='Apply to user messages')),
                ('applies_to_output', models.BooleanField(default=True, help_text='Apply to AI responses')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Patterns with lower numbers are checked first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Values Guardrail Pattern',
                'verbose_name_plural': 'Values Guardrail Patterns',
                'ordering': ['sort_order', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ValuesRedirectSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('journal', 'Journal'), ('faith', 'Faith'), ('health', 'Health'), ('purpose', 'Purpose/Goals'), ('life', 'Organize/Life'), ('finance', 'Finance'), ('capture', 'Capture'), ('general', 'General Wellness')], help_text='Which WLJ module this suggestion relates to', max_length=20)),
                ('trigger_keywords', models.TextField(help_text='Comma-separated keywords that trigger this suggestion (case-insensitive)')),
                ('suggestion_text', models.TextField(help_text='The redirect message to show. Can use {module_name} placeholder.')),
                ('follow_up_prompt', models.TextField(blank=True, help_text='Optional follow-up question to guide the user')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this suggestion is currently active')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Suggestions with lower numbers are preferred')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Values Redirect Suggestion',
                'verbose_name_plural': 'Values Redirect Suggestions',
                'ordering': ['sort_order', 'module'],
            },
        ),
    ]
