# Generated by Django 4.2.27 on 2026-01-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0017_add_values_guardrail_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmessage',
            name='appeal_email_sent',
            field=models.BooleanField(default=False, help_text='Whether the appeal email was sent to admin'),
        ),
        migrations.AddField(
            model_name='assistantmessage',
            name='flagged_pattern_name',
            field=models.CharField(blank=True, help_text='Name of the pattern that triggered the flag', max_length=100),
        ),
        migrations.AddField(
            model_name='assistantmessage',
            name='is_flagged_inappropriate',
            field=models.BooleanField(default=False, help_text='Whether this message was flagged by the values filter'),
        ),
        migrations.AddField(
            model_name='assistantmessage',
            name='user_appealed',
            field=models.BooleanField(default=False, help_text="Whether the user responded 'yes' to appeal the flag"),
        ),
    ]
