# Generated by Django 4.2.27 on 2026-02-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0020_alter_aipromptconfig_prompt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmessage',
            name='is_proactive',
            field=models.BooleanField(default=False, help_text='Whether this message was proactively generated by the system'),
        ),
        migrations.AddField(
            model_name='assistantmessage',
            name='quick_replies',
            field=models.JSONField(blank=True, default=list, help_text='Quick reply buttons for user interaction (proactive check-ins)'),
        ),
        migrations.AddField(
            model_name='assistantmessage',
            name='quick_reply_used',
            field=models.CharField(blank=True, help_text='ID of the quick reply button that was clicked', max_length=50),
        ),
    ]
