# Generated by Django 4.2.27 on 2026-02-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0021_add_quick_replies_to_assistant_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsight',
            name='time_period',
            field=models.CharField(blank=True, default='', help_text='Time period when insight was generated (early_morning, morning, afternoon, evening)', max_length=20),
        ),
    ]
