# Generated by Django 4.2.27 on 2026-02-25 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0022_add_time_period_to_aiinsight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(help_text="The user's original message")),
                ('assistant_summary', models.TextField(blank=True, help_text='Condensed assistant response (first 300 chars)')),
                ('topic_tags', models.JSONField(blank=True, default=list, help_text='Auto-detected topic tags: faith, health, goals, tasks, journal, etc.')),
                ('page_context_type', models.CharField(blank=True, help_text='Page type when this exchange happened (reading_plan_progress, goal, etc.)', max_length=50)),
                ('embedding', models.JSONField(blank=True, default=list, help_text='OpenAI text-embedding-3-small vector (1536 dimensions)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='ai.assistantconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation Memory',
                'verbose_name_plural': 'Conversation Memories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_conversa_user_id_98e628_idx'), models.Index(fields=['user', 'page_context_type'], name='ai_conversa_user_id_6c66d2_idx')],
            },
        ),
    ]
