# Generated by Django 4.2.27 on 2026-02-28 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0023_conversationmemory'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmemory',
            name='helpfulness_score',
            field=models.FloatField(default=0.0, help_text='Accumulated helpfulness signal (-1.0 to 1.0). Positive = helpful, negative = unhelpful.'),
        ),
        migrations.AddField(
            model_name='conversationmemory',
            name='retrieval_count',
            field=models.PositiveIntegerField(default=0, help_text='How many times this memory has been retrieved for context.'),
        ),
        migrations.AddField(
            model_name='conversationmemory',
            name='was_corrected',
            field=models.BooleanField(default=False, help_text='Whether the user corrected the assistant response in this exchange.'),
        ),
        migrations.CreateModel(
            name='ResponsePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_length', models.CharField(choices=[('concise', 'Concise'), ('balanced', 'Balanced'), ('detailed', 'Detailed')], default='balanced', help_text='Learned preferred response length.', max_length=20)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('unhelpful_count', models.PositiveIntegerField(default=0)),
                ('style_scores', models.JSONField(blank=True, default=dict, help_text='Per-coaching-style effectiveness: {style: {helpful: N, unhelpful: N}}')),
                ('effective_traits', models.JSONField(blank=True, default=dict, help_text='Traits correlated with helpfulness: {trait: score}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Response Preference',
                'verbose_name_plural': 'Response Preferences',
            },
        ),
        migrations.CreateModel(
            name='CorrectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_response', models.TextField(help_text='What CoS originally said (the incorrect/imprecise response).')),
                ('user_correction', models.TextField(help_text="The user's correction message.")),
                ('corrected_truth', models.TextField(blank=True, help_text='Distilled corrected fact (auto-extracted or user-provided).')),
                ('topic_tags', models.JSONField(blank=True, default=list, help_text='Topic tags for retrieval filtering.')),
                ('embedding', models.JSONField(blank=True, default=list, help_text='Embedding of the correction for semantic retrieval.')),
                ('confidence', models.FloatField(default=0.8, help_text='Confidence in the correction (0-1). Higher = more certain.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_message', models.ForeignKey(blank=True, help_text='The assistant message that was corrected.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='ai.assistantmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cos_corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Correction Record',
                'verbose_name_plural': 'Correction Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_correcti_user_id_90eeea_idx')],
            },
        ),
        migrations.CreateModel(
            name='BehavioralPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('time_pattern', 'Time-of-Day Pattern'), ('adherence_pattern', 'Adherence/Consistency Pattern'), ('correlation_pattern', 'Cross-Domain Correlation'), ('frequency_pattern', 'Frequency Pattern'), ('emotional_pattern', 'Emotional Pattern')], max_length=30)),
                ('domain', models.CharField(choices=[('journal', 'Journal'), ('health', 'Health'), ('faith', 'Faith'), ('tasks', 'Tasks'), ('goals', 'Goals'), ('finance', 'Finance'), ('cross_domain', 'Cross-Domain')], max_length=20)),
                ('description', models.TextField(help_text='Human-readable description of the pattern.')),
                ('evidence', models.JSONField(blank=True, default=list, help_text='Data points supporting this pattern (dates, values, etc.).')),
                ('confidence', models.FloatField(default=0.5, help_text='Pattern confidence (0-1). Increases with more evidence.')),
                ('detection_count', models.PositiveIntegerField(default=1, help_text='How many times this pattern has been re-detected.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this pattern is still actively observed.')),
                ('user_confirmed', models.BooleanField(blank=True, help_text='None=pending, True=user confirmed, False=user denied.', null=True)),
                ('first_detected', models.DateTimeField(auto_now_add=True)),
                ('last_confirmed', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Behavioral Pattern',
                'verbose_name_plural': 'Behavioral Patterns',
                'ordering': ['-confidence', '-last_confirmed'],
                'indexes': [models.Index(fields=['user', 'is_active', '-confidence'], name='ai_behavior_user_id_2c7d33_idx'), models.Index(fields=['user', 'domain'], name='ai_behavior_user_id_89fa77_idx')],
            },
        ),
    ]
