# Generated by Django 4.2.27 on 2026-03-03 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0024_persistent_learning_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.TextField(help_text='Base64 encoded image data')),
                ('image_mime_type', models.CharField(help_text="MIME type of the image (e.g., 'image/png')", max_length=50)),
                ('image_expires_at', models.DateTimeField(blank=True, help_text='When the image data should be auto-deleted (72 hours after creation)', null=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Order of the image in the message (0-based)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ai.assistantmessage')),
            ],
            options={
                'verbose_name': 'Message Image',
                'verbose_name_plural': 'Message Images',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['message', 'order'], name='ai_messagei_message_74e700_idx'), models.Index(fields=['image_expires_at'], name='ai_messagei_image_e_dc7bcb_idx')],
            },
        ),
    ]
