# Generated by Django 4.2.27 on 2026-03-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0025_messageimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text Message'), ('insight', 'AI Insight'), ('nudge', 'Accountability Nudge'), ('celebration', 'Celebration'), ('action_suggestion', 'Action Suggestion'), ('reflection_prompt', 'Reflection Prompt'), ('scripture', 'Scripture Reference'), ('priority_list', 'Priority List'), ('state_assessment', 'State Assessment'), ('fallback', 'Fallback Response')], default='text', max_length=20),
        ),
    ]
