# Generated by Django 4.2.27 on 2026-03-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0026_add_fallback_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingstyle',
            name='message_templates',
            field=models.JSONField(blank=True, default=dict, help_text='Persona message templates keyed by message_type → day_status. E.g. {"next_action": {"low": "Start with {action}.", ...}, "day_summary": {"strong": "Great work today.", ...}}'),
        ),
    ]
