# Generated by Django 4.2.27 on 2026-07-07 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistant', '0005_improvementtaskmodel_engineering_category_and_more'),
        ('ai', '0029_prove_orphaned_cos_placeholders'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveScorecardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('window_days', models.PositiveIntegerField(default=30)),
                ('reflection_count', models.PositiveIntegerField(default=0)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Executive Scorecard Snapshot',
                'verbose_name_plural': 'Executive Scorecard Snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReflectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trigger', models.CharField(choices=[('correction', 'User correction'), ('positive', 'Positive signal'), ('ignored', 'Advice ignored'), ('other', 'Other')], default='other', max_length=20)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failure', 'Failure'), ('neutral', 'Neutral')], default='neutral', max_length=12)),
                ('trust_delta', models.CharField(choices=[('increased', 'Increased'), ('maintained', 'Maintained'), ('decreased', 'Decreased')], default='maintained', max_length=12)),
                ('locus', models.CharField(blank=True, choices=[('truth_retrieval', 'Truth Retrieval'), ('reasoning', 'Reasoning'), ('execution', 'Execution'), ('communication', 'Communication'), ('preference', 'Preference'), ('confidence_calibration', 'Confidence Calibration'), ('none', 'None / Positive'), ('indeterminate', 'Indeterminate')], default='none', max_length=32)),
                ('disposition', models.CharField(choices=[('reinforce', 'Reinforce'), ('learn', 'Learn'), ('eio', 'Executive Improvement Opportunity'), ('insufficient_evidence', 'Insufficient Evidence'), ('observe', 'Observe')], default='observe', max_length=24)),
                ('confidence', models.FloatField(default=0.0)),
                ('topic', models.CharField(blank=True, max_length=64)),
                ('user_message', models.TextField(blank=True)),
                ('response_excerpt', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('directive_key', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'verbose_name': 'Reflection Event',
                'verbose_name_plural': 'Reflection Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='correctionrecord',
            name='readback_approved',
            field=models.BooleanField(default=False, help_text='Classifier-approved for CoS prompt read-back (Phase 4 gate).'),
        ),
        migrations.AddIndex(
            model_name='correctionrecord',
            index=models.Index(fields=['user', 'readback_approved'], name='ai_correcti_user_id_56a85b_idx'),
        ),
        migrations.AddField(
            model_name='reflectionevent',
            name='eio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflection_events', to='assistant.improvementtaskmodel'),
        ),
        migrations.AddField(
            model_name='reflectionevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='executivescorecardsnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_scorecards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reflectionevent',
            index=models.Index(fields=['user', '-created_at'], name='ai_reflecti_user_id_60fd31_idx'),
        ),
        migrations.AddIndex(
            model_name='reflectionevent',
            index=models.Index(fields=['user', 'disposition'], name='ai_reflecti_user_id_3fa20b_idx'),
        ),
        migrations.AddIndex(
            model_name='reflectionevent',
            index=models.Index(fields=['user', 'locus'], name='ai_reflecti_user_id_30055a_idx'),
        ),
        migrations.AddIndex(
            model_name='executivescorecardsnapshot',
            index=models.Index(fields=['user', '-created_at'], name='ai_executiv_user_id_c71311_idx'),
        ),
    ]
