# Generated by Django 4.2.27 on 2026-07-09 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0030_executivescorecardsnapshot_reflectionevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnedCommunicationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32)),
                ('key', models.CharField(max_length=48)),
                ('value', models.CharField(max_length=64)),
                ('source', models.CharField(choices=[('explicit', 'Explicit (user asked)'), ('inferred', 'Inferred (learned from patterns)'), ('system_default', 'System default')], default='explicit', help_text='Explicit user requests outrank inferred patterns.', max_length=16)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='high', max_length=8)),
                ('evidence_count', models.PositiveIntegerField(default=1)),
                ('last_evidence_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_comm_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'key'],
                'indexes': [models.Index(fields=['user', 'active'], name='ai_learnedc_user_id_0193d8_idx')],
                'unique_together': {('user', 'category', 'key')},
            },
        ),
    ]
