# Generated by Django 4.2.27 on 2026-07-09 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0031_learnedcommunicationpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('surface', models.CharField(blank=True, default='', max_length=32)),
                ('kind', models.CharField(choices=[('truth', 'Truth provided'), ('action', 'Action requested/executed'), ('preference', 'Preference written'), ('response', 'Response returned')], max_length=16)),
                ('tool_name', models.CharField(blank=True, default='', max_length=64)),
                ('args', models.JSONField(blank=True, default=dict)),
                ('result_status', models.CharField(blank=True, default='', max_length=32)),
                ('result_digest', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_call_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'turn_id'], name='ai_toolcall_user_id_c8a87f_idx'), models.Index(fields=['created_at'], name='ai_toolcall_created_af38a3_idx')],
            },
        ),
    ]
