# Generated by Django 4.2.27 on 2026-07-20 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0033_alter_assistantmessage_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructuredImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_domain', models.CharField(db_index=True, max_length=32)),
                ('intent', models.CharField(blank=True, default='', max_length=64)),
                ('source_artifact_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('source', models.CharField(blank=True, default='', max_length=120)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('manifest', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_import_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'target_domain'], name='ai_structur_user_id_ee24ef_idx'), models.Index(fields=['source_artifact_id', 'target_domain'], name='ai_structur_source__7c01b9_idx')],
            },
        ),
    ]
