# Generated by Django 4.2.27 on 2026-07-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0034_structuredimportrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmessage',
            name='confirmation',
            field=models.JSONField(blank=True, help_text='Rich Confirmation card for deterministic-action confirmation.', null=True),
        ),
    ]
