# Generated by Django 4.2.27 on 2026-07-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0035_assistantmessage_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmessage',
            name='attachment_receipts',
            field=models.JSONField(blank=True, default=list, help_text="Attachment receipts shown on the user's sent message (filename/kind/state)."),
        ),
    ]
