# Generated by Django 4.2.27 on 2026-07-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0036_assistantmessage_attachment_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcalllog',
            name='conversation_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='toolcalllog',
            index=models.Index(fields=['user', 'conversation_id'], name='ai_toolcall_user_id_711209_idx'),
        ),
    ]
