# Generated by Django 4.2.27 on 2026-08-17 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0037_toolcalllog_conversation_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField(db_index=True)),
                ('topic', models.CharField(max_length=280)),
                ('subject_ref', models.CharField(blank=True, default='', max_length=120)),
                ('origin', models.CharField(choices=[('user_requested', 'User requested'), ('assistant_proposed', 'Assistant proposed')], default='user_requested', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivering', 'Delivering'), ('delivered', 'Delivered'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='ai.assistantconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_follow_ups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation Follow-Up',
                'verbose_name_plural': 'Conversation Follow-Ups',
                'ordering': ['due_at'],
                'indexes': [models.Index(fields=['user', 'status', 'due_at'], name='ai_conversa_user_id_a0ee3f_idx'), models.Index(fields=['status', 'due_at'], name='ai_conversa_status_d0d775_idx')],
            },
        ),
    ]
