# Generated by Django 4.2.27 on 2026-08-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0041_cleanup_object_reveal_artifacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingstyle',
            name='operational_defaults',
            field=models.JSONField(blank=True, default=dict, help_text='SUGGESTED Operational Preference defaults (Contract 1.4). Applied ONLY where the user has expressed no explicit setting. A persona NEVER overrides an explicit user choice. Keys must be canonical preference keys.'),
        ),
        migrations.AddField(
            model_name='coachingstyle',
            name='voice_attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Reusable VOICE attributes (Contract 1.2) - internal, never shown to the customer as sliders. Recognized keys: register, warmth, directness, humor, formality, verbosity_bias, signature_expressions (list). Used to compose the persona instruction block so N personas do not need N hand-written essays.'),
        ),
    ]
