# Generated by Django 4.2.27 on 2026-08-19 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0043_m1_persona_registry_reconciliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], db_index=True, default='active', max_length=12)),
                ('topic_states', models.JSONField(blank=True, default=dict, help_text='{topic: {state, at}} — outcomes the USER established. Emergent topic labels are accepted as-is; no deploy is needed for a new area of life.')),
                ('turn_count', models.PositiveIntegerField(default=0)),
                ('facts_recorded', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, help_text='The conversation this session is being conducted in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to='ai.assistantconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview Session',
                'ordering': ['-last_active_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='ai_intervie_user_id_efd48e_idx')],
            },
        ),
    ]
