# Generated by Django 4.2.27 on 2026-08-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0044_interviewsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealLLMAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, help_text='Opaque id exported as WLJ_LLM_RUN_ID for the authorized run.', max_length=64, unique=True)),
                ('reason', models.TextField(help_text="What Danny approved, in his words — e.g. 'one persona smoke test'.")),
                ('calls_authorized', models.PositiveIntegerField(help_text='Hard ceiling. Never raised — mint a new authorization instead.')),
                ('calls_remaining', models.PositiveIntegerField(help_text='Decremented atomically at the admission seam. Zero means STOP.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Authorization naturally lapses; an unused budget is not permanent.')),
                ('note', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Real LLM Authorization',
                'verbose_name_plural': 'Real LLM Authorizations',
                'ordering': ['-created_at'],
            },
        ),
    ]
