# Generated by Django 4.2.27 on 2026-08-28 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0045_real_llm_authorization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionConfirmation',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True, default='')),
                ('authorization_line', models.CharField(blank=True, default='', max_length=300)),
                ('view', models.JSONField(blank=True, null=True)),
                ('conversation_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('source_artifact_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executing', 'Executing (claimed)'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('choice', models.CharField(blank=True, default='', max_length=32)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_confirmations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Action Confirmation',
                'indexes': [models.Index(fields=['user', 'status'], name='ai_actionco_user_id_4fa435_idx'), models.Index(fields=['user', 'conversation_id', 'status'], name='ai_actionco_user_id_7b1af6_idx')],
            },
        ),
    ]
