"""
E3 — Explain Templates.

Template-based explanation generators for each intelligence output type.
Produces human-readable explanations without AI calls.
"""

import logging

logger = logging.getLogger(__name__)


def explain_guidance(guidance_item):
    """
    Generate explanation for a PGE GuidanceItem.

    Args:
        guidance_item: GuidanceItem instance.

    Returns:
        (explanation: str, confidence_explanation: str or None)
    """
    source_labels = {
        "prie_prediction": "a predictive model",
        "pie_insight": "a pattern detected in your data",
        "sae_state": "your current state snapshot",
        "composite": "multiple intelligence sources",
    }
    source_label = source_labels.get(guidance_item.source, "intelligence analysis")

    rule_label = guidance_item.guidance_type.replace("_", " ") if guidance_item.guidance_type else "analysis"

    explanation = (
        f"This guidance was generated by the {rule_label} rule, "
        f"based on {source_label}."
    )

    if guidance_item.module:
        explanation += f" It relates to your {guidance_item.module} data."

    priority_labels = {
        1: "This is marked critical — immediate attention recommended.",
        2: "This is high priority — review when you can.",
    }
    if guidance_item.priority in priority_labels:
        explanation += f" {priority_labels[guidance_item.priority]}"

    # Confidence explanation
    confidence_explanation = None
    if guidance_item.confidence_score is not None:
        conf = guidance_item.confidence_score
        if conf >= 0.8:
            confidence_explanation = (
                f"Confidence is {conf:.0%} — strong signal from your data. "
                "Multiple data points support this conclusion."
            )
        elif conf >= 0.5:
            confidence_explanation = (
                f"Confidence is {conf:.0%} — moderate signal. "
                "Some supporting data, but more data would strengthen this."
            )
        else:
            confidence_explanation = (
                f"Confidence is {conf:.0%} — early signal. "
                "This is based on limited data and may change as more data arrives."
            )

    return explanation, confidence_explanation


def explain_briefing(daily_briefing):
    """
    Generate explanation for a DBE DailyBriefing.

    Args:
        daily_briefing: DailyBriefing instance.

    Returns:
        (explanation: str, confidence_explanation: str or None)
    """
    parts = []

    guidance = daily_briefing.guidance_snapshot or {}
    insights = daily_briefing.insight_snapshot or {}
    predictions = daily_briefing.prediction_snapshot or {}

    g_count = guidance.get("count", 0)
    i_count = insights.get("count", 0)
    p_count = predictions.get("count", 0)

    parts.append(
        f"This briefing was generated on {daily_briefing.briefing_date} "
        f"by aggregating your intelligence data."
    )

    sources = []
    if g_count:
        sources.append(f"{g_count} guidance item{'s' if g_count > 1 else ''}")
    if i_count:
        sources.append(f"{i_count} insight{'s' if i_count > 1 else ''}")
    if p_count:
        sources.append(f"{p_count} prediction{'s' if p_count > 1 else ''}")

    if sources:
        parts.append(f"It includes: {', '.join(sources)}.")
    else:
        parts.append("No active intelligence items were found — the briefing reflects your current state.")

    explanation = " ".join(parts)
    return explanation, None


def explain_weekly_report(weekly_report):
    """
    Generate explanation for a WIRE WeeklyIntelligenceReport.

    Args:
        weekly_report: WeeklyIntelligenceReport instance.

    Returns:
        (explanation: str, confidence_explanation: str or None)
    """
    parts = []

    parts.append(
        f"This weekly report covers {weekly_report.week_start_date} to "
        f"{weekly_report.week_end_date}."
    )

    # Count items
    insights = weekly_report.insight_snapshot or {}
    predictions = weekly_report.prediction_snapshot or {}
    guidance = weekly_report.guidance_snapshot or {}
    deltas = weekly_report.state_delta_snapshot or {}

    i_count = len(insights.get("insights", []))
    p_count = len(predictions.get("predictions", []))
    g_count = len(guidance.get("guidance", []))
    d_count = len(deltas.get("deltas", []))

    sources = []
    if i_count:
        sources.append(f"{i_count} insight{'s' if i_count > 1 else ''}")
    if p_count:
        sources.append(f"{p_count} prediction{'s' if p_count > 1 else ''}")
    if g_count:
        sources.append(f"{g_count} guidance item{'s' if g_count > 1 else ''}")
    if d_count:
        sources.append(f"{d_count} state change{'s' if d_count > 1 else ''}")

    if sources:
        parts.append(f"The report was built from: {', '.join(sources)}.")
        parts.append("Items were selected by priority and ranked by confidence.")
    else:
        parts.append("No significant intelligence activity was detected this week.")

    # Learning engagement
    learning = weekly_report.learning_snapshot or {}
    resp = learning.get("responsiveness_score")
    if resp is not None:
        parts.append(
            f"Your guidance engagement score this week was {resp:.0%}."
        )

    explanation = " ".join(parts)
    return explanation, None
