# Generated by Django 5.2.10 on 2026-01-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0002_safetylimitoverride"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="improvementtaskmodel",
            new_name="assistant_i_status_a738da_idx",
            old_name="assistant_i_status_4b7e8c_idx",
        ),
        migrations.RenameIndex(
            model_name="improvementtaskmodel",
            new_name="assistant_i_gap_typ_b098b3_idx",
            old_name="assistant_i_gap_typ_7a3d12_idx",
        ),
        migrations.RenameIndex(
            model_name="improvementtaskmodel",
            new_name="assistant_i_severit_affd01_idx",
            old_name="assistant_i_severit_f2c891_idx",
        ),
        migrations.RenameIndex(
            model_name="improvementtaskmodel",
            new_name="assistant_i_created_b97181_idx",
            old_name="assistant_i_created_d1e456_idx",
        ),
        migrations.RenameIndex(
            model_name="improvementtaskmodel",
            new_name="assistant_i_require_5c93dc_idx",
            old_name="assistant_i_require_a9b3c7_idx",
        ),
        migrations.AddField(
            model_name="improvementtaskmodel",
            name="approval_token",
            field=models.CharField(
                blank=True,
                help_text="Secure one-time token for email-based approval",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="improvementtaskmodel",
            name="approval_token_created_at",
            field=models.DateTimeField(
                blank=True, help_text="When the approval token was generated", null=True
            ),
        ),
        migrations.AddField(
            model_name="improvementtaskmodel",
            name="rejected_at",
            field=models.DateTimeField(
                blank=True, help_text="When the task was rejected", null=True
            ),
        ),
        migrations.AddField(
            model_name="improvementtaskmodel",
            name="rejection_reason",
            field=models.TextField(
                blank=True, help_text="Reason for rejecting the task"
            ),
        ),
        migrations.AddField(
            model_name="improvementtaskmodel",
            name="rollback_reason",
            field=models.TextField(
                blank=True, help_text="Reason for rolling back the task"
            ),
        ),
        migrations.AddField(
            model_name="improvementtaskmodel",
            name="rolled_back_at",
            field=models.DateTimeField(
                blank=True, help_text="When the task was rolled back", null=True
            ),
        ),
        migrations.AlterField(
            model_name="improvementtaskmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("pending_approval", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("in_progress", "In Progress"),
                    ("testing", "Testing"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                    ("rolled_back", "Rolled Back"),
                ],
                default="new",
                help_text="Current status in the task lifecycle",
                max_length=20,
            ),
        ),
    ]
