# Generated by Django 5.2.10 on 2026-01-10 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_rename_assistant_i_status_4b7e8c_idx_assistant_i_status_a738da_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='improvementtaskmodel',
            name='triggered_by_user',
            field=models.ForeignKey(blank=True, help_text='User whose query triggered this improvement task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_improvement_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
