# Generated by Django 4.2.27 on 2026-07-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_add_triggered_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvementtaskmodel',
            name='engineering_category',
            field=models.CharField(blank=True, choices=[('architecture', 'Architecture'), ('retrieval', 'Retrieval'), ('state', 'State'), ('serialization', 'Serialization'), ('pipeline', 'Pipeline'), ('telemetry', 'Telemetry'), ('ui', 'UI'), ('dead_code', 'Dead Code'), ('other', 'Other')], help_text='EIO: what kind of work fixes it (the remedy).', max_length=20),
        ),
        migrations.AddField(
            model_name='improvementtaskmodel',
            name='evidence',
            field=models.JSONField(blank=True, default=dict, help_text='EIO: immutable reconstruction evidence bundle.'),
        ),
        migrations.AddField(
            model_name='improvementtaskmodel',
            name='functional_locus',
            field=models.CharField(blank=True, choices=[('truth_retrieval', 'Truth Retrieval'), ('reasoning', 'Reasoning'), ('execution', 'Execution'), ('confidence_calibration', 'Confidence Calibration'), ('capability', 'Capability Gap')], help_text="EIO: which of Beth's faculties is implicated (the symptom).", max_length=32),
        ),
        migrations.AddField(
            model_name='improvementtaskmodel',
            name='recurrence_count',
            field=models.PositiveIntegerField(default=1, help_text='EIO: how many materially-similar opportunities were observed.'),
        ),
        migrations.AddField(
            model_name='improvementtaskmodel',
            name='source',
            field=models.CharField(choices=[('gap_detector', 'Gap Detector'), ('reflection', 'Executive Reflection')], default='gap_detector', help_text='Producer of this row: the gap detector or Executive Reflection.', max_length=20),
        ),
        migrations.AlterField(
            model_name='improvementtaskmodel',
            name='gap_type',
            field=models.CharField(choices=[('unknown_data_type', 'Unknown Data Type'), ('missing_keywords', 'Missing Keywords'), ('no_data_method', 'No Data Method'), ('unsupported_query_pattern', 'Unsupported Query Pattern'), ('reflection_eio', 'Executive Improvement Opportunity')], help_text='Type of knowledge gap that triggered this task', max_length=50),
        ),
    ]
