# Generated by Django 4.2.27 on 2026-02-20 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purpose', '0006_alter_habitgoal_measurement_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('is_all_day', models.BooleanField(default=False)),
                ('event_kind', models.CharField(choices=[('manual', 'Manual'), ('deadline_marker', 'Deadline Marker'), ('execution_block', 'Execution Block'), ('external_readonly', 'External (Read-Only)')], default='manual', max_length=20)),
                ('source_type', models.CharField(choices=[('none', 'None (Manual)'), ('task', 'Task'), ('goal', 'Goal'), ('goal_milestone', 'Goal Milestone'), ('habit', 'Habit'), ('life_event', 'Life Event'), ('external', 'External')], default='none', max_length=20)),
                ('source_id', models.CharField(blank=True, help_text='PK of the source object (stored as string for flexibility)', max_length=100)),
                ('is_protected', models.BooleanField(default=False, help_text='Used by Habit Protection Layer — prevents silent overwrites')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='scheduled', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='purpose.lifedomain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_dt'],
            },
        ),
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('byweekday', models.JSONField(blank=True, default=list, help_text='List of ISO weekday numbers (1=Mon..7=Sun)')),
                ('interval', models.PositiveIntegerField(default=1)),
                ('until_dt', models.DateTimeField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('timezone', models.CharField(default='America/Chicago', max_length=50)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence', to='calendar_engine.calendarevent')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarOverrideLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='override_logs_as_moved', to='calendar_engine.calendarevent')),
                ('overridden_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='override_logs_as_overridden', to='calendar_engine.calendarevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_override_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecurrenceException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_start_dt', models.DateTimeField(help_text='The original occurrence start that this exception replaces')),
                ('new_start_dt', models.DateTimeField(blank=True, null=True)),
                ('new_end_dt', models.DateTimeField(blank=True, null=True)),
                ('is_canceled', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_exceptions', to='calendar_engine.calendarevent')),
            ],
            options={
                'unique_together': {('event', 'original_start_dt')},
            },
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['user', 'start_dt'], name='calendar_en_user_id_40b6db_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['user', 'source_type', 'source_id'], name='calendar_en_user_id_799b6f_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['user', 'status'], name='calendar_en_user_id_0925ea_idx'),
        ),
    ]
