# Generated by Django 4.2.27 on 2026-02-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash for assistant-path duplicate prevention', max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.UniqueConstraint(fields=('user', 'title', 'start_dt'), name='unique_user_title_start'),
        ),
    ]
