# Generated by Django 4.2.27 on 2026-02-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_engine', '0002_phase9_idempotency_and_unique_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='calendarevent',
            name='unique_user_title_start',
        ),
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.UniqueConstraint(fields=('user', 'idempotency_key'), name='uq_calendar_event_user_idempotency'),
        ),
    ]
