# Generated by Django 4.2.27 on 2026-02-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_engine', '0004_phase9_idempotency_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft-delete timestamp. Set when status transitions to canceled.', null=True),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['user', 'deleted_at'], name='calendar_en_user_id_c76388_idx'),
        ),
    ]
