# Generated by Django 4.2.27 on 2026-02-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_engine', '0005_add_deleted_at_and_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['user', 'title', 'start_dt', 'end_dt'], name='idx_cal_event_semantic_dup'),
        ),
    ]
