# Generated by Django 4.2.27 on 2026-02-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_engine', '0006_add_semantic_duplicate_index'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='calendarevent',
            name='uq_calendar_event_user_idempotency',
        ),
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'idempotency_key'), name='uq_calendar_event_user_idempotency'),
        ),
    ]
