# Generated by Django 4.2.27 on 2026-02-25 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendar_engine', '0007_fix_idempotency_constraint_exclude_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclinedSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=20)),
                ('source_id', models.CharField(max_length=100)),
                ('declined_date', models.DateField(help_text='The date the suggestion was declined for')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declined_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'source_type', 'source_id', 'declined_date')},
            },
        ),
    ]
