# Generated by Django 4.2.27 on 2026-03-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_engine', '0008_declinedsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='commitment_level',
            field=models.CharField(choices=[('optional', 'Optional'), ('important', 'Important'), ('non_negotiable', 'Non-Negotiable')], default='important', help_text='Importance classification. Non-negotiable commitments are never compensable in the compensatory reasoning engine.', max_length=20),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='source_type',
            field=models.CharField(choices=[('none', 'None (Manual)'), ('task', 'Task'), ('goal', 'Goal'), ('goal_milestone', 'Goal Milestone'), ('habit', 'Habit'), ('life_event', 'Life Event'), ('external', 'External'), ('medicine_schedule', 'Medicine Schedule'), ('faith_routine', 'Faith Routine'), ('workout_schedule', 'Workout Schedule')], default='none', max_length=20),
        ),
    ]
