# Generated by Django 4.2.27 on 2026-03-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_engine', '0009_calendarevent_commitment_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='commitment_level',
            field=models.CharField(choices=[('foundational', 'Foundational'), ('important', 'Important'), ('flexible', 'Flexible')], default='important', help_text='Importance classification. Non-negotiable commitments are never compensable in the compensatory reasoning engine.', max_length=20),
        ),
    ]
