# Generated by Django 4.2.27 on 2026-07-07 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendar_engine', '0010_normalize_commitment_to_importance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Work', max_length=200)),
                ('kind', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='unavailable', help_text='Whether this block marks time as available or unavailable.', max_length=12)),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('frequency', models.CharField(blank=True, choices=[('', 'Does not repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='', max_length=10)),
                ('byweekday', models.JSONField(blank=True, default=list, help_text='ISO weekday numbers (1=Mon..7=Sun) for weekly recurrence.')),
                ('interval', models.PositiveIntegerField(default=1)),
                ('until_dt', models.DateTimeField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('timezone', models.CharField(default='America/Chicago', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_dt'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_start_dt', models.DateTimeField(help_text='The original occurrence start this exception replaces.')),
                ('new_start_dt', models.DateTimeField(blank=True, null=True)),
                ('new_end_dt', models.DateTimeField(blank=True, null=True)),
                ('is_canceled', models.BooleanField(default=False)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='calendar_engine.availabilityblock')),
            ],
            options={
                'unique_together': {('block', 'original_start_dt')},
            },
        ),
        migrations.AddIndex(
            model_name='availabilityblock',
            index=models.Index(fields=['user', 'start_dt'], name='calendar_en_user_id_55b27a_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityblock',
            index=models.Index(fields=['user', 'is_active', 'deleted_at'], name='calendar_en_user_id_4a0dbf_idx'),
        ),
    ]
