# Generated by Django 4.2.27 on 2026-07-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_engine', '0011_availabilityblock_availabilityexception_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityblock',
            name='exceptions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='AvailabilityException',
        ),
    ]
