# Generated by Django 5.2.9 on 2025-12-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminHelpTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "context_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for admin context (e.g., ADMIN_AI_PROMPTS, ADMIN_THEMES)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "help_id",
                    models.SlugField(
                        help_text="URL-friendly identifier (e.g., admin-ai-prompts, admin-themes)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Help topic title (e.g., 'Configuring AI Prompts')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of what this admin help covers",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Full technical help content (supports Markdown)"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Category (e.g., 'AI Configuration', 'User Management', 'System Settings')",
                        max_length=50,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order within category (lower = first)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Show this admin help topic"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_topics",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Related admin help topics to suggest",
                        to="help.adminhelptopic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Help Topic",
                "verbose_name_plural": "Admin Help Topics",
                "ordering": ["category", "order", "title"],
            },
        ),
        migrations.CreateModel(
            name="HelpTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "context_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier matching HELP_CONTEXT_ID (e.g., DASHBOARD_HOME, HEALTH_WORKOUT_CREATE)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "help_id",
                    models.SlugField(
                        help_text="URL-friendly identifier (e.g., dashboard-overview, health-log-workout)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Help topic title (e.g., 'How to Log a Workout')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of what this help covers",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Full help content with step-by-step instructions (supports Markdown)"
                    ),
                ),
                (
                    "app_name",
                    models.CharField(
                        blank=True,
                        help_text="App this help belongs to (e.g., dashboard, health, journal)",
                        max_length=50,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order within app (lower = first)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Show this help topic"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_topics",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Related help topics to suggest",
                        to="help.helptopic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Help Topic",
                "verbose_name_plural": "Help Topics",
                "ordering": ["app_name", "order", "title"],
            },
        ),
    ]
