# Generated by Django 5.2.9 on 2025-12-27 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'Getting Started')",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief description of this category"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="📚", help_text="Emoji icon for display", max_length=10
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order (lower = first)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Show this category"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Help Category",
                "verbose_name_plural": "Help Categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="HelpArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Article title", max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=200, unique=True
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        help_text="Short 1-2 sentence summary for chat responses",
                        max_length=300,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Full help content (Markdown supported)"
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("general", "General / App-wide"),
                            ("dashboard", "Dashboard"),
                            ("journal", "Journal"),
                            ("health", "Health"),
                            ("faith", "Faith"),
                            ("life", "Life"),
                            ("purpose", "Purpose"),
                            ("settings", "Settings"),
                        ],
                        default="general",
                        help_text="Which app module this relates to",
                        max_length=20,
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated keywords for search (e.g., 'login, password, account')",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Publish this article"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order within category"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_articles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Related articles to suggest",
                        to="help.helparticle",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Category this article belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="help.helpcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Help Article",
                "verbose_name_plural": "Help Articles",
                "ordering": ["category", "sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="HelpConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "context_module",
                    models.CharField(
                        blank=True,
                        help_text="Module user was viewing when starting chat",
                        max_length=20,
                    ),
                ),
                (
                    "context_url",
                    models.CharField(
                        blank=True,
                        help_text="URL user was on when starting chat",
                        max_length=500,
                    ),
                ),
                (
                    "emailed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When conversation was emailed to user",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="help_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Help Conversation",
                "verbose_name_plural": "Help Conversations",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="HelpMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="Message text")),
                (
                    "is_user",
                    models.BooleanField(
                        default=True,
                        help_text="True if from user, False if from assistant",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="help.helpconversation",
                    ),
                ),
                (
                    "source_articles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Articles used to generate this response",
                        to="help.helparticle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Help Message",
                "verbose_name_plural": "Help Messages",
                "ordering": ["created_at"],
            },
        ),
    ]
