# Generated by Django 4.2.27 on 2026-01-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_add_wlj_assistant_chat_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_id', models.SlugField(help_text="Unique identifier (e.g., 'weight-tracking', 'journal-new')", max_length=100, unique=True)),
                ('name', models.CharField(help_text="Friendly name shown to user (e.g., 'Weight Tracking')", max_length=100)),
                ('path_description', models.CharField(help_text="Navigation path (e.g., 'Health → Weight')", max_length=200)),
                ('explanation', models.TextField(blank=True, help_text='Brief description of what user can do there')),
                ('url', models.CharField(help_text="Direct URL path (e.g., '/health/weight/')", max_length=300)),
                ('keywords', models.TextField(help_text="Comma-separated keywords/phrases for matching (e.g., 'weight, log weight, track weight, weigh myself')")),
                ('module', models.CharField(blank=True, help_text='App module (health, journal, life, purpose, ai, etc.)', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order for fallback suggestions')),
                ('is_active', models.BooleanField(default=True, help_text='Include in teaching tool responses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teaching Destination',
                'verbose_name_plural': 'Teaching Destinations',
                'ordering': ['module', 'sort_order', 'name'],
            },
        ),
    ]
