# Generated by Django 4.2.27 on 2026-07-02 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('relationship_label', models.CharField(blank=True, max_length=120)),
                ('permission_level', models.CharField(choices=[('view', 'Can see'), ('add', 'Can add'), ('manage', 'Can help manage')], default='add', max_length=10)),
                ('invite_status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('declined', 'Declined'), ('expired', 'Expired')], db_index=True, default='invited', max_length=10)),
                ('invite_token', models.CharField(blank=True, db_index=True, max_length=64)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('letter', 'Letter'), ('other', 'Other')], db_index=True, default='photo', max_length=12)),
                ('file', models.FileField(blank=True, null=True, upload_to='legacy/media/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('taken_on', models.DateField(blank=True, help_text='When the media was captured', null=True)),
                ('source_note', models.CharField(blank=True, help_text="Provenance: where/whom this came from (e.g. 'Mom's box')", max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Media',
                'ordering': ['-taken_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True, help_text='The story text or voice transcript')),
                ('entry_type', models.CharField(choices=[('memory', 'Memory'), ('story', 'Story'), ('person', 'Someone important'), ('place', 'A place'), ('event', 'An event'), ('object', 'An object'), ('tradition', 'A tradition'), ('lesson', 'A lesson'), ('saying', 'A saying'), ('brain_dump', 'Brain dump'), ('record_together', 'Recorded together')], db_index=True, default='memory', max_length=20)),
                ('entry_state', models.CharField(choices=[('draft', 'Just for me'), ('legacy', 'In your Legacy'), ('shared', 'Shared')], db_index=True, default='draft', max_length=10)),
                ('occurred_on', models.DateField(blank=True, null=True)),
                ('occurred_precision', models.CharField(choices=[('exact', 'Exact date'), ('month', 'Month'), ('year', 'Year'), ('approx', 'Approximate'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('source_kind', models.CharField(choices=[('owner', 'The keeper'), ('contributor', 'A family contributor')], default='owner', max_length=12)),
                ('provenance_note', models.CharField(blank=True, max_length=255)),
                ('significance', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Memories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('display_name', models.CharField(db_index=True, max_length=200)),
                ('also_known_as', models.CharField(blank=True, help_text='Nicknames / other names (comma-separated)', max_length=200)),
                ('relationship_label', models.CharField(blank=True, help_text="Relationship to the keeper (e.g. 'your father')", max_length=120)),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True)),
                ('death_year', models.PositiveIntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, help_text="A 'who they were' narrative")),
                ('significance', models.PositiveSmallIntegerField(default=0)),
                ('primary_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_people', to='legacy.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'People',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('relationship_type', models.CharField(help_text="e.g. 'father of', 'mentored by', 'married to'", max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('started_year', models.PositiveIntegerField(blank=True, null=True)),
                ('ended_year', models.PositiveIntegerField(blank=True, null=True)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='legacy.person')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='legacy.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['from_person__display_name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('location_text', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, help_text="A 'what it was' narrative")),
                ('significance', models.PositiveSmallIntegerField(default=0)),
                ('primary_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_places', to='legacy.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('output_type', models.CharField(choices=[('memoir', 'Memoir'), ('autobiography', 'Autobiography'), ('childrens_book', "Children's book"), ('picture_book', 'Picture book'), ('family_history', 'Family history'), ('timeline', 'Timeline'), ('encyclopedia', 'Character encyclopedia'), ('museum', 'Digital museum'), ('photo_album', 'Photo album'), ('podcast', 'Podcast script'), ('documentary', 'Documentary outline')], max_length=20)),
                ('scope_kind', models.CharField(choices=[('whole_life', 'Your whole life'), ('person', 'A person'), ('place', 'A place'), ('period', 'A time period'), ('collection', 'A collection')], default='whole_life', max_length=12)),
                ('audience', models.CharField(choices=[('adults', 'For adults'), ('child', 'For a child'), ('family', 'For the family')], default='family', max_length=10)),
                ('generation_status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='draft', max_length=12)),
                ('summary', models.TextField(blank=True)),
                ('scope_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outputs', to='legacy.person')),
                ('scope_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outputs', to='legacy.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoryPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legacy.memory')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legacy.place')),
            ],
            options={
                'unique_together': {('memory', 'place')},
            },
        ),
        migrations.CreateModel(
            name='MemoryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=120)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legacy.memory')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legacy.person')),
            ],
            options={
                'unique_together': {('memory', 'person')},
            },
        ),
        migrations.AddField(
            model_name='memory',
            name='attributed_to',
            field=models.ForeignKey(blank=True, help_text='Whose memory/voice this is', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributed_memories', to='legacy.person'),
        ),
        migrations.AddField(
            model_name='memory',
            name='contributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='legacy.contributor'),
        ),
        migrations.AddField(
            model_name='memory',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='memories', to='legacy.media'),
        ),
        migrations.AddField(
            model_name='memory',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='memories', through='legacy.MemoryPerson', to='legacy.person'),
        ),
        migrations.AddField(
            model_name='memory',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='memories', through='legacy.MemoryPlace', to='legacy.place'),
        ),
        migrations.AddField(
            model_name='memory',
            name='primary_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_memories', to='legacy.media'),
        ),
        migrations.AddField(
            model_name='memory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contributor',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_contributor', to='legacy.person'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', 'entry_state', 'status'], name='legacy_memo_user_id_0fb38d_idx'),
        ),
    ]
