# Generated by Django 4.2.27 on 2026-07-02 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legacy', '0002_legacy_module_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_edited_memories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MemoryRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('entry_state', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_memory_revisions', to=settings.AUTH_USER_MODEL)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='legacy.memory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
