# Generated by Django 4.2.27 on 2026-07-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0003_memory_updated_by_memoryrevision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='audience',
            field=models.CharField(choices=[('me', 'Me'), ('family', 'Family'), ('children', 'Children'), ('grandchildren', 'Grandchildren'), ('public', 'Public')], default='family', max_length=14),
        ),
    ]
