# Generated by Django 4.2.27 on 2026-07-02 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0005_legacy_nav_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryDiscovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('person', 'Person'), ('relationship', 'Relationship'), ('place', 'Place'), ('human_time', 'Human time'), ('calendar_time', 'Calendar time'), ('life_stage', 'Life stage'), ('relative_time', 'Relative time'), ('event', 'Event'), ('quote', 'Quote'), ('artifact', 'Artifact'), ('media_ref', 'Media reference'), ('theme', 'Theme'), ('value', 'Value'), ('tradition', 'Tradition'), ('emotion', 'Emotion')], db_index=True, max_length=16)),
                ('label', models.CharField(max_length=500)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=6)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='proposed', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('linked_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discoveries', to='legacy.person')),
                ('linked_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discoveries', to='legacy.place')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoveries', to='legacy.memory')),
            ],
            options={
                'ordering': ['status', 'kind', 'id'],
            },
        ),
    ]
