# Generated by Django 4.2.27 on 2026-07-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0006_memorydiscovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='discovery_prompts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
