# Generated by Django 4.2.27 on 2026-07-03 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legacy', '0007_memory_discovery_prompts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('source_name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('chatgpt', 'ChatGPT conversation'), ('claude', 'Claude conversation'), ('word', 'Word document'), ('pdf', 'PDF'), ('journal', 'Journal'), ('memoir', 'Existing memoir'), ('plain_text', 'Plain text'), ('other', 'Other')], default='other', max_length=12)),
                ('import_status', models.CharField(choices=[('parsed', 'Parsed'), ('importing', 'Importing'), ('complete', 'Complete'), ('failed', 'Failed')], default='parsed', max_length=12)),
                ('total_chunks', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Import batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='memory',
            name='import_chunk',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='legacy.importbatch'),
        ),
        migrations.CreateModel(
            name='ImportChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('source_ref', models.CharField(blank=True, help_text="e.g. 'message 7'", max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('imported', 'Imported'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='legacy.importbatch')),
                ('memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_chunks', to='legacy.memory')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('batch', 'index')},
            },
        ),
    ]
