# Generated by Django 4.2.27 on 2026-07-03 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legacy', '0008_importbatch_memory_import_chunk_memory_import_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorydiscovery',
            name='kind',
            field=models.CharField(choices=[('person', 'Person'), ('relationship', 'Relationship'), ('place', 'Place'), ('milestone', 'Life milestone'), ('human_time', 'Human time'), ('calendar_time', 'Calendar time'), ('life_stage', 'Life stage'), ('relative_time', 'Relative time'), ('event', 'Event'), ('quote', 'Quote'), ('artifact', 'Artifact'), ('media_ref', 'Media reference'), ('theme', 'Theme'), ('value', 'Value'), ('tradition', 'Tradition'), ('emotion', 'Emotion')], db_index=True, max_length=16),
        ),
        migrations.CreateModel(
            name='LifeMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('kind', models.CharField(choices=[('marriage', 'Marriage'), ('home', 'Home'), ('education', 'Education'), ('military', 'Military'), ('career', 'Career'), ('birth', 'Birth'), ('death', 'Loss'), ('faith', 'Faith'), ('health', 'Health'), ('relocation', 'Move'), ('travel', 'Travel'), ('business', 'Business'), ('relationship', 'Relationship'), ('other', 'Milestone')], default='other', max_length=14)),
                ('year', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('significance', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Life milestone',
                'verbose_name_plural': 'Life milestones',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.AddField(
            model_name='memory',
            name='milestones',
            field=models.ManyToManyField(blank=True, related_name='memories', to='legacy.lifemilestone'),
        ),
        migrations.AddField(
            model_name='memorydiscovery',
            name='linked_milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discoveries', to='legacy.lifemilestone'),
        ),
    ]
