# Generated by Django 4.2.27 on 2026-07-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0009_alter_memorydiscovery_kind_lifemilestone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorydiscovery',
            name='kind',
            field=models.CharField(choices=[('person', 'Person'), ('relationship', 'Relationship'), ('place', 'Place'), ('milestone', 'Life milestone'), ('human_time', 'Human time'), ('calendar_time', 'Calendar time'), ('life_stage', 'Life stage'), ('relative_time', 'Relative time'), ('event', 'Event'), ('quote', 'Quote'), ('artifact', 'Artifact'), ('media_ref', 'Media reference'), ('existing_media', 'Media you already have'), ('theme', 'Theme'), ('value', 'Value'), ('tradition', 'Tradition'), ('emotion', 'Emotion')], db_index=True, max_length=16),
        ),
    ]
