# Generated by Django 4.2.27 on 2026-07-04 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legacy', '0011_memory_cleanup_original_body_place_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importchunk',
            name='chunk_kind',
            field=models.CharField(choices=[('story', 'Story'), ('journal_entry', 'Journal entry'), ('letter', 'Letter'), ('fact', 'Fact'), ('person', 'Person'), ('relationship_alias', 'Relationship alias'), ('place', 'Place'), ('milestone', 'Life milestone'), ('timeline_event', 'Timeline event'), ('quote', 'Quote'), ('artifact', 'Artifact'), ('media_ref', 'Media reference'), ('biography', 'Biography'), ('description', 'Description'), ('unknown', 'Unknown')], db_index=True, default='story', max_length=20),
        ),
        migrations.AddField(
            model_name='importchunk',
            name='kind_confidence',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.CreateModel(
            name='RelationshipAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('alias', models.CharField(db_index=True, help_text='normalized, lowercased', max_length=80)),
                ('label', models.CharField(help_text="as written, e.g. 'Dad'", max_length=80)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='legacy.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Relationship aliases',
                'unique_together': {('user', 'alias')},
            },
        ),
    ]
