# Generated by Django 4.2.27 on 2026-07-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0012_importchunk_chunk_kind_importchunk_kind_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='source_type',
            field=models.CharField(choices=[('chatgpt', 'ChatGPT conversation'), ('claude', 'Claude conversation'), ('word', 'Word document'), ('pdf', 'PDF'), ('journal', 'Journal'), ('memoir', 'Existing memoir'), ('plain_text', 'Plain text'), ('gedcom', 'Genealogy (GEDCOM)'), ('other', 'Other')], default='other', max_length=12),
        ),
        migrations.AlterField(
            model_name='importchunk',
            name='chunk_kind',
            field=models.CharField(choices=[('story', 'Story'), ('journal_entry', 'Journal entry'), ('letter', 'Letter'), ('fact', 'Fact'), ('person', 'Person'), ('relationship_alias', 'Relationship alias'), ('place', 'Place'), ('milestone', 'Life milestone'), ('timeline_event', 'Timeline event'), ('quote', 'Quote'), ('artifact', 'Artifact'), ('media_ref', 'Media reference'), ('biography', 'Biography'), ('description', 'Description'), ('gedcom_person', 'Genealogy person'), ('gedcom_family', 'Genealogy family'), ('unknown', 'Needs clarification')], db_index=True, default='story', max_length=20),
        ),
    ]
