# Generated by Django 4.2.27 on 2026-07-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0013_alter_importbatch_source_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importchunk',
            name='chunk_kind',
            field=models.CharField(choices=[('story', 'Story'), ('journal_entry', 'Journal entry'), ('letter', 'Letter'), ('fact', 'Fact'), ('person', 'Person'), ('relationship_alias', 'Relationship alias'), ('place', 'Place'), ('milestone', 'Life milestone'), ('timeline_event', 'Timeline event'), ('quote', 'Quote'), ('artifact', 'Artifact'), ('media_ref', 'Media reference'), ('biography', 'Biography'), ('description', 'Description'), ('gedcom_person', 'Genealogy person'), ('gedcom_family', 'Genealogy family'), ('unknown', 'Not sure yet')], db_index=True, default='story', max_length=20),
        ),
    ]
