# Generated by Django 4.2.27 on 2026-07-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0014_alter_importchunk_chunk_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='importchunk',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
