# Generated by Django 4.2.27 on 2026-07-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0015_importchunk_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_self',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
