# Generated by Django 4.2.27 on 2026-07-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0016_person_is_self'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='rel_status',
            field=models.CharField(blank=True, choices=[('current', 'Current'), ('former', 'Former'), ('estranged', 'Estranged'), ('unknown', 'Unknown')], max_length=10),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.CharField(blank=True, help_text="e.g. 'father of', 'mentored by', 'married to'", max_length=120),
        ),
    ]
