# Generated by Django 4.2.27 on 2026-07-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0017_relationship_rel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationship',
            name='ended_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationship',
            name='started_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
