# Generated by Django 4.2.27 on 2026-07-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0020_backfill_dates_bind_self'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='relationship_category',
            field=models.CharField(choices=[('family', 'Family'), ('romantic', 'Romantic'), ('professional', 'Professional'), ('social', 'Social'), ('faith', 'Faith'), ('education', 'Education'), ('military', 'Military'), ('community', 'Community'), ('medical', 'Medical'), ('other', 'Other'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=14),
        ),
    ]
