# Generated by Django 4.2.27 on 2026-07-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0022_backfill_relationship_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='coverage',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
