# Generated by Django 4.2.27 on 2026-07-04 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legacy', '0023_importbatch_coverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreservedFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_via', models.CharField(choices=[('manual', 'Manual Entry'), ('ai_camera', 'AI Camera Scan'), ('import', 'Data Import'), ('api', 'API'), ('routine', 'Routine Completion')], default='manual', help_text='How this entry was created', max_length=20)),
                ('subject_label', models.CharField(blank=True, help_text='Who/what this is about when no Person is linked', max_length=200)),
                ('source_format', models.CharField(db_index=True, default='gedcom', max_length=20)),
                ('concept', models.CharField(db_index=True, help_text='Canonical concept: Career, Faith Journey, Military…', max_length=60)),
                ('label', models.CharField(help_text='Granular fact type: Occupation, Baptism…', max_length=80)),
                ('original_tag', models.CharField(help_text='Exact source tag, e.g. OCCU, _MILT', max_length=40)),
                ('value', models.CharField(blank=True, max_length=2000)),
                ('fact_date', models.CharField(blank=True, help_text='Raw source date string', max_length=80)),
                ('fact_place', models.CharField(blank=True, max_length=255)),
                ('original_data', models.JSONField(blank=True, default=dict)),
                ('fact_status', models.CharField(choices=[('awaiting', 'Awaiting canonical model'), ('unknown', 'Preserved — not yet recognized'), ('modeled', 'Migrated into Canonical Truth')], db_index=True, default='awaiting', max_length=12)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preserved_facts', to='legacy.person')),
                ('source_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preserved_facts', to='legacy.importbatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['concept', '-created_at'],
                'indexes': [models.Index(fields=['user', 'concept'], name='legacy_pres_user_id_371995_idx')],
            },
        ),
    ]
