# Generated by Django 4.2.27 on 2026-07-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0025_repair_inferred_marriages'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(blank=True, db_index=True, max_length=1),
        ),
    ]
