# Generated by Django 4.2.27 on 2026-07-05 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0027_backfill_sex_and_parent_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='is_refresh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='refresh_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refreshes', to='legacy.importbatch'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='refresh_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='relationship',
            name='user_edited',
            field=models.BooleanField(default=False),
        ),
    ]
