# Generated by Django 4.2.27 on 2026-07-05 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0032_rename_person_primary_photo_to_portrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='portrait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portrait_for_people', to='legacy.media'),
        ),
    ]
