# Generated by Django 4.2.27 on 2026-07-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0034_clarificationdismissal'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='coordinate_source',
            field=models.CharField(blank=True, choices=[('', 'Unknown / legacy'), ('esri', 'Esri geocoder'), ('pin', 'Dropped pin'), ('manual', 'Entered manually'), ('reviewed', 'Reviewed — kept')], default='', max_length=12),
        ),
    ]
