# Generated by Django 4.2.27 on 2026-07-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0035_place_coordinate_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifemilestone',
            name='description_plain',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='person',
            name='bio_plain',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='place',
            name='description_plain',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='relationship',
            name='notes_plain',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
